### PR TITLE
fix(net): Add outer timeouts for critical network operations to avoid hangs

### LINKED ISSUE #7772: bug: zebrad will not reconnect after an internet connection failure and restore
### What happened?

 I expected to see this happen: zebrad re-establishes a working connection after the internet connection is re-established.

Instead, this happened: zebrad continuously warns that 'chain updates have stalled, state height has not increased for # minutes'. Restarting the node fixes the issue.

### What were you doing when the issue happened?

Disconnecting and reconnecting the router attached to the devices from the internet (I'm filing this issue from the device in question at the same time zebrad is not reconnecting).

### Zebra logs

https://gist.github.com/autotunafish/30959aa159bf301c38af8f4480a206e2

peers
https://gist.github.com/autotunafish/79fdcdfcb20ce1b4eb6a27f24885babd

### Zebra Version

1.3.0

### Which operating systems does the issue happen on?

- [X] Linux
- [ ] macOS
- [ ] Windows
- [ ] Other OS

### OS details

Linux john-Satellite-L775D 5.4.0-164-generic #181-Ubuntu SMP Fri Sep 1 13:41:22 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by teor2345**
## Motivation

This is a quick fix for Zebra hanging rather than disconnecting when the peer set is empty. It prevents the requesting service side of the hang.

Close #7772

### Specifications

Sometimes a hang can happen if the called service doesn't correctly set up its waker (a bug), the request is really expensive, or the service is full of requests.

### Complex Code or Requirements

It seems unnecessary to have timeouts within service implementations, and in their callers. But it's very easy to add code that doesn't have a timeout, or has a subtle hang or slowness bug under some conditions. So we should move timeouts as far out of the service stack as possible, to include more code.

For now this PR just adds timeouts to the outermost layer of critical network services, or explains how they are already implemented.

## Solution

Timeouts:
- Add a timeout to syncer obtain, extend, and genesis block downloads and verifies
- Add a timeout to mempool crawls
- Add a timeout to mempool download and verify

Hang fixes:
- Remove a potential hang from address book requests
- Remove a potential hang when the lookahead limit is reached, then the pending blocks drop below the limit
- Remove a potential hang when the lookahead limit is reached, then the syncer is completely reset

Documentation:
- Explain why the inbound service never hangs

### Testing

- [x] TODO: Manually disconnect Zebra from the network for more than 10 minutes, then restore the network, and make sure that it reconnects within 10 minutes

## Review

This PR would be good to get in the release. It is low risk, because it just adds timeouts to existing code. (Or ignores inbound peers requests under load.)

### Reviewer Checklist

  - [ ] Will the PR name make sense to users?
    - [ ] Does it need extra CHANGELOG info? (new features, breaking changes, large changes)
  - [ ] Are the PR labels correct?
  - [ ] Does the code do what the ticket and PR says?
    - [ ] Does it change concurrent code, unsafe code, or consensus rules?
  - [ ] How do you know it works? Does it have tests?

## Follow Up Work

PR #7859 is a more complicated fix to an underlying peer set bug. But it should go in the next release to get more testing.

### CODE REVIEW

File: zebrad/src/components/sync.rs [hunk 1]
```diff
@@ -550,76 +557,103 @@ where
...
-                self.handle_block_response(rsp)?;
-            }
-            self.update_metrics();
+            // Avoid hangs due to service readiness or other internal operations
+            extra_hashes = timeout(BLOCK_VERIFY_TIMEOUT, self.try_to_sync_once(extra_hashes))
+                .await
+                .map_err(Into::into)
+                // TODO: replace with flatten() when it stabilises (#70142)
+                .and_then(convert::identity)?;
+        }
```
Comment (teor2345) [inline zebrad/src/components/sync.rs:578]: This is the only change in the diff for this loop, the rest is code movement and removing an indent.

Comment (teor2345) [inline zebrad/src/components/sync.rs:579]: This is the only change in the diff for this loop, the rest is code movement and removing an indent.

File: zebrad/src/components/sync.rs [hunk 2]
```diff
@@ -550,76 +557,103 @@ where
...
         self.update_metrics();
 
         while !self.prospective_tips.is_empty() || !extra_hashes.is_empty() {
-            // Check whether any block tasks are currently ready:
-            while let Poll::Ready(Some(rsp)) = futures::poll!(self.downloads.next()) {
-                self.handle_block_response(rsp)?;
-            }
-            self.update_metrics();
+            // Avoid hangs due to service readiness or other internal operations
+            extra_hashes = timeout(BLOCK_VERIFY_TIMEOUT, self.try_to_sync_once(extra_hashes))
```
Comment (arya2) [inline zebrad/src/components/sync.rs:574]: Optional/Nitpick: Could we leave a TODO for replacing this with a constant + some duration per future in `downloads`?

**Review by arya2 — DISMISSED** [review]
Looks good!

> Manually disconnect Zebra from the network for more than 10 minutes, then restore the network, and make sure that it reconnects within 10 minutes

This worked as expected.

**Comment by upbqdn** [comment]
> Manually disconnect Zebra from the network

I'm just wondering how you did this.

**Comment by teor2345** [comment]
> > Manually disconnect Zebra from the network
> 
> I'm just wondering how you did this.

I would remove the ethernet cable on the machine, or turn off wifi. If I wanted to keep working on other things on the same machine, I'd make the Linux firewall block or drop all packets into and out of a process.

Dropping all packets to or from the Zcash network port number doesn't work, because peers can have other ports.

Here is a GUI that does that:
https://github.com/evilsocket/opensnitch

Or you can use `zebrad &; iptables -m owner --pid-owner $! -j REJECT`:
https://stackoverflow.com/questions/4314163/create-iptables-rule-per-process-service

(This used to require another user account, but recent versions can do it by process ID.)

File: zebrad/src/components/sync.rs (hunk 2 above)
Comment (teor2345) [reply zebrad/src/components/sync.rs:574]: Some of these timeouts already exist, but based on the logs in the ticket, they aren't enough to stop all of the syncer hangs.

For example, until we merge this PR, the following code won't have a timeout:

Called by `download_and_verify()`:
https://github.com/ZcashFoundation/zebra/blob/b0555c0e61cd6576234e39170d1accdda342c293/zebrad/src/components/sync/downloads.rs#L333-L336

Called inside the spawned `downloads` future:
https://github.com/ZcashFoundation/zebra/blob/b0555c0e61cd6576234e39170d1accdda342c293/zebrad/src/components/sync/downloads.rs#L503-L514

Called by the `syncer` module:
https://github.com/ZcashFoundation/zebra/blob/b0555c0e61cd6576234e39170d1accdda342c293/zebrad/src/components/sync.rs#L629-L635

https://github.com/ZcashFoundation/zebra/blob/b0555c0e61cd6576234e39170d1accdda342c293/zebrad/src/components/sync.rs#L659

https://github.com/ZcashFoundation/zebra/blob/b0555c0e61cd6576234e39170d1accdda342c293/zebrad/src/components/sync.rs#L705

https://github.com/ZcashFoundation/zebra/blob/b0555c0e61cd6576234e39170d1accdda342c293/zebrad/src/components/sync.rs#L780

And similar code in `extend_tips()` and `request_genesis()`.

And any code we add in future without explicitly thinking about timeouts every time. So an outer wrapper seems easier to maintain.

Comment (teor2345) [reply zebrad/src/components/sync.rs:574]: I started trying to do each one, and by the time I got to changing the third low-level statement, I decided it was much easier to use an outer timeout.

**Comment by teor2345** [comment]
I pushed another significant hang fix in commit [b2385d9](https://github.com/ZcashFoundation/zebra/pull/7869/commits/b2385d932167bbf33bf2840e2b2af593529c26b2). 

Previously we weren't resetting the lookahead pause flag when we were above the lookahead limit, then the syncer was reset. We could also skip resetting the flag if the mutex was locked when the final block was downloaded.

This could be the cause of some of the hangs we see during syncing. It's better for a few blocks to wait for a short time than hang the entire syncer.

**Comment by teor2345** [comment]
> ERROR: failed to solve: rust:bullseye: unexpected status from HEAD request to https://registry-1.docker.io/v2/library/rust/manifests/bullseye: 429 Too Many Requests

https://github.com/ZcashFoundation/zebra/actions/runs/6700359536/job/18206164708?pr=7869#step:10:230

This rate-limit will be hit less if we fix #7816.

File: zebrad/src/components/sync.rs [hunk 3]
```diff
@@ -541,7 +548,8 @@ where
     /// following a fork. Either way, Zebra should attempt to obtain some more tips.
     ///
     /// Returns `Err` if there was an unrecoverable error and restarting the synchronization is
-    /// necessary.
+    /// necessary. This includes outer timeouts, where an entire syncing step takes an extrememly
```
Comment (upbqdn) [inline zebrad/src/components/sync.rs]:
```suggestion
    /// necessary. This includes outer timeouts, where an entire syncing step takes an extremely
```

File: zebrad/src/components/inbound.rs [hunk 4]
```diff
@@ -366,29 +375,56 @@ impl Service<zn::Request> for Inbound {
...
+                            debug!(
+                                "ignoring `Peers` request from remote peer because our address \
+                                 book has no available peers"
+                            );
+                        } else {
+                            info!(
+                                "ignoring `Peers` request from remote peer because our address \
+                                 book is busy"
+                            );
+                        }
```
Comment (upbqdn) [inline zebrad/src/components/inbound.rs]: Shouldn't we swap these two messages?

```suggestion
                        // Sometimes we don't know if the peer response will be empty until we've
                        // sanitized them.
                        if is_busy {
                            info!(
                                "ignoring `Peers` request from remote peer because our address \
                                 book is busy"
                            );
                        } else {
                            debug!(
                                "ignoring `Peers` request from remote peer because our address \
                                 book has no available peers"
                            );
                        }
```

**Review by arya2 — DISMISSED** [review]

File: zebrad/src/components/inbound.rs (hunk 4 above)
Comment (teor2345) [reply zebrad/src/components/inbound.rs]: Thank you, I got them the wrong way around because I got the logic wrong. (I was thinking `!is_busy`, and I got rid of the `!` but didn't swap the messages).

**Review by arya2 — DISMISSED** [review]

File: zebrad/Cargo.toml [hunk 5]
```diff
@@ -168,6 +168,7 @@ toml = "0.8.3"
 futures = "0.3.29"
 rayon = "1.7.0"
 tokio = { version = "1.33.0", features = ["time", "rt-multi-thread", "macros", "tracing", "signal"] }
+tokio-stream = { version = "0.1.14", features = ["time"] }
```
Comment (upbqdn) [inline zebrad/Cargo.toml:171]: I'd like a bit more time to finish reviewing this PR before it gets merged, so I'm opening this dummy comment. I'll resolve it manually soon.

Comment (teor2345) [reply zebrad/Cargo.toml:171]: We won't be doing anything with the release until after tomorrow's meeting about PR #7817, and after the [full sync](https://github.com/ZcashFoundation/zebra/actions/runs/6686504232) finishes.

So you have plenty of time.

**Comment by teor2345** [comment]
This failure looks like an infrastructure issue, compiling hung part of the way through:
```
Tue, 31 Oct 2023 21:07:01 GMT
   Compiling zebra-chain v1.0.0-beta.30 (/opt/zebrad/zebra-chain)
Tue, 31 Oct 2023 21:07:11 GMT
   Compiling metrics v0.21.1
Tue, 31 Oct 2023 21:07:12 GMT
   Compiling humantime-serde v1.1.1
Tue, 31 Oct 2023 21:07:12 GMT
   Compiling bincode v1.3.3
Tue, 31 Oct 2023 21:11:58 GMT
Error: The operation was canceled.
```

https://github.com/ZcashFoundation/zebra/actions/runs/6711815526/job/18240439236?pr=7869

**Comment by teor2345** [comment]
Here's a comment from Slack that might be useful here:

The network & state release freeze applies to high-risk PRs between the start of the last full sync and the release.

I'm thinking of allowing [fix(net): Add outer timeouts for critical network operations to avoid hangs](https://github.com/ZcashFoundation/zebra/pull/7869), because it helps fix an important network hang bug.

Here's my risk analysis of each change in the PR:

- adding timeouts to syncer and mempool crawler functions that usually don't time out
	- in the syncer a timeout resets the syncer, this is a standard operation
	- in the mempool it just skips the crawl and does another one after the rate-limit timer, the exact timing of crawls is not important
- removing a potential deadlock or hang from the block downloader, but we know it doesn't usually deadlock (though it might or might not be the source of the regular 10 minute hangs in the logs)
	- this might slightly delay some block verify futures, but that delay is much shorter than a hang
- removing a potential hang from the inbound service by ignoring the request, but we know it usually works
	- ignoring inbound requests is allowed by the protocol, and zcashd does it all the time, so we know Zebra and zcashd can handle it

I think the biggest risk here is a panic or hang, but I can't see how that would happen in these code changes. And if it does and it's frequent, it is likely to get picked up by the CI tests before we release.

File: zebrad/src/components/sync/downloads.rs [hunk 6]
```diff
@@ -471,17 +482,11 @@ where
...
-                        },
-                        Err(TryLockError::Poisoned(_)) => panic!("thread panicked while holding the past_lookahead_limit_sender mutex guard"),
-                        // We'll try allowing new downloads when we get the next block
-                        Err(TryLockError::WouldBlock) => {}
-                    }
+                    // Reset the watched value to false, since we're well under the limit.
+                    // We need to block here, because if we don't the syncer can hang.
+
+                    // But if Zebra is shutting down, ignore the send error.
+                    let _ = past_lookahead_limit_sender.lock().expect("thread panicked while holding the past_lookahead_limit_sender mutex guard").send(false);
```
Comment (teor2345) [inline zebrad/src/components/sync/downloads.rs:489]: Oops, I accidentally deleted this metric:

```suggestion
                    let _ = past_lookahead_limit_sender.lock().expect("thread panicked while holding the past_lookahead_limit_sender mutex guard").send(false);
                    metrics::counter!("sync.max.height.limit.reset.count", 1);
```

**Review by upbqdn — APPROVED** [review]
