### PR TITLE
Fix scriptCode serialization and sighash test vectors

### LINKED ISSUE #2197: scriptCode is being serialized incorrectly without size prefix
**Version**

`zebra-chain v1.0.0-alpha.8` commit 227757ae

**Platform**

`Linux 5.8.0-53-generic #60~20.04.1-Ubuntu SMP Thu May 6 09:52:46 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`

**Description**

After adding an interoperability sighash with librustzcash in #2165 the tests were failing. After investigating (thanks @str4d for the help) we found out that zebra is encoding the scriptCode without its prefix when calculating the sighash (e.g. the empty scriptCode was being serialized as the empty byte vector instead of `00`). This was offset by the tests including the prefix when passing the scriptCode, which would prevent the bug from being detected (e.g. the empty scriptCode was being passed as `00` instead of an empty byte vector)

I tried this:

Computing sighash with zebra and librustzcash.

I expected to see this happen: sighashes to be equal.

Instead, this happened: different sighashes.

**Commands**

Running the `test_vec243_2` and `test_vec243_3` tests in #2165 

**Logs**

```
---- transaction::tests::vectors::test_vec243_2 stdout ----

The application panicked (crashed).
Message:  assertion failed: `(left == right)`
  left: `"bbe6d84f57c56b29b914c694baaccb891297e961de3eb46c68e3c89c47b1a1db"`,
 right: `"a2282054497b08aa582a1b796dc6f29b4b4f6be96dc2da8b0bf905b524a212a8"`
Location: zebra-chain/src/transaction/tests/vectors.rs:761

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ SPANTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  
   0: zebra_chain::transaction::tests::vectors::compare_final with expected.len=64 buf.len=64
      at zebra-chain/src/transaction/tests/vectors.rs:739

Backtrace omitted.
Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.

---- transaction::tests::vectors::test_vec243_3 stdout ----

The application panicked (crashed).
Message:  assertion failed: `(left == right)`
  left: `"f3148f80dfab5e573d5edfe7a850f5fd39234f80b5429d3a57edcc11e34c585b"`,
 right: `"f27411aa9bd02879181c763a80bdb6f9ea9158f0de71757e7e12ed17760ebe3f"`
Location: zebra-chain/src/transaction/tests/vectors.rs:882

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ SPANTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  
   0: zebra_chain::transaction::tests::vectors::compare_final with expected.len=64 buf.len=64
      at zebra-chain/src/transaction/tests/vectors.rs:858

Backtrace omitted.
Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.

```

### PR DESCRIPTION
**Pull request by conradoplg**
## Motivation

The scriptCode was being serialized without the compact size prefix, and the test vectors included the prefix in the script, which cancelled each other.

## Solution

Make the raw bytes private to prevent using them directly.

Use zcash_serialize to serialize the script, which does include the compact size prefix.

Change the test vectors to correctly specify the scriptCode without the compact size prefix.

The code in this pull request has:
  - [x] Documentation Comments
  - [x] Unit Tests and Property Tests

## Review

This blocks #2165, but that is already being blocked too by librustzcash.

@teor2345 or @dconnolly may like to review it?

I'm not sure about the `raw_bytes()` method. It kinda defeats the purpose of making the underlying bytes private. But we need it because some other parts of the code need access to it. Is there a better way to handle it?

I'm also considering adding a test using https://github.com/zcash/zcash/blob/master/src/test/data/sighash.json but I wanted to created the PR soon. Let me know if that's a good idea and I'll work on it.

## Related Issues

Closes #2197 

## Follow Up Work

Sync #2165 after this is accepted.

### CODE REVIEW

File: zebra-chain/src/transaction/sighash.rs [hunk 1]
```diff
@@ -359,7 +359,7 @@ impl<'a> SigHasher<'a> {
             .as_ref()
             .expect("caller verifies input is not none");
 
-        writer.write_all(&lock_script.0)?;
+        lock_script.zcash_serialize(&mut writer)?;
```
Comment (dconnolly) [inline zebra-chain/src/transaction/sighash.rs:363]: 💯

File: zebra-chain/src/transaction/sighash.rs [hunk 2]
```diff
@@ -621,7 +621,7 @@ mod test {
         let transaction = ZIP143_2.zcash_deserialize_into::<Transaction>()?;
 
         let value = hex::decode("2f6e04963b4c0100")?.zcash_deserialize_into::<Amount<_>>()?;
-        let lock_script = Script(hex::decode("0153")?);
+        let lock_script = Script::new(hex::decode("53")?);
```
Comment (dconnolly) [inline zebra-chain/src/transaction/sighash.rs]: 👍

File: zebra-chain/src/transaction/sighash.rs [hunk 3]
```diff
@@ -782,7 +782,7 @@ mod test {
         let transaction = ZIP243_2.zcash_deserialize_into::<Transaction>()?;
 
         let value = hex::decode("adedf02996510200")?.zcash_deserialize_into::<Amount<_>>()?;
-        let lock_script = Script(hex::decode("00")?);
+        let lock_script = Script::new(vec![]);
```
Comment (dconnolly) [inline zebra-chain/src/transaction/sighash.rs]: 👍

File: zebra-chain/src/transaction/sighash.rs [hunk 4]
```diff
@@ -880,8 +880,8 @@ mod test {
         let transaction = ZIP243_3.zcash_deserialize_into::<Transaction>()?;
 
         let value = hex::decode("80f0fa0200000000")?.zcash_deserialize_into::<Amount<_>>()?;
-        let lock_script = Script(hex::decode(
-            "1976a914507173527b4c3318a2aecd793bf1cfed705950cf88ac",
+        let lock_script = Script::new(hex::decode(
+            "76a914507173527b4c3318a2aecd793bf1cfed705950cf88ac",
         )?);
```
Comment (dconnolly) [inline zebra-chain/src/transaction/sighash.rs]: Looking at this knowing the bug, this is so funny now :P

File: zebra-chain/src/transparent/script.rs [hunk 5]
```diff
@@ -12,7 +12,20 @@ use std::{fmt, io};
...
+    /// The raw bytes must not contain the compact size prefix.
+    pub fn new(raw_bytes: Vec<u8>) -> Self {
+        Script(raw_bytes)
+    }
+
+    /// Return the raw bytes of the script without the compact size prefix.
+    pub fn raw_bytes(&self) -> &Vec<u8> {
+        &self.0
+    }
+}
```
Comment (dconnolly) [inline zebra-chain/src/transparent/script.rs]: Should these be a `From` impl? @teor2345 @jvff

File: zebra-script/src/lib.rs [hunk 6]
```diff
@@ -366,7 +366,7 @@ mod tests {
         let amount = 210 * coin;
         let output = transparent::Output {
             value: amount.try_into()?,
-            lock_script: transparent::Script(SCRIPT_PUBKEY.clone()),
+            lock_script: transparent::Script::new(SCRIPT_PUBKEY.clone()),
```
Comment (dconnolly) [inline zebra-script/src/lib.rs]: 👍

File: zebra-script/src/lib.rs [hunk 7]
```diff
@@ -357,7 +357,7 @@ mod tests {
         let amount = 211 * coin;
         let output = transparent::Output {
             value: amount.try_into()?,
-            lock_script: transparent::Script(SCRIPT_PUBKEY.clone()),
+            lock_script: transparent::Script::new(SCRIPT_PUBKEY.clone()),
```
Comment (dconnolly) [inline zebra-script/src/lib.rs]: 👍

File: zebra-script/src/lib.rs [hunk 8]
```diff
@@ -332,7 +332,7 @@ mod tests {
         let amount = 212 * coin;
         let output = transparent::Output {
             value: amount.try_into()?,
-            lock_script: transparent::Script(SCRIPT_PUBKEY.clone()),
+            lock_script: transparent::Script::new(SCRIPT_PUBKEY.clone()),
```
Comment (dconnolly) [inline zebra-script/src/lib.rs]: 👍

File: zebra-script/src/lib.rs [hunk 9]
```diff
@@ -323,7 +323,7 @@ mod tests {
         let amount = 211 * coin;
         let output = transparent::Output {
             value: amount.try_into()?,
-            lock_script: transparent::Script(SCRIPT_PUBKEY.clone()),
+            lock_script: transparent::Script::new(SCRIPT_PUBKEY.clone()),
```
Comment (dconnolly) [inline zebra-script/src/lib.rs]: 👍

File: zebra-script/src/lib.rs [hunk 10]
```diff
@@ -289,14 +289,14 @@ mod tests {
...
         };
         verifier.is_valid(branch_id, (input_index, output))?;
 
         let amount = 211 * coin;
         let output = transparent::Output {
             value: amount.try_into()?,
-            lock_script: transparent::Script(SCRIPT_PUBKEY.clone()),
+            lock_script: transparent::Script::new(SCRIPT_PUBKEY.clone()),
```
Comment (dconnolly) [inline zebra-script/src/lib.rs]: 👍

File: zebra-script/src/lib.rs [hunk 11]
```diff
@@ -289,14 +289,14 @@ mod tests {
         let amount = 212 * coin;
         let output = transparent::Output {
             value: amount.try_into()?,
-            lock_script: transparent::Script(SCRIPT_PUBKEY.clone()),
+            lock_script: transparent::Script::new(SCRIPT_PUBKEY.clone()),
```
Comment (dconnolly) [inline zebra-script/src/lib.rs]: 👍

File: zebra-script/src/lib.rs [hunk 12]
```diff
@@ -257,14 +257,14 @@ mod tests {
...
```
Comment (dconnolly) [inline zebra-script/src/lib.rs]: 👍

File: zebra-script/src/lib.rs [hunk 13]
```diff
@@ -257,14 +257,14 @@ mod tests {
...
         };
         verifier.is_valid(branch_id, (input_index, output))?;
 
         let amount = 212 * coin;
         let output = transparent::Output {
             value: amount.try_into()?,
-            lock_script: transparent::Script(SCRIPT_PUBKEY.clone()),
+            lock_script: transparent::Script::new(SCRIPT_PUBKEY.clone()),
```
Comment (dconnolly) [inline zebra-script/src/lib.rs]: 👍

File: zebra-script/src/lib.rs [hunk 14]
```diff
@@ -224,7 +224,7 @@ mod tests {
         let amount = 211 * coin;
         let output = transparent::Output {
             value: amount.try_into()?,
-            lock_script: transparent::Script(SCRIPT_PUBKEY.clone()),
+            lock_script: transparent::Script::new(SCRIPT_PUBKEY.clone()),
```
Comment (dconnolly) [inline zebra-script/src/lib.rs]: 👍

File: zebra-script/src/lib.rs [hunk 15]
```diff
@@ -201,7 +201,7 @@ mod tests {
         let amount = 212 * coin;
         let output = transparent::Output {
             value: amount.try_into()?,
-            lock_script: transparent::Script(SCRIPT_PUBKEY.clone()),
+            lock_script: transparent::Script::new(SCRIPT_PUBKEY.clone()),
```
Comment (dconnolly) [inline zebra-script/src/lib.rs]: 👍

**Comment by dconnolly** [comment]
> I'm also considering adding a test using https://github.com/zcash/zcash/blob/master/src/test/data/sighash.json but I wanted to created the PR soon. Let me know if that's a good idea and I'll work on it.

Great idea! Yes please 🙏

File: zebra-chain/src/transparent/script.rs (hunk 5 above)
Comment (teor2345) [reply zebra-chain/src/transparent/script.rs]: Not really, we want the `raw` to be explicit - this isn't the serialization format, and that should be very clear in any code.

File: zebra-chain/src/transparent/script.rs [hunk 16]
```diff
@@ -12,7 +12,20 @@ use std::{fmt, io};
     any(test, feature = "proptest-impl"),
     derive(proptest_derive::Arbitrary)
 )]
-pub struct Script(pub Vec<u8>);
+pub struct Script(Vec<u8>);
+
+impl Script {
+    /// Create a new Bitcoin script from its raw bytes.
+    /// The raw bytes must not contain the compact size prefix.
+    pub fn new(raw_bytes: Vec<u8>) -> Self {
```
Comment (teor2345) [inline zebra-chain/src/transparent/script.rs]: Can we be explicit that these are raw bytes, not Zcash serialization?
Also can we restrict these functions to the crate (`pub(crate) fn`), the transparent module (`pub(super) fn`) or the script module (`fn`)?
Can we accept a slice here, rather than a specific collection type?

```suggestion
    fn new_from_raw(raw_bytes: &[u8]) -> Self {
```

File: zebra-chain/src/transparent/script.rs [hunk 17]
```diff
@@ -12,7 +12,20 @@ use std::{fmt, io};
...
+        Script(raw_bytes)
+    }
+
+    /// Return the raw bytes of the script without the compact size prefix.
+    pub fn raw_bytes(&self) -> &Vec<u8> {
```
Comment (teor2345) [inline zebra-chain/src/transparent/script.rs]: Similarly, can we restrict this function to a smaller scope?
Can we return a slice here, rather than a specific collection type?

```suggestion
    fn raw_bytes(&self) -> &[u8] {
```

File: zebra-chain/src/transaction/sighash.rs (hunk 3 above)
Comment (teor2345) [inline zebra-chain/src/transaction/sighash.rs]: Can we combine the `value` and `lock_script` bytes into a single bytes array, and `zcash_deserialize` them into an `Output`?

That way, we make sure our deserialization and sighash are compatible.

If this works, let's make the same changes for all these unit tests.

**Review by teor2345 — CHANGES_REQUESTED** [review]
This looks really good, thanks for finding and fixing this bug!

I have some suggestions for improving the tests, and tweaking the new `Script` interfaces.

File: zebra-chain/src/transparent/script.rs (hunk 17 above)
Comment (dconnolly) [inline zebra-chain/src/transparent/script.rs]: We might want to call this `as_raw_bytes` to follow the Rust API Guidelines? https://rust-lang.github.io/api-guidelines/naming.html#c-conv

Comment (teor2345) [reply zebra-chain/src/transparent/script.rs]: Seems good to me, let's explicitly add a correctness note for serialization?

```rust
/// # Correctness
///
/// These raw bytes do not have a length prefix.
///
/// The Zcash serialization format requires a length prefix, use `zcash_serialize`
/// and `zcash_deserilize` to create byte data with a length prefix.
```

File: zebra-chain/src/transaction/sighash.rs (hunk 3 above)
Comment (conradoplg) [reply zebra-chain/src/transaction/sighash.rs]: I'm not sure how helpful would that be... In the test vectors they are listed separately, so I'd have to serialize them by hand to include in the test

File: zebra-chain/src/transparent/script.rs (hunk 16 above)
Comment (conradoplg) [reply zebra-chain/src/transparent/script.rs]: Changed the name and return type.

About the  visibility, good question. It's possible to make it `pub(crate)`, but consider the API: the `Transaction::sighash` method (which is `pub`) receives a `transparent::Output` which in turns needs a `Script`. Therefore, any crate users must be able to construct a `Script` in other to use the method.

(The reason that it is possible to currently get away with `pub(crate)` is that zebra never seems to call `Transaction::sighash` for transparent inputs, using `zebra_script` instead. But that could change in the future?)

File: zebra-chain/src/transparent/script.rs (hunk 17 above)
Comment (conradoplg) [reply zebra-chain/src/transparent/script.rs]: Changed to return a slice.

Unfortunately it's not possible to restrict it since it is used by `zebra_script`.

Comment (conradoplg) [reply zebra-chain/src/transparent/script.rs]: Great suggestion! Changed the name and added the comment.

File: zebra-chain/src/transparent/script.rs (hunk 5 above)
Comment (conradoplg) [reply zebra-chain/src/transparent/script.rs]: Exactly, my intention was to prevent someone using it "by accident" :+1:

**Comment by conradoplg** [comment]
> > I'm also considering adding a test using https://github.com/zcash/zcash/blob/master/src/test/data/sighash.json but I wanted to created the PR soon. Let me know if that's a good idea and I'll work on it.
> 
> Great idea! Yes please

I implemented that but run into a bunch of issues which I commented over Discord. Could we move this to a separate issue to prevent blocking this one?

File: zebra-chain/src/transaction/sighash.rs (hunk 3 above)
Comment (teor2345) [reply zebra-chain/src/transaction/sighash.rs]: Ah right. That seems like an issue with the test vectors, but not something we can or should fix.

Our integration tests should catch issues like this anyway.

**Comment by teor2345** [comment]
> > > I'm also considering adding a test using https://github.com/zcash/zcash/blob/master/src/test/data/sighash.json but I wanted to created the PR soon. Let me know if that's a good idea and I'll work on it.
> > 
> > 
> > Great idea! Yes please
> 
> I implemented that but run into a bunch of issues which I commented over Discord. Could we move this to a separate issue to prevent blocking this one?

Please feel free to split off new issues and PRs as needed.

File: zebra-chain/src/transparent/script.rs (hunk 16 above)
Comment (teor2345) [reply zebra-chain/src/transparent/script.rs]: Ah right, don't worry about the visibility then - it's a type constructor.

**Review by teor2345 — APPROVED** [review]
Looks good to me, feel free to merge when you think it's done

File: zebra-chain/src/transparent/script.rs [hunk 18]
```diff
@@ -12,7 +12,26 @@ use std::{fmt, io};
...
+    /// Return the raw bytes of the script without the length prefix.
+    ///
+    /// # Correctness
+    ///
+    /// These raw bytes do not have a length prefix.
+    /// The Zcash serialization format requires a length prefix; use `zcash_serialize`
+    /// and `zcash_deserialize` to create byte data with a length prefix.
+    pub fn as_raw_bytes(&self) -> &[u8] {
+        &self.0
+    }
```
Comment (dconnolly) [inline zebra-chain/src/transparent/script.rs:33]: 👍

**Review by dconnolly — APPROVED** [review]
