### PR TITLE
test: add missing coverage for mempool input standardness checks

### LINKED ISSUE #10358: test: add missing coverage for mempool input standardness checks
#10314 added `are_inputs_standard()` and `p2sh_sigop_count()` to the mempool policy layer. The existing tests cover basic rejection paths but leave several branches untested.

Missing coverage:

- `are_inputs_standard()` happy path — no test confirms a transaction with valid standard inputs is accepted
- Wrong stack depth — a scriptSig with the wrong number of pushes for its script type (e.g. P2PKH with 3 pushes instead of 2) should be rejected; this branch is untested
- P2SH sigops over limit via `p2sh_sigop_count()` — the existing `mempool_reject_too_many_sigops` only sets `legacy_sigop_count` directly and never exercises `p2sh_sigop_count()`
- P2SH accepted with a standard redeemed script — the P2SH-specific branch in `are_inputs_standard()` has no positive test
- `count_script_push_ops()` with multi-byte push opcodes (`OP_PUSHDATA2`, `OP_PUSHDATA4`) — current unit tests only cover single-byte pushes and empty input

Suggested location: new functions in `zebrad/src/components/mempool/tests/vector.rs` for integration tests, plus a few lines in `zebrad/src/components/mempool/storage/policy.rs` for the unit test gaps.

_Test coverage analysis by GitHub Copilot._

### PR DESCRIPTION
**Pull request by zmanian**
## Motivation

Addresses review feedback from #10314 requesting additional test coverage for the mempool input standardness policy functions. Test gaps were tracked in #10358.

## Solution

Adds 13 new unit tests in `zebrad/src/components/mempool/storage/policy.rs` covering:

### `count_script_push_ops()`
- **OP_PUSHDATA1**: Verifies multi-byte push opcode (0x4c) with 1-byte length
- **OP_PUSHDATA2**: Verifies multi-byte push opcode (0x4d) with 2-byte length
- **OP_PUSHDATA4**: Verifies multi-byte push opcode (0x4e) with 4-byte length
- **Mixed push types**: Combines OP_0, OP_PUSHBYTES, and OP_PUSHDATA1

### `are_inputs_standard()`
- **Happy path**: Valid P2PKH input with correct 2-push scriptSig accepted
- **Wrong stack depth (too many)**: P2PKH with 3 pushes rejected
- **Wrong stack depth (too few)**: P2PKH with 1 push rejected
- **Non-standard spent output**: Input spending a non-standard script rejected
- **P2SH with standard redeemed script**: P2SH wrapping P2PKH with correct depth accepted
- **P2SH with too many sigops**: Redeemed script with 16 OP_CHECKSIG (> MAX_P2SH_SIGOPS) rejected
- **P2SH with non-standard low sigops**: Redeemed script with exactly 15 OP_CHECKSIG accepted

### `p2sh_sigop_count()`
- **P2SH input**: Returns correct sigop count from redeemed script
- **Non-P2SH input**: Returns 0 for P2PKH spent output

All tests construct transactions directly using `Transaction::V4` with controlled inputs/outputs and dummy scripts, avoiding the need for full mempool service setup.

## Test Evidence

```
running 18 tests
test components::mempool::storage::policy::tests::... ok (all 18)
test result: ok. 18 passed; 0 failed
```

## Dependencies

This PR is based on #10314 (which introduces the `policy.rs` module).

Closes #10358

## AI Disclosure

Claude Code was used to implement the tests based on the coverage gaps identified in #10358. All tests were verified locally.

### CODE REVIEW

**Comment by oxarbitrage** [comment]
Please rebase to reduce diff. Also fix conflics where needed. Thanks.

**Comment by zmanian** [comment]
Rebased onto main and squashed into a single commit. The diff is now minimal (3 files, +493/-8) — only the test additions and defensive improvements on top of the merged #10314.

File: zebrad/src/components/mempool/storage.rs [hunk 1]
```diff
@@ -130,7 +130,7 @@ pub enum RejectionError {
 }
 
 /// Non-standard transaction error.
-#[derive(Error, Clone, Debug, PartialEq, Eq)]
+#[derive(Error, Clone, Debug, PartialEq, Eq, Hash)]
```
Comment (oxarbitrage) [inline zebrad/src/components/mempool/storage.rs]:
```suggestion
#[derive(Error, Clone, Debug, PartialEq, Eq)]
```
Not needed.

File: zebrad/src/components/mempool/storage/tests/vectors.rs [hunk 2]
```diff
@@ -407,8 +407,11 @@ fn mempool_removes_dependent_transactions() -> Result<()> {
 
 // ---- Policy function unit tests ----
 
+// Note: p2pkh_lock_script and p2sh_lock_script are intentionally duplicated from
+// policy::tests because Rust's #[cfg(test)] module boundaries prevent sharing.
```
Comment (oxarbitrage) [inline zebrad/src/components/mempool/storage/tests/vectors.rs]: Consider moving `p2pkh_lock_script`, `p2sh_lock_script`, and `p2pk_lock_script` out of `mod tests` in `policy.rs` to module level as `#[cfg(test)] pub(super)` functions.

**Review by oxarbitrage — COMMENTED** [review]
They look good, thanks. Minor suggestions added.

File: zebrad/src/components/mempool/storage.rs (hunk 1 above)
Comment (zmanian) [reply zebrad/src/components/mempool/storage.rs]: Done -- removed the `Hash` derive.

File: zebrad/src/components/mempool/storage/tests/vectors.rs (hunk 2 above)
Comment (zmanian) [reply zebrad/src/components/mempool/storage/tests/vectors.rs]: Good call. Moved `p2pkh_lock_script`, `p2sh_lock_script`, and `p2pk_lock_script` to module level in `policy.rs` as `#[cfg(test)] pub(super)` functions. `vectors.rs` now imports them instead of duplicating.

**Review by oxarbitrage — DISMISSED** [review]
Looks good, thanks.

**Comment by oxarbitrage** [comment]
@zmanian can you fix clippy and rustfmt for this PR ? Thanks.

**Comment by zmanian** [comment]
Fixed -- sorted imports alphabetically to pass rustfmt. Clippy is clean as well.

**Review by oxarbitrage — APPROVED** [review]
