### PR TITLE
fix: Inconsistent Docs for Downloading ZKP Params

### LINKED ISSUE #6340: [NCC-E005955-WVM] `zebra-consensus`: Off-by-One Errors and Inconsistent Usage of `PARAMETER_DOWNLOAD_MAX_RETRIES`
## Impact

The `PARAMETER_DOWNLOAD_MAX_RETRIES` may not behave as expected due to a potential off-by-one error.

## Description

The parameter `PARAMETER_DOWNLOAD_MAX_RETRIES` is defined in [zebra-consensus/src/
primitives/groth16/params.rs](https://github.com/ZcashFoundation/zebra/blob/audit-v1.0.0-rc.0/zebra-consensus/src/primitives/groth16/params.rs):

https://github.com/ZcashFoundation/zebra/blob/5a88fe783c4c219beb94362b78974555fa1a398b/zebra-consensus/src/primitives/groth16/params.rs#L18-L22

As noted, this parameter represents the number of times to retry the download of groth16 parameters. However, later in the same file the following description is given:

https://github.com/ZcashFoundation/zebra/blob/5a88fe783c4c219beb94362b78974555fa1a398b/zebra-consensus/src/primitives/groth16/params.rs#L63-L70

Here, the parameter is claimed to specify the number of download attempts, not the number of _retry_ attempts. The implementation matches the described behavior and uses this parameter to cap the total number of download attempts; see `retry_download_sapling_parameters()` :

https://github.com/ZcashFoundation/zebra/blob/5a88fe783c4c219beb94362b78974555fa1a398b/zebra-consensus/src/primitives/groth16/params.rs#L132-L144

The same behavior is implemented for `retry_download_sprout_parameters()` . Documentation for both of these functions is inconsistent:

https://github.com/ZcashFoundation/zebra/blob/5a88fe783c4c219beb94362b78974555fa1a398b/zebra-consensus/src/primitives/groth16/params.rs#L120-L125

For example, consider a case where `PARAMETER_DOWNLOAD_MAX_RETRIES` = 1 . Then this
comment specifies the following: 

1. “Download Sapling parameters and retry 1 if it fails.” – This should likely read “1 time(s)” if it fails (currently missing the word “time”). This description matches the implied behavior based on the parameter name.
2. Panics “After 1 failed download attempts” – In other words, it will not retry 1 time. This description matches the implemented behavior.

For consistency, the parameter should be uniformly treated as the maximum number of download attempts, or the maximum number of retry attempts, and treated appropriately in all documentation and code.

## Recommendation

Revise documentation, parameter names, and implemented behavior to correctly capture the behavior of `PARAMETER_DOWNLOAD_MAX_RETRIES`.

## Location

[zebra-consensus/src/primitives/groth16/params.rs](https://github.com/ZcashFoundation/zebra/blob/audit-v1.0.0-rc.0/zebra-consensus/src/primitives/groth16/params.rs)

### PR DESCRIPTION
**Pull request by upbqdn**
## Motivation

Close #6340.

## Solution

This PR:

- adjusts the implementation so that `PARAMETER_DOWNLOAD_MAX_RETRIES` is regarded as the max number of _retries_ instead of _attempts_;
- removes the prefix `retry_` from functions that download the parameters;
- cleans up the docs a bit.

### Reviewer Checklist

  - [ ] Will the PR name make sense to users?
    - [ ] Does it need extra CHANGELOG info? (new features, breaking changes, large changes)
  - [ ] Are the PR labels correct?
  - [ ] Does the code do what the ticket and PR says?
    - [ ] Does it change concurrent code, unsafe code, or consensus rules?
  - [ ] How do you know it works? Does it have tests?

### CODE REVIEW

File: zebra-consensus/src/primitives/groth16/params.rs [hunk 1]
```diff
@@ -15,19 +15,19 @@ use crate::BoxError;
...
     ///
-    /// When this static is accessed:
-    /// - the parameters are downloaded if needed, then cached to a shared directory,
-    /// - the file hashes are checked, for both newly downloaded and previously cached files,
-    /// - the parameters are loaded into Zebra.
+    /// This static is accessed when:
+    ///
+    /// - Zebra needs to download and cache the parameters to a shared directory, or
+    /// - Zebra checks the file hashes for both newly downloaded and previously cached files, or
+    /// - Zebra loads the parameters.
```
Comment (arya2) [inline zebra-consensus/src/primitives/groth16/params.rs]: Nitpick/Optional:

```suggestion
    /// This static is accessed when Zebra:
    ///
    /// - needs to download and cache the parameters to a shared directory, or
    /// - checks the file hashes for both newly downloaded and previously cached files, or
    /// - loads the parameters.
```

File: zebra-consensus/src/primitives/groth16/params.rs [hunk 2]
```diff
@@ -137,10 +136,10 @@ impl Groth16Parameters {
                 sapling_output_path,
             ) {
                 retries += 1;
-                if retries >= PARAMETER_DOWNLOAD_MAX_RETRIES {
+                if retries >= PARAMETER_DOWNLOAD_MAX_ATTEMPTS {
```
Comment (arya2) [inline zebra-consensus/src/primitives/groth16/params.rs]: Nitpick: Update variable name

```suggestion
                if num_attempts >= PARAMETER_DOWNLOAD_MAX_ATTEMPTS {
```

File: zebra-consensus/src/primitives/groth16/params.rs [hunk 3]
```diff
@@ -173,23 +172,23 @@ impl Groth16Parameters {
...
+    /// - After [`PARAMETER_DOWNLOAD_MAX_ATTEMPTS`] failed download attempts.
+    fn download_sprout_parameters(sprout_path: &Path) {
         if !sprout_path.exists() {
             tracing::info!("downloading Zcash Sprout parameters");
 
             let mut retries = 0;
             while let Err(error) = Groth16Parameters::download_sprout_parameters_once(sprout_path) {
                 retries += 1;
-                if retries >= PARAMETER_DOWNLOAD_MAX_RETRIES {
+                if retries >= PARAMETER_DOWNLOAD_MAX_ATTEMPTS {
```
Comment (arya2) [inline zebra-consensus/src/primitives/groth16/params.rs]: Nitpick: Update variable name

```suggestion
                if num_attempts >= PARAMETER_DOWNLOAD_MAX_ATTEMPTS {
```

File: zebra-consensus/src/primitives/groth16/params.rs [hunk 4]
```diff
@@ -15,19 +15,19 @@ use crate::BoxError;
...
 pub const PARAMETER_DOWNLOAD_TIMEOUT: u64 = 60 * 60;
 
-/// The maximum number of times to retry download parameters.
+/// The maximum number of times Zebra tries to download the parameters.
 ///
-/// Zebra will retry to download Sprout of Sapling parameters only if they
-/// failed for whatever reason.
-pub const PARAMETER_DOWNLOAD_MAX_RETRIES: usize = 3;
+/// Zebra will retry the download only if the previous attempt fails.
+pub const PARAMETER_DOWNLOAD_MAX_ATTEMPTS: usize = 3;
```
Comment (arya2) [inline zebra-consensus/src/primitives/groth16/params.rs]: Optional:

Use retries and make `retries + 1` attempts.

**Review by arya2 — DISMISSED** [review]
This looks great, thank you!

I may remember us saying we want to keep these as `*_RETRIES` and update the code to make `retries + 1` attempts for fixes to this finding (e.g. PR [#6460](https://github.com/ZcashFoundation/zebra/pull/6460/files#diff-1b43a508fa9f5834c283c789a7e38d9f799471988f0c2daef108c273773603f8R200)), but I'm not sure and that's not a blocker in any case.

File: zebra-consensus/src/primitives/groth16/params.rs (hunk 4 above)
Comment (upbqdn) [reply zebra-consensus/src/primitives/groth16/params.rs]: Done in [4208704](https://github.com/ZcashFoundation/zebra/pull/6464/commits/4208704c92c446422358baa3b89fa561473fff04).

File: zebra-consensus/src/primitives/groth16/params.rs (hunk 2 above)
Comment (upbqdn) [reply zebra-consensus/src/primitives/groth16/params.rs]: Well spotted; however, I switched back to _retries_, so I'm closing this as resolved without applying the suggestion.

File: zebra-consensus/src/primitives/groth16/params.rs (hunk 3 above)
Comment (upbqdn) [reply zebra-consensus/src/primitives/groth16/params.rs]: Well spotted! However, I switched back to _retries_, so I'm resolving this without applying the suggestion.

**Comment by upbqdn** [comment]
> I may remember us saying we want to keep these as *_RETRIES and update the code to make retries + 1 attempts for fixes to this finding (e.g. PR [#6460](https://github.com/ZcashFoundation/zebra/pull/6460/files#diff-1b43a508fa9f5834c283c789a7e38d9f799471988f0c2daef108c273773603f8R200))

Thanks for pointing that out, I wasn't aware of that. I switched back to _retries_, adjusted the code, and edited the PR description.

File: zebra-consensus/src/primitives/groth16/params.rs [hunk 5]
```diff
@@ -137,7 +136,7 @@ impl Groth16Parameters {
                 sapling_output_path,
             ) {
                 retries += 1;
-                if retries >= PARAMETER_DOWNLOAD_MAX_RETRIES {
+                if retries > PARAMETER_DOWNLOAD_MAX_RETRIES {
```
Comment (arya2) [inline zebra-consensus/src/primitives/groth16/params.rs:139]: Optional: increment retries after the if statement so that `retries` is `attempts - 1` when the original condition is checked instead of updating the condition.

**Review by arya2 — APPROVED** [review]
Thank you for making the change to retries!

File: zebra-consensus/src/primitives/groth16/params.rs (hunk 5 above)
Comment (upbqdn) [reply zebra-consensus/src/primitives/groth16/params.rs:139]: I'd say the current implementation follows the domain logic well:

- When we enter https://github.com/zcashfoundation/zebra/blob/4208704c92c446422358baa3b89fa561473fff04/zebra-consensus/src/primitives/groth16/params.rs#L186, we already know the initial attempt failed, and
- we can regard the initial attempt as the zeroth retry.
- We then count the actual retries starting at one, and
- we increment the counter after we've done a retry (not when we're about to do one), so
- we panic once we exceed the max number of retries (not when we're at the limit).
