### PR TITLE
Security: Stop panicking on invalid reserved orchard::Flags bits

### LINKED ISSUE #2263: Security: Stop panicking when the reserved bits of orchard::Flags are non-zero
## Motivation

Zebra panics via `unwrap` when the reserved bits of `orchard::Flags` are non-zero.

Also, the consensus rules were updated to require that reserved bits of `orchard::Flags` are all zero.

### Specifications

"In a version 5 transaction, the reserved bits 2..7 of the flags Orchard field MUST be zero."
https://zips.z.cash/protocol/protocol.pdf#txnencodingandconsensus

### Designs

The `orchard::Flags` design was implemented in PR #2116:
https://github.com/ZcashFoundation/zebra/blob/main/book/src/dev/rfcs/0010-v5-transaction.md#adding-orchard-flags

But the implementation had a security issue, because the design didn't cover parsing errors.

### API Reference

> pub fn from_bits(bits: u32) -> Option<Flags>
> Convert from underlying bit representation, unless that representation contains bits that do not correspond to a flag.

https://docs.rs/bitflags/1.2.1/bitflags/example_generated/struct.Flags.html#method.from_bits

## Solution

- [ ] Update the RFC to include the new consensus rule
- [ ] Return an error during deserialization when any reserved bits of `orchard::Flags` are non-zero
  - quote the consensus rule in the function docs and link to the spec
- [ ] Add a proptest that parses an arbitrary flag byte
  - when all reserved bits of `orchard::Flags` are zero, check that deserialization succeeds 
  - when any reserved bits of `orchard::Flags` are non-zero, check that deserialization fails with an error

### PR DESCRIPTION
**Pull request by oxarbitrage**
## Motivation

We need to make sure the consensus rule about the reserved bits of the `orchard::Flags` for transactions V5 is present in Zebra. https://github.com/ZcashFoundation/zebra/issues/2263

In addition there is an `unwrap()` in the deserialization of the `orchard::Flags` that needs to be fixed. 

### Specifications

https://zips.z.cash/protocol/protocol.pdf#txnencodingandconsensus

"In a version 5 transaction, the reserved bits 2..7 of the flagsOrchard field MUST be zero."

### Designs

Also in this PR a note about this consensus rule is added to the orchard flags section: https://github.com/ZcashFoundation/zebra/blob/main/book/src/dev/rfcs/0010-v5-transaction.md#adding-orchard-flags 

## Solution

Only deserialize valid flags and prop test them. 

## Review

As it is a consensus rule will be good if @teor2345 can review, the code in general can be reviewed by anyone.

### Reviewer Checklist

  - [ ] Code implements Specs and Designs
  - [ ] Tests for Expected Behaviour
  - [ ] Tests for Errors

### CODE REVIEW

File: zebra-chain/src/orchard/tests/prop.rs [hunk 1]
```diff
@@ -0,0 +1,43 @@
...
+                flag == orchard::Flags::empty()
+                || flag == orchard::Flags::ENABLE_SPENDS
+                || flag == orchard::Flags::ENABLE_OUTPUTS
+                || flag == orchard::Flags::ENABLE_SPENDS | orchard::Flags::ENABLE_OUTPUTS);
+        }
+        else {
+            prop_assert!(binary_repr.len() > 2);
+            prop_assert_eq!(error_catch, "parse error: invalid orchard flags");
+        }
+    }
```
Comment (jvff) [inline zebra-chain/src/orchard/tests/prop.rs]: I'm not sure if this is a good suggestion, but maybe it could help with ideas to make it simpler:
```suggestion
        let invalid_bits_mask = !orchard::Flags::all().bits();
        match orchard::Flags::from_bits(flags) {
            Some(valid_flags) => {
                prop_assert_eq!(maybe_deserialized, Ok(valid_flags));
                prop_assert_eq!(flags & invalid_bits_mask, 0);
            }
            None => {
                prop_assert_eq!(maybe_deserialized, Err(SerializationError::Parse("invalid orchard flags")));
                prop_assert_ne!(flags & invalid_bits_mask, 0);
            }
        }
    }
```

**Review by jvff — COMMENTED** [review]
I think it looks good, I just added a comment about the proptest, because I thought of another way of doing the checks, but I'm not sure if it's a clearer option :thinking:

File: zebra-chain/src/orchard/tests/prop.rs (hunk 1 above)
Comment (oxarbitrage) [reply zebra-chain/src/orchard/tests/prop.rs]: I like it, thanks :)

**Comment by teor2345** [comment]
I've changed the name of this PR to include `security`, because we use PR names to make our changelog.

And remotely triggerable panics are more important to users than consensus rule changes.

File: book/src/dev/rfcs/0010-v5-transaction.md [hunk 2]
```diff
@@ -416,6 +416,8 @@ bitflags! {
 
 This type is also defined in `orchard/shielded_data.rs`.
 
+Note: A [consensus rule](https://zips.z.cash/protocol/protocol.pdf#txnencodingandconsensus) was added to the protocol specification stating that the reserved bits (2..7) of the flags must be all zero in transactions V5.
```
Comment (teor2345) [inline book/src/dev/rfcs/0010-v5-transaction.md]: Please quote the exact consensus rule from the spec.

If we copy and paste the consensus rule, we can compare the design to the new rule when there are spec changes.

```suggestion
Note: A [consensus rule](https://zips.z.cash/protocol/protocol.pdf#txnencodingandconsensus) was added to the protocol specification stating that:
> In a version 5 transaction, the reserved bits 2..7 of the flagsOrchard field MUST be zero.
```

File: zebra-chain/src/orchard/shielded_data.rs [hunk 3]
```diff
@@ -155,8 +155,12 @@ impl ZcashSerialize for Flags {
 
 impl ZcashDeserialize for Flags {
     fn zcash_deserialize<R: io::Read>(mut reader: R) -> Result<Self, SerializationError> {
-        let flags = Flags::from_bits(reader.read_u8()?).unwrap();
-
-        Ok(flags)
+        // Consensus rule: In a version 5 transaction,
+        // the reserved bits 2..7 of the flagsOrchard field MUST be zero.
+        // https://zips.z.cash/protocol/protocol.pdf#txnencodingandconsensus
```
Comment (teor2345) [inline zebra-chain/src/orchard/shielded_data.rs]: Thanks for quoting the consensus rule here.

Nitpick: let's make it clear that this is a spec quote

```suggestion
        // Consensus rule: "In a version 5 transaction,
        // the reserved bits 2..7 of the flagsOrchard field MUST be zero."
        // https://zips.z.cash/protocol/protocol.pdf#txnencodingandconsensus
```

File: zebra-chain/src/orchard/shielded_data.rs [hunk 4]
```diff
@@ -155,8 +155,12 @@ impl ZcashSerialize for Flags {
...
+        match Flags::from_bits(reader.read_u8()?) {
+            Some(flags) => Ok(flags),
+            None => Err(SerializationError::Parse("invalid orchard flags")),
+        }
```
Comment (teor2345) [inline zebra-chain/src/orchard/shielded_data.rs]: Optional refactor: https://doc.rust-lang.org/std/option/enum.Option.html#method.ok_or

We might also want to say "reserved" here, because there are other consensus rules that apply to non-reserved flags.

```suggestion
        Flags::from_bits(reader.read_u8()?).ok_or(SerializationError::Parse("invalid reserved orchard flags"))
```

File: zebra-chain/src/orchard/tests/prop.rs [hunk 5]
```diff
@@ -0,0 +1,35 @@
...
+use std::io::Cursor;
+
+use crate::{
+    orchard,
+    serialization::{ZcashDeserializeInto, ZcashSerialize},
+};
+
+proptest! {
+    #[test]
+    // Make sure only valid flags deserialize
```
Comment (teor2345) [inline zebra-chain/src/orchard/tests/prop.rs]: Nitpick: We might as well use a doc-comment here, rather than a standard comment.

And we usually put doc comments before attributes like `#[test]`.
```suggestion
    /// Make sure only valid flags deserialize
    #[test]
```

File: zebra-chain/src/orchard/shielded_data.rs [hunk 6]
```diff
@@ -155,8 +155,12 @@ impl ZcashSerialize for Flags {
```
Comment (teor2345) [inline zebra-chain/src/orchard/shielded_data.rs:162]: Can you also add the consensus rule to the `Flags` struct documentation?

We should also document that `bitflags` restricts its values to the set of valid flags, and link to
https://docs.rs/bitflags/1.2.1/bitflags/index.html

After you change the documentation, you can remove the `// Reserved, zeros (bits 2 .. 7)` comment.

**Review by teor2345 — CHANGES_REQUESTED** [review]
Looks good, just needs some documentation updates.

I also suggested a refactor to simplify the code.

File: zebra-chain/src/orchard/tests/prop.rs [hunk 7]
```diff
@@ -0,0 +1,35 @@
...
+    fn flags_roundtrip(flags in any::<u8>()) {
+
+        let mut serialized = Cursor::new(Vec::new());
+        flags.zcash_serialize(&mut serialized)?;
+
+        serialized.set_position(0);
+        let maybe_deserialized = (&mut serialized).zcash_deserialize_into();
+
+        let invalid_bits_mask = !orchard::Flags::all().bits();
+        match orchard::Flags::from_bits(flags) {
```
Comment (teor2345) [inline zebra-chain/src/orchard/tests/prop.rs]: This is a good deserialization test - we need more of these.

File: zebra-chain/src/orchard/tests/prop.rs [hunk 8]
```diff
@@ -0,0 +1,35 @@
...
+
+use crate::{
+    orchard,
+    serialization::{ZcashDeserializeInto, ZcashSerialize},
+};
+
+proptest! {
+    #[test]
+    // Make sure only valid flags deserialize
+    fn flags_roundtrip(flags in any::<u8>()) {
```
Comment (teor2345) [inline zebra-chain/src/orchard/tests/prop.rs]: Let's change the test name to make it clear that we're testing bytes, not structures:
```suggestion
    fn flag_roundtrip_bytes(flags in any::<u8>()) {
```

**Review by teor2345 — APPROVED** [review]
Looks good, let's merge
