### PR TITLE
Legacy chain check and tests

### LINKED ISSUE #2308: Legacy Chain Check
### Check Finalized Transaction network_upgrade field

V5 transactions have a `network_upgrade` field. If Zebra has followed a legacy chain, the `network_upgrade` field will be different to the calculated `network_upgrade` for that height.

In `StateService::new`, immediately after the new state is created:
- [ ] get a block iterator using `new_service.any_ancestor_blocks(new_service.best_tip().1)`
  - if the state is empty, and the `best_tip()` is `None`, skip the legacy chain check
- [ ] call a function that does the following checks on each block in the iterator:
  - [ ] if the block height is less than the `NU5` activation height, or there is no NU5 activation height, return `Ok(())`
  - [ ] if you've checked 100 blocks, return an error
    - this check finds pre-NU5 legacy chains, because they don't have V5 transactions with network upgrade fields
  - [ ] if `Block.check_transaction_network_upgrade` (#2343) returns an error, return an error
  - [ ] if there is at least one transaction with a `network_upgrade`, and `Block.check_transaction_network_upgrade` returns success, return `Ok(())`

### Panic and Log User Action

If the finalized tip doesn't pass validation:
  - [ ] panic
  - [ ] suggest that the user deletes the database and retries a full sync
  - [ ] give them the exact database path (#2344)

#### Unit Tests

Test that the legacy chain function works:

If the block height is less than the `NU5` activation height, or there is no NU5 activation height, return `Ok(())`
  - [ ] test fake v5 blocks that are less than the NU5 activation height
https://github.com/ZcashFoundation/zebra/blob/2291abc1505f9e639f2ed6c30031bbb7d7ef7dc4/zebra-chain/src/transaction/tests/vectors.rs#L235-L242
  - [ ] proptest a block vector containing at least 100 blocks, starting less than 100 blocks past the NU5 activation height
    - some blocks must be lower than the NU5 activation height
    - the transactions need to all be V4, use the transaction version override from #2347

If you've checked 100 blocks, return an error:
  - [ ] proptest a block vector containing at least 100 blocks, starting 100 blocks or more past the NU5 activation height
    - the transactions need to all be V4, use the transaction version override from #2347

If `Block.check_transaction_network_upgrade` returns an error, return that error:
  - [ ] proptest a block vector starting 100 blocks or more past the NU5 activation height
    - these transactions need to be V5 and some need invalid `network_upgrade` fields, use the transaction version override from #2347
    - to make sure there is an error, use at least 50 blocks

If there is at least one transaction with a `network_upgrade`, and `Block.check_transaction_network_upgrade` returns success, return `Ok(())`
  - [ ] proptest a block vector containing blocks at the NU5 activation height or higher
    - in some tests, some blocks should be lower than the NU5 activation height
    - the transactions need to be V5 and have valid `network_upgrade` fields, use the transaction version override and valid network upgrade overrides from #2347

#### Success Cached State Test

Check that the legacy chain check passes in the existing cached state tests:
- [ ] search the log output to make sure that the legacy chain check runs and passes
  - add a log at info level when starting the check
  - add a log at info level when the check passes

This is part of a split of #1820

### PR DESCRIPTION
**Pull request by oxarbitrage**
## Motivation

We need to have a check after Nu5 activation when zebra starts to make sure we are not following a legacy chain. Close https://github.com/ZcashFoundation/zebra/issues/2308

## Solution

Implement what is detailed in the ticket: https://github.com/ZcashFoundation/zebra/issues/2308

## Review

I know a lot here can be improved so i will like @jvff to make an initial review before passing it into @teor2345 later on.

### Reviewer Checklist

  - [ ] Code implements Specs and Designs
  - [ ] Tests for Expected Behaviour
  - [ ] Tests for Errors

### CODE REVIEW

File: zebra-state/src/service.rs [hunk 1]
```diff
@@ -679,3 +690,46 @@ impl Service<Request> for StateService {
...
+
+                // If we find at least one transaction with a `network_upgrade` field we are ok.
+                let network_upgrades: Vec<NetworkUpgrade> = block
+                    .transactions
+                    .iter()
+                    .filter_map(|trans| trans.network_upgrade())
+                    .collect();
+                if !network_upgrades.is_empty() {
+                    return Ok(());
+                }
```
Comment (jvff) [inline zebra-state/src/service.rs]: Minor idea: you can avoid the allocation inside `Vec` and also stop sooner if you use `.find()` or `.find_map()`:

```suggestion
                let has_network_upgrade = block
                    .transactions
                    .iter()
                    .find_map(|trans| trans.network_upgrade())
                    .is_some();
                if has_network_upgrade {
                    return Ok(());
                }
```

File: zebra-chain/src/parameters/network_upgrade.rs [hunk 2]
```diff
@@ -56,7 +56,8 @@ pub(crate) const MAINNET_ACTIVATION_HEIGHTS: &[(block::Height, NetworkUpgrade)]
     (block::Height(653_600), Blossom),
     (block::Height(903_000), Heartwood),
     (block::Height(1_046_400), Canopy),
-    // TODO: Add Nu5 mainnet activation height
+    // TODO: Add the correct Nu5 mainnet activation height
+    (block::Height(10_000_000), Nu5),
```
Comment (jvff) [inline zebra-chain/src/parameters/network_upgrade.rs]: Is the plan to merge this placeholder height? Because if so, it might make sense for me to remove a few `#[should_panic]` from some tests that expect an NU5 height :sweat_smile:

File: zebra-state/src/service/tests.rs [hunk 3]
```diff
@@ -183,3 +187,87 @@ fn state_behaves_when_blocks_are_committed_out_of_order() -> Result<()> {
...
+        .prop_flat_map(|init| Block::partial_chain_strategy(init, BLOCKS_AFTER_NU5 as usize));
+
+        proptest!(ProptestConfig::with_cases(env::var("PROPTEST_CASES")
+            .ok()
+            .and_then(|v| v.parse().ok())
+            .unwrap_or(DEFAULT_PARTIAL_CHAIN_PROPTEST_CASES)),
+            |(chain in strategy1)| {
+                let response = crate::service::legacy_chain_check(Height(nu5_height.0 + BLOCKS_AFTER_NU5), chain.into_iter(), network);
+                prop_assert_eq!(response.is_err(), false);
+                prop_assert_eq!(response.unwrap(), ());
```
Comment (jvff) [inline zebra-state/src/service/tests.rs]: Minor: I think this could be simplified to:

```suggestion
                prop_assert_eq!(response, Ok(()));
```

File: zebra-state/src/service/tests.rs [hunk 4]
```diff
@@ -183,3 +187,87 @@ fn state_behaves_when_blocks_are_committed_out_of_order() -> Result<()> {
...
+        .prop_flat_map(|init| Block::partial_chain_strategy(init, BLOCKS_AFTER_NU5 as usize + 1));
+
+        proptest!(ProptestConfig::with_cases(env::var("PROPTEST_CASES")
+            .ok()
+            .and_then(|v| v.parse().ok())
+            .unwrap_or(DEFAULT_PARTIAL_CHAIN_PROPTEST_CASES)),
+            |(chain in strategy2)| {
+                let response = crate::service::legacy_chain_check(Height(nu5_height.0 + BLOCKS_AFTER_NU5 + 1), chain.into_iter(), network);
+                prop_assert_eq!(response.is_err(), true);
+                prop_assert_eq!(response.err().unwrap().to_string(), "giving up after checking too many blocks");
```
Comment (jvff) [inline zebra-state/src/service/tests.rs]: Minor idea: I think this could also be simplified, but it requires adding a `.map_err(|error| error.to_string())` to the `response`:

```suggestion
                let response = crate::service::legacy_chain_check(
                    Height(nu5_height.0 + BLOCKS_AFTER_NU5 + 1),
                    chain.into_iter(),
                    network,
                ).map_err(|error| error.to_string());
                
                prop_assert_eq!(response.is_err(), Err();
                prop_assert_eq!(response, Err("giving up after checking too many blocks".into()));
```

File: zebra-chain/src/parameters/network_upgrade.rs (hunk 2 above)
Comment (oxarbitrage) [inline zebra-chain/src/parameters/network_upgrade.rs]: I had to put something here so i can make the tests. Same as the testnet Nu5 height. Open to other number suggestions.

File: zebra-state/src/service/tests.rs [hunk 5]
```diff
@@ -183,3 +187,87 @@ fn state_behaves_when_blocks_are_committed_out_of_order() -> Result<()> {
...
+
+    if let Some(nu5_height) = NetworkUpgrade::Nu5.activation_height(network) {
+        // Test if we can find at least one transaction with `network_upgrade` field in the chain.
+        let strategy1 = zebra_chain::block::LedgerState::height_strategy(
+            Height(nu5_height.0 + BLOCKS_AFTER_NU5),
+            Some(NetworkUpgrade::Nu5),
+            Some(5),
+            true,
+        )
+        .prop_flat_map(|init| Block::partial_chain_strategy(init, BLOCKS_AFTER_NU5 as usize));
```
Comment (jvff) [inline zebra-state/src/service/tests.rs]: Minor idea: I'm not sure if this is a good idea, but it might be useful to create a utility function to collect the common code. With something like:

```
// Utility functions

fn partial_nu5_chain_strategy(
    transaction_version_override: u32,
    transaction_has_valid_network_upgrade: bool,
    blocks_after_nu5_activation: u32,
) -> impl Strategy<Value = (Network, Height, SummaryDebug<Vec<Arc<Block>>>)> {
    any::<Network>().prop_flat_map(move |network| {
        let nu5_height = NetworkUpgrade::Nu5
            .activation_height(network)
            .expect("NU5 activation height not set");
        let height = Height(nu5_height.0 + blocks_after_nu5_activation);

        zebra_chain::block::LedgerState::height_strategy(
            height,
            Some(NetworkUpgrade::Nu5),
            Some(transaction_version_override),
            transaction_has_valid_network_upgrade,
        )
        .prop_flat_map(move |init| {
            Block::partial_chain_strategy(init, blocks_after_nu5_activation as usize)
        })
        .prop_map(move |partial_chain| (network, height, partial_chain))
    })
}
```

the proptest can use as input something like:

```
(network, height, chain) in partial_nu5_chain_strategy(5, true, BLOCKS_AFTER_NU5)
```

File: zebra-state/src/service/tests.rs [hunk 6]
```diff
@@ -183,3 +187,87 @@ fn state_behaves_when_blocks_are_committed_out_of_order() -> Result<()> {
...
+
+#[test]
+fn legacy_chain() -> Result<()> {
+    zebra_test::init();
+
+    legacy_chain_for_network(Network::Mainnet)?;
+    legacy_chain_for_network(Network::Testnet)?;
+
+    Ok(())
+}
```
Comment (jvff) [inline zebra-state/src/service/tests.rs]: Optional styling: feel free to ignore this, and I apologize for the amount of code in the comment :sweat: 

I thought it might be useful to mention that I try to create separate `#[test]`s for separate checks, so that when it fails it's a bit easier to track down. In this case it might be harder because of testing both testnet and mainnet, but one idea might be to make that part of the proptest input. That also allows gathering the `ProptestConfig::with_cases` configuration into a single place.

I've included an example below (which also includes some changes suggested in other comments below). Just an idea, but it might be useful as inspiration for any other changes :sweat_smile: :

```
const DEFAULT_PARTIAL_CHAIN_PROPTEST_CASES: u32 = 2;
const BLOCKS_AFTER_NU5: u32 = 100;

proptest! {
    #![proptest_config(
        proptest::test_runner::Config::with_cases(env::var("PROPTEST_CASES")
            .ok()
            .and_then(|v| v.parse().ok())
            .unwrap_or(DEFAULT_PARTIAL_CHAIN_PROPTEST_CASES))
    )]

    #[test]
    fn at_least_one_transaction_with_network_upgrade(
        (network, height, chain) in partial_nu5_chain_strategy(5, true, BLOCKS_AFTER_NU5)
    ) {
        let response = crate::service::legacy_chain_check(height, chain.into_iter(), network)
            .map_err(|error| error.to_string());

        prop_assert_eq!(response, Ok(()));
    }

    #[test]
    fn no_transactions_with_network_upgrade(
        (network, height, chain) in partial_nu5_chain_strategy(4, true, BLOCKS_AFTER_NU5 + 1)
    ) {
        let response = crate::service::legacy_chain_check(height, chain.into_iter(), network)
            .map_err(|error| error.to_string());

        prop_assert_eq!(
            response,
            Err("giving up after checking too many blocks".into())
        );
    }

    #[test]
    fn at_least_one_transactions_with_inconsistent_network_upgrade(
        (network, height, chain) in partial_nu5_chain_strategy(5, true, BLOCKS_AFTER_NU5)
    ) {
        let start_check_height = (height - 1).expect("Too few blocks after NU5 activation");
        let response =
            crate::service::legacy_chain_check(start_check_height, chain.into_iter(), network)
                .map_err(|error| error.to_string());

        prop_assert_eq!(
            response,
            Err("inconsistent network upgrade found in transaction".into())
        );
    }
}
```

File: zebra-state/src/service.rs [hunk 7]
```diff
@@ -679,3 +690,46 @@ impl Service<Request> for StateService {
...
+                    return Err("giving up after checking too many blocks".into());
+                }
+
+                // All transaction `network_upgrade` fields must be consistent with the block height.
+                if block
+                    .check_transaction_network_upgrade_consistency(network)
+                    .is_err()
+                {
+                    return Err("inconsistent network upgrade found in transaction".into());
+                }
```
Comment (jvff) [inline zebra-state/src/service.rs]: Comment: another way to do this is with `map_err`, but I'm not sure if it's more readable :thinking: 

```suggestion
                block
                    .check_transaction_network_upgrade_consistency(network)
                    .map_err(|_| "inconsistent network upgrade found in transaction")?;
```

File: zebra-state/src/service.rs [hunk 8]
```diff
@@ -664,6 +664,17 @@ impl Service<Request> for StateService {
...
+            Request::IsLegacyChain => {
+                let mut response = None;
+                if let Some(tip) = self.best_tip() {
+                    if legacy_chain_check(tip.0, self.any_ancestor_blocks(tip.1), self.network)
+                        .is_err()
+                    {
+                        response = Some(self.disk.path().to_path_buf());
+                    }
+                }
+                async move { Ok(response).map(Response::LegacyChain) }.boxed()
```
Comment (jvff) [inline zebra-state/src/service.rs]: Minor: this could be done without the `.map`. I'm not sure which one is easier to read, so feel free to leave it as is :D 

```suggestion
                async move { Ok(Response::LegacyChain(response)) }.boxed()
```

I'm also thinking if it might make sense to rename `response` into something like `legacy_chain_path` :thinking:

File: zebrad/src/commands/start.rs [hunk 9]
```diff
@@ -54,6 +54,27 @@ impl StartCmd {
...
+        {
+            Ok(zebra_state::Response::LegacyChain(response)) => {
+                if response.is_some() {
+                    // we found a legacy chain
+                    panic!(
+                        "Legacy chain found, database can be corrupted.
+                        Delete your database and retry a full sync.
+                        Database path: {:?}",
+                        response.expect("the corrupted database path")
+                    );
```
Comment (jvff) [inline zebrad/src/commands/start.rs]: Minor styling: you could avoid the `expect` with something like:

```suggestion
                if let Some(corrupt_db_path) = response {
                    // we found a legacy chain
                    panic!(
                        "Legacy chain found, database can be corrupted.
                        Delete your database and retry a full sync.
                        Database path: {:?}",
                        corrupt_db_path,
                    );
```

**Review by jvff — COMMENTED** [review]
Looks good! I added a few suggestions to the code, and an example of a different way to organize the tests, but they're all optional :+1:

File: zebra-chain/src/parameters/network_upgrade.rs (hunk 2 above)
Comment (jvff) [reply zebra-chain/src/parameters/network_upgrade.rs]: Ah, that makes sense. I had to do the same for some NU5 tests too. But before merging I was planning on removing the height and add `#[should_panic]` to the tests that require the height (and also a `TODO` to remove them later). @teor2345 had also mentioned that it's a good idea to list the tests that we do this in #1841, so we can remove the `#[should_panic]`s and `TODO`s when the height is set :smile:

File: zebra-state/src/service.rs (hunk 1 above)
Comment (oxarbitrage) [reply zebra-state/src/service.rs]: Nice one, i fixed this at https://github.com/ZcashFoundation/zebra/pull/2366/commits/4c6e9379f4b837e4e1989038fa0b942a74789443

File: zebra-state/src/service/tests.rs (hunk 6 above)
Comment (oxarbitrage) [reply zebra-state/src/service/tests.rs]: Yea, i think this is a good idea. I applied in https://github.com/ZcashFoundation/zebra/pull/2366/commits/b46c0a6f2408865d9cac034270bdaa4a1221e72f

Had to change some stuff but not because your suggestion was wrong but because the third tests had problems.

With this in place many of the other suggestions do not apply, i am going to mark them as resolved. 

Thanks.

File: zebra-state/src/service/tests.rs (hunk 5 above)
Comment (oxarbitrage) [reply zebra-state/src/service/tests.rs]: The utility function was added as part of https://github.com/ZcashFoundation/zebra/commit/b46c0a6f2408865d9cac034270bdaa4a1221e72f

File: zebra-state/src/service/tests.rs (hunk 3 above)
Comment (oxarbitrage) [reply zebra-state/src/service/tests.rs]: Do not apply anymore.

File: zebra-state/src/service/tests.rs (hunk 4 above)
Comment (oxarbitrage) [reply zebra-state/src/service/tests.rs]: Do not apply anymore.

File: zebra-state/src/service.rs (hunk 7 above)
Comment (oxarbitrage) [reply zebra-state/src/service.rs]: done at https://github.com/ZcashFoundation/zebra/pull/2366/commits/0587bed76c3d302a01e4a20ed943c2ba11b79214

File: zebra-state/src/service.rs (hunk 8 above)
Comment (oxarbitrage) [reply zebra-state/src/service.rs]: done at https://github.com/ZcashFoundation/zebra/pull/2366/commits/0587bed76c3d302a01e4a20ed943c2ba11b79214

File: zebrad/src/commands/start.rs (hunk 9 above)
Comment (oxarbitrage) [reply zebrad/src/commands/start.rs]: Thanks, i added this one in https://github.com/ZcashFoundation/zebra/pull/2366/commits/796fc7c558cd48376b7a34b9775b3f3545b9931f

File: zebra-chain/src/parameters/network_upgrade.rs (hunk 2 above)
Comment (teor2345) [reply zebra-chain/src/parameters/network_upgrade.rs]: Security: we can't merge code with an incorrect activation height, because it makes nodes follow a different chain.

Instead, pass a NU5 activation height to the `legacy_chain_check` and `partial_nu5_chain_strategy` functions.

File: zebra-chain/src/parameters/network_upgrade.rs [hunk 10]
```diff
@@ -71,7 +72,8 @@ pub(crate) const TESTNET_ACTIVATION_HEIGHTS: &[(block::Height, NetworkUpgrade)]
     (block::Height(584_000), Blossom),
     (block::Height(903_800), Heartwood),
     (block::Height(1_028_500), Canopy),
-    // TODO: Add Nu5 testnet activation height
+    // TODO: Add the correct Nu5 testnet activation height
+    (block::Height(10_000_000), Nu5),
```
Comment (teor2345) [inline zebra-chain/src/parameters/network_upgrade.rs]: Security: the activation height change must be reverted before merging

File: zebra-state/src/request.rs [hunk 11]
```diff
@@ -316,4 +316,7 @@ pub enum Request {
         /// Optionally, the hash of the last header to request.
         stop: Option<block::Hash>,
     },
+
+    /// Returns `Some(database_path)` if Zebra has followed a legacy chain.
+    IsLegacyChain,
```
Comment (teor2345) [inline zebra-state/src/request.rs]: Redundant code: There's no need to add a new state request variant.

Instead, do the legacy chain check in `StateService::new`, immediately after the state is initialized.

File: zebra-state/src/response.rs [hunk 12]
```diff
@@ -41,4 +41,7 @@ pub enum Response {
 
     /// The response to a `FindBlockHeaders` request.
     BlockHeaders(Vec<block::CountedHeader>),
+
+    /// The response to a `IsLegacyChain` request.
+    LegacyChain(Option<std::path::PathBuf>),
```
Comment (teor2345) [inline zebra-state/src/response.rs]: Redundant code: Do the check in the state itself, and remove this response variant

File: zebra-state/src/service.rs [hunk 13]
```diff
@@ -679,3 +690,43 @@ impl Service<Request> for StateService {
 pub fn init(config: Config, network: Network) -> BoxService<Request, Response, BoxError> {
     BoxService::new(StateService::new(config, network))
 }
+
+/// Check if zebra is following a legacy chain and return an error if so.
+pub fn legacy_chain_check<I>(
+    tip_height: block::Height,
+    ancestors: I,
```
Comment (teor2345) [inline zebra-state/src/service.rs]: Redundant code: there's no need for a tip height argument, because every block height gets checked.

Also, the tip height is the height of the first block in `ancestors`.
https://github.com/ZcashFoundation/zebra/blob/24bf952e982bde28eb384b211659159d46150f63/zebra-state/src/service.rs#L288-L293

File: zebra-state/src/service.rs [hunk 14]
```diff
@@ -679,3 +690,43 @@ impl Service<Request> for StateService {
...
+    network: Network,
+) -> Result<(), BoxError>
+where
+    I: Iterator<Item = Arc<Block>>,
+{
+    const MAX_BLOCKS_TO_CHECK: usize = 100;
+
+    // Only do the check if we have an Nu5 activation height.
+    if let Some(nu5_height) = NetworkUpgrade::Nu5.activation_height(network) {
```
Comment (teor2345) [inline zebra-state/src/service.rs]: Testing:
- pass the NU5 activation height to this function
- add a task to #1841 (mainnet): remove the NU5 activation height argument when the mainnet activation height is added to Zebra

File: zebra-state/src/service.rs [hunk 15]
```diff
@@ -679,3 +690,43 @@ impl Service<Request> for StateService {
...
+        // And only do the check if we are above Nu5 activation.
+        if tip_height >= nu5_height {
+            for (count, block) in ancestors.enumerate() {
+                if count >= MAX_BLOCKS_TO_CHECK {
+                    return Err("giving up after checking too many blocks".into());
+                }
+
+                // All transaction `network_upgrade` fields must be consistent with the block height.
```
Comment (teor2345) [inline zebra-state/src/service.rs]: Explain design: How does this check detect a legacy chain?
```suggestion
                // If a transaction `network_upgrade` field is different from the network upgrade calculated
                // using our activation heights, the Zebra instance that verified those blocks had different
                // network upgrade heights.
```

File: zebra-state/src/service.rs [hunk 16]
```diff
@@ -679,3 +690,43 @@ impl Service<Request> for StateService {
...
+    I: Iterator<Item = Arc<Block>>,
+{
+    const MAX_BLOCKS_TO_CHECK: usize = 100;
+
+    // Only do the check if we have an Nu5 activation height.
+    if let Some(nu5_height) = NetworkUpgrade::Nu5.activation_height(network) {
+        // And only do the check if we are above Nu5 activation.
+        if tip_height >= nu5_height {
+            for (count, block) in ancestors.enumerate() {
+                if count >= MAX_BLOCKS_TO_CHECK {
```
Comment (teor2345) [inline zebra-state/src/service.rs]: Explain design: How does this check detect a legacy chain?
```suggestion
                // If we are past our NU5 activation height, but there are no V5 transactions in recent blocks,
                // the Zebra instance that verified those blocks had no NU5 activation height.
                if count >= MAX_BLOCKS_TO_CHECK {
```

File: zebra-state/src/service.rs [hunk 17]
```diff
@@ -679,3 +690,43 @@ impl Service<Request> for StateService {
...
+                    return Err("giving up after checking too many blocks".into());
+                }
+
+                // All transaction `network_upgrade` fields must be consistent with the block height.
+                block
+                    .check_transaction_network_upgrade_consistency(network)
+                    .map_err(|_| "inconsistent network upgrade found in transaction")?;
+
+                // If we find at least one transaction with a `network_upgrade` field we are ok.
```
Comment (teor2345) [inline zebra-state/src/service.rs]: Explain design: How does this check detect a correct chain?
```suggestion
                // If we find at least one transaction with a valid `network_upgrade` field, the Zebra instance that
                // verified those blocks used the same network upgrade heights. (Up to this point in the chain.)
```

File: zebra-state/src/service.rs [hunk 18]
```diff
@@ -679,3 +690,43 @@ impl Service<Request> for StateService {
...
+) -> Result<(), BoxError>
+where
+    I: Iterator<Item = Arc<Block>>,
+{
+    const MAX_BLOCKS_TO_CHECK: usize = 100;
+
+    // Only do the check if we have an Nu5 activation height.
+    if let Some(nu5_height) = NetworkUpgrade::Nu5.activation_height(network) {
+        // And only do the check if we are above Nu5 activation.
+        if tip_height >= nu5_height {
```
Comment (teor2345) [inline zebra-state/src/service.rs]: 1. Bug: Do this check on every block height, not just the first block height

2. Explain design: Why is this check is important? Why does it need to be done for every block?

3. Confusing code: Let's call it `nu5_activation_height`, because there are lots of NU5 blocks

```suggestion
        // Stop checking if the chain reaches Canopy. We won't find any more V5 transactions,
        // so the rest of our checks are useless.
        //
        // If the cached tip is close to NU5 activation, but there aren't any V5 transactions in the
        // chain yet, we could reach MAX_BLOCKS_TO_CHECK in Canopy, and incorrectly return an error.
        if block.coinbase_height().expect("valid blocks have coinbase heights") < nu5_activation_height {
            return Ok(());
        }
```

File: zebra-state/src/service.rs [hunk 19]
```diff
@@ -679,3 +690,43 @@ impl Service<Request> for StateService {
 pub fn init(config: Config, network: Network) -> BoxService<Request, Response, BoxError> {
     BoxService::new(StateService::new(config, network))
 }
+
+/// Check if zebra is following a legacy chain and return an error if so.
+pub fn legacy_chain_check<I>(
```
Comment (teor2345) [inline zebra-state/src/service.rs]: Small Module API: This function isn't called outside zebra-state
```suggestion
fn legacy_chain_check<I>(
```

File: zebra-state/src/service/tests.rs [hunk 20]
```diff
@@ -183,3 +187,172 @@ fn state_behaves_when_blocks_are_committed_out_of_order() -> Result<()> {
...
+            Some(nu),
+            Some(transaction_version_override),
+            transaction_has_valid_network_upgrade,
+        )
+        .prop_flat_map(move |init| {
+            Block::partial_chain_strategy(init, blocks_after_nu5_activation as usize)
+        })
+        .prop_map(move |partial_chain| (network, height, partial_chain))
+    })
+}
```
Comment (teor2345) [inline zebra-state/src/service/tests.rs]: Module Structure: Let's put all the chain strategies together.

1. Move `zebra_chain::service::non_finalized_state::arbitrary` to `zebra_chain::service::arbitrary`
2. Move this strategy to `zebra_chain::service::arbitrary`

File: zebra-state/src/service/tests.rs [hunk 21]
```diff
@@ -183,3 +187,172 @@ fn state_behaves_when_blocks_are_committed_out_of_order() -> Result<()> {
...
+    Value = (
+        Network,
+        Height,
+        zebra_chain::fmt::SummaryDebug<Vec<Arc<Block>>>,
+    ),
+> {
+    any::<Network>().prop_flat_map(move |network| {
+        let nu5_height = NetworkUpgrade::Nu5
+            .activation_height(network)
+            .expect("NU5 activation height not set");
```
Comment (teor2345) [inline zebra-state/src/service/tests.rs]: Testing:
- pass a NU5 activation height argument to `partial_nu5_chain_strategy`
- give the same NU5 activation height to `legacy_chain_check` and `partial_nu5_chain_strategy`
- add a task to #1841 (mainnet): remove the NU5 activation height argument when the mainnet activation height is added to Zebra

File: zebra-state/src/service/tests.rs [hunk 22]
```diff
@@ -183,3 +187,172 @@ fn state_behaves_when_blocks_are_committed_out_of_order() -> Result<()> {
...
+        let height = Height(nu5_height.0 + blocks_after_nu5_activation);
+
+        let mut nu = NetworkUpgrade::Nu5;
+        if !transaction_has_valid_network_upgrade {
+            nu = NetworkUpgrade::Canopy;
+        }
```
Comment (teor2345) [inline zebra-state/src/service/tests.rs]: Maybe redundant code or bug: Can you add a comment explaining why this code is needed, or remove this code?

It looks like you set the network upgrade to `Canopy` when `transaction_has_valid_network_upgrade` is `false`. But the legacy chain check needs to detect any invalid network upgrade.

File: zebrad/src/commands/start.rs [hunk 23]
```diff
@@ -54,6 +54,27 @@ impl StartCmd {
...
+                        "Legacy chain found, database can be corrupted.
+                        Delete your database and retry a full sync.
+                        Database path: {:?}",
+                        corrupt_db_path,
+                    );
+                }
+            }
+            _ => unreachable!("the legacy chain call should always respond"),
+        };
+        info!("no legacy chain found");
```
Comment (teor2345) [inline zebrad/src/commands/start.rs]: Redundant Code: Can you do this check and panic in `StateService::new`?

File: zebrad/src/commands/start.rs [hunk 24]
```diff
@@ -54,6 +54,27 @@ impl StartCmd {
...
+        {
+            Ok(zebra_state::Response::LegacyChain(response)) => {
+                if let Some(corrupt_db_path) = response {
+                    // we found a legacy chain
+                    panic!(
+                        "Legacy chain found, database can be corrupted.
+                        Delete your database and retry a full sync.
+                        Database path: {:?}",
+                        corrupt_db_path,
+                    );
```
Comment (teor2345) [inline zebrad/src/commands/start.rs]: 1. Usability: a state created by an older Zebra version isn't corrupt, it's just outdated. If we say "corrupt", users will think their disks are failing.

2. Format Bug: multi-line indented strings must be escaped in Rust: https://stackoverflow.com/questions/29483365/what-is-the-syntax-for-a-multiline-string-literal/29483453#29483453

3. Redundant comment: comments don't need to repeat what the code or error message says.

```suggestion
                if let Some(legacy_db_path) = response {
                    panic!(
                        "Cached state contains a legacy chain. \
                        An outdated Zebra version did not know about a recent network upgrade, \
                        so it followed a legacy chain using outdated rules. \
                        Hint: Delete your database, and restart Zebra to do a full sync. \
                        Database path: {:?}",
                        legacy_db_path,
                    );
```

File: zebrad/tests/acceptance.rs [hunk 25]
```diff
@@ -1327,3 +1327,28 @@ where
...
+
+    // Run the program and kill it after a few seconds
+    std::thread::sleep(LAUNCH_DELAY);
+    child.kill()?;
+
+    let output = child.wait_with_output()?;
+    let output = output.assert_failure()?;
+
+    output.stdout_line_contains("starting legacy chain check")?;
+    output.stdout_line_contains("no legacy chain found")?;
```
Comment (teor2345) [inline zebrad/tests/acceptance.rs]: Test coverage: move these checks to the existing tests:
- start
- restart
- cached state

Doing these checks in existing tests also lets us remove this redundant test.

File: zebra-state/src/service/tests.rs [hunk 26]
```diff
@@ -183,3 +187,172 @@ fn state_behaves_when_blocks_are_committed_out_of_order() -> Result<()> {
 
     Ok(())
 }
+
+/*
+#[test]
```
Comment (teor2345) [inline zebra-state/src/service/tests.rs]: I haven't reviewed the tests in detail yet.

Here are some changes I'd like to see first:
- [ ] Do the `legacy_chain_check` and proptest strategy refactors
- [x] Delete any redundant tests
- [ ] Test Coverage: Make sure every rule is covered - see the latest list of test cases in the ticket
- [ ] Explain tests: Can you add a short doc comment to each test, explaining which rule it tests?

File: zebra-state/src/service.rs [hunk 27]
```diff
@@ -679,3 +690,43 @@ impl Service<Request> for StateService {
...
+    tip_height: block::Height,
+    ancestors: I,
+    network: Network,
+) -> Result<(), BoxError>
+where
+    I: Iterator<Item = Arc<Block>>,
```
Comment (teor2345) [inline zebra-state/src/service.rs:719]: 👍

File: zebra-state/src/service/tests.rs (hunk 26 above)
Comment (teor2345) [inline zebra-state/src/service/tests.rs]: The ticket was missing a test for this rule:
> for every block, if the block height is less than the NU5 activation height, return Ok(())

Here's the test:
- proptest a block vector containing at least 100 blocks, starting less than 100 blocks past the NU5 activation height
  - some blocks must be lower than the NU5 activation height
  - the transactions need to all be V4, use the transaction version override from #2347

I've also added the missing test to the ticket, and tried to clarify some of the other tests.

File: zebra-state/src/service.rs [hunk 28]
```diff
@@ -679,3 +690,43 @@ impl Service<Request> for StateService {
...
+        if tip_height >= nu5_height {
+            for (count, block) in ancestors.enumerate() {
+                if count >= MAX_BLOCKS_TO_CHECK {
+                    return Err("giving up after checking too many blocks".into());
+                }
+
+                // All transaction `network_upgrade` fields must be consistent with the block height.
+                block
+                    .check_transaction_network_upgrade_consistency(network)
+                    .map_err(|_| "inconsistent network upgrade found in transaction")?;
```
Comment (teor2345) [inline zebra-state/src/service.rs]: _Panic message changes can be done after the next review. Bug and test changes are more important._

Usability: To give a better panic message, let's return the underlying `WrongTransactionConsensusBranchId` error. Then we can add fields to it, and use them in the panic message.
```suggestion
                    .check_transaction_network_upgrade_consistency(network)?;
```

File: zebra-state/src/service.rs [hunk 29]
```diff
@@ -679,3 +690,43 @@ impl Service<Request> for StateService {
...
+{
+    const MAX_BLOCKS_TO_CHECK: usize = 100;
+
+    // Only do the check if we have an Nu5 activation height.
+    if let Some(nu5_height) = NetworkUpgrade::Nu5.activation_height(network) {
+        // And only do the check if we are above Nu5 activation.
+        if tip_height >= nu5_height {
+            for (count, block) in ancestors.enumerate() {
+                if count >= MAX_BLOCKS_TO_CHECK {
+                    return Err("giving up after checking too many blocks".into());
```
Comment (teor2345) [inline zebra-state/src/service.rs]: _Panic message changes can be done after the next review. Bug and test changes are more important._

Usability: Let's create a `WrongTransactionConsensusBranchId` error here, with `block_height`, `expected_network_upgrade: NU5`, and `invalid_network_upgrade: Canopy`. Then we can use those details in the panic message.

File: zebrad/src/commands/start.rs (hunk 24 above)
Comment (teor2345) [inline zebrad/src/commands/start.rs]: _Panic message changes can be done after the next review. Bug and test changes are more important._

Usability: Let's also tell users the block height and network upgrade that failed. If we return `error_block_height` and  `error_network_upgrade` from `legacy_chain_check`, we can also make the tests more specific. You'll need to add some fields to the `check_transaction_network_upgrade_consistency` error.

```rust
                if let Some(legacy_db_path) = response {
                    panic!(
                        "Cached state contains a legacy chain at {:?}. \
                        An outdated Zebra version did not know about the {:?} network upgrade, \
                        so it followed a legacy chain using {:?} rules. \
                        Hint: Delete your database, and restart Zebra to do a full sync. \
                        Database path: {:?}",
                        error.block_height,
                        error.expected_network_upgrade,
                        error.invalid_network_upgrade,
                        legacy_db_path,
                    );
```

**Review by teor2345 — CHANGES_REQUESTED** [review]
This looks like a good start - the overall check and structure is pretty good.

Before the next review, let's try to:
- fix bugs in the legacy chain check
- simplify the code and module structure
- change the legacy chain check and proptest strategies so they are easier to test

I also made some suggestions to improve the panic message. We could make them into another ticket. Or if you have time, you could do them after the other changes are done.

File: zebra-state/src/request.rs (hunk 11 above)
Comment (oxarbitrage) [reply zebra-state/src/request.rs]: https://github.com/ZcashFoundation/zebra/pull/2366/commits/f4dce3b3b7bfe95c78ad424ca5c9ad8a732c1155

File: zebra-state/src/response.rs (hunk 12 above)
Comment (oxarbitrage) [reply zebra-state/src/response.rs]: https://github.com/ZcashFoundation/zebra/pull/2366/commits/f4dce3b3b7bfe95c78ad424ca5c9ad8a732c1155

File: zebra-chain/src/parameters/network_upgrade.rs (hunk 2 above)
Comment (oxarbitrage) [reply zebra-chain/src/parameters/network_upgrade.rs]: The Nu5 activation heights were removed.

File: zebra-chain/src/parameters/network_upgrade.rs (hunk 10 above)
Comment (oxarbitrage) [reply zebra-chain/src/parameters/network_upgrade.rs]: This was reverfted in https://github.com/ZcashFoundation/zebra/pull/2366/commits/730c51874e169a88e125c03c07de8d6c3af9af05

File: zebra-state/src/service.rs (hunk 13 above)
Comment (oxarbitrage) [reply zebra-state/src/service.rs]: The tip argument was removed.

File: zebra-state/src/service.rs (hunk 15 above)
Comment (oxarbitrage) [reply zebra-state/src/service.rs]: Docs were added in https://github.com/ZcashFoundation/zebra/pull/2366/commits/8bb38d5ff2fa83dbabd5b1b7158148be0f475f1c

File: zebra-state/src/service.rs (hunk 16 above)
Comment (oxarbitrage) [reply zebra-state/src/service.rs]: https://github.com/ZcashFoundation/zebra/pull/2366/commits/8bb38d5ff2fa83dbabd5b1b7158148be0f475f1c

File: zebra-state/src/service.rs (hunk 17 above)
Comment (oxarbitrage) [reply zebra-state/src/service.rs]: https://github.com/ZcashFoundation/zebra/pull/2366/commits/8bb38d5ff2fa83dbabd5b1b7158148be0f475f1c

File: zebra-state/src/service.rs (hunk 18 above)
Comment (oxarbitrage) [reply zebra-state/src/service.rs]: https://github.com/ZcashFoundation/zebra/pull/2366/commits/8bb38d5ff2fa83dbabd5b1b7158148be0f475f1c

File: zebra-state/src/service/tests.rs (hunk 20 above)
Comment (oxarbitrage) [reply zebra-state/src/service/tests.rs]: Was done in https://github.com/ZcashFoundation/zebra/pull/2366/commits/ee9294a821e202724f3fdcc759cbab2661387d52

File: zebra-state/src/service/tests.rs (hunk 22 above)
Comment (oxarbitrage) [reply zebra-state/src/service/tests.rs]: Some comments about this were added to the code in  https://github.com/ZcashFoundation/zebra/pull/2366/commits/ee9294a821e202724f3fdcc759cbab2661387d52

File: zebrad/src/commands/start.rs (hunk 24 above)
Comment (oxarbitrage) [reply zebrad/src/commands/start.rs]: https://github.com/ZcashFoundation/zebra/pull/2366/commits/d3989c6694db013997db3bbfcdc3d45e61f1142c

File: zebrad/tests/acceptance.rs (hunk 25 above)
Comment (oxarbitrage) [reply zebrad/tests/acceptance.rs]: https://github.com/ZcashFoundation/zebra/pull/2366/commits/6d2b5ddd6eee9d5d81d24516c8d90c7a7310f61e

File: zebra-state/src/service.rs (hunk 19 above)
Comment (oxarbitrage) [reply zebra-state/src/service.rs]: This suggestion was valid for when the function was in the same file as the prop tests. After the move of this function into service/arbitrary.rs we need it to be `pub` so we can call it from the prop tests. We now have it as `pub(crate)` as that is all we need.

File: zebra-chain/src/parameters/arbitrary.rs [hunk 30]
```diff
@@ -18,4 +18,17 @@ impl NetworkUpgrade {
         ]
         .boxed()
     }
+
+    /// Generates network upgrades from a reduced set
+    pub fn reduced_branch_id_strategy() -> BoxedStrategy<NetworkUpgrade> {
```
Comment (oxarbitrage) [inline zebra-chain/src/parameters/arbitrary.rs:23]: This can probably be done directly in https://github.com/ZcashFoundation/zebra/blob/ee9294a821e202724f3fdcc759cbab2661387d52/zebra-state/src/service/arbitrary.rs#L108
Unsure if that will be a better choice.

File: zebra-state/src/service/arbitrary.rs [hunk 31]
```diff
@@ -86,3 +91,46 @@ impl Strategy for PreparedChain {
...
+        zebra_chain::fmt::SummaryDebug<Vec<Arc<Block>>>,
+    ),
+> {
+    (
+        any::<Network>(),
+        NetworkUpgrade::reduced_branch_id_strategy(),
+    )
+        .prop_flat_map(move |(network, random_nu)| {
+            // We are going to test the legacy chain with Canopy instead as we don't have a
+            // Nu5 activation height yet.
```
Comment (oxarbitrage) [inline zebra-state/src/service/arbitrary.rs]: I understand this can be confusing.

**Comment by oxarbitrage** [comment]
I think is ready for a second round of review. The panic changes were not done, i think we should do them in a new ticket with lower priority. I didn't updated https://github.com/ZcashFoundation/zebra/issues/1841 yet, i think the rest is more or less covered even if sometimes not exactly as suggested.

File: zebra-chain/src/parameters/arbitrary.rs (hunk 30 above)
Comment (teor2345) [reply zebra-chain/src/parameters/arbitrary.rs:23]: I think it's fine, we're going to revise this code in #1974 anyway.

File: zebra-state/src/service.rs [hunk 32]
```diff
@@ -679,3 +700,56 @@ impl Service<Request> for StateService {
...
+        if block
+            .coinbase_height()
+            .expect("valid blocks have coinbase heights")
+            < nu5_activation_height
+        {
+            return Ok(());
+        }
+
+        // If we are past our NU5 activation height, but there are no V5 transactions in recent blocks,
+        // the Zebra instance that verified those blocks had no NU5 activation
```
Comment (teor2345) [inline zebra-state/src/service.rs]: Typo
```suggestion
        // the Zebra instance that verified those blocks had no NU5 activation height.
```

File: zebra-state/src/service.rs [hunk 33]
```diff
@@ -679,3 +700,56 @@ impl Service<Request> for StateService {
...
+            .check_transaction_network_upgrade_consistency(network)
+            .map_err(|_| "inconsistent network upgrade found in transaction")?;
+
+        // If we find at least one transaction with a valid `network_upgrade` field, the Zebra instance that
+        // verified those blocks used the same network upgrade heights. (Up to this point in the chain.)
+        let has_network_upgrade = block
+            .transactions
+            .iter()
+            .find_map(|trans| trans.network_upgrade())
+            .is_some();
```
Comment (teor2345) [inline zebra-state/src/service.rs:756]: Nice use of `find_map` to do an efficient search.

File: zebra-state/src/service/arbitrary.rs (hunk 31 above)
Comment (teor2345) [reply zebra-state/src/service/arbitrary.rs]: Suggestion: We could make it less confusing by passing a network upgrade argument to the strategy.

File: zebra-state/src/service/arbitrary.rs [hunk 34]
```diff
@@ -86,3 +91,46 @@ impl Strategy for PreparedChain {
         })
     }
 }
+
+/// Generate a chain to test legacy chain check.
```
Comment (teor2345) [inline zebra-state/src/service/arbitrary.rs]: Documentation: can you explain what the strategy does, and what each argument does?

For arguments that you're passing to the inner strategy, it's better to say "See `LedgerState::height_strategy` for details." It's less work for you, and we don't have to update multiple docs when the arguments change.

File: zebra-state/src/service/tests.rs [hunk 35]
```diff
@@ -183,3 +183,65 @@ fn state_behaves_when_blocks_are_committed_out_of_order() -> Result<()> {
...
+    #![proptest_config(
+        proptest::test_runner::Config::with_cases(env::var("PROPTEST_CASES")
+            .ok()
+            .and_then(|v| v.parse().ok())
+            .unwrap_or(DEFAULT_PARTIAL_CHAIN_PROPTEST_CASES))
+    )]
+
+    /// Test blocks that are less than the NU5 activation height.
+    #[test]
+    fn some_block_less_than_network_upgrade(
```
Comment (teor2345) [inline zebra-state/src/service/tests.rs:202]: These tests all look good

File: zebrad/tests/acceptance.rs [hunk 36]
```diff
@@ -860,6 +864,10 @@ fn create_cached_database_height(network: Network, height: Height) -> Result<()>
     let network = format!("network: {},", network);
     child.expect_stdout_line_matches(&network)?;
     child.expect_stdout_line_matches(STOP_AT_HEIGHT_REGEX)?;
+
+    child.expect_stdout_line_matches("starting legacy chain check")?;
+    child.expect_stdout_line_matches("no legacy chain found")?;
```
Comment (teor2345) [inline zebrad/tests/acceptance.rs]: Bug: the legacy chain check happens when the database is opened. Then after the chain has synced for a while, we stop at the configured height.
```suggestion

    child.expect_stdout_line_matches("starting legacy chain check")?;
    child.expect_stdout_line_matches("no legacy chain found")?;

    child.expect_stdout_line_matches(STOP_AT_HEIGHT_REGEX)?;
```

Comment (teor2345) [inline zebrad/tests/acceptance.rs:881]: Test coverage: Can you also add these checks to `sync_until`?

Those tests are enabled in CI, so we can check we got the log order right.

**Review by teor2345 — CHANGES_REQUESTED** [review]
I think we're pretty good here, just a few things we could tweak, and a small bug fix.

You might want to check with @conradoplg about the chain proptest strategies, he's also fixing some issues.

File: zebra-state/src/service.rs [hunk 37]
```diff
@@ -64,21 +66,40 @@ impl StateService {
...
             mem,
             queued_blocks,
             pending_utxos,
             network,
             last_prune: Instant::now(),
+        };
+
+        tracing::info!("starting legacy chain check");
+        if let Some(tip) = state.best_tip() {
+            if legacy_chain_check(tip.0, state.any_ancestor_blocks(tip.1), state.network).is_err() {
```
Comment (teor2345) [inline zebra-state/src/service.rs]: Bug: `tip.0` is not the NU5 activation height.

File: zebra-state/src/service.rs (hunk 33 above)
Comment (oxarbitrage) [reply zebra-state/src/service.rs:756]: Yea, that was a @jvff suggestion :)

File: zebra-state/src/service.rs (hunk 14 above)
Comment (teor2345) [reply zebra-state/src/service.rs]: I updated #1841

File: zebra-state/src/service/tests.rs (hunk 21 above)
Comment (teor2345) [reply zebra-state/src/service/tests.rs]: I updated #1841

File: zebra-state/src/service.rs (hunk 28 above)
Comment (teor2345) [reply zebra-state/src/service.rs]: I opened #2394 for this

File: zebrad/tests/acceptance.rs (hunk 36 above)
Comment (oxarbitrage) [reply zebrad/tests/acceptance.rs:881]: I tried to do this however the output if the child there stops before the check is done:

```
Jun 24 21:02:39.528  INFO {zebrad="bee2cca" net="Main"}: zebrad::commands::start: Starting zebrad
Jun 24 21:02:39.528  INFO {zebrad="bee2cca" net="Main"}: zebrad::commands::start: config=ZebradConfig { consensus: Config { checkpoint_sync: false }, metrics: MetricsSection { endpoint_addr: None }, network: Config { listen_addr: 127.0.0.1:0, network: Mainnet, initial_mainnet_peers: {"dnsseed.z.cash:8233", "mainnet.is.yolo.money:8233", "mainnet.seeder.zfnd.org:8233", "dnsseed.str4d.xyz:8233"}, initial_testnet_peers: {"testnet.seeder.zfnd.org:18233", "testnet.is.yolo.money:18233", "dnsseed.testnet.z.cash:18233"}, peerset_initial_target_size: 50, crawl_new_peer_interval: 30s }, state: Config { cache_dir: "/tmp/zebrad_tests.ShIQzAXkoZkZ/state", ephemeral: false, debug_stop_at_height: Some(0) }, tracing: TracingSection { use_color: true, filter: None, endpoint_addr: None, flamegraph: None, use_journald: false }, sync: SyncSection { max_concurrent_block_requests: 50, lookahead_limit: 2000 } }
Jun 24 21:02:39.528  INFO {zebrad="bee2cca" net="Main"}: zebrad::commands::start: initializing node state
Jun 24 21:02:39.529  INFO {zebrad="bee2cca" net="Main"}: zebra_state::config: the open file limit is at or above the specified limit new_limit=1024 current_limit=1024 hard_rlimit=Some(4096)
Jun 24 21:02:39.569  INFO {zebrad="bee2cca" net="Main"}: zebra_state::service::finalized_state: Opened Zebra state cache at /tmp/zebrad_tests.ShIQzAXkoZkZ/state/state/v5/mainnet
Jun 24 21:02:39.570  INFO {zebrad="bee2cca" net="Main"}: zebra_state::service::finalized_state: state is already at the configured height debug_stop_at_height=Height(0) tip_height=Height(0) tip_hash=block::Hash("00040fe8ec8471911baa1db1266ea15dd06b4a8a5c453883c000b031973dce08")
```

Comment (oxarbitrage) [reply zebrad/tests/acceptance.rs]: https://github.com/ZcashFoundation/zebra/pull/2366/commits/e3208f42579ba586705a35108c47c0b2e120c0c6

File: zebra-state/src/service.rs (hunk 32 above)
Comment (oxarbitrage) [reply zebra-state/src/service.rs]: https://github.com/ZcashFoundation/zebra/pull/2366/commits/e3208f42579ba586705a35108c47c0b2e120c0c6

File: zebra-state/src/service.rs (hunk 37 above)
Comment (oxarbitrage) [reply zebra-state/src/service.rs]: Yea, you are right here but what can we send, `Canopy` with a `TODO` to change after we have `Nu5` height?

File: zebra-state/src/service/arbitrary.rs (hunk 31 above)
Comment (oxarbitrage) [reply zebra-state/src/service/arbitrary.rs]: I made this suggestion at https://github.com/ZcashFoundation/zebra/pull/2366/commits/d593c9f009a7843c984aa6ab7f2f2d241e4ba286

File: zebra-state/src/service.rs (hunk 37 above)
Comment (teor2345) [reply zebra-state/src/service.rs]: We can skip the check if there is no NU5 activation height, because the next possible legacy chain is Canopy -> NU5.

That way, we automatically do the check on testnet as soon as its height is added, but the mainnet check waits for a few months.

```rust
if let Some(tip) = state.best_tip() {
    if let Some(nu5_activation_height) = Nu5.activation_height(network) {
```

File: zebrad/tests/acceptance.rs (hunk 36 above)
Comment (teor2345) [reply zebrad/tests/acceptance.rs:881]: You could try something like:
```rust
if child.expect_stdout_line_matches("starting legacy chain check").is_ok() {
    child.expect_stdout_line_matches("no legacy chain found")?;
}
```

That way, if the legacy check is skipped, the test still passes.

(It's ok if the legacy chain check is skipped, because Zebra still works. But if it fails and panics on a good chain, we want to catch that in the tests.)

Comment (oxarbitrage) [reply zebrad/tests/acceptance.rs:881]: That will not work either:

```
The application panicked (crashed).
Message:  child must capture stdout to call expect_stdout_line_matches
```

File: zebra-state/src/service.rs (hunk 37 above)
Comment (oxarbitrage) [reply zebra-state/src/service.rs]: Thanks. I added this at https://github.com/ZcashFoundation/zebra/pull/2366/commits/922d36605113d2de7fb93fdffe306891d6dffb42

File: zebra-state/src/service/arbitrary.rs (hunk 34 above)
Comment (oxarbitrage) [reply zebra-state/src/service/arbitrary.rs]: Added some docs at https://github.com/ZcashFoundation/zebra/pull/2366/commits/93530423bd92933c32208b7e0e9dba2c204f0a67 and https://github.com/ZcashFoundation/zebra/pull/2366/commits/591eff1d906aa5ce258d569f7cd76e3d63366b2b

File: zebra-state/src/service/arbitrary.rs [hunk 38]
```diff
@@ -86,3 +91,56 @@ impl Strategy for PreparedChain {
...
+> {
+    (
+        any::<Network>(),
+        NetworkUpgrade::reduced_branch_id_strategy(),
+    )
+        .prop_flat_map(move |(network, random_nu)| {
+            // TODO: update this to Nu5 after we have a height #1841
+            let mut nu = network_upgrade;
+            let nu_activation = nu.activation_height(network).unwrap();
+            let height = Height(nu_activation.0 + blocks_after_nu_activation);
```
Comment (teor2345) [inline zebra-state/src/service/arbitrary.rs:128]: Doc or code bug: 

The docs say:
> - `network_upgrade` - The height at which the strategy will start generating blocks.

But the code:
1. adds `blocks_after_nu_activation` to the network upgrade activation height
2. starts the chain at that height
3. generates `blocks_after_nu_activation` blocks after that height

Comment (teor2345) [reply zebra-state/src/service/arbitrary.rs:128]: Would it help to add a test for the strategy, that makes sure the blocks are at the heights you expect?

File: zebrad/tests/acceptance.rs (hunk 36 above)
Comment (teor2345) [reply zebrad/tests/acceptance.rs:881]: ### Priority / Scheduling

This test is pretty important, because we don't have any other way of testing the legacy chain check against cached state. But we can't do it until we add an NU5 activation height.

So let's open another ticket for this change?

Since we'll be relying on the proptests to merge this PR, we'll have to make sure they're testing the right height ranges and data.

### Details

That's a confusing panic message, see PR #2406 for a better one.

What's happening is that the output gets dropped and the process killed when there isn't any match. So my original idea wouldn't have worked, because:
`if child.expect_stdout_line_matches("starting legacy chain check")`
would consume all the output and kill the process.

Instead, we'll need to pass a parameter to `sync_until`, which tells it if it should check for legacy chain output.

If we expect the state to sync some blocks, and there is an NU5 activation height, we should check for legacy chain output. But if we expect to be at the stop height, or there is no NU5 activation height, we should skip the legacy chain output check, because Zebra will exit before it happens.

File: zebra-state/src/service/arbitrary.rs (hunk 38 above)
Comment (oxarbitrage) [reply zebra-state/src/service/arbitrary.rs:128]: The documentation is wrong for sure, i made an update in https://github.com/ZcashFoundation/zebra/pull/2366/commits/f13bf679c6fa2c7e91066e3fd28541aae286e5f2

File: zebrad/tests/acceptance.rs (hunk 36 above)
Comment (teor2345) [reply zebrad/tests/acceptance.rs:881]: Fixed by a645a74

**Review by teor2345 — CHANGES_REQUESTED** [review]
This looks good now, but it changes the cached state tests, so it is blocked by #2402.

**Review by teor2345 — APPROVED** [review]
The blockers have all merged.

There's no easy way to test this branch merged with the latest `main`, so I'm just going to go ahead and merge, and then check that it works.

If it fails someone should revert and re-open the PR.

**Comment by teor2345** [comment]
This appears to work locally on mainnet and testnet, with and without cached state, and before and after the mandatory checkpoint.
