### PR TITLE
fix(network): Fixes bug in `ActiveConnectionCounter` and inaccurate connection count metrics

### LINKED ISSUE #7981: The number of outbound connections reported by progress bars periodically glitches
### Description

When syncing on Testnet, I noticed the number of outbound connections reported by the new progress bars periodically jumps from ~7 to the limit of 75 and then back to ~7. The period seems to be equal to the `crawl_new_peer_interval` setting.

### Analysis

That's probably because the connection counter actually comes from the connection limit, which is updated when we start making a connection. (Not when we successfully connect.)

So every few minutes, we re-try all the failed peers at the same time, the connection limit goes to 75, and then it drops back when they all fail.

### Possible Solutions

Reducing the progress bar update interval would hide this, but it would still occasionally happen. (And be visible for longer.)

The real fix would be to move the progress bar to the peer set. We track inbound/outbound on the [ConnectedAddr type in ConnectionInfo](https://github.com/ZcashFoundation/zebra/blob/b5e16a6b26d05f5d901a8537f324fa001451753f/zebra-network/src/peer/handshake.rs#L131), which is part of the LoadTrackedClient in the PeerSet.

### PR DESCRIPTION
**Pull request by arya2**
## Motivation

This is an alternative to #10248 and will close #7981.

It would be nice to separate reserved slots for connection attempts from the connection count while addressing this issue to pave the way for a more flexible configuration in the future.

### PR Checklist

- [ ] The PR name is suitable for the release notes.
- [ ] The PR follows the [contribution guidelines](https://github.com/ZcashFoundation/zebra/blob/main/CONTRIBUTING.md).
- [ ] The library crate changelogs are up to date.
- [ ] The solution is tested.
- [ ] The documentation is up to date.

### CODE REVIEW

File: zebra-network/src/peer_set/limit.rs [hunk 1]
```diff
@@ -20,16 +20,25 @@ pub struct ConnectionClosed;
...
     limit: usize,
 
     /// The label for this connection counter, typically its type.
     label: Arc<str>,
 
+    /// The channel used to send opened connection notifications.
+    open_notification_tx: mpsc::UnboundedSender<()>,
+
+    /// The channel used to receive opened connection notifications.
+    open_notification_rx: mpsc::UnboundedReceiver<()>,
```
Comment (arya2) [inline zebra-network/src/peer_set/limit.rs]: These could be unified if we prefer this approach.

File: zebra-network/src/peer_set/limit.rs [hunk 2]
```diff
@@ -150,12 +180,18 @@ impl fmt::Debug for ConnectionTracker {
 }
 
 impl ConnectionTracker {
+    pub fn mark_open(&mut self) {
```
Comment (conradoplg) [inline zebra-network/src/peer_set/limit.rs:184]: Optional: document the function

File: zebra-network/src/peer_set/limit.rs [hunk 3]
```diff
@@ -181,6 +218,7 @@ impl Drop for ConnectionTracker {
         // # Security
         //
         // This channel is actually bounded by the inbound and outbound connection limit.
+        self.mark_open();
```
Comment (conradoplg) [inline zebra-network/src/peer_set/limit.rs:230]: Optional: document why this needs to be called here

File: zebra-network/src/peer_set/limit.rs (hunk 1 above)
Comment (conradoplg) [reply zebra-network/src/peer_set/limit.rs]: Could you give more details?

**Review by conradoplg — CHANGES_REQUESTED** [review]
A couple of optional improvements suggested, but looks good, thanks

**Review by conradoplg — DISMISSED** [review]
A couple of optional improvements suggested, but looks good, thanks

File: zebra-network/src/peer_set/limit.rs (hunk 1 above)
Comment (arya2) [reply zebra-network/src/peer_set/limit.rs]: It could use just one channel with a more flexible message type instead of two channels, see https://github.com/ZcashFoundation/zebra/pull/10311/changes/bf6643e5c2a3fddf00061bae3b7c29bb1bf2a2f4

File: zebra-network/src/peer_set/limit.rs (hunk 3 above)
Comment (arya2) [reply zebra-network/src/peer_set/limit.rs:230]: Documented in https://github.com/ZcashFoundation/zebra/pull/10311/changes/89537ad415462da720e3ca19a99973427a021299.

File: zebra-network/src/peer_set/limit.rs (hunk 2 above)
Comment (arya2) [reply zebra-network/src/peer_set/limit.rs:184]: Added in https://github.com/ZcashFoundation/zebra/pull/10311/changes/89537ad415462da720e3ca19a99973427a021299.

**Review by conradoplg — APPROVED** [review]
