### PR TITLE
return errors from `send_periodic_heartbeats_with_shutdown_handle`

### LINKED ISSUE #4733: Return connection errors from the heartbeat task to the `Client`
## Motivation

We're seeing  "failed servers must set their error slot" panics when Zebra is overloaded.

This panic is caused by the design of the `Client` connection code. Currently, the `Client` tasks share an `ErrorSlot` mutex, which must be updated before they exit.

This ticket stops using the error slot in the heartbeat task.

### Designs

Instead of using the error slot, `Client` tasks should exit and return an error to the client instance.
The `Client` should exit when any task errors or stops.

We could try something like this:
(click for details)

<details>

Replace `Client.error_slot` with returning a `PeerError`:
- end the task when there is a permanent connection error, returning `Result<(), PeerError>’
- check the error via the `JoinHandle` in the `Client`
- shut down the `Client` when the heartbeat task exits or errors

</details>

## Related Work

This is part of:
- #3263

### PR DESCRIPTION
**Pull request by oxarbitrage**
## Motivation

We want to return errors from `send_periodic_heartbeats_with_shutdown_handle`. When finished this should close https://github.com/ZcashFoundation/zebra/issues/4733

Right now, this is a draft to ask @teor2345 some questions as i am unsure if this is complete. I think we can't remove `error_slot` yet as it is still used by the connection task.

## Solution

Return `Result` from `send_periodic_heartbeats_with_shutdown_handle`, then follow compiler to make it work.

## Review

@teor2345 , i am unsure if this is complete, that could be missing or if there are any problems. Will like you to take an initial look when you can. 

### Reviewer Checklist

  - [ ] Code implements Specs and Designs
  - [ ] Tests for Expected Behaviour
  - [ ] Tests for Errors

### CODE REVIEW

File: zebra-network/src/peer/client.rs [hunk 1]
```diff
@@ -438,7 +439,7 @@ impl Client {
                 // Heartbeat task is still running.
                 Ok(())
             }
-            Poll::Ready(Ok(())) => {
+            Poll::Ready(Ok(_)) => {
```
Comment (oxarbitrage) [inline zebra-network/src/peer/client.rs]: This and the panic below it generates me some doubts. Do you think we should return `Ok` here and `PeerError` below to avoid the panic ?

Comment (teor2345) [reply zebra-network/src/peer/client.rs]: Good catch, I think this is partly an existing bug.

Since we added a result to the JoinHandle, the type is now `Poll<Result<Result<(), PeerError>, JoinError>`.

There's a few different cases we need to handle:
- if the `Err` is [`JoinError::is_cancelled()`](https://docs.rs/tokio/latest/tokio/task/struct.JoinError.html#method.is_cancelled), then some other task told the heartbeat task to exit, so we can return a `PeerError` (feel free to make a new variant)
- if the `Err` is `JoinError::is_panic()`, then we need to re-panic here, we can't recover from a panic. There's [a good example of how to do that in the `JoinError::try_into_panic()` docs](https://docs.rs/tokio/latest/tokio/task/struct.JoinError.html#method.try_into_panic)
- if the inner result is a `Ok(Err(PeerError))`, we can return that error
- if the inner result is `Ok(Ok(()))`, we can return `PeerError::HeartbeatTaskExited`
- otherwise the `Poll::Pending` code stays the same

We missed the cancelled case when we last changed this code. Or it might be a new tokio feature, I'm not sure.

**Review by teor2345 — COMMENTED** [review]
This looks really good, it just needs a quick fix for the panic handling, as you said.

Good pickup on that bug, it seems like it's been there for a while.

File: zebra-network/src/peer/client.rs (hunk 1 above)
Comment (oxarbitrage) [reply zebra-network/src/peer/client.rs]: this is just an idea, i am ok on doing it  different https://github.com/ZcashFoundation/zebra/pull/4756/commits/90526e31fe78fbdd3dd43eab2cc4a5315fc36f89

Basically added an argument to `HeartbeatTaskExited`. Let me know how do you see it.

**Review by teor2345 — APPROVED** [review]
Thanks this looks great!

File: zebra-network/src/peer/client.rs (hunk 1 above)
Comment (teor2345) [reply zebra-network/src/peer/client.rs]: That's a great idea, it makes it clear that the heartbeat task stopped, whatever the error actually was.

**Comment by oxarbitrage** [comment]
@mergify update

**Comment by teor2345** [comment]
There are other tasks that are higher priority, so I moved this one to medium.
