### PR TITLE
Stop panicking when ClientRequests return an error

### LINKED ISSUE #1027: use exhaustive match statement in `peer/connection.rs`
based on a comment in code review

---

do we want to try to find a way to get exhaustive matching here?

_Originally posted by @yaahc in https://github.com/ZcashFoundation/zebra/pull/1016#discussion_r483852626_

### LINKED ISSUE #1471: Panic: ClientRequest oneshot sender must not be dropped
```
Dec 07 08:56:27.460  INFO {zebrad="5b687f87"}:sync:obtain_tips: zebra_network::peer_set::set: network request with no ready peers: finding more peers, waiting for 18 peers to answer requests
Dec 07 10:42:24.595  INFO {zebrad="5b687f87"}:peer{addr=185.153.231.82:8233}:msg_as_req{msg=getheaders}:inbound:state: zebra_state::service: responding to peer GetBlocks or GetHeaders final_height=Height(1067845) response_len=127 chain_tip_height=Height(1067845) stop_height=None intersection_height=Some(Height(1067718))
Dec 07 10:42:24.775  INFO {zebrad="5b687f87"}:peer{addr=47.253.0.14:8233}:msg_as_req{msg=getheaders}:inbound:state: zebra_state::service: responding to peer GetBlocks or GetHeaders final_height=Height(1067845) response_len=127 chain_tip_height=Height(1067845) stop_height=None intersection_height=Some(Height(1067718))
Dec 07 10:42:25.279  INFO {zebrad="5b687f87"}:peer{addr=47.94.92.186:8233}:msg_as_req{msg=getheaders}:inbound:state: zebra_state::service: responding to peer GetBlocks or GetHeaders final_height=Height(1067845) response_len=127 chain_tip_height=Height(1067845) stop_height=None intersection_height=Some(Height(1067718))
```

## Error
```
ClientRequest oneshot sender must not be dropped before send: Canceled
```

## Metadata
|key|value|
|--|--|
|**version**|3.0.0-alpha.0|
|**git commit**|5b687f87|
|**location**|zebra-network/src/peer/client.rs:84:26|

## SpanTrace

<details>

```
SpanTrace:
   0: zebrad::components::sync::obtain_tips
             at zebrad/src/components/sync.rs:255
   1: zebrad::components::sync::sync
             at zebrad/src/components/sync.rs:150
   2: zebrad::commands::
           with zebrad="5b687f87"
             at zebrad/src/commands.rs:56
```
</details>

## Backtrace

<details>

```
Backtrace:
   0: backtrace::backtrace::libunwind::trace
             at .cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.54/src/backtrace/libunwind.rs:90:5
      backtrace::backtrace::trace_unsynchronized
             at .cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.54/src/backtrace/mod.rs:66:5
   1: backtrace::backtrace::trace
             at .cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.54/src/backtrace/mod.rs:53:14
   2: backtrace::capture::Backtrace::create
             at .cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.54/src/capture.rs:176:9
   3: backtrace::capture::Backtrace::new
             at .cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.54/src/capture.rs:140:22
   4: color_eyre::config::PanicHook::panic_report
             at .cargo/registry/src/github.com-1ecc6299db9ec823/color-eyre-0.5.10/src/config.rs:982:18
   5: color_eyre::config::PanicHook::into_panic_hook::{{closure}}
             at .cargo/registry/src/github.com-1ecc6299db9ec823/color-eyre-0.5.10/src/config.rs:961:29
   6: std::panicking::rust_panic_with_hook
             at /rustc/1c389ffeff814726dec325f0f2b0c99107df2673/library/std/src/panicking.rs:595:17
   7: std::panicking::begin_panic_handler::{{closure}}
             at /rustc/1c389ffeff814726dec325f0f2b0c99107df2673/library/std/src/panicking.rs:497:13
   8: std::sys_common::backtrace::__rust_end_short_backtrace
             at /rustc/1c389ffeff814726dec325f0f2b0c99107df2673/library/std/src/sys_common/backtrace.rs:141:18
   9: rust_begin_unwind
             at /rustc/1c389ffeff814726dec325f0f2b0c99107df2673/library/std/src/panicking.rs:493:5
  10: core::panicking::panic_fmt
             at /rustc/1c389ffeff814726dec325f0f2b0c99107df2673/library/core/src/panicking.rs:92:14
  11: core::option::expect_none_failed
             at /rustc/1c389ffeff814726dec325f0f2b0c99107df2673/library/core/src/option.rs:1268:5
  12: core::result::Result<T,E>::expect
             at .rustup/toolchains/nightly-x86_64-apple-darwin/lib/rustlib/src/rust/library/core/src/result.rs:933:23

```
</details>

### LINKED ISSUE #1510: Panic: called fail_with on already-failed connection state
**Suggested Solution**

Stop calling `fail_with` on already-failed connection states.

**Detailed Logs**

*Click triangle to reveal logs* <details>
```
Dec 13 12:39:40.386  INFO {zebrad="83e72bdd"}:peer{addr=[2001:19f0:5001:d0a:5400:1ff:fed2:7142]:8233}:msg_as_req{msg=getheaders}:inbound:state: zebra_state::service: responding to peer GetBlocks or GetHeaders final_height=Height(550808) response_len=158 chain_tip_height=Height(597795) stop_height=None intersection_height=Some(Height(550650))
Dec 13 12:39:41.022  WARN {zebrad="83e72bdd"}:peer{addr=[2a01:4f9:3a:1055::2]:8233}:msg_as_req{msg=inv}: zebra_network::peer::connection: inbound service is overloaded, closing connection
The application panicked (crashed).
Message:  called fail_with on already-failed connection state
Location: /Users/rex/rex4539-zebra-peer-set-debug/zebra-network/src/peer/connection.rs:403

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ SPANTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  
   0: zebra_network::peer::connection::msg_as_req with msg=inv
      at zebra-network/src/peer/connection.rs:564
   1: zebra_network::peer::handshake::peer with addr=[2a01:4f9:3a:1055::2]:8233
      at zebra-network/src/peer/handshake.rs:198
   2: zebrad::commands:: with zebrad="83e72bdd"
      at zebrad/src/commands.rs:56

zebrad was compiled with optimization - stepping may behave oddly; variables may not be available.
Process 5701 stopped
* thread #12, name = 'tokio-runtime-worker', stop reason = breakpoint 10.6
    frame #0: 0x0000000101705404 zebrad`panic_abort::__rust_start_panic::abort::h19164e12d4c30869 at lib.rs:37:17 [opt]
Target 0: (zebrad) stopped.
(lldb) bt
error: need to add support for DW_TAG_base_type '()' encoded with DW_ATE = 0x7, bit_size = 0
error: need to add support for DW_TAG_base_type '()' encoded with DW_ATE = 0x7, bit_size = 0
error: need to add support for DW_TAG_base_type '()' encoded with DW_ATE = 0x7, bit_size = 0
error: need to add support for DW_TAG_base_type '()' encoded with DW_ATE = 0x7, bit_size = 0
error: need to add support for DW_TAG_base_type '()' encoded with DW_ATE = 0x7, bit_size = 0
error: need to add support for DW_TAG_base_type '()' encoded with DW_ATE = 0x7, bit_size = 0
* thread #12, name = 'tokio-runtime-worker', stop reason = breakpoint 10.6
  * frame #0: 0x0000000101705404 zebrad`panic_abort::__rust_start_panic::abort::h19164e12d4c30869 at lib.rs:37:17 [opt]
    frame #1: 0x00000001017053e9 zebrad`__rust_start_panic at lib.rs:32:5 [opt]
    frame #2: 0x00000001016f7f89 zebrad`rust_panic at panicking.rs:640:9 [opt]
    frame #3: 0x00000001016f7f3f zebrad`std::panicking::rust_panic_with_hook::hbb70e1d25c7381a9 at panicking.rs:610:5 [opt]
    frame #4: 0x00000001016aafa7 zebrad`std::panicking::begin_panic::_$u7b$$u7b$closure$u7d$$u7d$::hf9c0b57a1c79da14 at panicking.rs:520:9
    frame #5: 0x00000001016abca8 zebrad`std::sys_common::backtrace::__rust_end_short_backtrace::h0e2da18db7995d52(f=<unavailable>) at backtrace.rs:141:18
    frame #6: 0x0000000101728b05 zebrad`std::panicking::begin_panic::h9ef23acf7776d7ab(msg=(data_ptr = "called fail_with on already-failed connection state", length = 51)) at panicking.rs:519:12
    frame #7: 0x00000001001cfbb9 zebrad`zebra_network::peer::connection::Connection$LT$S$C$Tx$GT$::fail_with::ha59aa07ae52c808a(self=0x0000000107881430, e=PeerError @ 0x00007000064430f8) at connection.rs:403:13
    frame #8: 0x00000001001bee9e zebrad`zebra_network::peer::connection::Connection$LT$S$C$Tx$GT$::drive_peer_request::_$u7b$$u7b$closure$u7d$$u7d$::h05c50702d04614ad((null)=ResumeTy @ 0x00007000064444b8) at connection.rs:686:21
    frame #9: 0x00000001001b8a00 zebrad`_$LT$core..future..from_generator..GenFuture$LT$T$GT$$u20$as$u20$core..future..future..Future$GT$::poll::h3ef57d778b32e83a(self=Pin<&mut core::future::from_generator::GenFuture<generator-0>> @ 0x0000700006444880, cx=0x000070000644c1f8) at mod.rs:80:19
    frame #10: 0x00000001001c9f33 zebrad`zebra_network::peer::connection::Connection$LT$S$C$Tx$GT$::handle_message_as_request::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::hefc3a654c771665a((null)=ResumeTy @ 0x0000700006447250) at connection.rs:664:9
    frame #11: 0x00000001001bb0e0 zebrad`_$LT$core..future..from_generator..GenFuture$LT$T$GT$$u20$as$u20$core..future..future..Future$GT$::poll::hd8d08677772c8fb2(self=Pin<&mut core::future::from_generator::GenFuture<generator-0>> @ 0x0000700006447a10, cx=0x000070000644c1f8) at mod.rs:80:19
    frame #12: 0x000000010017ce26 zebrad`_$LT$tracing_futures..Instrumented$LT$T$GT$$u20$as$u20$core..future..future..Future$GT$::poll::h8a6419eff233aa57(self=Pin<&mut tracing_futures::Instrumented<core::future::from_generator::GenFuture<generator-0>>> @ 0x0000700006447a70, cx=0x000070000644c1f8) at lib.rs:258:9
    frame #13: 0x00000001001c5001 zebrad`zebra_network::peer::connection::Connection$LT$S$C$Tx$GT$::handle_message_as_request::_$u7b$$u7b$closure$u7d$$u7d$::h2337c24c8c300ad3((null)=ResumeTy @ 0x0000700006448408) at connection.rs:565:65
    frame #14: 0x00000001001bb6b0 zebrad`_$LT$core..future..from_generator..GenFuture$LT$T$GT$$u20$as$u20$core..future..future..Future$GT$::poll::he532a3acac8ce952(self=Pin<&mut core::future::from_generator::GenFuture<generator-0>> @ 0x0000700006448560, cx=0x000070000644c1f8) at mod.rs:80:19
    frame #15: 0x00000001001ccae6 zebrad`zebra_network::peer::connection::Connection$LT$S$C$Tx$GT$::run::_$u7b$$u7b$closure$u7d$$u7d$::h9f032ec50735c9c3((null)=ResumeTy @ 0x000070000644b960) at connection.rs:325:33
    frame #16: 0x00000001001ba1e0 zebrad`_$LT$core..future..from_generator..GenFuture$LT$T$GT$$u20$as$u20$core..future..future..Future$GT$::poll::h9682f4974cebd320(self=Pin<&mut core::future::from_generator::GenFuture<generator-0>> @ 0x000070000644bff0, cx=0x000070000644c1f8) at mod.rs:80:19
    frame #17: 0x000000010017cdc6 zebrad`_$LT$tracing_futures..Instrumented$LT$T$GT$$u20$as$u20$core..future..future..Future$GT$::poll::h86941f3385faae37(self=Pin<&mut tracing_futures::Instrumented<core::future::from_generator::GenFuture<generator-0>>> @ 0x000070000644c050, cx=0x000070000644c1f8) at lib.rs:258:9
    frame #18: 0x0000000101146ade zebrad`_$LT$core..pin..Pin$LT$P$GT$$u20$as$u20$core..future..future..Future$GT$::poll::h622e917129b495f7(self=Pin<&mut core::pin::Pin<alloc::boxed::Box<Future, alloc::alloc::Global>>> @ 0x000070000644c0b0, cx=0x000070000644c1f8) at future.rs:119:9
    frame #19: 0x00000001010d2b26 zebrad`_$LT$tracing..instrument..Instrumented$LT$T$GT$$u20$as$u20$core..future..future..Future$GT$::poll::h7a906c52db28be88(self=Pin<&mut tracing::instrument::Instrumented<core::pin::Pin<alloc::boxed::Box<Future, alloc::alloc::Global>>>> @ 0x000070000644c130, cx=0x000070000644c1f8) at instrument.rs:151:9
    frame #20: 0x0000000101145d5a zebrad`tokio::runtime::task::core::Core$LT$T$C$S$GT$::poll::_$u7b$$u7b$closure$u7d$$u7d$::h628814ee330d4d0c(ptr=0x0000000105f4ae68) at core.rs:173:17
    frame #21: 0x00000001011106b5 zebrad`tokio::loom::std::unsafe_cell::UnsafeCell$LT$T$GT$::with_mut::h0676b7d2d2c541da(self=0x0000000105f4ae68, f=closure-0 @ 0x000070000644c278) at unsafe_cell.rs:14:9
    frame #22: 0x0000000101145aa1 zebrad`tokio::runtime::task::core::Core$LT$T$C$S$GT$::poll::h71522dbdd7e32077(self=0x0000000105f4ae60, header=0x0000000105f4ae30) at core.rs:158:13
    frame #23: 0x00000001010c7606 zebrad`tokio::runtime::task::harness::Harness$LT$T$C$S$GT$::poll::_$u7b$$u7b$closure$u7d$$u7d$::h52bd7bd0b557226e at harness.rs:107:27
    frame #24: 0x00000001010cdaf0 zebrad`core::ops::function::FnOnce::call_once::hfac0dbd1acdb912f((null)=closure-0 @ 0x000070000644c398, (null)=<unavailable>) at function.rs:227:5
    frame #25: 0x000000010114904c zebrad`_$LT$std..panic..AssertUnwindSafe$LT$F$GT$$u20$as$u20$core..ops..function..FnOnce$LT$$LP$$RP$$GT$$GT$::call_once::hb7f9c0a74e7018d3(self=AssertUnwindSafe<closure-0> @ 0x000070000644c3e0, _args=<unavailable>) at panic.rs:322:9
    frame #26: 0x000000010111b956 zebrad`std::panicking::try::do_call::h5bb2d87997087cc5(data="??D\x06") at panicking.rs:379:40
    frame #27: 0x000000010111b4d9 zebrad`std::panicking::try::h3bdc0c4ac4854659(f=AssertUnwindSafe<closure-0> @ 0x000070000644c5a0) at panicking.rs:343:19
    frame #28: 0x000000010114913c zebrad`std::panic::catch_unwind::h9e29a98a2da32ebe(f=AssertUnwindSafe<closure-0> @ 0x000070000644c610) at panic.rs:396:14
    frame #29: 0x00000001010c6de1 zebrad`tokio::runtime::task::harness::Harness$LT$T$C$S$GT$::poll::h11caab30e96fb3ad(self=Harness<tracing::instrument::Instrumented<core::pin::Pin<alloc::boxed::Box<Future, alloc::alloc::Global>>>, alloc::sync::Arc<tokio::runtime::thread_pool::worker::Worker>> @ 0x000070000644c6b0) at harness.rs:89:19
    frame #30: 0x000000010112f412 zebrad`tokio::runtime::task::raw::poll::h5048e0f4b40e7490(ptr=NonNull<tokio::runtime::task::core::Header> @ 0x000070000644c820) at raw.rs:104:5
    frame #31: 0x000000010160515e zebrad`tokio::runtime::task::raw::RawTask::poll::hc89e5bc150a57c52(self=RawTask @ 0x000070000644c850) at raw.rs:66:18
    frame #32: 0x0000000101646d35 zebrad`tokio::runtime::task::Notified$LT$S$GT$::run::ha2ee5c84333c4156(self=Notified<alloc::sync::Arc<tokio::runtime::thread_pool::worker::Worker>> @ 0x000070000644c878) at mod.rs:171:9
    frame #33: 0x0000000101605fec zebrad`tokio::runtime::thread_pool::worker::Context::run_task::_$u7b$$u7b$closure$u7d$$u7d$::hab67772daa1796dd at worker.rs:346:13
    frame #34: 0x0000000101643fde zebrad`tokio::coop::with_budget::_$u7b$$u7b$closure$u7d$$u7d$::h8844a16f5ff90b15(cell=0x0000000109008e22) at coop.rs:121:9
    frame #35: 0x000000010165ce3b zebrad`std::thread::local::LocalKey$LT$T$GT$::try_with::hbd5fcf16e5f1c295(self=0x0000000101996e48, f=closure-0 @ 0x000070000644ca90) at local.rs:272:16
    frame #36: 0x000000010165bd1c zebrad`std::thread::local::LocalKey$LT$T$GT$::with::hda68ae8d7d88b19a(self=0x0000000101996e48, f=<unavailable>) at local.rs:248:9
    frame #37: 0x0000000101605f93 zebrad`tokio::runtime::thread_pool::worker::Context::run_task::he75bd550cde8a541 [inlined] tokio::coop::with_budget::h1542830cccad9c0d(budget=(__0 = core::option::Option<u8> @ 0x000070000644cb68), f=closure-0 @ 0x000070000644cb70) at coop.rs:114:5
    frame #38: 0x0000000101605f77 zebrad`tokio::runtime::thread_pool::worker::Context::run_task::he75bd550cde8a541 [inlined] tokio::coop::budget::hbd3a5760b4b06b29(f=closure-0 @ 0x000070000644cb40) at coop.rs:98
    frame #39: 0x0000000101605f47 zebrad`tokio::runtime::thread_pool::worker::Context::run_task::he75bd550cde8a541(self=0x000070000644cd78, task=Notified<alloc::sync::Arc<tokio::runtime::thread_pool::worker::Worker>> @ 0x000070000644cb30, core=0x0000000105908fa0) at worker.rs:345
    frame #40: 0x0000000101605cb7 zebrad`tokio::runtime::thread_pool::worker::Context::run::hb0246eebe05e624c(self=0x000070000644cd78, core=0x0000000105908fa0) at worker.rs:317:24
    frame #41: 0x0000000101605b95 zebrad`tokio::runtime::thread_pool::worker::run::_$u7b$$u7b$closure$u7d$$u7d$::h8e5b550afab8865d at worker.rs:302:17
    frame #42: 0x0000000101654ef3 zebrad`tokio::macros::scoped_tls::ScopedKey$LT$T$GT$::set::hc7b1486b701f362f(self=0x0000000101997108, t=0x000070000644cd78, f=closure-0 @ 0x000070000644cd08) at scoped_tls.rs:61:9
    frame #43: 0x0000000101605b58 zebrad`tokio::runtime::thread_pool::worker::run::h8f2f8de5d0b46d36(worker=Arc<tokio::runtime::thread_pool::worker::Worker> @ 0x000070000644cd60) at worker.rs:299:5
    frame #44: 0x0000000101605a61 zebrad`tokio::runtime::thread_pool::worker::Launch::launch::_$u7b$$u7b$closure$u7d$$u7d$::h140892baace04f3e at worker.rs:278:45
    frame #45: 0x0000000101620538 zebrad`tokio::runtime::handle::Handle::spawn_blocking::_$u7b$$u7b$closure$u7d$$u7d$::hf5b5485d1b6e6d8d at handle.rs:196:17
    frame #46: 0x000000010161a3ad zebrad`_$LT$tokio..runtime..blocking..task..BlockingTask$LT$T$GT$$u20$as$u20$core..future..future..Future$GT$::poll::h644b2a0df9510d47(self=Pin<&mut tokio::runtime::blocking::task::BlockingTask<closure-0>> @ 0x000070000644ce40, _cx=0x000070000644cf88) at task.rs:42:21
    frame #47: 0x000000010161f27a zebrad`tokio::runtime::task::core::Core$LT$T$C$S$GT$::poll::_$u7b$$u7b$closure$u7d$$u7d$::hd12bee239e809f69(ptr=0x0000000105f04650) at core.rs:173:17
    frame #48: 0x000000010162e795 zebrad`tokio::loom::std::unsafe_cell::UnsafeCell$LT$T$GT$::with_mut::he8150f8a6a43b4fd(self=0x0000000105f04650, f=closure-0 @ 0x000070000644d008) at unsafe_cell.rs:14:9
    frame #49: 0x000000010161f11b zebrad`tokio::runtime::task::core::Core$LT$T$C$S$GT$::poll::hd9228082ccf0d0e9(self=0x0000000105f04650, header=0x0000000105f04620) at core.rs:158:13
    frame #50: 0x0000000101648dc6 zebrad`tokio::runtime::task::harness::Harness$LT$T$C$S$GT$::poll::_$u7b$$u7b$closure$u7d$$u7d$::hb9c59f2cbebf8957 at harness.rs:107:27
    frame #51: 0x00000001016615c0 zebrad`core::ops::function::FnOnce::call_once::hc1451c26209a52cb((null)=closure-0 @ 0x000070000644d128, (null)=<unavailable>) at function.rs:227:5
    frame #52: 0x000000010162119c zebrad`_$LT$std..panic..AssertUnwindSafe$LT$F$GT$$u20$as$u20$core..ops..function..FnOnce$LT$$LP$$RP$$GT$$GT$::call_once::h4d7f8d3bbf2d6c76(self=AssertUnwindSafe<closure-0> @ 0x000070000644d170, _args=<unavailable>) at panic.rs:322:9
    frame #53: 0x0000000101654bb6 zebrad`std::panicking::try::do_call::hf3bd26e5cd7d5ccb(data="@?D\x06") at panicking.rs:379:40
    frame #54: 0x00000001016547c9 zebrad`std::panicking::try::h6744a753065b3609(f=AssertUnwindSafe<closure-0> @ 0x000070000644d330) at panicking.rs:343:19
    frame #55: 0x000000010162218c zebrad`std::panic::catch_unwind::h0e6df765d0ec468f(f=AssertUnwindSafe<closure-0> @ 0x000070000644d3a0) at panic.rs:396:14
    frame #56: 0x0000000101648a91 zebrad`tokio::runtime::task::harness::Harness$LT$T$C$S$GT$::poll::h3fdafeeae85a3c02(self=Harness<tokio::runtime::blocking::task::BlockingTask<closure-0>, tokio::runtime::blocking::schedule::NoopSchedule> @ 0x000070000644d440) at harness.rs:89:19
    frame #57: 0x00000001016052a2 zebrad`tokio::runtime::task::raw::poll::hef8c96fa66648c7c(ptr=NonNull<tokio::runtime::task::core::Header> @ 0x000070000644d5b0) at raw.rs:104:5
    frame #58: 0x000000010160515e zebrad`tokio::runtime::task::raw::RawTask::poll::hc89e5bc150a57c52(self=RawTask @ 0x000070000644d5e0) at raw.rs:66:18
    frame #59: 0x0000000101646d05 zebrad`tokio::runtime::task::Notified$LT$S$GT$::run::h3b1927b24bcba4fa(self=Notified<tokio::runtime::blocking::schedule::NoopSchedule> @ 0x000070000644d608) at mod.rs:171:9
    frame #60: 0x0000000101612546 zebrad`tokio::runtime::blocking::pool::Inner::run::h1dbc71d4a7461847(self=0x0000000105909650, worker_thread_id=10) at pool.rs:277:17
    frame #61: 0x00000001016123f5 zebrad`tokio::runtime::blocking::pool::Spawner::spawn_thread::_$u7b$$u7b$closure$u7d$$u7d$::hcf03f17bdb61a19e at pool.rs:257:17
    frame #62: 0x00000001015fb384 zebrad`std::sys_common::backtrace::__rust_begin_short_backtrace::h4f8b7f40a5d5b31a(f=<unavailable>) at backtrace.rs:125:18
    frame #63: 0x00000001016236e1 zebrad`std::thread::Builder::spawn_unchecked::_$u7b$$u7b$closure$u7d$$u7d$::_$u7b$$u7b$closure$u7d$$u7d$::hff51272d10ede402 at mod.rs:474:17
    frame #64: 0x00000001016211e1 zebrad`_$LT$std..panic..AssertUnwindSafe$LT$F$GT$$u20$as$u20$core..ops..function..FnOnce$LT$$LP$$RP$$GT$$GT$::call_once::h6f19d153361e8a6d(self=<unavailable>, _args=<unavailable>) at panic.rs:322:9
    frame #65: 0x0000000101654b25 zebrad`std::panicking::try::do_call::h2fb91f3a2381eb34(data="\x01") at panicking.rs:379:40
    frame #66: 0x0000000101654a33 zebrad`std::panicking::try::h99adac12e42dfae6(f=<unavailable>) at panicking.rs:343:19
    frame #67: 0x0000000101622201 zebrad`std::panic::catch_unwind::he3386189a2f52b0d(f=<unavailable>) at panic.rs:396:14
    frame #68: 0x00000001016235fd zebrad`std::thread::Builder::spawn_unchecked::_$u7b$$u7b$closure$u7d$$u7d$::hdaf74289515ee884 at mod.rs:473:30
    frame #69: 0x0000000101661151 zebrad`core::ops::function::FnOnce::call_once$u7b$$u7b$vtable.shim$u7d$$u7d$::hb5cfd68db5d3e283((null)=0x000000010590ac10, (null)=<unavailable>) at function.rs:227:5
    frame #70: 0x00000001016fb76d zebrad`std::sys::unix::thread::Thread::new::thread_start::h93dd3097fa4fa219 [inlined] _$LT$alloc..boxed..Box$LT$F$C$A$GT$$u20$as$u20$core..ops..function..FnOnce$LT$Args$GT$$GT$::call_once::h1658d06ba2d41cb5 at boxed.rs:1328:9 [opt]
    frame #71: 0x00000001016fb767 zebrad`std::sys::unix::thread::Thread::new::thread_start::h93dd3097fa4fa219 [inlined] _$LT$alloc..boxed..Box$LT$F$C$A$GT$$u20$as$u20$core..ops..function..FnOnce$LT$Args$GT$$GT$::call_once::h747cc083e7349205 at boxed.rs:1328 [opt]
    frame #72: 0x00000001016fb75e zebrad`std::sys::unix::thread::Thread::new::thread_start::h93dd3097fa4fa219 at thread.rs:71 [opt]
    frame #73: 0x00007fff20357950 libsystem_pthread.dylib`_pthread_start + 224
    frame #74: 0x00007fff2035347b libsystem_pthread.dylib`thread_start + 15
```
</details>

## Error
```
called fail_with on already-failed connection state
```

## Metadata
|key|value|
|--|--|
|**version**|3.0.0-alpha.0|
|**git commit**|83e72bdd|
|**location**|/Users/rex/rex4539-zebra-peer-set-debug/zebra-network/src/peer/connection.rs:403:13|

## SpanTrace

<details>

```
SpanTrace:
   0: zebra_network::peer::connection::msg_as_req
           with msg=inv
             at zebra-network/src/peer/connection.rs:564
   1: zebra_network::peer::handshake::peer
           with addr=[2a01:4f9:3a:1055::2]:8233
             at zebra-network/src/peer/handshake.rs:198
   2: zebrad::commands::
           with zebrad="83e72bdd"
             at zebrad/src/commands.rs:56
```
</details>

## BackTrace

<details>

```
  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   1: backtrace::backtrace::libunwind::trace::h56b5b89d46ea18ee
      at /Users/rex/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.54/src/backtrace/libunwind.rs:90
        88 │ #[inline(always)]
        89 │ pub unsafe fn trace(mut cb: &mut dyn FnMut(&super::Frame) -> bool) {
        90 >     uw::_Unwind_Backtrace(trace_fn, &mut cb as *mut _ as *mut _);
        91 │ 
        92 │     extern "C" fn trace_fn(
   2: backtrace::backtrace::trace_unsynchronized::h456d388ebbb97b58
      at /Users/rex/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.54/src/backtrace/mod.rs:66
        64 │ /// See information on `trace` for caveats on `cb` panicking.
        65 │ pub unsafe fn trace_unsynchronized<F: FnMut(&Frame) -> bool>(mut cb: F) {
        66 >     trace_imp(&mut cb)
        67 │ }
        68 │ 
   3: backtrace::backtrace::trace::h0c2ee1e6653540fd
      at /Users/rex/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.54/src/backtrace/mod.rs:53
        51 │ pub fn trace<F: FnMut(&Frame) -> bool>(cb: F) {
        52 │     let _guard = crate::lock::lock();
        53 >     unsafe { trace_unsynchronized(cb) }
        54 │ }
        55 │ 
   4: backtrace::capture::Backtrace::create::h8d054d598eb8a93e
      at /Users/rex/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.54/src/capture.rs:176
       174 │         let mut frames = Vec::new();
       175 │         let mut actual_start_index = None;
       176 >         trace(|frame| {
       177 │             frames.push(BacktraceFrame {
       178 │                 frame: Frame::Raw(frame.clone()),
   5: backtrace::capture::Backtrace::new::h89e80605e5dd4af5
      at /Users/rex/.cargo/registry/src/github.com-1ecc6299db9ec823/backtrace-0.3.54/src/capture.rs:140
       138 │     #[inline(never)] // want to make sure there's a frame here to remove
       139 │     pub fn new() -> Backtrace {
       140 >         let mut bt = Self::create(Self::new as usize);
       141 │         bt.resolve();
       142 │         bt
   6: color_eyre::config::PanicHook::panic_report::h35620cffb3b3e3a3
      at /Users/rex/.cargo/registry/src/github.com-1ecc6299db9ec823/color-eyre-0.5.10/src/config.rs:982
       980 │ 
       981 │         let backtrace = if capture_bt {
       982 >             Some(backtrace::Backtrace::new())
       983 │         } else {
       984 │             None
```

</details>

### PR DESCRIPTION
**Pull request by teor2345**
## Motivation

Zebra's connection-handling code panics because it drops the ClientRequest oneshot sender in the error case (#1471).

## Solution

- call ClientRequest.tx.send even if there is an error
- document this invariant

The code in this pull request has:
  - [x] Documentation Comments
  - No tests 😞
  - A future test plan - see #1515 and #1048

## Review

I need @yaahc's help with some ownership issues.

## Related Issues

Closes #1471
Closes #1510 - fixes at least one known cause of this panic

Closes #1027 - matches are now exhaustive (some patterns contain partial wildcards, but those matches are panics)

Partial work on #1435 - fixes multiple potential hangs, but testing shows we still sometimes end up with an empty or very small peer set

## Follow Up Work

Refactor zebra-network Bitcoin to Zebra protocol translation layer #1515
Test translation for zebra-network::{Request, Response} protocol #1048
Split up the large files and functions in zebra-network #1557

Check that these panics are resolved:
- Panic: ClientRequest oneshot sender must not be dropped #1471
- Panic: called fail_with on already-failed connection state #1510

Make heartbeats timeout if the connection request queue stays full #1551

### CODE REVIEW

File: zebra-network/src/peer/connection.rs [hunk 1]
```diff
@@ -585,7 +586,10 @@ where
                 .peer_tx
                 .send(Message::Mempool)
                 .await
-                .map_err(|e| e.into())
+                // TODO: work out how to re-use `tx`
+                // `tx` is only used once, in either the error or the result,
+                // but rustc doesn't know that
```
Comment (teor2345) [inline zebra-network/src/peer/connection.rs]: @yaahc I don't know how to use tx in both `map` and `map_err`.

Should we leave the result as it is, and create the `AwaitingResponse` in the outer match?

File: zebra-network/src/peer/connection.rs [hunk 2]
```diff
@@ -598,31 +602,38 @@ where
...
                 self.state = new_state;
                 self.request_timer = Some(sleep(constants::REQUEST_TIMEOUT));
             }
-            Err(e) => self.fail_with(e),
+            Err((e, Some(tx))) => {
+                // TODO: work out how to re-use `e`
+                // copy and clone don't work here, because some of the source
+                // errors don't implement copy or clone
+                tx.send(Err(SharedPeerError::from(e)));
+                self.fail_with(e);
```
Comment (teor2345) [inline zebra-network/src/peer/connection.rs]: @yaahc I don't know how to use `e` in both `tx.send` and `self.fail_with`.

I can't work out how to impl `Copy` or `Clone` for `e`, because some of its sources don't impl `Copy` or `Clone`.

Comment (teor2345) [reply zebra-network/src/peer/connection.rs]: I think the solution here is to convert to SharedPeerError, and change fail_with to take `Into<SharedPeerError>`.

File: zebra-network/src/peer/connection.rs (hunk 1 above)
Comment (yaahc) [reply zebra-network/src/peer/connection.rs]: I don't think that will be necessary, if you just write out the `map` and `map_err` as a `match expr { Ok(e) => Ok(<expression>), Err(e) => Err(<expression>), }` it should be able to prove that the cases are mutually exclusive and will let you reuse the same variable in both.

File: zebra-network/src/peer/connection.rs (hunk 2 above)
Comment (yaahc) [reply zebra-network/src/peer/connection.rs]: Sounds good. I'm pretty sure `SharedPeerError` only exists in the first place to make `e` clone, so just converting it a little earlier makes perfect sense to me.

File: zebra-network/src/peer/connection.rs [hunk 3]
```diff
@@ -506,123 +509,143 @@ where
 
         // XXX(hdevalence) this is truly horrible, but let's fix it later
 
-        // Inner match returns Result with the new state or an error.
-        // Outer match updates state or fails.
+        // Inner matches return a Result with a new state or an (error, Option<oneshot::Sender>)
+        // Middle match returns Result with the new state or the (error, Option<oneshot::Sender>)
+        // Outer match updates state or fails, and sends the error on the Sender if it is Some
```
Comment (teor2345) [inline zebra-network/src/peer/connection.rs]: Now we have 3 layers of matches, which is very very horrible, so we should fix it now 😱

File: zebra-network/src/peer/connection.rs [hunk 4]
```diff
@@ -458,7 +458,10 @@ where
     }
 
     /// Marks the peer as having failed with error `e`.
-    fn fail_with(&mut self, e: PeerError) {
+    fn fail_with<E>(&mut self, e: E)
+    where
+        E: Into<SharedPeerError> + fmt::Display,
+    {
         debug!(%e, "failing peer service with error");
```
Comment (teor2345) [inline zebra-network/src/peer/connection.rs]: Call `let e = e.into();` first to avoid `E: fmt::Display`

File: zebra-network/src/peer/connection.rs [hunk 5]
```diff
@@ -506,123 +509,143 @@ where
...
                     .await
-                    .map_err(|e| e.into())
-                    .map(|()| AwaitingRequest)
+                {
+                    Ok(()) => Ok(AwaitingRequest),
+                    Err(e) => Err((e, None)),
+                }
             }
             (AwaitingRequest, AdvertiseBlock(hash)) => {
                 let _ = tx.send(Ok(Response::Nil));
```
Comment (teor2345) [inline zebra-network/src/peer/connection.rs]: Move these sends to the outer match

File: zebra-network/src/peer/client.rs [hunk 6]
```diff
@@ -25,11 +25,14 @@ pub struct Client {
 
 /// A message from the `peer::Client` to the `peer::Server`.
 #[derive(Debug)]
+#[must_use = "tx.send() must be called before drop"]
```
Comment (teor2345) [inline zebra-network/src/peer/client.rs]: Add `MustUseSender` with a `send` method and an optional sender.

File: zebra-network/src/peer/connection.rs (hunk 1 above)
Comment (teor2345) [reply zebra-network/src/peer/connection.rs]: Fixed in 12fec92cc43e198127d567498809c215f96a57c4

File: zebra-network/src/peer/connection.rs (hunk 2 above)
Comment (teor2345) [reply zebra-network/src/peer/connection.rs]: Fixed in 12fec92cc43e198127d567498809c215f96a57c4

File: zebra-network/src/peer/connection.rs (hunk 3 above)
Comment (teor2345) [reply zebra-network/src/peer/connection.rs]: Fixed in 6ed420ee238a031eb57b152e816663e0c98880ff

File: zebra-network/src/peer/connection.rs (hunk 4 above)
Comment (teor2345) [reply zebra-network/src/peer/connection.rs]: Fixed in 404afb220c3537718823ce68cae6c57eec8c2d17

File: zebra-network/src/peer/connection.rs (hunk 5 above)
Comment (teor2345) [reply zebra-network/src/peer/connection.rs]: Fixed in 97137259ad35d6ecaa5231794373fb9a47e3d702.

This change also fixes a bug where `AwaitingRequest` would not send errors back to the caller.

Comment (teor2345) [reply zebra-network/src/peer/connection.rs]: It's not as clean as I might like.

I tried to just move `tx` into the `AwaitingResponse`s, but rustc couldn't prove that tx was being moved correctly, so I got compiler errors.

**Review by yaahc — COMMENTED** [review]
looks good though it's missing the MustUseSender change that we talked about. Are you planning on doing that as a follow up? My preference would be to do it as part of this PR or to implement the follow up PR before merging this just so we make sure to get that change done, I feel that it is important.

**Comment by teor2345** [comment]
> looks good though it's missing the MustUseSender change that we talked about

I didn't have time to finish `MustUseSender` before I went on leave.
I'm not sure if you saw my message on Discord?

> Are you planning on doing that as a follow up?

Now I'm back from leave, I'll start work on this change.

> My preference would be to do it as part of this PR or to implement the follow up PR before merging this just so we make sure to get that change done, I feel that it is important.

I agree that this is an important change, but I don't think we need to block this PR merging to make it happen.

In general, I'd like to be able to merge PRs once they contain a cohesive set of improvements, even if there is still some follow-up work. I'd like to manage task priority using our project management processes, rather than by blocking code merges. (If a follow-up task is important, it should be at the top of my list of priorities.)

Merging PRs as soon as they're ready helps me:
- avoid a large stack of PRs that all depend on each other
- avoid conflicts with other PRs
- resolve bugs - we're still getting bug reports for #1510, and this PR contains a (partial?) fix 

That said, if you think there's a significant risk of bugs in this PR, and the `MustUseSender` change will help us fix them, I'm happy to delay merging until it's done.

**Comment by teor2345** [comment]
I force-pushed to rebase on `main` after #1518 merged

**Comment by teor2345** [comment]
I'm getting a panic, but I can't work out why, because the backtrace and span info doesn't contain anything useful.

The panic handler tells me to use:
```
export RUST_BACKTRACE=full
export COLORBT_SHOW_HIDDEN=1
```

I've also tried:
```
export RUST_LIB_BACKTRACE=full
```

But the panic handler still says:
```
Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.
```

Here's what I see in the logs when `zebrad` panics:
```
Jan 04 20:03:01.821  INFO {zebrad="5f6f914"}:sync: zebrad::components::sync: exhausted prospective tip set                                                                                    
Jan 04 20:03:01.821  INFO {zebrad="5f6f914"}:sync: zebrad::components::sync: waiting to restart sync timeout=45s                                                                              
The application panicked (crashed).                                                                                                                                                            
Message:  unused oneshot sender: oneshot must be used or canceled: MustUseOneshotSender { tx: Some(Sender { inner: Inner { complete: false, data: Lock { locked: false, data: UnsafeCell }, rx_
task: Lock { locked: false, data: UnsafeCell }, tx_task: Lock { locked: false, data: UnsafeCell } } }) }                           
Location: zebra-network/src/peer/client.rs:108
                                                                                                                                                                                               
   
   0: zebra_network::peer::client::drop
      at zebra-network/src/peer/client.rs:105
       103 │ 
       104 │ impl<T: std::fmt::Debug> Drop for MustUseOneshotSender<T> {
       105 >     #[instrument(skip(self))]
       106 │     fn drop(&mut self) {
       107 │         // is_canceled() will not panic, because we check is_none() first

   1: color_eyre::config::PanicHook::panic_report::hdd2544fa14f3a5ff
      at <unknown source file>:<unknown line>
   2: <zebrad::application::ZebradApp as abscissa_core::application::Application>::register_components::{{closure}}::h925c0d278f45a09b
      at <unknown source file>:<unknown line>

Run with COLORBT_SHOW_HIDDEN=1 environment variable to disable frame filtering.

Consider reporting this error using this URL: ...
```

**Comment by teor2345** [comment]
Running a debug build, it looks like the MustUseOneshotSender is being dropped in a future's `poll` method:
https://github.com/rust-lang/futures-rs/blob/bde29dad82b7d8021c0a7c19aa059db7673ef822/futures-util/src/sink/send.rs#L43

So we might need to satisfy the invariant by sending an error on drop, rather than panicking on drop.
 
```
Jan 04 20:48:35.927  INFO {zebrad="5f6f9148"}:peer{addr=47.100.175.51:8233}:run:msg_as_req{msg=getheaders}:inbound:state: zebra_state::service: responding to peer GetBlocks or GetHeaders fina
l_height=Height(1100149) response_len=0 chain_tip_height=Height(1100149) stop_height=None intersection_height=Some(Height(1100149))                                                            
━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ BACKTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━                                                                                                               
 1: <zebra_network::peer::client::MustUseOneshotSender<T> as core::ops::drop::Drop>::drop::h85129a05c1c6d310                                                                                   
    at /home/dev/zebra/zebra-network/src/peer/client.rs:108                                                                                                                                    
 2: core::ptr::drop_in_place::h8cfdcf1a959ff012                                                                                                                                                
    at /home/dev/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:179                                                                      
 3: core::ptr::drop_in_place::hfb6669f9b48181bb                                                                                                                                                
    at /home/dev/.rustup/toolchains/nightly-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/library/core/src/ptr/mod.rs:179
 4: <futures_util::sink::send::Send<Si,Item> as core::future::future::Future>::poll::h59fdc635e3c99e94
    at /home/dev/.cargo/registry/src/github.com-1ecc6299db9ec823/futures-util-0.3.8/src/sink/send.rs:43
The application panicked (crashed).
Message:  unused oneshot sender: oneshot must be used or canceled: MustUseOneshotSender { tx: Some(Sender { inner: Inner { complete: false, data: Lock { locked: false, data: UnsafeCell }, rx_
task: Lock { locked: false, data: UnsafeCell }, tx_task: Lock { locked: false, data: UnsafeCell } } }) }
Location: zebra-network/src/peer/client.rs:114

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ SPANTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
   
   0: zebra_network::peer::client::drop
      at zebra-network/src/peer/client.rs:105
```

File: zebra-network/src/peer/client.rs [hunk 7]
```diff
@@ -25,17 +25,100 @@ pub struct Client {
...
 pub(super) struct ClientRequest {
     /// The actual request.
     pub request: Request,
     /// The return message channel, included because `peer::Client::call` returns a
     /// future that may be moved around before it resolves.
-    pub tx: oneshot::Sender<Result<Response, SharedPeerError>>,
+    ///
+    /// INVARIANT: `tx.send()` must be called before dropping `tx`.
```
Comment (yaahc) [inline zebra-network/src/peer/client.rs:60]: Can we add a comment explaining why this invariant is necessary?
```suggestion
    /// INVARIANT: `tx.send()` must be called before dropping `tx`.
    ///
    /// JUSTIFICATION: the `peer::Client` will translate all `Request`s into a `ClientRequest` which it sends to a background task, and if the send replies with `Ok(())` it will assume that it is safe to unconditionally poll the `Receiver` tied to the `Sender` used to create the `ClientRequest`.
```

**Comment by yaahc** [comment]
@teor2345 was this debug run still built with `panic = abort` on? We should be able to get even more frames out of a backtrace normally, I'd expect closer to 70, not 4. Before we go ahead and start sending errors in the `Drop` impl I want to understand how this drop is occurring a little better. Rn we know it's dropping from a `Sink` future, which we only create a few places.

My guess is that it's happening when dropping this future

* https://github.com/ZcashFoundation/zebra/pull/1531/files#diff-558ef42996967fa2dcffe0d47a6959571254ec41db7d9b0d26d7c3e240feadacL467

Which looks like heartbeat logic. I am a little unfamiliar with this code so I'm still trying to figure out how everything here is tied together. Assuming this is the correct location from where the `ClientRequest` then why is it being dropped? My guess is that it is failing the `send` into the `Client`.

Okay I think I got the scenario:

1. client spawns a background heartbeat task that periodically queues up heartbeat requests
2. the `Client` is dropped by the syncer for whatever reason
3. the background task is resumed by the executor, before the `Client` has sent it's shutdown signal in `drop`
4. the background task queues up a new heartbeat request, this fails, causing it to drop the sender immediately
5. it panics because the sender was unused

Seems to be a race condition between the `Client` shutdown code and its background thread. Lets try fixing that before changing any `drop` impls to automatically send errors, which I fear will hide issues more than fix them.

**Comment by yaahc** [comment]
Based on the stuff I was able to figure out above I think we might also want to change our `MustUseSender` design slightly or at least where and how we're using it. I think it is enforcing a stronger requirement than we need it to. Right now it's guaranteeing that all senders in `ClientRequest` must be used, but we should only need to use them once they've been successfully received in `connection.rs`. We should probably swap things around so the `MustUseSender` is only created and used to wrap the original sender once we dequeue it from the `mpsc::Receiver<ClientRequest>` in `connection.rs`.

**Comment by teor2345** [comment]
> @teor2345 was this debug run still built with `panic = abort` on? We should be able to get even more frames out of a backtrace normally, I'd expect closer to 70, not 4.

I'm using the default workspace `Cargo.toml`, which sets `panic = "abort"`:
```
[profile.dev]
panic = "abort"

[profile.release]
panic = "abort"
```

**Comment by yaahc** [comment]
In case I miss you I figured I should dump the design for the fix that I came up with.

* Update `ClientRequest` to use a regular sender instead of a `MustUseSender`
* Add a new type, `InProgressClientRequest`, that is the same as `ClientRequest` but has a `MustUseSender`
* `impl From<ClientRequest> for InProgressClientRequest`
* Add a new `ClientRequestReceiver` type that implements only one function, "async fn next(&self) -> Option<InProgressClientRequest>" that wraps a `mpsc::Receiver<ClientRequest>`, calls `next` on it, and then calls `into` on it to convert it to the must use variant of a client request
* Replace `    pub(super) client_rx: mpsc::Receiver<ClientRequest>,` in `Connection` in `connection.rs` with the new `ClientRequestReceiver` type

**Comment by teor2345** [comment]
> I'm using the default workspace `Cargo.toml`, which sets `panic = "abort"`:

I wasn't setting the relevant env vars in my run scripts - but the output still isn't that helpful.

File: zebra-network/src/peer/handshake.rs [hunk 8]
```diff
@@ -464,19 +464,39 @@ where
...
+                                            ?e,
+                                            "error sending heartbeat request, shutting down"
+                                        );
+                                        if e.is_disconnected() {
+                                            let ClientRequest { tx, .. } = e.into_inner();
+                                            let _ =
+                                                tx.send(Err(PeerError::ConnectionClosed.into()));
+                                        } else if e.is_full() {
+                                            let ClientRequest { tx, .. } = e.into_inner();
+                                            let _ = tx.send(Err(PeerError::Overloaded.into()));
```
Comment (teor2345) [inline zebra-network/src/peer/handshake.rs]: We close the connection if the queue is full, but the previous code waited for it to be empty.

Here are our options for fixing this issue:
* can we await the queue being empty?
* can we just ignore this heartbeat, and pick it up on the next request?
  * it might be better to close the connection, to avoid hangs   
* is it ok to just close the connection if the queue is full?

File: zebra-network/src/peer/handshake.rs [hunk 9]
```diff
@@ -464,19 +464,39 @@ where
...
+                                    tx: tx.into(),
+                                    span: tracing::Span::current(),
+                                }) {
+                                    Ok(()) => {
+                                        match server_tx.flush().await {
+                                            Ok(()) => {}
+                                            Err(e) => {
+                                                // TODO: we can't get the client request for this failure,
+                                                // so we can't ensure the invariant holds
+                                                panic!("flushing client request failed: {:?}", e);
```
Comment (teor2345) [inline zebra-network/src/peer/handshake.rs]: We panic if `flush` fails, but the previous code just closed the connection.

Here are our options for fixing this issue:
* does `flush` ever fail?
  * if it never fails, we don't actually need to fix anything
* can we cleanup the `ClientRequest` some other way?
  * is there a `flush` variant that returns the message on error?
  * is there a `try_send_and_flush` function?

**Comment by teor2345** [comment]
> In case I miss you I figured I should dump the design for the fix that I came up with.
> 
>     * Update `ClientRequest` to use a regular sender instead of a `MustUseSender`
>     * Add a new type, `InProgressClientRequest`, ...
>     * Add a new `ClientRequestReceiver` type ...

This seems like a good fix, but it's also a bit complicated, so I'd like to avoid as much of that complexity if we can.

I found a missing send in `Client::call` that was easy to fix:
https://github.com/ZcashFoundation/zebra/pull/1531/commits/2dfba5fda4a975a0cf36e750df5be95d4bcf8504#diff-946777883d52596b10e4679ed99713f02c8afe589c8ac641015b473d82b6dd56R151

But the fix for `Heartbeat::call` was a bit more complicated:
https://github.com/ZcashFoundation/zebra/pull/1531/commits/2dfba5fda4a975a0cf36e750df5be95d4bcf8504#diff-558ef42996967fa2dcffe0d47a6959571254ec41db7d9b0d26d7c3e240feadacR467

I'm testing my new code now, and I've added some comments about how we might fix the remaining issues.

**Comment by teor2345** [comment]
(If we can't fix those issues, then we should look at a more complex design, and yours seems like a good one.)

File: zebra-network/src/peer/handshake.rs (hunk 8 above)
Comment (teor2345) [reply zebra-network/src/peer/handshake.rs]: Thinking about this some more…

The old behaviour was buggy, because it could hang forever waiting for the queue to be ready.
The new behaviour is better, because it doesn't hang, but it also churns connections more than needed.
Ideally, we should wait for the queue to be ready with a timeout, and close the connection if it times out.

File: zebra-network/src/peer/handshake.rs (hunk 9 above)
Comment (teor2345) [reply zebra-network/src/peer/handshake.rs]: @yaahc the problem seems to be that most futures APIs aren't designed to return messages on failure.

We could auto-send ConnectionClosed on drop in this one very specific case, and leave all the rest of the code to panic on drop?

File: zebra-network/src/peer/handshake.rs (hunk 8 above)
Comment (teor2345) [reply zebra-network/src/peer/handshake.rs]: Since the latest code in this PR works, I'd be happy to make the timeout change in a follow-up PR. I don't think it's a particularly high priority, unless it really affects performance.

**Comment by yaahc** [comment]
> This seems like a good fix, but it's also a bit complicated, so I'd like to avoid as much of that complexity if we can.

Iunno, I feel like the fix I suggested is less complicated, even if it requires more code, and it will be more maintainable going forward. With the whole `InProgressClientRequest` design we end up encoding the exact shape of the invariant `Client` needs us to uphold. The fix you suggested only fixes this one specific instance of misuse, but if someone else accidentally creates and drops a `ClientRequest` they'll run into the exact same problem even though there was never actually an issue with them dropping that `ClientRequest` because it was never sent to the `Connection`.

**Comment by teor2345** [comment]
> With the whole `InProgressClientRequest` design we end up encoding the exact shape of the invariant `Client` needs us to uphold

How can we make sure we have the correct invariant?

We need make sure that:
* the `Client` polls the background task correctly (#1471)
* each connection is only failed once (#1510)
  * I think this invariant is "exactly once", but it might be "at most once"

I'm happy to implement a more complex design to make future changes easier. But we seem to have tried a few different alternative designs here, so I want to make sure we settle on something that works.

File: zebra-network/src/peer/handshake.rs (hunk 9 above)
Comment (teor2345) [reply zebra-network/src/peer/handshake.rs]: I think applying `MustUseOneshotSender` after the `ClientRequest` is successfully received resolves this issue, because a failed `flush` means that the request was never received.

File: zebra-network/src/peer/client.rs [hunk 10]
```diff
@@ -63,9 +143,15 @@ impl Service<Request> for Client {
...
-        match self.server_tx.try_send(ClientRequest { request, span, tx }) {
+        match self.server_tx.try_send(ClientRequest {
+            request,
+            span,
+            tx: tx.into(),
+        }) {
             Err(e) => {
                 if e.is_disconnected() {
+                    let ClientRequest { tx, .. } = e.into_inner();
+                    let _ = tx.send(Err(PeerError::ConnectionClosed.into()));
```
Comment (teor2345) [inline zebra-network/src/peer/client.rs:222]: This change won't be required with the new design, but it's still an improvement over the old code.

File: zebra-network/src/peer/handshake.rs [hunk 11]
```diff
@@ -463,19 +464,39 @@ where
...
+                                        tracing::trace!(
+                                            ?e,
+                                            "error sending heartbeat request, shutting down"
+                                        );
+                                        if e.is_disconnected() {
+                                            let ClientRequest { tx, .. } = e.into_inner();
+                                            let _ =
+                                                tx.send(Err(PeerError::ConnectionClosed.into()));
+                                        } else if e.is_full() {
+                                            let ClientRequest { tx, .. } = e.into_inner();
```
Comment (teor2345) [inline zebra-network/src/peer/handshake.rs:500]:
```suggestion
                                            // TODO: wait for the sink to be ready, or wait for a timeout,
                                            // then close the connection with an overloaded error (#1551)
                                            let ClientRequest { tx, .. } = e.into_inner();
```

File: zebra-network/src/peer/handshake.rs (hunk 8 above)
Comment (teor2345) [reply zebra-network/src/peer/handshake.rs]: See #1551

**Comment by teor2345** [comment]
The latest commit seems to be a lot more stable. So I think we've identified almost all the places where a `ClientRequest` is dropped without sending anything.

I'll try implementing the `InProgressClientRequest` design, and see how we go.

File: zebra-network/src/peer/handshake.rs (hunk 9 above)
Comment (yaahc) [reply zebra-network/src/peer/handshake.rs]: > I think applying `MustUseOneshotSender` after the `ClientRequest` is successfully received resolves this issue, because a failed `flush` means that the request was never received.

I agree, this is precisely what the `InProgressClientRequest` would do by encoding "applying the `MustUseOneshotSender` to a `ClientRequest` once it is received" in the type system.

**Comment by teor2345** [comment]
> I'll try implementing the `InProgressClientRequest` design, and see how we go.

It was a bit more complicated than I expected, because we call `future::select` on `ClientRequestReceiver::next`, which requires `ClientRequestReceiver` to `impl Stream`. (Or maybe `impl Future`?)

As a consequence, I needed to implement `ClientRequestReceiver::poll_next` rather than `ClientRequestReceiver::next`. It's  a little bit more complicated, because it needs a pinning utility function and a match statement on the `Poll` result.

@yaahc if you're happy with this PR, let's rebase-merge it, in case we need to revert or inspect some of these changes.

File: zebra-network/src/peer/client.rs [hunk 12]
```diff
@@ -54,6 +87,49 @@ pub(super) struct MustUseOneshotSender<T: std::fmt::Debug> {
...
+            // `inner.poll_next_unpin` parks the task for this future
+            Poll::Pending => Poll::Pending,
+        }
+    }
+
+    /// Returns `inner.size_hint()`
+    fn size_hint(&self) -> (usize, Option<usize>) {
+        self.inner.size_hint()
+    }
+}
```
Comment (yaahc) [inline zebra-network/src/peer/client.rs:125]: ooh yea, didn't see this one coming. Sorry about that and great work.

**Review by yaahc — APPROVED** [review]
looks great
