### PR TITLE
fix(state): Avoid temporary failures verifying the first non-finalized block or attempting to fork the chain before the final checkpoint

### LINKED ISSUE #5125: Avoid temporary failures verifying the first non-finalized block
## Motivation

Waiting for the last finalized block is currently handled by `can_fork_chain_at()`, which returns early if the tip hash doesn't match any blocks.

https://github.com/ZcashFoundation/zebra/blob/093d503d22894fee57249387f25eb86a5bc8b985/zebra-state/src/service.rs#L378-L381

But it has two bugs: 
- if the first non-finalized block arrives before the last finalized block, it will time out and fail verification, because the fork point is only checked once per block. But it will verify correctly when it gets retried.
- if the syncer reaches the lookahead limit before the last checkpoint verified block is committed, semantically verified blocks in the queue will time out, because it only checks if it's finished committing checkpoint verified blocks when semantically verified blocks are queued.

_Originally posted by @teor2345 in https://github.com/ZcashFoundation/zebra/issues/4937#issuecomment-1241352383_

### Status

We partially fixed this in PR #5257, and added a workaround for the remaining timeouts.

## Tasks

- when receiving a finalized block in the last checkpoint, check for pending non-finalized UTXO requests
- remove the special 5 minute timeout for initial fully verified blocks in `sync:: downloads`

### LINKED ISSUE #6388: can_fork_chain_at() should ignore blocks below the finalized tip
## Motivation

We can't fork the chain at a finalized block height below the finalized tip height, but the `sent_non_finalized_blocks` data structure contains the heights of some finalized blocks close to the final checkpoint.

We might need to store the queued finalized block list separately, rather than re-using an existing data structure that other code depends on.

(This is an existing bug, but the code in the linked audit PR added more finalized blocks to the data structure.)

_Originally posted by @teor2345 in https://github.com/ZcashFoundation/zebra/pull/6335#discussion_r1144234829_

## Scheduling

We reviewed this code, and checked that even if it was called incorrectly, the write block task would return a similar error. So this is just a technical debt cleanup.

### PR DESCRIPTION
**Pull request by arya2**
## Motivation

This PR updates the `can_fork_chain_at()` method in zebra-state to ignore blocks below the finalized tip and fixes a bug where the first block past the final checkpoint will fail verification if it arrives in zebra-state before the final checkpoint block is written to disk.

Close #6388
Close #5125

Part of #5709

## Solution

- Add a `can_fork_chain_at_hashes` flag to `SentHashes`
- Add and use a `can_fork_chain_at(hash)` method to `SentHashes` that checks the new flag
- When closing finalized block write channel:
  - Replace `block_write_sent_hashes` with an empty `SentHashes` and mark `can_fork_chain_at_hashes` as true 
  - Start committing queued non-finalized child blocks of finalized tip

Related:

- Adds `shrink_to_fit()` calls in `prune_by_height()`

## Review

This is low-priority.

### Reviewer Checklist

  - [ ] Will the PR name make sense to users?
    - [ ] Does it need extra CHANGELOG info? (new features, breaking changes, large changes)
  - [ ] Are the PR labels correct?
  - [ ] Does the code do what the ticket and PR says?
    - [ ] Does it change concurrent code, unsafe code, or consensus rules?
  - [ ] How do you know it works? Does it have tests?

### CODE REVIEW

File: zebra-state/src/service/queued_blocks.rs [hunk 1]
```diff
@@ -219,18 +219,49 @@ impl QueuedBlocks {
     }
 }
 
+#[derive(Debug)]
```
Comment (teor2345) [inline zebra-state/src/service/queued_blocks.rs]: Please derive the standard set of impls on new types, so they are easier to use in future code changes.

**Review by teor2345 — DISMISSED** [review]
"non-finalized" and "finalized" are outdated terms that we're trying to move away from, because they were very confusing during the audit. When we're talking about the verification status of blocks, we use "semantically verified", "checkpoint verified" or "contextually verified".

But it's ok to say "finalized queue" when talking about block storage, or which state blocks are queued for.

There's a list of name changes in ticket #6793 which might be helpful.

Edit: name changes have finished

File: zebra-state/src/service/queued_blocks.rs [hunk 2]
```diff
@@ -219,18 +219,49 @@ impl QueuedBlocks {
...
+
+    /// Stores a set of hashes that may have been sent to the block write task via
+    /// the finalized block write channel but may not be in the finalized state yet.
+    sent_finalized: HashMap<block::Hash, Vec<transparent::OutPoint>>,
 
-    /// Stores a set of hashes that have been sent to the block write task but
-    /// may not be in the finalized state yet.
-    sent: HashMap<block::Hash, Vec<transparent::OutPoint>>,
+    /// Stores a set of hashes that have been sent to the block write task via the
+    /// non-finalized block write channel but may not be in the finalized state yet.
```
Comment (teor2345) [inline zebra-state/src/service/queued_blocks.rs]: Which state do you mean here?

File: zebra-state/src/service/queued_blocks.rs [hunk 3]
```diff
@@ -314,30 +347,41 @@ impl SentHashes {
...
-        self.sent.shrink_to_fit();
+        self.sent_finalized.shrink_to_fit();
+        self.sent_non_finalized.shrink_to_fit();
+        self.known_utxos.shrink_to_fit();
 
         self.update_metrics_for_cache();
     }
 
     /// Returns true if SentHashes contains the `hash`
     pub fn contains(&self, hash: &block::Hash) -> bool {
```
Comment (teor2345) [inline zebra-state/src/service/queued_blocks.rs]: These docs and method name are now outdated

File: zebra-state/src/service.rs [hunk 4]
```diff
@@ -720,28 +720,31 @@ impl StateService {
...
-        rsp_rx
-    }
+        self.sent_non_finalized_block_hashes
+            .prune_by_height(finalized_tip_height);
 
-    /// Returns `true` if `hash` is a valid previous block hash for new non-finalized blocks.
-    fn can_fork_chain_at(&self, hash: &block::Hash) -> bool {
-        self.sent_non_finalized_block_hashes.contains(hash)
-            || &self.read_service.db.finalized_tip_hash() == hash
+        self.sent_non_finalized_block_hashes.contains(hash) || &finalized_tip_hash == hash
```
Comment (teor2345) [inline zebra-state/src/service.rs]: This field name is now outdated for two reasons:
1. It uses old verification status terminology
2. The type contains both checkpointed and semantically verified blocks

File: zebra-state/src/service.rs [hunk 5]
```diff
@@ -720,28 +720,31 @@ impl StateService {
...
-            // Wait until block commit task is ready to write non-finalized blocks before dequeuing them
-            self.send_ready_non_finalized_queued(parent_hash);
+        self.send_ready_non_finalized_queued(parent_hash);
 
-            let finalized_tip_height = self.read_service.db.finalized_tip_height().expect(
+        rsp_rx
+    }
+
+    /// Returns `true` if `hash` is a valid previous block hash for new non-finalized blocks.
+    fn can_fork_chain_at(&mut self, hash: &block::Hash) -> bool {
```
Comment (teor2345) [inline zebra-state/src/service.rs]: This PR changes syncing behaviour, can you run a full sync test before we merge it?
You'll have to do it manually, or get Gustavo to fix #6568 first.

File: zebra-state/src/service/queued_blocks.rs (hunk 2 above)
Comment (arya2) [reply zebra-state/src/service/queued_blocks.rs]: The finalized state, I'll add some context on how it's used in `can_fork_chain_at()`.

I think I could just add a flag to this struct and simplify this PR.

Comment (teor2345) [reply zebra-state/src/service/queued_blocks.rs]:
```suggestion
    /// non-finalized block write channel, but haven't been committed to the finalized state yet.
    /// (They are either in the channel, or in the non-finalized state.)
```

Comment (teor2345) [reply zebra-state/src/service/queued_blocks.rs]: I wasn't asking for a code change here, I just wanted to check that "finalized state" wasn't a copy-paste error.

File: zebra-state/src/service.rs (hunk 4 above)
Comment (teor2345) [reply zebra-state/src/service.rs]: > 1. It uses old verification status terminology

~~Let's do these name changes automatically in ticket #6793?
Any complicated documentation changes can be done in this PR, or added to the list in #6681.~~

Edit: we've finished name changes

File: zebra-state/src/service.rs (hunk 5 above)
Comment (teor2345) [reply zebra-state/src/service.rs]: I fixed #6568, I hope!

Comment (teor2345) [reply zebra-state/src/service.rs]: Since there's a sync risk, this PR should go at the end of the PR backlog.

**Review by teor2345 — DISMISSED** [review]
Just marking this as needing changes.

**Comment by teor2345** [comment]
I updated my review because the name changes in ticket #6793 have merged.

(There's no need to work on this PR any time soon, please check with Pili first.)

File: zebra-state/src/service/queued_blocks.rs (hunk 2 above)
Comment (arya2) [reply zebra-state/src/service/queued_blocks.rs]: > I wasn't asking for a code change here

I know - but I think I initially overcomplicated this, I updated it to prune out all the finalized sent hashes and mark a `can_fork_chain_at_hashes` flag as true. It should actually just drop it and replace it with a new one since it'll always be emptied anyways. ~I'll do this in a follow-up PR.~

File: zebra-state/src/service.rs (hunk 5 above)
Comment (arya2) [reply zebra-state/src/service.rs]: Mainnet sync started here: https://github.com/ZcashFoundation/zebra/actions/runs/5661476853

Update: Finished in 2d 4h, last full sync time I'd seen was 3d 20h.

File: zebra-state/src/service/queued_blocks.rs (hunk 1 above)
Comment (arya2) [reply zebra-state/src/service/queued_blocks.rs]: I started over and removed this struct, and noted.

File: zebra-state/src/service.rs (hunk 4 above)
Comment (arya2) [reply zebra-state/src/service.rs]: Should this PR still update this field name?

**Comment by arya2** [comment]
@Mergifyio update

**Comment by arya2** [comment]
@Mergifyio update

**Review by oxarbitrage — COMMENTED** [review]
I think this looks good, is short, clear and it seems to work.

What i am not totally sure is if it closes all the stuff that are inside the related tickets.

I will like @teor2345 to make the final review as they have more context in the tickets this is closing. I think the next few days could be a good time to merge this in.

File: zebra-state/src/service.rs (hunk 5 above)
Comment (teor2345) [reply zebra-state/src/service.rs]: Ok great that seems fine.

The scheduled full syncs usually complete in just over 2 days.

**Review by teor2345 — APPROVED** [review]
Thanks for this fix!

> What i am not totally sure is if it closes all the stuff that are inside the related tickets.

That's a good question.

#5125 is partially resolved, I opened #7352 with the remaining work. (Which I don't think we should fix unless it actually happens.)

I checked the logs and #5709 is not resolved, it seems to be just as frequent as before this fix. (The warnings are still there, and syncing takes about the same amount of time.)
