### PR TITLE
fix(doc): Fix broken links to `zebra_network` and `zebra_state` `Config` structs on doc.zebra.zfnd.org

### LINKED ISSUE #7048: Broken link to zebra_network and zebra_state Config in docs
## Motivation

`network: Config` on https://doc.zebra.zfnd.org/zebrad/config/struct.ZebradConfig.html should link to `zebra_network::Config`. But instead there's an extra `zebra_network` directory in the URL.

`zebra_state::Config` also has the same issue.

### Testing

Look at the generated docs manually.

### PR DESCRIPTION
**Pull request by teor2345**
## Motivation

_What are the most important goals of the ticket or PR?_

This PR fixes broken links to the `zebra_network` and `zebra_state` `Config` structs in https://doc.zebra.zfnd.org/zebrad/config/struct.ZebradConfig.html

Close #7048

### PR Author Checklist

Check before marking the PR as ready for review:
  - [x] Will the PR name make sense to users?
    - ~~Does it need extra CHANGELOG info?~~
    - [x] Does the PR have a priority label?
  - ~~Have you added or updated tests?~~
  - ~~Is the documentation up to date?~~

This PR doesn't change Rust code behaviour, just the generated doc links.

## Solution

- Use full paths to config imports to avoid a doc link bug

Related:
- Exclude `zebra-test` from the external docs build

### Testing

I manually tested this locally with the doc build command we use in CI, and checked the files for `zebra_network/zebra_network` and `zebra_state/zebra_state`.

## Review

This is a routine fix.

The generated docs from this PR should be checked for broken links in https://doc.zebra.zfnd.org/zebrad/config/struct.ZebradConfig.html

The "Deploy external docs to firebase" step logs a preview URL with the docs from each PR.

### Reviewer Checklist

Check before approving the PR:
  - [ ] Does the PR scope match the ticket?
  - [ ] How do you know it works? Do the tests cover the PR motivation?
  - [ ] Are there any blockers to merging this PR?
    - [ ] Can some changes go in new tickets or PRs?
  - [ ] Manually test the PR

_And check the PR Author checklist is complete._

## Follow Up Work

If this happens again we should just link to docs.rs, it doesn't have this bug:
- #7837

### CODE REVIEW

File: zebra-state/src/config.rs [hunk 1]
```diff
@@ -385,44 +385,52 @@ pub(crate) fn database_format_version_at_path(
...
 
-    // The major version is already in the directory path.
-    assert_eq!(
-        changed_version.major, DATABASE_FORMAT_VERSION,
-        "tried to do in-place database format change to an incompatible version"
-    );
+pub(crate) mod hidden {
 
-    let version = format!("{}.{}", changed_version.minor, changed_version.patch);
+    use super::*;
```
Comment (teor2345) [inline zebra-state/src/config.rs:393]: This looks complicated but it's just moving the function into a module to conditionally hide it.

**Review by arya2 — APPROVED** [review]
Looks good!
