### PR TITLE
fix(consensus): Verify consensus branch ID in SIGHASH precomputation

### LINKED ISSUE #9089: The tx verifier does not enforce using the correct consensus branch ID in the SIGHASH precomputation
When precomputing the SIGHASH of V5 txs, we pick the consensus branch ID from the `nConsensusBranchId` field if the tx has it. If the field is set to a consensus branch ID corresponding to NU5 and NU6 is active, the SIGHASH precomputation doesn't follow this consensus rule:

> [NU6 only] All transactions MUST use the NU6 consensus branch ID 0xC8E71055 as defined in ZIP-253.

This bug was mitigated in #9063 by checking the `nConsensusBranchId` field early in the tx verifier, so it won't accept NU5 transactions after NU6 activation anymore. However, we should fix the precomputation to adhere to the above consensus rule since it takes place in `zebra-chain` and not `zebra-consensus`, where the verifier is, and can be used by other crates.

The bug originates in this fn: https://github.com/zcash/librustzcash/blob/443faf9e855e0acf7aca509885ac2ede8090c5bd/zcash_primitives/src/transaction/mod.rs#L604-L616, which considers the `consensus_branch_id` param for pre-V5 txs but doesn't do so for V5 ones.

### PR DESCRIPTION
**Pull request by upbqdn**
## Motivation

Close #9089.

#### [§ 4.10 SIGHASH Transaction Hashing](https://zips.z.cash/protocol/protocol.pdf#sighash)                                                                                
                                                                                           
> [NU5 only, pre-NU6] All transactions MUST use the NU5 consensus branch ID `0xF919A198` as defined in [ZIP-252].                                                                    
                                                                                           
> [NU6 only] All transactions MUST use the NU6 consensus branch ID `0xC8E71055` as defined in [ZIP-253].

[ZIP-252]: <https://zips.z.cash/zip-0252>
[ZIP-253]: <https://zips.z.cash/zip-0253>                                                  

## Solution

- Implement a check ensuring compliance with the consensus rules listed above. This check makes the tx SIGHASH precomputation panic if the tx contains an invalid value in its `nConsensusBranchId` field. This precomputation is implemented in `zebra-chain`, and is used by the tx verifier in `zebra-consensus` and by the transparent script verifier in `zebra-script`, but this verifier is only called from the tx verifier. It might be worth optimizing this, but that is currently not possible, as described in #9165. The panic should never occur in regular use because the tx verifier implements another consensus branch ID check according to another consensus rule implemented here: https://github.com/zcashfoundation/zebra/blob/05a9b6171ccbc06bcc888470e4be8a60b1d574ef/zebra-consensus/src/transaction/check.rs#L513-L552, which takes effect early on and doesn't panic.
- Add new error types in `zebra-chain`.
- Pass `NetworkUpgrade` instead of `ConsensusBranchId` to the SIGHASH precomputation and tx conversion.
- Use `TryFrom` instead of ad-hoc functions for conversion.
- Remove a redundant `TryFrom<&Transaction> for zcash_primitives::transaction::Transaction`.
- Document that we now implement the consensus rules listed above.
- Impl `NetworkUpgrade::previous_upgrade` and refactor `NetworkUpgrade::next_upgrade` so that it doesn't explicitly enumerate all upgrades.
- Don't make `NETWORK_UPGRADES_IN_ORDER` `pub`.

### Tests

- Add tests that check that tx SIGHASH precomputation and computation fail when a tx attempts to use an invalid consensus branch id. 

### PR Author's Checklist

- [x] The PR name will make sense to users.
- [ ] The PR provides a CHANGELOG summary.
- [x] The solution is tested.
- [x] The documentation is up to date.
- [x] The PR has a priority label.

### PR Reviewer's Checklist

- [ ] The PR Author's checklist is complete.
- [ ] The PR resolves the issue.

### CODE REVIEW

File: zebrad/src/components/mempool/downloads.rs [hunk 1]
```diff
@@ -373,6 +373,7 @@ where
                 .oneshot(tx::Request::Mempool {
                     transaction: tx.clone(),
                     height: next_height,
+                    skip_checks: None
```
Comment (upbqdn) [inline zebrad/src/components/mempool/downloads.rs]: Why does guarding this by `#[cfg(any(test, feature = "proptest-impl"))]` not work, and why does it work as it is since `skip_checks` is guarded by the same attribute in `zebra-consensus`?

Comment (upbqdn) [reply zebrad/src/components/mempool/downloads.rs]: Turns out it doesn't. I have to understand better how feature assignment behaves during compilation. And it's probably not a good idea to do it this way anyway.

Comment (upbqdn) [reply zebrad/src/components/mempool/downloads.rs]: I used this hack to solve this: https://github.com/zcashfoundation/zebra/blob/9597792567982ae19643eba0d2537d3a81fe5956/zebrad/Cargo.toml#L301-L304.

Comment (upbqdn) [reply zebrad/src/components/mempool/downloads.rs]: I'm trying to think of something better in general.

File: zebra-consensus/src/transaction.rs [hunk 2]
```diff
@@ -575,13 +600,13 @@ where
...
                     let transaction = VerifiedUnminedTx::new(
-                        transaction,
-                        miner_fee.expect(
-                            "unexpected mempool coinbase transaction: should have already rejected",
-                        ),
+                        tx.clone(),
+                        miner_fee.expect("fee should have been checked earlier"),
                         legacy_sigop_count,
+                        #[cfg(any(test, feature = "proptest-impl"))]
+                        req.skip_checks().is_some_and(|checks| checks.contains(&SkipCheck::Zip317))
```
Comment (oxarbitrage) [inline zebra-consensus/src/transaction.rs]: I am not sure why but i remember seeing other odd behaviors when using `proptest-impl`. Here is one option to fix it:


```suggestion
                        #[cfg(any(test, feature = "proptest-impl"))]
                        req.skip_checks().is_some_and(|checks| checks.contains(&SkipCheck::Zip317)),
                        #[cfg(not(any(test, feature = "proptest-impl")))]
                        false,
```

Comment (upbqdn) [reply zebra-consensus/src/transaction.rs]: Nope.

Comment (oxarbitrage) [reply zebra-consensus/src/transaction.rs]: Yea, sorry about that. I will try something else.

File: zebra-chain/src/parameters/network_upgrade.rs [hunk 3]
```diff
@@ -350,17 +350,18 @@ impl NetworkUpgrade {
...
+            .filter(|&p| (p + 1) < NETWORK_UPGRADES_IN_ORDER.len())
+            .map(|p| NETWORK_UPGRADES_IN_ORDER[p + 1])
+    }
+
+    /// Returns the previous network before after this network upgrade
+    pub fn previous_upgrade(self) -> Option<Self> {
+        Self::iter()
+            .position(|nu| self == nu)
+            .filter(|&p| p > 0)
+            .map(|p| NETWORK_UPGRADES_IN_ORDER[p - 1])
```
Comment (arya2) [inline zebra-chain/src/parameters/network_upgrade.rs]: Optional/Nitpick, requires a suggestion below:

```suggestion
        Self::iter().skip_while(|&nu| self != nu).nth(1)
    }

    /// Returns the previous network before after this network upgrade
    pub fn previous_upgrade(self) -> Option<Self> {
        Self::iter().rev().skip_while(|&nu| self != nu).nth(1)
```

File: zebra-chain/src/parameters/network_upgrade.rs [hunk 4]
```diff
@@ -538,6 +539,11 @@ impl NetworkUpgrade {
     ) -> Duration {
         NetworkUpgrade::current(network, height).averaging_window_timespan()
     }
+
+    /// Returns an iterator over [`NetworkUpgrade`] variants.
+    pub fn iter() -> impl Iterator<Item = NetworkUpgrade> {
```
Comment (arya2) [inline zebra-chain/src/parameters/network_upgrade.rs]: Required for the suggestion above
```suggestion
    pub fn iter() -> impl DoubleEndedIterator<Item = NetworkUpgrade> {
```

File: zebra-chain/src/parameters/network_upgrade.rs (hunk 3 above)
Comment (upbqdn) [reply zebra-chain/src/parameters/network_upgrade.rs]: Amazing. Thanks.

File: zebra-chain/src/transaction/tests/vectors.rs [hunk 5]
```diff
@@ -801,6 +803,46 @@ fn zip244_sighash() -> Result<()> {
...
+                .expect_err("tx is not convertible under nu other than the tx one");
+
+            std::panic::catch_unwind(|| PrecomputedTxData::new(&tx, any_other_nu, &[]))
+                .expect_err("precomputing tx sighash data panics under nu other than the tx one");
+
+            std::panic::catch_unwind(|| sighash::SigHasher::new(&tx, any_other_nu, &[]))
+                .expect_err("creating the sighasher panics under nu other than the tx one");
+
+            std::panic::catch_unwind(|| tx.sighash(any_other_nu, HashType::ALL, &[], None))
+                .expect_err("the sighash computation panics under nu other than the tx one");
```
Comment (arya2) [inline zebra-chain/src/transaction/tests/vectors.rs:841]: Could you mention this in the method docs for `sighash()` and `sighasher()` too?

Comment (upbqdn) [reply zebra-chain/src/transaction/tests/vectors.rs:841]: This is a bit more nuanced. It won't panic for txs that don't contain the `nConsensusBranchId` field. This test uses only those, so the message here can be simplified. Other reasons for panicking can be issues with obtaining a librustzcash version of the consensus branch id from the passed network upgrade. 

This is documented in the corresponding functions: https://github.com/zcashfoundation/zebra/blob/2e32fd688c53e6956d0a7447bf750f37a7df0a99/zebra-chain/src/transaction.rs#L1237 and https://github.com/zcashfoundation/zebra/blob/2e32fd688c53e6956d0a7447bf750f37a7df0a99/zebra-chain/src/primitives/zcash_primitives.rs#L243.
We usually document panics only in the functions from which they originate, so I thought it was fine as it was. 

I can document it in those functions you mentioned, but then I would have to describe the whole story, which feels too repetitive. Would you prefer that?

Comment (arya2) [reply zebra-chain/src/transaction/tests/vectors.rs:841]: > We usually document panics only in the functions from which they originate, so I thought it was fine as it was.

I think it'd be nice to say "Panics on parser errors or network upgrade mismatches" with a reference to the docs for `PrecomputedTxData::new()` + `to_librustzcash()`, but I also think it's fine as-is and definitely shouldn't be repeated.

Comment (upbqdn) [reply zebra-chain/src/transaction/tests/vectors.rs:841]: Addressed in 3b25023db93e708837da4e6d625810e932e81869.

File: zebra-consensus/src/transaction.rs [hunk 6]
```diff
@@ -575,12 +575,10 @@ where
...
                     legacy_sigop_count,
                 },
-                Request::Mempool { transaction, .. } => {
+                Request::Mempool { transaction: ref tx, .. } => {
                     let transaction = VerifiedUnminedTx::new(
-                        transaction,
-                        miner_fee.expect(
-                            "unexpected mempool coinbase transaction: should have already rejected",
-                        ),
+                        tx.clone(),
```
Comment (arya2) [inline zebra-consensus/src/transaction.rs:580]: Why this change?

File: zebra-script/src/lib.rs [hunk 7]
```diff
@@ -451,13 +440,13 @@ mod tests {
...
 
-        verifier.is_valid(branch_id, input_index + 1).unwrap_err();
-
-        verifier.is_valid(branch_id, input_index + 1).unwrap_err();
+        verifier
+            .is_valid(NetworkUpgrade::Blossom, input_index + 1)
+            .expect_err("verification should fail");
+        verifier
+            .is_valid(NetworkUpgrade::Blossom, input_index + 1)
+            .expect_err("verification should fail");
```
Comment (arya2) [inline zebra-script/src/lib.rs]:
```suggestion
        verifier
            .is_valid(NetworkUpgrade::Blossom, input_index + 1)
            .expect_err("verification should fail");
```

**Review by arya2 — DISMISSED** [review]
Looks good, thank you!

**Review by oxarbitrage — APPROVED** [review]

File: zebra-script/src/lib.rs (hunk 7 above)
Comment (upbqdn) [reply zebra-script/src/lib.rs]: This shouldn't have been merged. The verifier is supposed to fail twice. It's in the name of the test, similarly to other tests in the file.

File: zebra-consensus/src/transaction.rs (hunk 6 above)
Comment (upbqdn) [reply zebra-consensus/src/transaction.rs:580]: Thanks for spotting this. It was required for the conditional compilation I had earlier, which is gone now. I'll revert it.

File: zebra-script/src/lib.rs (hunk 7 above)
Comment (upbqdn) [reply zebra-script/src/lib.rs]: I'll fix it in another PR.

Comment (oxarbitrage) [reply zebra-script/src/lib.rs]: sorry about that, i thought it was an oversight.
