### PR TITLE
fix(state): Remove an outdated anchor assertion in a comment

### LINKED ISSUE #6389: Re-enable or delete the assertion in `fetch_sprout_final_treestates()`
## Motivation

The auditors have suggested that this commented-out assertion should either be deleted, or enabled but disabled in tests:
https://github.com/ZcashFoundation/zebra/blob/c838383fd53610da01bfee4f7555f219f84853d0/zebra-state/src/service/check/anchors.rs#L158-L172

We can do this using `#[cfg(not(test))]`.

### Testing

Our existing integration tests should cover this.

### PR DESCRIPTION
**Pull request by teor2345**
## Motivation

There is an outdated assertion in the state Sprout anchor checking code, which has already been commented out.

This assertion could be expensive, so we can only do it during tests.

Close #6389

### Specifications

This assertion is not consensus-critical, the existing production code already constructs the anchor map correctly.

## Solution

- Remove the commented-out assertion
- Update the TODO to only apply to tests

## Review

This is an audit fix, it should be reviewed first.

### Reviewer Checklist

  - [ ] Will the PR name make sense to users?
    - [ ] Does it need extra CHANGELOG info? (new features, breaking changes, large changes)
  - [ ] Are the PR labels correct?
  - [ ] Does the code do what the ticket and PR says?
    - [ ] Does it change concurrent code, unsafe code, or consensus rules?
  - [ ] How do you know it works? Does it have tests?

## Follow Up Work

We could fix the tests, but it's not important at all.

### CODE REVIEW

File: zebra-state/src/service/check/anchors.rs [hunk 1]
```diff
@@ -155,24 +155,15 @@ fn fetch_sprout_final_treestates(
...
-            );
-             */
-
             sprout_final_treestates.insert(joinsplit.anchor, input_tree);
 
+            /* TODO:
+               - fix tests that generate incorrect root data
+               - assert that joinsplit.anchor matches input_tree.root() during tests,
+                 but don't assert in production, because the check is CPU-intensive,
+                 and sprout_anchors_refer_to_treestates() constructs the map correctly
```
Comment (arya2) [inline zebra-state/src/service/check/anchors.rs:164]: Do you want to uncomment the `assert_eq!()` as a `debug_assert_eq!()` here instead of removing the comment?

**Review by arya2 — APPROVED** [review]
This looks good!

File: zebra-state/src/service/check/anchors.rs (hunk 1 above)
Comment (teor2345) [reply zebra-state/src/service/check/anchors.rs:164]: No, because the assert fails for some tests, so the tests need to be fixed first.
