### PR TITLE
fix panic in seed subcommand

### LINKED ISSUE #394: `zebra seed` command is throwing a panic but keeps going fine?
image

```
May 26 11:47:58.437  INFO zebrad::components::tracing: Initializing tracing endpoint
May 26 11:47:58.438  INFO zebrad::components::metrics: Initializing metrics endpoint
May 26 11:47:58.438  INFO zebrad::commands::seed: begin tower-based peer handling test stub
May 26 11:47:58.448  INFO add_initial_peers: zebra_network::peer_set::initialize: Connecting to initial peer set initial_peers=[V4(3.136.31.59:8233), V4(34.66.191.95:8233), V4(138.197.158.219:8233), V4(3.19.66.87:8233), V4(47.254.18.12:8233), V4(198.187.30.208:8233), V4(47.254.69.198:8233), V4(192.64.112.23:8233), V4(81.2.80.52:8233), V4(51.89.96.119:8233), V4(213.227.145.69:8233), V4(62.210.91.14:8233), V4(52.30.69.116:8233), V4(139.59.187.105:8233), V4(46.4.192.189:8233), V4(47.254.178.251:8233), V4(116.203.188.195:8233), V4(47.254.179.213:8233), V4(95.216.227.171:8233), V4(94.156.174.100:8233), V4(5.9.193.19:8233), V4(89.234.183.220:8233), V4(118.24.175.14:8233), V4(47.94.251.211:8233), V4(162.14.4.106:8233), V4(3.92.199.184:8233), V4(47.252.1.134:8233), V4(47.254.18.12:8233), V4(198.187.30.208:8233), V4(164.132.122.137:8233), V4(52.30.69.116:8233), V4(51.77.64.61:8233), V4(78.129.149.90:8233), V4(51.77.64.51:8233), V4(116.202.100.25:8233), V4(95.216.227.171:8233), V4(46.4.192.189:8233), V4(47.254.179.213:8233), V4(167.86.124.82:8233), V4(188.72.203.154:8233), V4(116.202.105.79:8233), V4(173.249.53.153:8233), V4(139.59.128.41:8233), V4(95.216.46.146:8233), V4(85.15.179.171:8233), V4(3.112.252.179:8233), V4(13.231.145.68:8233), V4(47.244.58.44:8233), V4(47.106.224.223:8233), V4(119.23.67.66:8233)]
May 26 11:48:01.314  INFO zebra_network::peer_set::initialize: Sending initial request for peers
May 26 11:48:01.314  INFO zebrad::commands::seed: waiting for peer_set ready
May 26 11:48:01.314  INFO zebrad::commands::seed: peer_set became ready
The application panicked (crashed).
Message:  assertion failed: !self.cancel_handles.contains_key(&key)
Location: <::std::macros::panic macros>:2

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.
May 26 11:48:01.354 ERROR zebra_network::peer_set::initialize: e=send failed because receiver is gone
```

### PR DESCRIPTION
**Pull request by yaahc**
Prior to this change, the seed subcommand would consistently encounter a panic in one of the background tasks, but would continue running after the panic. This is indicative of two bugs. 

First, zebrad was not configured to treat panics as non recoverable and instead defaulted to the tokio defaults, which are to catch panics in tasks and return them via the join handle if available, or to print them if the join handle has been discarded. This is likely a poor fit for zebrad as an application, we do not need to maximize uptime or minimize the extent of an outage should one of our tasks / services start encountering panics. Ignoring a panic increases our risk of observing invalid state, causing all sorts of wild and bad bugs. To deal with this we've switched the default panic behavior from `unwind` to `abort`. This makes panics fail immediately and take down the entire application, regardless of where they occur, which is consistent with our treatment of misbehaving connections.

The second bug is the panic itself. This was triggered by a duplicate entry in the initial_peers set. To fix this we've switched the storage for the peers from a `Vec` to a `HashSet`, which has similar properties but guarantees uniqueness of its keys.

### CODE REVIEW

**Comment by yaahc** [comment]
I switched this to a draft because I think there's a little more work that needs to be done, specifically the `push` command on `HashSet` returns a boolean to indicate if the insert succeeded or not. Right now all those bools are being discarded, we may wish to audit them all to verify that this behavior is correct.

File: zebra-network/src/peer_set/initialize.rs [hunk 1]
```diff
@@ -148,7 +148,7 @@ where
 /// the results over `tx`.
 #[instrument(skip(initial_peers, connector, tx))]
 async fn add_initial_peers<S>(
-    initial_peers: Vec<SocketAddr>,
+    initial_peers: std::collections::HashSet<SocketAddr>,
```
Comment (dconnolly) [inline zebra-network/src/peer_set/initialize.rs:151]: 👍

File: zebra-network/src/config.rs [hunk 2]
```diff
@@ -49,16 +49,16 @@ pub struct Config {
...
             .iter()
             .flat_map(|s| s.to_socket_addrs())
             .flatten()
-            .collect::<Vec<SocketAddr>>()
+            .collect()
     }
 
     /// Get the initial seed peers based on the configured network.
-    pub fn initial_peers(&self) -> Vec<SocketAddr> {
+    pub fn initial_peers(&self) -> HashSet<SocketAddr> {
```
Comment (dconnolly) [inline zebra-network/src/config.rs:61]: 👍

**Comment by yaahc** [comment]
It looks like all of the pushing into the set is really done by the flat_map and collect in `parse_peers`, which will just ignore duplicates which is pretty much exactly what we want.

However, in the process of reviewing this i noticed that `parse_peers` silently discards errors from the socket resolution, which makes me a little anxious. How do we feel about making this fn return a `Result`?

File: zebra-network/src/config.rs [hunk 3]
```diff
@@ -21,11 +21,11 @@ pub struct Config {
 
     /// A list of initial peers for the peerset when operating on
     /// mainnet.
-    pub initial_mainnet_peers: Vec<String>,
+    pub initial_mainnet_peers: HashSet<String>,
```
Comment (dconnolly) [inline zebra-network/src/config.rs:24]: 👍

File: zebra-network/src/config.rs [hunk 4]
```diff
@@ -1,7 +1,7 @@
 use std::{
     net::{SocketAddr, ToSocketAddrs},
     string::String,
-    time::Duration,
+    time::Duration, collections::HashSet,
```
Comment (dconnolly) [inline zebra-network/src/config.rs:4]: 👍

File: zebra-network/src/config.rs [hunk 5]
```diff
@@ -21,11 +21,11 @@ pub struct Config {
 
     /// A list of initial peers for the peerset when operating on
     /// mainnet.
-    pub initial_mainnet_peers: Vec<String>,
+    pub initial_mainnet_peers: HashSet<String>,
 
     /// A list of initial peers for the peerset when operating on
     /// testnet.
-    pub initial_testnet_peers: Vec<String>,
+    pub initial_testnet_peers: HashSet<String>,
```
Comment (dconnolly) [inline zebra-network/src/config.rs:28]: 👍

File: zebra-network/src/config.rs [hunk 6]
```diff
@@ -49,16 +49,16 @@ pub struct Config {
 }
 
 impl Config {
-    fn parse_peers<S: ToSocketAddrs>(peers: Vec<S>) -> Vec<SocketAddr> {
+    fn parse_peers<S: ToSocketAddrs>(peers: HashSet<S>) -> HashSet<SocketAddr> {
```
Comment (dconnolly) [inline zebra-network/src/config.rs:52]: 👍

**Review by dconnolly — APPROVED** [review]
😎

**Comment by dconnolly** [comment]
> It looks like all of the pushing into the set is really done by the flat_map and collect in `parse_peers`, which will just ignore duplicates which is pretty much exactly what we want.
> 
> However, in the process of reviewing this i noticed that `parse_peers` silently discards errors from the socket resolution, which makes me a little anxious. How do we feel about making this fn return a `Result`?

I am cool with returning a `Result` and handling it 👍
