### PR TITLE
Deduplicate metrics dependencies

### LINKED ISSUE #1349: Metrics regression: some metrics don't appear in the exporter
**Version**

`main`

**Description**

After #1330 I noticed a problem where a bunch of metrics didn't show up. I'm not sure if it's connected, or a local misconfiguration on my part.

That change bumped the metrics version in order to pick up a new version of the exporter, because the old version used an old version of hyper that expected to run on the Tokio 0.2 runtime.  The new version builds its own single-threaded runtime for the exporter and launches it on a worker thread.

If we have problems like this, we can roll back to the previous version of the metrics crate, and avoid the Tokio incompatibilities by copying the worker thread code from the current prometheus exporter but using it to launch a single-threaded Tokio 0.2 runtime for the old metrics exporter.  This is probably faster than trynig to spend a lot of time debugging metrics issues right now.

### PR DESCRIPTION
**Pull request by yaahc**
## Motivation

This PR is motivated by the regression identified in https://github.com/ZcashFoundation/zebra/issues/1349. That PR notes that the metrics stopped working for most of the crates other than `zebrad`.

## Solution

This PR resolves the regression by deduplicating the `metrics` crate dependency. During a recent change we upgraded the metrics version in `zebrad` and a couple other of our crates, but we never updated the dependencies in `zebra-state`, `zebra-consensus`, or `zebra-network`. This caused the metrics macros to attempt to retrieve the current metrics exporter through the wrong function. We would install the metrics exporter in `0.13`, but then attempt to look it up through the `0.12` crate, which contains a different instance of the metrics exporter static variable which is unset. Doing this causes the metrics macros to return `None` for the current exporter after which they just silently give up.

## Related Issues

closes https://github.com/ZcashFoundation/zebra/issues/1349

## Follow Up Work

I noticed we have quite a few duplicate dependencies in our tree. We might be able to save some compilation time by auditing those and deduplicating them as much as possible.

- https://github.com/ZcashFoundation/zebra/issues/1582

### CODE REVIEW

**Comment by teor2345** [comment]
> I noticed we have quite a few duplicate dependencies in our tree. We might be able to save some compilation time by auditing those and deduplicating them as much as possible.

It would be good to have an automated way to detect and prevent duplicate dependencies.

File: zebra-consensus/src/checkpoint.rs [hunk 1]
```diff
@@ -393,12 +393,12 @@ where
     /// Increase the current checkpoint height to `verified_height`,
     fn update_progress(&mut self, verified_height: block::Height) {
         if let Some(max_height) = self.queued.keys().next_back() {
-            metrics::gauge!("checkpoint.queued.max.height", max_height.0 as i64);
+            metrics::gauge!("checkpoint.queued.max.height", max_height.0 as f64);
         } else {
             // use -1 as a sentinel value for "None", because 0 is a valid height
-            metrics::gauge!("checkpoint.queued.max.height", -1);
+            metrics::gauge!("checkpoint.queued.max.height", -1.0);
```
Comment (teor2345) [inline zebra-consensus/src/checkpoint.rs]: Since this is just a sentinel value, what happens if we use `NaN` here?
```suggestion
            metrics::gauge!("checkpoint.queued.max.height", f64::NAN);
```

File: zebra-network/src/peer_set/initialize.rs [hunk 2]
```diff
@@ -272,7 +272,10 @@ where
     let mut crawl_timer = tokio::time::interval(new_peer_interval);
 
     loop {
-        metrics::gauge!("crawler.in_flight_handshakes", handshakes.len() as i64 - 1);
+        metrics::gauge!(
+            "crawler.in_flight_handshakes",
+            (handshakes.len() - 1) as f64
```
Comment (teor2345) [inline zebra-network/src/peer_set/initialize.rs]: Do we need to check that this calculation is valid?
```suggestion
            handshakes.len().checked_sub(1).expect("the pool always contains an unresolved future") as f64
```

File: zebra-consensus/src/checkpoint.rs [hunk 3]
```diff
@@ -393,12 +393,12 @@ where
     /// Increase the current checkpoint height to `verified_height`,
     fn update_progress(&mut self, verified_height: block::Height) {
         if let Some(max_height) = self.queued.keys().next_back() {
-            metrics::gauge!("checkpoint.queued.max.height", max_height.0 as i64);
+            metrics::gauge!("checkpoint.queued.max.height", max_height.0 as f64);
         } else {
             // use -1 as a sentinel value for "None", because 0 is a valid height
```
Comment (teor2345) [inline zebra-consensus/src/checkpoint.rs]:
```suggestion
            // use f64::NAN as a sentinel value for "None", because 0 is a valid height
```

File: zebra-state/src/service/non_finalized_state/queued_blocks.rs [hunk 4]
```diff
@@ -141,12 +141,12 @@ impl QueuedBlocks {
     /// Update metrics after the queue is modified
     fn update_metrics(&self) {
         if let Some(max_height) = self.by_height.keys().next_back() {
-            metrics::gauge!("state.memory.queued.max.height", max_height.0 as i64);
+            metrics::gauge!("state.memory.queued.max.height", max_height.0 as f64);
         } else {
             // use -1 as a sentinel value for "None", because 0 is a valid height
```
Comment (teor2345) [inline zebra-state/src/service/non_finalized_state/queued_blocks.rs]:
```suggestion
            // use f64::NAN as a sentinel value for "None", because 0 is a valid height
```

File: zebra-state/src/service/non_finalized_state/queued_blocks.rs [hunk 5]
```diff
@@ -141,12 +141,12 @@ impl QueuedBlocks {
...
-            metrics::gauge!("state.memory.queued.max.height", -1);
+            metrics::gauge!("state.memory.queued.max.height", -1.0);
```
Comment (teor2345) [inline zebra-state/src/service/non_finalized_state/queued_blocks.rs]:
```suggestion
            metrics::gauge!("state.memory.queued.max.height", f64::NAN);
```

**Review by teor2345 — CHANGES_REQUESTED** [review]
Looks good

I have some suggestions for handling some edge cases, but we'll need to check how metrics, prometheus, and grafana handle `f64::NAN`s

**Comment by teor2345** [comment]
> I have some suggestions for handling some edge cases, but we'll need to check how metrics, prometheus, and grafana handle `f64::NAN`s

@yaahc do you have prometheus and grafana set up, or would you like me to do that testing?

**Comment by yaahc** [comment]
> > I noticed we have quite a few duplicate dependencies in our tree. We might be able to save some compilation time by auditing those and deduplicating them as much as possible.
> 
> It would be good to have an automated way to detect and prevent duplicate dependencies.

I should be able to set that up

> @yaahc do you have prometheus and grafana set up, or would you like me to do that testing?

I have it setup, though if you have any dashboard json files you use that you think might be useful that would be appreciated. I've not really got that part setup or figured out yet other than the two ones henry sent me a while back for network and checkpointing.

**Comment by teor2345** [comment]
> > > I noticed we have quite a few duplicate dependencies in our tree. We might be able to save some compilation time by auditing those and deduplicating them as much as possible.
> > 
> > 
> > It would be good to have an automated way to detect and prevent duplicate dependencies.
> 
> I should be able to set that up

@dconnolly can dependabot remove duplicate dependencies?
It seems like that should be part of its job - making sure every Zebra crate is using the same version of each dependency.

**Comment by teor2345** [comment]
> > @yaahc do you have prometheus and grafana set up, or would you like me to do that testing?
> 
> I have it setup, though if you have any dashboard json files you use that you think might be useful that would be appreciated. I've not really got that part setup or figured out yet other than the two ones henry sent me a while back for network and checkpointing.

Edit: here are my grafana dashboards for checkpoint verification, full block verification, and network activity:

https://gist.github.com/teor2345/2e34ef736f514201f2215053725f626f

**Comment by teor2345** [comment]
I didn't get a chance to test this today, but I put a link to all my grafana dashboards in the previous post.

(I edited it to remove the outdated link.)

**Comment by yaahc** [comment]
> > > > I noticed we have quite a few duplicate dependencies in our tree. We might be able to save some compilation time by auditing those and deduplicating them as much as possible.
> > > 
> > > 
> > > It would be good to have an automated way to detect and prevent duplicate dependencies.
> > 
> > 
> > I should be able to set that up
> 
> @dconnolly can dependabot remove duplicate dependencies?
> It seems like that should be part of its job - making sure every Zebra crate is using the same version of each dependency.

I don't think dependabot can handle this but thankfully the tool does exist and it's called [`guppy`](https://crates.io/crates/guppy). It's not really polished and reusable the way dependabot is but Rain (the author) and I talked about it over the weekend and they pointed me to the implementation of this exact check in their codebase on `diem`.

* https://github.com/diem/diem/blob/76576974dc47bada937c2851b62060a43fc0bd55/devtools/x/src/lint/guppy.rs#L262-L311

I talked about this a bit with Pili and Antonie already but I was thinking this would be a great issue for external contributors. I'm gonna to ahead and throw together an issue for implementing the duplicate dependency lint and sketch out a design for how to fit it into zebra, ideally in a reusable way so other projects can easily add this check to their codebase as well. Then, once I've got the issue setup I'll go ahead and put it on this-week-in-rust and wherever else I can find to connect us with contributors looking for work to practice on.

**Comment by yaahc** [comment]
I think this is ready now so I set it to auto merge once it's approved @teor2345

**Review by teor2345 — APPROVED** [review]
Looks great, and we've tested it to make sure the grafana output is good
