### PR TITLE
fix(consensus): reuse sighasher when validating txs

### LINKED ISSUE #9532: feature: actually cache sighash context
### Motivation

In https://github.com/ZcashFoundation/zebra/pull/8566 I updated `zebra-script` for the new `zcash-script` callback API. I changed the  `SigHasher` to support precomputation which we had in the old API... but it ended up not being actually used 😬  (that PR was super tricky and I guess after I got it to work I completely forgot about getting the precomputation part to work).

We should changed it so that the `SigHasher` is actually stored inside `CachedFfiTransaction` or something equivalent. We should also find a way to share the `SigHasher` with the shielded transaction validation.

I'm not sure how big will be the performance gain but it should be an easy quick win.

### Specifications

_No response_

### Complex Code or Requirements

_No response_

### Testing

_No response_

### Related Work

_No response_

### PR DESCRIPTION
**Pull request by conradoplg**
## Motivation

We were creating a new sighasher context for each input being verified, which is incredibly wasteful - not only because the sighasher context can be reused, but also because building the sighasher requires converting from a Zebra tx to a librustzcash tx via serializing/deserializing, and librustzcash deserializing also suffers from #7939 

Closes #9532 

## Solution

Create a sighasher in `CachedFfiTransaction::new()` and use it for all validations. Also reuse it when verifying shielded transactions.

This required changing the wrap the `all_previous_outputs` `Vec<Output>` in an `Arc`. It was possible to just move it all the way down to the `PrecomputedData` and add getters for it all the way back to `CachedFfiTransaction`, but using `Arc` seemed much simpler and mimics how `Transaction` is handled (also with an `Arc`)

I also moved `legacy_sigop_count()` out of `CachedFfiTransaction` because otherwise using it would require creating a `CachedFfiTransaction` with a dummy network upgrade; and I think it didn't actually belong there because it does not use anything in `CachedFfiTransaction` other then the transaction reference itself.

### Tests

Existing tests should ensure it will work.

We don't have benchmarks for this but the performance gains should be immediate. I'll also run a full sync to see what happens.

### PR Checklist

- [ ] The PR name is suitable for the release notes.
- [ ] The solution is tested.
- [ ] The documentation is up to date.

### CODE REVIEW

File: zebra-script/src/lib.rs [hunk 1]
```diff
@@ -42,6 +42,10 @@ pub enum Error {
     TxCoinbase,
     /// unknown error from zcash_script: {0}
     Unknown(zcash_script_error_t),
+    /// transaction is invalid according to zebra_chain (not a zcash_script error)
+    //TODO: ideally this should be `#[from] zebra_chain::Error` but that does
+    //not implement Clone
```
Comment (upbqdn) [inline zebra-script/src/lib.rs]: Can we not derive it?

File: zebra-chain/src/transaction/sighash.rs [hunk 2]
```diff
@@ -67,28 +69,28 @@ impl AsRef<[u8]> for SigHash {
...
     /// Create a new SigHasher for the given transaction.
     ///
     /// # Panics
     ///
     /// - If `trans` can't be converted to its `librustzcash` equivalent. This could happen, for
     ///   example, if `trans` contains the `nConsensusBranchId` field, and `nu` doesn't match it.
-    ///   More details in [`PrecomputedTxData::new`].
-    /// - If `nu` doesn't contain a consensus branch id convertible to its `librustzcash`
+    ///   More details [`PrecomputedTxData::new`].
+    /// - If `nu` doesn't contain a consensuranch id convertible to its `librustzcash`
```
Comment (upbqdn) [inline zebra-chain/src/transaction/sighash.rs]: Why this change?

```suggestion
    /// - If `nu` doesn't contain a consensus branch id convertible to its `librustzcash`
```

File: zebra-chain/src/transaction/sighash.rs [hunk 3]
```diff
@@ -67,28 +69,28 @@ impl AsRef<[u8]> for SigHash {
...
+impl SigHasher {
     /// Create a new SigHasher for the given transaction.
     ///
     /// # Panics
     ///
     /// - If `trans` can't be converted to its `librustzcash` equivalent. This could happen, for
     ///   example, if `trans` contains the `nConsensusBranchId` field, and `nu` doesn't match it.
-    ///   More details in [`PrecomputedTxData::new`].
-    /// - If `nu` doesn't contain a consensus branch id convertible to its `librustzcash`
+    ///   More details [`PrecomputedTxData::new`].
```
Comment (upbqdn) [inline zebra-chain/src/transaction/sighash.rs]:
```suggestion
    ///   More details in [`PrecomputedTxData::new`].
```

File: zebra-script/src/lib.rs (hunk 1 above)
Comment (conradoplg) [reply zebra-script/src/lib.rs]: We can't, that contains an `io::Error` that annoyingly does not implement `Clone`

File: zebra-chain/src/transaction/sighash.rs (hunk 2 above)
Comment (conradoplg) [reply zebra-chain/src/transaction/sighash.rs]: Weird, some search&replace mistake, thanks!

**Review by upbqdn — DISMISSED** [review]

File: zebra-script/src/lib.rs [hunk 4]
```diff
@@ -42,6 +42,10 @@ pub enum Error {
...
+    TxInvalid,
 }
```
Comment (arya2) [inline zebra-script/src/lib.rs]: This should work for keeping the `Clone` impl, but not the `Copy` impl.

```suggestion
    TxInvalid(#[from] std::sync::Arc<zebra_chain::Error>),
}

impl From<zebra_chain::Error> for Error {
    fn from(value: zebra_chain::Error) -> Self {
        std::sync::Arc::new(value).into()
    }
}
```

File: zebra-script/src/lib.rs [hunk 5]
```diff
@@ -55,6 +59,7 @@ impl fmt::Display for Error {
                 "tx is a coinbase transaction and should not be verified".to_owned()
             }
             Error::Unknown(e) => format!("unknown error from zcash_script: {e}"),
+            Error::TxInvalid => "tx is invalid".to_owned(),
```
Comment (arya2) [inline zebra-script/src/lib.rs]:
```suggestion
            Error::TxInvalid(e) => format!("tx is invalid: {e}"),
```

File: zebra-chain/src/transaction/tests/vectors.rs [hunk 6]
```diff
@@ -549,7 +555,8 @@ fn test_vec243_1() -> Result<()> {
 
     let transaction = ZIP243_1.zcash_deserialize_into::<Transaction>()?;
 
-    let hasher = SigHasher::new(&transaction, NetworkUpgrade::Sapling, &[]);
+    let hasher = SigHasher::new(&transaction, NetworkUpgrade::Sapling, Arc::new(Vec::new()))
```
Comment (arya2) [inline zebra-chain/src/transaction/tests/vectors.rs:558]: Optional/Nitpick: This could be simplified if we accept `impl Into<Vec<Output>>` for the `all_previous_outputs` param in `SigHasher::new()`.

```suggestion
    let hasher = SigHasher::new(&transaction, NetworkUpgrade::Sapling, [])
```

```rust

    pub fn new(
        trans: &Transaction,
        nu: NetworkUpgrade,
        all_previous_outputs: impl Into<Vec<transparent::Output>>,
    ) -> Result<Self, Error> {
        Ok(SigHasher {
            precomputed_tx_data: PrecomputedTxData::new(
                trans,
                nu,
                Arc::new(all_previous_outputs.into()),
            )?,
        })
    }

```

File: zebra-script/src/lib.rs [hunk 7]
```diff
@@ -217,46 +235,46 @@ impl CachedFfiTransaction {
...
-                    unsafe {
-                        zcash_script::zcash_script_legacy_sigop_count_script(
-                            script.as_ptr(),
-                            script.len() as u32,
-                        )
-                    }
+/// Returns the number of transparent signature operations in the
+/// transparent inputs and outputs of the given transaction.
+#[allow(clippy::unwrap_in_result)]
+pub fn legacy_sigop_count(transaction: &Transaction) -> Result<u64, Error> {
```
Comment (arya2) [inline zebra-script/src/lib.rs:239]: Optional/Nitpick: Would it be nice to make this a trait method and implement it for both `Transaction` and `CachedFfiTransaction`?

**Review by arya2 — DISMISSED** [review]
Last commit looks good, the production changes look good and should fix the issue. Nice catch!

I left a few suggestions for cleanup, but no blockers.

File: zebra-chain/src/transaction/tests/vectors.rs [hunk 8]
```diff
@@ -874,20 +874,16 @@ fn consensus_branch_id() {
...
+            let err = PrecomputedTxData::new(&tx, any_other_nu, Arc::new(Vec::new())).unwrap_err();
+            assert!(matches!(err, crate::Error::InvalidConsensusBranchId));
+
+            let err = sighash::SigHasher::new(&tx, any_other_nu, Arc::new(Vec::new())).unwrap_err();
+            assert!(matches!(err, crate::Error::InvalidConsensusBranchId));
+
+            let err = tx
+                .sighash(any_other_nu, HashType::ALL, Arc::new(Vec::new()), None)
+                .unwrap_err();
+            assert!(matches!(err, crate::Error::InvalidConsensusBranchId));
```
Comment (arya2) [inline zebra-chain/src/transaction/tests/vectors.rs]: Optional/Nitpick: It may be nice to have the old panic messages in `expect_err()` for these `assert!`s too.

File: zebra-script/src/lib.rs (hunk 4 above)
Comment (conradoplg) [reply zebra-script/src/lib.rs]: I love this. I considered using `Arc` but didn't considering manually adding a `From` to a avoid all the breakage.

In fact I think I'll try to do this where `io::Error` is used, if it works I'll create a separate PR just for that.

Thanks!

File: zebra-chain/src/transaction/tests/vectors.rs (hunk 6 above)
Comment (conradoplg) [reply zebra-chain/src/transaction/tests/vectors.rs:558]: Oof that would have saved me some work :rofl: I'll do it anyway, it looks much better, thanks!

File: zebra-script/src/lib.rs (hunk 7 above)
Comment (upbqdn) [reply zebra-script/src/lib.rs:239]: I can try that in a subsequent PR.

File: zebra-chain/src/transaction/tests/vectors.rs (hunk 8 above)
Comment (conradoplg) [reply zebra-chain/src/transaction/tests/vectors.rs]: Done in 9db4f0a1b

File: zebra-script/src/lib.rs (hunk 4 above)
Comment (conradoplg) [reply zebra-script/src/lib.rs]: I think it was small enough so I sneaked this in b69d1a5. Let me know if you'd prefer a separate PR

File: zebra-script/src/lib.rs (hunk 5 above)
Comment (conradoplg) [reply zebra-script/src/lib.rs]: Done in b69d1a5

File: zebra-chain/src/transaction/tests/vectors.rs (hunk 6 above)
Comment (conradoplg) [reply zebra-chain/src/transaction/tests/vectors.rs:558]: Now that I thought about it I'm not sure, the whole point of using `Arc` was to avoid cloning the entire vector. However if we do this, `CachedFfiTransaction` will have to clone it when calling `Sighasher::new()`.

I imagine there might be some trait magic to make this (make a function receive either T or `Arc<T>` and automatically wrap in a `Arc` if it is `T`) work but I couldn't find it.

In hindsight I think just moving the vector all the way down to `PrecomputedTx` might have been the best approach, but I guess it doesn't really matter that much

File: zebra-script/src/lib.rs (hunk 7 above)
Comment (conradoplg) [reply zebra-script/src/lib.rs:239]: I'll leave this as is then

Comment (upbqdn) [reply zebra-script/src/lib.rs:239]: I'll need sigops for lrz txs.

File: zebra-chain/src/transaction/tests/vectors.rs (hunk 6 above)
Comment (arya2) [reply zebra-chain/src/transaction/tests/vectors.rs:558]: > Now that I thought about it I'm not sure, the whole point of using Arc was to avoid cloning the entire vector.

It'll still do that, `Sighasher::new()` is _now_ only called once in the transaction verifier via `CachedFfiTransaction::new()`. 

Update: I see, it has a copy in `all_previous_outputs` and another copy on the `sighasher` field. Slight waste of memory when blocks are being synced out of order (if it were to be updated to accept `Into<Vec<_>>` instead of `Arc<Vec<_>>`). We could remove the `all_previous_outputs` field altogether and make it a function that gets it from the `Sighasher` to avoid that:

```rust

impl PrecomputedTxData{
    pub fn all_prev_outputs(&self) -> Arc<Vec<transparent::Output>> {
        self.all_previous_outputs.clone()
    }
}

impl SigHasher {
    pub fn all_prev_outputs(&self) -> Arc<Vec<transparent::Output>> {
        self.precomputed_tx_data.all_prev_outputs()
    }
}

impl CachedFfiTransaction {
    pub fn all_previous_outputs(&self) -> Arc<Vec<transparent::Output>> {
        self.sighasher.all_prev_outputs()
    }

    pub fn is_valid(&self, input_index: usize) -> Result<(), Error> {
        let all_previous_outputs = self.all_previous_outputs();
        let previous_output = all_previous_outputs
        ..
    }
}

```


Previously it would've cloned it, which wasn't terrible since the items are `Copy` if not for re-constructing the entire `Sighasher` and `zp_tx::TransactionData`.

Not very important here either way, I mostly wanted to advertise the pattern.

File: zebra-script/src/lib.rs (hunk 4 above)
Comment (arya2) [reply zebra-script/src/lib.rs]: I'm happy for it to go in this PR. 

Could we implement `PartialEq` for the `zebra_script` Error type instead?

File: zebra-chain/src/error.rs [hunk 9]
```diff
@@ -57,17 +57,47 @@ pub enum AddressError {
...
+                    // is the main purpose for our usage of PartialEq for errors
+                    e.to_string() == o.to_string()
+                } else {
+                    false
+                }
+            }
+            Error::MissingNetworkUpgrade => matches!(other, Error::MissingNetworkUpgrade),
+        }
+    }
+}
```
Comment (arya2) [inline zebra-chain/src/error.rs:101]: We should implement this for the error type in `zebra-script` instead and say it's partially equal as long as the enum variant matches. I think we should avoid implementing `Eq` for that too.

File: zebra-chain/src/transaction/tests/vectors.rs (hunk 6 above)
Comment (arya2) [reply zebra-chain/src/transaction/tests/vectors.rs:558]: > Not very important here either way, I mostly wanted to advertise the pattern.

It would be nice to get rid of the duplicate field, but accepting the generic param still seems unimportant.

File: zebra-chain/src/error.rs (hunk 9 above)
Comment (conradoplg) [reply zebra-chain/src/error.rs:101]: Why do you think that? I don't think two `zebra_script::Error::TxInvalid(e)` should be considered equal if `e` is different between them.

File: zebra-chain/src/transaction/tests/vectors.rs (hunk 6 above)
Comment (conradoplg) [reply zebra-chain/src/transaction/tests/vectors.rs:558]: > We could remove the `all_previous_outputs` field altogether and make it a function that gets it from the `Sighasher` to avoid that:

That would work for `CachedFfiTransaction`, but `Sighasher` would need to do the same since `PrecomputedTxData` (a `Sighasher` field) also needs `all_previous_output`... and there is now a bit trickier, because it's put into a `MapTransparent` struct which is passed to `.map_authorization()` but I'm not sure if you can ever fetch it back after that. It just seemed simpler to use `Arc`

File: zebra-chain/src/error.rs (hunk 9 above)
Comment (arya2) [reply zebra-chain/src/error.rs:101]: > Why do you think that?

I think it's okay because that was the behaviour before, but, it's not ideal.

**Review by arya2 — APPROVED** [review]
