### PR TITLE
Handle duplicate blocks in zebra-state

### LINKED ISSUE #1182: Panic: hashes must be unique in memory_state
**Version**

zebrad main branch, 19 October 2020.

**Platform**

`Linux ... 5.4.68 #1-NixOS SMP Sat Sep 26 16:03:16 UTC 2020 x86_64 GNU/Linux`

**Description**

While syncing mainnet blocks, `zebrad` panicked with a "hashes must be unique" error in `memory_state`, inside the span `zebra_state::service::queue_and_commit_non_finalized_blocks`.

I tried this:

Partially syncing mainnet, a sync hang (#1181), then restarting `zebrad` so sync could continue.

I expected to see this happen:

A successful sync to the tip.

Instead, this happened: [explanation]

A block timeout error, followed by a `zebra-state` panic.

## Metadata
|key|value|
|--|--|
|**version**|3.0.0-alpha.0|

## Block Download Error
```
Error: 
   0: failed to verify block
   1: request timed out
```

## SpanTrace

<details>

```
SpanTrace:
   0: zebrad::components::sync::block_fetch_verify
           with hash=00000000024f9794d9cfe1d7ab6e7e23e7fa68dbc00316ea6e9a0c96358f73b4
             at zebrad/src/components/sync.rs:615
   1: zebrad::components::sync::extend_tips
             at zebrad/src/components/sync.rs:434
   2: zebrad::components::sync::sync
             at zebrad/src/components/sync.rs:169
```
</details>

## State Error
```
hashes must be unique
```

## SpanTrace

<details>

```
SpanTrace:
   0: zebra_state::service::queue_and_commit_non_finalized_blocks
             at zebra-state/src/service.rs:76
   1: zebrad::components::sync::block_fetch_verify
           with hash=000000000166f4b01559db2831189c088a99943ba2db2b40b4d068412ea16454
             at zebrad/src/components/sync.rs:615
   2: zebrad::components::sync::obtain_tips
             at zebrad/src/components/sync.rs:314
   3: zebrad::components::sync::sync
             at zebrad/src/components/sync.rs:169
```
</details>

### PR DESCRIPTION
**Pull request by yaahc**
## Motivation

The zebra-state service needs to be able to handle duplicate blocks
~idempotently. When we receive a `CommitBlock` request for a block that has
already been queued we should subscribe to the existing channel for sending the
result of commiting that block. If we receive a block that has already been
succesfully committed to the non-finalized or finalized state we should
immediately respond to the request that the block was committed succesfully.~

## Solution

This implements changes already outlined by [The State
RFC](https://zebra.zfnd.org/dev/rfcs/0005-state-updates.html). We check for
successfully committed blocks first, since interacting with the queued blocks
struct at this point just complicates the implimentation. If the block has not
already been committed we then check if the block has already been queued, if
not we handle the block normally (normally here being the bit we already had
implemented).

## Documentation Changes

- [x] Update the state RFC to match the ways this fix departs from the design
	- the main thing is that I switched the order of checking for duplicates
- [x] ~~Add newly added functions to the state rfc~~ Decided not to do this because they're minor getters that don't influence the rest of the design and aren't exposed as part of the API
- [x] Document newly added functions inline

## Related Issues

- fixes https://github.com/ZcashFoundation/zebra/issues/1182
- tracking issue https://github.com/ZcashFoundation/zebra/issues/1049

### CODE REVIEW

File: zebra-state/src/service.rs [hunk 1]
```diff
@@ -118,6 +136,17 @@ impl StateService {
         self.mem.any_chain_contains(hash) || &self.sled.finalized_tip_hash() == hash
     }
 
+    /// Returns true if the given hash has been committed to either the finalized
+    /// or non-finalized state.
+    fn contains(&self, block: &Block) -> bool {
```
Comment (teor2345) [inline zebra-state/src/service.rs]: Tweak: the queue also contains blocks, so let's qualify this function name.

```suggestion
    fn contains_committed_block(&self, block: &Block) -> bool {
```

File: zebra-state/src/sled_state.rs [hunk 2]
```diff
@@ -289,6 +289,13 @@ impl FinalizedState {
         }
     }
 
+    pub fn get_hash(&self, height: block::Height) -> Option<block::Hash> {
+        self.hash_by_height
+            .get(&height.0.to_be_bytes())
+            .expect("sled errors aren't handled")
```
Comment (teor2345) [inline zebra-state/src/sled_state.rs]: Question: what does this expect mean?

Should the errors be handled by sled?
Or should the errors never happen?

**Review by teor2345 — APPROVED** [review]
This looks really good, I like how neat the implementation is.

I'd like @hdevalence to double-check the channel stuff.

**Review by teor2345 — DISMISSED** [review]
Edit: This error was due to #1041.

**Comment by teor2345** [comment]
Edit: This error was due to #1041.

**Review by dconnolly — DISMISSED** [review]

**Comment by hdevalence** [comment]
Just to back up a second, why do we need to handle duplicate blocks idempotently?

**Comment by yaahc** [comment]
@hdevalence previous discussion https://github.com/ZcashFoundation/zebra/pull/1101#discussion_r501381091

**Comment by hdevalence** [comment]
Thanks for the pointer!

File: zebra-state/src/sled_state.rs (hunk 2 above)
Comment (yaahc) [reply zebra-state/src/sled_state.rs]: The errors are likely indicative of IO errors, we could handle them in theory but I think that's a level of reliability we shouldn't concern ourselves with, the idea being if their disk starts failing we just panic at the first sign of trouble.

File: book/src/dev/rfcs/0005-state-updates.md [hunk 3]
```diff
@@ -528,30 +528,29 @@ New `non-finalized` blocks are commited as follows:
 
 ### `pub(super) fn queue_and_commit_non_finalized_blocks(&mut self, new: Arc<Block>) -> tokio::sync::broadcast::Receiver<block::Hash>`
 
-1. If a duplicate block exists in the queue:
```
Comment (teor2345) [inline book/src/dev/rfcs/0005-state-updates.md:531]: We need to revise the RFC to return an error:
* if there are two pending blocks, return an error for the older pending duplicate block, and replace the older block with the newer block
* if there is a committed block, return an error for the newer block

We won't need a broadcast channel any more.

File: zebra-state/src/service.rs [hunk 4]
```diff
@@ -73,14 +73,30 @@ impl StateService {
...
-        let parent_hash = new.block.header.previous_block_hash;
+    #[instrument(skip(self, block))]
+    fn queue_and_commit_non_finalized_blocks(
+        &mut self,
+        block: Arc<Block>,
+    ) -> broadcast::Receiver<Result<block::Hash, CloneError>> {
+        let hash = block.hash();
+        let parent_hash = block.header.previous_block_hash;
+
+        if self.contains_committed_block(&block) {
```
Comment (teor2345) [inline zebra-state/src/service.rs:83]: if there is a committed block, return an error for the newer block

File: zebra-state/src/service.rs [hunk 5]
```diff
@@ -73,14 +73,30 @@ impl StateService {
...
     ///
     /// [1]: https://zebra.zfnd.org/dev/rfcs/0005-state-updates.html#committing-non-finalized-blocks
-    #[instrument(skip(self, new))]
-    fn queue_and_commit_non_finalized_blocks(&mut self, new: QueuedBlock) {
-        let parent_hash = new.block.header.previous_block_hash;
+    #[instrument(skip(self, block))]
+    fn queue_and_commit_non_finalized_blocks(
+        &mut self,
+        block: Arc<Block>,
+    ) -> broadcast::Receiver<Result<block::Hash, CloneError>> {
```
Comment (teor2345) [inline zebra-state/src/service.rs]: We won't need a broadcast channel any more.

File: zebra-state/src/service.rs [hunk 6]
```diff
@@ -73,14 +73,30 @@ impl StateService {
...
+
+        if self.contains_committed_block(&block) {
+            let (rsp_tx, rsp_rx) = broadcast::channel(1);
+            let _ = rsp_tx.send(Ok(hash));
+            return rsp_rx;
+        }
 
-        self.queued_blocks.queue(new);
+        let rsp_rx = if let Some(queued_block) = self.queued_blocks.get(&hash) {
+            queued_block.rsp_tx.subscribe()
```
Comment (teor2345) [inline zebra-state/src/service.rs]: if there are two pending blocks, return an error for the older pending duplicate block, and replace the older block with the newer block

File: book/src/dev/rfcs/0005-state-updates.md [hunk 7]
```diff
@@ -526,32 +526,35 @@ The state service uses the following entry points:
...
-     - Create an extra receiver for the existing block, using `block.rsp_tx.subscribe`,
-     - Drop the newly received duplicate block
-     - Return the extra receiver, so it can be used in the response future for the duplicate block request
-
-2. Create a `QueuedBlock` for `block`:
-     - Create a `tokio::sync::broadcast` channel
-     - Use that channel to create a `QueuedBlock` for `block`.
-
-3. If a duplicate block exists in a non-finalized chain, or the finalized chain,
+1. If a duplicate block exists in a non-finalized chain, or the finalized chain,
```
Comment (teor2345) [inline book/src/dev/rfcs/0005-state-updates.md]:
```suggestion
1. If a duplicate block hash exists in a non-finalized chain, or the finalized chain,
```

File: book/src/dev/rfcs/0005-state-updates.md [hunk 8]
```diff
@@ -526,32 +526,35 @@ The state service uses the following entry points:
...
    it has already been successfully verified:
-     - Broadcast `Ok(block.hash())` via `block.rsp_tx`, and return the receiver for the block's channel
+     - create a new oneshot channel
+     - immediately send `Err(DuplicateBlock)` drop the sender
+     - return the reciever
 
-4. Add `block` to `self.queued_blocks`
-
-5. If `block.header.previous_block_hash` is not present in the finalized or
+2. If a duplicate block exists in the queue:
```
Comment (teor2345) [inline book/src/dev/rfcs/0005-state-updates.md]:
```suggestion
2. If a duplicate block hash exists in the queue:
```

File: book/src/dev/rfcs/0005-state-updates.md [hunk 9]
```diff
@@ -526,32 +526,35 @@ The state service uses the following entry points:
...
-2. Create a `QueuedBlock` for `block`:
-     - Create a `tokio::sync::broadcast` channel
-     - Use that channel to create a `QueuedBlock` for `block`.
-
-3. If a duplicate block exists in a non-finalized chain, or the finalized chain,
+1. If a duplicate block exists in a non-finalized chain, or the finalized chain,
    it has already been successfully verified:
-     - Broadcast `Ok(block.hash())` via `block.rsp_tx`, and return the receiver for the block's channel
+     - create a new oneshot channel
+     - immediately send `Err(DuplicateBlock)` drop the sender
```
Comment (teor2345) [inline book/src/dev/rfcs/0005-state-updates.md]:
```suggestion
     - immediately send `Err(DuplicateBlockHash)` drop the sender
```

File: book/src/dev/rfcs/0005-state-updates.md [hunk 10]
```diff
@@ -526,32 +526,35 @@ The state service uses the following entry points:
...
+     - return the reciever
 
-4. Add `block` to `self.queued_blocks`
-
-5. If `block.header.previous_block_hash` is not present in the finalized or
+2. If a duplicate block exists in the queue:
+     - Find the `QueuedBlock` for that existing duplicate block
+     - create a new channel for the new request
+     - replace the old sender in `queued_block` with the new sender
+     - send `Err(DuplicateBlock)` through the old sender channel
```
Comment (teor2345) [inline book/src/dev/rfcs/0005-state-updates.md]:
```suggestion
     - send `Err(DuplicateBlockHash)` through the old sender channel
```

File: zebra-state/src/sled_state.rs (hunk 2 above)
Comment (teor2345) [reply zebra-state/src/sled_state.rs]:
```suggestion
            .expect("expected that sled errors would not occur")
```

Comment (teor2345) [reply zebra-state/src/sled_state.rs]: Let's use the same message as:
https://github.com/ZcashFoundation/zebra/blob/e05103323e95f76e2b8325c9239846cb2c3eaf71/zebra-state/src/service.rs#L92

File: zebra-state/src/service.rs [hunk 11]
```diff
@@ -73,14 +72,33 @@ impl StateService {
...
+        let hash = block.hash();
+        let parent_hash = block.header.previous_block_hash;
 
-        self.queued_blocks.queue(new);
+        if self.contains_committed_block(&block) {
+            let (rsp_tx, rsp_rx) = oneshot::channel();
+            let _ = rsp_tx.send(Err("duplicate block".into()));
+            return rsp_rx;
+        }
+
```
Comment (hdevalence) [inline zebra-state/src/service.rs:88]: It would be nice to have a comment here explaining the queue of blocks to be verified is a pipeline and that replacing older queued requests by newer ones is a way to lazily flush the pipeline.

**Review by hdevalence — DISMISSED** [review]
LGTM

**Comment by hdevalence** [comment]
Clippy failures are unrelated to this PR

**Review by hdevalence — APPROVED** [review]

**Review by dconnolly — COMMENTED** [review]
👍
