### PR TITLE
fix(network): Limit number of peer connections per IP address, Ignore new peer connections from the same IP and port

### LINKED ISSUE #6936: Zebra node establishes multiple inbound or outbound connections to the same peer
### What happened?

I set up a small testnet with two nodes, zcash and zebra.
When I ask a zcash node to add a connection to a zebra node with an rpc `addnode 'ip:port' onetry` I expect that the zebra node creates only a single inbound connection to this peer. 

Instead, this happened:
After that inbound conn is set up, the zebra node establishes a second outbound connection to the same zcash peer node, by learning, I believe, its address from the version message.
I think, this is a sort of a problem as the second connection wastes a slot in the limited connection list.

When komodod or zcashd node gets an inbound connection they won't create an outbound connection to the same peer, I believe, thankfully to this code:
https://github.com/zcash/zcash/blob/fa3827656df8f97fb4700b22022cc581fbda61fa/src/net.cpp#L1663 (checking that there is no peer with this ip address already).
Maybe this check was not implemented deliberately in Zebra but I have not found any explanations for that so I'm creating this issue just for sure.

### What were you doing when the issue happened?

`zcash-cli addnode 'ip:port' onetry` to connect a zcash node to a zebra node

### Zebra logs

_No response_

### Zebra Version

Zebra:1.0.0-rc.9 (build from the main branch on 12 June 2023)

### Which operating systems does the issue happen on?

- [ ] Linux
- [ ] macOS
- [ ] Windows
- [ ] Other OS

### OS details

not os dependent

### Additional information

Sample getpeerinfo output from a zcash node from a small testnet, with both inbound and outbound conns to a zebra node (7999 port is used for listening) :
```
./zcash-cli -testnet getpeerinfo
[
  {
    "id": 1,
    "addr": "XX.XX.87.135:7999",
    "addrlocal": "XX.XX.238.59:40006",
    "services": "0000000000000001",
    ...
    "version": 170100,
    "subver": "/Zebra:1.0.0-rc.9/",
     "inbound": false,
     ...
  },
  {
    "id": 2,
    "addr": "XX.XX.87.135:48982",
    "addrlocal": "XX.XX.238.59:7999",
    "services": "0000000000000001",
    ...
    "version": 170100,
    "subver": "/Zebra:1.0.0-rc.9/",
    "inbound": true,
     ...
  }
]
```

### PR DESCRIPTION
**Pull request by arya2**
## Motivation

This PR drops additional peer connections from a given IP after there are already `MAX_CONNS_PER_IP` in the peer set.

Closes #6936.

## Solution

- Define `MAX_CONNS_PER_IP`
- Count the number of keys in `PeerSet.ready_services` and `PeerSet.cancel_handles` before inserting new connections into the peer set
- Drop new connections when there are already `MAX_CONNS_PER_IP`

## Review

This is a routine security fix.

### Reviewer Checklist

  - [x] Will the PR name make sense to users?
    - [x] Does it need extra CHANGELOG info? (new features, breaking changes, large changes)
  - [x] Are the PR labels correct?
  - [x] Does the code do what the ticket and PR says?
    - [x] Does it change concurrent code, unsafe code, or consensus rules?
  - [x] How do you know it works? Does it have tests?

## Follow Up Work

- #6981 
- #6982

### CODE REVIEW

File: zebra-network/src/peer_set/set.rs [hunk 1]
```diff
@@ -497,6 +508,14 @@ where
                     // - check for any errors that happened right after the handshake
                     trace!(?key, "got Change::Insert from Discover");
                     self.remove(&key);
+
+                    // drop the new peer if its IP is in cancel_handles or ready_services,
```
Comment (arya2) [inline zebra-network/src/peer_set/set.rs]:
```suggestion
                    // drop the new peer if there are already `MAX_CONNS_PER_IP` peers with
                    // the same IP address in the peer set
```

File: zebra-network/src/constants.rs [hunk 2]
```diff
@@ -67,6 +67,10 @@ pub const INBOUND_PEER_LIMIT_MULTIPLIER: usize = 5;
 /// See [`INBOUND_PEER_LIMIT_MULTIPLIER`] for details.
 pub const OUTBOUND_PEER_LIMIT_MULTIPLIER: usize = 3;
 
+/// The maximum number of peer connections Zebra will for a given IP address
```
Comment (arya2) [inline zebra-network/src/constants.rs]:
```suggestion
/// The maximum number of peer connections Zebra will keep for a given IP address
```

File: zebra-network/src/peer_set/set.rs [hunk 3]
```diff
@@ -497,6 +508,15 @@ where
                     // - check for any errors that happened right after the handshake
                     trace!(?key, "got Change::Insert from Discover");
                     self.remove(&key);
```
Comment (teor2345) [inline zebra-network/src/peer_set/set.rs]: This `remove()` call is now incorrect.

For security/reliability reasons, I think old connections with exactly the same IP and port should stay, rather than replacing them with new connections. This matches the behaviour of the IP-based security fix in this PR.

Otherwise, two nodes could get in a loop where they initiate new connections, and they continually replace the other node's connection.

```suggestion
```

File: zebra-network/src/peer_set/set.rs [hunk 4]
```diff
@@ -497,6 +508,15 @@ where
...
+
+                    // drop the new peer if there are already `MAX_CONNS_PER_IP` peers with
+                    // the same IP address in the peer set
+                    // this is skipped for tests so we can mock peer connections
+                    #[cfg(not(test))]
+                    if self.num_peers_with_ip(key.ip()) > crate::constants::MAX_CONNS_PER_IP {
+                        continue;
```
Comment (teor2345) [inline zebra-network/src/peer_set/set.rs:546]: Nitpick: I prefer explicit drops, particularly in security fixes.

```suggestion
                        std::mem::drop(svc);
                        continue;
```

File: zebra-network/src/peer_set/set.rs [hunk 5]
```diff
@@ -497,6 +508,15 @@ where
                     // - check for any errors that happened right after the handshake
                     trace!(?key, "got Change::Insert from Discover");
                     self.remove(&key);
+
+                    // drop the new peer if there are already `MAX_CONNS_PER_IP` peers with
```
Comment (teor2345) [inline zebra-network/src/peer_set/set.rs:542]:
```suggestion
                    // # Security
                    //
                    // drop the new peer if there are already `MAX_CONNS_PER_IP` peers with
```

**Review by teor2345 — CHANGES_REQUESTED** [review]
I think this change needs some tests, what do you think?

File: zebra-network/src/peer_set/set.rs [hunk 6]
```diff
@@ -496,7 +507,18 @@ where
...
                     // - check for any errors that happened right after the handshake
                     trace!(?key, "got Change::Insert from Discover");
-                    self.remove(&key);
+
+                    // # Security
+                    //
+                    // drop the new peer if there are already `MAX_CONNS_PER_IP` peers with
+                    // the same IP address in the peer set
+                    // this is skipped for tests so we can mock peer connections
+                    #[cfg(not(test))]
```
Comment (teor2345) [inline zebra-network/src/peer_set/set.rs]: I just realised that disabling this check in tests will also disable it in integration and acceptance tests. So we'll still get the testnet failures we're seeing on other PRs in CI.

File: zebra-network/src/peer_set/set.rs [hunk 7]
```diff
@@ -496,7 +507,18 @@ where
                     // - always do the same checks on every ready peer, and
                     // - check for any errors that happened right after the handshake
                     trace!(?key, "got Change::Insert from Discover");
-                    self.remove(&key);
```
Comment (teor2345) [inline zebra-network/src/peer_set/set.rs:499]: I just realised my suggestion here is wrong, we still have to do something about duplicate connections to the same IP and port.

So I opened #6983.

Comment (arya2) [reply zebra-network/src/peer_set/set.rs:499]: > for outbound connections, this can cause connection thrashing, if two peers disagree on which of their connections is "latest"

Good thinking keeping the older connection.

File: zebra-network/src/peer_set/set.rs (hunk 6 above)
Comment (arya2) [reply zebra-network/src/peer_set/set.rs]: Replaced with a configurable `max_conns_per_ip` in https://github.com/ZcashFoundation/zebra/pull/6980/commits/cbd9041affac75f684b41058379e17caa060743b.

Comment (teor2345) [reply zebra-network/src/peer_set/set.rs]: Thanks!

File: zebra-network/src/peer_set/set.rs [hunk 8]
```diff
@@ -282,6 +287,9 @@ where
     /// - `inv_stream`: receives inventory changes from peers,
     ///                 allowing the peer set to direct inventory requests;
     /// - `address_book`: when peer set is busy, it logs address book diagnostics.
+    /// - `minimum_peer_version`: endpoint to see the minimum peer protocol version in real time.
```
Comment (teor2345) [inline zebra-network/src/peer_set/set.rs:290]: Technically minimum peer version updates are delayed until blocks are verified, even if the network has a higher minimum

```suggestion
    /// - `minimum_peer_version`: endpoint to see the minimum peer protocol version based on the latest state tip height.
```

**Review by teor2345 — APPROVED** [review]
Thanks for the tests!

File: zebra-network/src/peer_set/set.rs (hunk 8 above)
Comment (teor2345) [reply zebra-network/src/peer_set/set.rs:290]: This isn't a blocker so I'm just going to merge the PR
