### PR TITLE
feature(rpc): add fixed values to getblocktemplate response

### LINKED ISSUE #5452: Populate `Blocktemplate` responses with fixed values data
## Motivation

Several `BlockTemplate`  fields introduced in https://github.com/ZcashFoundation/zebra/issues/5451 are fixed values. 

## Tasks

- [ ] Add fixed values to the response of the `getblocktemplate` RPC call. These values should use the relevant Zebra constants, or create a new constant.
  - `version`: `4` - existing block version number constant from block parser
  - `mutable`: `["time", "transactions", "prevblock"]` - new constant list of strings
  - `noncerange`: `00000000ffffffff` - new min and max nonce constants, set to `u32::MIN` and `u32::MAX`
  - `sigoplimit`: `20000` - existing sigops limit constant from consensus rule check
  - `sizelimit`: `2000000` - existing block byte limit constant from block parser
- [ ] Update the test created at 1- so it can also test for fixed values in the responses.

Depends on https://github.com/ZcashFoundation/zebra/issues/5451

### PR DESCRIPTION
**Pull request by oxarbitrage**
## Motivation

Close https://github.com/ZcashFoundation/zebra/issues/5452

## Solution

Add constants where needed, get constant from other crates, update tests.

## Review

Anyone can review.

### Reviewer Checklist

  - [ ] Will the PR name make sense to users?
    - [ ] Does it need extra CHANGELOG info? (new features, breaking changes, large changes)
  - [ ] Are the PR labels correct?
  - [ ] Does the code do what the ticket and PR says?
  - [ ] How do you know it works? Does it have tests?

### CODE REVIEW

File: zebra-chain/src/block/header.rs [hunk 1]
```diff
@@ -146,6 +146,12 @@ const BLOCK_HEADER_LENGTH: usize =
 /// A CountedHeader has BLOCK_HEADER_LENGTH bytes + 1 or more bytes for the transaction count
 pub(crate) const MIN_COUNTED_HEADER_LEN: usize = BLOCK_HEADER_LENGTH + 1;
 
+/// The Zcash accepted block version.
+///
+/// The consensus rules do not force the block version to be this value but just equal or greater than it.
+/// However, it is suggested that submitted block versions to be of this exact value.
```
Comment (teor2345) [inline zebra-chain/src/block/header.rs:152]: Optional: Do you think it makes more sense to move the consensus rule docs here?

File: zebra-rpc/src/methods/tests/snapshot/snapshots/get_block_template@mainnet_10.snap [hunk 2]
```diff
@@ -1,10 +1,11 @@
 ---
 source: zebra-rpc/src/methods/tests/snapshot/get_block_template_rpcs.rs
+assertion_line: 128
```
Comment (teor2345) [inline zebra-rpc/src/methods/tests/snapshot/snapshots/get_block_template@mainnet_10.snap:3]: Optional: if you upgrade to `cargo insta` 1.13 or later, this line won't be added to snapshots any more. (Most of us have already upgraded.)

https://insta.rs/changelog/#1-13-0

File: zebra-rpc/src/methods/get_block_template_rpcs/constants.rs [hunk 3]
```diff
@@ -0,0 +1,15 @@
...
+pub const GET_BLOCK_TEMPLATE_NONCE_RANGE_FIELD: &str = "00000000ffffffff";
+
+lazy_static! {
+    /// A hardcoded list of fields that the miner can change from the block.
+    pub static ref GET_BLOCK_TEMPLATE_MUTABLE_FIELD: Vec<String> = vec![
+        "time".to_string(),
+        "transactions".to_string(),
+        "prevblock".to_string()
+    ];
+}
```
Comment (teor2345) [inline zebra-rpc/src/methods/get_block_template_rpcs/constants.rs]: I'd like to avoid new uses of `lazy_static`, because its maintainer is slow, and it has known bugs:
- https://github.com/rust-lang-nursery/lazy-static.rs/issues/201
- https://github.com/rust-lang-nursery/lazy-static.rs/issues/204

Instead, we can use a constant value, see my PR #5559.

File: zebra-rpc/src/methods/get_block_template_rpcs.rs [hunk 4]
```diff
@@ -324,12 +328,17 @@ where
...
+                nonce_range: constants::GET_BLOCK_TEMPLATE_NONCE_RANGE_FIELD.to_string(),
 
-                nonce_range: empty_string.clone(),
+                // Max legacy signature operations in the block.
+                sigop_limit: MAX_BLOCK_SIGOPS,
 
-                sigop_limit: 0,
-                size_limit: 0,
+                // Max block size in bytes
+                size_limit: MAX_BLOCK_BYTES,
```
Comment (teor2345) [inline zebra-rpc/src/methods/get_block_template_rpcs.rs]: Can you add documentation to the `GetBlockTemplate` struct for these new fields?

**Review by teor2345 — COMMENTED** [review]
Thanks, looks good!

I have a suggestion in PR #5559, and it will help me to review if we add documentation for the new fields.

**Comment by teor2345** [comment]
@Mergifyio update

**Comment by teor2345** [comment]
@mergifyio update

File: zebra-rpc/src/methods/get_block_template_rpcs.rs (hunk 4 above)
Comment (oxarbitrage) [reply zebra-rpc/src/methods/get_block_template_rpcs.rs]: https://github.com/ZcashFoundation/zebra/pull/5558/commits/5590d0cab8339748ed97f88fcf40cf144916ec18

File: zebra-rpc/src/methods/get_block_template_rpcs/constants.rs (hunk 3 above)
Comment (oxarbitrage) [reply zebra-rpc/src/methods/get_block_template_rpcs/constants.rs]: Thanks.

File: zebra-rpc/src/methods/tests/snapshot/snapshots/get_block_template@mainnet_10.snap (hunk 2 above)
Comment (oxarbitrage) [reply zebra-rpc/src/methods/tests/snapshot/snapshots/get_block_template@mainnet_10.snap:3]: I am not sure how to do this. I do have cargo insta 1.21 on my system and that are the snapshot it is doing.

File: zebra-rpc/src/methods/get_block_template_rpcs.rs (hunk 4 above)
Comment (teor2345) [reply zebra-rpc/src/methods/get_block_template_rpcs.rs]: My suggestion PR documented the roots fields that I missed in a previous PR.

But it's also important to document the mutable, nonce_range, sigop_limit, and size_limit fields on the struct. (The docs here are good, you can just copy them to the struct definition.)

File: zebra-rpc/src/methods/tests/snapshot/snapshots/get_block_template@mainnet_10.snap (hunk 2 above)
Comment (teor2345) [reply zebra-rpc/src/methods/tests/snapshot/snapshots/get_block_template@mainnet_10.snap:3]: That's strange, maybe you have multiple versions installed?
You could try running `cargo install cargo-insta` to update it.

But it's not a big deal, it should keep on working until Zebra starts using a feature your version doesn't have.

**Comment by teor2345** [comment]
This PR has conflicts with PR #5554, which just merged. So it will need to be rebased or it will need a merge commit.

**Comment by oxarbitrage** [comment]
The tests will fail because they all get into this code section https://github.com/ZcashFoundation/zebra/blob/304048efe2a07eec86110d7c3cdeb08bb01f16cc/zebra-rpc/src/methods/get_block_template_rpcs.rs#L280

where everything is empty.

I am unsure if we should update the test and snapshots to be empty or if we should add the fixed values into that code as well.

**Comment by teor2345** [comment]
> The tests will fail because they all get into this code section
> 
> https://github.com/ZcashFoundation/zebra/blob/304048efe2a07eec86110d7c3cdeb08bb01f16cc/zebra-rpc/src/methods/get_block_template_rpcs.rs#L280
> 
> where everything is empty.
> 
> I am unsure if we should update the test and snapshots to be empty or if we should add the fixed values into that code as well.

That code disappears in my next PR #5580, so you could base this PR on that one, or copy the fixed values into the code that is about to be deleted?

**Review by teor2345 — APPROVED** [review]
Thanks, looks good!
