### PR TITLE
fix(chain): Return errors instead of panicking in methods for `Height`s

### LINKED ISSUE #7263: Return errors instead of panicking in methods for  `Height`s
### Motivation

Resolve the issues raised in https://github.com/ZcashFoundation/zebra/pull/7239#discussion_r1266136500.

### PR DESCRIPTION
**Pull request by upbqdn**
## Motivation

Close #7263.

## Solution

- Don't panic in:
	- `Height::next()`, and
	- `Height::previous()`.

And instead:

- Create a new error type `HeightError`.
- Return the new error type wrapped in `Result`.

### Reviewer Checklist

  - [ ] Will the PR name make sense to users?
    - [ ] Does it need extra CHANGELOG info? (new features, breaking changes, large changes)
  - [ ] Are the PR labels correct?
  - [ ] Does the code do what the ticket and PR says?
    - [ ] Does it change concurrent code, unsafe code, or consensus rules?
  - [ ] How do you know it works? Does it have tests?

### CODE REVIEW

File: zebra-state/src/service/non_finalized_state/chain.rs [hunk 1]
```diff
@@ -556,7 +556,7 @@ impl Chain {
         // Don't add a new tree unless it differs from the previous one or there's no previous tree.
         if height.is_min()
             || self
-                .sprout_tree(height.previous().into())
+                .sprout_tree(height.previous().unwrap().into())
```
Comment (upbqdn) [inline zebra-state/src/service/non_finalized_state/chain.rs]: It's OK to use `unwrap()` here because `previous()` gets executed only when `height.is_min()` returns `false` at line 557. Likewise for all the other `unwrap()`s in this PR.

File: zebra-chain/src/block/height.rs [hunk 2]
```diff
@@ -24,6 +25,14 @@ pub mod json_conversion;
 #[derive(Copy, Clone, Debug, Eq, PartialEq, PartialOrd, Ord, Hash, Serialize, Deserialize)]
 pub struct Height(pub u32);
 
+#[derive(Error, Debug)]
+pub enum HeightError {
+    #[error("The resulting height would ovferflow Height::MAX.")]
```
Comment (teor2345) [inline zebra-chain/src/block/height.rs]:
```suggestion
    #[error("The resulting height would overflow Height::MAX.")]
```

File: zebra-state/src/service/finalized_state/disk_format/upgrade/add_subtrees.rs [hunk 3]
```diff
@@ -353,7 +353,12 @@ fn check_sapling_subtrees(db: &ZebraDb) -> Result<(), &'static str> {
         }
         // Check that the final note has a greater subtree index if it didn't complete a subtree.
         else {
-            let Some(prev_tree) = db.sapling_tree_by_height(&subtree.end.previous()) else {
+            let prev_height = subtree
+                .end
+                .previous()
+                .expect("Height should not underflow here.");
```
Comment (teor2345) [inline zebra-state/src/service/finalized_state/disk_format/upgrade/add_subtrees.rs]: Usually we put a reason in the `expect()` string, so it's easier to fix bugs.

```suggestion
                .expect("underflow is impossible: Sapling activation is a long way from genesis");
```

Comment (teor2345) [reply zebra-state/src/service/finalized_state/disk_format/upgrade/add_subtrees.rs]: This applies to all the `expect()` and `unwrap()` in this PR.

File: zebra-state/src/service/non_finalized_state/chain.rs (hunk 1 above)
Comment (teor2345) [reply zebra-state/src/service/non_finalized_state/chain.rs]: Usually in this situation we would say `expect("already checked for underflow")` so if we're wrong it's easier to diagnose the bug.

**Review by teor2345 — COMMENTED** [review]
Would you mind putting a reason in every `expect()`, and turning every `unwrap()` into an `expect()` with a reason?

That way the PR will be easier to review, and if the `expect()` fails we'll be able to fix it.

File: zebra-chain/src/block/height.rs (hunk 2 above)
Comment (upbqdn) [reply zebra-chain/src/block/height.rs]: This was a handy typo because it made the length of the line match the one below for underflows. Goodbye, typo.

**Comment by upbqdn** [comment]
Thanks for noting that I should improve the error messages. It didn't occur to me that I didn't actually explain why we can always expect an `Ok`.

I generally try to follow the "expect as precondition" style: https://doc.rust-lang.org/std/error/index.html#common-message-styles.

File: zebra-state/src/service/non_finalized_state/chain.rs (hunk 1 above)
Comment (upbqdn) [reply zebra-state/src/service/non_finalized_state/chain.rs]: Done in [bad9fbb](https://github.com/ZcashFoundation/zebra/pull/7591/commits/bad9fbbaf644248ba687a4a5f7da816c5abbfa57).

**Review by teor2345 — APPROVED** [review]
Thanks!
