### PR TITLE
fix: Speed up the block round trip proptest

### LINKED ISSUE #803: slow test cleanup
Right now a few of our tests, particularly our proptests it seems, take a while to run. For CI this isn't as big of a deal but Ideally I'd like to be able to run tests super quickly locally before push. We should investigate fixing up particularly long running tests if possible or setting them to `#[ignored]` by default so we only run the particularly slow tests in CI.

### PR DESCRIPTION
**Pull request by teor2345**
Reduce the number of cases run by the block round trip proptest, to
speed up the Zebra tests.

Closes #803.

### CODE REVIEW

**Comment by teor2345** [comment]
After this change, using this script:

```sh
for d in zebra*; do
    pushd "$d"
    cargo --quiet test --no-run
    time cargo --quiet test
    popd
done
```

The crates with test times over 1 second are:

zebra-chain
real    0m8.927s
user    0m39.625s

zebra-consensus
real    0m1.716s
user    0m2.761s

zebrad
real    0m3.837s
user    0m1.772s

**Comment by teor2345** [comment]
@yaahc is 15-20 seconds fast enough for all the Zebra tests, or would you like me to tweak them some more?

**Review by yaahc — APPROVED** [review]
15-20 seconds is plenty good I expect, lol.

File: zebra-chain/src/block/tests.rs [hunk 1]
```diff
@@ -210,6 +211,11 @@ proptest! {
 
         prop_assert_eq![header, other_header];
     }
+}
+
+proptest! {
+    // The block roundtrip test can be really slow
+    #![proptest_config(Config::with_cases(16))]
```
Comment (dconnolly) [inline zebra-chain/src/block/tests.rs:218]: Where does the value '16' come from?

**Review by dconnolly — COMMENTED** [review]
I'm ok with configuring the number of proptests run, I wonder if we can use the env vars it looks at to make it 'faster' where needed (local before push) and 'slower' where capacity allows (CI, where we can require even more test cases to pass if we want). 

https://docs.rs/proptest/0.10.0/proptest/prelude/struct.ProptestConfig.html#structfield.cases

image

File: zebra-chain/src/block/tests.rs (hunk 1 above)
Comment (teor2345) [reply zebra-chain/src/block/tests.rs:218]: The largest power of two which executes in under 10 seconds on my machine.

**Comment by teor2345** [comment]
> I'm ok with configuring the number of proptests run, I wonder if we can use the env vars it looks at to make it 'faster' where needed (local before push) and 'slower' where capacity allows (CI, where we can require even more test cases to pass if we want).

I don't want to globally override the number of cases by default, because only the block rests are slow right now.

But I could use the cases env var where it exists, and then default to 16 block cases. That way, we can increase the number of cases in CI, or decrease them even further right before push.

(Most of the time when I'm developing, each change takes me longer than 20 seconds to write.)

**Review by hdevalence — APPROVED** [review]
lgtm

**Comment by teor2345** [comment]
> But I could use the cases env var where it exists, and then default to 16 block cases. That way, we can increase the number of cases in CI, or decrease them even further right before push.

See #828 for this change.
