### PR TITLE
fix(consensus): Check that Zebra's state contains the social consensus chain on startup

### LINKED ISSUE #5912: On startup, check that the finalized state blocks match the checkpoint hashes
## Motivation

Currently, Zebra doesn't check if its checkpoints match the blocks in its cached state. This means that Zebra can follow a chain fork for a very long time, even after restarts.

This has become more of an issue recently, because Zebra will soon be able to:
- mine its own blocks, and
- generate its own checkpoints.

### Specifications

`zcashd` checks for a few well-known block hashes on startup, which are typically network upgrade activations.

### Complex Code or Requirements

To avoid startup delays, Zebra can do these checks concurrently with the rest of its startup and sync tasks. This can happen in a similar way to the Zcash parameter downloads. (But it can be async, because the state service is async.)

https://github.com/ZcashFoundation/zebra/blob/bc783a7745251b7ab0e23d58c26080191c6306ca/zebra-consensus/src/chain.rs#L242-L251

### Testing

We could manually insert a bad block hash into the database, then run this check and make sure it fails.

The success case will be covered by existing tests.

## Related Work

This is part of a larger issue for the Zcash network - we don't have good monitoring for chain forks or other serious network events.

We also want to track the recent chain forks that an individual Zebra node has discovered in our metrics:
- #5297

### PR DESCRIPTION
**Pull request by teor2345**
## Motivation

Zebra does not check that the state has followed the correct chain, but this is a new consensus requirement on mainnet.

Closes #5912

### Specifications

> A network upgrade is settled on a given network when there is a social consensus that it has activated with a given activation block hash. A full validator that potentially risks Mainnet funds or displays Mainnet transaction information to a user MUST do so only for a block chain that includes the activation block of the most recent settled network upgrade

https://zips.z.cash/protocol/protocol.pdf#blockchain

### Complex Code or Requirements

This PR adds another short startup task using the existing concurrent task framework and event loop.

## Solution

- [Validate existing state block hashes at startup](https://github.com/ZcashFoundation/zebra/commit/c5a685a0ef2038129c21f3914828b0c24f3538f2)
    - [Make Request::BestChainBlockHash redirect to the ReadStateService](https://github.com/ZcashFoundation/zebra/commit/f2955cb552f382e19fb630537d7b07927285dbd5)
- [Monitor state block hash checkpoint task in the start command](https://github.com/ZcashFoundation/zebra/commit/f5dca6cb4491ef940829b8bfce73354580454d25)
- [Re-write the checkpoint_sync config docs based on the latest consensus rules](https://github.com/ZcashFoundation/zebra/commit/320b61c8ad004bd427003240c64ddc94f68a0981)

Unrelated cleanups:
- [Allow missing docs directly on derived error types](https://github.com/ZcashFoundation/zebra/commit/b1565ace0b4499a170712b6eab93ae39b34c3cfa)

### Testing

New tests:
- check that this code is active in the existing cached state tests
- check that it fails when the checkpoints don't match the previous cached state (and succeeds when they do)

I also did full and partial syncs locally, and they passed. (I had some unrelated issues with syncing due to proof errors, likely caused by disk corruption.)

### Changelog

Added security and deprecation notes in this PR.

## Review

This PR's code is ready for review. It is not on the critical path.

### Reviewer Checklist

  - [ ] Will the PR name make sense to users?
    - [x] Does it need extra CHANGELOG info? (new features, breaking changes, large changes)
  - [ ] Are the PR labels correct?
  - [ ] Does the code do what the ticket and PR says?
    - [ ] Does it change concurrent code, unsafe code, or consensus rules?
  - [ ] How do you know it works? Does it have tests?

## Follow Up

- #6178

### CODE REVIEW

**Comment by teor2345** [comment]
This new task takes about one second on my machine, about the same time as validating the Zcash parameters:
```
2023-02-15T02:51:47.494988Z  INFO {zebrad="f5dca6c" net="Main"}: zebrad::commands::start: initializing verifiers
2023-02-15T02:51:47.494999Z  INFO {zebrad="f5dca6c" net="Main"}:crawl_and_dial{new_peer_interval=61s}: zebra_network::peer_set::initialize: starting the peer address crawler crawl_new_peer_interval=61s outbound_connections=18
2023-02-15T02:51:47.495024Z  INFO {zebrad="f5dca6c" net="Main"}:init{config=Config { checkpoint_sync: true, debug_skip_parameter_preload: false } network=Mainnet debug_skip_parameter_preload=false}: zebra_consensus::chain: starting state checkpoint validation...
2023-02-15T02:51:47.495058Z  INFO {zebrad="f5dca6c" net="Main"}:init{config=Config { checkpoint_sync: true, debug_skip_parameter_preload: false } network=Mainnet debug_skip_parameter_preload=false}: zebra_consensus::primitives::groth16::params: checking and loading Zcash Sapling and Sprout parameters
2023-02-15T02:51:47.498429Z  INFO {zebrad="f5dca6c" net="Main"}:init{config=Config { checkpoint_sync: true, debug_skip_parameter_preload: false } network=Mainnet debug_skip_parameter_preload=false}: zebra_consensus::chain: initializing chain verifier tip=Some((Height(1984325), block::Hash("00000000011c7c1efffc288d30fae56d9f3a82ad62c662e81c63c3c1984d755d"))) max_checkpoint_height=Height(1965904)
2023-02-15T02:51:47.498444Z  INFO {zebrad="f5dca6c" net="Main"}: zebrad::commands::start: initializing syncer
2023-02-15T02:51:47.498459Z  INFO {zebrad="f5dca6c" net="Main"}: zebrad::commands::start: initializing mempool
2023-02-15T02:51:47.498470Z  INFO {zebrad="f5dca6c" net="Main"}: zebra_rpc::server: Trying to open RPC endpoint at 0.0.0.0:28232...
2023-02-15T02:51:47.515981Z  INFO {zebrad="f5dca6c" net="Main"}: zebra_rpc::server: Opened RPC endpoint at 0.0.0.0:28232
2023-02-15T02:51:47.516147Z  INFO {zebrad="f5dca6c" net="Main"}: zebrad::commands::start: spawned initial Zebra tasks
2023-02-15T02:51:47.516252Z  INFO {zebrad="f5dca6c" net="Main"}: zebrad::components::mempool::crawler: initializing mempool crawler task
2023-02-15T02:51:47.516252Z  INFO {zebrad="f5dca6c" net="Main"}: zebrad::components::sync::gossip: initializing block gossip task
2023-02-15T02:51:47.516269Z  INFO {zebrad="f5dca6c" net="Main"}: zebrad::components::mempool::gossip: initializing transaction gossip task
2023-02-15T02:51:47.516268Z  INFO {zebrad="f5dca6c" net="Main"}: zebra_state::config: finished old database version cleanup task
2023-02-15T02:51:47.516272Z  INFO {zebrad="f5dca6c" net="Main"}: zebrad::components::mempool::queue_checker::initializing mempool queue checker task
2023-02-15T02:51:47.519140Z  INFO {zebrad="f5dca6c" net="Main"}:sync:try_to_sync: zebrad::components::sync::starting sync, obtaining new tips state_tip=Some(Height(1984325))
2023-02-15T02:51:47.520915Z  INFO {zebrad="f5dca6c" net="Main"}: zebrad::components::sync::progress: estimated progress to chain tip sync_percent=99.995% current_height=Height(1984325) network_upgrade=Nu5 remaining_sync_blocks=109 time_since_last_state_block=0s
2023-02-15T02:51:47.973306Z  INFO {zebrad="f5dca6c" net="Main"}:init{config=Config { checkpoint_sync: true, debug_skip_parameter_preload: false } network=Mainnet debug_skip_parameter_preload=false}: zebra_consensus::chain: finished state checkpoint validation
2023-02-15T02:51:48.466416Z  INFO {zebrad="f5dca6c" net="Main"}:init{config=Config { checkpoint_sync: true, debug_skip_parameter_preload: false } network=Mainnet debug_skip_parameter_preload=false}: zebra_consensus::primitives::groth16::params: Zcash Sapling and Sprout parameters downloaded and/or verified
```

**Comment by teor2345** [comment]
I'm also seeing these errors in this PR:

`zebrad start`:
> 2023-02-15T02:51:50.507488Z  WARN {zebrad="f5dca6c" net="Main"}:sync:try_to_sync: zebrad::components::sync: error downloading and verifying block e=Invalid { error: Block { source: Transaction(InternalDowncastError("downcast to known transaction error type failed, original error: ConstraintSystemFailure")) }, height: Height(1984331), hash: block::Hash("000000000130ba233dcbe01f5a4fcfeb2d1e590176d06d33fefbe2028d29a8ff") }

`cargo test`:
> ---- primitives::halo2::tests::verify_generated_halo2_proofs stdout ----
> The application panicked (crashed).
> Message:  assertion failed: verify_orchard_halo2_proofs(&mut verifier, shielded_data).await.is_ok()
> Location: zebra-consensus/src/primitives/halo2/tests.rs:164

They seem unrelated to this change, but maybe it is exposing a concurrency bug?

**Comment by teor2345** [comment]
> I'm also seeing these errors in this PR:
> 
> `zebrad start`:
> 
> > 2023-02-15T02:51:50.507488Z  WARN {zebrad="f5dca6c" net="Main"}:sync:try_to_sync: zebrad::components::sync: error downloading and verifying block e=Invalid { error: Block { source: Transaction(InternalDowncastError("downcast to known transaction error type failed, original error: ConstraintSystemFailure")) }, height: Height(1984331), hash: block::Hash("000000000130ba233dcbe01f5a4fcfeb2d1e590176d06d33fefbe2028d29a8ff") }
> 
> `cargo test`:
> 
> > ---- primitives::halo2::tests::verify_generated_halo2_proofs stdout ----
> > The application panicked (crashed).
> > Message:  assertion failed: verify_orchard_halo2_proofs(&mut verifier, shielded_data).await.is_ok()
> > Location: zebra-consensus/src/primitives/halo2/tests.rs:164
> 
> They seem unrelated to this change, but maybe it is exposing a concurrency bug?

These also happen for me on the `main` branch. It's possible we have a bug in `main`, or I have a corrupt file on disk.

File: zebra-consensus/src/chain.rs [hunk 1]
```diff
@@ -262,6 +262,78 @@ where
...
+                        if checkpoint_sync {
+                            tracing::info!(
+                                "state is not fully synced yet, remaining checkpoints will be \
+                                 verified during syncing"
+                            );
+                        } else {
+                            tracing::warn!(
+                                "state is not fully synced yet, remaining checkpoints will be \
+                                 verified next time Zebra starts up. Zebra will be less secure \
+                                 until it is restarted"
```
Comment (arya2) [inline zebra-consensus/src/chain.rs]: Optional: Suggest using `checkpoint_sync = true` to verify checkpoints during sync?

File: zebra-consensus/src/config.rs [hunk 2]
```diff
@@ -4,17 +4,28 @@ use serde::{Deserialize, Serialize};
...
+    /// # Details
     ///
-    /// Future versions of Zebra may change the required and optional checkpoints.
+    /// This option is `true` by default, because it prevents some kinds of chain attacks.
+    ///
+    /// Disabling this option makes Zebra start full validation earlier.
+    /// It is slower and less secure.
+    ///
+    /// Zebra requires some checkpoints to simplify validation of legacy network upgrades.
+    /// So those checkpoints are always active, even when this option is `false`.
```
Comment (arya2) [inline zebra-consensus/src/config.rs]: Nitpick:
```suggestion
    /// Required checkpoints are always active, even when this option is `false`.
```

File: zebra-consensus/src/chain.rs [hunk 3]
```diff
@@ -296,15 +368,16 @@ where
     (
         chain,
         transaction,
-        groth16_download_handle,
+        // TODO: turn this into a struct?
+        vec![groth16_download_handle, state_checkpoint_verify_handle],
```
Comment (arya2) [inline zebra-consensus/src/chain.rs]: Optional: return `[JoinHandle<()>; 2]` here and de-structure it in the start command.
```suggestion
        [groth16_download_handle, state_checkpoint_verify_handle],
```

**Review by arya2 — COMMENTED** [review]
This is looking good!

File: zebra-consensus/src/chain.rs (hunk 1 above)
Comment (teor2345) [reply zebra-consensus/src/chain.rs]: Thanks, fixed in 9d63e068ce.

I think this is actually required, because the setting is required to satisfy the Zcash spec.

File: zebra-consensus/src/config.rs (hunk 2 above)
Comment (teor2345) [reply zebra-consensus/src/config.rs]: Fixed in a6dca646d3, I also clarified other docs in that module.

File: zebra-consensus/src/chain.rs (hunk 3 above)
Comment (teor2345) [reply zebra-consensus/src/chain.rs]: I'm probably going to work on this tomorrow, and use a struct so we have named fields and can't get them mixed up.

**Comment by teor2345** [comment]
Coverage failed downloading Zcash parameters:
> thread 'main' panicked at 'error downloading Sapling parameter files after 3 retries. IoError(Custom { kind: InvalidData, error: "sapling-spend.params failed validation:\nexpected: 8270785a1a0d0bc77196f000ee6d221c9c9894f55307bd9357c3f0105d31ca63991ab91324160d8f53e2bbd3c2633a6eb8bdf5205d822e7f3f73edac51b2b70c hashing 47958396 bytes,\nactual:   786a02f742015903c6c6fd852552d272912f4740e15847618a86e217f71f5419d25e1031afee585313896444934eb04b903a685b1448b755d56f701afe9be2ce hashing 0 bytes from \"https://download.z.cash/downloads/sapling-spend.params.part.1 + [https://download.z.cash/downloads/sapling-spend.params.part.2\](https://download.z.cash/downloads/sapling-spend.params.part.2/)"" })

https://github.com/ZcashFoundation/zebra/actions/runs/4192197818/jobs/7267473489#step:9:18

It's possible the download server is very slow right now.

File: zebra-consensus/src/chain.rs (hunk 3 above)
Comment (teor2345) [reply zebra-consensus/src/chain.rs]: Fixed in b4499bd

File: zebrad/tests/common/sync.rs [hunk 4]
```diff
@@ -314,6 +314,10 @@ pub fn check_sync_logs_until(
     if check_legacy_chain {
         zebrad.expect_stdout_line_matches("starting legacy chain check")?;
         zebrad.expect_stdout_line_matches("no legacy chain found")?;
+
+        zebrad.expect_stdout_line_matches("starting state checkpoint validation")?;
+        // TODO: what if the mempool is enabled for debugging before this finishes?
```
Comment (arya2) [inline zebrad/tests/common/sync.rs:319]: What would be the issue if the mempool is enabled for debugging?

**Review by arya2 — DISMISSED** [review]
There are "missing documentation for a struct field" warnings in the `BackgroundTaskHandles`, but this looks perfect otherwise!

File: zebrad/tests/common/sync.rs (hunk 4 above)
Comment (teor2345) [reply zebrad/tests/common/sync.rs:319]: Those logs would be discarded while we're still waiting for this line, then the mempool log checks below would fail.

**Comment by teor2345** [comment]
> There are "missing documentation for a struct field" warnings in the `BackgroundTaskHandles`, but this looks perfect otherwise!

Oops, that should be fixed now!

File: zebrad/tests/common/sync.rs (hunk 4 above)
Comment (arya2) [reply zebrad/tests/common/sync.rs:319]: Ah, okay. This fn isn't used with `debug_enable_at_height` anywhere currently so a TODO should be sufficient.

**Review by arya2 — DISMISSED** [review]
Looks great! Thank you!

**Comment by mpguerra** [comment]
@Mergifyio refresh

**Comment by teor2345** [comment]
@mergifyio update

**Comment by teor2345** [comment]
Failed due to bug #5940, that fix is in the `main` branch now.

**Comment by teor2345** [comment]
@arya2 this just needs a re-approval after a `main` branch merge.

**Review by arya2 — APPROVED** [review]

**Comment by teor2345** [comment]
@mergifyio refresh

**Comment by teor2345** [comment]
Unrelated failure in the getblocktemplate tests, I'll open another ticket.

**Comment by teor2345** [comment]
@mergifyio refresh
