### PR TITLE
Security: stop gossiping failure and attempt times as last_seen times

### LINKED ISSUE #1867: Security: Zebra should stop gossiping unreachable addresses to other nodes, Action: re-deploy all nodes
## User Actions for the Changelog

Re-deploy all running Zebra nodes after fixing this bug. This bug fix allows the network to delete the unreachable peer addresses introduced by #2120, and kept alive by #1868.

## Motivation

Zebra relays peer addresses to other nodes, even if it hasn't been able to contact those peers itself, and even if the `untrusted_last_seen` time gossiped by other nodes is a long way in the past.

Zebra is currently keeping unreachable addresses in its address book, and sending them to other peers, so this security fix is important and urgent.

### Specification

"The typical presumption is that a node is likely to be active if it has been sending a message within the last three hours."

https://en.bitcoin.it/wiki/Protocol_documentation#getaddr

This time period is a network health / network view leakage design tradeoff.

## Solution

This fix depends on #1849 and #1871.

Zebra should stop gossiping peers that haven't had a successful connection or sent a message for 3 hours.

To avoid sending old peers from other nodes, Zebra should stop gossiping peers where:
- [ ] the `last_success_time` is older than 3 hours
- [ ] the `last_success_time` is `None`, and the `untrusted_last_seen_time` is older than 3 hours (requires the far-future fix in #1871)

We can make these changes in the `AddressBook::sanitized` function.

Zebra should also:
- [x] provide an accessor method on `MetaAddr` to simplify the interface to the `last_success_time` and `untrusted_last_seen_time`
- [x] avoid updating timestamps based on new gossips from other peers (security fixes must maintain this constraint)

Property testing:
- [ ] Generate some random `MetaAddr`s
- [ ] Put them in an `AddressBook`
- [ ] Sanitize the address book
- [ ] Make sure that old `last_success_time`s and `untrusted_last_seen_time`s are handled correctly

Acceptance testing:
- [ ] add a `debug_gossip_max_peer_age` config
- [ ] add an acceptance test that sets it to `10` seconds
- [ ] add a log when peers are skipped because they're too old, and check for that log

## Alternatives

This is a serious security issue, so we must do something. If we find a simpler design that fixes this security issue, we should use it.

## Context

`zcashd` and Zebra will check addresses for connectivity, then move on to other addresses. So this is not a critical security issue.

## Follow-Up Tasks

We might want to do #1865 after this ticket - they modify the same code.

As a follow-up, we should review this design, and make sure that we're minimising network-based metadata leaks in Zebra.

### LINKED ISSUE #1868: Security: Zebra should stop gossiping failure times as last_seen times
## Motivation

Zebra updates its internal `last_seen` time when it fails to connect to other nodes. Then it sends that time on to other nodes who request peer addresses. But the `last_seen` time should only be updated on a successful connection to a peer.

## Solution

This fix depends on #1849.

Zebra should use an accurate time in gossiped `MetaAddr`s.

Zebra should set the `last_seen` time in gossiped `MetaAddr`s to:
- [x] `last_success_time`
- [x] if `last_success_time` is `None`, `untrusted_last_seen` (the time gossiped by other peers for this peer)
  - the accuracy of `untrusted_last_seen` is improved by #1871, but that fix is not required for this fix to be effective
- [x] provide an accessor method on `MetaAddr` to simplify the interface to these times

## Alternatives

This is a critical security issue, so we must do something.

This seems like the simplest design that will fix this issue. #1867 already limits how long we'll send `untrusted_last_seen` to other peers.

## Context

`zcashd` is not vulnerable to this issue - it ignores `last_seen` times from peers.

### PR DESCRIPTION
**Pull request by teor2345**
## Motivation

Previously, Zebra had a single time field for each peer, which was updated every time a peer was attempted, sent a message, or failed.

This is a security issue, because the `last_seen` time should be "the last time [a peer] connected to that node", so that
"nodes can use the time field to avoid relaying old 'addr' messages".

So Zebra was sending incorrect peer times to other nodes, which is malicious behaviour.

### Specifications

addr.time field description:
> Nodes advertising IP addresses they’ve connected to set this to the last time they connected to that node. Other nodes just relaying the IP address should not change the time. Nodes can use the time field to avoid relaying old “addr” messages. Malicious nodes may change times or even set them in the future.

https://developer.bitcoin.org/reference/p2p_networking.html#addr

### Designs

This PR uses the `DateTime32` type introduced in PR #2210, see ticket #2171 for more details.

### Security Changes

- Keep success times separate from failure and attempt times
- Only send success times to peers

### Other Required Changes

Split the `last_seen` time into the following fields:
- untrusted_last_seen: time gossiped from other peers - serialized `DateTime32`
- last_response: time we got a response from a directly connected peer - serialized `DateTime32`
- last_attempt: time we attempted to connect to a peer - monotonic `Instant`
- last_failure: time a connection with a peer failed - monotonic `Instant`

Send peer changes using a new `MetaAddrChange` type, so that senders don't accidentally overwrite peer fields with outdated data. (Due to concurrency, changes can be applied to the address book out of order.)

## Review

@jvff can review this PR. It's an important security fix, but it's not particularly urgent.

This PR should close #1868.

### Reviewer Checklist

  - [x] Code implements Specs and Designs
  - [x] Tests for Expected Behaviour
  - [ ] Tests for Errors

## Follow Up Work

This PR is part of a series of MetaAddr refactors.

After #1867 is fixed, the network will be able to remove the unreachable addresses introduced by #2120.

### CODE REVIEW

**Comment by teor2345** [comment]
I still need to write proptests to ensure:
- the untrusted last seen time is not updated by any change
- the services are only updated after a handshake
- the only times that get included in serialized `MetaAddr`s are the untrusted last seen and responded times

File: zebra-network/src/meta_addr.rs [hunk 1]
```diff
@@ -4,22 +4,27 @@ use std::{
...
+    time::Instant,
 };
 
 use byteorder::{LittleEndian, ReadBytesExt, WriteBytesExt};
 
+use chrono::Duration;
 use zebra_chain::serialization::{
     DateTime32, ReadZcashExt, SerializationError, TrustedPreallocate, WriteZcashExt,
     ZcashDeserialize, ZcashDeserializeInto, ZcashSerialize,
 };
```
Comment (jvff) [inline zebra-network/src/meta_addr.rs:16]: I'm not sure if I'm mistaken or being too nitpicky, but shouldn't the import groups be:

```suggestion
use byteorder::{LittleEndian, ReadBytesExt, WriteBytesExt};
use chrono::Duration;

use zebra_chain::serialization::{
    DateTime32, ReadZcashExt, SerializationError, TrustedPreallocate, WriteZcashExt,
    ZcashDeserialize, ZcashDeserializeInto, ZcashSerialize,
};
```

File: zebra-network/src/meta_addr.rs [hunk 2]
```diff
@@ -123,20 +143,136 @@ pub struct MetaAddr {
...
     pub last_connection_state: PeerAddrState,
+    //
+    // TODO: move the time and services fields into PeerAddrState?
+    //       then some fields could be required in some states
+}
+
+/// A change to an existing `MetaAddr`.
+#[derive(Copy, Clone, Debug, Eq, PartialEq)]
+#[cfg_attr(any(test, feature = "proptest-impl"), derive(Arbitrary))]
+pub enum MetaAddrChange {
```
Comment (jvff) [inline zebra-network/src/meta_addr.rs:182]: All variants have an `addr` field. I was wondering if it might make sense to split this type in two: `MetaAddrChange` and `MetaAddrEvent`, where:

```
pub struct MetaAddrChange {
    #[cfg_attr(
        any(test, feature = "proptest-impl"),
        proptest(strategy = "canonical_socket_addr()")
    )]
    addr: SockAddr,
    event: MetaAddrEvent,
}
```

and `MetaAddrEvent` is the (private?) `enum` with all the extra event-specific information. The downside is that it's an extra type, so I'm not sure if that's better :thinking:

File: zebra-network/src/meta_addr.rs [hunk 3]
```diff
@@ -162,85 +313,113 @@ impl MetaAddr {
...
 
-    /// Create a new `MetaAddr` for a peer that we want to reconnect to.
-    pub fn new_reconnect(addr: &SocketAddr, services: &PeerServices) -> MetaAddr {
-        MetaAddr {
-            addr: *addr,
-            services: *services,
-            last_seen: DateTime32::now(),
-            last_connection_state: AttemptPending,
-        }
+    /// Returns a [`MetaAddrChange::UpdateConnectionAttempt`] for a peer that we
```
Comment (jvff) [inline zebra-network/src/meta_addr.rs:323]:
```suggestion
    /// Returns a [`MetaAddrChange::UpdateAttempt`] for a peer that we
```

File: zebra-network/src/meta_addr.rs [hunk 4]
```diff
@@ -162,85 +313,113 @@ impl MetaAddr {
...
-    /// Create a new `MetaAddr` for our own listener address.
-    pub fn new_local_listener(addr: &SocketAddr) -> MetaAddr {
-        MetaAddr {
-            addr: *addr,
-            // TODO: create a "local services" constant
-            services: PeerServices::NODE_NETWORK,
-            last_seen: DateTime32::now(),
-            last_connection_state: Responded,
-        }
+    /// Returns a [`MetaAddrChange::NewLocalListener`] for our own listener address.
```
Comment (jvff) [inline zebra-network/src/meta_addr.rs:338]:
```suggestion
    /// Returns a [`MetaAddrChange::NewLocal`] for our own listener address.
```

File: zebra-network/src/meta_addr.rs [hunk 5]
```diff
@@ -162,85 +313,113 @@ impl MetaAddr {
...
     }
 
-    /// Create a new `MetaAddr` for a peer that has just had an error.
-    pub fn new_errored(addr: &SocketAddr, services: &PeerServices) -> MetaAddr {
-        MetaAddr {
+    /// Returns a [`MetaAddrChange::UpdateFailed`] for a peer that has just had
+    /// an error.
+    pub fn new_errored(
+        addr: &SocketAddr,
+        services: impl Into<Option<PeerServices>>,
```
Comment (jvff) [inline zebra-network/src/meta_addr.rs:347]: Nice! This is great for ergonomics! :tada:

File: zebra-network/src/meta_addr.rs [hunk 6]
```diff
@@ -259,18 +438,208 @@ impl MetaAddr {
...
+        }
+    }
+
+    /// Return the last attempt for this change, if available.
+    pub fn last_attempt(&self) -> Option<Instant> {
+        match self {
+            NewGossiped { .. } => None,
+            NewAlternate { .. } => None,
+            NewLocal { .. } => None,
+            UpdateAttempt { .. } => Some(Instant::now()),
```
Comment (jvff) [inline zebra-network/src/meta_addr.rs:531]: I think it's not an issue in practice, but I wanted to mention it just in case I'm missing something: would it make sense to store the time in the type when it is created, in case there's a large delay between the time it is created and the time the address book is updated?

File: zebra-network/src/meta_addr.rs [hunk 7]
```diff
@@ -259,18 +438,208 @@ impl MetaAddr {
...
+            NewAlternate { .. } => NeverAttemptedAlternate,
+            // local listeners get sanitized, so the exact value doesn't matter
+            NewLocal { .. } => NeverAttemptedGossiped,
+            UpdateAttempt { .. } => AttemptPending,
+            UpdateResponded { .. } => Responded,
+            UpdateFailed { .. } => Failed,
+        }
+    }
+
+    /// If this change can create a new `MetaAddr`, return that address.
```
Comment (jvff) [inline zebra-network/src/meta_addr.rs:574]:
```suggestion
    /// If this change can create a new [`MetaAddr`], return that address.
```

File: zebra-network/src/meta_addr.rs [hunk 8]
```diff
@@ -259,18 +438,208 @@ impl MetaAddr {
...
+                last_connection_state: self.peer_addr_state(),
+            }),
+            UpdateAttempt { .. } | UpdateResponded { .. } | UpdateFailed { .. } => None,
+        }
+    }
+
+    /// Apply this change to a previous `MetaAddr` from the address book,
+    /// producing a new or updated `MetaAddr`.
+    ///
+    /// If the change isn't valid for the `previous` address, returns `None`.
```
Comment (jvff) [inline zebra-network/src/meta_addr.rs:596]:
```suggestion
    /// Apply this change to a previous [`MetaAddr`] from the address book,
    /// producing a new or updated [`MetaAddr`].
    ///
    /// If the change isn't valid for the `previous` address, returns `None`.
```

File: zebra-network/src/meta_addr/arbitrary.rs [hunk 9]
```diff
@@ -1,10 +1,19 @@
...
+use std::net::SocketAddr;
 
-use super::{MetaAddr, PeerAddrState, PeerServices};
+use proptest::{arbitrary::any, collection::vec, prelude::*};
+
+use super::{MetaAddr, MetaAddrChange, PeerServices};
 
 use zebra_chain::serialization::{arbitrary::canonical_socket_addr, DateTime32};
 
+/// The largest number of random changes we want to apply to a MetaAddr
```
Comment (jvff) [inline zebra-network/src/meta_addr/arbitrary.rs:9]:
```suggestion
/// The largest number of random changes we want to apply to a [`MetaAddr`].
```

File: zebra-network/src/meta_addr/arbitrary.rs [hunk 10]
```diff
@@ -1,10 +1,19 @@
...
+///
+/// This should be at least twice the number of [`PeerAddrState`]s, so
+/// the tests can cover multiple transitions through every state.
+pub const MAX_ADDR_CHANGE: usize = 15;
+
 impl MetaAddr {
+    /// Returns a strategy which generates arbitrary gossiped `MetaAddr`s.
```
Comment (jvff) [inline zebra-network/src/meta_addr/arbitrary.rs]:
```suggestion
    /// Returns a strategy which generates arbitrary gossiped [`MetaAddr`]s.
```

**Review by jvff — COMMENTED** [review]
It's looking good! I added a few suggestions and questions.

**Comment by jvff** [comment]
I updated the PR description, changing `After we fix #1867` to `After #1867 is fixed`, because GitHub parsed the `fix #1867` and thought that this PR would close that issue once it is merged.

File: zebra-network/src/meta_addr.rs (hunk 2 above)
Comment (teor2345) [reply zebra-network/src/meta_addr.rs:182]: I think that's a good idea, but it's not required for the security fix. (And PRs #2275 and #2276 are likely to conflict with those changes.)

So I've opened ticket #2292 to keep a list of cleanup tasks.

File: zebra-network/src/meta_addr.rs (hunk 1 above)
Comment (teor2345) [reply zebra-network/src/meta_addr.rs:16]: This was probably an auto-insert by my editor, but it gets removed in #2275:
https://github.com/ZcashFoundation/zebra/pull/2275/files#diff-eb2e147a0d1ede36aea47b09193357df50c4eee92db53a603fc0f6d483813effR13

File: zebra-network/src/meta_addr.rs (hunk 7 above)
Comment (teor2345) [reply zebra-network/src/meta_addr.rs:574]: I'm concerned that these comment changes might cause a lot of conflicts with #2275 and later PRs, so I've added them to ticket #2292

File: zebra-network/src/meta_addr.rs (hunk 8 above)
Comment (teor2345) [reply zebra-network/src/meta_addr.rs:596]: Added to #2292

File: zebra-network/src/meta_addr/arbitrary.rs (hunk 10 above)
Comment (teor2345) [reply zebra-network/src/meta_addr/arbitrary.rs]: Added to #2292

File: zebra-network/src/meta_addr/arbitrary.rs (hunk 9 above)
Comment (teor2345) [reply zebra-network/src/meta_addr/arbitrary.rs:9]: Added to #2292

File: zebra-network/src/meta_addr.rs (hunk 4 above)
Comment (teor2345) [reply zebra-network/src/meta_addr.rs:338]: Fixed in 4d12cf6b in #2275

File: zebra-network/src/meta_addr.rs (hunk 3 above)
Comment (teor2345) [reply zebra-network/src/meta_addr.rs:323]: Fixed in 4d12cf6b in #2275

File: zebra-network/src/meta_addr.rs (hunk 5 above)
Comment (teor2345) [reply zebra-network/src/meta_addr.rs:347]: I did it to minimise changes in other modules, but it is really nice for ergonomics as well.

It effectively adds `None` to the argument values for the inner type.

It's fairly low-cost too, particularly for small functions like this. You get 2 monomorphised versions of the function: one for `Option<T>`, and one for `T` itself.

File: zebra-network/src/meta_addr.rs (hunk 6 above)
Comment (teor2345) [reply zebra-network/src/meta_addr.rs:531]: It's not an issue in practice. But the impacts are different for each time field, and some of the reasoning is subtle.

I've added detailed comments in ccdb6a81 in #2275.

I also added "update the attempt time before we start the handshake" to the list of requirements in the refactor ticket #1976. (Otherwise we could try the same peer twice if there are channel delays.)

As a side-effect, keeping times out of changes makes them smaller and more efficient. It also allows us to optimise timestamp collection by merging identical changes, see #2293.

**Comment by teor2345** [comment]
> I updated the PR description, changing `After we fix #1867` to `After #1867 is fixed`, because GitHub parsed the `fix #1867` and thought that this PR would close that issue once it is merged.

Thanks for catching that!

**Review by jvff — DISMISSED** [review]

**Comment by teor2345** [comment]
I merged the arbitrary and proptest changes from #2278.

All the changes were in test code, and they were minor. So I'll admin-merge once CI passes, which lets me make progress on #2275 without more conflicts.
