### PR TITLE
try to do deserialization of transaction in a rayon thread

### LINKED ISSUE #4787: Move network transaction deserialization to a dedicated blocking and CPU-heavy thread
## Motivation

Zebra's sync can be slow or fail, because transaction deserialization involves some CPU-heavy cryptography.

So we want to move transaction deserialization into a `rayon` CPU thread pool `scope`.

### API Reference

Blocking threads:
https://docs.rs/tokio/latest/tokio/task/fn.spawn_blocking.html

CPU-heavy threads:
https://docs.rs/rayon/latest/rayon/fn.scope_fifo.html

### Detailed Analysis

See https://github.com/ZcashFoundation/zebra/issues/4583#issuecomment-1186662862

### Designs

When `zebra-network` deserializes a block or transaction, move that work to the `rayon` thread pool.

Example code for `rayon` in `tokio` blocking threads:
https://github.com/ZcashFoundation/zebra/blob/81727d7df0ee57e6d4f2172c287e52e414c4e6a0/zebra-consensus/src/primitives/ed25519.rs#L121-L134

## Related Work

State deserialization is handled in #4788

### PR DESCRIPTION
**Pull request by oxarbitrage**
## Motivation

We want to add the deserialization of transactions and blocks in the zebra-network crate into the rayon pool. Resolves https://github.com/ZcashFoundation/zebra/issues/4787

## Solution

Implement deserialize transactions and blocks in a rayon thread.

### CODE REVIEW

**Comment by oxarbitrage** [comment]
This code fails compilation with the following:

```
oxarbitrage@oxarbitrage-Lenovo-ideapad-320S-14IKB:~/zebra/issue4787/zebra$ cargo test
   Compiling zebrad v1.0.0-beta.12 (/home/oxarbitrage/zebra/issue4787/zebra/zebrad)
   Compiling zebra-network v1.0.0-beta.12 (/home/oxarbitrage/zebra/issue4787/zebra/zebra-network)
error[E0597]: `body` does not live long enough
   --> zebra-network/src/protocol/external/codec.rs:413:51
    |
413 |                 let mut body_reader = Cursor::new(&body);
    |                                       ------------^^^^^-
    |                                       |           |
    |                                       |           borrowed value does not live long enough
    |                                       argument requires that `body` is borrowed for `'static`
...
465 |             }
    |             - `body` dropped here while still borrowed

error[E0597]: `body_reader` does not live long enough
   --> zebra-network/src/protocol/external/codec.rs:430:63
    |
430 |                     b"tx\0\0\0\0\0\0\0\0\0\0" => self.read_tx(&mut body_reader),
    |                                                  -------------^^^^^^^^^^^^^^^^-
    |                                                  |            |
    |                                                  |            borrowed value does not live long enough
    |                                                  argument requires that `body_reader` is borrowed for `'static`
...
465 |             }
    |             - `body_reader` dropped here while still borrowed

error[E0502]: cannot borrow `body_reader` as immutable because it is also borrowed as mutable
   --> zebra-network/src/protocol/external/codec.rs:451:22
    |
430 |                     b"tx\0\0\0\0\0\0\0\0\0\0" => self.read_tx(&mut body_reader),
    |                                                  ------------------------------
    |                                                  |            |
    |                                                  |            mutable borrow occurs here
    |                                                  argument requires that `body_reader` is borrowed for `'static`
...
451 |                 .map(|msg| {
    |                      ^^^^^ immutable borrow occurs here
...
455 |                     let extra_bytes = body.len() as u64 - body_reader.position();
    |                                                           ----------- second borrow occurs due to use of `body_reader` in closure

Some errors have detailed explanations: E0502, E0597.
For more information about an error, try `rustc --explain E0502`.
error: could not compile `zebra-network` due to 3 previous errors
warning: build failed, waiting for other jobs to finish...
error: could not compile `zebra-network` due to 3 previous errors
error: could not compile `zebra-network` due to 3 previous errors
oxarbitrage@oxarbitrage-Lenovo-ideapad-320S-14IKB:~/zebra/issue4787/zebra$ 
```

File: zebra-network/src/protocol/external/codec.rs [hunk 1]
```diff
@@ -674,6 +676,30 @@ impl Codec {
...
+        let mut result = None;
+
+        // Correctness: TBA
+        //
+        // Since we use `block_in_place()`, other futures running on the connection task will be blocked:
+        // https://docs.rs/tokio/latest/tokio/task/fn.block_in_place.html
+        //
+        // We can't use `spawn_blocking()` because:
+        // - The `reader` has a lifetime (but we could replace it with a `Vec` of message data)
+        // - There is no way to check the blocking task's future for panics
```
Comment (teor2345) [inline zebra-network/src/protocol/external/codec.rs:694]: It seems like we have to use `tokio::task::block_in_place()` here - I added a comment with some detailed reasons.

**Review by teor2345 — COMMENTED** [review]
I found a way to make it work, I pushed it to this PR in commit 47156967f855a57d54c6e778607de1379e0d9da8.

Some of the tests will need to be changed to use the multi-threaded `tokio` runtime, here's an example:
https://github.com/ZcashFoundation/zebra/blob/9be13a4fb73598d68905a8d06e79e7af022cdfcd/zebra-network/src/isolated/tor/tests/vectors.rs#L44-L45

File: zebra-network/src/protocol/external/codec.rs [hunk 2]
```diff
@@ -674,6 +676,52 @@ impl Codec {
...
+                s.spawn_fifo(|_s| result = Some(Transaction::zcash_deserialize(reader)))
+            })
+        });
+
+        result.expect("scope has already finished")
+    }
+
+    /// Given the reader, deserialize the block in the rayon thread pool.
+    #[allow(clippy::unwrap_in_result)]
+    fn deserialize_block_spawning<R: Read + std::marker::Send>(reader: R) -> Result<Block, Error> {
```
Comment (oxarbitrage) [inline zebra-network/src/protocol/external/codec.rs:706]: To avoid duplication we could have a single `deserialize_spawning()` and pass the functions as arguments. Arguments will be `Block::zcash_deserialize(reader)` or `Transaction::zcash_deserialize(reader)` however we can do that later.

**Review by teor2345 — APPROVED** [review]
Thanks, looks good!

**Comment by teor2345** [comment]
I admin-merged this PR because it is an urgent sync fix.
