### PR TITLE
remove unused mutability to defuse deadlock

### LINKED ISSUE #1001: Broken tracing endpoint
**Version**

Git `main`

**Platform**

All

**Description**

The tracing endpoint is broken and no longer allows reloading the tracing filter.  Reloading is processed here:

https://github.com/ZcashFoundation/zebra/blob/main/zebrad/src/components/tracing/endpoint.rs#L107-L112

Inserting tracing calls before and after reveals that that expression never resolves.  Shutting down the application causes it to be processed much later.  This suggests that the problem is that something is holding a lock on the application state for much longer than it should be.

TODO:
  - [ ] discover and fix the locking issue - maybe a git bisect would help?
  - [ ] enable the tracing_endpoint acceptance test by default

### PR DESCRIPTION
**Pull request by yaahc**
## Motivation

For a while now our tracing endpoint for configuring filters at runtime has been broken. The root cause of this was deadlock trying to access the state. The endpoint attempts to acquire an exclusive lock on the global application state, which is already locked by at least one reader for the entire duration of async execution.

## Solution

This PR changes the reload function to instead take a shared reference, allowing it to utilize a shared lock of the global state, rather than asking for an exclusive one. The underlying reload api already didn't require mutability, so the required change is extremely minimal.

The code in this pull request has:
  - [ ] Documentation Comments
  - [ ] Unit Tests and Property Tests

## Related Issues

closes https://github.com/ZcashFoundation/zebra/issues/1001

### CODE REVIEW

**Review by dconnolly — APPROVED** [review]

File: zebrad/tests/acceptance.rs [hunk 1]
```diff
@@ -789,7 +789,6 @@ async fn metrics_endpoint() -> Result<()> {
 }
 
 #[tokio::test]
-#[ignore]
```
Comment (teor2345) [inline zebrad/tests/acceptance.rs:792]: 👍

**Review by teor2345 — APPROVED** [review]
Looks good to me
