### PR TITLE
fix(commands): Require an argument name before the list of tracing filters when used without a subcommand

### LINKED ISSUE #7052: Supplying an incorrect subcommand name runs `zebrad start` instead
### What happened?

I expected to see this happen:

An error saying that the command does not exist.

Instead, this happened:

`zebrad` seemed to hang. (It was actually running, but without any logging.)

### What were you doing when the issue happened?

I ran:
```
zebrad download-params
```

The correct subcommand name is `zebrad download`.

### Zebra logs

`zebrad` does not log anything, because `download-params` is interpreted as a tracing filter.

If I run `zebrad zebrad=info`, I get info-level logs from zebrad only:
```
2023-06-22T23:53:12.410167Z  INFO zebrad::components::tracing::component: started tracing component filter="zebrad=info" TRACING_STATIC_MAX_LEVEL=LevelFilter::TRACE LOG_STATIC_MAX_LEVEL=Trace
2023-06-22T23:53:12.410185Z  INFO zebrad::application: Diagnostic Metadata:
version: 1.0.0
Zcash network: Mainnet
state version: 25
features: default,release_max_level_info
target triple: x86_64-unknown-linux-gnu
rust compiler: 1.72.0-nightly
rust release date: 2023-06-12
optimization level: 3
debug checks: true
2023-06-22T23:53:12.410197Z  INFO zebrad::application: loaded zebrad config config_path=Some("/home/dev/.config/zebrad.toml") config=ZebradConfig { consensus: Config { checkpoint_sync: true, debug_skip_parameter_preload: false }, metrics: Config { endpoint_addr: None }, network: Config { listen_addr: 0.0.0.0:8233, network: Mainnet, initial_mainnet_peers: {"dnsseed.z.cash:8233", "dnsseed.str4d.xyz:8233", "mainnet.seeder.zfnd.org:8233", "mainnet.is.yolo.money:8233"}, initial_testnet_peers: {"dnsseed.testnet.z.cash:18233", "testnet.seeder.zfnd.org:18233", "testnet.is.yolo.money:18233"}, cache_dir: IsEnabled(true), peerset_initial_target_size: 25, crawl_new_peer_interval: 61s }, state: Config { cache_dir: "/home/dev/.cache/zebra", ephemeral: false, debug_stop_at_height: None, delete_old_database: true }, tracing: Config { use_color: true, force_use_color: false, filter: Some("zebrad=info"), buffer_limit: 128000, endpoint_addr: None, flamegraph: None, log_file: None, use_journald: false }, sync: Config { download_concurrency_limit: 50, checkpoint_verify_concurrency_limit: 1000, full_verify_concurrency_limit: 20, parallel_cpu_threads: 0 }, mempool: Config { tx_cost_limit: 80000000, eviction_memory_time: 3600s, debug_enable_at_height: None }, rpc: Config { listen_addr: None, parallel_cpu_threads: 1, debug_force_finished_sync: false } }
2023-06-22T23:53:12.410240Z  INFO {net="Main"}: zebrad::application: initialized rayon thread pool for CPU-bound tasks num_threads=36
2023-06-22T23:53:12.411198Z  INFO {net="Main"}: zebrad::commands::start: Starting zebrad
2023-06-22T23:53:12.411227Z  INFO {net="Main"}: zebrad::commands::start: initializing node state
2023-06-22T23:53:12.416032Z  INFO {net="Main"}: zebrad::commands::start: opening database, this may take a few minutes
2023-06-22T23:53:12.430465Z  INFO {net="Main"}: zebrad::commands::start: initializing network
2023-06-22T23:53:17.537981Z  INFO {net="Main"}: zebrad::commands::start: initializing verifiers
2023-06-22T23:53:17.543117Z  INFO {net="Main"}: zebrad::commands::start: initializing syncer
2023-06-22T23:53:17.543133Z  INFO {net="Main"}: zebrad::commands::start: initializing mempool
2023-06-22T23:53:17.543140Z  INFO {net="Main"}: zebrad::commands::start: fully initializing inbound peer request handler
2023-06-22T23:53:17.543166Z  INFO {net="Main"}: zebrad::commands::start: spawned initial Zebra tasks
2023-06-22T23:53:17.543165Z  INFO {net="Main"}: zebrad::components::sync::gossip: initializing block gossip task
2023-06-22T23:53:17.543169Z  INFO {net="Main"}: zebrad::components::mempool::queue_checker: initializing mempool queue checker task
2023-06-22T23:53:17.543172Z  INFO {net="Main"}: zebrad::components::mempool::gossip: initializing transaction gossip task
2023-06-22T23:53:17.543183Z  INFO {net="Main"}: zebrad::components::sync::end_of_support: Starting end of support task
2023-06-22T23:53:17.543186Z  INFO {net="Main"}: zebrad::components::mempool::crawler: initializing mempool crawler task
2023-06-22T23:53:17.543479Z  INFO {net="Main"}:sync:try_to_sync: zebrad::components::sync: starting sync, obtaining new tips state_tip=Some(Height(3600))
2023-06-22T23:53:17.548278Z  INFO {net="Main"}: zebrad::components::sync::progress: estimated progress to chain tip sync_percent=0.168% current_height=Height(3600) network_upgrade=BeforeOverwinter remaining_sync_blocks=2141194 time_since_last_state_block=0s
^C2023-06-22T23:53:18.026227Z  INFO {net="Main"}:sig{kind=SignalKind(2) name="SIGINT"}: zebrad::signal: received SIGINT, starting shutdown
2023-06-22T23:53:18.026261Z  INFO {net="Main"}: zebrad::components::tokio: waiting for async tokio tasks to shut down TOKIO_SHUTDOWN_TIMEOUT=20s
2023-06-22T23:53:18.480457Z  INFO {net="Main"}: zebrad::components::tokio: shutting down Zebra
2023-06-22T23:53:18.480477Z  INFO {net="Main"}: zebrad::commands::start: stopping zebrad
```

### Zebra Version

zebrad 1.0.0

### Which operating systems does the issue happen on?

- [X] Linux
- [ ] macOS
- [ ] Windows
- [ ] Other OS

### OS details

Linux machine-name 5.15.85 #1-NixOS SMP Wed Dec 21 16:36:38 UTC 2022 x86_64 GNU/Linux

### Additional information

The underlying problem is that a `zebrad` command with a tracing filter argument (or any other unlabelled argument) will accept any number of arguments, including invalid arguments.

We could fix this bug by:
- not accepting tracing filters on the command-line unless the user explicitly puts `start` on the command-line

(This is technically a breaking change, but there is an easy workaround: just say "start".)

Or making a breaking change to argument processing:
- [requiring an argument name](https://docs.rs/clap/latest/clap/_derive/_tutorial/index.html#options) before the list of tracing filters

Validating the arguments supplied as tracing filters won't help, because almost any string is valid:
https://docs.rs/tracing-subscriber/0.3.17/tracing_subscriber/filter/struct.EnvFilter.html#usage-notes

This is where we'd make the changes (and in every command that accepts a list of free arguments):
https://github.com/ZcashFoundation/zebra/blob/31bc46bb2a736110d215de2fac5cdfd79bcbd058/zebrad/src/commands/start.rs#L101-L102

### PR DESCRIPTION
**Pull request by arya2**
## Motivation

Supplying an incorrect subcommand name should not run start.

This PR does not affect how tracing filters are parsed where the user provided the start subcommand.

Closes #7052

## Solution

- Adds `long` to `filters` field on `EntryPoint` (this field is ignored by the tracing component)
- Appends start to the end when no subcommand is provided (instead of before the first filter)
- Appends filters arg after the default subcommand

Related: I tried [`EnvFilter::try_new().expect()`](https://docs.rs/tracing-subscriber/0.3.17/tracing_subscriber/filter/struct.EnvFilter.html#method.try_new), but the format was too permissive, (this was noted in the issue as well.)

## Review

Anyone can review.

### Reviewer Checklist

  - [ ] Will the PR name make sense to users?
    - [ ] Does it need extra CHANGELOG info? (new features, breaking changes, large changes)
  - [ ] Are the PR labels correct?
  - [ ] Does the code do what the ticket and PR says?
    - [ ] Does it change concurrent code, unsafe code, or consensus rules?
  - [ ] How do you know it works? Does it have tests?

### CODE REVIEW

File: zebrad/src/commands/entry_point.rs [hunk 1]
```diff
@@ -63,28 +61,22 @@ impl EntryPoint {
...
-            for (idx, arg) in args.iter().enumerate() {
-                num_top_level_args = match arg.to_str() {
-                    Some("--verbose" | "-v" | "--version" | "-V" | "--help") => idx + 1,
-                    Some("--config" | "-c") => idx + 2,
-                    _ => num_top_level_args,
-                }
+        if entry_point.should_add_default_subcommand() {
+            args.push(EntryPoint::default_cmd_as_str().into());
+            for filter in entry_point.filters {
+                args.push(filter.into())
```
Comment (arya2) [inline zebrad/src/commands/entry_point.rs:79]: It duplicates the top-level filters args, but will parse and ignore the first set.

**Comment by teor2345** [comment]
This looks like a breaking change, does it need to wait for the 1.1.0 release?

(I don't mind either way, just checking as the person tagging the release.)

**Comment by arya2** [comment]
> This looks like a breaking change, does it need to wait for the 1.1.0 release?

I'd be okay with a patch update since it's a very small breaking change.

**Comment by teor2345** [comment]
> > This looks like a breaking change, does it need to wait for the 1.1.0 release?
> 
> I'd be okay with it okay in a patch update since it's a very small breaking change.

Seems ok, just as long as it has something in the changelog.

File: zebrad/src/commands/tests.rs [hunk 2]
```diff
@@ -16,7 +16,7 @@ fn args_with_subcommand_pass_through() {
         (true, false, false, vec!["zebrad", "--help"]),
         (false, true, false, vec!["zebrad", "start"]),
         (false, true, true, vec!["zebrad", "-v", "start"]),
-        (false, true, false, vec!["zebrad", "warn"]),
+        (false, true, false, vec!["zebrad", "--filters", "warn"]),
```
Comment (teor2345) [inline zebrad/src/commands/tests.rs:19]: Can you also add a test case for detecting an invalid subcommand?
I'd also like to check that `zebrad start debug` works without `--filters`, like it does in v1.0.1.

File: zebrad/src/commands/entry_point.rs [hunk 3]
```diff
@@ -63,28 +61,23 @@ impl EntryPoint {
...
-            // try_parse_from currently produces an error if the first argument is not the binary name,
-            let mut num_top_level_args = 1;
-
-            // update last_top_level_arg_idx to the number of top-level args
-            for (idx, arg) in args.iter().enumerate() {
-                num_top_level_args = match arg.to_str() {
-                    Some("--verbose" | "-v" | "--version" | "-V" | "--help") => idx + 1,
-                    Some("--config" | "-c") => idx + 2,
-                    _ => num_top_level_args,
-                }
```
Comment (teor2345) [inline zebrad/src/commands/entry_point.rs:83]: Thanks for simplifying this code!

File: CHANGELOG.md [hunk 4]
```diff
@@ -6,6 +6,12 @@ The format is based on [Keep a Changelog](https://keepachangelog.com/en/1.0.0/),
 and this project adheres to [Semantic Versioning](https://semver.org).
 
 
+## [Zebra 1.0.1](https://github.com/ZcashFoundation/zebra/releases/tag/v1.0.1) - 2023-XX-XX
+
+### Breaking Changes
+
+- Zebra now requires an argument name before the list of tracing filters when running `start` without an explicit subcommand.
```
Comment (teor2345) [inline CHANGELOG.md]: It might help to describe the impact of this change on most users, then provide an example of the workaround a few users might need.

```suggestion
- Zebra now detects subcommand name typos on the command-line. If you want to give Zebra a list of tracing filters, use `zebrad start --filters debug,...` ([#7056](https://github.com/ZcashFoundation/zebra/pull/7056))
```

**Review by teor2345 — DISMISSED** [review]
Looks good, some optional suggestions about the changelog and testing.

File: zebrad/src/commands/tests.rs (hunk 2 above)
Comment (arya2) [inline zebrad/src/commands/tests.rs:19]:
```suggestion
        (false, true, false, vec!["zebrad", "--filters", "warn"]),
        (true, false, false, vec!["zebrad", "warn"]),
```

Comment (arya2) [reply zebrad/src/commands/tests.rs:19]: > https://github.com/ZcashFoundation/zebra/pull/7056/commits/26a7295b53ef8f3a20764dbb83de7d4e0999f52b

Added in https://github.com/ZcashFoundation/zebra/pull/7056/commits/26a7295b53ef8f3a20764dbb83de7d4e0999f52b.

> I'd also like to check that zebrad start debug works without --filters, like it does in v1.0.1.

This should be checked by the second-last test case, `zebrad start warn`.

File: CHANGELOG.md (hunk 4 above)
Comment (arya2) [reply CHANGELOG.md]: Thank you!

**Review by teor2345 — APPROVED** [review]
Thanks for this fix!
