### PR TITLE
Ignore unexpected block responses to fix error cascade when synchronizing blocks

### LINKED ISSUE #3352: Fix intermittent syncing
## Motivation

Currently, the sync stops for a couple minutes every ~5 minutes, which makes syncing very slow.

Identify the cause and fix it. We're currently discussing it in https://discord.com/channels/676527656170160146/920784737872773122

The issue seems to have appeared in https://github.com/ZcashFoundation/zebra/pull/3120

### PR DESCRIPTION
**Pull request by jvff**
## Motivation

Zebra is having some block synchronization issues, which seems to be caused by the block synchronizer restarting every few minutes.

After investigating the issue, the cause was found to be that the connection to a remote peer become "unsynchronized". What happened was:

1. Local peer requests a block to the remote peer
2. The request is cancelled (this is normal, it can happen due to a timeout or due to a hedge request finishing first)
3. A second request is sent to the remote peer
4. The remote peer responds to the first request
5. The local peer thinks it's a response to the second request, and thinks the remote peer sent an incorrect block, so it returns an error
6. The local peer sends a third block request to the remote peer
7. The remote peer responds to the second request
8. The local peer thinks it's a response to the third request, ...

## Solution

Ignore responses with the incorrect block hash. That way there's a chance that a response received later has the correct block hash. If the remote peer did send out the incorrect block, the request will timeout anyway.

This fixes #3352.

The changes are simple, but I had to refactor the tests to be able to write a test case to reproduce the scenario. The test became a property test, and should now help us catch a regression to the error cascade behavior in the future.

## Review

@oxarbitrage can review this.

### Reviewer Checklist

  - [ ] Code implements Specs and Designs
  - [ ] Tests for Expected Behaviour
  - [ ] Tests for Errors

### CODE REVIEW

File: zebra-network/src/protocol/internal/response.rs [hunk 1]
```diff
@@ -11,7 +11,7 @@ use std::{fmt, sync::Arc};
 use proptest_derive::Arbitrary;
 
 /// A response to a network request, represented in internal format.
-#[derive(Clone, Debug)]
+#[derive(Clone, Debug, Eq, PartialEq)]
```
Comment (jvff) [inline zebra-network/src/protocol/internal/response.rs:14]: This was added so that the property test can do `prop_assert_eq!(response, Response::...)`.

File: zebra-network/src/protocol/external/codec.rs [hunk 2]
```diff
@@ -35,12 +35,14 @@ use super::{
 const HEADER_LEN: usize = 24usize;
 
 /// A codec which produces Bitcoin messages from byte streams and vice versa.
+#[derive(Clone)]
```
Comment (jvff) [inline zebra-network/src/protocol/external/codec.rs]: These `Clone` derivations were added so that the `new_test_connection` function can clone the `Codec` in order to create separate `FrameRead` and `FrameWrite` types. Both of them require a `Codec` instance, one to decode `Message`s and the other to write `Message`s.

File: zebra-network/src/peer/connection/tests.rs [hunk 3]
```diff
@@ -1,3 +1,64 @@
...
+};
+
+mod prop;
 mod vectors;
+
+/// Creates a new [`Connection`] instance for testing.
+fn new_test_connection<A>() -> (
+    Connection<MockService<Request, Response, A>, FramedWrite<DuplexStream, Codec>>,
+    mpsc::Sender<ClientRequest>,
+    MockService<Request, Response, A>,
```
Comment (jvff) [inline zebra-network/src/peer/connection/tests.rs:29]: The `MockService` has a generic `A` assertion type parameter. This is different for property tests and unit tests.

The `vector` and `prop` modules have `new_test_connection` functions that specify which assertion type should be used.

File: zebra-test/src/mock_service.rs [hunk 4]
```diff
@@ -256,7 +256,7 @@ impl MockServiceBuilder {
     /// Note that this is used by both [`Self::for_prop_tests`] and [`Self::for_unit_tests`], the
     /// only difference being the `Assertion` generic type parameter, which Rust infers
     /// automatically.
-    fn finish<Request, Response, Assertion, Error>(
+    pub fn finish<Request, Response, Assertion, Error>(
```
Comment (jvff) [inline zebra-test/src/mock_service.rs:259]: This was made public so that the generic `new_test_connection` function could be generic and support both property tests and unit tests.

**Comment by dconnolly** [comment]
Some graphs from running this fix:

image

**Comment by jvff** [comment]
> Some graphs from running this fix:

Looks nice :slightly_smiling_face:  There's still the large plateau, which I think is around 106k blocks. I believe that's caused by having too many large blocks and ending up waiting on downloads from a few slow peers. I'll try take a look still this week to see if there's something we can do to improve that :+1:

File: zebra-network/src/protocol/external/codec.rs (hunk 2 above)
Comment (jvff) [reply zebra-network/src/protocol/external/codec.rs]: I'm resolving this because I managed to remove it. I replaced the `Framed` channels with a single `mpsc` unbounded channel, which should also make the tests a little faster because it avoids serialization and deserialization of messages.

**Review by dconnolly — APPROVED** [review]
I've synced nearly the whole chain in about 9 hours, far better than we were doing before, with the checkpointed blocks screaming very fast and then slowing down after checkpointing finishes. Awesome job!

image
