### PR TITLE
fix(rpc): `z_gettreestate` optional fields

### LINKED ISSUE #9445: `z_gettreestate` incorrectly assumes presence of `finalState`
As noted in the original issue (#3156), `finalState` is an optional field, only returned if available. However, `zebra-rpc` denotes it as always present:
https://github.com/ZcashFoundation/zebra/blob/6e039c26c312f97a3d26ec1b073749238a481dc6/zebra-rpc/src/methods/trees.rs#L157-L169

This didn't cause issues when `zebra-rpc` was solely a server-side crate. However, Zaino now uses its types for client-side parsing, which means the bug is now present in Zaino and prevents it from correctly communicating with a `zcashd` instance (which omits `finalState` for example in the `orchard` section for blocks prior to NU5 activation).

We don't necessarily need to alter Zebra's server behaviour; one can squint and pretend that the Orchard tree was retroactively "always empty" from Zcash launch in 2016 through to NU5 activation. But the actual RPC method has the field documented as optional, and if `zebra-rpc` is intended to be used as a client library, it needs to implement the documented API rather than Zebra's desired subset (at least for the duration of 2025 while people will be using Zaino with `zcashd` alongside Zebra).

### PR DESCRIPTION
**Pull request by oxarbitrage**
## Motivation

Fix https://github.com/ZcashFoundation/zebra/issues/9445

## Solution

- Make the optional fields like zcashd

### Tests

We have a few snapshots, i also did a small amount of tests between zcashd and zebrad.

### PR Checklist

- [ ] The PR name is suitable for the release notes.
- [ ] The solution is tested.
- [ ] The documentation is up to date.
- [ ] The PR has a priority label.
- [ ] If the PR shouldn't be in the release notes, it has the
      `C-exclude-from-changelog` label.

### CODE REVIEW

**Comment by oxarbitrage** [comment]
Manual tests:

zcashd at height 1:

```
$ curl --silent --user __cookie__ --data-binary '{"jsonrpc": "1.0", "id":"curltest", "method": "z_gettreestate", "params": ["1"] }' -H 'Content-type: application/json' http://127.0.0.1:8232/ | jq
Enter host password for user '__cookie__':
{
  "result": {
    "hash": "0007bc227e1c57a4a70e237cad00e7b7ce565155ab49166bc57397a26d339283",
    "height": 1,
    "time": 1477671596,
    "sprout": {
      "commitments": {
        "finalRoot": "59d2cde5e65c1414c32ba54f0fe4bdb3d67618125286e6a191317917c812c6d7",
        "finalState": "000000"
      }
    },
    "sapling": {
      "commitments": {
        "finalRoot": "0000000000000000000000000000000000000000000000000000000000000000"
      }
    },
    "orchard": {
      "commitments": {
        "finalRoot": "0000000000000000000000000000000000000000000000000000000000000000"
      }
    }
  },
  "error": null,
  "id": "curltest"
}
$
```

zebrad at height 1::

```
$ curl --silent --user __cookie__ --data-binary '{"jsonrpc": "1.0", "id":"curltest", "method": "z_gettreestate", "params": ["1"] }' -H 'Content-type: application/json' http://127.0.0.1:8232/ | jq
Enter host password for user '__cookie__':
{
  "jsonrpc": "1.0",
  "id": "curltest",
  "result": {
    "hash": "0007bc227e1c57a4a70e237cad00e7b7ce565155ab49166bc57397a26d339283",
    "height": 1,
    "orchard": {
      "commitments": {}
    },
    "sapling": {
      "commitments": {}
    },
    "time": 1477671596
  },
  "error": null
}
$ 
```

zcashd at height 500_000:

```
$ curl --silent --user __cookie__ --data-binary '{"jsonrpc": "1.0", "id":"curltest", "method": "z_gettreestate", "params": ["500000"] }' -H 'Content-type: application/json' http://127.0.0.1:8232/ | jq
Enter host password for user '__cookie__':
{
  "result": {
    "hash": "0000000001130a4e3a851bf4be43214f796f6d304953ac25236227585f448927",
    "height": 500000,
    "time": 1552955406,
    "sprout": {
      "commitments": {
        "finalRoot": "924917c62925002a73d6f312b9fb60b4260689839475860b8730f3ba4cddbcd5",
        "finalState": "01ffa0622e5b34317e5458e54f2f6cf9ec6c650bb1af1a74a4c8a55dd48a9c2cfc01f62a052bf433cc7c004c88eaf2d7f4cca6321d3ad3d95ff75d5a9ffd56ff495814000163d9b28541ea0b9d3ec281fc7ff2c73ad0004cf1e1812e1437e437c48665ac6c000001f13a821f3c635aac51e38ed136ce4aef4bf827b18b2b09a9f344d0b97f0efb2d00019d77f6184b9bf0c073daf9778e0b3cf0c4aa8b57f1ead12aa8c04e04603de7c60001b9a684ebeb26e4b977c1ba67b441d1298169569c59f8c80c3494535f90aa78a0012e5a80ff32f61f52f876d8307fb1f394ad9213fa45eb05d9af93b644559d9fc0013cb37e72ec1c514ada3dbbc86208c4ec7fc7c9aa127c321a5ad602fba86b1ef201e7e1e6a4d8f340828c8bea8b2f5bc78ed2641e8b5db07cd4b53a956af4d6fca601bfe901322f0ef29e838a4b6aeab38709065cfdd1ada676aebbfaa6618fbad29a0000000001c14d7b1dfae9c25c284218d74c43621b795246a5fb3c238c2ca9d7f91d5aa86000011b1fc3241793d87854115ec7190ea06c64b76faa971c77ccc6316ec716f90f77"
      }
    },
    "sapling": {
      "commitments": {
        "finalRoot": "21facefaa0e2ba2851a5316d6ac9b119ada1ab57c5e24a089781ad244f38c938",
        "finalState": "01bd95b1203680c0f6377f2719737ca38e1fb82e8a99fd728d6a4a11e15c5dce19000e01bca58aff7016f2e9481f339addd57ad28b3a870baf575440a84194a3314f665e000198db3688339bc083537b54ee34a5081aba45bbc73502328f81aaab2a0967235b00012b697a92270c6741333ae149da5217f972f0cd7718ef32439a86f01ec54b050d0128c87a43e47bbb15ebccb15ca373bc16dad277fb6eb7f1354923c5e090ac815d01a459fa0009223967f3f42a6482ebda5b53c3f379b6179e539896b3b01da27f6501e4977ec1f780d89f6f7cdce494a007cd561af54f41d28cb49cd09a51d70c081101e09fff8dfbfab281e3923e5d057947dc69a2af17178230bef3f10f3ec90ee73e01b1847e1281565f2408b844553aecdae90e88b1ee06e41e3715a9a6c7333caf400001633a706b172940cb57d66e488256cd852468e11133a5bcf3f7175e83257afd1c0120dbe8afbcd899b7e930d198c5916ea8a53f4c6b1ce8dc1e0826c5df5011424c0177cb7c8bb2599130d641ec8d8f32689051a57cbcac583671c45a95fd00180639"
      }
    },
    "orchard": {
      "commitments": {
        "finalRoot": "0000000000000000000000000000000000000000000000000000000000000000"
      }
    }
  },
  "error": null,
  "id": "curltest"
}
$ 
```

zebrad at height 500_000:

```
$ curl --silent --user __cookie__ --data-binary '{"jsonrpc": "1.0", "id":"curltest", "method": "z_gettreestate", "params": ["500000"] }' -H 'Content-type: application/json' http://127.0.0.1:8232/ | jq
Enter host password for user '__cookie__':
{
  "jsonrpc": "1.0",
  "id": "curltest",
  "result": {
    "hash": "0000000001130a4e3a851bf4be43214f796f6d304953ac25236227585f448927",
    "height": 500000,
    "orchard": {
      "commitments": {}
    },
    "sapling": {
      "commitments": {
        "finalState": "01bd95b1203680c0f6377f2719737ca38e1fb82e8a99fd728d6a4a11e15c5dce19001f01bca58aff7016f2e9481f339addd57ad28b3a870baf575440a84194a3314f665e000198db3688339bc083537b54ee34a5081aba45bbc73502328f81aaab2a0967235b00012b697a92270c6741333ae149da5217f972f0cd7718ef32439a86f01ec54b050d0128c87a43e47bbb15ebccb15ca373bc16dad277fb6eb7f1354923c5e090ac815d01a459fa0009223967f3f42a6482ebda5b53c3f379b6179e539896b3b01da27f6501e4977ec1f780d89f6f7cdce494a007cd561af54f41d28cb49cd09a51d70c081101e09fff8dfbfab281e3923e5d057947dc69a2af17178230bef3f10f3ec90ee73e01b1847e1281565f2408b844553aecdae90e88b1ee06e41e3715a9a6c7333caf400001633a706b172940cb57d66e488256cd852468e11133a5bcf3f7175e83257afd1c0120dbe8afbcd899b7e930d198c5916ea8a53f4c6b1ce8dc1e0826c5df5011424c0177cb7c8bb2599130d641ec8d8f32689051a57cbcac583671c45a95fd001806390000000000000000000000000000000000"
      }
    },
    "time": 1552955406
  },
  "error": null
}
$ 
```

zcashd at height 2_000_000:

```
$ curl --silent --user __cookie__ --data-binary '{"jsonrpc": "1.0", "id":"curltest", "method": "z_gettreestate", "params": ["2000000"] }' -H 'Content-type: application/json' http://127.0.0.1:8232/ | jq
Enter host password for user '__cookie__':
{
  "result": {
    "hash": "00000000010accaf2f87934765dc2e0bf4823a2b1ae2c1395b334acfce52ad68",
    "height": 2000000,
    "time": 1677602242,
    "sprout": {
      "commitments": {
        "finalRoot": "468d8b07c22e54909112c319bcedcf29e9db0e929ddf236de80e02e246a4ad68",
        "finalState": "019c187b09247a32bd4ab21d0030572db88533d2a98607f7e1472942b0b9dfadb6017e2de971541bfd698ed28f573f2718f828c8342b0af27fca1801dcfd81d3345f14014561507d01f4cbef6a0f90991bc4c50aa4139a04ee1fb073d3ca7fe5486b4cda0001c12baa078b030ddfedfe7f4b2d993ec752036737cd889762b6468aa5b2b9c0810127a138125fcbbafea45a803080205abc03a707db72b534feb822a0622cfe283201cbddae23632fe1acae85382f27579a2962d985894a007aafb96ced64e79c54e7012f36395e813ac7adadd840ba80c1c1c32429efa2a3d9ef4f639c51a8fad249c40158e85230d09c2c4dfe18a330da25e35bfb4383353df28ba5ff568b1648904a4201f779c93f8bae99232c50676ee35b5ee0b16bb291b3f0e3ebea59b195c724f25a0118a42f7941cd9d5f1459d0ae25ebf4528402d7db7b3e6f56aaaf1d8b49a8ca3500000196295a1e8d018c1c59f098e69350c7a206b850c828710fbaeb86d3ef72da3bb6000001806212ff57170f6904d462d24bc5df6112269a0b65defffbd4b78ff9a7859b9d0183a03915c566ab12ba59b130bab08a25b932ce204bf1774fc9e9267e5130f19101465dbb7f98de7f19e22f37c537660e9447fc27e1839238dc75548b047c41d1be01c14d7b1dfae9c25c284218d74c43621b795246a5fb3c238c2ca9d7f91d5aa86000011b1fc3241793d87854115ec7190ea06c64b76faa971c77ccc6316ec716f90f77"
      }
    },
    "sapling": {
      "commitments": {
        "finalRoot": "23cf0bd8cb75cf221913a8960b9803a89c3486577fe3a86e5916a3ba5fb08e4b",
        "finalState": "014fc4a4b4d4a845524e6aa4862f5e2b85c287690e91549a757f02d8965ec7e114001a01c44c2a47aebfce6b4107cf42696cd53f95a3a1b0c2f057946477dbdac6ac990c01808aeb344006041d1eecebaeeefad330ccda2724981acb4188e78fded787d1170147b91a80c478a0d57378a2d14764e14156cd362c278fb38d8d4ac7ecd70dbc2a0001e8dca28dd4f7c0e042487d7c757d36989acb6ea8fe3c0ecd3939bcc52d12f947013f92f5f50f9f61bd6c2f679568ecd355884517b3059b162d8f2ac7511d0bb301000001a0da06f0f35326e480e0dfe97ab843093891cf2ebd6f37056ebdbd101a18666e0186b6566bed5f6772a8f137ffd2f893119a7eac46d1964298914a9bae76429142010b420ffb46b26642b47b5627d5e7d922d7a1201a85ddde8751546754a63a8c390137ea7b9284f93d58bf1af22b804001e9abee5879e6b782ff34bb8f64d0f9c01b00000001c1cffa22d637cb194102a1b02a57d2b47c67f54094f6773a38b2e53d3becb45f01c9a38e0a8812c9b32afdf24d5c49910813edd0216141c67afa6706a90a1c7c6a014eccd7817f743da07b04d009162821e21f9ec19ad80f6f84ba69d7a6514e4f2f000000011619f99023a69bb647eab2d2aa1a73c3673c74bb033c3c4930eacda19e6fd93b0000000160272b134ca494b602137d89e528c751c06d3ef4a87a45f33af343c15060cc1e"
      }
    },
    "orchard": {
      "commitments": {
        "finalRoot": "1300a17af41e48e376842a9472fa7460def59791dd24d3ca1c8cbff4fe0d1b14",
        "finalState": "01cb46ca4cf0f0ed106de4d60b221673f658ff149ad26c6d396320e69fa2095f3901df70743a88355f9d056a98cd5e23ed0e0adccb72c0db88e7d931922e0b27c2081f01a4fe69f278213617b940616243ba9a24a4c0551f37211cadfdb2516d9d5fde1001d90fe822ab9faa194c18aa7e72239187c6ec25b2a8b9aa842f353840144956360152f96784e7b5811c0357acc5c8c9227e58f66c31b7e8d7bfcaa468a109223c320130340039618259fe389b7563cfad75eb7d5860d7e94bd424813e49b0800e8a1000000000015389012bccf5921c2d7bcefc8ec0b3db13bbe56ba941166cbbeb0622d89f0d2001a5145ac56c471b7d3f8d9289c17b4f0a4ecb3d47f49e41e8c9bd8751188a9d07014c6a1e0e9c77653e09e2e8197520aea825b7f98aa597ad39766ba53d3fc3123601cb7dacdcb84c3b29b7180981cf7112132ab97f3db442068f1b2f9369dc512b3e01f9badafc448fc46dda2132d275d26d36f3b5162626e6d20615255ce99ade1c3100010ff6f43cee8327100ec80be1e4bc6f7989d1e7e88c982401b3747784959cd114014ed1866378b18ead5507467e097c989adcab54e20ed592fc18d1a8a49c4b6126000001e21bfa403108d3dd3bd719beb7c0e2b27c2c927a9bc19810f827c13c12a7751700000194be91dcf7396b61c164434ee2d40b4f641da3a82f2b9a3e9651e1e897bc1d3d000001e2bca6a8d987d668defba89dc082196a922634ed88e065c669e526bb8815ee1b000000000000"
      }
    }
  },
  "error": null,
  "id": "curltest"
}
```

zebrad at height 2_000_000::

```
$ curl --silent --user __cookie__ --data-binary '{"jsonrpc": "1.0", "id":"curltest", "method": "z_gettreestate", "params": ["2000000"] }' -H 'Content-type: application/json' http://127.0.0.1:8232/ | jq
Enter host password for user '__cookie__':
{
  "jsonrpc": "1.0",
  "id": "curltest",
  "result": {
    "hash": "00000000010accaf2f87934765dc2e0bf4823a2b1ae2c1395b334acfce52ad68",
    "height": 2000000,
    "orchard": {
      "commitments": {
        "finalState": "01cb46ca4cf0f0ed106de4d60b221673f658ff149ad26c6d396320e69fa2095f3901df70743a88355f9d056a98cd5e23ed0e0adccb72c0db88e7d931922e0b27c2081f01a4fe69f278213617b940616243ba9a24a4c0551f37211cadfdb2516d9d5fde1001d90fe822ab9faa194c18aa7e72239187c6ec25b2a8b9aa842f353840144956360152f96784e7b5811c0357acc5c8c9227e58f66c31b7e8d7bfcaa468a109223c320130340039618259fe389b7563cfad75eb7d5860d7e94bd424813e49b0800e8a1000000000015389012bccf5921c2d7bcefc8ec0b3db13bbe56ba941166cbbeb0622d89f0d2001a5145ac56c471b7d3f8d9289c17b4f0a4ecb3d47f49e41e8c9bd8751188a9d07014c6a1e0e9c77653e09e2e8197520aea825b7f98aa597ad39766ba53d3fc3123601cb7dacdcb84c3b29b7180981cf7112132ab97f3db442068f1b2f9369dc512b3e01f9badafc448fc46dda2132d275d26d36f3b5162626e6d20615255ce99ade1c3100010ff6f43cee8327100ec80be1e4bc6f7989d1e7e88c982401b3747784959cd114014ed1866378b18ead5507467e097c989adcab54e20ed592fc18d1a8a49c4b6126000001e21bfa403108d3dd3bd719beb7c0e2b27c2c927a9bc19810f827c13c12a7751700000194be91dcf7396b61c164434ee2d40b4f641da3a82f2b9a3e9651e1e897bc1d3d000001e2bca6a8d987d668defba89dc082196a922634ed88e065c669e526bb8815ee1b000000000000"
      }
    },
    "sapling": {
      "commitments": {
        "finalState": "014fc4a4b4d4a845524e6aa4862f5e2b85c287690e91549a757f02d8965ec7e114001f01c44c2a47aebfce6b4107cf42696cd53f95a3a1b0c2f057946477dbdac6ac990c01808aeb344006041d1eecebaeeefad330ccda2724981acb4188e78fded787d1170147b91a80c478a0d57378a2d14764e14156cd362c278fb38d8d4ac7ecd70dbc2a0001e8dca28dd4f7c0e042487d7c757d36989acb6ea8fe3c0ecd3939bcc52d12f947013f92f5f50f9f61bd6c2f679568ecd355884517b3059b162d8f2ac7511d0bb301000001a0da06f0f35326e480e0dfe97ab843093891cf2ebd6f37056ebdbd101a18666e0186b6566bed5f6772a8f137ffd2f893119a7eac46d1964298914a9bae76429142010b420ffb46b26642b47b5627d5e7d922d7a1201a85ddde8751546754a63a8c390137ea7b9284f93d58bf1af22b804001e9abee5879e6b782ff34bb8f64d0f9c01b00000001c1cffa22d637cb194102a1b02a57d2b47c67f54094f6773a38b2e53d3becb45f01c9a38e0a8812c9b32afdf24d5c49910813edd0216141c67afa6706a90a1c7c6a014eccd7817f743da07b04d009162821e21f9ec19ad80f6f84ba69d7a6514e4f2f000000011619f99023a69bb647eab2d2aa1a73c3673c74bb033c3c4930eacda19e6fd93b0000000160272b134ca494b602137d89e528c751c06d3ef4a87a45f33af343c15060cc1e0000000000"
      }
    },
    "time": 1677602242
  },
  "error": null
}
$ 

```

File: zebra-rpc/src/methods/trees.rs [hunk 1]
```diff
@@ -154,28 +154,38 @@ impl<Tree: AsRef<[u8]>> Treestate<Tree> {
...
-    pub fn new(final_state: Tree) -> Self {
+    /// Returns a new instance of ['Commitments'] with optional `final_state`.
+    pub fn new(final_state: Option<Tree>) -> Self {
         Commitments { final_state }
     }
 
-    /// Returns a reference to the final_state.
-    pub fn inner(&self) -> &Tree {
+    /// Returns a reference to the optional `final_state`.
+    pub fn inner(&self) -> &Option<Tree> {
```
Comment (oxarbitrage) [inline zebra-rpc/src/methods/trees.rs:188]: This is a breaking change for Zaino (@idky137). We can avoid changing the signature in `Commitments::new` but probably not in `Commitments::inner`.

Comment (idky137) [reply zebra-rpc/src/methods/trees.rs:188]: not a problem, I was adding a workaround in zaino but its cleaner to change it here. 

Thanks for referencing me, I will open a PR in zaino for this change.

**Comment by str4d** [comment]
I've confirmed that this change gets me past the error I was running into with Zaino. I've not reviewed this PR beyond that.

**Review by arya2 — APPROVED** [review]

**Comment by mpguerra** [comment]
@mergifyio requeue

**Comment by str4d** [comment]
Looks like CI failure in all three cases is "Error: The operation was canceled". What needs to happen to get past this and merge?

**Comment by oxarbitrage** [comment]
> Looks like CI failure in all three cases is "Error: The operation was canceled". What needs to happen to get past this and merge?

We’re seeing failures in our CI apparently due to the Lightwalletd integration tests (I am not into the details). The team is treating this as a high-priority blocker as no approved PRs can merge until it’s resolved.

Because today is a holiday for many of our staff, capacity is limited, but we expect a fix by tomorrow or, at the latest, early next week. Sorry for the inconvenience and thanks for your patience.

**Comment by conradoplg** [comment]
@Mergifyio rebase
