### PR TITLE
Respond to getblockchaininfo with genesis block when empty state

### LINKED ISSUE #8939: bug: Respond to getblockchaininfo requests when the state is empty
[Lightwalletd test failed when calling `getblockchaininfo`](https://github.com/ZcashFoundation/zebra/actions/runs/11357961703/job/31591878366#step:4:622) in https://github.com/ZcashFoundation/zebra/pull/8857.

This looks like a bug where Zebra, when its state is empty, should be using the known genesis block height, hash, and time or responding without some fields.

### PR DESCRIPTION
**Pull request by elijahhampton**
## Motivation

A lightwalletd test fails for getblockchaininfo when the state is empty. This PR refactors the rpc request to return the genesis block.

## Solution

Adds a test for returning the genesis state in prop.rs. Refactors getblockchaininfo rpc to return the genesis block if TipPoolValues request fails.

### PR Author's Checklist

- [X] The PR name will make sense to users.
- [X] The PR provides a CHANGELOG summary.
- [X] The solution is tested.
- [ ] The documentation is up to date.
- [ ] The PR has a priority label.

### PR Reviewer's Checklist

- [ ] The PR Author's checklist is complete.
- [ ] The PR resolves the issue.

### CODE REVIEW

File: zebra-rpc/src/methods/tests/prop.rs [hunk 1]
```diff
@@ -493,6 +496,109 @@ proptest! {
...
     }
 
+    /// Test the `get_blockchain_info` response when tip_pool request fails.
+    #[test]
+    fn get_blockchain_info_returns_genesis_when_tip_pool_fails(network in any::<Network>()) {
+        let (runtime, _init_guard) = zebra_test::init_async();
+        let _guard = runtime.enter();
+        let (mut mempool, mut state, rpc, mempool_tx_queue) = mock_services(network.clone(), NoChainTip);
+
+
```
Comment (oxarbitrage) [inline zebra-rpc/src/methods/tests/prop.rs:507]:
```suggestion
```

File: zebra-rpc/src/methods/tests/prop.rs [hunk 2]
```diff
@@ -493,6 +496,109 @@ proptest! {
...
+        let genesis_block = match network {
+            Network::Mainnet => {
+                let block_bytes = zebra_test::vectors::CONTINUOUS_MAINNET_BLOCKS[&0];
```
Comment (oxarbitrage) [inline zebra-rpc/src/methods/tests/prop.rs]: It might be clearer to use:

```suggestion
                let block_bytes = &zebra_test::vectors::BLOCK_MAINNET_GENESIS_BYTES;
```

File: zebra-rpc/src/methods/tests/prop.rs [hunk 3]
```diff
@@ -493,6 +496,109 @@ proptest! {
...
+                let block: Arc<Block> = block_bytes.zcash_deserialize_into().expect("block is valid");
+                block
+            },
+            Network::Testnet(_) => {
+                let block_bytes = zebra_test::vectors::CONTINUOUS_TESTNET_BLOCKS[&0];
```
Comment (oxarbitrage) [inline zebra-rpc/src/methods/tests/prop.rs]:
```suggestion
                let block_bytes = &zebra_test::vectors::BLOCK_TESTNET_GENESIS_BYTES;
```

File: zebra-rpc/src/methods/tests/prop.rs [hunk 4]
```diff
@@ -493,6 +496,109 @@ proptest! {
...
+                let block: Arc<Block> = block_bytes.zcash_deserialize_into().expect("block is valid");
+                block
+            },
+        };
+
+        // CORRECTNESS: Nothing in this test depends on real time, so we can speed it up.
+        tokio::time::pause();
```
Comment (oxarbitrage) [inline zebra-rpc/src/methods/tests/prop.rs]: In all the other tests, this line is just after `let (mut mempool, mut state, rpc, mempool_tx_queue) ...`.We might want to move it there for consistency.

**Review by oxarbitrage — DISMISSED** [review]
This looks really good, thank you for making it. There are a few non used imports that need to be fixed. I also left some small optional suggestions in the test code.

**Review by oxarbitrage — APPROVED** [review]

**Comment by mpguerra** [comment]
@mergify requeue
