### PR TITLE
sync: add backpressure to syncer

### LINKED ISSUE #617: Handle backpressure in the Syncer.
The part of the Syncer that was written up in detail in a design document is the logic for managing pipelined block lookup: determining which blocks to download and how to extend prospective chain tips in advance of completed verification of all previous blocks.  This is important for performance, but also because it enables designs like the checkpoint verifier, which would not otherwise be possible.

However, the design did not really describe how the Syncer should handle backpressure, and because it spawns independently-driven tasks for all of the block download and verifications, the sync logic is completely non-blocking on the verification logic.  This means that nothing prevents the syncer from downloading tens or hundreds of thousands of blocks ahead of the verification progress, leading to potential resource exhaustion. Instead, the syncer should have a `LOOKAHEAD_LIMIT` parameter controlling how far ahead of the chain tip it can reach before waiting for queued verifications to complete.  

Here is one potential solution: instead of spawning nested tasks, the syncer should have two `FuturesUnordered`s, one containing `JoinHandle`s for block downloads and one containing `JoinHandle`s for verification tasks.  The chunk size (how many blocks to request from each peer) should be changed from an inline constant to a named `CHUNK_SIZE` constant.  This allows computing the number of in-flight blocks as `downloads.len() * CHUNK_SIZE + verifications.len()`.  If this quantity is bigger than `LOOKAHEAD_LIMIT`, the syncer should wait for in-flight tasks to finish before continuing to extend chain tips.

### LINKED ISSUE #698: zebrad's sync service logs are a bit too verbose
`sync:obtain_tips` logs client request timeouts at error level.

I can submit a PR to reduce them to warn or info, but I don't know how to disable the backtraces. (I tried RUST_BACKTRACE, but it doesn't remove the span trace.)

### PR DESCRIPTION
**Pull request by hdevalence**
Closes #617.
Closes #698.

The remaining work on the syncer is alluded to in a new comment:

1. Correctly constructing a block locator object
2. Detecting when we've stopped making progress syncing and restarting obtain_tips.

### CODE REVIEW

File: zebrad/src/commands/start/sync.rs [hunk 1]
```diff
@@ -14,37 +14,32 @@ use zebra_consensus::checkpoint;
...
-            retry_peer_set,
-            block_requests: FuturesUnordered::new(),
-            // Limit the fanout to the number of chains that the
-            // CheckpointVerifier can handle
-            fanout: checkpoint::MAX_QUEUED_BLOCKS_PER_HEIGHT,
-            prospective_tips: HashSet::new(),
-        }
-    }
+    /// Used to perform extendtips requests, with no retry logic (failover is handled using fanout).
+    tip_network: ZN,
```
Comment (hdevalence) [inline zebrad/src/commands/start/sync.rs:35]: `peer_set` and `retry_peer_set` are renamed according to their uses as `tip_network` and `block_network` because it's a logic error to use one in place of the other.

File: zebrad/src/commands/start/sync.rs [hunk 2]
```diff
@@ -14,37 +14,32 @@ use zebra_consensus::checkpoint;
...
+#[derive(Debug)]
+pub struct Syncer<ZN, ZS, ZV>
 where
-    ZN: Service<zn::Request> + Clone,
+    ZN: Service<zn::Request, Response = zn::Response, Error = Error> + Send + Clone + 'static,
+    ZN::Future: Send,
+    ZS: Service<zs::Request, Response = zs::Response, Error = Error> + Send + Clone + 'static,
+    ZS::Future: Send,
+    ZV: Service<Arc<Block>, Response = BlockHeaderHash, Error = Error> + Send + Clone + 'static,
+    ZV::Future: Send,
```
Comment (hdevalence) [inline zebrad/src/commands/start/sync.rs:32]: Trait bounds are added to the struct itself since we never want to create one without these bounds, and adding them to the struct rather than an impl gives clearer error messages (can't construct the struct rather than can't use some method)

File: zebrad/src/commands/start/sync.rs [hunk 3]
```diff
@@ -67,6 +74,35 @@ where
...
+                        // TODO(hdevalence): handle interruptions in the chain
+                        // sync process. this should detect when we've stopped
+                        // making progress (probably using a timeout), then
+                        // continue the loop with a new invocation of
+                        // obtain_tips(), which will restart block downloads.
+                        // this requires correctly constructing a block locator
+                        // (TODO below) and ensuring that the verifier handles
+                        // multiple requests for verification of the same block
+                        // hash by handling both requests or by discarding the
+                        // earlier request in favor of the later one.
```
Comment (hdevalence) [inline zebrad/src/commands/start/sync.rs:102]: This is the summary of the remaining syncer work to do, mentioned in the main PR comment. It's possible for this code to get stuck if a block we need repeatedly fails to download, but the same was true before and the fix requires fixing up some other TODOs so I'd prefer to do it in a subsequent PR.

File: zebrad/src/commands/start/sync.rs [hunk 4]
```diff
@@ -169,8 +208,9 @@ where
                         "added hashes to download set"
                     );
                 }
-                Ok(r) => tracing::error!("unexpected response {:?}", r),
-                Err(e) => tracing::error!("{:?}", e),
+                Ok(_) => unreachable!("network returned wrong response"),
```
Comment (hdevalence) [inline zebrad/src/commands/start/sync.rs:211]: #698: this isn't a recoverable error, it's a violation of the `zebra-network` contract. So panic.

File: zebrad/src/commands/start/sync.rs [hunk 5]
```diff
@@ -169,8 +208,9 @@ where
...
+                // We ignore this error because we made multiple fanout requests.
+                Err(e) => tracing::debug!(?e),
```
Comment (hdevalence) [inline zebrad/src/commands/start/sync.rs:213]: #698: this error is supposed to be handled using the request fanout as failover, so it's a transient error. Demote it to `debug`.

File: zebrad/src/commands/start/sync.rs [hunk 6]
```diff
@@ -240,8 +284,9 @@ where
 
                         download_set.extend(hashes);
                     }
-                    Ok(r) => tracing::error!("unexpected response {:?}", r),
-                    Err(e) => tracing::error!("{:?}", e),
+                    Ok(_) => unreachable!("network returned wrong response"),
+                    // We ignore this error because we made multiple fanout requests.
+                    Err(e) => tracing::debug!("{:?}", e),
```
Comment (hdevalence) [inline zebrad/src/commands/start/sync.rs:289]: #698, same rationale as above.

File: zebrad/src/commands/start/sync.rs [hunk 7]
```diff
@@ -269,61 +314,31 @@ where
...
-                        } else {
-                            debug!(?resp, "unexpected response");
-                        }
-
-                        while let Some(res) = handles.next().await {
-                            let _hash = res??;
-                        }
-
-                        Ok::<_, Error>(())
+        for hash in hashes.into_iter() {
```
Comment (hdevalence) [inline zebrad/src/commands/start/sync.rs:319]: The logic is much simpler if we don't download blocks in chunks, and get them one at a time instead: we can chain verification to follow a successful download, we don't need to manage fanout of block requests, and we get more precise information in case of failure.

**Comment by hdevalence** [comment]
Oops, this was supposed to be based on the current `main` but I forgot to update my local refs after merging PRs this morning and starting working on it .... rebasing...

File: zebrad/src/commands/start/sync.rs [hunk 8]
```diff
@@ -14,37 +14,32 @@ use zebra_consensus::checkpoint;
...
-    }
+    /// Used to perform extendtips requests, with no retry logic (failover is handled using fanout).
+    tip_network: ZN,
+    /// Used to download blocks, with retry logic.
+    block_network: Retry<RetryLimit, ZN>,
+    state: ZS,
+    verifier: ZV,
+    prospective_tips: HashSet<BlockHeaderHash>,
+    pending_blocks:
+        Pin<Box<FuturesUnordered<Instrumented<JoinHandle<Result<BlockHeaderHash, Error>>>>>>,
```
Comment (yaahc) [inline zebrad/src/commands/start/sync.rs:42]: type alias might help here

File: zebrad/src/commands/start/sync.rs (hunk 4 above)
Comment (yaahc) [reply zebrad/src/commands/start/sync.rs:211]: I thought this was an unavoidable condition thanks to the bitcoin protocol legacy

File: zebrad/src/commands/start/sync.rs [hunk 9]
```diff
@@ -269,65 +314,31 @@ where
...
-
-                        while let Some(res) = handles.next().await {
-                            let _hash = res??;
-                        }
-
-                        Ok::<_, Error>(())
+        for hash in hashes.into_iter() {
+            let mut retry_peer_set = self.block_network.clone();
+            let mut verifier = self.verifier.clone();
+            let span = tracing::info_span!("block_fetch_verify", hash = ?hash);
```
Comment (yaahc) [inline zebrad/src/commands/start/sync.rs]:
```suggestion
            let span = tracing::info_span!("block_fetch_verify", ?hash);
```

the identifier is redundant in this case

File: zebrad/src/commands/start/sync.rs [hunk 10]
```diff
@@ -269,65 +314,31 @@ where
...
+            self.pending_blocks.push(
+                tokio::spawn(async move {
```
Comment (yaahc) [inline zebrad/src/commands/start/sync.rs]: took me a while to realize this was a `push` around the `spawn`, at first read through this looked like a spawn where the join handle was being discarded. Might be worth breaking this up to be a little more imperative, which will also reduce the drift to the right

**Review by yaahc — DISMISSED** [review]

File: zebrad/src/commands/start/sync.rs (hunk 8 above)
Comment (hdevalence) [reply zebrad/src/commands/start/sync.rs:42]: I would add one if this was used in multiple places but I didn't add one here because we don't ever need to refer to this type except in this struct definition.

Comment (yaahc) [reply zebrad/src/commands/start/sync.rs:42]: fair, I was mostly concerned about the weird wrapping because the type is so long.

File: zebrad/src/commands/start/sync.rs (hunk 4 above)
Comment (hdevalence) [reply zebrad/src/commands/start/sync.rs:211]: No, the `zebra-network` implementation guarantees that you don't get a response that's unrelated to your request, the only problem is that we expose the network as a service from any type of request to any type of response rather than as N services from this request to this response, etc.

If we had nice combinators like in future tower we could do lightweight conversions of a zebra-network service to a specific service (like mapping a `HashSet<BlockHeaderHash>` into a `Request` and unwrapping the `Response`) but I think exposing multiple services from zebra-network would make the API much more complicated (since you have to convey somehow that the services are all fronting the same peer set).

Comment (yaahc) [reply zebrad/src/commands/start/sync.rs:211]: Oh okay, good to know. For some reason I thought that `zebra-network` had been unable to abstract away that upstream issue, glad to know that we're safe from this!

File: zebrad/src/commands/start/sync.rs (hunk 10 above)
Comment (hdevalence) [reply zebrad/src/commands/start/sync.rs]: fixed in 476da68

File: zebrad/src/commands/start/sync.rs (hunk 4 above)
Comment (hdevalence) [reply zebrad/src/commands/start/sync.rs:211]: Yep, this should probably be better documented because @teor2345 was surprised too in a different context (in that instance it was that ZN guarantees that if you request blocks by hash you'll either get those blocks or you'll get an error, there's no way to get a different unrelated block).

Comment (hdevalence) [reply zebrad/src/commands/start/sync.rs:211]: #710

File: zebrad/src/commands/start/sync.rs (hunk 3 above)
Comment (teor2345) [reply zebrad/src/commands/start/sync.rs:102]: > ensuring that the verifier handles
> multiple requests for verification of the same block
> hash by handling both requests or by discarding the
> earlier request in favor of the later one.

At the moment, both requests are sent to the verifiers. But even if the verifiers accept the block, the state rejects duplicate block hashes, and the ChainVerifier propagates this rejection back to the caller.

In addition, the CheckpointVerifier rejects duplicates by:
  * storing up to FANOUT blocks at a single height,
  * rejecting additional blocks immediately, and
  * rejecting any other duplicates when the current range is full.

The BlockVerifier accepts duplicate blocks, but this might change when we implement contextual validation.

**Review by teor2345 — APPROVED** [review]
Looks good to me!

I'm really looking forward to having this all working and merged.
