### PR TITLE
1. fix(state): when sending `headers` to peers, only deserialize the header data from disk

### LINKED ISSUE #1924: Stop sending incorrect transaction counts in CountedHeader messages
## Motivation

Zebra supplies the number of transactions in the original block in a `CountedHeader` struct.

But that doesn't match the Bitcoin spec, which always sends zero.

### Specification

The Bitcoin wiki says:
> Number of transaction entries, this value is always 0

https://en.bitcoin.it/wiki/Protocol_documentation#Block_Headers

### Implementation in `zcashd`

`zcashd` always populates this field with zero:
https://github.com/zcash/zcash/blob/420f8dfe38fd6b2465a665324366c2ae14aa98f4/src/main.cpp#L6864-L6874

`zcashd` ignores this field from other nodes:
https://github.com/zcash/zcash/blob/420f8dfe38fd6b2465a665324366c2ae14aa98f4/src/main.cpp#L7046-L7050

### PR DESCRIPTION
**Pull request by teor2345**
## Motivation

When Zebra sends block headers to peers, it fetches the entire block from disk, then throws away the transactions.

This is slow for two reasons:
- fetching extra data costs disk reads
- deserializing transaction data cost CPU time

If we stop deserializing the transactions, it helps with bug #4788, because we avoid some block fetches entirely.

Close #1924, since we were removing transaction counts anyway.

## Solution

- When sending `headers` to peers, only deserialize the header data from disk
    - Call the new `block_header()` method from the existing `block()` method
- Wrap the block header in an `Arc`, so a headers response can be sent to the network without copying 200 kB of data
    - Implement `block::Hash` from `Arc<Header>`
    - Update a lot of tests to use `Arc<Header>`
- Remove incorrect counts from `CountedHeader`

## Review

Anyone can review this PR, it's urgent because it improves sync speed.

### Reviewer Checklist

  - [ ] Code implements Specs and Designs
  - [ ] Tests for Expected Behaviour
  - [ ] Tests for Errors

### CODE REVIEW

File: zebra-chain/src/block.rs [hunk 1]
```diff
@@ -46,9 +46,9 @@ pub use arbitrary::LedgerState;
 #[cfg_attr(any(test, feature = "proptest-impl"), derive(Serialize))]
 pub struct Block {
     /// The block header, containing block metadata.
-    pub header: Header,
+    pub header: Arc<Header>,
```
Comment (teor2345) [inline zebra-chain/src/block.rs:49]: Using `Arc<Header>` reduces memory copies and memory usage, but it needs updates to a bunch of tests.

File: zebra-chain/src/block/header.rs [hunk 2]
```diff
@@ -125,18 +125,14 @@ impl Header {
...
 pub struct CountedHeader {
     /// The header for a block
-    pub header: Header,
-
-    /// The number of transactions that come after the header
-    ///
-    /// TODO: should this always be zero? (#1924)
-    pub transaction_count: CompactSizeMessage,
+    pub header: Arc<Header>,
 }
```
Comment (teor2345) [inline zebra-chain/src/block/header.rs:136]: We can't get the transaction count any more, and it was always wrong to send it, so it's easiest just to remove it.

File: zebra-state/src/service.rs [hunk 3]
```diff
@@ -918,17 +927,10 @@ impl Service<Request> for StateService {
...
-                                .transactions
-                                .len()
-                                .try_into()
-                                .expect("transaction count has already been validated"),
-                            header: block.header,
-                        }
+                        let header = self
+                            .best_block_header(hash.into())
+                            .expect("block header for found hash is in the best chain");
+                        block::CountedHeader { header }
```
Comment (teor2345) [inline zebra-state/src/service.rs:932]: This is the core of the bug fix: get headers from the database, rather than entire blocks.

File: zebra-state/src/service/finalized_state/zebra_db/block.rs [hunk 4]
```diff
@@ -79,20 +79,31 @@ impl ZebraDb {
...
+    //
+    // TODO: move this method to the start of the section
+    #[allow(clippy::unwrap_in_result)]
+    pub fn block(&self, hash_or_height: HashOrHeight) -> Option<Arc<Block>> {
+        // Block
+        let height = hash_or_height.height_or_else(|hash| self.height(hash))?;
+        let header = self.block_header(height.into())?;
+
         // Transactions
         let tx_by_loc = self.db.cf_handle("tx_by_loc").unwrap();
```
Comment (teor2345) [inline zebra-state/src/service/finalized_state/zebra_db/block.rs:108]: This is where we get the block header from the database, rather than the block.

File: zebra-state/src/service/read.rs [hunk 5]
```diff
@@ -77,6 +77,33 @@ where
         .or_else(|| db.block(hash_or_height))
 }
 
+/// Returns the [`block:Header`] with [`block::Hash`](zebra_chain::block::Hash) or
```
Comment (oxarbitrage) [inline zebra-state/src/service/read.rs:80]:
```suggestion
/// Returns the [`block::Header`](zebra_chain::block::Header) with [`block::Hash`](zebra_chain::block::Hash) or
```

**Review by oxarbitrage — APPROVED** [review]
It looks great, thanks @teor2345

**Comment by teor2345** [comment]
I admin-merged this PR because it is an urgent sync fix.
