### PR TITLE
fix(beta-toolchain): Warnings

### LINKED ISSUE #8379: ci(fix): Warnings building in rust beta toolchain
After the last rust upgrade we have a few warnings when building the internal docs. They are visible in all pull requests open after the upgrade for example in https://github.com/ZcashFoundation/zebra/pull/8376/files

Screenshot from 2024-03-26 07-38-57

This warnings do not block the merge of pull requests but we should fix anyways.

### PR DESCRIPTION
**Pull request by oxarbitrage**
## Motivation

The rust beta toolchain has a lot of warnings. `cargo fix` and similars will not fix everything for us so i did it pretty much manually.

Most of the changes are redundant imports, the rest are minor changes too but a lot of them.

Close https://github.com/ZcashFoundation/zebra/issues/8379

Draft until CI runs beta.

#### Check before marking the PR as ready for review:
  - [x] Will the PR name make sense to users?
  - [x] Does the PR have a priority label?
  - [x] Have you added or updated tests?
  - [x] Is the documentation up to date?

## Solution

Fix all warnings.

### Testing

Check CI for beta runs.

## Review

Anyone can review.

### Reviewer Checklist

Check before approving the PR:
  - [ ] Does the PR scope match the ticket?
  - [ ] Are there enough tests to make sure it works? Do the tests cover the PR motivation?
  - [ ] Are all the PR blockers dealt with?
        PR blockers can be dealt with in new tickets or PRs.

_And check the PR Author checklist is complete._

### CODE REVIEW

**Comment by arya2** [comment]
Added `do-not-merge` while we tag the release.

@upbqdn I can review this one if you want to prioritize reviewing the release PR and #8383.

File: zebra-chain/src/transparent/address.rs [hunk 1]
```diff
@@ -158,6 +158,7 @@ impl ZcashDeserialize for Address {
     }
 }
 
+#[allow(dead_code)]
```
Comment (arya2) [inline zebra-chain/src/transparent/address.rs]: Optional/Nitpick: Could we move this and its impls to the `tests` module below?

File: zebra-chain/src/transparent/address.rs [hunk 2]
```diff
@@ -223,6 +224,7 @@ impl Address {
         }
     }
 
+    #[allow(dead_code)]
```
Comment (arya2) [inline zebra-chain/src/transparent/address.rs]: Optional/Nitpick: Could this be moved to the `tests` module too?

File: zebra-rpc/src/methods/get_block_template_rpcs/types/long_poll.rs [hunk 3]
```diff
@@ -227,6 +227,7 @@ fn update_checksum(checksum: &mut u32, item: [u8; 32]) {
     }
 }
 
+#[allow(unknown_lints, clippy::to_string_trait_impl)]
```
Comment (arya2) [inline zebra-rpc/src/methods/get_block_template_rpcs/types/long_poll.rs]: Optional/Nitpick: This may not need to be implemented directly, could we replace this with a `Display` impl using `write!()` instead? So:

```rust

impl std::fmt::Display for LongPollId {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        let LongPollId {
            tip_height,
            tip_hash_checksum,
            max_timestamp,
            mempool_transaction_count,
            mempool_transaction_content_checksum,
        } = self;

        // We can't do this using `serde`, because it names each field,
        // but we want a single string containing all the fields.
        write!(
            f,
            // Height as decimal, padded with zeroes to the width of Height::MAX
            // Checksums as hex, padded with zeroes to the width of u32::MAX
            // Timestamp as decimal, padded with zeroes to the width of u32::MAX
            // Transaction Count as decimal, padded with zeroes to the width of u32::MAX
            "{tip_height:010}\
             {tip_hash_checksum:08x}\
             {max_timestamp:010}\
             {mempool_transaction_count:010}\
             {mempool_transaction_content_checksum:08x}"
        )
    }
}


```

File: zebra-chain/src/tests/vectors.rs [hunk 4]
```diff
@@ -30,7 +30,7 @@ impl Network {
         }
     }
 
-    ///
+    /// Returns BTreemap of blocks.
```
Comment (upbqdn) [inline zebra-chain/src/tests/vectors.rs]: ###### Optional Suggestion

```suggestion
    /// Returns blocks indexed by height in a [`BtreeMap`].
    ///
    /// Returns Mainnet blocks if `self` is set to Mainnet, and Testnet blocks otherwise.
```

File: zebra-test/src/mock_service.rs [hunk 5]
```diff
@@ -959,6 +959,7 @@ impl<Request, Response, Error> ResponseSender<Request, Response, Error> {
     }
 }
 
+#[allow(dead_code)]
```
Comment (upbqdn) [inline zebra-test/src/mock_service.rs]: ###### Optional Suggestion

It's better to put attributes below comments: https://github.com/rust-lang/style-team/issues/72.

File: zebra-chain/src/transparent/address.rs (hunk 2 above)
Comment (upbqdn) [inline zebra-chain/src/transparent/address.rs]: ###### Optional Suggestion

It's better to put attributes below comments: https://github.com/rust-lang/style-team/issues/72.

File: zebra-test/src/mock_service.rs (hunk 5 above)
Comment (arya2) [inline zebra-test/src/mock_service.rs]: Optional/Nitpick: Do we want to open an issue for adding this as a constraint on the `MockService` struct and its methods? I think it's also fine to leave it as dead code for now, it's still useful for documentation.

**Review by upbqdn — DISMISSED** [review]

**Comment by upbqdn** [comment]
@arya, I'm only noticing your comment now. This was quick to review anyway.

**Review by arya2 — DISMISSED** [review]
Thank you!

File: zebra-chain/src/tests/vectors.rs [hunk 6]
```diff
@@ -30,7 +30,9 @@ impl Network {
         }
     }
 
+    /// Returns blocks indexed by height in a [`BtreeMap`].
```
Comment (arya2) [inline zebra-chain/src/tests/vectors.rs]:
```suggestion
    /// Returns blocks indexed by height in a [`BTreeMap`].
```

File: zebra-chain/src/transparent/address.rs (hunk 1 above)
Comment (oxarbitrage) [reply zebra-chain/src/transparent/address.rs]: https://github.com/ZcashFoundation/zebra/pull/8404/commits/a7da26e6ff69555b176d039ce51833b45c8a9578

File: zebra-chain/src/transparent/address.rs (hunk 2 above)
Comment (oxarbitrage) [reply zebra-chain/src/transparent/address.rs]: https://github.com/ZcashFoundation/zebra/pull/8404/commits/a7da26e6ff69555b176d039ce51833b45c8a9578

File: zebra-rpc/src/methods/get_block_template_rpcs/types/long_poll.rs (hunk 3 above)
Comment (oxarbitrage) [reply zebra-rpc/src/methods/get_block_template_rpcs/types/long_poll.rs]: Thanks, fixed this at https://github.com/ZcashFoundation/zebra/pull/8404/commits/f0d6d862a9221b9b860364ab14a80f94a757bfa8

File: zebra-chain/src/tests/vectors.rs (hunk 6 above)
Comment (oxarbitrage) [reply zebra-chain/src/tests/vectors.rs]: https://github.com/ZcashFoundation/zebra/pull/8404/commits/5247b1e8cc34934fd65f7070bbe72ff50d404cc6

File: zebra-test/src/mock_service.rs (hunk 5 above)
Comment (oxarbitrage) [reply zebra-test/src/mock_service.rs]: let just leave it, i don't think is very important.

**Review by upbqdn — APPROVED** [review]

**Comment by arya2** [comment]
@Mergifyio refresh
