### PR TITLE
Acceptance tests - check kill signal

### LINKED ISSUE #804: Check for panics in the acceptance tests
In #690, we create acceptance tests for each zebrad command.

When we run seed and start, we kill them after 1 second, then check for a failed exit status. But we don't check to see if the command panicked while starting up.

Let's fail on panics by:
1. adding a constant with the signal or exit code that's returned by a killed process
2. passing the test if we get that signal or exit code
3. failing the test if we get anything else

Since signals only exist on cfg(unix), we'll need to check signals on unix, and codes on not(unix).

Here's the exit code reference docs:
https://doc.rust-lang.org/std/process/struct.ExitStatus.html#method.code

Here's an example of conditional exit codes and signals:
https://github.com/ZcashFoundation/zebra/blob/917a4fbdbedb370c6b62ee5428d6453442060d20/zebra-utils/src/bin/zebra-checkpoints/main.rs#L62-L75

### PR DESCRIPTION
**Pull request by oxarbitrage**
Fix https://github.com/ZcashFoundation/zebra/issues/804

### CODE REVIEW

File: zebra-test/src/command.rs [hunk 1]
```diff
@@ -221,4 +224,12 @@ impl TestOutput {
         .with_section(command)
         .with_section(stdout)
     }
+
+    pub fn exit_code(&self) -> Option<i32> {
```
Comment (teor2345) [inline zebra-test/src/command.rs]: Suggestion: Let's use a generic name for "code or signal". And let's document the function.

```suggestion
    /// Returns the exit signal on unix platforms, and the exit code otherwise.
    pub fn exit_status(&self) -> Option<i32> {
```

File: zebrad/tests/acceptance.rs [hunk 2]
```diff
@@ -8,6 +8,11 @@ use color_eyre::eyre::Result;
 use std::time::Duration;
 use zebra_test::prelude::*;
 
+#[cfg(unix)]
+const KILL_SIGNAL: i32 = 9;
+#[cfg(not(unix))]
+const KILL_SIGNAL: i32 = 1;
```
Comment (teor2345) [inline zebrad/tests/acceptance.rs]: Similarly, let's use generic names, and document:

```suggestion
/// The kill signal exit status on unix platforms.
#[cfg(unix)]
const KILL_STATUS: i32 = 9;
/// The kill exit code on non-unix platforms.
#[cfg(not(unix))]
const KILL_STATUS: i32 = 1;
```

**Review by teor2345 — DISMISSED** [review]
Looks great, thanks for doing this work!

I have some suggestions about names and documentation.

These functions are starting to look similar, do you think it's worth factoring out the repeated code?

File: zebra-test/src/command.rs [hunk 3]
```diff
@@ -221,4 +224,13 @@ impl TestOutput {
...
     }
+
+    /// Returns the exit signal on unix platforms, and the exit code otherwise.
+    pub fn exit_status(&self) -> Option<i32> {
+        #[cfg(unix)]
+        return self.output.status.signal();
+
+        #[cfg(not(unix))]
+        return self.output.status.code();
+    }
```
Comment (yaahc) [inline zebra-test/src/command.rs]: I think we should try to isolate the platform specific behaviour to this function rather than mixing up signals and exit codes and requiring ppl to know that the meaning of the value depends on the platform.

```suggestion
    /// Returns the exit signal on unix platforms, and the exit code otherwise.
    pub fn was_killed(&self) -> bool {
        #[cfg(unix)]
        self.output.status.signal() == Some(9)

        #[cfg(not(unix))]
        self.output.status.code() == Some(1)
    }
```

**Review by yaahc — CHANGES_REQUESTED** [review]

File: zebra-test/src/command.rs (hunk 3 above)
Comment (oxarbitrage) [reply zebra-test/src/command.rs]: Sounds good to me, i made this change at https://github.com/ZcashFoundation/zebra/pull/814/commits/dee397a2a8fdfc7a1225dbce412fac47f57e2818

I was not able to remove the `return`s in the `was_killed` function as suggested, build issues in that form with the macros.

File: zebrad/tests/acceptance.rs [hunk 4]
```diff
@@ -155,7 +148,7 @@ fn seed_no_args() -> Result<()> {
     output.stdout_contains(r"Starting zebrad in seed mode")?;
 
     // Make sure the command was killed
-    assert_eq!(output.exit_status(), Some(KILL_STATUS));
+    assert_eq!(output.was_killed(), true);
```
Comment (yaahc) [inline zebrad/tests/acceptance.rs]:
```suggestion
    assert!(output.was_killed());
```

**Review by yaahc — CHANGES_REQUESTED** [review]
Just need to fix up the `assert_eq!` calls then I think this is good to go :smile:

**Review by yaahc — APPROVED** [review]
Looks great, thank you again!

File: zebrad/tests/acceptance.rs (hunk 4 above)
Comment (oxarbitrage) [reply zebrad/tests/acceptance.rs]: Thanks, changed those at https://github.com/ZcashFoundation/zebra/pull/814/commits/c2bbbd37156db5cd077fdefbcd6eeeb645535db5

**Review by dconnolly — APPROVED** [review]
🛥️
