### PR TITLE
change(state): Check database format is valid on shutdown, to catch format errors in new block code

### LINKED ISSUE #7570: Test that "sync from empty" and "upgrade from existing" state code produces the same data
### Motivation

We want to prevent bugs like #7532 happening again. Expecting developers to run manual tests on all the different ways of creating a state isn't reliable.

#### Run subtree tests on both kinds of states

One option is to run the subtree tests in tickets #7450, #7451, and #7446 on both a "sync from new" state and an "upgrade from existing" state. But to do that, we'd need to:
1. change the state selection script so it accepts a parameter for new/upgraded state kinds
2. change the state deletion script so it always keeps both state kinds
3. Run all those tests twice
4. Remember to do this for every future state upgrade

#### Re-run state validity checks while Zebra is running

Another option is to repeat the state validity check in PR #7566:
- [x] periodically while Zebra is running
- [x] before Zebra shuts down (or any time after the full sync finishes)
- [ ] fail CI if the format is wrong

Then that check will run:
- on upgraded states: PRs and main branch merges (this already happens once),
- on "sync from empty" states: the weekly full sync (this is the missing check),
- before we write the cached state in CI.

Then as soon as we merge PR #7565 we'll automatically get a ticket when these checks fail on `main` merges or scheduled full syncs.

This seems like the more reliable option, because it will automatically test all state upgrade code, not just subtrees. 

### Complex Code or Requirements

Now we have two different code paths for creating state data, we need to check that they create exactly the same data.

But unfortunately, we can't run a full and an upgrade sync on each PR, because that would take 3 days. So this ticket is about finding another way to reduce the risk.

### Testing

This is a testing ticket.

### PR DESCRIPTION
**Pull request by teor2345**
## Motivation

We want to catch format errors in new block code. But currently that code is only tested when Zebra adds new blocks, then shuts down, then opens the same state. So PRs can merge with bugs in that code.

Instead, we check the format is valid before Zebra shuts down. This tells users early if they need to re-sync their state, rather than surprising them the next time they launch Zebra.

It also prevents us writing invalid cached states in CI.

Close #7570.

### Complex Code or Requirements

I think a panic on shutdown should fail CI, but I haven't checked to make sure. Do you think it's worth doing that manually?

## Solution

- [Tell the user what to do when the database format is invalid](https://github.com/ZcashFoundation/zebra/commit/91c52a5bd66ea3554823badfb99aa4730f247e76)
- [Check the database format before Zebra shuts down](https://github.com/ZcashFoundation/zebra/commit/1878581e8f7a863cc0af93fe05f2343c24d6cf79)

Related Refactors:
- [Split a path-based database version method](https://github.com/ZcashFoundation/zebra/commit/48d13295b55d12034bd837d2e543a48faf7f2d30)

## Review

This is optional for the release.

### Reviewer Checklist

  - [ ] Will the PR name make sense to users?
    - [ ] Does it need extra CHANGELOG info? (new features, breaking changes, large changes)
  - [ ] Are the PR labels correct?
  - [ ] Does the code do what the ticket and PR says?
    - [ ] Does it change concurrent code, unsafe code, or consensus rules?
  - [ ] How do you know it works? Does it have tests?

## Follow Up Work

We could replace a whole lot of `config` arguments with the database and version paths, but that can happen later if needed. Storing an `Arc<Config>` isn't that expensive.

### CODE REVIEW

**Comment by upbqdn** [comment]
> I think a panic on shutdown should fail CI, but I haven't checked to make sure.  Do you think it's worth doing that manually?

I don't think so.

File: zebra-state/src/service/finalized_state/disk_format/upgrade.rs [hunk 1]
```diff
@@ -369,8 +369,12 @@ impl DbFormatChange {
         //   (unless a future upgrade breaks these format checks)
         // - re-opening the current version should be valid, regardless of whether the upgrade
         //   or new block code created the format (or any combination).
-        Self::format_validity_checks_detailed(upgrade_db, cancel_receiver)?
-            .expect("new, upgraded, or downgraded database format is valid");
+        Self::format_validity_checks_detailed(upgrade_db, cancel_receiver)?.unwrap_or_else(|_| {
```
Comment (upbqdn) [inline zebra-state/src/service/finalized_state/disk_format/upgrade.rs:372]: Did you use `unwrap_or_else()` over `expect()` to avoid costly string formatting?

File: zebra-state/src/service/finalized_state/zebra_db.rs [hunk 2]
```diff
@@ -169,6 +178,42 @@ impl ZebraDb {
...
+            // # Correctness
+            //
+            // Check that the database format is correct before shutting down.
+            // This lets users know to delete and re-sync their database immediately,
+            // rather than surprising them next time Zebra starts up.
+            //
+            // # Testinng
+            //
+            // In Zebra's CI, panicking here stops us writing invalid cached states,
+            // which would then get make unrelated PRs fail when Zebra starts up.
```
Comment (upbqdn) [inline zebra-state/src/service/finalized_state/zebra_db.rs]: ###### Optional Suggestion

```suggestion
            // which would then make unrelated PRs fail when Zebra starts up.
```

**Review by upbqdn — DISMISSED** [review]

File: zebra-state/src/service/finalized_state/disk_format/upgrade.rs (hunk 1 above)
Comment (teor2345) [reply zebra-state/src/service/finalized_state/disk_format/upgrade.rs:372]: This is a clippy lint, so I just did what it said.

This code runs every 5 minutes, so the string formatting cost is minimal.

**Review by upbqdn — APPROVED** [review]
