### PR TITLE
fix(net): Reduce inbound service overloads and add a timeout

### LINKED ISSUE #6911: Avoid hangs due to slow inbound service requests
## Motivation

I'm still seeing multiple connections dropped in rapid succession:
```
2023-06-11T22:29:18.631120Z  INFO {zebrad="1e643e1" net="Main"}:{peer=Out("v4redacted:8233")}:msg_as_req{msg="inv"}: zebra_network::peer::connection: inbound service is overloaded, closing connection drop_connection_probability=0.05000000074505806 remote_user_agent="/MagicBean:5.4.2/" negotiated_version=Version(170100) peer="v4redacted:8233" 
```

<details>

<summary>15 connections dropped in less than a millisecond</summary>

```
2023-06-11T22:29:18.631120Z  INFO {zebrad="1e643e1" net="Main"}:{peer=Out("v4redacted:8233")}:msg_as_req{msg="inv"}: zebra_network::peer::connection: inbound service is overloaded, closing connection drop_connection_probability=0.05000000074505806 remote_user_agent="/MagicBean:5.4.2/" negotiated_version=Version(170100) peer="v4redacted:8233" last_peer_state=Some("AwaitingRequest::In::Req::AdvertiseTransactionIds") remote_height=Height(2118305) cached_addrs=1 connection_state=AwaitingRequest
2023-06-11T22:29:18.631109Z  INFO {zebrad="1e643e1" net="Main"}:{peer=Out("v4redacted:8233")}:msg_as_req{msg="inv"}: zebra_network::peer::connection: inbound service is overloaded, closing connection drop_connection_probability=0.05000000074505806 remote_user_agent="/MagicBean:5.5.1/" negotiated_version=Version(170100) peer="v4redacted:8233" last_peer_state=Some("AwaitingRequest::In::Req::AdvertiseTransactionIds") remote_height=Height(2118308) cached_addrs=1 connection_state=AwaitingRequest
2023-06-11T22:29:18.631150Z  INFO {zebrad="1e643e1" net="Main"}:{peer=Out("v4redacted:8233")}:msg_as_req{msg="inv"}: zebra_network::peer::connection: inbound service is overloaded, closing connection drop_connection_probability=0.949999988079071 remote_user_agent="/MagicBean:5.5.1/" negotiated_version=Version(170100) peer="v4redacted:8233" last_peer_state=Some("AwaitingRequest::In::Req::AdvertiseTransactionIds") remote_height=Height(2118276) cached_addrs=1 connection_state=AwaitingRequest                                                                                                                    
2023-06-11T22:29:18.631159Z  INFO {zebrad="1e643e1" net="Main"}:{peer=Out("v4redacted:8233")}:msg_as_req{msg="inv"}: zebra_network::peer::connection: inbound service is overloaded, closing connection drop_connection_probability=0.949999988079071 remote_user_agent="/MagicBean:5.5.1/" negotiated_version=Version(170100) peer="v4redacted:8233" last_peer_state=Some("AwaitingRequest::In::Req::AdvertiseTransactionIds") remote_height=Height(2118316) cached_addrs=1 connection_state=AwaitingRequest
2023-06-11T22:29:18.631191Z  INFO {zebrad="1e643e1" net="Main"}:{peer=Out("v4redacted:8233")}:msg_as_req{msg="inv"}: zebra_network::peer::connection: inbound service is overloaded, closing connection drop_connection_probability=0.949999988079071 remote_user_agent="/MagicBean:5.5.1/" negotiated_version=Version(170100) peer="v4redacted:8233" last_peer_state=Some("AwaitingRequest::In::Req::AdvertiseTransactionIds") remote_height=Height(2118308) cached_addrs=2 connection_state=AwaitingRequest
2023-06-11T22:29:18.631193Z  INFO {zebrad="1e643e1" net="Main"}:{peer=Out("v4redacted:8233")}:msg_as_req{msg="inv"}: zebra_network::peer::connection: inbound service is overloaded, closing connection drop_connection_probability=0.05000000074505806 remote_user_agent="/MagicBean:5.4.1/" negotiated_version=Version(170100) peer="v4redacted:8233" last_peer_state=Some("AwaitingRequest::In::Req::AdvertiseTransactionIds") remote_height=Height(2118316) cached_addrs=1 connection_state=AwaitingRequest
2023-06-11T22:29:18.631182Z  INFO {zebrad="1e643e1" net="Main"}:{peer=Out("v4redacted:8836")}:msg_as_req{msg="inv"}: zebra_network::peer::connection: inbound service is overloaded, closing conn ... p_connection_probability=0.949999988079071 remote_user_agent="/MagicBean:5.5.1/" negotiated_version=Version(170100) peer="v4redacted:8836" last_peer_state=Some("AwaitingRequest::In::Req::AdvertiseTransactionIds") remote_height=Height(2118304) cached_addrs=2 connection_state=AwaitingRequest
2023-06-11T22:29:18.631198Z  INFO {zebrad="1e643e1" net="Main"}:{peer=Out("v4redacted:8233")}:msg_as_req{msg="inv"}: zebra_network::peer::connection: inbound service is overloaded, closing connection drop_connection_probability=0.949999988079071 remote_user_agent="/MagicBean:5.5.1/" negotiated_version=Version(170100) peer="v4redacted:8233" last_peer_state=Some("AwaitingRequest::In::Req::AdvertiseTransactionIds") remote_height=Height(2118298) cached_addrs=1000 connection_state=AwaitingRequest
2023-06-11T22:29:18.631201Z  INFO {zebrad="1e643e1" net="Main"}:{peer=Out("v4redacted:30834")}:msg_as_req{msg="inv"}: zebra_network::peer::connection: inbound service is overloaded, closing connection drop_connection_probability=0.949999988079071 remote_user_agent="/MagicBean:5.5.1/" negotiated_version=Version(170100) peer="v4redacted:30834" last_peer_state=Some("AwaitingRequest::In::Req::AdvertiseTransactionIds") remote_height=Height(2118308) cached_addrs=0 connection_state=AwaitingRequest
2023-06-11T22:29:18.631199Z  INFO {zebrad="1e643e1" net="Main"}:{peer=Out("v4redacted:8233")}:msg_as_req{msg="inv"}: zebra_network::peer::connection: inbound service is overloaded, closing connection drop_connection_probability=0.949999988079071 remote_user_agent="/MagicBean:5.5.0/" negotiated_version=Version(170100) peer="v4redacted:8233" last_peer_state=Some("AwaitingRequest::In::Req::AdvertiseTransactionIds") remote_height=Height(2118298) cached_addrs=1 connection_state=AwaitingRequest
2023-06-11T22:29:18.631197Z  INFO {zebrad="1e643e1" net="Main"}:{peer=Out("v4redacted:2838")}:msg_as_req{msg="inv"}: zebra_network::peer::connection: inbound service is overloaded, closing connection drop_connection_probability=0.949999988079071 remote_user_agent="/MagicBean:5.5.0/" negotiated_version=Version(170100) peer="v4redacted:2838" last_peer_state=Some("AwaitingRequest::In::Req::AdvertiseTransactionIds") remote_height=Height(2118308) cached_addrs=1000 connection_state=AwaitingRequest
2023-06-11T22:29:18.631215Z  INFO {zebrad="1e643e1" net="Main"}:{peer=Out("v4redacted:30834")}:msg_as_req{msg="inv"}: zebra_network::peer::connection: inbound service is overloaded, closing connection drop_connection_probability=0.949999988079071 remote_user_agent="/MagicBean:5.5.1/" negotiated_version=Version(170100) peer="v4redacted:30834" last_peer_state=Some("AwaitingRequest::In::Req::AdvertiseTransactionIds") remote_height=Height(2118308) cached_addrs=0 connection_state=AwaitingRequest
2023-06-11T22:29:18.631224Z  INFO {zebrad="1e643e1" net="Main"}:{peer=In("v4redacted:32838")}:msg_as_req{msg="inv"}: zebra_network::peer::connection: inbound service is overloaded, closing connection drop_connection_probability=0.949999988079071 remote_user_agent="/Zebra:1.0.0-rc.8/" negotiated_version=Version(170100) peer="v4redacted:32838" last_peer_state=Some("AwaitingRequest::In::Req::AdvertiseTransactionIds") remote_height=Height(2118313) cached_addrs=0 connection_state=AwaitingRequest
2023-06-11T22:29:18.631231Z  INFO {zebrad="1e643e1" net="Main"}:{peer=Out("v4redacted:8233")}:msg_as_req{msg="inv"}: zebra_network::peer::connection: inbound service is overloaded, closing connection drop_connection_probability=0.949999988079071 remote_user_agent="/MagicBean:5.4.2/" negotiated_version=Version(170100) peer="v4redacted:8233" last_peer_state=Some("AwaitingRequest::In::Req::AdvertiseTransactionIds") remote_height=Height(2118308) cached_addrs=1 connection_state=AwaitingRequest
2023-06-11T22:29:18.631219Z  INFO {zebrad="1e643e1" net="Main"}:{peer=Out("v4redacted:8333")}:msg_as_req{msg="inv"}: zebra_network::peer::connection: inbound service is overloaded, closing connection drop_connection_probability=0.949999988079071 remote_user_agent="/MagicBean:5.5.1/" negotiated_version=Version(170100) peer="v4redacted:8333" last_peer_state=Some("AwaitingRequest::In::Req::AdvertiseTransactionIds") remote_height=Height(2118308) cached_addrs=2 connection_state=AwaitingRequest
```

</details>

### Specifications

Tower has a timeout layer, we use timeouts on almost every other request, but not inbound service requests.

**Edit:**
I don't think this is happening due to the Buffer implementation, but that needs to be documented:
https://docs.rs/tower/latest/tower/buffer/struct.Buffer.html#a-note-on-choosing-a-bound

### Complex Code or Requirements

This is complicated concurrent code. It should have a timeout.

**Edit:**
~~We can fix it by closing overloaded connections based on the inbound buffer being un-ready, rather than using a `LoadShed` layer to turn them into request errors. This avoids holding an inbound buffer semaphore for a long period of time.~~

### Testing

We should test for hangs caused by the inbound service, and check the logs to make sure that fewer connections are dropped when the inbound service is overloaded.

We can open a new ticket when we know which inbound requests are slow.

## Related Work

This is likely part of:
- #6763

### PR DESCRIPTION
**Pull request by teor2345**
## Motivation

Sometimes Zebra's inbound service gets overloaded and drops a whole lot of connections at the same time.

Close #6911

### Complex Code or Requirements

This is concurrent code.

## Solution

Timeouts:
- Add a timeout to inbound service requests, there is currently no timeout on those requests. This is a security issue.
- Treat inbound timeouts like queue overloads

Overloads:
- Increase the inbound concurrency limit, to reduce overloads at the cost of slightly more memory
- Reduce the peer broadcast fraction, to reduce network load
- Reduce maximum connection drop probability, to reduce the number of disconnections that happen at the same time

Related changes:
- Document security requirements of inbound peer overload handling

## Review

This is an important security fix, it should go in early in the next release.

### Reviewer Checklist

  - [ ] Will the PR name make sense to users?
    - [ ] Does it need extra CHANGELOG info? (new features, breaking changes, large changes)
  - [ ] Are the PR labels correct?
  - [ ] Does the code do what the ticket and PR says?
    - [ ] Does it change concurrent code, unsafe code, or consensus rules?
  - [ ] How do you know it works? Does it have tests?

## Follow Up Work

Work out which requests are slow (or numerous), and make them faster. This PR adds logging for inbound request timeouts.

### CODE REVIEW

File: zebrad/src/components/inbound.rs [hunk 1]
```diff
@@ -50,6 +52,12 @@ mod tests;
 
 use downloads::Downloads as BlockDownloads;
 
+/// The maximum amount of time an inbound service response can take.
+///
+/// If the response takes longer than this time, it will be cancelled,
+/// and the peer might be disconnected.
+pub const MAX_INBOUND_RESPONSE_TIME: Duration = Duration::from_secs(5);
```
Comment (teor2345) [inline zebrad/src/components/inbound.rs:59]: Our outbound request timeout is 20 seconds, but that seems like a long time to block inbound requests.

File: zebrad/src/components/inbound/downloads.rs [hunk 2]
```diff
@@ -49,7 +49,7 @@ type BoxError = Box<dyn std::error::Error + Send + Sync + 'static>;
 /// Since Zebra keeps an `inv` index, inbound downloads for malicious blocks
 /// will be directed to the malicious node that originally gossiped the hash.
 /// Therefore, this attack can be carried out by a single malicious node.
-pub const MAX_INBOUND_CONCURRENCY: usize = 20;
+pub const MAX_INBOUND_CONCURRENCY: usize = 30;
```
Comment (arya2) [inline zebrad/src/components/inbound/downloads.rs:52]: Tangent: It would nice to make target memory usage configurable to scale some of these constants.

File: zebra-network/src/constants.rs [hunk 3]
```diff
@@ -349,7 +349,7 @@ pub const MIN_OVERLOAD_DROP_PROBABILITY: f32 = 0.05;
 
 /// The maximum probability of dropping a peer connection when it receives an
 /// [`Overloaded`](crate::PeerError::Overloaded) error.
-pub const MAX_OVERLOAD_DROP_PROBABILITY: f32 = 0.95;
+pub const MAX_OVERLOAD_DROP_PROBABILITY: f32 = 0.5;
```
Comment (arya2) [inline zebra-network/src/constants.rs:352]: 👍

**Review by arya2 — APPROVED** [review]
This looks good, thank you.

> [we're downloading blocks in the wrong order (not strict height order) then hitting a concurrency limit](https://github.com/ZcashFoundation/zebra/issues/6763#issuecomment-1587965168)

I suspect you were right about the blocks being out of order, increasing `MAX_INBOUND_CONCURRENCY` should help.

File: zebrad/src/components/inbound/downloads.rs (hunk 2 above)
Comment (teor2345) [reply zebrad/src/components/inbound/downloads.rs:52]: Counterpoint: If these constants have reliability impacts, then we might not want users changing them. Every configuration is something extra we have to support.
