### PR TITLE
fix spandoc instrumentation for await expressions

### LINKED ISSUE #609: Fix spandoc in the BlockVerifier tests
Blocked by the code movement in ticket #582.

We need to fix spandoc usage in the BlockVerifier tests, so we call `map_err` before `await`:
```
                .await
                .map_err(|e| eyre!(e))?;
```
Becomes:
```
                .map_err(|e| eyre!(e))
                .await?;
```

See commit fec6d2ba47be0fffa9e8c11687a7b94a83136000 for more examples of this fix in CheckpointVerifier.

> So I'm working on fixing this but for now spandoc is restricted on how thoroughly it can instrument futures. The problem is it can only instrument the futures themselves, and not the rest of the expressions in the chain of function calls. The way you have this setup (and the way I setup the examples that you based this on) is subtly wrong. Right here you're constructing a `Report` in a combinator on the `Result` returned from the future, so this gets called after the future is done executing and the span is no longer entered. We need to start using `TryFutureExt::map_err` before the await to have the conversion run as part of the future if we want to get these spandoc comments in our error messages.
> 
> So if you notice your spandoc spans aren't showing up in your eyre::Reports that's why.

_Originally posted by @yaahc in https://github.com/_render_node/MDE3OlB1bGxSZXF1ZXN0UmV2aWV3NDQ0MTM3MDQx/pull_request_reviews/more_threads_

### PR DESCRIPTION
**Pull request by yaahc**
This PR and the associated changes upstream in `spandoc` fix the issues in https://github.com/ZcashFoundation/zebra/issues/609 and make it so either ordering of `map_err` and `await` is valid and correctly instrumented :partying_face:

### CODE REVIEW

**Comment by yaahc** [comment]
blocked on upstream release of spandoc

File: zebra-consensus/src/checkpoint.rs [hunk 1]
```diff
@@ -781,17 +785,17 @@ mod tests {
             BlockHeight(0)
         );
 
-        /// Make sure the verifier service is ready
+        /// SPANDOC: Make sure the verifier service is ready
```
Comment (yaahc) [inline zebra-consensus/src/checkpoint.rs:788]: `spandoc` is now configured to ignore all doc comments that don't start with `SPANDOC: `. This is to prevent issues where people accidentally use `///` and `//` interchangably and to help new contributors figure out wtf is going on with our in-function doc comments

File: zebra-consensus/src/checkpoint.rs [hunk 2]
```diff
@@ -818,6 +822,10 @@ mod tests {
     }
 
     #[tokio::test]
+    async fn multi_item_checkpoint_list_test() -> Result<(), Report> {
```
Comment (yaahc) [inline zebra-consensus/src/checkpoint.rs:825]: I had to split these tests into inner and outer functions to separate the `#[tokio::test]` and `#[spandoc]` attributes which do not play together well due to bugs in span preservation in proc macros. If you put both attributes on the same function all "unused doc comment" warnings will be reported at `lib.rs:1` so its really difficult to figure out why the warning got introduced.

**Review by dconnolly — APPROVED** [review]
lgtm! 🐻
