### PR TITLE
fix(tests): Checking if transactions get into the mempool fails in lightwalletd tests

### LINKED ISSUE #7529: Checking if transactions get into the mempool fails in lightwalletd tests
In `send_transaction_tests` we send transactions using grpc and then attempt to check if they are inside the mempool using grpc calls as well. This should be more or less what a wallet using lightwalletd may want to do.

However, the check of the mempool works in some local environments (i was able to make that work reliable locally) but fails in the CI for unknown reasons.

In the past, when we were using `adityapk00` lightwalletd fork the mempool calls were commented out so an empty response was expected.  When we changed to the `zcash` lightwalletd we were expecting this test to start working so they were enabled in https://github.com/ZcashFoundation/zebra/pull/7349, however this is not the case so we disabled them back again in the same PR.

We don't know the reason of the failure. More details can be found in https://github.com/ZcashFoundation/zebra/pull/7349

### PR DESCRIPTION
**Pull request by arya2**
## Motivation

Zebra should be using the zcash/lightwalletd service.proto.

Close #7529.

## Solution

- Use updated service.proto from [zcash/lightwalletd](https://github.com/zcash/lightwalletd/blob/master/walletrpc/service.proto)
  - Where height has been changed from -1 to 0, lightwalletd ignores that field anyways.

Related Cleanups:
- Remove redundant truncate in test code

## Review

Anyone can review.

### Reviewer Checklist

  - [ ] Will the PR name make sense to users?
    - [ ] Does it need extra CHANGELOG info? (new features, breaking changes, large changes)
  - [ ] Are the PR labels correct?
  - [ ] Does the code do what the ticket and PR says?
    - [ ] Does it change concurrent code, unsafe code, or consensus rules?
  - [ ] How do you know it works? Does it have tests?

### CODE REVIEW

File: zebrad/tests/common/lightwalletd/send_transaction_test.rs [hunk 1]
```diff
@@ -148,9 +147,6 @@ pub async fn run() -> Result<()> {
 
     let mut rpc_client = connect_to_lightwalletd(lightwalletd_rpc_port).await?;
 
-    // To avoid filling the mempool queue, limit the transactions to be sent to the RPC and mempool queue limits
-    transactions.truncate(max_sent_transactions());
```
Comment (teor2345) [inline zebrad/tests/common/lightwalletd/send_transaction_test.rs:152]: Note: Removing redundant code like this is great. But if you remember, please mention it in the PR description, so reviewers don't have to search for the reason for the code change.

File: zebrad/tests/common/lightwalletd/send_transaction_test.rs [hunk 2]
```diff
@@ -202,15 +198,14 @@ pub async fn run() -> Result<()> {
...
-    //    "all transactions from future blocks failed to send to an isolated mempool"
-    //);
+    // This check will fail if there are no non-coinbase transactions in the first 50 non-finalized blocks
+    assert!(
+        counter >= 1,
+        "all transactions from future blocks failed to send to an isolated mempool"
+    );
 
     // GetMempoolTx: make sure at least one of the transactions were inserted into the mempool.
     tracing::info!("calling GetMempoolStream gRPC to fetch transactions...");
```
Comment (teor2345) [inline zebrad/tests/common/lightwalletd/send_transaction_test.rs:239]: Optional: Does updating the service file also allow the `GetMempoolStream` check to be re-enabled?

File: zebrad/tests/common/lightwalletd/proto/service.proto [hunk 3]
```diff
@@ -36,7 +36,7 @@ message TxFilter {
 // by GetMempoolStream(), the latest block height.
 message RawTransaction {
```
Comment (teor2345) [inline zebrad/tests/common/lightwalletd/proto/service.proto:37]: Updating this file seems like something that's easy to forget. Is there somewhere we can document that it needs to be done?

**Review by teor2345 — DISMISSED** [review]
Thank you for this fix. Is there a way to avoid this mistake next time we update `lightwalletd` forks?

File: zebrad/tests/common/lightwalletd/proto/service.proto (hunk 3 above)
Comment (arya2) [reply zebrad/tests/common/lightwalletd/proto/service.proto:37]: Added a comment in https://github.com/ZcashFoundation/zebra/pull/7644/commits/b4e6761673620a5720f0bdcbe9b2ae27944cd43b.

File: zebrad/tests/common/lightwalletd/send_transaction_test.rs (hunk 1 above)
Comment (arya2) [reply zebrad/tests/common/lightwalletd/send_transaction_test.rs:152]: I knew I was forgetting something.

File: zebrad/tests/common/lightwalletd/send_transaction_test.rs (hunk 2 above)
Comment (arya2) [reply zebrad/tests/common/lightwalletd/send_transaction_test.rs:239]: No, but the other assertion failed and had the message, "developers: should fail if `get_mempool_stream` start working": 

https://github.com/ZcashFoundation/zebra/pull/7600/files#diff-91452b1b52c32dc72de4dd903dd355f10ffc99e30d7217df595bb0177f88bd27L234-L237

**Review by teor2345 — APPROVED** [review]
This code looks good to me but CI seems to be having issues.

**Review by teor2345 — CHANGES_REQUESTED** [review]
The test that this PR changes is still failing in CI, maybe we need to disable that part of the test:
https://github.com/ZcashFoundation/zebra/actions/runs/6433900141/job/17472517050?pr=7644#step:9:416

File: zebrad/tests/common/lightwalletd/send_transaction_test.rs [hunk 4]
```diff
@@ -148,8 +147,21 @@ pub async fn run() -> Result<()> {
 
     let mut rpc_client = connect_to_lightwalletd(lightwalletd_rpc_port).await?;
 
-    // To avoid filling the mempool queue, limit the transactions to be sent to the RPC and mempool queue limits
-    transactions.truncate(max_sent_transactions());
+    // Call GetMempoolTx so lightwalletd caches the empty mempool state.
+    // This is a workaround for a bug where lightwalletd will skip calling `get_raw_transaction`
+    // the first time GetMempoolTx is called because it replaces the cache early and only calls the
+    // RPC method for transaction ids that are missing in the old cache as keys.
+    //
```
Comment (arya2) [inline zebrad/tests/common/lightwalletd/send_transaction_test.rs:155]:
```suggestion
    // <https://github.com/zcash/lightwalletd/blob/master/frontend/service.go#L495-L502>
    //
```

**Review by teor2345 — APPROVED** [review]
This seems to pass CI now
