### PR TITLE
fix(install): Downgrade `owo-colors` from 3.6.0 to 3.5.0

### LINKED ISSUE #6197: Consider downgrading `owo-colors` crate?
When i follow[ this instructions ](https://zebra.zfnd.org/user/lightwalletd.html#download-and-build-zebra)to install zebra i get the following warning:

```
$ cargo install --locked --git https://github.com/ZcashFoundation/zebra zebrad
    Updating git repository `https://github.com/ZcashFoundation/zebra`
  Installing zebrad v1.0.0-rc.4 (https://github.com/ZcashFoundation/zebra#4daedbc7)
    Updating crates.io index
warning: package `owo-colors v3.6.0` in Cargo.lock is yanked in registry `crates-io`, consider running without --locked
...
```

Version seems to be yanked by the author: https://crates.io/crates/owo-colors/versions

Should we downgrade to `3.5.0` ?

### PR DESCRIPTION
**Pull request by oxarbitrage**
## Motivation

`owo-colors` v 0.3.6 is yanked. This PR downgrade to version 0.3.5. Close https://github.com/ZcashFoundation/zebra/issues/6197

## Solution

Downgrade.

Test the warning is gone with:

```
cargo install --locked --features getblocktemplate-rpcs --git https://github.com/ZcashFoundation/zebra --branch issue6197 zebrad
```

Dependabot will try to update, we will deny, dependabot will leave us alone until a greater version is released.

The change in `command.rs` is needed to fix a clippy lint that was not happening when `owo-colors` was at 0.3.6.

## Review

Anyone can review.

### Reviewer Checklist

  - [ ] Will the PR name make sense to users?
    - [ ] Does it need extra CHANGELOG info? (new features, breaking changes, large changes)
  - [ ] Are the PR labels correct?
  - [ ] Does the code do what the ticket and PR says?
    - [ ] Does it change concurrent code, unsafe code, or consensus rules?
  - [ ] How do you know it works? Does it have tests?

### CODE REVIEW

File: zebra-test/tests/command.rs [hunk 1]
```diff
@@ -505,7 +505,7 @@ fn failure_regex_matches_stdout_failure_message_wait_for_output() {
 
     // Wait with output should read all unread output to generate the error context,
     // or the output should be read on drop.
-    child.wait_with_output().unwrap_err();
+    let _ = child.wait_with_output().unwrap_err();
```
Comment (teor2345) [inline zebra-test/tests/command.rs]: Just curious, what does this fix? Is it a warning of some kind?

File: deny.toml [hunk 2]
```diff
@@ -44,8 +44,8 @@ skip-tree = [
     # wait for curve25519-dalek to upgrade
     { name = "digest", version = "=0.9.0" },
 
-    # wait for primitive-types to upgrade
-    { name = "proc-macro-crate", version = "=0.1.5" },
+    # wait for jsonrpc-http-server to upgrade tokio-util, parking_lot
```
Comment (teor2345) [inline deny.toml]: I tweaked this a bit to list the dependencies that are actually causing the problems here. It's tricky to work that out because the dependency trees are complicated.

I also removed some exceptions that other upgrades had made obsolete.

**Review by teor2345 — CHANGES_REQUESTED** [review]
I'm surprised to see such a large change to Cargo.lock. How did you generate it?

We're keeping some packages to specific versions, and there are some cryptographic package changes in here. So I think we might need to check each dependency change in detail to make sure they are correct. Can you split those changes into another PR, and just to the owo-colors change in this one?

File: zebra-test/tests/command.rs (hunk 1 above)
Comment (oxarbitrage) [reply zebra-test/tests/command.rs]: It is a warning.

**Comment by oxarbitrage** [comment]
> I'm surprised to see such a large change to Cargo.lock. How did you generate it?

I just downgraded `owo-colors` and build, Cargo.lock is auto generated.

> We're keeping some packages to specific versions, and there are some cryptographic package changes in here. So I think we might need to check each dependency change in detail to make sure they are correct. Can you split those changes into another PR, and just to the owo-colors change in this one?

I am not understanding, changes here are just to make the downgrade work. I can't see unrelated changes. Deny.toml changes are done to make the CI pass.

File: zebra-test/tests/command.rs (hunk 1 above)
Comment (teor2345) [reply zebra-test/tests/command.rs]: What was the warning?

**Comment by teor2345** [comment]
> > I'm surprised to see such a large change to Cargo.lock. How did you generate it?
> 
> I just downgraded `owo-colors` and build, Cargo.lock is auto generated.

Cargo.lock is auto-generated from the Cargo.toml files and the previous Cargo.lock. It's easy to accidentally change it a lot. It can happen if you delete the Cargo.lock, replace it with an older version, or use a command like `cargo update` to update all the dependency versions.

> > We're keeping some packages to specific versions, and there are some cryptographic package changes in here. So I think we might need to check each dependency change in detail to make sure they are correct. Can you split those changes into another PR, and just to the owo-colors change in this one?
> 
> I am not understanding, changes here are just to make the downgrade work. I can't see unrelated changes. Deny.toml changes are done to make the CI pass.

There are 700 lines of changes in Cargo.lock. That's a very big change.

For example, the cryptographic dependency `bls12_381` should not change in a PR about a terminal colour dependency:
https://github.com/ZcashFoundation/zebra/pull/6203/files#diff-13ee4b2252c9e516a0547f2891aa2105c3ca71c6d7a1e682c69be97998dfc87eR484-R488

Screenshot 2023-02-23 at 07 21 24

**Comment by teor2345** [comment]
Happy to jump on a call if that would help?

**Comment by oxarbitrage** [comment]
> Happy to jump on a call if that would help?

Sorry, it seems i screwed up somewhere, my apologies for not checking it carefully.

It seems only a downgrade in the Cargo.toml is needed, no changes were done to the lock after built. The [warning](https://github.com/ZcashFoundation/zebra/pull/6203#discussion_r1114958300) is gone and no need to change deny.toml.

**Comment by oxarbitrage** [comment]
Hmm, unfortunatly the warning is still there, so it needs further changes.
```
$ cargo install --locked --features getblocktemplate-rpcs --git https://github.com/ZcashFoundation/zebra --branch issue6197 zebrad
    Updating git repository `https://github.com/ZcashFoundation/zebra`
  Installing zebrad v1.0.0-rc.4 (https://github.com/ZcashFoundation/zebra?branch=issue6197#35199d2e)
    Updating crates.io index
warning: package `owo-colors v3.6.0` in Cargo.lock is yanked in registry `crates-io`, consider running without --locked
```

**Comment by oxarbitrage** [comment]
Trying updated Cargo.lock after `cargo update -p owo-color` in https://github.com/ZcashFoundation/zebra/pull/6203/commits/4a80946f7012884f219eb076f3c9689b91fbd9a4

**Review by teor2345 — APPROVED** [review]
Thanks, that looks a lot better!
