### PR TITLE
Release Blocker: Stop trying to verify coinbase inputs using the script verifier

### LINKED ISSUE #2401: "unexpected coinbase input" error stops Zebra syncing past Canopy checkpoint
## Description

When Zebra tries to validate any block using the `BlockVerifier` and `transaction::Verifier`, validation fails with an "unexpected coinbase input" error.

### Steps to Reproduce

I tried launching a new `zebrad` sync, and starting a sync with cached state, using the command:
```sh
zebrad start
```

### Expected Behaviour

I expected the chain to sync to the current best tip.

### Actual Behaviour

After Zebra stops using the `CheckpointVerifier`, all blocks are considered invalid.

Syncing stops at:
* Mainnet height 1_046_449
* Testnet height 1_028_800

Or a later height if a working Zebra version cached blocks past the mandatory checkpoint.
(I assume configuring `checkpoint_sync` would also allow Zebra to sync further.)

### Zebra Logs

Mainnet:
<details>
```
Jun 28 15:59:23.641  WARN {zebrad="ffea09f" net="Main"}:sync: zebrad::components::sync: error downloading and verifying block e=Block(Transaction(InternalDowncastError("downcast to redjubjub:
:Error failed, original error: \"unexpected coinbase input\"")))
Jun 28 15:59:23.641  INFO {zebrad="ffea09f" net="Main"}:sync: zebrad::components::sync: waiting to restart sync timeout=61s
Jun 28 16:00:24.642  INFO {zebrad="ffea09f" net="Main"}:sync: zebrad::components::sync: starting sync, obtaining new tips
Jun 28 16:00:24.643  INFO {zebrad="ffea09f" net="Main"}:sync:obtain_tips:state: zebra_state::util: created block locator tip_height=Height(1046449) min_locator_height=1046350 locators=[Height
(1046449), Height(1046448), Height(1046447), Height(1046445), Height(1046441), Height(1046433), Height(1046417), Height(1046385), Height(1046350)]
Jun 28 16:00:24.643  INFO {zebrad="ffea09f" net="Main"}:sync:obtain_tips: zebrad::components::sync: trying to obtain new chain tips tip=block::Hash("00000000027e574556fb054084b677946515ee2804
5edf4a67fb129b06814b97")                                                                                                                                                                       Jun 28 16:00:30.844  WARN {zebrad="ffea09f" net="Main"}:sync:obtain_tips: zebra_consensus::transaction: ignoring binding_sig_error=Invalid signature.
...
Jun 28 16:00:33.429  WARN {zebrad="ffea09f" net="Main"}:sync:obtain_tips: zebra_consensus::transaction: ignoring binding_sig_error=Invalid signature.
Jun 28 16:00:33.498  WARN {zebrad="ffea09f" net="Main"}:sync: zebrad::components::sync: error downloading and verifying block e=Block(Transaction(InternalDowncastError("downcast to redjubjub::Error failed, original error: \"unexpected coinbase input\"")))
```
</details>

Testnet:
<details>
```
Jun 28 15:59:48.296  WARN {zebrad="ffea09f" net="Test"}:sync: zebrad::components::sync: error downloading and verifying block e=Block(Transaction(InternalDowncastError("downcast to redjubjub::Error failed, original error: \"unexpected coinbase input\"")))
Jun 28 15:59:48.296  INFO {zebrad="ffea09f" net="Test"}:sync: zebrad::components::sync: waiting to restart sync timeout=61s
Jun 28 16:00:09.449  INFO {zebrad="ffea09f" net="Test"}:crawl_and_dial{crawl_new_peer_interval=60s}: zebra_network::peer_set::candidate_set: timeout waiting for the peer service to become ready
Jun 28 16:00:49.298  INFO {zebrad="ffea09f" net="Test"}:sync: zebrad::components::sync: starting sync, obtaining new tips
Jun 28 16:00:49.298  INFO {zebrad="ffea09f" net="Test"}:sync:obtain_tips:state: zebra_state::util: created block locator tip_height=Height(1028800) min_locator_height=1028701 locators=[Height(1028800), Height(1028799), Height(1028798), Height(1028796), Height(1028792), Height(1028784), Height(1028768), Height(1028736), Height(1028701)]
Jun 28 16:00:49.298  INFO {zebrad="ffea09f" net="Test"}:sync:obtain_tips: zebrad::components::sync: trying to obtain new chain tips tip=block::Hash("017541e9a4a46c2d37f804dd1edde16da3ec9ecfd22361b02525765e1deffe66")
Jun 28 16:00:55.309  INFO {zebrad="ffea09f" net="Test"}:sync:obtain_tips: zebra_network::peer_set::set: network request with no ready peers: finding more peers, waiting for 7 peers to answer requests address_metrics=AddressMetrics { responded: 7, never_attempted_gossiped: 0, never_attempted_alternate: 0, failed: 907, attempt_pending: 49, recently_live: 7, recently_stopped_responding: 0 }
Jun 28 16:01:09.392  INFO {zebrad="ffea09f" net="Test"}:crawl_and_dial{crawl_new_peer_interval=60s}: zebra_network::peer_set::candidate_set: timeout waiting for the peer service to become ready
Jun 28 16:01:24.539  WARN {zebrad="ffea09f" net="Test"}:sync: zebrad::components::sync: error downloading and verifying block e=Block(Transaction(InternalDowncastError("downcast to redjubjub::Error failed, original error: \"unexpected coinbase input\"")))
```
</details>

### Zebra Version

commit ffea09f: PR #2395 + main branch commits + zebrad 1.0.0-alpha.11

### Operating System

`Linux ... 5.4.96 #1-NixOS SMP Sun Feb 7 14:35:50 UTC 2021 x86_64 GNU/Linux`

### PR DESCRIPTION
**Pull request by teor2345**
## Motivation

Fixes #2401, a `transaction::Verifier` bug introduced by PR #2382.

This bug stops Zebra syncing after the mandatory Canopy checkpoint, as soon as the `transaction::Verifier` starts being used.

### Specifications

Unfortunately, the Zcash specification doesn't cover all the validation rules for coinbase inputs and outputs.

## Solution

- Stop passing coinbase inputs to the script verifier
- Add tests with transparent coinbase outputs

## Review

@jvff can review this PR, it's a high priority, because it stops syncing. (And makes other code hard to test.)

### Reviewer Checklist

  - [ ] Code implements Specs and Designs
  - [ ] Tests for Expected Behaviour
  - [ ] Tests for Errors

## Follow Up Work

We'll do shielded coinbase tests as part of the shielded coinbase ticket.

### CODE REVIEW

File: zebra-consensus/src/transaction/tests.rs [hunk 1]
```diff
@@ -294,6 +294,50 @@ async fn v4_transaction_with_transparent_transfer_is_accepted() {
...
+        lock_time: LockTime::Height(block::Height(0)),
+        expiry_height: transaction_block_height,
+        joinsplit_data: None,
+        sapling_shielded_data: None,
+    };
+
+    let transaction_hash = transaction.hash();
+
+    let state_service =
+        service_fn(|_| async { unreachable!("State service should not be called") });
```
Comment (jvff) [inline zebra-consensus/src/transaction/tests.rs:325]: Random thought: I think I've seen this pattern a few times. I know it's a one-liner but would it make sense to move it to something like `zebra_test::unreachable_service()`?

File: zebra-consensus/src/transaction/tests.rs [hunk 2]
```diff
@@ -294,6 +294,50 @@ async fn v4_transaction_with_transparent_transfer_is_accepted() {
...
+    let script_verifier = script::Verifier::new(state_service);
+    let verifier = Verifier::new(network, script_verifier);
+
+    let result = verifier
+        .oneshot(Request::Block {
+            transaction: Arc::new(transaction),
+            known_utxos: Arc::new(known_utxos),
```
Comment (jvff) [inline zebra-consensus/src/transaction/tests.rs]: Nit: I'd remove the `known_utxos` variable to avoid the impression that there are any known UTXOs in the test.

```suggestion
            known_utxos: Arc::new(HashMap::new()),
```

File: zebra-consensus/src/transaction/tests.rs [hunk 3]
```diff
@@ -397,6 +441,55 @@ async fn v5_transaction_with_transparent_transfer_is_accepted() {
     assert_eq!(result, Ok(transaction_hash));
 }
 
+/// Test if V5 coinbase transaction is accepted.
+#[tokio::test]
+// TODO: Remove `should_panic` once the NU5 activation heights for testnet and mainnet have been
+// defined.
+#[should_panic]
```
Comment (jvff) [inline zebra-consensus/src/transaction/tests.rs:447]: Minor: Maybe also add this to #1841?

**Review by jvff — DISMISSED** [review]
Looks good! I added some comments, but they're all optional.

File: zebra-consensus/src/transaction/tests.rs (hunk 1 above)
Comment (teor2345) [reply zebra-consensus/src/transaction/tests.rs:325]: Feel free to open a ticket - or to make that function in the next PR that uses it.

Getting the async and generics right might be hard, so we shouldn't spend too much time on it right now.

File: zebra-consensus/src/transaction/tests.rs (hunk 3 above)
Comment (teor2345) [reply zebra-consensus/src/transaction/tests.rs:447]: Done!

I just noticed a bug here: these functions should all use `Testnet`, because it will have an activation height first.

(Ideally they should use both networks, but that's a larger change.)

File: zebra-consensus/src/transaction/tests.rs (hunk 2 above)
Comment (teor2345) [reply zebra-consensus/src/transaction/tests.rs]: Fixed in 3ee905f8

File: zebra-consensus/src/transaction/tests.rs (hunk 3 above)
Comment (teor2345) [reply zebra-consensus/src/transaction/tests.rs:447]: Bug fixed in 09b815cf, also I updated the ticket, and added "any other should_panic" tests.

**Comment by teor2345** [comment]
This is ready for another review.

But since all the changes were optional, I can also merge once CI passes.
