### PR TITLE
zebra-rpc: Correctly map JSON-RPC to/from 2.0

### LINKED ISSUE #9211: feature: restore JSON-RPC 1.0 support
### Motivation

Zebra used to support both JSON-RPC 1.0 or 2.0 in respect to the `jsonrpc` field (non-existent in 1.0, mandatory with the `2.0` value in 2.0).

However, after the migration to jsonrpsee, this does not work anymore, and tools like `zcash-cli` stopped working with

```
{"jsonrpc":"2.0","id":"curltest","error":{"code":-32600,"message":"Invalid request"}}
```

We might want to restore that support. We [already replace](https://github.com/ZcashFoundation/zebra/blob/fcf5565b2ee981f0c37bf9a9a9910d5bb7d03dbe/zebra-rpc/src/server/http_request_compatibility.rs#L218) requests with `jsonrpc = "1.0"` (which is nonsensical, since the field did not exist in 1.0, but some tools like lightwalletd use it) to `jsonrpc = "2.0"` using a middleware; it might be simple to make it _add_  `jsonrpc = "2.0"`  if the `jsonrpc` field is missing.

### Specifications

_No response_

### Complex Code or Requirements

_No response_

### Testing

_No response_

### Related Work

_No response_

### PR DESCRIPTION
**Pull request by str4d**
## Motivation

The existing code was only handling the `lightwalletd` client format which includes a `"jsonrpc": "1.0"` entry, and it was returning responses as JSON-RPC 2.0 regardless of what the client expected.

## Solution

Ports the fix from Zallet: https://github.com/zcash/wallet/commit/00c2349d1fbc445b5aefb01dafe4ae5cae645077

Closes #9211.

### Tests

`zcash-cli` should now work with `zebrad`; I tested this patch with Zallet's JSON-RPC which is based on `zebra-rpc`. But someone should test that this does indeed cause `zebrad` to work with `zcash-cli`, and that it also still works with `lightwalletd`.

### Follow-up Work

I did not exhaustively check that the detection and mapping logic for `bitcoind`-style JSON-RPC or `lightwalletd`-style JSON-RPC was comprehensive; I focused on the main breaking differences I knew of between them. It's sufficient for `zcash-cli` and should still work with `lightwalletd`, but there might be further bugs that need addressing in subsequent PRs.

### PR Author's Checklist

- [x] The PR name will make sense to users.
- [ ] The PR provides a CHANGELOG summary.
- [ ] The solution is tested.
- [ ] The documentation is up to date.
- [ ] The PR has a priority label.

### PR Reviewer's Checklist

- [ ] The PR Author's checklist is complete.
- [ ] The PR resolves the issue.

### CODE REVIEW

File: zebra-rpc/src/server/http_request_compatibility.rs [hunk 1]
```diff
@@ -118,24 +119,55 @@ impl<S> HttpRequestMiddleware<S> {
...
+            .to_bytes();
+        let (version, bytes) =
+            if let Ok(request) = serde_json::from_slice::<'_, JsonRpcRequest>(bytes.as_ref()) {
+                let version = request.version();
+                if matches!(version, JsonRpcVersion::Unknown) {
+                    (version, bytes)
+                } else {
+                    (
+                        version,
+                        serde_json::to_vec(&request.to_2()).expect("valid").into(),
```
Comment (arya2) [inline zebra-rpc/src/server/http_request_compatibility.rs]:
```suggestion
                        serde_json::to_vec(&request.into_2()).expect("valid").into(),
```

File: zebra-rpc/src/server/http_request_compatibility.rs [hunk 2]
```diff
@@ -118,24 +119,55 @@ impl<S> HttpRequestMiddleware<S> {
...
+    ) -> HttpResponse<HttpBody> {
+        let (parts, body) = response.into_parts();
+        let bytes = body
+            .collect()
+            .await
+            .expect("Failed to collect body data")
+            .to_bytes();
+        let bytes =
+            if let Ok(response) = serde_json::from_slice::<'_, JsonRpcResponse>(bytes.as_ref()) {
+                serde_json::to_vec(&response.to_version(version))
```
Comment (arya2) [inline zebra-rpc/src/server/http_request_compatibility.rs]:
```suggestion
                serde_json::to_vec(&response.into_version(version))
```

File: zebra-rpc/src/server/http_request_compatibility.rs [hunk 3]
```diff
@@ -203,25 +235,97 @@ where
...
+                ),
+            ) => JsonRpcVersion::TwoPointZero,
+            (Some("1.0"), Some(_), Some(_)) => JsonRpcVersion::Lightwalletd,
+            (None, Some(_), Some(_)) => JsonRpcVersion::Bitcoind,
+            _ => JsonRpcVersion::Unknown,
+        }
+    }
 
-            let request = HttpRequest::from_parts(parts, body);
+    fn to_2(mut self) -> Self {
```
Comment (arya2) [inline zebra-rpc/src/server/http_request_compatibility.rs]:
```suggestion
    fn into_2(mut self) -> Self {
```

File: zebra-rpc/src/server/http_request_compatibility.rs [hunk 4]
```diff
@@ -203,25 +235,97 @@ where
...
+    #[serde(skip_serializing_if = "Option::is_none")]
+    result: Option<serde_json::Value>,
+    #[serde(skip_serializing_if = "Option::is_none")]
+    error: Option<serde_json::Value>,
+    id: serde_json::Value,
+}
 
-            service.call(request).await.map_err(Into::into)
+impl JsonRpcResponse {
+    fn to_version(mut self, version: JsonRpcVersion) -> Self {
```
Comment (arya2) [inline zebra-rpc/src/server/http_request_compatibility.rs]:
```suggestion
    fn into_version(mut self, version: JsonRpcVersion) -> Self {
```

File: zebra-rpc/src/server/http_request_compatibility.rs [hunk 5]
```diff
@@ -203,25 +235,97 @@ where
...
+                self.error = self.error.or(Some(serde_json::Value::Null));
+            }
+            JsonRpcVersion::Lightwalletd => {
+                self.jsonrpc = Some("1.0".into());
+                self.result = self.result.or(Some(serde_json::Value::Null));
+                self.error = self.error.or(Some(serde_json::Value::Null));
+            }
+            JsonRpcVersion::TwoPointZero => {
+                // `jsonrpsee` should be returning valid JSON-RPC 2.0 responses.
+                assert_eq!(self.jsonrpc.as_deref(), Some("2.0"));
```
Comment (arya2) [inline zebra-rpc/src/server/http_request_compatibility.rs:326]:
```suggestion
                assert_eq!(self.jsonrpc.as_deref(), Some("2.0"));
                // Correct `submitblock` responses
                if self.result.is_none() && self.error.is_none() {
                    self.result = self.result.or(Some(serde_json::Value::Null));
                }
```

**Review by arya2 — COMMENTED** [review]
Thank you!!

I left some suggestions to resolve lints and workaround a deserialization bug.

**Comment by str4d** [comment]
[Force-pushed](https://github.com/ZcashFoundation/zebra/compare/50a003aa778a7477f3624a45b8698097e782f4c9..0abf9e7ee204d206b227bce9a68ab1ba2a2364bc) to resolve comments.

**Review by arya2 — DISMISSED** [review]

**Comment by mpguerra** [comment]
@mergify requeue

**Comment by mpguerra** [comment]
@mergify requeue

**Comment by mpguerra** [comment]
@mergify requeue

File: zebra-rpc/src/server/http_request_compatibility.rs [hunk 6]
```diff
@@ -203,25 +235,103 @@ where
...
+/// A version-agnostic JSON-RPC response.
+#[derive(Debug, Deserialize, Serialize)]
+struct JsonRpcResponse {
+    #[serde(skip_serializing_if = "Option::is_none")]
+    jsonrpc: Option<String>,
+    #[serde(skip_serializing_if = "Option::is_none")]
+    result: Option<serde_json::Value>,
+    #[serde(skip_serializing_if = "Option::is_none")]
+    error: Option<serde_json::Value>,
+    id: serde_json::Value,
```
Comment (arya2) [inline zebra-rpc/src/server/http_request_compatibility.rs]: The reordered fields are causing [a snapshot test to fail](https://github.com/ZcashFoundation/zebra/actions/runs/13261383302/job/37019097980#step:15:814), preserving the previous order or updating the snapshots should fix it.

```suggestion
    id: serde_json::Value,
    #[serde(skip_serializing_if = "Option::is_none")]
    result: Option<serde_json::Value>,
    #[serde(skip_serializing_if = "Option::is_none")]
    error: Option<serde_json::Value>,
```

**Review by oxarbitrage — APPROVED** [review]

**Comment by arya2** [comment]
@mergifyio refresh

**Comment by arya2** [comment]
@mergifyio refresh

**Comment by arya2** [comment]
@mergifyio update

**Comment by arya2** [comment]
@mergifyio refresh
