### PR TITLE
fix(sync): Fix block propagation in regtest

### LINKED ISSUE #10332: bug(network): Zebra broadcasting in regtest mode
From discord, @str4d :

> Main thing I'm now running into is that I can't get zebra nodes to reliably broadcast regtest blocks between themselves as part of cache preparation. cc @arya if you have ideas?
>
> Oh hmm, maybe I need to connect them directly, not in a star topology. That would explain why the first node (currently the centre of the star) is able to broadcast fine, but the second node onwards isn't working because it only broadcasts to the first node, and the first node does not rebroadcast automatically (whereas zcashd did so)
>
> Hmm nope, trying to connect every node (8 of them) to the subset that are mining nodes (4 of them) runs into duplicate IP issues, and the nodes don't connect at all. If instead I connect the nodes in a line, then everything connects fine but block broadcasting never happens beyond a single hop, which is bad.

https://discord.com/channels/809218587167293450/809250845396041738/1473498714881527971

### PR DESCRIPTION
**Pull request by oxarbitrage**
## Motivation

In regtest, blocks mined on one node failed to propagate across multi-hop topologies (`A → B → C`). Node B would receive a block from A but not relay it to C, causing integration tests using `generate(N)` with N > 1 to time out during `sync_all()`.

This was caused by three issues:

- Syncer disabled in regtest (`start.rs`): The syncer task was replaced with `std::future::pending()`, leaving only gossip for propagation. Gossip only advertises the latest tip hash, so rapidly mined blocks caused intermediate blocks to be missed with no recovery path.
- `obtain_tips()` discarding small responses (`sync.rs`): A workaround for a zcashd quirk strips the last hash from `FindBlocks` responses. For short chains this left too few hashes, causing the response to be discarded and preventing recovery of the final block.
- SyncStatus::is_close_to_tip() always false (`sync/status.rs`): Gossip waits for `wait_until_close_to_tip()` before relaying blocks. On fresh regtest nodes this condition never became true, effectively blocking relay.

## Solution

- `start.rs`: Re-enable the syncer in regtest (genesis still committed locally).
- `sync.rs`:
  - Reduced delay in regtest with `REGTEST_SYNC_RESTART_DELAY` to 2s
  - Skip the zcashd last-hash stripping in regtest.
- `sync/status.rs`: Add `SyncStatus::new_for_network()`. In regtest, `is_close_to_tip()` returns true immediately so gossip can relay blocks.

### Tests

Added `regtest_block_relay.py` to the integration tests, reproducing the scenario from #10332: three nodes in a linear `A -- B -- C` topology, mining on A and verifying propagation to C.

Closes #10332.

### AI Disclosure

- [ ] No AI tools were used in this PR
- [x] AI tools were used: Claude for text and some code

### PR Checklist

- [ ] The PR name is suitable for the release notes.
- [ ] The PR follows the [contribution guidelines](https://github.com/ZcashFoundation/zebra/blob/main/CONTRIBUTING.md).
- [ ] This change was discussed in an issue or with the team beforehand.
- [ ] The solution is tested.
- [ ] The documentation and changelogs are up to date.

### CODE REVIEW

File: zebrad/src/components/sync.rs [hunk 1]
```diff
@@ -739,13 +753,28 @@ where
...
+                    // blocks to sync (e.g. 2 new blocks), where stripping the
+                    // last hash leaves only 1 unknown hash and rchunks_exact(2)
+                    // would discard the entire response.
+                    let hashes = if self.is_regtest {
+                        hashes.as_slice()
+                    } else {
+                        match hashes.as_slice() {
+                            [] => continue,
+                            [rest @ .., _last] => rest,
+                        }
```
Comment (arya2) [inline zebrad/src/components/sync.rs:773]: Could use an if guard in the match statement instead of a separate if statement

**Review by arya2 — APPROVED** [review]
Looks good!
