### PR TITLE
fix: Resist CheckpointVerifier memory DoS attacks

### LINKED ISSUE #628: Limit the number of queued blocks at each height
To avoid a memory DoS, we want to limit the number of queued blocks at each height:
https://mobile.twitter.com/_prestwich/status/1281325791297470464

- [x] Any additional blocks should fail validation immediately.

Assuming we checkpoint every 500 blocks, the maximum memory usage for a checkpoint range is:
* 1 block per height: `1 * 2 MB * 500 = 1 GB`
* 2 blocks per height: `2 * 2 MB * 500 = 2 GB`
* 3 blocks per height: `3 * 2 MB * 500 = 3 GB`

When we're close to having a full range, the queue might contain some blocks from the next range as well. So the actual usage is slightly higher.

On my machine, `zcashd` uses approximately 1-3 GB, so we should try to restrict checkpoint memory usage to 1-2 GB. 

We could remove the `QueuedBlockList` vector, and just accept 1 block per height. But if we got a bad block, we would have to wait for the sync service to re-fetch the correct block.

To avoid quadratic behaviour on multiple bad blocks, we should:
- [ ] ~discard all the unverified blocks in the interval~ - not implemented, because rejecting blocks lower than the bad block makes other attacks possible

This change resists an attack where a single bad peer feeds us multiple bad blocks, then we reject a bad block, restart the sync service, wait for downloads, re-fetch a good block, then find another bad block lower down...

Let's also keep up to 2 blocks per height, so we can efficiently reject blocks from a single bad peer:
- [x] 2 blocks per height: `2 * 2 MB * 500 = 2 GB`

Since `QueuedBlockList` is `Vec<Arc<Block>>`, and `Block` is `{header: BlockHeader, transactions: Vec<Transactions>}`, the actual size of empty allocations is only ~1.4 kB for the block header and a few pointers.

So we don't need to carefully manage vector capacity with each `push`. We can just:
- [x] initialise vectors `with_capacity(2)` - the maximum number of blocks at each height

We won't need to use `reserve_exact` or `shrink_to_fit`. (And in any case, we `drain` vectors during validation, and only re-queue valid blocks.)

### PR DESCRIPTION
**Pull request by teor2345**
Allow a maximum of 4 queued blocks (`fanout`) at each height, as a tradeoff between
efficient bad block rejection, and memory usage.

Closes #628.

### CODE REVIEW

**Comment by yaahc** [comment]
would we want to implement some sort of LRU cache policy or would we want to just reject all blocks after the second?

**Comment by teor2345** [comment]
> would we want to implement some sort of LRU cache policy or would we want to just reject all blocks after the second?

To verify up to a checkpoint, we need a valid block at each height below that checkpoint.

If all our peers are well-behaved, and our checkpoint list is a few hours behind the chain tip, we expect to only have one block at each height. (The valid block from the main chain.)

If we connect to bad peers, a generic LRU cache would allow those peers to flood us with arbitrary blocks, and make us drop all the valid blocks from our cache. (Assuming we asked the bad peers for the bad hashes and bad blocks.)

With the design in this PR, the bad peers have to win a race with the good peers three times in a row:
* a bad list of hashes
* a bad block at a height `H`
* another bad block at height `H`

That seems unlikely, as long as the number of bad peers is small.

(It might be possible for bad peers to provide multiple blocks at the same height, for arbitrary hashes. But it would be hard for them to win all the time, across an entire checkpoint interval.)

We should probably also limit the total number of blocks in the queue, I opened #640 for that fix.

File: zebra-consensus/src/checkpoint.rs [hunk 1]
```diff
@@ -56,10 +56,23 @@ struct QueuedBlock {
...
 
+/// The maximum number of queued blocks at any one height.
+///
+/// This value is a tradeoff between:
+/// - rejecting bad blocks: higher is more efficient, and
+/// - avoiding a memory DoS: lower means less memory usage.
+///
+/// If we use a checkpoint interval of 500 blocks, our approximate queued block
+/// memory usage is:
+/// `500 blocks * 2 MB max per block * 2 blocks per height = 2 GB`
```
Comment (hdevalence) [inline zebra-consensus/src/checkpoint.rs]: Although this is an upper bound on our memory use, I don't think that this is a reasonable approximation for queued block memory usage, because it assumes that we only communicate with malicious peers who feed us giant blocks.

File: zebra-consensus/src/checkpoint.rs [hunk 2]
```diff
@@ -56,10 +56,23 @@ struct QueuedBlock {
...
+const MAX_QUEUED_BLOCKS_PER_HEIGHT: usize = 2;
```
Comment (hdevalence) [inline zebra-consensus/src/checkpoint.rs]: I'm not sure it makes sense for this parameter to be different from the fanout parameter that we use in the syncer.  When we perform fanout to try to extend chain tips, we admit the possibility of up to `F` different tips.  So if there should be a limit here, it seems like the limit should be `F`, since that's the number of chain tips we're potentially pursuing in parallel.

**Comment by teor2345** [comment]
I expect a clippy failure is in unrelated code:

```
error: match expression looks like `matches!` macro
```

Fixed in #657.

File: zebra-consensus/src/checkpoint.rs (hunk 1 above)
Comment (teor2345) [reply zebra-consensus/src/checkpoint.rs]: I deleted this comment in 65ee727c8c3f87dc2ef539279684a0abb2d56dc8.

When I create the checkpoint list, I'll update that comment for block-size-based checkpoint intervals.

File: zebra-consensus/src/checkpoint.rs (hunk 2 above)
Comment (teor2345) [reply zebra-consensus/src/checkpoint.rs]: I made the fanout and blocks per height equal in 65ee727c8c3f87dc2ef539279684a0abb2d56dc8.

File: zebra-consensus/src/checkpoint.rs [hunk 3]
```diff
@@ -327,6 +328,9 @@ impl CheckpointVerifier {
         // Add the block to the list of queued blocks at this height
         let hash = block.as_ref().into();
         let new_qblock = QueuedBlock { block, hash, tx };
+        // We avoid allocating extra space, because multiple blocks are rare,
+        // and block headers are large.
```
Comment (hdevalence) [inline zebra-consensus/src/checkpoint.rs]: I don't think this changes whether it's a good idea to use `with_capacity(1)`, but since `block` is an `Arc<Block>`, it's just the size of a single pointer, not the size of a full block header.

File: zebrad/src/commands/start/sync.rs [hunk 4]
```diff
@@ -38,7 +39,9 @@ where
             verifier,
             retry_peer_set,
             block_requests: FuturesUnordered::new(),
-            fanout: 4,
+            // Limit the fanout to the number of chains that the
+            // CheckpointVerifier can handle
+            fanout: checkpoint::MAX_QUEUED_BLOCKS_PER_HEIGHT,
```
Comment (hdevalence) [inline zebrad/src/commands/start/sync.rs:44]: :+1:

**Review by hdevalence — DISMISSED** [review]
LGTM!

File: zebra-consensus/src/checkpoint.rs (hunk 3 above)
Comment (teor2345) [reply zebra-consensus/src/checkpoint.rs]: You're right, I was still thinking of Blocks.

I'll just revert that part of the change then, there's no need for us to worry about 8 bytes vs 32 bytes. We might as well just allocate the 32 bytes upfront. (And that will reduce memory fragmentation.)

Comment (hdevalence) [reply zebra-consensus/src/checkpoint.rs]: Sorry I was unclear, I think it's still a good idea to use `with_capacity(1)` -- it's the common case and it means we'll get exactly the right size in the common case.

Comment (teor2345) [reply zebra-consensus/src/checkpoint.rs]: Done in 095a37f9462eb185fb74c6a76457949d08606bde

Comment (teor2345) [reply zebra-consensus/src/checkpoint.rs]: Ah right now I understand. I fixed it properly in 002e148616e5d75db77d01b962371483b3129537.

Comment (teor2345) [reply zebra-consensus/src/checkpoint.rs]: >  002

*No I am not mining commit hashes, why do you ask?* 😃

**Review by yaahc — APPROVED** [review]
