### PR TITLE
Fix candidate set address state handling

### LINKED ISSUE #1435: Peer connections hang temporarily or fail permanently
**Analysis**

Peer connection failures can result in a slow sync, temporary sync hangs, or permanent sync hangs.

These failures can happen after network interruptions, or due to normal connection churn. They might also happen because Zebra's protocol state machine gets in an invalid or unrecoverable state.

**Next Steps**

Here are some things we could try:

- [ ] Run Zebra with a single local peer, and make it panic as soon as that peer disappears. It's ok for the peer to go from ready to unready and back, and maybe disconnect, but it should never disappear.

**Version**

zebrad 3.0.0-alpha.0

Current `main` branch
Edit: as of 2020-12-02

**Platform**
Linux oxarbitrage 4.15.0-20-generic #21-Ubuntu SMP Tue Apr 24 06:16:15 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Description**

During sync on the mainnet the `sync` component stopped responding. The program didn't crashed or hanged totally as the inbound requests where still being responded however no more block downloads were made. I have a log of this at https://gist.github.com/oxarbitrage/2f067fed9588c3d942e499d1252fc777 where the last msg from the sync component is at https://gist.github.com/oxarbitrage/2f067fed9588c3d942e499d1252fc777#file-gistfile1-txt-L2843 and no further msg after 30 minutes.

I tried stooping the program and start again. The sync resumed.

--
When trying to sync the zcash blockchain using zebra i will expect to download all the blocks from start to end without intervention. Instead, i had to stop(ctrl-c) the program and restart to keep going.

### LINKED ISSUE #1707: CandidateSet address books are not disjoint
## Description

The `CandidateSet` address books: `disconnected`, `gossiped`, and `failed`, are not disjoint. But the module documentation says they should be.

## Analysis

Peers are not removed from the other sets when they are added to the `failed` set in `report_failed`. So the sets can not possibly be disjoint.

## Suggested Solution

Core changes:
1. add a `PeerState` enum field to the `MetaAddr`
2. implement the time-based state as a `MetaAddr` method, rather than an enum variant
3. delete the `disconnected`, `gossiped`, and `failed` peer sets, and replace them with lookups into the single peer set

Optional improvements:
4. delete unused code

After these changes, there is only one copy of each peer, and it can only be in one state.

### PR DESCRIPTION
**Pull request by teor2345**
## Motivation

The `CandidateSet` address books: `disconnected`, `gossiped`, and `failed`, are not disjoint. But the module documentation says they should be.

The overall peer state handling is also a bit broken and inconsistent - it looks like peers can get stuck in particular states (perhaps related to #1633 or #1435).

## Solution

Design:
- [x] Redesign `AddressBook` by deleting duplicate indexes, rather than maintaining complex runtime invariants
- [x] Add a `PeerConnectionState` to each `MetaAddr`
- [x] Use a single peer set for all peers, regardless of state
- [x] Implement time-based liveness as an `AddressBook` method, rather than a `PeerConnectionState` variant

Implementation:
- [x] Simplify the `AddressBook` iterator implementation, replacing it with methods that are more obviously correct
- [x] Simplify `AddressBook` changes using `update` and `take` modifier methods
- [x] Consistently collect peer metrics

Documentation:
- Expand and update the peer set documentation

We can optimise later, but for now we want simple code that is more obviously correct.

The code in this pull request has:
  - [x] Documentation Comments
  - [x] Integration Tests

## Review

I don't know if @yaahc or @dconnolly is more familiar with this code, but it's a big enough change that everyone should probably take a look.

This rewrite might solve a whole bunch of our network problems, so it's a high priority. But the review is not urgent.

## Related Issues

Closes #1707.
Closes #1435, according to our testing - Zebra hasn't hung over several weeks of cumulative node runtime.

## Follow Up Work

Fix the `Client` state handling bug (#1599)

Performance/Security:
- [ ] limit the total address book size to maintain performance, discarding the oldest addresses once the limit is reached
  - 2x the peer set target size should be more than sufficient for our needs - this is close to the current number of active mainnet peers, so the code actually gets exercised on a regular basis

Security:
- [ ] handle future peer-provided last_seen times by subtracting the local/remote time delta from all the times in that peer's response
  - use relative skew to avoid assuming anything about the correctness of the local or remote clocks (the security analysis and testing done absolute times can get quite complex)
  - [ ] check for anywhere else in the protocol that uses peer-provided times or other untrusted/unverified data
- [ ] filter out known addresses, then limit the number of new addresses used from each request to `target peer size/3`
  - with a minimum of 3, so we almost always get addresses from multiple nodes, because some nodes are dual stack
  - this avoids having a single peer provide our entire set of peer connections (or our entire address book)

Network health:
- [ ] in response to peer requests, only provide peers we've actually connected to, to avoid gossiping unverified peer addresses, last_seen times, or services
  - decide if we want to send live or `Responded` peers
  - think about what happens for IPv4-only or IPv6-only peers
- [ ] don't gossip peers that are older than a day or so - some NAT / dynamic DNS networks change addresses every day, or even multiple times a day (laptops/mobiles)

Correctness:
- [ ] reject updates that move existing peers into the `AssumedDead` and `NeverAttempted` states. (Updates can only be `AttemptPending`, `AssumedAlive`, or `Failed`.)
- [ ] ensure that all inserts of new peers are in the `NeverAttempted` state.

Refactors:
- [ ] Implement time-based liveness as an `AssumedDead` state, via `update` and `take` inner type methods
    - make the `MetaAddr` state into a template parameter, which defaults to the outer state enum 
- [ ] make future peer-provided last_seen times into a parse error, if possible, so API users have to handle them

Features:
- [ ] Open a follow-up ticket to set up a persistent peer address book cache using RocksDB?

### CODE REVIEW

**Comment by teor2345** [comment]
Hey @mpguerra why did you set ticket #1707 as a blocker for this PR?

This PR actually fixes ticket #1707.

**Comment by mpguerra** [comment]
> Hey @mpguerra why did you set ticket #1707 as a blocker for this PR?
> 
> This PR actually fixes ticket #1707.

I put the reference in the wrong field... fixed now

File: zebra-network/src/address_book.rs [hunk 1]
```diff
@@ -5,54 +5,73 @@ use std::{
...
+            self.by_addr.len(),
+            self.by_state.len(),
+            "state-based and addresss-based indexes must have the same number of entries"
+        );
+
+        for reconnection_meta in self.by_state.iter() {
+            let addr_meta = self.by_addr.get(&reconnection_meta.addr);
+            assert_eq!(Some(reconnection_meta),
+                       addr_meta,
+                       "address metadata in state-based index does not match the metadata in the addresss-based index");
```
Comment (yaahc) [inline zebra-network/src/address_book.rs]:
```suggestion
                       "address metadata in state-based index does not match the metadata in the address-based index");
```

File: zebra-network/src/address_book.rs [hunk 2]
```diff
@@ -5,54 +5,73 @@ use std::{
...
-        for (a, (t, s)) in self.by_addr.iter() {
-            for meta in self.by_time.iter().filter(|meta| meta.addr == *a) {
-                if meta.last_seen != *t || meta.services != *s {
-                    panic!("meta {:?} is not {:?}, {:?}, {:?}", meta, a, t, s);
-                }
-            }
+        assert_eq!(
+            self.by_addr.len(),
+            self.by_state.len(),
+            "state-based and addresss-based indexes must have the same number of entries"
```
Comment (yaahc) [inline zebra-network/src/address_book.rs]:
```suggestion
            "state-based and address-based indexes must have the same number of entries"
```

Might want to double check that this typo isn't elsewhere in the file since it showed up in two places

File: zebra-network/src/peer_set/candidate_set.rs [hunk 3]
```diff
@@ -3,67 +3,80 @@ use std::sync::{Arc, Mutex};
...
+///  │                               │
+///  │                               │
+///  │                               │
+///  │                               │
+///  ├───────────────────────────────┼───────────────────────────────┐
+///  │ PeerSet AddressBook           ▼                               │
+///  │ ┌─────────────┐       ┌────────────────┐      ┌─────────────┐ │
+///  │ │  Possibly   │       │`NeverAttempted`│      │  `Failed`   │ │
+///  │ │Disconnected │       │     Peers      │      │   Peers     │◀┼┐
+///  │ │  `Recent`   │       │                │      │             │ ││
```
Comment (teor2345) [inline zebra-network/src/peer_set/candidate_set.rs]: - [x] Rename `Recent` to `Responded`

File: zebra-network/src/address_book.rs [hunk 4]
```diff
@@ -5,54 +5,73 @@ use std::{
...
+    /// Maps each peer address to its matching `MetaAddr`
+    by_addr: HashMap<SocketAddr, Arc<MetaAddr>>,
+
+    /// Stores peer addresses, in state then reconnection order.
+    ///
+    /// This order should not be used for reconnection attempts: use
+    /// [`reconnection_peers`] instead.
+    by_state: BTreeSet<Arc<MetaAddr>>,
+
+    /// The span for operations on this address book.
```
Comment (teor2345) [inline zebra-network/src/address_book.rs]: - [ ] Open a follow-up ticket to set up a persistent peer address book cache using RocksDB?

File: zebra-network/src/address_book.rs [hunk 5]
```diff
@@ -5,54 +5,73 @@ use std::{
...
-    by_addr: HashMap<SocketAddr, (DateTime<Utc>, PeerServices)>,
-    by_time: BTreeSet<MetaAddr>,
+    /// Maps each peer address to its matching `MetaAddr`
+    by_addr: HashMap<SocketAddr, Arc<MetaAddr>>,
+
+    /// Stores peer addresses, in state then reconnection order.
+    ///
+    /// This order should not be used for reconnection attempts: use
+    /// [`reconnection_peers`] instead.
+    by_state: BTreeSet<Arc<MetaAddr>>,
```
Comment (teor2345) [inline zebra-network/src/address_book.rs]: - [x] Remove the `Arc` and just copy the `MetaAddr`
- [x] See if there's a Rust in-memory database-like type that can do lookups on multiple distinct keys, and combined keys, and ensure key uniqueness

File: zebra-network/src/address_book.rs [hunk 6]
```diff
@@ -65,131 +84,244 @@ impl AddressBook {
...
-    /// more recent or discarding `new` if it is stale.
-    pub fn update(&mut self, new: MetaAddr) {
+    /// Add `new_peer` to the address book, updating the previous entry if
+    /// `new_peer` is more recent, or discarding `new_peer` if `new_peer` is
+    /// stale.
+    ///
+    /// ## Correctness:
+    ///
+    /// All changes should go through `update` or `take`, to ensure consistency
+    /// and accurate metrics.
```
Comment (teor2345) [inline zebra-network/src/address_book.rs]: - [ ] create an inner type with `update`, `take`, and query methods
- [ ]  use that type to do the `AssumedDead` state mapping

Comment (teor2345) [reply zebra-network/src/address_book.rs]: The inner type for #1709 can have an inner enum with a `Responded` state.

- [ ] map `Responded`  to `AssumedAlive` or `AssumedDead` as part of the inner-outer API. (Based on the current time.)
- [ ] make the `MetaAddr` state into a template parameter, which defaults to the outer state enum

That way we don't need inner mutability on every query, which is good for correctness and performance.

Also we can:
- [ ] reject updates that move existing peers into the `AssumedDead` and `NeverAttempted` states. (Updates can only be `AttemptPending`, `AssumedAlive`, or `Failed`.)
- [ ] ensure that all inserts of new peers are in the `NeverAttempted` state.

File: zebra-network/src/meta_addr.rs [hunk 7]
```diff
@@ -34,29 +112,48 @@ impl MetaAddr {
...
 impl Ord for MetaAddr {
-    /// `MetaAddr`s are sorted newest-first, and then in an arbitrary
-    /// but determinate total order.
+    /// `MetaAddr`s are sorted in approximate reconnection attempt order, but
+    /// with `Recent` peers sorted together.
+    ///
+    /// This order should not be used for reconnection attempts: use
+    /// [`AddressBook::reconnection_peers`] instead.
+    ///
+    /// See [`CandidateSet`] for more details.
```
Comment (teor2345) [inline zebra-network/src/meta_addr.rs:144]: This ordering allows multiple `MetaAddr`s with the same address in the `BTreeMap`. But it seems like it's a source of subtle bugs and complexity.

We could:
- [x] delete `Ord` and `PartialOrd` for `MetaAddr`
- [x] remove the inner `BTreeMap`
- [x] remove the consistency check function

As an alternative, we could document these issues, but the performance and code simplicity gain are probably worth it.

High priority performance/security follow up:
- [ ] limit the total address book size to maintain performance, discarding the oldest addresses once the limit is reached (2x the peer set target size should be more than sufficient for our needs - this is close to the current number of active mainnet peers, so the code actually gets exercised on a regular basis)

High priority security follow ups:
- [ ] handle future peer-provided last_seen times by subtracting the local/remote time delta from all the times in that peer's response
  - we use relative skew to avoid assuming anything about the correctness of the local or remote clocks (the security analysis and testing done absolute times can get quite complex)
  - [ ] open a follow-up to check for anywhere else in the protocol that uses peer-provided times or other untrusted/unverified data
- [ ] make future peer-provided last_seen times into a parse error, if possible
- [ ] filter out known addresses, then limit the number of new addresses used from each request to `target peer size/3` (with a minimum of 3, so we almost always get addresses from multiple nodes, because some nodes are dual stack)
  - this avoids having a single peer provide our entire set of peer connections (or our entire address book)
- [ ] in response to peer requests, only provide peers we've actually connected to (`AssumedAlive` or `AssumedDead`), to avoid gossiping unverified peer addresses, last_seen times, or services
  - [ ] don't provide peers that are older than a day or so - some NAT / dynamic DNS networks change addresses every day, or even multiple times a day (laptops/mobiles)
  - [ ] think about what happens for IPv4-only or IPv6-only peers

File: zebra-network/src/address_book.rs (hunk 5 above)
Comment (teor2345) [reply zebra-network/src/address_book.rs]: >  See if there's a Rust in-memory database-like type that can do lookups on multiple distinct keys, and combined keys, and ensure key uniqueness

there doesn't seem to be, maybe we should just use `HashSet<SocketAddr, MetaAddr>` and see what the performance is like

Comment (teor2345) [reply zebra-network/src/address_book.rs]: The performance is acceptable, even with ~4,000 failed addresses in the list on mainnet.

File: zebra-network/src/address_book.rs (hunk 2 above)
Comment (teor2345) [reply zebra-network/src/address_book.rs]: Fixed by deleting the state-based index 🤔

**Comment by teor2345** [comment]
@dconnolly @yaahc I've made the required design changes from the first review.

I'd like to get this reviewed and merged soon, so we can get it into the next alpha.

There's a bunch of other refactors, performance improvements, and security fixes we could do. But they're not required to fix the hangs. So I think we should open separate tickets for them, and schedule them in future sprints.

File: zebra-network/src/address_book.rs [hunk 8]
```diff
@@ -10,52 +10,44 @@ use std::{
...
+    /// The span for operations on this address book.
     span: Span,
 }
 
 #[allow(clippy::len_without_is_empty)]
 impl AddressBook {
     /// Construct an `AddressBook` with the given [`tracing::Span`].
     pub fn new(span: Span) -> AddressBook {
-        AddressBook {
+        let constructor_span = span.clone();
```
Comment (dconnolly) [inline zebra-network/src/address_book.rs:30]: `clone`, not move?

File: zebra-network/src/address_book.rs [hunk 9]
```diff
@@ -65,131 +57,212 @@ impl AddressBook {
...
-            // The ordering on MetaAddrs is newest-first, then arbitrary,
-            // so any fields will do here.
-            addr: SocketAddr::new(IpAddr::V4(Ipv4Addr::new(0, 0, 0, 0)), 0),
-            services: PeerServices::default(),
+    /// Returns true if the given [`SocketAddr`] has recently sent us a message.
+    pub fn recently_live_addr(&self, addr: &SocketAddr) -> bool {
+        let _guard = self.span.enter();
+        match self.by_addr.get(addr) {
+            None => false,
+            // NeverAttempted, Failed, and AttemptPending peers should never be live
```
Comment (dconnolly) [inline zebra-network/src/address_book.rs:128]: 👍

File: zebra-network/src/meta_addr.rs [hunk 10]
```diff
@@ -15,17 +15,112 @@ use zebra_chain::serialization::{
...
+        }
+    }
+}
+
+impl PartialOrd for PeerConnectionState {
+    fn partial_cmp(&self, other: &Self) -> Option<Ordering> {
+        Some(self.cmp(other))
+    }
+}
+
```
Comment (dconnolly) [inline zebra-network/src/meta_addr.rs]: Should this be defined in the `peer` module and used in here for `MetaAddr`? If yes we should reconcile this type of `peer::connection::State` with [the existing one](https://github.com/ZcashFoundation/zebra/blob/cc7d5bd2adea1fee9c9092f0438c5b04d5cf91b3/zebra-network/src/peer/connection.rs#L311), which is an enum that only has variants about `awaiting` or `failed`.

File: zebra-network/src/meta_addr.rs [hunk 11]
```diff
@@ -15,17 +15,112 @@ use zebra_chain::serialization::{
...
+    ///
+    /// The exact meaning depends on `last_connection_state`:
+    ///   - `Responded`: the services advertised by this peer, the last time we
+    ///      performed a handshake with it
+    ///   - `NeverAttempted`: the unverified services provided by the remote peer
+    ///     that sent us this address
+    ///   - `Failed` or `AttemptPending`: unverified services via another peer,
+    ///      or services advertised in a previous handshake
+    ///
+    /// ## Security
```
Comment (dconnolly) [inline zebra-network/src/meta_addr.rs:100]: Nice

File: zebra-network/src/meta_addr.rs [hunk 12]
```diff
@@ -15,17 +15,112 @@ use zebra_chain::serialization::{
...
+    ///
+    /// The exact meaning depends on `last_connection_state`:
+    ///   - `Responded`: the last time we processed a message from this peer
+    ///   - `NeverAttempted`: the unverified time provided by the remote peer
+    ///     that sent us this address
+    ///   - `Failed`: the last time we marked the peer as failed
+    ///   - `AttemptPending`: the last time we queued the peer for a reconnection
+    ///     attempt
+    ///
+    /// ## Security
```
Comment (dconnolly) [inline zebra-network/src/meta_addr.rs:116]: 👍

File: zebra-network/src/meta_addr.rs [hunk 13]
```diff
@@ -34,29 +129,48 @@ impl MetaAddr {
...
-            match (self.addr.ip(), other.addr.ip()) {
-                (V4(a), V4(b)) => a.octets().cmp(&b.octets()),
-                (V6(a), V6(b)) => a.octets().cmp(&b.octets()),
-                (V4(_), V6(_)) => Ordering::Less,
-                (V6(_), V4(_)) => Ordering::Greater,
-            }
+            .then(ip_numeric)
             .then(self.addr.port().cmp(&other.addr.port()))
             .then(self.services.bits().cmp(&other.services.bits()))
-        })
```
Comment (dconnolly) [inline zebra-network/src/meta_addr.rs:59]: Nice

File: zebra-network/src/meta_addr.rs (hunk 10 above)
Comment (teor2345) [reply zebra-network/src/meta_addr.rs]: No, these are very different states. `peer::connection::State` tracks the state of a single TCP connection. This state tracks peer address activity.

So I think we should rename this state to `PeerAddrState`.

File: zebra-network/src/address_book.rs (hunk 8 above)
Comment (teor2345) [reply zebra-network/src/address_book.rs:30]: You'll have to spell this one out for me

File: zebra-network/src/meta_addr.rs (hunk 11 above)
Comment (teor2345) [reply zebra-network/src/meta_addr.rs:100]: Yeah we should do a follow-up where we make the verified and unverified timestamps and services into different fields.

File: zebra-network/src/meta_addr.rs (hunk 10 above)
Comment (dconnolly) [reply zebra-network/src/meta_addr.rs]: I like that 👍

File: zebra-network/src/meta_addr.rs (hunk 11 above)
Comment (teor2345) [reply zebra-network/src/meta_addr.rs:100]: This is one of those distributed systems things - distinguishing untrusted data (from peers) from verified data (that we've created or checked ourselves).

File: zebra-network/src/address_book.rs (hunk 8 above)
Comment (dconnolly) [reply zebra-network/src/address_book.rs:30]: Ah, I mean, it's not obvious to me why this requires a clone, vs handing it to this constructor which then owns it, or borrowing it? Not a blocker

Comment (teor2345) [reply zebra-network/src/address_book.rs:30]: The constructor moves `span`, and `Span::enter` borrows it, so we can't use both on the same span.

Specifically:
`Span::enter` takes a reference to the span in the returned guard. The returned guard is dropped at the end of the function. `rustc` assumes that the `Drop` impl can access that reference, so it doesn't allow the move into the constructor.

Comment (teor2345) [reply zebra-network/src/address_book.rs:30]: This is the conservative drop check rule, which is often more strict than necessary:
https://doc.rust-lang.org/nomicon/dropck.html

File: zebra-network/src/meta_addr.rs (hunk 11 above)
Comment (teor2345) [reply zebra-network/src/meta_addr.rs:100]: I have a bunch of these kinds of changes, let's talk about them later this week.

**Comment by teor2345** [comment]
I've rebased on #1750 to silence a bunch of clippy lints.

**Comment by teor2345** [comment]
The CI failure is #1730.

**Review by dconnolly — DISMISSED** [review]

**Comment by teor2345** [comment]
Testnet is unstable, we'll fix that in #1222

**Comment by teor2345** [comment]
Merging because @dconnolly approved and asked for a rebase
