### PR TITLE
fix(test): Wait for zebrad and lightwalletd to reach the tip in tests, to improve test coverage

### LINKED ISSUE #4894: Make tests wait until lightwalletd full sync goes all the way to the tip
## Motivation

lightwalletd doesn't reliably log when it reaches the chain tip.

In PR #4828, we added a workaround to the lightwalletd full sync test, which stops at a fixed height near the chain tip. But for tests like #4350, we need to wait until it has actually reached the tip.

### Designs

Make the lightwalletd full sync, update sync, grpc, and send transaction tests wait until lightwalletd has reached the chain tip.

We could do this by checking that the Zebra JSON-RPC and lightwalletd gRPC heights match. (We can't do it using the logs, because `lightwalletd` doesn't reliably log block heights.)

The `lightwalletd_integration_test()` already does most of this work, we might want to call it from the grpc and send transaction tests.

### PR DESCRIPTION
**Pull request by oxarbitrage**
## Motivation

We need to make sure lightwalletd and zebrad is at the tip for several tests. Fix https://github.com/ZcashFoundation/zebra/issues/4894 if merged.

Depends-On: #5307

## Solution

Add a new function and move common code to check if we are at the tip. Call it from tests. We are calling this function from all tests that call `lightwalletd_integration_test` and from `wallet_grpc_test` and `send_transaction_test`.

Also, the `lightwalletd_test_suite` now runs `wallet_grpc_test` before `send_transaction_test` so we know cache is up to date when running the tests using the suite.

Functional changes:
- use the same code to configure, launch, and wait for `zebrad` and `lightwalletd` across all 8 RPC integration tests,
  this makes all these tests check a bunch of things the same way 
- run the quick tests first in the test suite, then the slow tests

Refactors:
- make some test functions easier to call

## Review

This PR is ready for review.

### Reviewer Checklist

  - [ ] Will the PR name make sense to users?
    - [ ] Does it need extra CHANGELOG info? (new features, breaking changes, large changes)
  - [ ] Are the PR labels correct?
  - [ ] Does the code do what the ticket and PR says?
  - [ ] How do you know it works? Does it have tests?
    - [ ] Do the existing tests run, or are we accidentally skipping them? Check the test time and test logs.

### CODE REVIEW

File: zebrad/tests/common/launch.rs [hunk 1]
```diff
@@ -195,26 +196,32 @@ where
     }
 }
 
-/// Spawns a zebrad instance to interact with lightwalletd, but without an internet connection.
+/// Spawns a zebrad instance to interact with lightwalletd.
 ///
+/// If `internet_connection` is not true then spawn but without any peers.
```
Comment (teor2345) [inline zebrad/tests/common/launch.rs]:
```suggestion
/// If `internet_connection` is `false` then spawn, but without any peers.
```

File: zebrad/tests/common/launch.rs [hunk 2]
```diff
@@ -195,26 +196,32 @@ where
...
     // This is what we recommend our users configure.
     let mut config = random_known_rpc_port_config(true)
         .expect("Failed to create a config file with a known RPC listener port");
 
     config.state.ephemeral = false;
-    config.network.initial_mainnet_peers = IndexSet::new();
+    if !internet_connection {
+        config.network.initial_mainnet_peers = IndexSet::new();
+    }
     config.network.initial_testnet_peers = IndexSet::new();
```
Comment (teor2345) [inline zebrad/tests/common/launch.rs]: We don't run on testnet at the moment, but this is the code we'll need if we do:

```suggestion
    if !internet_connection {
        config.network.initial_mainnet_peers = IndexSet::new();
        config.network.initial_testnet_peers = IndexSet::new();
    }
```

File: zebrad/tests/common/launch.rs [hunk 3]
```diff
@@ -228,12 +235,61 @@ pub fn spawn_zebrad_for_rpc_without_initial_peers<P: ZebradTestDirExt + std::fmt
...
+>(
+    mut lightwalletd: TestChild<TempDir>,
+    mut zebrad: TestChild<P>,
+    test_type: LightwalletdTestType,
+) -> Result<(TestChild<TempDir>, TestChild<P>)> {
+    let lightwalletd_thread = std::thread::spawn(move || -> Result<_> {
+        tracing::info!(?test_type, "waiting for lightwalletd to sync to the tip");
+
+        lightwalletd
+            .expect_stdout_line_matches(crate::common::sync::LIGHTWALLETD_SYNC_FINISHED_REGEX)?;
```
Comment (teor2345) [inline zebrad/tests/common/launch.rs]: This regex is actually a fixed height. So we are finishing these tests too early, significantly reducing our test coverage.

I think we'll want to:

In the `zebrad` thread:
- wait for Zebra to sync to the tip
- keep checking the `zebrad` logs until `lightwalletd` syncs to the tip
- then finish the thread

In the `lightwalletd` thread:
- keep checking the `lightwalletd` logs until Zebra syncs to the tip
- then keep asking `lightwalletd` for its height via gRPC, until it is equal to the `zebrad` height
- then finish the thread

This probably needs a channel from the `zebrad` to the `lightwalletd` thread.

File: zebrad/tests/common/lightwalletd/send_transaction_test.rs [hunk 4]
```diff
@@ -109,13 +109,10 @@ pub async fn run() -> Result<()> {
...
 
-    // TODO: change debug_skip_parameter_preload to true if we do the mempool test in the wallet gRPC test
-    let (mut zebrad, zebra_rpc_address) = spawn_zebrad_for_rpc_without_initial_peers(
-        Network::Mainnet,
-        zebrad_state_path,
-        test_type,
-        false,
-    )?;
+    // Start zebrad with no peers, we want to send transactions without blocks coming in. If `wallet_grpc_test`
+    // runs before this test (as it does in `lightwalletd_test_suite`), then we are the most up to date with tip we can.
```
Comment (teor2345) [inline zebrad/tests/common/lightwalletd/send_transaction_test.rs:109]: In CI, these tests run in parallel, so we'll need to change the logic in `wait_for_zebrad_and_lightwalletd_tip` to check `lightwalletd` is at the tip, and add it to `send_transaction_test::run()`.

File: zebrad/tests/common/launch.rs [hunk 5]
```diff
@@ -228,12 +235,61 @@ pub fn spawn_zebrad_for_rpc_without_initial_peers<P: ZebradTestDirExt + std::fmt
...
+/// But if the logs just stop, we can't tell the difference between a hang and fully synced.
+/// So we assume `lightwalletd` will sync and log large groups of blocks,
+/// and check for logs with heights near the mainnet tip height.
+#[tracing::instrument]
+pub fn wait_for_zebrad_and_lightwalletd_tip<
+    P: ZebradTestDirExt + std::fmt::Debug + std::marker::Send + 'static,
+>(
+    mut lightwalletd: TestChild<TempDir>,
+    mut zebrad: TestChild<P>,
+    test_type: LightwalletdTestType,
```
Comment (teor2345) [inline zebrad/tests/common/launch.rs:258]:
```suggestion
    test_type: LightwalletdTestType,
    wait_for_zebrad_tip: bool,
```

File: zebrad/tests/common/launch.rs [hunk 6]
```diff
@@ -228,12 +235,61 @@ pub fn spawn_zebrad_for_rpc_without_initial_peers<P: ZebradTestDirExt + std::fmt
...
 }
 
+/// Wait for lightwalletd to sync to Zebra's tip.
+///
+/// "Adding block" and "Waiting for block" logs stop when `lightwalletd` reaches the tip.
+/// But if the logs just stop, we can't tell the difference between a hang and fully synced.
+/// So we assume `lightwalletd` will sync and log large groups of blocks,
+/// and check for logs with heights near the mainnet tip height.
+#[tracing::instrument]
+pub fn wait_for_zebrad_and_lightwalletd_tip<
```
Comment (teor2345) [inline zebrad/tests/common/launch.rs]:
```suggestion
pub fn wait_for_zebrad_and_lightwalletd_sync<
```

File: zebrad/tests/common/lightwalletd/send_transaction_test.rs [hunk 7]
```diff
@@ -136,17 +133,36 @@ pub async fn run() -> Result<()> {
...
+        .body(r#"{"jsonrpc": "2.0", "method": "getblockchaininfo", "params": [], "id":123 }"#)
+        .header("Content-Type", "application/json")
+        .send()
+        .await?
+        .text()
+        .await?;
+
+    // Make sure tip from lightwalletd is the same as zebrad
+    let parsed: serde_json::Value = serde_json::from_str(&res)?;
+    assert_eq!(block_tip.height, parsed["result"]["blocks"]);
```
Comment (teor2345) [inline zebrad/tests/common/lightwalletd/send_transaction_test.rs]: We can move this into its own function and call it from `wait_for_zebrad_and_lightwalletd_sync`.

Here we'll want `wait_for_zebrad_tip = false`.

File: zebrad/tests/common/lightwalletd/wallet_grpc_test.rs [hunk 8]
```diff
@@ -145,6 +143,29 @@ pub async fn run() -> Result<()> {
...
+        .body(r#"{"jsonrpc": "2.0", "method": "getblockchaininfo", "params": [], "id":123 }"#)
+        .header("Content-Type", "application/json")
+        .send()
+        .await?
+        .text()
+        .await?;
+
+    // Make sure tip from lightwalletd and from zebrad are the same
+    let parsed: serde_json::Value = serde_json::from_str(&res)?;
+    assert_eq!(block_tip.height, parsed["result"]["blocks"]);
```
Comment (teor2345) [inline zebrad/tests/common/lightwalletd/wallet_grpc_test.rs]: We can move this into its own function and call it from `wait_for_zebrad_and_lightwalletd_sync`.

Here we'll want `wait_for_zebrad_tip = true`.

File: zebrad/tests/acceptance.rs [hunk 9]
```diff
@@ -1630,42 +1630,9 @@ fn lightwalletd_integration_test(test_type: LightwalletdTestType) -> Result<()>
...
-                .join()
-                .unwrap_or_else(|panic_object| panic::resume_unwind(panic_object))?;
-
-            let lightwalletd = lightwalletd_thread
-                .join()
-                .unwrap_or_else(|panic_object| panic::resume_unwind(panic_object))?;
-
+        if let Some(lightwalletd) = lightwalletd {
+            let (zebrad, lightwalletd) =
+                wait_for_zebrad_and_lightwalletd_tip(lightwalletd, zebrad, test_type)?;
```
Comment (teor2345) [inline zebrad/tests/acceptance.rs]: Here we'll want `wait_for_zebrad_tip = true`.

**Review by teor2345 — COMMENTED** [review]
This is pretty much what we want.

I just want to add a few more checks to some tests, so they run for longer and cover more blocks and code.

**Comment by teor2345** [comment]
@mergifyio update

File: zebrad/tests/common/launch.rs (hunk 3 above)
Comment (arya2) [reply zebrad/tests/common/launch.rs]: Was the idea behind `wait_for_zebrad_tip: bool` to make this optional or should it always do this?

**Comment by teor2345** [comment]
I combined the test APIs for the lightwalletd sync and gRPC tests.
This will give us a consistent sync to the tip across all those tests.

But I still need to fix some test failures.

File: zebrad/tests/common/launch.rs (hunk 3 above)
Comment (teor2345) [reply zebrad/tests/common/launch.rs]: Some tests need to wait until they sync to the public network chain tip. Others run disconnected from the network, so they just need to load whatever state they have.

And then lightwalletd will sync whatever zebrad has in both kinds of tests.

**Comment by teor2345** [comment]
I think I've fixed all the test failures, so this PR is ready for review.

If any of the CI runs fail, I'll fix them on Monday.

**Comment by teor2345** [comment]
I fixed a bug in the send transaction test tip sync check, and tried to speed up lightwalletd syncs to avoid GitHub Actions timeouts. (They are taking 6 hours, which seems like far too long for lightwalletd.)

**Comment by teor2345** [comment]
It's possible the sync speed will be fixed by PR #5134 or ticket #5253.

File: zebrad/tests/common/lightwalletd/sync.rs [hunk 10]
```diff
@@ -0,0 +1,206 @@
...
+    zebra_rpc_address: SocketAddr,
+    test_type: LightwalletdTestType,
+    wait_for_zebrad_mempool: bool,
+    wait_for_zebrad_tip: bool,
+) -> Result<(TestChild<TempDir>, TestChild<P>)> {
+    let is_zebrad_finished = AtomicBool::new(false);
+    let is_lightwalletd_finished = AtomicBool::new(false);
+
+    let is_zebrad_finished = &is_zebrad_finished;
+    let is_lightwalletd_finished = &is_lightwalletd_finished;
```
Comment (arya2) [inline zebrad/tests/common/lightwalletd/sync.rs:44]: These aren't necessary

```suggestion
```

File: zebrad/tests/common/lightwalletd/sync.rs [hunk 11]
```diff
@@ -0,0 +1,206 @@
...
+    std::thread::scope(|s| {
+        // Launch the sync-waiting threads
+        let zebrad_thread = s.spawn(|| {
+            zebrad_wait_fn().expect("test failed while waiting for zebrad to sync");
+        });
+
+        let lightwalletd_thread = s.spawn(|| {
+            let lightwalletd_result = lightwalletd_wait_fn();
+            is_lightwalletd_finished.store(true, Ordering::SeqCst);
+            lightwalletd_result.expect("test failed while waiting for lightwalletd to sync");
```
Comment (arya2) [inline zebrad/tests/common/lightwalletd/sync.rs]: It looks like `is_lightwalletd_finished` is being set to true after this thread is joined. It could also update the finished markers with a panic hook.

```suggestion
            lightwalletd_wait_fn().expect("test failed while waiting for lightwalletd to sync.");
```

File: zebrad/tests/common/lightwalletd/sync.rs [hunk 12]
```diff
@@ -0,0 +1,206 @@
...
+    Ok((lightwalletd, zebrad))
+}
+
+/// Returns `Ok(true)` if zebrad and lightwalletd are both at the same height.
+#[tracing::instrument]
+pub fn are_zebrad_and_lightwalletd_tips_synced(
+    lightwalletd_rpc_port: u16,
+    zebra_rpc_address: SocketAddr,
+) -> Result<bool> {
+    let rt = tokio::runtime::Builder::new_multi_thread()
```
Comment (arya2) [inline zebrad/tests/common/lightwalletd/sync.rs:172]: Does it need a multi-thread runtime? It probably doesn't matter either way since this is only being called once per minute, but I'm curious about the overhead for keeping it alive vs startup and shutdown.

File: zebrad/tests/common/lightwalletd/sync.rs (hunk 11 above)
Comment (teor2345) [reply zebrad/tests/common/lightwalletd/sync.rs]: Thanks, I meant to do that cleanup, but forgot about it.

> It could also update the finished markers with a panic hook.

That doesn't work, because `&mut zebra_test::command::TestChild<TempDir>` is not unwind-safe.
See the TODO note below.

File: zebrad/tests/common/lightwalletd/sync.rs (hunk 10 above)
Comment (teor2345) [reply zebrad/tests/common/lightwalletd/sync.rs:44]: When I tried it without them, both closures tried to capture both `AtomicBool`s, which didn't work, because they had already been moved. (`AtomicBool`s are not `Copy`.)

But I've made some changes after that, feel free to push another PR to see if it works.

File: zebrad/tests/common/lightwalletd/sync.rs (hunk 12 above)
Comment (teor2345) [reply zebrad/tests/common/lightwalletd/sync.rs:172]: Yes, `tokio::block_in_place()` is used in the state, and it panics in a single-threaded runtime.

**Comment by teor2345** [comment]
> It's possible the sync speed will be fixed by PR #5134 or ticket #5253.

I've added ticket #5253 to this sprint.

**Comment by teor2345** [comment]
> > It's possible the sync speed will be fixed by PR #5134 or ticket #5253.
> 
> I've added ticket #5253 to this sprint.

We might also want to try re-applying #4933, but only for transactions over a certain size.
(Because they are more likely to be shielded transactions.)

**Comment by teor2345** [comment]
I'm testing how long `zebrad` and `zcashd` full `lightwalletd` syncs take.

If Zebra is faster, I'll move the full `lightwalletd` sync to the `main` branch (like the full Zebra Zcash chain sync).
If `zcashd` is faster, I'll try to work out if it is a recent Zebra regression, or what we need to do to fix it.

I used these commands:

```sh
$ time lightwalletd     --zcash-conf-path /home/dev/.config/zebra/zebrad-mainnet-lightwalletd-tmp-zcash.conf     --data-dir $(mktemp -d)     --log-file /dev/stdout     --grpc-bind-addr 0.0.0.0:0     --http-bind-addr 0.0.0.0:0     --no-tls-very-insecure           2>&1 |   rg --passthru --max-count 1 'Adding block to cache 182[0-9]{4}'
```

```sh
$ time lightwalletd     --zcash-conf-path /home/dev/.zcash/zcash.conf     --data-dir $(mktemp -d)     --log-file /dev/stdout     --grpc-bind-addr 0.0.0.0:0     --http-bind-addr 0.0.0.0:0     --no-tls-very-insecure           2>&1 |  rg --passthru --max-count 1 'Adding block to cache 182[0-9]{4}'
```

`rg` (ripgrep) is a Rust-based `grep` alternative.
`/home/dev/.config/zebra/zebrad-mainnet-lightwalletd-tmp-zcash.conf` is set up like it is in the `lightwalletd` tests.

**Comment by teor2345** [comment]
> I'm testing how long `zebrad` and `zcashd` full `lightwalletd` syncs take.

Zebra:
```
{"app":"lightwalletd","level":"info","msg":"Adding block to cache 1820016 0000000000b8829cf2e067786d21d6d8f466c4ef5a4ed498bc3784c2aaf48843","time":"2022-09-29T00:40:09+10:00"}

real    425m2.980s
user    54m46.146s
sys     10m42.911s
```

`zcashd`:
```
{"app":"lightwalletd","level":"info","msg":"Adding block to cache 1820013 00000000003906dc28e4be077d64a2b93faaad5d73882370f3843fb3fae674ef","time":"2022-09-28T22:45:53+10:00"}

real    310m45.464s
user    55m43.160s
sys     11m8.546s
```

Zebra is 37% slower than `zcashd` (7h vs 5h), so this is a performance issue in Zebra we need to fix before the release candidate.

**Comment by teor2345** [comment]
I made verbose block requests about 8x faster in commit eb1359acb0.

I'm running a full sync overnight to see if that helps.

**Comment by teor2345** [comment]
> I made verbose block requests about 8x faster in commit [eb1359a](https://github.com/ZcashFoundation/zebra/commit/eb1359acb0ad576ad9b1b9c88fb47c5406ff6306).
> 
> I'm running a full sync overnight to see if that helps.

A full `lightwalletd` sync takes 3.4 hours now, so that meets our performance goals for the release candidate. (3.4h vs 5h for `zcashd`.)

```
$ time lightwalletd-mainnet-tmp | rg --passthru --max-count 1 'Adding block to cache 182[0-9]{4}'
...
{"app":"lightwalletd","level":"info","msg":"Adding block to cache 1820018 000000000085c92f02a5dec63a62d77455a9e631a624b24c50bfc7e733df65d9","time":"2022-09-29T23:22:58+10:00"}


real    204m48.731s
user    52m38.236s
sys     10m22.202s
```

**Comment by upbqdn** [comment]
`release-drafter` labeled this PR as `C-trivial`. Probably because we edited the file `zcash-rpc-diff` in `zebra-utils`. I removed the label.

**Comment by teor2345** [comment]
> `release-drafter` labeled this PR as `C-trivial`. Probably because we edited the file `zcash-rpc-diff` in `zebra-utils`. I removed the label.

Yeah we might want to change that pattern to "only zebra-utils" or remove it entirely. Feel free to push a PR!

**Comment by teor2345** [comment]
I got the path wrong for the `lightwalletd` cached state, so there is one `lightwalletd` cached state disk that is missing the `lightwalletd` database files.

The latest 2 commits fix the path, so the env var is used for all the syncs that might use or create/update cached states.

**Comment by teor2345** [comment]
`ubuntu-latest` tests failed due to `mempool_cancel_mined`. That's bug #5301.
https://github.com/ZcashFoundation/zebra/actions/runs/3170245187/jobs/5162701722#step:14:17349

**Comment by teor2345** [comment]
@mergifyio update

**Comment by teor2345** [comment]
All the checks passed, but some didn't run because the PR was automatically rebased to `main`.

**Comment by teor2345** [comment]
Alfredo is going to review this PR, but I can't set him as a reviewer, because he opened it.

**Comment by teor2345** [comment]
The macOS test had an unrelated failure, I opened PR #5325 to get better diagnostics.

**Review by oxarbitrage — COMMENTED** [review]
This looks really good to me. I can't approve as i am the original author but it seems to be merge ready.

**Comment by upbqdn** [comment]
I'm reviewing this PR now.

**Review by teor2345 — APPROVED** [review]
Arya and Alfredo have already reviewed this PR.

**Comment by gustavovalverde** [comment]
@Mergifyio update

**Comment by arya2** [comment]
`mempool_cancel_mined` failed in the merge-queue

**Comment by arya2** [comment]
@Mergifyio refresh
