### PR TITLE
chore(lints): Fixes Clippy warnings

### LINKED ISSUE #8722: Fix new lints in the latest stable version of clippy
## Motivation 

The new lints need to be addressed to prevent CI from failing.

### PR DESCRIPTION
**Pull request by arya2**
## Motivation

New lints added in the latest version of Clippy are causing CI to fail.

Closes #8722.

## Solution

- Manually addressed new Clippy warnings.

Related changes:
- Removes unused stored test configs.

### Tests

Lint job in CI should pass.

### Follow-up Work

Rebase PRs off of main.

### PR Author's Checklist

- [x] The PR name will make sense to users.
- [x] The PR provides a CHANGELOG summary.
- [x] The solution is tested.
- [x] The documentation is up to date.
- [x] The PR has a priority label.

### PR Reviewer's Checklist

- [ ] The PR Author's checklist is complete.
- [ ] The PR resolves the issue.

### CODE REVIEW

File: zebra-state/src/service/non_finalized_state.rs [hunk 1]
```diff
@@ -182,6 +182,7 @@ impl NonFinalizedState {
         // Chain::cmp uses the partial cumulative work, and the hash of the tip block.
         // Neither of these fields has interior mutability.
         // (And when the tip block is dropped for a chain, the chain is also dropped.)
+        #[allow(clippy::mutable_key_type)]
```
Comment (arya2) [inline zebra-state/src/service/non_finalized_state.rs:185]: This was a [false positive](https://rust-lang.github.io/rust-clippy/master/index.html#/mutable_key_type) and should remain a false positive unless there are unexpected changes to how `Chain` is mutated or its `Ord` impl. 

We could refactor this method to use `pop_last()` instead, I'm happy to do that in this PR, open an issue, or leave a TODO if we want to do that (though I would prefer that it be done in another PR to fix the issue on main sooner).

**Review by oxarbitrage — APPROVED** [review]
