### PR TITLE
fix(rpc): Refactor the serialization of note commitment trees

### LINKED ISSUE #8471: bug: `get_tree_state` fails at sapling activation height + 0 and +1
### What happened?

I called the `get_tree_state` gRPC function to my zebra-backed litewalletd server.

 I expected to see this happen:

419200 is the sapling activation height, so I would expect that block to work. It's odd that 419202 works, but not 419201.

Instead, this happened: 

The litewalletd eturns this error when I use 419200 or 419201 as the birthday height:

> status: Unknown, message: "zcashd did not return treestate", details: [], metadata: MetadataMap { headers: {"content-type": "application/grpc"} }

### What were you doing when the issue happened?

Exploratory testing of a wallet.

### Zebra logs

_No response_

### Zebra Version

1.6.1

### Which operating systems does the issue happen on?

- [X] Linux
- [ ] macOS
- [ ] Windows
- [ ] Other OS

### OS details

Ubuntu 22.04.1

### Additional information

@str4d [diagnosed this:](https://discord.com/channels/809218587167293450/1233989754014531644)

> Those first two blocks contained no Sapling notes IIRC, so the tree is empty. This is a bug in Zebra, because it should be returning the entry TreeState in that case

### PR DESCRIPTION
**Pull request by upbqdn**
## Motivation

Close #8471.

The bug described in #8471 is caused by an incorrect serialization of empty note commitment trees for RPCs. Zebra serializes such trees as the empty string, but `zcashd` serializes them as `000000`. This bug is related only to the `z_get_treestate` RPC. The state contains the right trees and uses a different serialization format.

#### Check before marking the PR as ready for review:
  - [x] Will the PR name make sense to users?
  - [x] Does the PR have a priority label?
  - [x] Have you added or updated tests?
  - [x] Is the documentation up to date?

## Solution

- Remove the old RPC serialization code.
- Use an upstream code to serialize the trees for RPCs.

  Note that the serialization of non-empty Sapling treestates now differs between `zebrad` and `zcashd`. We can see this in the results of the manual tests below. The difference is that `zebrad`'s non-empty Sapling treestates contain trailing zeros, whereas `zcashd`'s ones don't. Both serializations deserialize to the same frontier and use the sparse format, which permits the omission or inclusion of the trailing zeros. See https://discord.com/channels/809218587167293450/809251012610752513/1240372877358792755 for more details.
- Cleanups.

### Snapshots

- Remove old test snapshots and add new ones.

<details>
<summary>

### Results of manual tests
</summary>

The results below compare the responses from `z_gettreestate` to `zcashd`. Note that `zebrad` doesn't provide the `finalState` object, and when an object is empty, `zebrad` skips its serialization.

#### Sapling

`zcash-cli z_gettreestate 419199 | jq`

`zebrad`:

```json
{
  "hash": "00000000025c3b19eb08bbc0d74c0c5e798fcd58b38ecdcdda6b83e5c5945295",
  "height": 419199,
  "time": 1540779316
}
```

`zcashd`:
```json
{
  "hash": "00000000025c3b19eb08bbc0d74c0c5e798fcd58b38ecdcdda6b83e5c5945295",
  "height": 419199,
  "time": 1540779316,
  "sapling": {
    "commitments": {
      "finalRoot": "0000000000000000000000000000000000000000000000000000000000000000"
    }
  },
  "orchard": {
    "commitments": {
      "finalRoot": "0000000000000000000000000000000000000000000000000000000000000000"
    }
  }
}
```

`zcash-cli z_gettreestate 419200 | jq`

`zebrad`:
```json
{
  "hash": "00000000025a57200d898ac7f21e26bf29028bbe96ec46e05b2c17cc9db9e4f3",
  "height": 419200,
  "time": 1540779337,
  "sapling": {
    "commitments": {
      "finalState": "000000"
    }
  }
}
```

`zcashd`:
```json
{
  "hash": "00000000025a57200d898ac7f21e26bf29028bbe96ec46e05b2c17cc9db9e4f3",
  "height": 419200,
  "time": 1540779337,
  "sapling": {
    "commitments": {
      "finalRoot": "3e49b5f954aa9d3545bc6c37744661eea48d7c34e3000d82b7f0010c30f4c2fb",
      "finalState": "000000"
    }
  },
  "orchard": {
    "commitments": {
      "finalRoot": "0000000000000000000000000000000000000000000000000000000000000000"
    }
  }
}
```

`zcash-cli z_gettreestate 419201 | jq`

`zebrad`:
```json
{
  "hash": "00000000014d117faa2ea701b24261d364a6c6a62e5bc4bc27335eb9b3c1e2a8",
  "height": 419201,
  "time": 1540779438,
  "sapling": {
    "commitments": {
      "finalState": "019eb30778ddeea84c72e69e07a1689f3c8def3dc0a1939f0edcbe47279069d931001f000150715810d52caf35471d10feb487213fbd95ff209122225b7b65d27a7fb1a44d0000000000000000000000000000000000000000000000000000000000"
    }
  }
}
```

`zcashd`:
```json
{
  "hash": "00000000014d117faa2ea701b24261d364a6c6a62e5bc4bc27335eb9b3c1e2a8",
  "height": 419201,
  "time": 1540779438,
  "sapling": {
    "commitments": {
      "finalRoot": "638d7e5ba37ab7921c51a4f3ae1b32d71c605a0ed9be7477928111a637f7421b",
      "finalState": "019eb30778ddeea84c72e69e07a1689f3c8def3dc0a1939f0edcbe47279069d9310002000150715810d52caf35471d10feb487213fbd95ff209122225b7b65d27a7fb1a44d"
    }
  },
  "orchard": {
    "commitments": {
      "finalRoot": "0000000000000000000000000000000000000000000000000000000000000000"
    }
  }
}
```

`zcash-cli z_gettreestate 1687104 | jq`

`zebrad`:
```json
{
  "hash": "0000000000d723156d9b65ffcf4984da7a19675ed7e2f06d9e5d5188af087bf8",
  "height": 1687104,
  "time": 1654019405,
  "sapling": {
    "commitments": {
      "finalState": "01b44a49543697efcf8c8f31759426c7baaea332c188a5ad2cbe0f7cdc35f5ad3f001f013cef92c19a6d24ba2e4454d018f7c7d6a64e0d7dc428a7a463617c726459230f01e8fe3507e2380ce4b17febf0bd5692883b5eff1cf9336c94fbec2153ece9e752014985ea98e1e8612a883112e794599176c1d84e5eccf531aecf7ecb0630a3ed1d01c1eacd8226ff8865f6c2495cb6c69f3e2fb71f142264dd123cad696ac4e3d35f015addd80e5152fbd8eeb49177dd46a6626b1629d4ed31a833155ca3b6cf3cb54101279f7afb4866502d697c5cbbd4a2b86bfb981dbe3c5ef29538ad1234159d3673010284d6898ca14c204611c5549bd410e6524053af5a166a6c5837653f46c3074501ae61a98ec05d976a41e46f0b7ae8dee5bda5ab490eea7b701153511a15be42590198c748a5e9516711db607e282f08013ba00b3e77bc66ec28702ca17893a5154b000139113a1e0f54d93c6180f2df7d16afbf7c320f6c7665cb10e1fc309878b0d716019a0214bcb1fd7a70e53166101992147512f3debb0fdce45ac625fffd64771010000134136b9f1f00c2e9d16dc7358ef920862511c8fc42fb7074cbc9016d8d4e8b4c015eddc191a81221b7900bbdcd8610e5df595e3cdc7fd5b3432e3825206ae35b05017eda713cd733ccc555123788692a1876f9ca292b0aa2ddf3f45ed2b47f027340000000015ec9e9b1295908beed437df4126032ca57ada8e3ebb67067cd22a73c79a840090000000000000000000000"
    }
  },
  "orchard": {
    "commitments": {
      "finalState": "000000"
    }
  }
}
```

`zcashd`:
```json
{
  "hash": "0000000000d723156d9b65ffcf4984da7a19675ed7e2f06d9e5d5188af087bf8",
  "height": 1687104,
  "time": 1654019405,
  "sapling": {
    "commitments": {
      "finalRoot": "4c0455466849dafedc0aab00f842f5ce4ef7dc1e795995d460fd072ce20f609f",
      "finalState": "01b44a49543697efcf8c8f31759426c7baaea332c188a5ad2cbe0f7cdc35f5ad3f0014013cef92c19a6d24ba2e4454d018f7c7d6a64e0d7dc428a7a463617c726459230f01e8fe3507e2380ce4b17febf0bd5692883b5eff1cf9336c94fbec2153ece9e752014985ea98e1e8612a883112e794599176c1d84e5eccf531aecf7ecb0630a3ed1d01c1eacd8226ff8865f6c2495cb6c69f3e2fb71f142264dd123cad696ac4e3d35f015addd80e5152fbd8eeb49177dd46a6626b1629d4ed31a833155ca3b6cf3cb54101279f7afb4866502d697c5cbbd4a2b86bfb981dbe3c5ef29538ad1234159d3673010284d6898ca14c204611c5549bd410e6524053af5a166a6c5837653f46c3074501ae61a98ec05d976a41e46f0b7ae8dee5bda5ab490eea7b701153511a15be42590198c748a5e9516711db607e282f08013ba00b3e77bc66ec28702ca17893a5154b000139113a1e0f54d93c6180f2df7d16afbf7c320f6c7665cb10e1fc309878b0d716019a0214bcb1fd7a70e53166101992147512f3debb0fdce45ac625fffd64771010000134136b9f1f00c2e9d16dc7358ef920862511c8fc42fb7074cbc9016d8d4e8b4c015eddc191a81221b7900bbdcd8610e5df595e3cdc7fd5b3432e3825206ae35b05017eda713cd733ccc555123788692a1876f9ca292b0aa2ddf3f45ed2b47f027340000000015ec9e9b1295908beed437df4126032ca57ada8e3ebb67067cd22a73c79a84009"
    }
  },
  "orchard": {
    "commitments": {
      "finalRoot": "ae2935f1dfd8a24aed7c70df7de3a668eb7a49b1319880dde2bbd9031ae5d82f",
      "finalState": "000000"
    }
  }
}
```

`zcash-cli z_gettreestate 1687107 | jq`

`zebrad`:
```json
{
  "hash": "00000000005a5e6f54c494b6317f3e800ce89a716584e62dcb35c2b3ace4b498",
  "height": 1687107,
  "time": 1654019794,
  "sapling": {
    "commitments": {
      "finalState": "01548d76c9708e1ea19cbfca3a0da6e368210dbe36ed022f32641416070760e750001f01a122025ebf64510a565e95a48604ff431c5cde6cb8caf9b7234066fcd1325c2a01162d1c2490d6bac0c7622d7a6aa214959367513dc2c45711a0d386bb3aafd261000000000000000138ebc51a133a60cdd2c02bdef27df1f1aa68882e0550a948fd7fb6f6b71e07210139113a1e0f54d93c6180f2df7d16afbf7c320f6c7665cb10e1fc309878b0d716019a0214bcb1fd7a70e53166101992147512f3debb0fdce45ac625fffd64771010000134136b9f1f00c2e9d16dc7358ef920862511c8fc42fb7074cbc9016d8d4e8b4c015eddc191a81221b7900bbdcd8610e5df595e3cdc7fd5b3432e3825206ae35b05017eda713cd733ccc555123788692a1876f9ca292b0aa2ddf3f45ed2b47f027340000000015ec9e9b1295908beed437df4126032ca57ada8e3ebb67067cd22a73c79a840090000000000000000000000"
    }
  },
  "orchard": {
    "commitments": {
      "finalState": "01e542b41a8a44e417521228218da39f865283ae50431c2292c36f379f6da04d2d0138fb218b939d9d6b7e906f1e68e49b4a5b9c1941fbf21c543529b19eadbcb01f1f00000000000000000000000000000000000000000000000000000000000000"
    }
  }
}
```

`zcashd`:
```json
{
  "hash": "00000000005a5e6f54c494b6317f3e800ce89a716584e62dcb35c2b3ace4b498",
  "height": 1687107,
  "time": 1654019794,
  "sapling": {
    "commitments": {
      "finalRoot": "4b013ee86a4a7b19871aa9b7a1dff0b29e0a737812c8970356c18340752957c7",
      "finalState": "01548d76c9708e1ea19cbfca3a0da6e368210dbe36ed022f32641416070760e750001401a122025ebf64510a565e95a48604ff431c5cde6cb8caf9b7234066fcd1325c2a01162d1c2490d6bac0c7622d7a6aa214959367513dc2c45711a0d386bb3aafd261000000000000000138ebc51a133a60cdd2c02bdef27df1f1aa68882e0550a948fd7fb6f6b71e07210139113a1e0f54d93c6180f2df7d16afbf7c320f6c7665cb10e1fc309878b0d716019a0214bcb1fd7a70e53166101992147512f3debb0fdce45ac625fffd64771010000134136b9f1f00c2e9d16dc7358ef920862511c8fc42fb7074cbc9016d8d4e8b4c015eddc191a81221b7900bbdcd8610e5df595e3cdc7fd5b3432e3825206ae35b05017eda713cd733ccc555123788692a1876f9ca292b0aa2ddf3f45ed2b47f027340000000015ec9e9b1295908beed437df4126032ca57ada8e3ebb67067cd22a73c79a84009"
    }
  },
  "orchard": {
    "commitments": {
      "finalRoot": "7b61fc613cea5c2c84c5e2c64d4fd4afb8c8c9d10dce9bcad49431c9cf32f131",
      "finalState": "01e542b41a8a44e417521228218da39f865283ae50431c2292c36f379f6da04d2d0138fb218b939d9d6b7e906f1e68e49b4a5b9c1941fbf21c543529b19eadbcb01f1f00000000000000000000000000000000000000000000000000000000000000"
    }
  }
}
```
</details>

### Reviewer Checklist

Check before approving the PR:
  - [x] Does the PR scope match the ticket?
  - [x] Are there enough tests to make sure it works? Do the tests cover the PR motivation?
  - [x] Are all the PR blockers dealt with?
        PR blockers can be dealt with in new tickets or PRs.

_And check the PR Author checklist is complete._

## Follow Up Work

- #8536

### CODE REVIEW

File: zebra-rpc/src/methods.rs [hunk 1]
```diff
@@ -504,30 +505,18 @@ where
         let (tip_height, tip_hash) = self
             .latest_chain_tip
             .best_tip_height_and_hash()
-            .ok_or_else(|| Error {
-                code: ErrorCode::ServerError(0),
-                message: "No Chain tip available yet".to_string(),
-                data: None,
-            })?;
+            .ok_or(to_error("No Chain tip available yet"))?;
```
Comment (arya2) [inline zebra-rpc/src/methods.rs]: Thank you for the clean up! Could we use the error conversion trait here?

```suggestion
            .ok_or_server_error("No Chain tip available yet")?;
```

File: zebra-rpc/src/methods.rs [hunk 2]
```diff
@@ -1938,3 +1751,12 @@ pub fn height_from_signed_int(index: i32, tip_height: Height) -> Result<Height>
...
 }
+
+/// Turns anything implementing [`ToString`] into [`Error`].
+fn to_error(err: impl ToString) -> Error {
+    Error {
+        code: ErrorCode::ServerError(0),
+        message: err.to_string(),
+        data: None,
+    }
+}
```
Comment (arya2) [inline zebra-rpc/src/methods.rs]: Could we replace all uses of this with `ok_or_server_error()`?

```suggestion
```

File: zebra-chain/src/orchard/tree.rs [hunk 3]
```diff
@@ -688,68 +701,3 @@ impl From<Vec<pallas::Base>> for NoteCommitmentTree {
...
-///
-/// The sparse format, used in this implementation, allows representing invalid
-/// commitment trees while the dense format allows representing only valid
-/// commitment trees.
-///
-/// It is likely that the dense format will be used in future RPCs, in which
-/// case the current implementation will have to change and use the format
-/// compatible with [`Frontier`](bridgetree::Frontier) instead.
-#[derive(Clone, Debug, Default, Eq, PartialEq, serde::Serialize)]
-pub struct SerializedTree(Vec<u8>);
```
Comment (arya2) [inline zebra-chain/src/orchard/tree.rs:715]: Could we move the documentation to the field on `GetTreestate`?

File: zebra-chain/src/sapling/tree.rs [hunk 4]
```diff
@@ -219,7 +217,7 @@ impl ToHex for Node {
     }
 }
 
-/// Required to convert [`NoteCommitmentTree`] into [`SerializedTree`].
+/// Required to serialize [`NoteCommitmentTree`]s in a format compatible with `zcashd`.
```
Comment (arya2) [inline zebra-chain/src/sapling/tree.rs]: Nitpick/Optional:

```suggestion
/// Required to serialize [`NoteCommitmentTree`]s in a format matching `zcashd`.
```

File: zebra-chain/src/sapling/tree.rs [hunk 5]
```diff
@@ -614,7 +612,21 @@ impl NoteCommitmentTree {
         assert_eq!(self.inner, other.inner);
 
         // Check the RPC serialization format (not the same as the Zebra database format)
-        assert_eq!(SerializedTree::from(self), SerializedTree::from(other));
+        assert_eq!(self.to_rpc_bytes(), other.to_rpc_bytes());
+    }
+
+    /// Serializes [`Self`] to a format compatible with `zcashd`'s RPCs.
```
Comment (arya2) [inline zebra-chain/src/sapling/tree.rs]:
```suggestion
    /// Serializes [`Self`] to a format matching `zcashd`'s RPCs.
```

File: zebra-rpc/Cargo.toml [hunk 6]
```diff
@@ -64,6 +64,8 @@ tracing = "0.1.39"
 hex = { version = "0.4.3", features = ["serde"] }
 serde = { version = "1.0.201", features = ["serde_derive"] }
 
+zcash_primitives = { version = "0.13.0" }
+
```
Comment (arya2) [inline zebra-rpc/Cargo.toml:68]: Nitpick/Optional: Could/Should we define an `is_nu_active()` method on Zebra's `Network` type instead?

```rust
    /// Accepts a network upgrade and a block height
    ///
    /// Returns true if the network upgrade is active at the provided height, or false otherwise.
    pub fn is_nu_active(&self, nu: NetworkUpgrade, height: Height) -> bool {
        nu.activation_height(self).map_or(false, |h| h <= height)
    }
```

```suggestion
```

File: zebra-rpc/src/methods.rs [hunk 7]
```diff
@@ -51,6 +50,8 @@ pub mod get_block_template_rpcs;
 #[cfg(feature = "getblocktemplate-rpcs")]
 pub use get_block_template_rpcs::{GetBlockTemplateRpc, GetBlockTemplateRpcImpl};
 
+use self::trees::GetTreestate;
```
Comment (arya2) [inline zebra-rpc/src/methods.rs]: This could be added to the `use::crate::methods::trees` on line 36, next to the `GetSubtrees` and `SubtreeRpcData` imports.

File: zebra-rpc/src/methods.rs [hunk 8]
```diff
@@ -504,30 +505,18 @@ where
         let (tip_height, tip_hash) = self
             .latest_chain_tip
             .best_tip_height_and_hash()
-            .ok_or_else(|| Error {
-                code: ErrorCode::ServerError(0),
-                message: "No Chain tip available yet".to_string(),
-                data: None,
-            })?;
+            .ok_or_server_error("No Chain tip available yet")?;
```
Comment (arya2) [inline zebra-rpc/src/methods.rs:506]: Optional/Nitpick: Could we use this method for `get_best_block_hash()` too?

Optional/Nitpick: Could/Should we update the `ok_or()` in `ok_or_server_error()` to `ok_or_else()`?

```rust
self.ok_or_else(|| jsonrpc_core::Error {
    code: ErrorCode::ServerError(0),
    message: message.to_string(),
    data: None,
})
```

File: zebra-rpc/src/methods.rs [hunk 9]
```diff
@@ -606,11 +595,7 @@ where
             let valid_addresses = address_strings.valid_addresses()?;
 
             let request = zebra_state::ReadRequest::AddressBalance(valid_addresses);
-            let response = state.oneshot(request).await.map_err(|error| Error {
-                code: ErrorCode::ServerError(0),
-                message: error.to_string(),
-                data: None,
-            })?;
+            let response = state.oneshot(request).await.map_err(to_error)?;
```
Comment (arya2) [inline zebra-rpc/src/methods.rs]: Could we replace `.map_err(to_error)` in this file with `map_server_error()`, like:

```suggestion
            let response = state.oneshot(request).await.map_server_error()?;
```

File: zebra-rpc/src/methods.rs [hunk 10]
```diff
@@ -1069,59 +1019,38 @@ where
...
                     verbose,
                 )),
-                zebra_state::ReadResponse::Transaction(None) => Err(Error {
-                    code: ErrorCode::ServerError(0),
-                    message: "Transaction not found".to_string(),
-                    data: None,
-                }),
+                zebra_state::ReadResponse::Transaction(None) => {
+                    Err(to_error("Transaction not found"))
+                }
```
Comment (arya2) [inline zebra-rpc/src/methods.rs]: We could replace this with:

```rust
let zebra_state::ReadResponse::Transaction(response) = state
    .ready()
    .and_then(|service| service.call(request))
    .await
    .map_server_error()?
else {
    unreachable!("unmatched response to a transaction request")
};

let MinedTx {
    tx,
    height,
    confirmations,
} = response.ok_or_server_error("Transaction not found")?;

Ok(GetRawTransaction::from_transaction(
    tx,
    Some(height),
    confirmations,
    verbose,
))
```

File: zebra-rpc/src/methods.rs [hunk 11]
```diff
@@ -1069,59 +1019,38 @@ where
...
         async move {
             // Convert the [`hash_or_height`] string into an actual hash or height.
-            let hash_or_height = hash_or_height
-                .parse()
-                .map_err(|error: SerializationError| Error {
-                    code: ErrorCode::ServerError(0),
-                    message: error.to_string(),
-                    data: None,
-                })?;
+            let hash_or_height = hash_or_height.parse().map_err(to_error)?;
```
Comment (arya2) [inline zebra-rpc/src/methods.rs]: Optional: If we want to get resolve the "use `height_from_signed_int()` to handle negative heights" TODO, could we replace this with something like:

```suggestion
            let hash_or_height = match hash_or_height.parse() {
                Ok(hash_or_height) => hash_or_height,
                Err(err) => height_from_signed_int(
                    hash_or_height.parse().map_err(|_| err).map_server_error()?,
                    latest_chain_tip
                        .best_tip_height()
                        .ok_or_server_error("No Chain tip available yet")?,
                )
                .map_server_error()?
                .into(),
            };
```

Optional: Could we do this in a function instead and use it in `get_block()` too?

File: zebra-rpc/src/methods.rs [hunk 12]
```diff
@@ -1069,59 +1019,38 @@ where
...
             }
         }
         .boxed()
     }
 
-    // TODO:
-    // - use a generic error constructor (#5548)
-    // - use `height_from_signed_int()` to handle negative heights
-    //   (this might be better in the state request, because it needs the state height)
-    // - create a function that handles block hashes or heights, and use it in `get_block()`
```
Comment (arya2) [inline zebra-rpc/src/methods.rs:1087]: Optional: I think this last TODO is outdated for the `get_block()` method too, could we get rid of it there as well?

File: zebra-rpc/src/methods.rs [hunk 13]
```diff
@@ -1069,59 +1019,38 @@ where
...
-            // Fetch the block referenced by [`hash_or_height`] from the state.
-            // TODO: If this RPC is called a lot, just get the block header,
-            // rather than the whole block.
-            let block_request = zebra_state::ReadRequest::Block(hash_or_height);
-            let block_response = state
+            // For consistency, this lookup must be performed first, then all the other lookups must
+            // be based on the hash.
+            //
+            // TODO: If this RPC is called a lot, just get the block header, rather than the whole
+            // block.
```
Comment (arya2) [inline zebra-rpc/src/methods.rs]: Optional/Nitpick:

```suggestion
            // TODO: If this RPC is called a lot, just get the block header, rather than the whole block.
```

File: zebra-rpc/src/methods.rs [hunk 14]
```diff
@@ -1133,73 +1062,54 @@ where
...
-                .and_then(|service| service.call(orchard_request))
-                .await
-                .map_err(|error| Error {
-                    code: ErrorCode::ServerError(0),
-                    message: error.to_string(),
-                    data: None,
-                })?;
+            let hash = hash_or_height
+                .hash_or_else(|_| Some(block.hash()))
+                .expect("block hash");
```
Comment (arya2) [inline zebra-rpc/src/methods.rs:1062]: Optional/Nitpick: Could we keep using `unwrap_or_else()` here?

```suggestion
            let hash = hash_or_height.hash().unwrap_or_else(|| block.hash());
```

File: zebra-rpc/src/methods.rs [hunk 15]
```diff
@@ -1133,73 +1062,54 @@ where
...
 
-            // We've got all the data we need for the RPC response, so we
-            // assemble the response.
-
-            let height = block
-                .coinbase_height()
-                .expect("verified blocks have a valid height");
+            let height = hash_or_height
+                .height_or_else(|_| block.coinbase_height())
+                .expect("block height");
```
Comment (arya2) [inline zebra-rpc/src/methods.rs]: Nitpick:

```suggestion
            let height = hash_or_height
                .height_or_else(|_| block.coinbase_height())
                .expect("verified blocks have a coinbase height");
```

File: zebra-rpc/src/methods/tests/snapshot.rs [hunk 16]
```diff
@@ -40,6 +49,105 @@ async fn test_rpc_response_data() {
...
+    // Request the treestate for an invalid height.
+    let rsp = rpc
+        .z_get_treestate(EXCESSIVE_BLOCK_HEIGHT.to_string())
+        .await;
+    settings.bind(|| insta::assert_json_snapshot!("z_get_treestate_excessive_block_height", rsp));
+
+    // Request the treestate for an unparsable hash or height.
+    let rsp = rpc.z_get_treestate("Do you even shield?".to_string()).await;
+    settings
+        .bind(|| insta::assert_json_snapshot!("z_get_treestate_unparsable_hash_or_height", rsp));
```
Comment (arya2) [inline zebra-rpc/src/methods/tests/snapshot.rs]: Optional/Nitpick: It seems the snapshots include the variable name, `tree_state` may be a bit more descriptive?

```suggestion
    let tree_state = rpc
        .z_get_treestate(blocks[0].hash().to_string())
        .await
        .expect("genesis treestate = no treestate");
    settings.bind(|| insta::assert_json_snapshot!("z_get_treestate_by_hash", tree_state));

    // Request the treestate by a hash for a block which is not in the state.
    let tree_state = rpc.z_get_treestate(block::Hash([0; 32]).to_string()).await;
    settings
        .bind(|| insta::assert_json_snapshot!("z_get_treestate_by_non_existent_hash", tree_state));

    // Request the treestate before Sapling activation.
    let tree_state = rpc
        .z_get_treestate((SAPLING_ACTIVATION_HEIGHT - 1).to_string())
        .await
        .expect("no Sapling treestate and no Orchard treestate");
    settings.bind(|| insta::assert_json_snapshot!("z_get_treestate_no_treestate", tree_state));

    // Request the treestate at Sapling activation.
    let tree_state = rpc
        .z_get_treestate(SAPLING_ACTIVATION_HEIGHT.to_string())
        .await
        .expect("empty Sapling treestate and no Orchard treestate");
    settings.bind(|| {
        insta::assert_json_snapshot!("z_get_treestate_empty_Sapling_treestate", tree_state)
    });

    // Request the treestate for an invalid height.
    let tree_state = rpc
        .z_get_treestate(EXCESSIVE_BLOCK_HEIGHT.to_string())
        .await;
    settings.bind(|| {
        insta::assert_json_snapshot!("z_get_treestate_excessive_block_height", tree_state)
    });

    // Request the treestate for an unparsable hash or height.
    let tree_state = rpc.z_get_treestate("Do you even shield?".to_string()).await;
    settings.bind(|| {
        insta::assert_json_snapshot!("z_get_treestate_unparsable_hash_or_height", tree_state)
    });
```

**Review by arya2 — DISMISSED** [review]
This looks good! Thank you for the clean up with error construction and moving types to the `trees` module.

Feel free to resolve these comments if you want to merge this, they're all clean up except the one about the "use `height_from_signed_int()`" TODO, that one would be nice to have, but it could also go in another PR.

File: zebra-rpc/Cargo.toml (hunk 6 above)
Comment (upbqdn) [reply zebra-rpc/Cargo.toml:68]: I'd lean towards using upstream libs so we don't need to reimplement and maintain the functionality that exists elsewhere.

File: zebra-chain/src/orchard/tree.rs (hunk 3 above)
Comment (upbqdn) [reply zebra-chain/src/orchard/tree.rs:715]: Done in [829ae6b](https://github.com/ZcashFoundation/zebra/pull/8533/commits/829ae6b558f0d4cc90cd87394e272b9eb0349867).

File: zebra-rpc/src/methods.rs (hunk 2 above)
Comment (upbqdn) [reply zebra-rpc/src/methods.rs]: Done in [2c3a8db](https://github.com/ZcashFoundation/zebra/pull/8533/commits/2c3a8dbe8f3dd4a5bb256829c2e44f993d8d32de).

File: zebra-rpc/src/methods.rs (hunk 7 above)
Comment (upbqdn) [reply zebra-rpc/src/methods.rs]: Done in [763d896](https://github.com/ZcashFoundation/zebra/pull/8533/commits/763d896b38858982ae24d6c882c58841d83b1691).

File: zebra-rpc/src/methods.rs (hunk 9 above)
Comment (upbqdn) [reply zebra-rpc/src/methods.rs]: Done in [2c3a8db](https://github.com/ZcashFoundation/zebra/pull/8533/commits/2c3a8dbe8f3dd4a5bb256829c2e44f993d8d32de).

File: zebra-rpc/src/methods.rs (hunk 8 above)
Comment (upbqdn) [reply zebra-rpc/src/methods.rs:506]: > Optional/Nitpick: Could we use this method for `get_best_block_hash()` too?

Done in [9a282ce](https://github.com/ZcashFoundation/zebra/pull/8533/commits/9a282cee80bc9e5fabf2185499671467558c151c).

> Optional/Nitpick: Could/Should we update the `ok_or()` in `ok_or_server_error()` to `ok_or_else()`?

I'm good with `ok_or`.

File: zebra-rpc/src/methods.rs (hunk 10 above)
Comment (upbqdn) [reply zebra-rpc/src/methods.rs]: I think that refactor would be too distant from this PR's intention. I did a simpler one in [2c3a8db](https://github.com/ZcashFoundation/zebra/pull/8533/commits/2c3a8dbe8f3dd4a5bb256829c2e44f993d8d32de).

File: zebra-rpc/Cargo.toml [hunk 17]
```diff
@@ -64,6 +64,8 @@ tracing = "0.1.39"
 hex = { version = "0.4.3", features = ["serde"] }
 serde = { version = "1.0.201", features = ["serde_derive"] }
 
+zcash_primitives = { version = "0.13.0" }
```
Comment (oxarbitrage) [inline zebra-rpc/Cargo.toml:67]:
```suggestion
zcash_primitives = { version = "0.14.0" }
```

Can we go straight to version 0.14 ?

File: Cargo.lock [hunk 18]
```diff
@@ -6191,6 +6191,7 @@ dependencies = [
  "tower",
  "tracing",
  "zcash_address",
+ "zcash_primitives 0.13.0",
```
Comment (oxarbitrage) [inline Cargo.lock:6194]:
```suggestion
 "zcash_primitives 0.14.0",
```

If we use version 0.14.0 as suggested in https://github.com/ZcashFoundation/zebra/pull/8533#discussion_r1607137444 and build then this should automatically change but if we apply suggestions from github without building then we should add this one as well.

**Review by oxarbitrage — DISMISSED** [review]
Thanks, i think it looks great. I love the amount of code we were able to remove from Zebra here.

File: zebra-rpc/src/methods.rs (hunk 11 above)
Comment (upbqdn) [reply zebra-rpc/src/methods.rs]: The docs for the `z_get_treestate` say:

_The zcashd doc reference says that the parameter "`height` can be
negative where -1 is the last known valid block". On the other hand,
`lightwalletd` only uses positive heights, so Zebra does not support
negative heights._

I added a TODO regarding the negative heights in [641fd71](https://github.com/ZcashFoundation/zebra/pull/8533/commits/641fd718a19f847e8a078f25ed63c2ab937a00cc). If there isn't an API consumer in need of the functionality, I'd lean towards not implementing it.

If we decide to implement it, I'd prefer to do it in a different PR to keep the scope of the current one small.

File: zebra-rpc/src/methods.rs (hunk 12 above)
Comment (upbqdn) [reply zebra-rpc/src/methods.rs:1087]: Done in [787aea0](https://github.com/ZcashFoundation/zebra/pull/8533/commits/787aea079435b39971684f3bd5175957bba052e9).

File: zebra-rpc/Cargo.toml (hunk 17 above)
Comment (upbqdn) [reply zebra-rpc/Cargo.toml:67]: If we bump `zcash_primitives` in `zebra-rpc`, we should also bump it in `zebra-chain` because that's where we impl `zcash_primitives::consensus::Parameters`. However, bumping `zcash_primitives` in `zebra-chain` requires many other changes, so I reverted the bump in [318f945](https://github.com/ZcashFoundation/zebra/pull/8533/commits/318f945d2026a4cdbb8323a30d4b90b99e4de3ab).

Comment (oxarbitrage) [reply zebra-rpc/Cargo.toml:67]: Yea, that makes sense. Sorry about that, we can update later.

**Review by oxarbitrage — APPROVED** [review]

**Comment by oxarbitrage** [comment]
@mergifyio refresh
