### PR TITLE
fix(rpc): Avoid selecting duplicate transactions in block templates

### LINKED ISSUE #5982: Zebra's block template can contain duplicate transactions
## Motivation

When I use `zebra-utils/zcash-rpc-block-template-to-proposal` from PR #5944 to send a block proposal from Zebra to both `zcashd` and Zebra, I see these errors in Zebra's block template:
```
Node said proposal was invalid, error response from /run/user/1000/tmp.Kr4uDEHYbz.block-template-proposal/proposal-check-getblocktemplate-proposal.CurTime.8232.json:
bad-txns-inputs-missingorspent
Node said proposal was invalid, error response from /run/user/1000/tmp.Kr4uDEHYbz.block-template-proposal/proposal-check-getblocktemplate-proposal.CurTime.28232.json:
{
  "reject_reason": "rejected",
  "capabilities": [
    "proposal"
  ]
}
```

The template in template-getblocktemplate-template.json contains two copies of transaction `f7b68748b40a49bf7cb0ce8b9565a29bfd65cd917c68d0ee18feaf2614055608`. This is incorrect and breaks a consensus rule.

Both Zebra and `zcashd` agree that this block proposal is invalid.

This bug is a blocker for mining pools using Zebra, because it produces invalid blocks.

### Specifications

Duplicate transactions are invalid because of the consensus rules that prevent:
- double-spending a transparent input
- revealing a shielded spend nullifier that has already been revealed

### Complex Code or Requirements

It is difficult to reproduce this bug, because it depends on the mempool's state at the time, and the chain tips of both nodes.

But the bug isn't happening due to a chain fork or a concurrent block commit, that would be a previous block hash error.

### Testing

We might need to re-test with the same script a few times to reproduce this error, and make sure it is gone.

### Tasks

- [ ] Fix the consensus bug in the block proposal or mempool code

### PR DESCRIPTION
**Pull request by arya2**
## Motivation

The block template should not contain duplicate transactions.

Closes #5982.

## Solution

- Logs hashes of mempool transactions returned by `FullTransactions` request.
- Logs selected mempool transaction hashes and unpaid actions.
- Removes candidate transactions from candidate transaction collections during selection.

## Review

Part of regular scheduled work.

### Reviewer Checklist

  - [x] Will the PR name make sense to users?
    - [ ] Does it need extra CHANGELOG info? (new features, breaking changes, large changes)
  - [x] Are the PR labels correct?
  - [ ] Does the code do what the ticket and PR says?
    - [x] Does it change concurrent code, unsafe code, or consensus rules?
  - [ ] How do you know it works? Does it have tests?

### CODE REVIEW

File: zebra-rpc/src/methods/get_block_template_rpcs/types/get_block_template.rs [hunk 1]
```diff
@@ -209,11 +209,12 @@ impl GetBlockTemplate {
...
             // Sort in serialized data order, excluding the length byte.
             // `zcashd` sometimes seems to do this, but other times the order is arbitrary.
-            mempool_txs_with_templates.sort_by_key(|(tx_template, _tx)| tx_template.data.clone());
+            mempool_txs_with_templates
+                .sort_by_cached_key(|(tx_template, _tx)| tx_template.data.clone());
         } else {
             // Sort by hash, this is faster.
             mempool_txs_with_templates
-                .sort_by_key(|(tx_template, _tx)| tx_template.hash.bytes_in_display_order());
+                .sort_by_cached_key(|(tx_template, _tx)| tx_template.hash.bytes_in_display_order());
```
Comment (teor2345) [inline zebra-rpc/src/methods/get_block_template_rpcs/types/get_block_template.rs]: Nitpick: Are you sure that this change improves performance?

> For simple key functions (e.g., functions that are property accesses or basic operations), [sort_by_key](https://doc.rust-lang.org/std/primitive.slice.html#method.sort_by_key) is likely to be faster.

https://doc.rust-lang.org/std/vec/struct.Vec.html#method.sort_by_cached_key

`sort_by_cached_key` calls more complex code, and it uses extra memory, so it's only worth doing if we think it will make a difference.

It's unlikely to be faster for the reversed hash, but it might be faster for large data. However, `sort_by_cached_key` also makes it impossible for the compiler to eliminate the clone, because it stores the cloned value.

File: zebra-rpc/src/methods/get_block_template_rpcs/zip317.rs [hunk 2]
```diff
@@ -201,20 +201,13 @@ fn checked_add_transaction_weighted_random(
...
-    if weighted_index
-        .update_weights(&[(candidate_position, &0.0)])
-        .is_err()
-    {
-        // All weights are zero, so each transaction has either been selected or rejected
-        (None, candidate_tx)
-    } else {
-        (Some(weighted_index), candidate_tx)
-    }
+    // All weights are zero, so each transaction has either been selected or rejected
```
Comment (teor2345) [inline zebra-rpc/src/methods/get_block_template_rpcs/zip317.rs]: These remaining comments are both incorrect now.

File: zebra-rpc/src/methods/get_block_template_rpcs.rs [hunk 3]
```diff
@@ -568,6 +568,14 @@ where
             let next_block_height =
                 (chain_tip_and_local_time.tip_height + 1).expect("tip is far below Height::MAX");
 
+            tracing::info!(
```
Comment (teor2345) [inline zebra-rpc/src/methods/get_block_template_rpcs.rs]: Can make all these logs debug or trace level?

They could be too verbose for users if there are a lot of transactions in the mempool or block.

Nitpick: Rust style does not start logs or error messages with a capital letter. I think that's because they are often added to an existing formatted line or sentence.

File: zebra-rpc/src/methods/get_block_template_rpcs/zip317.rs [hunk 4]
```diff
@@ -201,20 +201,13 @@ fn checked_add_transaction_weighted_random(
...
+    (setup_fee_weighted_index(&candidate_txs), candidate_tx)
```
Comment (teor2345) [inline zebra-rpc/src/methods/get_block_template_rpcs/zip317.rs]: Let's explain why we have to regenerate the index every time, so we don't try to optimise this code in future, and re-introduce the bug.

```suggestion
    // We have to regenerate this index each time we choose a transaction, due to floating-point sum inaccuracies.
    // If we don't, some chosen transactions can end up with a tiny non-zero weight, leading to duplicates.
    // <https://github.com/rust-random/rand/blob/4bde8a0adb517ec956fcec91665922f6360f974b/src/distributions/weighted_index.rs#L173-L183>
    (setup_fee_weighted_index(&candidate_txs), candidate_tx)
```

File: zebra-rpc/src/methods/get_block_template_rpcs/zip317.rs [hunk 5]
```diff
@@ -201,20 +201,13 @@ fn checked_add_transaction_weighted_random(
...
+    candidate_txs: &mut Vec<VerifiedUnminedTx>,
+    weighted_index: WeightedIndex<f32>,
 ) -> (Option<WeightedIndex<f32>>, VerifiedUnminedTx) {
     let candidate_position = weighted_index.sample(&mut thread_rng());
-    let candidate_tx = candidate_txs[candidate_position].clone();
+    let candidate_tx = candidate_txs.swap_remove(candidate_position);
 
     // Only pick each transaction once, by setting picked transaction weights to zero
-    if weighted_index
-        .update_weights(&[(candidate_position, &0.0)])
```
Comment (teor2345) [inline zebra-rpc/src/methods/get_block_template_rpcs/zip317.rs:212]: Optional: Once we're sure this works, did you want to submit a PR to update the `update_weights` documentation?
https://github.com/rust-random/rand/blob/master/src/distributions/weighted_index.rs#L144

**Review by teor2345 — COMMENTED** [review]
Looks good, just a few tweaks for usability and maintenance.

How do you know this fix works?
Can you find a second reviewer for this PR?

File: zebra-rpc/src/methods/get_block_template_rpcs/types/get_block_template.rs (hunk 1 above)
Comment (arya2) [reply zebra-rpc/src/methods/get_block_template_rpcs/types/get_block_template.rs]: I'm not sure, I don't think it'll make a big difference either way so I'll revert this for now and might write a quick benchmark to check later.

Reverted in [`b1cec4f`](https://github.com/ZcashFoundation/zebra/pull/6006/commits/b1cec4fb44d64521b16adca1532ead59a9104d51).

**Comment by arya2** [comment]
> Looks good, just a few tweaks for usability and maintenance.
> 
> How do you know this fix works? 

It failed about 10 in ~30 tests before the change and 0 in ~20 tests after the change.

I checked the logic for the mempool and it shouldn't be returning any duplicate transactions, I also checked the hashes returned by the `FullTransactions` request several times to be sure that the duplicates were from the selection logic. 

The new selection logic doesn't clone candidate transactions anymore so I think that guarantees against duplication there. 

I tried to be thorough in confirming that the new logic works, I think `update_weights` wasn't behaving as expected due to subtracting floating point values from the total weight.

> Can you find a second reviewer for this PR?

Good idea, I added @oxarbitrage as a reviewer.

File: zebra-rpc/src/methods/get_block_template_rpcs/zip317.rs (hunk 5 above)
Comment (arya2) [reply zebra-rpc/src/methods/get_block_template_rpcs/zip317.rs:212]: Yeah that sounds good, I'll open a PR to ideally fix the bug (I think this is just undesirable behaviour) or at least update the documentation.

File: zebra-rpc/src/methods/get_block_template_rpcs/zip317.rs (hunk 2 above)
Comment (arya2) [reply zebra-rpc/src/methods/get_block_template_rpcs/zip317.rs]: Removed in [`b1cec4f`](https://github.com/ZcashFoundation/zebra/pull/6006/commits/b1cec4fb44d64521b16adca1532ead59a9104d51).

File: zebra-rpc/src/methods/get_block_template_rpcs.rs (hunk 3 above)
Comment (arya2) [reply zebra-rpc/src/methods/get_block_template_rpcs.rs]: > Can make all these logs debug or trace level?

Yep, I agree these are too verbose for info-level logs, fixed in [`b1cec4f`](https://github.com/ZcashFoundation/zebra/pull/6006/commits/b1cec4fb44d64521b16adca1532ead59a9104d51).

> Nitpick: Rust style does not start logs or error messages with a capital letter. I think that's because they are often added to an existing formatted line or sentence.

Fixed in [`b1cec4f`](https://github.com/ZcashFoundation/zebra/pull/6006/commits/b1cec4fb44d64521b16adca1532ead59a9104d51).

File: zebra-rpc/src/methods/get_block_template_rpcs/zip317.rs (hunk 4 above)
Comment (arya2) [reply zebra-rpc/src/methods/get_block_template_rpcs/zip317.rs]: Good idea, thank you. Applied in [`b1cec4f`](https://github.com/ZcashFoundation/zebra/pull/6006/commits/b1cec4fb44d64521b16adca1532ead59a9104d51).

Comment (daira) [reply zebra-rpc/src/methods/get_block_template_rpcs/zip317.rs]: Btw I've never liked that zcashd uses floating point here, and that is something we might change. Let us know if you want to change it to integer or fixed point arithmetic.

**Review by oxarbitrage — APPROVED** [review]
I think it looks good, i made a few manual calls and got no duplicates. 

I was thinking on making a script that just runs `getblocktemplate` and check there are no duplicate transactions however i am not really sure if it worth it. 

If we think it does, we can think on the test for it in a separated issue with lower priority.

File: zebra-rpc/src/methods/get_block_template_rpcs/zip317.rs (hunk 5 above)
Comment (teor2345) [reply zebra-rpc/src/methods/get_block_template_rpcs/zip317.rs:212]: I don't think it's possible to fix the bug, because doing an efficient weights update requires re-using partial sums. That works fine for integers, but floating-point sums can't be re-ordered.

**Comment by teor2345** [comment]
> > Looks good, just a few tweaks for usability and maintenance.
> > How do you know this fix works?
> 
> It failed about 10 in ~30 tests before the change and 0 in ~20 tests after the change.
> 
> I checked the logic for the mempool and it shouldn't be returning any duplicate transactions, I also checked the hashes returned by the `FullTransactions` request several times to be sure that the duplicates were from the selection logic.
> 
> The new selection logic doesn't clone candidate transactions anymore so I think that guarantees against duplication there.
> 
> I tried to be thorough in confirming that the new logic works, I think `update_weights` wasn't behaving as expected due to subtracting floating point values from the total weight.

We already have a CI test PR that will catch this bug, so I don't think we need any other tests.

File: zebra-rpc/src/methods/get_block_template_rpcs/zip317.rs (hunk 4 above)
Comment (teor2345) [reply zebra-rpc/src/methods/get_block_template_rpcs/zip317.rs]: We could use fixed point with u64, and scale the fee by 2^13 before dividing. That would get us close to the maximum number of actions. (Which I think is roughly 300K for transparent outputs.)

But we don't need to make that change any time soon, we're focused on finishing off all the RPCs that miners need.
