### PR TITLE
test(fix): Uncomment & update `disconnects_from_misbehaving_peers`

### LINKED ISSUE #9305: Fix and restore the `disconnects_from_misbehaving_peers` test
## Motivation

This test was commented out as it was causing CI failures due to a concurrency bug.

It's important test coverage that should be restored ahead of zcashd deprecation.

This issue could also track extending the test to check for the expected behaviour for every variant of errors with a `misbehavior_score()` or `mempool_misbehavior_score()` method.

### PR DESCRIPTION
**Pull request by oxarbitrage**
## Motivation

Restore `disconnects_from_misbehaving_peers` test

Close https://github.com/ZcashFoundation/zebra/issues/9305

## Solution

- Restore test (https://github.com/ZcashFoundation/zebra/pull/9735/commits/2c490991b8169a95885140590dbfb41892a75cbe)
- Fix import (https://github.com/ZcashFoundation/zebra/pull/9735/commits/acc81f6f262de32914357ea90f82aafc70f58cda)
- Add improvments (https://github.com/ZcashFoundation/zebra/pull/9735/commits/3e15e56d687d3699b8ac06514d12253cfeca5c52)

## Tests

- Passing locally all times. I was not able to find any failure by now with the new version after running it at least 10 times.

### PR Checklist

- [x] The PR name is suitable for the release notes.
- [x] The solution is tested.
- [x] The documentation is up to date.

### CODE REVIEW

**Comment by oxarbitrage** [comment]
@mergifyio refresh

**Comment by oxarbitrage** [comment]
I was able to see the test hanging in CI and locally 1 time today. I suspect this can be that `LAUNCH_DELAY` is not enough time so i am now testing with an additional waiting connection time on top of that in https://github.com/ZcashFoundation/zebra/pull/9735/commits/e686922fcf15310d7edf4971b55d5d0fcb08c327

Slow connections are being tracked at https://github.com/ZcashFoundation/zebra/issues/9721

The test is run by CI in https://github.com/ZcashFoundation/zebra/actions/runs/16683179527/job/47226466776#step:12:5876 so i am re-running that workflow a few times to see if that fixes the issue.

**Comment by oxarbitrage** [comment]
Attempt 2 running at: https://github.com/ZcashFoundation/zebra/actions/runs/16683179527

**Comment by oxarbitrage** [comment]
Attempt 3 running at https://github.com/ZcashFoundation/zebra/actions/runs/16683179527

**Comment by oxarbitrage** [comment]
Attempt 4: https://github.com/ZcashFoundation/zebra/actions/runs/16683179527

**Comment by oxarbitrage** [comment]
Attempt 4 failed https://github.com/ZcashFoundation/zebra/actions/runs/16683179527/job/47409601641?pr=9735

I increased the connection time a bit more to make a new set of tests at https://github.com/ZcashFoundation/zebra/pull/9735/commits/3d725cc4a20e84b92b82a04e3c5e86240369d1aa.

**Comment by oxarbitrage** [comment]
Attempt 2 after connection timeout was increased: https://github.com/ZcashFoundation/zebra/actions/runs/16751607658

**Comment by oxarbitrage** [comment]
Attempt 3: https://github.com/ZcashFoundation/zebra/actions/runs/16751607658

**Comment by oxarbitrage** [comment]
Attempt 4: https://github.com/ZcashFoundation/zebra/actions/runs/16751607658

**Comment by oxarbitrage** [comment]
Attempt 5: https://github.com/ZcashFoundation/zebra/actions/runs/16751607658

**Comment by oxarbitrage** [comment]
Attempt 6: https://github.com/ZcashFoundation/zebra/actions/runs/16751607658

**Comment by oxarbitrage** [comment]
Attempt 7: https://github.com/ZcashFoundation/zebra/actions/runs/16751607658

**Comment by oxarbitrage** [comment]
Attempt 8: https://github.com/ZcashFoundation/zebra/actions/runs/16751607658

**Comment by oxarbitrage** [comment]
Test passing at https://github.com/ZcashFoundation/zebra/actions/runs/17976977788/job/51132779183?pr=9735#step:8:870

File: zebra-chain/src/parameters/network/testnet.rs [hunk 1]
```diff
@@ -746,6 +746,16 @@ impl ParametersBuilder {
         self
     }
 
+    /// Clears checkpoints from the [`Parameters`] being built,
+    /// keep only the genesis checkpoint.
+    pub fn clear_checkpoints(mut self) -> Self {
+        self.checkpoints = Arc::new(
+            CheckpointList::from_list([(block::Height(0), self.genesis_hash)])
```
Comment (arya2) [inline zebra-chain/src/parameters/network/testnet.rs]: It would be simpler for this method to call `with_checkpoints(ConfiguredCheckpoints::Default(false))`

File: zebra-rpc/src/lib.rs [hunk 2]
```diff
@@ -20,5 +20,6 @@ pub use methods::types::{
         fetch_state_tip_and_local_time, generate_coinbase_and_roots,
         proposal::proposal_block_from_template,
     },
+    peer_info::PeerInfo, // Used by `disconnects_from_misbehaving_peers` acceptance test.
```
Comment (arya2) [inline zebra-rpc/src/lib.rs]: This type should be exported from the `client` module.

**Review by arya2 — DISMISSED** [review]
This looks good, thank you!

File: zebra-chain/src/parameters/network/testnet.rs (hunk 1 above)
Comment (oxarbitrage) [reply zebra-chain/src/parameters/network/testnet.rs]: Thanks, that is convinient.

Changes done at https://github.com/ZcashFoundation/zebra/pull/9735/commits/122ad89c2bb1f585f38d64f1c128fed2f1afda9b

File: zebra-rpc/src/lib.rs (hunk 2 above)
Comment (oxarbitrage) [reply zebra-rpc/src/lib.rs]: Sorry, i was supposed to fix this before pushing but never did. Thanks!

Fixed at https://github.com/ZcashFoundation/zebra/pull/9735/commits/2c3bb5bc590feb156af615d70c3ca9482b05d20a

**Comment by oxarbitrage** [comment]
@Mergifyio update

**Review by arya2 — APPROVED** [review]
