### PR TITLE
change(rpc): Adds ignored jsonrequestobject argument to the getblocktemplate RPC

### LINKED ISSUE #5495: Ignore the `jsonrequestobject` argument to the `getblocktemplate` RPC
## Motivation

Our stub `getblocktemplate` RPC will fail if it gets any arguments.

But we want to ignore the optional `jsonrequestobject` argument instead, because we're not going to support any optional features requested by clients.

### Specifications

https://zcash.github.io/rpc/getblocktemplate.html

### Designs

Accept an Option<String> argument and ignore it.

## Related Work

If we discover that clients need optional features, we can parse the argument and implement them later.

### PR DESCRIPTION
**Pull request by arya2**
## Motivation

We want to accept and ignore an optional jsonrequestobject in the getblocktemplate RPC.

Closes #5495.

## Solution

- Add an optional argument to the `getblocktemplate` method.

## Review

Part of regular scheduled work.

### Reviewer Checklist

  - [ ] Will the PR name make sense to users?
    - [ ] Does it need extra CHANGELOG info? (new features, breaking changes, large changes)
  - [ ] Are the PR labels correct?
  - [ ] Does the code do what the ticket and PR says?
  - [ ] How do you know it works? Does it have tests?

### CODE REVIEW

File: zebra-rpc/src/methods/get_block_template_rpcs/types/get_block_template.rs [hunk 1]
```diff
@@ -9,6 +9,40 @@ use crate::methods::{
...
+    Proposal,
+    ServerList,
+    WorkId,
+}
+
+/// Optional `jsonparametersobject` argument
+#[derive(Debug, serde::Deserialize)]
+pub struct JsonParameters {
+    #[serde(default)]
+    pub mode: GetBlockTemplateRequestMode,
```
Comment (teor2345) [inline zebra-rpc/src/methods/get_block_template_rpcs/types/get_block_template.rs]: I think mode is optional according to the spec?
https://en.bitcoin.it/wiki/BIP_0022#Block_Template_Request

I understand that serde substitutes the default, but that also needs to be documented.

File: zebra-rpc/src/methods/get_block_template_rpcs/types/get_block_template.rs [hunk 2]
```diff
@@ -9,6 +9,40 @@ use crate::methods::{
     GetBlockHash,
 };
 
+#[derive(Debug, serde::Deserialize)]
+#[serde(rename_all = "lowercase")]
+pub enum GetBlockTemplateRequestMode {
+    Template,
+    Proposal,
+}
```
Comment (teor2345) [inline zebra-rpc/src/methods/get_block_template_rpcs/types/get_block_template.rs]: Please document where the list of modes comes from, and what each mode means:
https://en.bitcoin.it/wiki/BIP_0022#Block_Template_Request
https://en.bitcoin.it/wiki/BIP_0023#Block_Proposal

This will fail if a client specifies a mode we don't know about.
Would it make sense to have an `UnknownMode(String)` variant?
Or should we error, because we can't provide the correct response to an unknown mode?

File: zebra-rpc/src/methods/get_block_template_rpcs/types/get_block_template.rs [hunk 3]
```diff
@@ -9,6 +9,40 @@ use crate::methods::{
...
+
+#[derive(Debug, serde::Deserialize)]
+#[serde(rename_all = "lowercase")]
+pub enum GetBlockTemplateCapability {
+    LongPoll,
+    CoinbaseTxn,
+    CoinbaseValue,
+    Proposal,
+    ServerList,
+    WorkId,
```
Comment (teor2345) [inline zebra-rpc/src/methods/get_block_template_rpcs/types/get_block_template.rs]: This list is missing the mutations:
https://en.bitcoin.it/wiki/BIP_0022#Block_Template_Request

This will fail if a client specifies a capability we don't know about.
Would it make sense to have an `UnknownCapability(String)` variant?

File: zebra-rpc/src/methods/get_block_template_rpcs/types/get_block_template.rs [hunk 4]
```diff
@@ -9,6 +9,40 @@ use crate::methods::{
...
+}
+
+/// Optional `jsonparametersobject` argument
+#[derive(Debug, serde::Deserialize)]
+pub struct JsonParameters {
+    #[serde(default)]
+    pub mode: GetBlockTemplateRequestMode,
+    #[serde(default)]
+    pub capabilities: Vec<GetBlockTemplateCapability>,
+    pub longpollid: Option<String>,
```
Comment (teor2345) [inline zebra-rpc/src/methods/get_block_template_rpcs/types/get_block_template.rs]: If we include the `longpollid` field but ignore it, then clients will expect us to handle it correctly. But we can't do that until we implement #5720.

If we don't list this field, then the RPC will return an error, and the client should stop trying to long poll:
https://en.bitcoin.it/wiki/BIP_0022#Optional:_Long_Polling

**Review by teor2345 — CHANGES_REQUESTED** [review]
Looks good, but I think we might want to return errors for some unsupported arguments.

~~We're missing documentation on all these new types. Please make the types modules and the other getblocktemplate RPC modules public, so documentation is required by CI.~~

What tests do we need for this?

File: zebra-rpc/src/methods/get_block_template_rpcs/types/get_block_template.rs (hunk 2 above)
Comment (arya2) [reply zebra-rpc/src/methods/get_block_template_rpcs/types/get_block_template.rs]: I think it should be an error.

Updated in [`575deba`](https://github.com/ZcashFoundation/zebra/pull/5772/commits/575debad65065ec49e332709dad682847f3c9492).

File: zebra-rpc/src/methods/get_block_template_rpcs/types/get_block_template.rs (hunk 1 above)
Comment (arya2) [reply zebra-rpc/src/methods/get_block_template_rpcs/types/get_block_template.rs]: Yeah, updated docs to say "all other fields are optional" in [`575deba`](https://github.com/ZcashFoundation/zebra/pull/5772/commits/575debad65065ec49e332709dad682847f3c9492).

File: zebra-rpc/src/methods/get_block_template_rpcs/types/get_block_template.rs (hunk 3 above)
Comment (arya2) [reply zebra-rpc/src/methods/get_block_template_rpcs/types/get_block_template.rs]: I commented it out and used a `Vec<String>` instead in [`423f546`](https://github.com/ZcashFoundation/zebra/pull/5772/commits/423f546839628d32b6fd93e609d6a45506bb847a). I'm not sure if `UnknownCapability(String)` would work, but it should definitely accept all valid options.

File: zebra-rpc/src/methods/get_block_template_rpcs/types/get_block_template.rs (hunk 4 above)
Comment (arya2) [reply zebra-rpc/src/methods/get_block_template_rpcs/types/get_block_template.rs]: Updated in [`9209e03`](https://github.com/ZcashFoundation/zebra/pull/5772/commits/9209e031c95a08328530fad2278cea0902abb03c) to return an error saying it's currently unsupported.

**Comment by teor2345** [comment]
> We're missing documentation on all these new types. Please make the types modules and the other getblocktemplate RPC modules public, so documentation is required by CI.

I did this in PR #5776, because the missing docs impacted that PR as well.

File: zebra-rpc/src/methods/get_block_template_rpcs/types/get_block_template_opts.rs [hunk 5]
```diff
@@ -0,0 +1,91 @@
...
+    /// Currently ignored by zcashd and zebra.
+    ServerList,
+
+    /// Currently ignored by zcashd and zebra.
+    WorkId,
+
+    /// Mutations
+    // TODO: Fill out valid mutations capabilities.
+    UnknownCapability(String),
+}
```
Comment (teor2345) [inline zebra-rpc/src/methods/get_block_template_rpcs/types/get_block_template_opts.rs]: I think this can work using `#[serde(other)]`, but I'm not sure of the exact syntax:
https://serde.rs/variant-attrs.html#other
https://serde.rs/enum-representations.html#internally-tagged

```suggestion
#[derive(Clone, Debug, PartialEq, Eq, serde::Deserialize)]
#[serde(tag = "type", rename_all = "lowercase")]
pub enum GetBlockTemplateCapability {
    /// Long Polling support.
    /// Currently ignored by zebra.
    LongPoll,

    /// Information for coinbase transaction, default template data with the `coinbasetxn` field.
    /// Currently ignored by zebra.
    CoinbaseTxn,

    /// Coinbase value, template response provides a `coinbasevalue` field and omits `coinbasetxn` field.
    /// Currently ignored by zebra.
    CoinbaseValue,

    /// Components of the coinbase transaction.
    /// Currently ignored by zebra.
    CoinbaseAux,

    /// Currently ignored by zcashd and zebra.
    Proposal,

    /// Currently ignored by zcashd and zebra.
    ServerList,

    /// Currently ignored by zcashd and zebra.
    WorkId,

    /// Mutations
    #[serde(other)]
    UnknownCapability(String),
}
```

File: zebra-rpc/src/methods/get_block_template_rpcs/types/get_block_template_opts.rs [hunk 6]
```diff
@@ -0,0 +1,91 @@
+//! Parameter types for the `getblocktemplate` RPC.
+
+use super::hex_data::HexData;
+
+/// Defines whether the RPC method should generate a block template or attempt to validate a block proposal.
+/// `Proposal` mode is currently unsupported and will return an error.
+#[derive(Debug, serde::Deserialize, PartialEq, Eq)]
```
Comment (teor2345) [inline zebra-rpc/src/methods/get_block_template_rpcs/types/get_block_template_opts.rs]: Nitpick:
```suggestion
#[derive(Clone, Debug, serde::Deserialize, PartialEq, Eq)]
```

File: zebra-rpc/src/methods/get_block_template_rpcs/types/get_block_template_opts.rs [hunk 7]
```diff
@@ -0,0 +1,91 @@
...
+    /// Mutations
+    // TODO: Fill out valid mutations capabilities.
+    UnknownCapability(String),
+}
+
+/// Optional argument `jsonrequestobject` for `getblocktemplate` RPC request.
+///
+/// The `data` field must be provided in `proposal` mode, and must be omitted in `template` mode.
+/// All other fields are optional.
+#[derive(Debug, serde::Deserialize, Default)]
```
Comment (teor2345) [inline zebra-rpc/src/methods/get_block_template_rpcs/types/get_block_template_opts.rs]: Nitpick:
```suggestion
#[derive(Clone, Debug, PartialEq, Eq, serde::Deserialize, Default)]
```

File: zebra-rpc/src/methods/get_block_template_rpcs/types/submit_block.rs [hunk 8]
```diff
@@ -9,7 +9,21 @@ use crate::methods::get_block_template_rpcs::GetBlockTemplateRpc;
 /// See notes for [`GetBlockTemplateRpc::submit_block`] method
 #[derive(Debug, serde::Deserialize)]
```
Comment (teor2345) [inline zebra-rpc/src/methods/get_block_template_rpcs/types/submit_block.rs]: Nitpick:
```suggestion
#[derive(Clone, Debug, PartialEq, Eq, serde::Deserialize)]
```

**Review by teor2345 — COMMENTED** [review]
Looks good for now, I have an optional suggestion to get `GetBlockTemplateCapability` to work.

**Review by teor2345 — DISMISSED** [review]

File: zebra-rpc/src/methods/get_block_template_rpcs/types/get_block_template_opts.rs (hunk 5 above)
Comment (arya2) [reply zebra-rpc/src/methods/get_block_template_rpcs/types/get_block_template_opts.rs]: Yes!!! 💯 It just has to a unit variant. I applied a slightly modified version of this.

Comment (arya2) [reply zebra-rpc/src/methods/get_block_template_rpcs/types/get_block_template_opts.rs]: Yes!!! 💯 It just has to be a unit variant. I applied a slightly modified version of this.

File: zebra-rpc/src/methods/get_block_template_rpcs/types/get_block_template_opts.rs [hunk 9]
```diff
@@ -0,0 +1,92 @@
...
+    /// Must be omitted as "proposal" mode is currently unsupported.
+    ///
+    /// Hex-encoded block data to be validated and checked against the server's usual acceptance rules
+    /// (excluding the check for a valid proof-of-work) when `mode` is set to `proposal`.
+    pub data: Option<HexData>,
+
+    /// A list of client-side supported capability features
+    // TODO: Fill out valid mutations capabilities.
+    #[serde(default)]
+    pub capabilities: Vec<GetBlockTemplateCapability>,
```
Comment (teor2345) [inline zebra-rpc/src/methods/get_block_template_rpcs/types/get_block_template_opts.rs:83]: Can you please add a test for this field?

File: zebra-rpc/src/methods/get_block_template_rpcs/types/get_block_template_opts.rs [hunk 10]
```diff
@@ -0,0 +1,92 @@
...
+    /// Currently ignored by zcashd and zebra.
+    ServerList,
+
+    /// Currently ignored by zcashd and zebra.
+    WorkId,
+
+    /// Unknown capability to fill in for mutations.
+    // TODO: Fill out valid mutations capabilities.
+    #[serde(other)]
+    UnknownCapability,
```
Comment (teor2345) [inline zebra-rpc/src/methods/get_block_template_rpcs/types/get_block_template_opts.rs:56]: Does this need to be `UnknownCapability(String)` to store mutations like "time"?

I guess we'll find out when we test it!

```suggestion
    /// Unknown capability to fill in for mutations.
    // TODO: Fill out valid mutations capabilities.
    #[serde(other)]
    UnknownCapability(String),
```

**Review by teor2345 — DISMISSED** [review]
Thanks, looks good, but I'd like to make sure we cover the `GetBlockTemplateCapability` field in our tests.

File: zebra-rpc/src/methods/get_block_template_rpcs/types/get_block_template_opts.rs (hunk 10 above)
Comment (teor2345) [reply zebra-rpc/src/methods/get_block_template_rpcs/types/get_block_template_opts.rs:56]: Oh, I saw your other comment, I guess the exact value doesn't matter if we're ignoring them anyway.

**Comment by teor2345** [comment]
Looks like this will also need a rebase before it merges.

File: zebra-rpc/src/methods/get_block_template_rpcs/types/get_block_template_opts.rs (hunk 9 above)
Comment (arya2) [reply zebra-rpc/src/methods/get_block_template_rpcs/types/get_block_template_opts.rs:83]: I'm not sure what to test here since it's not used in the method. Serde handles the `other` attribute as documented: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=20cee774557e5aad8c4f56b1e94295af.

Comment (teor2345) [reply zebra-rpc/src/methods/get_block_template_rpcs/types/get_block_template_opts.rs:83]: I just want to check that the entire implementation works like we expect, because there are a lot of different interacting pieces.

You could run the RPC manually, and check that it accepts an unknown capability?

Comment (arya2) [reply zebra-rpc/src/methods/get_block_template_rpcs/types/get_block_template_opts.rs:83]: Got it. Updated the acceptance in [`b46be81`](https://github.com/ZcashFoundation/zebra/pull/5772/commits/b46be810522daf93c9c7c633df68014690ae651f) to test it with and without the optional parameter and included an unknown capability there.

**Review by teor2345 — APPROVED** [review]
Looks great, thanks for the extra test!

**Comment by teor2345** [comment]
I tested this with:
```sh
zcash-cli getblocktemplate '{ "longpollid": "000190297833eb833116702948210000000001755ed052" }'
```

And it worked!
