### PR TITLE
Fix some verifier warnings

### LINKED ISSUE #784: Disable "unexpected high block" warnings when we restart with a full chain
These warnings might be useful when we're first syncing, but they should not happen when we've finished syncing.

I might also downgrade them to "info", because they are not actually a bug. (And we have a workaround.)

TODO:
- [x] downgrade "unexpected high block" warnings to info

When we have a full chain:
- [x] disable "unexpected high block" warnings
- [x] disable "there are no checkpoints left to verify" warnings

### PR DESCRIPTION
**Pull request by teor2345**
* downgrade "unexpected high block" warnings to info

When we have a full chain:
* disable "unexpected high block" warnings
* disable "there are no checkpoints left to verify" warnings (partially implemented)

Also:
* make sure the checkpoints cover all pre-Sapling blocks

Closes #784.

### CODE REVIEW

File: zebra-consensus/src/chain.rs [hunk 1]
```diff
@@ -160,10 +173,25 @@ where
     }
 }
 
+/// Returns true if block_height is higher than the maximum checkpoint
+/// height. Also returns true if there is no maximum checkpoint height.
+///
+/// Returns false if the block does not have a height.
+fn is_higher_than_max_checkpoint(
```
Comment (dconnolly) [inline zebra-consensus/src/chain.rs:180]: 👍

**Review by dconnolly — APPROVED** [review]
lgtm!
