### PR TITLE
fix(state): return non-finalized UTXOs and tx IDs in address queries

### LINKED ISSUE #4220: getaddressutxos RPC is missing non-finalized UTXOs
## Motivation

When I compare `zebrad` and `zcashd` RPC responses for `getaddressutxos`, using this command:
```sh
zebra-utils/zcash-rpc-diff 28232 getaddressutxos '{ "addresses": ["t3dvVE3SQEi7kqNzwrfNePxZ1d4hUyztBA1"] }'
```

The last 100 UTXOs are missing. This looks like all the non-finalized UTXOs.

### Steps to Diagnose

Check these parts of the address UTXOs code:
- the non-finalized state query
- the code that skips the non-finalized state query
- the function that combines both sets of UTXOs

### PR DESCRIPTION
**Pull request by teor2345**
## Motivation

When I compare `zebrad` and `zcashd` RPC responses for `getaddressutxos`, using this command:
```sh
zebra-utils/zcash-rpc-diff 28232 getaddressutxos '{ "addresses": ["t3dvVE3SQEi7kqNzwrfNePxZ1d4hUyztBA1"] }'
```

All the non-finalized UTXOs are missing.

`getaddresstxids` has a similar bug.

### Specifications

The RPCs should return all relevant UTXOs and tx IDs, regardless of Zebra's internal architecture:
https://zcash.github.io/rpc/getaddressutxos.html
https://zcash.github.io/rpc/getaddresstxids.html

### Designs

Compare the correct chain heights when matching up finalized database queries with non-finalized chains.

## Solution

- Stop ignoring all non-finalized UTXOs in address queries
- Stop ignoring all non-finalized tx IDs in address queries

Related changes:
- Log address UTXOs and tx ID request processing
- Assert that address TxIDs and UTXOs are in chain order

Testing:
- Cross-check getaddressutxos and getaddressbalance in zcash-rpc-diff
- Always output colour by default in zcash-rpc-diff
- Display the actual connected node software in zcash-rpc-diff

After these fixes, the UTXOs and balances are the same in Zebra and `zcashd`, except for a slightly different UTXO order (`zcashd` returns coinbase transactions last in each block).

Close #4220

## Review

Anyone can review this PR, we should fix this bug before we write tests that depend on it.

### Reviewer Checklist

  - [ ] Code implements Specs and Designs
  - [ ] Tests for Expected Behaviour
  - [ ] Tests for Errors

### CODE REVIEW

File: zebra-state/src/service/read.rs [hunk 1]
```diff
@@ -338,62 +382,121 @@ where
...
+    // - Ok contains the finalized tip height (no need to compensate)
+    // - Err contains the required non-finalized chain overlap
+    let finalized_tip_status = required_min_non_finalized_root..=finalized_tip_range.end().0;
+    let finalized_tip_status = if finalized_tip_status.is_empty() {
+        let finalized_tip_height = *finalized_tip_range.end();
+        Ok(finalized_tip_height)
+    } else {
+        let required_non_finalized_overlap = finalized_tip_status;
+        Err(required_non_finalized_overlap)
+    };
```
Comment (teor2345) [inline zebra-state/src/service/read.rs:397]: Previously, the code used the `required_non_finalized_overlap` range when the queries were consistent.

File: zebra-state/src/service/read.rs [hunk 2]
```diff
@@ -338,62 +382,121 @@ where
...
+        non_finalized_root.0 <= required_min_non_finalized_root,
+        "unexpected chain gap: the best chain is updated after its previous root is finalized",
     );
 
-    // If we've already committed this entire chain, ignore its UTXO changes.
-    // This is more likely if the non-finalized state is just getting started.
-    if chain_tip > *required_chain_overlap.end() {
-        if required_chain_overlap.is_empty() {
-            // The non-finalized chain has been committed, and we don't need it.
-            return Ok(Default::default());
```
Comment (teor2345) [inline zebra-state/src/service/read.rs:371]: This check always skipped the non-finalized chain.

Instead, we need to:
- skip the non-finalized chain when the finalized tip is consistent and higher
- retry when the finalized tip is inconsistent and higher

File: zebra-state/src/service/read.rs [hunk 3]
```diff
@@ -573,51 +683,117 @@ where
...
-    let required_min_chain_root = finalized_tip_range.start().0 + 1;
-    let mut required_chain_overlap = required_min_chain_root..=finalized_tip_range.end().0;
+    let required_min_non_finalized_root = finalized_tip_range.start().0 + 1;
+
+    // Work out if we need to compensate for finalized query results from multiple heights:
+    // - Ok contains the finalized tip height (no need to compensate)
+    // - Err contains the required non-finalized chain overlap
+    let finalized_tip_status = required_min_non_finalized_root..=finalized_tip_range.end().0;
+    let finalized_tip_status = if finalized_tip_status.is_empty() {
+        let finalized_tip_height = *finalized_tip_range.end();
```
Comment (teor2345) [inline zebra-state/src/service/read.rs:693]: The fixes for transaction IDs are very similar.

**Comment by teor2345** [comment]
> Error: buildx failed with: error: failed to solve: failed to fetch oauth token: unexpected status: 401 Unauthorized

Another #4234 bug

**Review by oxarbitrage — APPROVED** [review]
Looks good.
