### PR TITLE
fix(ci): check, create and mount lwd cached state for tests

### LINKED ISSUE #9419: main branch CI failed: schedule in Run tests
GitHub Actions workflow [Run tests #1818](https://github.com/ZcashFoundation/zebra/actions/runs/14402833751) failed.

Event: schedule
Branch: [main](https://github.com/ZcashFoundation/zebra/tree/main)
Commit: [c901adf17719e7722723a49d72c321150a604588](https://github.com/ZcashFoundation/zebra/commit/c901adf17719e7722723a49d72c321150a604588)

<sup><i>Created by [jayqi/failed-build-issue-action](https://github.com/jayqi/failed-build-issue-action)</i></sup>

### PR DESCRIPTION
**Pull request by arya2**
## Motivation

This PR initially aimed to add checks for the existence of the lightwalletd cached state directory (`LWD_CACHE_DIR`) before running integration tests that require it. During development and testing, several related issues in the CI workflow and test harness were identified and fixed:

1.  Tests requiring a pre-existing `lightwalletd` state (`lwd-update-sync`, `lwd-send-transactions`, `lwd-grpc-wallet`) were timing out. This was traced back to the `lwd-full-sync` test not correctly saving its state to the expected `LWD_CACHE_DIR`, preventing the CI from creating valid `lwd-cache-*` disk images.
2.  The test harness code responsible for launching `lightwalletd` contained debug logging that caused a panic during the `lwd-full-sync` test by attempting to read the state directory before `lightwalletd` created it.
3.  Inconsistencies in constructing disk image names/labels were observed, related to recent updates in the `rlespinasse/github-slug-action` in their v5.

Fixes #9419

## Solution

1.  **CI Workflow (`sub-ci-integration-tests-gcp.yml`, `sub-deploy-integration-tests-gcp.yml`, `sub-find-cached-disks.yml`):**
    *   Added the missing `-e LWD_CACHE_DIR=/home/zebra/.cache/lwd` environment variable to the `lwd-full-sync` test definition in `sub-ci-integration-tests-gcp.yml`. This ensures `lightwalletd` saves its state to the correct location.
    *   The `create-state-image` step in `sub-deploy-integration-tests-gcp.yml` will now correctly capture this state when creating `lwd-cache-*` images.
    *   Updated workflow files to use `env.GITHUB_REF_POINT_SLUG_URL` instead of `env.GITHUB_REF_SLUG_URL` for disk/label naming consistency, to mitigate the issues with `github-slug-action@v5`. (See [rlespinasse/github-slug-action#104](https://github.com/rlespinasse/github-slug-action/issues/104)).
    *   Added `github-slug-action` to `sub-find-cached-disks.yml` to ensure consistent variable availability.

2.  **Test Harness (`zebrad/tests/common/lightwalletd.rs`):**
    *   Modified `spawn_lightwalletd_child` to accept the `TestType` as an argument.
    *   Conditionalized the debug logging that reads the `lightwalletd` state directory size. It now skips this check for `TestType::FullSyncFromGenesis` (used by `lwd-full-sync`) to prevent panics when the directory doesn't initially exist.

3.  **RPC (`zebra-rpc/src/methods.rs`, `zebra-rpc/src/methods/get_block_template_rpcs.rs`):**
    *   Modified `chain_tip_difficulty` to accept a `should_use_default` flag. When true (as used by `getinfo`), it returns a default difficulty value instead of erroring if the state service isn't ready, preventing a potential panic.

### Tests

The primary testing for these changes involves the CI integration tests defined in `sub-ci-integration-tests-gcp.yml`:

-   The fix to `lwd-full-sync` saving its state correctly is verified by the subsequent successful runs of `lwd-update-sync`, `lwd-send-transactions`, and `lwd-grpc-wallet`, which depend on the `lwd-cache-*` disk image created by `lwd-full-sync`. These tests should no longer time out due to missing state.
-   The fix in `lightwalletd.rs` is verified by the `lwd-full-sync` test no longer panicking when attempting to log the cache directory size.

### Specifications & References

-   GitHub Slug Action Issue: [GITHUB_REF_NAME is not correctly filled on pull_request events #104](https://github.com/rlespinasse/github-slug-action/issues/104)

### PR Checklist

- [x] The PR name is suitable for the release notes.
- [x] The solution is tested (via CI integration tests).
- [x] The documentation is up to date (Internal test harness/CI documentation updated implicitly via code comments).

### CODE REVIEW

**Comment by gustavovalverde** [comment]
I confirmed that:

Lightwalletd tests fail when the lwd state is not available: 
- https://github.com/ZcashFoundation/zebra/actions/runs/14820065858/attempts/2?pr=9481

`lwd-full-sync` can be run, and it does not trigger the failure:
- https://github.com/ZcashFoundation/zebra/actions/runs/14810607881/job/41584899715

All lwd tests pass when the state is available:
- https://github.com/ZcashFoundation/zebra/actions/runs/14820065858/job/41611470826?pr=9481

File: zebrad/tests/common/lightwalletd.rs [hunk 1]
```diff
@@ -207,13 +211,39 @@ where
...
+                        .expect("unexpected failure reading lightwalletd cache dir");
+                let lwd_cache_dir_size = lwd_cache_dir.into_iter().fold(0, |acc, entry| {
+                    acc + entry
+                        .map(|entry| entry.metadata().map(|meta| meta.len()).unwrap_or(0))
+                        .unwrap_or(0)
+                });
+
+                tracing::info!("{lwd_cache_dir_size} bytes in lightwalletd cache dir");
+
+                let lwd_cache_dir =
```
Comment (upbqdn) [inline zebrad/tests/common/lightwalletd.rs]: We get the same dir above at line 219, could we not clone that? Or should we remove the whole `matches!` section now?

**Review by upbqdn — DISMISSED** [review]

File: zebrad/tests/common/lightwalletd.rs (hunk 1 above)
Comment (gustavovalverde) [reply zebrad/tests/common/lightwalletd.rs]: Solved here:
- [refactor(tests): Avoid redundant directory read for lightwalletd cach…](https://github.com/ZcashFoundation/zebra/pull/9481/commits/f4b328253391c30dd74773750bd25872c4ca3754)

**Review by upbqdn — COMMENTED** [review]
Was this the ultimate bug?

Edit: I meant it for commit [373e0a9](https://github.com/ZcashFoundation/zebra/pull/9481/commits/373e0a92f89f2527db90a6d78b441e5eea33bc9c).

File: zebrad/tests/common/lightwalletd.rs (hunk 1 above)
Comment (upbqdn) [reply zebrad/tests/common/lightwalletd.rs]: Great, thanks. Do you or @arya2 want to keep this code? It looks like it's suited only for debugging.

Comment (gustavovalverde) [reply zebrad/tests/common/lightwalletd.rs]: It's helpful. We previously had this in the entrypoint and it help catching (and understanding) this type of issues

**Comment by gustavovalverde** [comment]
> Was this the ultimate bug?
> 
This missing variable https://github.com/ZcashFoundation/zebra/pull/9481/files#diff-88f0a9cbc54ea70f51d3d7163ed664a292b5d5e5b3bbcf79d6bda582e46f9638R319

The cached state was being recreated in a different location.

**Review by gustavovalverde — APPROVED** [review]
I'm re-approving to get this merged.

**Comment by gustavovalverde** [comment]
@upbqdn it seems it will need your approval as I pushed commits to the branch :)

**Review by conradoplg — APPROVED** [review]

**Comment by conradoplg** [comment]
@mergifyio queue

File: zebra-rpc/src/methods.rs [hunk 2]
```diff
@@ -2702,7 +2704,11 @@ mod opthex {
     }
 }
 /// Returns the proof-of-work difficulty as a multiple of the minimum difficulty.
-pub async fn chain_tip_difficulty<State>(network: Network, mut state: State) -> Result<f64>
+pub async fn chain_tip_difficulty<State>(
+    network: Network,
+    mut state: State,
+    should_use_default: bool,
```
Comment (str4d) [inline zebra-rpc/src/methods.rs:2710]: This new field is undocumented, and I do not know how to set it. (This method is used downstream in Zaino.)
