### PR TITLE
fix(state): Write database format version to disk atomically to avoid a rare panic

### LINKED ISSUE #8793: Fix panic when Zebra in `database_format_version_at_path`
## Motivation

Zebra could be interrupted while writing a database format version file, and then panic when trying to read the malformed file.

See: https://github.com/ZcashFoundation/zebra/actions/runs/10479904554/job/29026515830#step:12:3460

## Design

Address [this TODO](https://github.com/ZcashFoundation/zebra/blob/main/zebra-network/src/config.rs#L515) and use it to write the database version file.

### PR DESCRIPTION
**Pull request by arya2**
## Motivation

We want to avoid potentially corrupting the database format version file when updating it.

Closes #8793.

## Solution

- Factors code for atomically updating the peer cache into an `atomic_write_to_tmp_file()` fn.
- Replaces call to `fs::write()` in `write_database_format_version_to_disk()` with a call to `atomic_write_to_tmp_file()`.

### Tests

Parts of this change are covered by existing tests for `update_peer_cache()`. 

We could also add a test for the atomic file write that interrupts a very expensive file system operation and checks that nothing has been written to the target file path, though I would prefer to leave that as follow-up work.

### Follow-up Work

- Add a test to check that `atomic_write_to_tmp_file()` doesn't write anything to the target file path when interrupted.
- Ensure that all in-place database format upgrades can succeed when re-run in case the disk format version is outdated.

### PR Author's Checklist

- [x] The PR name will make sense to users.
- [ ] The PR provides a CHANGELOG summary.
- [x] The solution is tested.
- [x] The documentation is up to date.
- [x] The PR has a priority label.

### PR Reviewer's Checklist

- [ ] The PR Author's checklist is complete.
- [ ] The PR resolves the issue.

### CODE REVIEW

File: zebra-chain/src/common.rs [hunk 1]
```diff
@@ -0,0 +1,74 @@
...
+///
+/// # Concurrency
+///
+/// This function blocks on filesystem operations and should be called in a blocking task
+/// when calling from an async environment.
+///
+/// # Panics
+///
+/// If the provided `file_path` is a directory path.
+pub fn atomic_write_to_tmp_file(
```
Comment (upbqdn) [inline zebra-chain/src/common.rs]: ###### Optional Suggestion


The final destination for the given data is the given path, not a tmp file, so a name like `atomic_write` instead of `atomic_write_to_tmp_file` might be better?

File: zebra-state/src/config.rs [hunk 2]
```diff
@@ -512,10 +510,9 @@ pub(crate) mod hidden {
 
         let version = format!("{}.{}", changed_version.minor, changed_version.patch);
 
-        // # Concurrency
-        //
-        // The caller handles locking for this file write.
-        fs::write(version_path, version.as_bytes())?;
+        // Write to a temporary file, so the cache is not corrupted if Zebra shuts down or crashes
+        // at the same time.
```
Comment (upbqdn) [inline zebra-state/src/config.rs]: ###### Optional Suggestion

```suggestion
        // Write the version file atomically so the cache is not corrupted if Zebra shuts down or
        // crashes.
```

File: zebra-chain/src/common.rs [hunk 3]
```diff
@@ -0,0 +1,74 @@
...
+
+    // Write data to the file asynchronously, by extracting the inner file, using it,
+    // then combining it back into a type that will correctly drop the file on error.
+    tmp_file.write_all(data)?;
+
+    // Atomically replace the current file with the temporary file.
+    // Do blocking filesystem operations on a dedicated thread.
+    let persist_result = tmp_file
+        .persist(&file_path)
+        // Drops the temp file and returns the file path if needed.
```
Comment (upbqdn) [inline zebra-chain/src/common.rs]: ###### Optional Suggestion

```suggestion
        // Drops the temp file and returns the file path.
```

File: zebra-chain/src/common.rs [hunk 4]
```diff
@@ -0,0 +1,74 @@
...
+    );
+
+    // Create the temporary file in the same directory as the permanent file,
+    // so atomic filesystem operations are possible.
+    let mut tmp_file = tempfile::Builder::new()
+        .prefix(&tmp_file_prefix)
+        .tempfile_in(file_dir)?;
+
+    // Write data to the file asynchronously, by extracting the inner file, using it,
+    // then combining it back into a type that will correctly drop the file on error.
```
Comment (upbqdn) [inline zebra-chain/src/common.rs]: This comment seems outdated in the current context.

```suggestion
```

File: zebra-chain/src/common.rs [hunk 5]
```diff
@@ -0,0 +1,74 @@
...
+    tmp_file.write_all(data)?;
+
+    // Atomically replace the current file with the temporary file.
+    // Do blocking filesystem operations on a dedicated thread.
```
Comment (upbqdn) [inline zebra-chain/src/common.rs]: This comment seems outdated.

```suggestion
```

File: zebra-chain/src/common.rs [hunk 6]
```diff
@@ -0,0 +1,74 @@
...
+    // so atomic filesystem operations are possible.
+    let mut tmp_file = tempfile::Builder::new()
+        .prefix(&tmp_file_prefix)
+        .tempfile_in(file_dir)?;
+
+    // Write data to the file asynchronously, by extracting the inner file, using it,
+    // then combining it back into a type that will correctly drop the file on error.
+    tmp_file.write_all(data)?;
+
+    // Atomically replace the current file with the temporary file.
```
Comment (upbqdn) [inline zebra-chain/src/common.rs]: ###### Optional Suggestion

```suggestion
    // Atomically write the temp file to `file_path`.
```

File: zebra-network/src/config.rs [hunk 7]
```diff
@@ -505,88 +504,34 @@ impl Config {
...
-
-                // Drops the temp file if needed
-                match result {
-                    Ok(_temp_file) => {
-                        info!(
-                            cached_ip_count = ?peer_list.len(),
-                            ?peer_cache_file,
-                            "updated cached peer IP addresses"
-                        );
+        .expect("unexpected panic creating temporary file")?;
```
Comment (upbqdn) [inline zebra-network/src/config.rs]:
```suggestion
        .expect("could not write the peer cache file")?;
```

File: zebra-network/src/config.rs [hunk 8]
```diff
@@ -505,88 +504,34 @@ impl Config {
 
         // Write to a temporary file, so the cache is not corrupted if Zebra shuts down or crashes
         // at the same time.
```
Comment (upbqdn) [inline zebra-network/src/config.rs]: ###### Optional Suggestion

```suggestion
        // Write the peer cache file atomically so the cache is not corrupted if Zebra shuts down
        // or crashes.
```

**Review by upbqdn — DISMISSED** [review]

File: zebra-state/src/config.rs [hunk 9]
```diff
@@ -512,10 +510,9 @@ pub(crate) mod hidden {
...
+        atomic_write_to_tmp_file(version_path, version.as_bytes())??;
```
Comment (arya2) [inline zebra-state/src/config.rs]:
```suggestion
        atomic_write(version_path, version.as_bytes())??;
```

File: zebra-state/src/config.rs [hunk 10]
```diff
@@ -471,6 +467,8 @@ pub(crate) use hidden::{
 pub(crate) mod hidden {
     #![allow(dead_code)]
 
+    use zebra_chain::common::atomic_write_to_tmp_file;
```
Comment (arya2) [inline zebra-state/src/config.rs]:
```suggestion
    use zebra_chain::common::atomic_write;
```

File: zebra-chain/src/common.rs (hunk 1 above)
Comment (arya2) [inline zebra-chain/src/common.rs]:
```suggestion
pub fn atomic_write(
```

File: zebra-network/src/config.rs [hunk 11]
```diff
@@ -2,19 +2,18 @@
...
 use indexmap::IndexSet;
 use serde::{de, Deserialize, Deserializer};
-use tempfile::NamedTempFile;
-use tokio::{fs, io::AsyncWriteExt};
-use tracing::Span;
+use tokio::fs;
 
+use tracing::Span;
 use zebra_chain::{
+    common::atomic_write_to_tmp_file,
```
Comment (arya2) [inline zebra-network/src/config.rs]:
```suggestion
    common::atomic_write,
```

File: zebra-network/src/config.rs [hunk 12]
```diff
@@ -505,88 +504,34 @@ impl Config {
...
-        let tmp_peer_cache_file = tokio::task::spawn_blocking(move || {
-            span.in_scope(move || {
-                // Put the temporary file in the same directory as the permanent file,
-                // so atomic filesystem operations are possible.
-                tempfile::Builder::new()
-                    .prefix(&tmp_peer_cache_prefix)
-                    .tempfile_in(peer_cache_dir)
-            })
+        let write_result = tokio::task::spawn_blocking(move || {
+            span.in_scope(move || atomic_write_to_tmp_file(peer_cache_file, peer_data.as_bytes()))
```
Comment (arya2) [inline zebra-network/src/config.rs]:
```suggestion
            span.in_scope(move || atomic_write(peer_cache_file, peer_data.as_bytes()))
```

File: zebra-chain/src/common.rs (hunk 1 above)
Comment (arya2) [reply zebra-chain/src/common.rs]: I agree, renamed in https://github.com/ZcashFoundation/zebra/pull/8795/commits/46417346cf1b444e79aaca5c9047cec1c8c47f2a.

**Review by upbqdn — APPROVED** [review]
