### PR TITLE
fix(getblocktemplate): change error format in proposals

### LINKED ISSUE #5981: Use the same format as `zcashd` for `getblocktemplate` proposal mode errors
## Motivation

When I use `zebra-utils/zcash-rpc-block-template-to-proposal` from PR #5944 to send a block proposal from Zebra to both `zcashd` and Zebra, I see these differences in the response format:
```
Proposal response diffs between ports  8232 6666 and time sources CurTime MinTime MaxTime ClampedNow:
--- /tmp/tmp.UWcAoSvcUZ.block-template-proposal/proposal-check-getblocktemplate-proposal.CurTime.8232.json	2023-01-26 15:15:37.881314992 -0300
+++ /tmp/tmp.UWcAoSvcUZ.block-template-proposal/proposal-check-getblocktemplate-proposal.MaxTime.6666.json	2023-01-26 15:15:38.329290891 -0300
@@ -0,0 +1,5 @@
+invalid proposal: Block {
+    source: ValidateProposal(
+        "proposal is not based on the current best chain tip: previous block hash must be the best chain tip",
+    ),
+}
```

Zebra should return a string to match the `zcashd` response format, but it is currently returning JSON. For example zcashd returns errors like `bad-txns-inputs-missingorspent`

### Specifications

We were following the specifications in the bitcoin improvement proposals here, but being compatible with the `zcashd` implementation is a higher priority.

It is enough to return any error string in `kebab-case` format - we don't need to match the exact error wording.

For the example above about best tip error zebra should return something like:

`invalid-proposal-proposal-is-not-based-on-the-current-best-chain-tip-previous-block-hash–must–be-the–best-chain-tip`

### Complex Code or Requirements

This should be a simple format change.

### Testing

We can use the `zebra-utils/zcash-rpc-block-template-to-proposal` script to manually re-test to make sure this bug is gone. We'll need to wait for an error.

(The previous block error happens if a new block has just arrived, or there is a chain fork.)

### PR DESCRIPTION
**Pull request by oxarbitrage**
## Motivation

We want to match zcashd error format in getblocktemplate proposal mode responses.

Close https://github.com/ZcashFoundation/zebra/issues/5981

## Solution

Create `kabeb-case` errors for `ProposalResponse` from zebra json.

## Review

Anyone can review.

### Reviewer Checklist

  - [ ] Will the PR name make sense to users?
    - [ ] Does it need extra CHANGELOG info? (new features, breaking changes, large changes)
  - [ ] Are the PR labels correct?
  - [ ] Does the code do what the ticket and PR says?
    - [ ] Does it change concurrent code, unsafe code, or consensus rules?
  - [ ] How do you know it works? Does it have tests?

### CODE REVIEW

File: zebra-rpc/src/methods/get_block_template_rpcs/types/get_block_template/proposal.rs [hunk 1]
```diff
@@ -42,23 +42,22 @@ pub enum ProposalResponse {
...
+        let error_kebab1 = format!("{error:?}")
+            .replace(|c: char| !c.is_alphanumeric(), "-")
+            .to_ascii_lowercase();
+
+        // Remove consecutive `-` characters if any.
+        let regex1 = regex::Regex::new(r"-+").expect("valid regex");
+        let error_kebab2 = regex1.replace_all(&error_kebab1, "-");
+        // Remove trailing `-` character if any.
+        let regex2 = regex::Regex::new(r"-$").expect("valid regex");
+        let final_error = regex2.replace_all(&error_kebab2, "");
```
Comment (oxarbitrage) [inline zebra-rpc/src/methods/get_block_template_rpcs/types/get_block_template/proposal.rs]: Maybe a list of regexes can be done here instead, i didn't tested it but i think this should be good enough as is too.

File: zebra-rpc/src/methods/get_block_template_rpcs/types/get_block_template/proposal.rs [hunk 2]
```diff
@@ -42,23 +42,22 @@ pub enum ProposalResponse {
...
-        ProposalResponse::Rejected(format!("{error:#?}"))
-    }
-}
-
-impl<E: Error + Send + Sync + 'static> From<E> for ProposalResponse {
-    fn from(error: E) -> Self {
-        Self::error(error.into())
+    ///
+    /// Note: Error kind is currently ignored to match zcashd error format (`kebab-case` string).
+    pub fn rejected<S: ToString>(_kind: S, error: BoxError) -> Self {
```
Comment (arya2) [inline zebra-rpc/src/methods/get_block_template_rpcs/types/get_block_template/proposal.rs:47]: Could we remove `_kind` altogether or add it to the message? (It's currently either "invalid proposal" or "invalid proposal format" so we could optionally make it an enum if we want to keep it).

Do you think we should also leave a TODO for explicitly downcasting and matching errors to constants?

File: zebra-rpc/src/methods/get_block_template_rpcs/types/get_block_template/proposal.rs [hunk 3]
```diff
@@ -42,23 +42,22 @@ pub enum ProposalResponse {
...
+        // Make error `kebab-case` to match zcashd format.
+        let error_kebab1 = format!("{error:?}")
+            .replace(|c: char| !c.is_alphanumeric(), "-")
+            .to_ascii_lowercase();
+
+        // Remove consecutive `-` characters if any.
+        let regex1 = regex::Regex::new(r"-+").expect("valid regex");
+        let error_kebab2 = regex1.replace_all(&error_kebab1, "-");
+        // Remove trailing `-` character if any.
+        let regex2 = regex::Regex::new(r"-$").expect("valid regex");
```
Comment (arya2) [inline zebra-rpc/src/methods/get_block_template_rpcs/types/get_block_template/proposal.rs]: Optional/Nitpick: I don't think any of the errors that might be converted need to be checked for leading '-' characters, but in lieu of tests, could we check anyways?

```suggestion
        // Trim any leading or trailing `-` characters.
        let regex2 = regex::Regex::new(r"^-|-$").expect("valid regex");
```

File: zebra-rpc/Cargo.toml [hunk 4]
```diff
@@ -42,6 +42,7 @@ jsonrpc-core = "18.0.0"
 jsonrpc-derive = "18.0.0"
 jsonrpc-http-server = "18.0.0"
 num_cpus = "1.15.0"
+regex = "1.7.1"
```
Comment (arya2) [inline zebra-rpc/Cargo.toml]: Could we make this an optional dependency that's required by the "getblocktemplate-rpcs" feature if we keep it.

File: zebra-rpc/src/methods/get_block_template_rpcs/types/get_block_template/proposal.rs [hunk 5]
```diff
@@ -42,23 +42,22 @@ pub enum ProposalResponse {
...
+    /// Note: Error kind is currently ignored to match zcashd error format (`kebab-case` string).
+    pub fn rejected<S: ToString>(_kind: S, error: BoxError) -> Self {
+        // Make error `kebab-case` to match zcashd format.
+        let error_kebab1 = format!("{error:?}")
+            .replace(|c: char| !c.is_alphanumeric(), "-")
+            .to_ascii_lowercase();
+
+        // Remove consecutive `-` characters if any.
+        let regex1 = regex::Regex::new(r"-+").expect("valid regex");
+        let error_kebab2 = regex1.replace_all(&error_kebab1, "-");
```
Comment (arya2) [inline zebra-rpc/src/methods/get_block_template_rpcs/types/get_block_template/proposal.rs]: I think adding the `regex` crate is okay, but if we want to remove it, we could use [`as_mut_vec`](https://doc.rust-lang.org/std/string/struct.String.html#method.as_mut_vec), [`dedup`](https://doc.rust-lang.org/std/vec/struct.Vec.html#method.dedup), and [`trim_matches`](https://doc.rust-lang.org/std/primitive.str.html#method.trim_matches) instead. 

`as_mut_vec` is unsafe because it might add invalid characters but in this case we would only be removing characters.

**Review by arya2 — COMMENTED** [review]
This looks great, thank you!

File: zebra-rpc/src/methods/get_block_template_rpcs/types/get_block_template/proposal.rs (hunk 2 above)
Comment (teor2345) [reply zebra-rpc/src/methods/get_block_template_rpcs/types/get_block_template/proposal.rs:47]: > Could we remove `_kind` altogether or add it to the message? (It's currently either "invalid proposal" or "invalid proposal format" so we could optionally make it an enum if we want to keep it).

I don't think it adds much to the error message, so I don't mind which way we fix this.

> Do you think we should also leave a TODO for explicitly downcasting and matching errors to constants?

This will only matter if miners care about the specific error text. I'll go ask some of the mining pools.

Comment (teor2345) [reply zebra-rpc/src/methods/get_block_template_rpcs/types/get_block_template/proposal.rs:47]: (I just checked, the mining pools we're in contact with don't use block proposals currently.)

File: zebra-rpc/src/methods/get_block_template_rpcs/types/get_block_template/proposal.rs (hunk 5 above)
Comment (teor2345) [reply zebra-rpc/src/methods/get_block_template_rpcs/types/get_block_template/proposal.rs]: We avoid using unsafe code when there is a safe alternative.

Here is a safe alternative to `as_mut_vec`:
```rust
let mut error: Vec<char> = error.chars().collect();
error.dedup();
let error: String = error.into_iter().collect();
```

File: zebra-rpc/src/methods/get_block_template_rpcs/types/get_block_template/proposal.rs (hunk 3 above)
Comment (teor2345) [reply zebra-rpc/src/methods/get_block_template_rpcs/types/get_block_template/proposal.rs]: This will only trim a single leading or trailing character, using `trim_matches` would be more reliable here.

**Review by teor2345 — DISMISSED** [review]
I think all the changes we've suggested are optional.

File: zebra-rpc/src/methods/get_block_template_rpcs/types/get_block_template/proposal.rs (hunk 3 above)
Comment (oxarbitrage) [reply zebra-rpc/src/methods/get_block_template_rpcs/types/get_block_template/proposal.rs]: Both suggestions are good to add, i made the `trim_matches` one at https://github.com/ZcashFoundation/zebra/pull/6044/commits/154386cc4ca94cfa9cff6b5fcce8eb6350556e33 so we have one regex less.

File: zebra-rpc/Cargo.toml (hunk 4 above)
Comment (oxarbitrage) [reply zebra-rpc/Cargo.toml]: Yea, i had been lazy here, sorry. Added it at https://github.com/ZcashFoundation/zebra/pull/6044/commits/377025fada23ad4275262d7cb3aeb692e9341825

File: zebra-rpc/src/methods/get_block_template_rpcs/types/get_block_template/proposal.rs (hunk 5 above)
Comment (oxarbitrage) [reply zebra-rpc/src/methods/get_block_template_rpcs/types/get_block_template/proposal.rs]: The only problem here and the reason we still have a regex left is with the `dedup()`. The method remove all the repeated characters so an error will end up looking as: 

`io-eror-kind-unexpectedeof-mesage-failed-to-fil-whole-bufer`

So i didn't applied it.

Comment (arya2) [reply zebra-rpc/src/methods/get_block_template_rpcs/types/get_block_template/proposal.rs]: > Here is a safe alternative to as_mut_vec:

`as_mut_vec` wouldn't have worked either, I should've paid closer attention to the return type, it's a `Vec<u8>` so chars that are represented with two bytes would be two elements.

> The only problem here and the reason we still have a regex left is with the `dedup()`. The method remove all the repeated characters so an error will end up looking as:
> 
> `io-eror-kind-unexpectedeof-mesage-failed-to-fil-whole-bufer`
> 
> So i didn't applied it.

Oops. I think `dedup_by(|a, b| a == &'-' && b == &'-')` would work but it's optional so feel free to resolve this.

**Review by arya2 — DISMISSED** [review]

File: zebra-rpc/src/methods/get_block_template_rpcs/types/get_block_template/proposal.rs (hunk 5 above)
Comment (oxarbitrage) [reply zebra-rpc/src/methods/get_block_template_rpcs/types/get_block_template/proposal.rs]: That worked, thanks! https://github.com/ZcashFoundation/zebra/pull/6044/commits/a8b4d718bb8e5f1950c620de783c0f3f9d11d8d7

**Review by teor2345 — APPROVED** [review]
Thanks!

**Comment by oxarbitrage** [comment]
There is an error in the CI but i think is unrelated to this PR so i am retrying.

Error is for macos only in the `v4_with_modified_joinsplit_is_rejected` test: https://github.com/ZcashFoundation/zebra/actions/runs/4068002665/jobs/7006036670#step:14:1929

**Comment by teor2345** [comment]
> There is an error in the CI but i think is unrelated to this PR so i am retrying.
> 
> Error is for macos only in the `v4_with_modified_joinsplit_is_rejected` test: https://github.com/ZcashFoundation/zebra/actions/runs/4068002665/jobs/7006036670#step:14:1929

This seems to be bug #5823, which is unrelated.
