### PR TITLE
fix(net): Fix potential network hangs, and reduce code complexity

### LINKED ISSUE #7858: security: avoid hangs in the peer set and related code
### Motivation

There are still some potential hangs in the peer set and related code.

### Specifications

Rust futures need to give a copy of their task waker to any code that could potentially wake the task.

### Complex Code or Requirements

Method calls shouldn't be skipped based on the outcomes of previous methods, unless the connection is shutting down.

### Testing

This is fairly straightforward, we need to check that each method that could wake the service or future is called.

We have existing tests that cover this code.

### Related Work

Follow up to #7772.

### PR DESCRIPTION
**Pull request by teor2345**
## Motivation

Zebra's peer handling code is complex, and it contains some potential hangs. This PR fixes some hangs, and simplifies the code.

Follow up to #7772
Close #7858

### Specifications

Rust futures wake a task when any waker cloned from the most recently passed Context is woken:
> When a future is not ready yet, poll returns Poll::Pending and stores a clone of the [Waker](https://doc.rust-lang.org/std/task/struct.Waker.html) copied from the current [Context](https://doc.rust-lang.org/std/task/struct.Context.html). This [Waker](https://doc.rust-lang.org/std/task/struct.Waker.html) is then woken once the future can make progress.
> ...
> Note that on multiple calls to poll, only the [Waker](https://doc.rust-lang.org/std/task/struct.Waker.html) from the [Context](https://doc.rust-lang.org/std/task/struct.Context.html) passed to the most recent call should be scheduled to receive a wakeup.

https://doc.rust-lang.org/std/future/trait.Future.html#tymethod.poll

### Complex Code or Requirements

This PR contains a lot of refactors to make future changes easier.
It also eliminates some wakers entirely to simplify the code and waking logic.

## Solution

Bug fixes:
- Pass context correctly to the peer set background task oneshot. (We're not waking on it now, but we might want to in future.)
- Pass context correctly to the peer client task, and the peer client request sender, so they always wake the client task. (The client task is the task that is spawned by the peer set buffer.)
- Check all ready peers for errors before sending requests to them.

Code simplification:
- Remove preselected peers, just select the peer when we have a new request. This makes waking much less complex.
- Use `futures::ready!` (the macro) and `?` to simplify polling

Refactors:
- Refactor polling methods to return `Poll`, and `Ok` if they do something
- Make panic checking method names clearer (this can be split into its own PR)

### Testing

The existing tests cover this behaviour fairly well. It is hard to check for hangs in tests.

Some tests have been updated for the new polling behaviour.

## Review

This might still need some test fixes.

### Reviewer Checklist

  - [ ] Will the PR name make sense to users?
    - [ ] Does it need extra CHANGELOG info? (new features, breaking changes, large changes)
  - [ ] Are the PR labels correct?
  - [ ] Does the code do what the ticket and PR says?
    - [ ] Does it change concurrent code, unsafe code, or consensus rules?
  - [ ] How do you know it works? Does it have tests?

## Follow Up Work

- #7858 
- #7822

### CODE REVIEW

File: zebra-network/src/peer_set/set.rs [hunk 1]
```diff
@@ -441,14 +424,24 @@ where
...
-                Poll::Pending | Poll::Ready(None) => return,
+    ///
+    /// Never returns an error. If there are no unready peers, returns `Ok` immediately.
+    /// Otherwise, returns `Poll::Pending`, and registers a wakeup for the next task that becomes
+    /// ready.
+    fn poll_unready(&mut self, cx: &mut Context<'_>) -> Poll<Result<(), BoxError>> {
+        if self.unready_services.is_empty() {
+            // Don't replace the previous waker, because we have no peers to wake the task.
+            return Poll::Ready(Ok(()));
+        }
```
Comment (teor2345) [inline zebra-network/src/peer_set/set.rs]: This is one half of the fix: don't replace the existing waker with a waker that will never wake.

File: zebra-network/src/peer_set/set.rs [hunk 2]
```diff
@@ -995,78 +997,74 @@ where
...
+        // This waker skips itself if it is empty and will never wake.
+        // Otherwise, each connected peer should become ready or timeout within a few minutes.
+        //
+        // TODO: drop peers that overload us with inbound messages and never become ready (#7822)
+        let _ = self.poll_unready(cx)?;
+
+        // Correctness: the waker in the context is waiting on peers. If it is replaced later in
+        // the function, the network could hang. We drop the reference here so it can't be used.
+        #[allow(dropping_references)]
+        std::mem::drop(cx);
```
Comment (teor2345) [inline zebra-network/src/peer_set/set.rs]: This is the other half of the fix: wake on the first ready existing peer, unless there aren't any, then wake on the first connected peer.

File: zebra-network/src/peer_set/set.rs [hunk 3]
```diff
@@ -995,78 +997,74 @@ where
...
-                    Poll::Pending => {
-                        trace!("preselected service is no longer ready, moving to unready list");
-                        self.push_unready(key, service);
-                    }
-                    Poll::Ready(Err(error)) => {
-                        trace!(%error, "preselected service failed, dropping it");
-                        std::mem::drop(service);
-                    }
-                }
-            }
```
Comment (teor2345) [inline zebra-network/src/peer_set/set.rs:1034]: Because this code sets a waker, it was easiest to just delete it.

File: zebra-network/src/peer_set/inventory_registry.rs [hunk 4]
```diff
@@ -283,11 +283,15 @@ impl InventoryRegistry {
...
+    /// Rotates the inventory HashMaps on every timer tick.
+    /// Drains the inv_stream channel and registers all advertised inventory.
     ///
-    /// - rotates HashMaps based on interval events
-    /// - drains the inv_stream channel and registers all advertised inventory
-    pub fn poll_inventory(&mut self, cx: &mut Context<'_>) -> Result<(), BoxError> {
+    /// Returns an error if the inventory channel is closed. Otherwise returns `Poll::Pending`, and
+    /// registers a wakeup the next time there is new inventory.
+    ///
+    /// TODO: also register a wakeup for the next timer tick.
```
Comment (teor2345) [inline zebra-network/src/peer_set/inventory_registry.rs]: I think this is incorrect: a `Waker` gives out the ability to wake the calling task to one or more other tasks or executor functions:
> When a future is not ready yet, poll returns Poll::Pending and stores a clone of the [Waker](https://doc.rust-lang.org/std/task/struct.Waker.html) copied from the current [Context](https://doc.rust-lang.org/std/task/struct.Context.html). This [Waker](https://doc.rust-lang.org/std/task/struct.Waker.html) is then woken once the future can make progress.

https://doc.rust-lang.org/std/future/trait.Future.html#tymethod.poll

More background:
https://doc.rust-lang.org/std/task/struct.Context.html
https://doc.rust-lang.org/std/task/struct.Waker.html
https://doc.rust-lang.org/std/task/struct.Waker.html#method.wake

File: zebra-network/src/peer_set/set.rs [hunk 5]
```diff
@@ -265,7 +254,11 @@ where
     C: ChainTip,
 {
     fn drop(&mut self) {
-        self.shut_down_tasks_and_channels()
+        // We don't want to wake the current task, we just want to drop everything we can.
```
Comment (teor2345) [inline zebra-network/src/peer_set/set.rs]:
```suggestion
        // We don't have access to the current task, and we're shutting down, so we just want to drop everything we can.
```

File: zebra-network/src/peer_set/set.rs [hunk 6]
```diff
@@ -479,14 +474,19 @@ where
...
                     debug!(%error, "service failed while unready, dropping service");
 
                     let cancel = self.cancel_handles.remove(&key);
                     assert!(cancel.is_some(), "missing cancel handle");
                 }
             }
         }
+
+        // There are no unready peers, so the unready_peers waker will never wake pending tasks.
+        *cx = Context::from_waker(original_waker);
```
Comment (teor2345) [inline zebra-network/src/peer_set/set.rs]: This line does nothing, because the task is the same, so the context and waker are the same:
https://github.com/ZcashFoundation/zebra/pull/7859/files#r1380722199

File: zebra-network/src/peer_set/set.rs [hunk 7]
```diff
@@ -441,14 +424,26 @@ where
...
-            match Pin::new(&mut self.unready_services).poll_next(cx) {
-                // No unready service changes, or empty unready services
-                Poll::Pending | Poll::Ready(None) => return,
+    ///
+    /// Never returns an error. If there are no unready peers, returns `Ok`, and preserves the
+    /// original waker. Otherwise, returns `Poll::Pending`, and registers a wakeup for the next
+    /// peer that becomes ready.
+    fn poll_unready(&mut self, cx: &mut Context<'_>) -> Poll<Result<(), BoxError>> {
+        if self.unready_services.is_empty() {
+            // Don't replace the previous waker, because we have no peers to wake the task.
```
Comment (teor2345) [inline zebra-network/src/peer_set/set.rs]: This is unnecessary, because the waker is a copy, so it can be woken by the spawned task for unready peers, or the inventory timer:
https://github.com/ZcashFoundation/zebra/pull/7859/files#r1380722199

File: zebra-network/src/peer_set/set.rs [hunk 8]
```diff
@@ -441,14 +424,26 @@ where
     ///
     /// Move newly ready services to the ready list if they are for peers with supported protocol
     /// versions, otherwise they are dropped. Also drop failed services.
-    fn poll_unready(&mut self, cx: &mut Context<'_>) {
-        loop {
-            match Pin::new(&mut self.unready_services).poll_next(cx) {
-                // No unready service changes, or empty unready services
-                Poll::Pending | Poll::Ready(None) => return,
+    ///
+    /// Never returns an error. If there are no unready peers, returns `Ok`, and preserves the
```
Comment (teor2345) [inline zebra-network/src/peer_set/set.rs]: Update this comment

File: zebra-network/src/peer_set/set.rs [hunk 9]
```diff
@@ -995,78 +1004,74 @@ where
...
 
     fn poll_ready(&mut self, cx: &mut Context<'_>) -> Poll<Result<(), Self::Error>> {
-        self.poll_background_errors(cx)?;
-
-        // Update peer statuses
+        // Update service and peer statuses.
+        //
+        // # Correctness
+        //
+        // If we poll these futures in series, then only the last polled future will wake
```
Comment (teor2345) [inline zebra-network/src/peer_set/set.rs]: This is wrong:
https://github.com/ZcashFoundation/zebra/pull/7859/files#r1380722199

File: zebra-network/src/peer_set/set.rs [hunk 10]
```diff
@@ -995,78 +1004,74 @@ where
...
+        // or no peers in the peer set at all.
+        //
+        // As a temporary fix, we try to pick the most likely waker, and skip wakers that will
+        // never wake.
+
+        // We can tolerate not being woken for these tasks, because we only return `Pending`
+        // when we have no ready peers. Delays in background error checking are acceptable,
+        // and we can't do anything useful with inventory until we have peers. (The oldest
+        // inventory will get automatically dropped.)
+        let _ = self.poll_background_errors(cx)?;
```
Comment (teor2345) [inline zebra-network/src/peer_set/set.rs]: We should match on `Poll` here, to make sure that's what we're ignoring even if the function types change.

File: zebra-network/src/peer_set/set.rs [hunk 11]
```diff
@@ -995,78 +1004,74 @@ where
...
+        let _ = self.inventory_registry.poll_inventory(cx)?;
+
+        // We must be woken if there are new peers, but new peers can be infrequent if our
+        // connection slots are full, or we're connected to all available/useful peers.
+        //
+        // TODO: wake waiting tasks if there are new peers or unready peers become ready (#7858)
```
Comment (teor2345) [inline zebra-network/src/peer_set/set.rs]: This is already happening, same with the TODO below:
https://github.com/ZcashFoundation/zebra/pull/7859/files#r1380722199

File: zebra-network/src/peer_set/set.rs [hunk 12]
```diff
@@ -995,78 +1004,74 @@ where
...
+        // This method preserves the original waker if it has no unready peers and will never wake.
+        // Otherwise, each connected peer should become ready or timeout within a few minutes.
+        //
+        // TODO: drop peers that overload us with inbound messages and never become ready (#7822)
+        let _ = self.poll_unready(cx)?;
+
+        // Correctness: the waker in the context is waiting on peers. If it is replaced later in
+        // the function, the network could hang. We drop the reference here so it can't be used.
+        #[allow(dropping_references)]
+        std::mem::drop(cx);
```
Comment (teor2345) [inline zebra-network/src/peer_set/set.rs]: Not needed:
https://github.com/ZcashFoundation/zebra/pull/7859/files#r1380722199

File: zebra-network/src/peer_set/set.rs (hunk 3 above)
Comment (teor2345) [reply zebra-network/src/peer_set/set.rs:1034]: This wasn't necessary for the waker, but reducing the complexity of this code helps avoid other logic bugs around waking, pending, and similar issues:
https://github.com/ZcashFoundation/zebra/pull/7859/files#r1380722199

File: zebra-chain/src/diagnostic/task/thread.rs [hunk 13]
```diff
@@ -8,45 +8,75 @@ use std::{
...
-impl<T> CheckForPanics for thread::Result<T> {
+impl<T> CheckForPanics for thread::Result<T>
+where
+    T: std::fmt::Debug,
+{
     type Output = T;
 
     /// Panics if the thread panicked.
+    /// If `panic_on_unexpected_termination` is true, and Zebra is not shutting down, also panics
+    /// if the thread exits.
```
Comment (arya2) [inline zebra-chain/src/diagnostic/task/thread.rs]: Optional/Nitpick:

```suggestion
    /// # Panics
    ///
    /// - if the thread panicked.
    /// - if the thread is cancelled, `panic_on_unexpected_termination` is true, and
    ///   Zebra is not shutting down.
```

File: zebra-network/src/peer_set/set.rs (hunk 3 above)
Comment (arya2) [reply zebra-network/src/peer_set/set.rs:1034]: I found this a lot easier to understand than the old code.

File: zebra-network/src/peer/client.rs [hunk 14]
```diff
@@ -421,26 +423,33 @@ impl MissingInventoryCollector {
...
-                PeerError::HeartbeatTaskExited("Task was cancelled".to_string()),
-            );
-        }
-
-        match self.heartbeat_task.poll_unpin(cx) {
+        let result = match self.heartbeat_task.poll_unpin(cx) {
             Poll::Pending => {
-                // Heartbeat task is still running.
-                Ok(())
+                if is_canceled {
```
Comment (arya2) [inline zebra-network/src/peer/client.rs:446]: Optional:

```suggestion
                // The heartbeat task will return `Pending` when cancelled but unable to immediately
                // acquire a permit to send a message to the `address_book_updater`.
                if is_canceled {
```

File: zebra-network/src/peer/client.rs [hunk 15]
```diff
@@ -536,6 +570,33 @@ impl Client {
...
+        // if either task exits, or if the heartbeat task drops the cancel handle.
+        //
+        //`ready!` returns `Poll::Pending` when `server_tx` is unready, and
+        // schedules this task for wakeup.
+        //
+        // It's ok to exit early and skip wakeups when there is an error, because the connection
+        // and its tasks are shut down immediately on error.
+
+        let _heartbeat_pending: Poll<()> = self.poll_heartbeat(cx)?;
+        let _connection_pending: Poll<()> = self.poll_connection(cx)?;
```
Comment (arya2) [inline zebra-network/src/peer/client.rs:596]: Good idea explicitly typing these.

File: zebra-network/src/peer/client.rs [hunk 16]
```diff
@@ -459,44 +468,66 @@ impl Client {
...
+                    self.set_task_exited_error(
+                        "connection",
+                        PeerError::HeartbeatTaskExited(error.to_string()),
+                    )
+                }
             }
-        }
+        };
+
+        Poll::Ready(result)
```
Comment (arya2) [inline zebra-network/src/peer/client.rs:532]: Optional/Nitpick/Subjective: This wasn't changed in this PR, but return an error from `set_task_exited_error()` and put it in a `Result::Err` here?

```rust
        Poll::Ready(Err(result))
```

File: zebra-network/src/peer_set/set.rs [hunk 17]
```diff
@@ -393,31 +382,25 @@ where
...
-                    None
+                    Poll::Ready(Ok(()))
                 }
 
-                // The tasks have been sent and consumed, but then they exited.
-                //
-                // Correctness: the peer set must receive at least one task.
-                //
-                // TODO: refactor `handle_rx` and `guards` into an enum
-                //       for the background task state: Waiting/Running/Shutdown.
```
Comment (arya2) [inline zebra-network/src/peer_set/set.rs:404]: Do we still want this TODO?

File: zebra-network/src/peer_set/set.rs [hunk 18]
```diff
@@ -995,78 +1009,70 @@ where
...
-                    Poll::Ready(Err(error)) => {
-                        trace!(%error, "preselected service failed, dropping it");
-                        std::mem::drop(service);
-                    }
-                }
-            }
+        if self.ready_services.is_empty() {
+            // # Correctness
+            //
+            // If the channel is full, drop the demand signal rather than waiting.
```
Comment (arya2) [inline zebra-network/src/peer_set/set.rs]:
```suggestion
            // If the channel is full, send the demand signal rather than waiting.
```

File: zebra-network/src/peer_set/set.rs [hunk 19]
```diff
@@ -441,14 +424,30 @@ where
...
+    /// doesn't register any wakeups. (Since wakeups come from peers, there needs to be at least one
+    /// peer to register a wakeup.)
+    fn poll_unready(&mut self, cx: &mut Context<'_>) -> Poll<Result<(), BoxError>> {
+        // # Correctness
+        //
+        // `poll_next()` must always be called, because `self.unready_services` could have been
+        // empty before the call to `self.poll_ready()`.
+        //
+        // > When new futures are added, `poll_next` must be called in order to begin receiving
+        // > wake-ups for new futures.
```
Comment (arya2) [inline zebra-network/src/peer_set/set.rs:447]: 🎉

**Review by arya2 — DISMISSED** [review]

File: zebra-network/src/peer_set/set.rs (hunk 3 above)
Comment (teor2345) [reply zebra-network/src/peer_set/set.rs:1034]: Yeah I'm really not sure why we needed to preselect a peer. It seems to work fine just selecting it at random at request time.

File: zebra-network/src/peer/client.rs (hunk 14 above)
Comment (teor2345) [reply zebra-network/src/peer/client.rs:446]: That's not quite what is happening here: there are no messages being sent in this code (until shutdown).

```suggestion
                // The heartbeat task returns `Pending` while it continues to run.
                // But if it has dropped its receiver, it is shutting down, and we should also shut down.
                if is_canceled {
```

File: zebra-network/src/peer/client.rs (hunk 16 above)
Comment (teor2345) [reply zebra-network/src/peer/client.rs:532]: I think that would make it more difficult to say `set_task_exited_error(...)?`.

We don't do that here, but we probably could.

File: zebra-network/src/peer_set/set.rs (hunk 17 above)
Comment (teor2345) [reply zebra-network/src/peer_set/set.rs:404]: I'm not sure if it makes sense any more. We might want to create `TaskGuard` and `TaskGuardSet` types, or make what we've done in the state with the update task more generic, and move it to `zebra_chain::task`.

I'm not sure, let's see what's actually needed later.

File: zebra-network/src/peer_set/set.rs (hunk 18 above)
Comment (teor2345) [reply zebra-network/src/peer_set/set.rs]: That's not what's happening here:
> Attempts to send a message on this Sender, returning the message if there was an error.

https://docs.rs/futures/latest/futures/channel/mpsc/struct.Sender.html#method.try_send

**Comment by teor2345** [comment]
I still need to fix some tests that are hanging, but they all seem to be inventory tests, so that should be an easy fix.

File: zebra-network/src/peer_set/set.rs (hunk 18 above)
Comment (arya2) [reply zebra-network/src/peer_set/set.rs]: Ah, that makes more sense.

**Comment by teor2345** [comment]
This should be ready to go now, there was a minor issue with the `Update` future for the inventory registry, but it seemed like a good idea to make all the poll methods consistent.

**Comment by teor2345** [comment]
Does this need a full sync before it merges, or can we wait until Friday's scheduled full sync?

If we do one now, the previous time was 2d 3h 15m:
https://github.com/ZcashFoundation/zebra/actions/runs/6824538443/job/18561008809

File: zebra-network/src/peer_set/set.rs [hunk 20]
```diff
@@ -479,14 +502,65 @@ where
...
+    /// because the peer set has exclusive access to send requests to each peer. (If an inbound
+    /// request is in progress, it will be handled, then our request will be sent by the connection
+    /// task.)
+    ///
+    /// Returns `Poll::Ready` if there are some ready peers, and `Poll::Pending` if there are no
+    /// ready peers. Never registers any task wakeups.
+    ///
+    /// # Panics
+    ///
+    /// If any peers somehow became unready. This indicates a bug in the peer set, where requests
```
Comment (arya2) [inline zebra-network/src/peer_set/set.rs]: Optional/Nitpick:

```suggestion
    /// If any peers somehow became unready without being sent a request. This indicates a bug in the peer set, where requests
```

File: zebra-network/src/peer_set/set.rs [hunk 21]
```diff
@@ -995,78 +1108,71 @@ where
...
-                    }
-                    Poll::Ready(Err(error)) => {
-                        trace!(%error, "preselected service failed, dropping it");
-                        std::mem::drop(service);
-                    }
-                }
-            }
+        // Check for failures in ready peers, removing newly errored or disconnected peers.
+        // So it needs to run after `poll_unready()`.
+        let ready_peers: Poll<()> = self.poll_ready_peer_errors(cx);
```
Comment (arya2) [inline zebra-network/src/peer_set/set.rs:1150]: Optional:

```suggestion
        //
        // TODO: Store an internal context with a noop_waker in a field for methods that never register wakers?
        let ready_peers: Poll<()> = self.poll_ready_peer_errors(cx);
```

File: zebra-network/src/peer_set/set.rs [hunk 22]
```diff
@@ -995,78 +1108,71 @@ where
...
+
+        // Check for newly ready peers, including newly added peers (which are added as unready).
+        // So it needs to run after `poll_discover()`. Registers a wakeup if there are any unready
+        // peers.
+        //
+        // Each connected peer should become ready within a few minutes, or timeout, close the
+        // connection, and release its connection slot.
+        //
+        // TODO: drop peers that overload us with inbound messages and never become ready (#7822)
+        let _poll_pending_or_ready: Poll<Option<()>> = self.poll_unready(cx)?;
```
Comment (arya2) [inline zebra-network/src/peer_set/set.rs:1137]: Could we add a correctness comment here like: "Must never register any task wakeups on this context after this call to `poll_unready()`"

**Review by arya2 — DISMISSED** [review]
> Does this need a full sync before it merges, or can we wait until Friday's scheduled full sync?

I think we can wait until the next scheduled full sync.

File: zebra-network/src/peer_set/set.rs (hunk 22 above)
Comment (teor2345) [reply zebra-network/src/peer_set/set.rs:1137]: That's not how task wakeups work. (It's how I thought they worked when I initially opened this PR, but I was wrong.)

*Every* potential waking event gets a reference to the waker via the context, and *any* of those events can wake the task.

File: zebra-network/src/peer_set/set.rs [hunk 23]
```diff
@@ -479,14 +502,65 @@ where
...
+
+    /// Checks previously ready peer services for errors.
+    ///
+    /// The only way these peer `Client`s can become unready is when we send them a request,
+    /// because the peer set has exclusive access to send requests to each peer. (If an inbound
+    /// request is in progress, it will be handled, then our request will be sent by the connection
+    /// task.)
+    ///
+    /// Returns `Poll::Ready` if there are some ready peers, and `Poll::Pending` if there are no
+    /// ready peers. Never registers any task wakeups.
```
Comment (teor2345) [inline zebra-network/src/peer_set/set.rs]:
```suggestion
    /// ready peers. Registers a wakeup if any peer has failed due to a disconnection, hang, or protocol error.
```

File: zebra-network/src/peer_set/set.rs (hunk 21 above)
Comment (teor2345) [reply zebra-network/src/peer_set/set.rs:1150]: This method does register wakeups for ready peer failures, I have edited the method comment.

And the suggested change is not needed, because the waker is shared among all the events that could wake the task.

**Review by arya2 — APPROVED** [review]

File: zebra-network/src/peer_set/set.rs (hunk 22 above)
Comment (arya2) [reply zebra-network/src/peer_set/set.rs:1137]: > any of those events can wake the task

Like a select?

Comment (teor2345) [reply zebra-network/src/peer_set/set.rs:1137]: Sort of, but much lower level. The context contains a waker, which gives the ability to wake the task.

Technically there is nothing stopping a future from storing a waker when it returns `Poll::Ready`, and in some cases in Zebra we do this in inner poll methods, in case the outer poll function returns `Pending` due to outer state or other inner poll methods.

> The typical life of a Waker is that it is constructed by an executor, wrapped in a [Context](https://docs.rs/futures/latest/futures/task/struct.Context.html), then passed to [Future::poll()](https://docs.rs/futures/latest/futures/future/trait.Future.html#tymethod.poll). Then, if the future chooses to return [Poll::Pending](https://docs.rs/futures/latest/futures/task/enum.Poll.html#variant.Pending), it must also store the waker somehow and call [Waker::wake()](https://docs.rs/futures/latest/futures/task/struct.Waker.html#method.wake) when the future should be polled again.

https://docs.rs/futures/latest/futures/task/struct.Waker.html

> When a future is not ready yet, poll returns Poll::Pending and stores a clone of the [Waker](https://doc.rust-lang.org/std/task/struct.Waker.html) copied from the current [Context](https://doc.rust-lang.org/std/task/struct.Context.html). This [Waker](https://doc.rust-lang.org/std/task/struct.Waker.html) is then woken once the future can make progress. For example, a future waiting for a socket to become readable would call .clone() on the [Waker](https://doc.rust-lang.org/std/task/struct.Waker.html) and store it. When a signal arrives elsewhere indicating that the socket is readable, [Waker::wake](https://doc.rust-lang.org/std/task/struct.Waker.html#method.wake) is called and the socket future’s task is awoken. Once a task has been woken up, it should attempt to poll the future again, which may or may not produce a final value.

https://doc.rust-lang.org/std/future/trait.Future.html#tymethod.poll
