### PR TITLE
fix(state): Use correct end heights for end of block subtrees during the full sync

### LINKED ISSUE #7532: bug: some subtrees have incorrect end heights after a full sync
### Steps to fix

- [x] Fix the bug
- [x] Remove different code for full sync and upgrading legacy states
- [ ] ~~Remove different code for end of block and middle of block~~ Edit: this is tricky to do
- [x] Test using sapling and orchard
- [ ] Optionally: test using full sync (+restart Zebra) and legacy upgrades
- [x] Revert PR #7555

### What happened?

I expected to see this happen:

Subtree end heights should be the block they are completed in.
Subtrees should match `zcashd`.

Instead, this happened: 

Subtree end heights were 1 more than they should be, under these conditions:
- the subtree was completed at the end of a block, and
- the subtree was created by a newly synced tip block (not an upgrade).

Some subtrees won't match `zcashd` after a full Zebra sync.

### What were you doing when the issue happened?

Testing PR #7531 on my local machine.

### Zebra logs

```
The application panicked (crashed).
Message:  already checked that the block completed a subtree: 
updated subtree:
index: Some(NoteCommitmentSubtreeIndex(0))
remaining notes: 0
is complete: true
original subtree:
index: NoteCommitmentSubtreeIndex(0)
remaining notes: 3
is complete: false
Location: zebra-state/src/service/finalized_state/disk_format/upgrade/add_subtrees.rs:599
Metadata:
version: 1.2.0+46.g8e74e49.modified
Zcash network: Mainnet 
running state version: 25.2.1
initial disk state version: 25.2.0                                                                                                                                                                         
features: default,getblocktemplate_rpcs,metrics_exporter_prometheus,prometheus,release_max_level_info 
branch: upgrade-subtrees-backwards
git commit: 8e74e49
```

### Zebra Version

zebrad 1.2.0 commit 8e74e49

### Which operating systems does the issue happen on?

- [X] Linux
- [ ] macOS
- [ ] Windows
- [ ] Other OS

### OS details

local machine

### Additional information

This bug would have been caught by ticket https://github.com/ZcashFoundation/zebra/issues/7446, but only if we found a test vector for "Completed Subtree at the end of the block", and "subtrees added with new tip blocks", and ran it on a full sync Zebra state.

The best way to detect this bug is a manual `zcash-rpc-diff` after a full sync of a new state, I'll add a check to ticket #7450.

In PR #7531, I refactored the upgrade and tip block subtrees to use the same code, which is how I found this bug. So a similar bug shouldn't happen again.

### PR DESCRIPTION
**Pull request by teor2345**
## Reviewer Questions

Does this PR have any data bugs?
Are there any other blocking issues? (For example, security bugs.)

Since this PR is on the critical path, I'd like other suggestions to go in other PRs or tickets.

## Motivation

When a subtree is created during the full sync, and the final note commitment is at the end of a block, the end height is one higher than it should be.

Close #7532

### Specifications

`zcashd` uses the height of the block the subtree ends in:
https://github.com/zcash/zcash/pull/6694

### Complex Code or Requirements

Because this bug fix is complex, I added some extra tests, and bumped the state version so the whole database will be upgraded again. I also cleared any data from the previous upgrade. This will make sure all our tests run on the new data.

## Solution

Refactor the subtree upgrade so it uses block validation code that has already been tested
Bump the state version and delete previous data, so the tests run on the data from this upgrade only

Use correct heights for subtrees completed at the end of a block. Previously, these subtrees had a height that was 1 higher than the block their final note was in. This bug only happened for subtrees created by new blocks. (And not for upgraded blocks.)

This bug would have been caught by ticket #7446, but only if we found a test vector for "Completed Subtree at the end of the block", and "subtrees added with new tip blocks", and ran it on a full sync Zebra state.

I refactored the upgrade and tip block subtrees to use the same code, which is how I found this bug. So a similar bug shouldn't happen again.

### Related Changes

Wait for the state upgrade in tests:
- before subtree gRPC tests
- before writing updated cached states (full syncs are ok, so are tests that don't write states)

Refactor the subtree upgrade so the upgrade can be done in reverse order, but don't reverse the order yet.

Fix some clippy lints.

### Testing

Add extra state validity tests, including a quick check before the upgrade runs for 20 minutes. The quick check runs on every Zebra launch, even in production.

## Review

This is a routine change, but it is on the critical path for getting the RPCs finished and tested. It is also blocking all the rest of the test tickets.

I'd like non-blocking suggestions to go in other PRs or tickets.

### Reviewer Checklist

  - [ ] Will the PR name make sense to users?
    - [ ] Does it need extra CHANGELOG info? (new features, breaking changes, large changes)
  - [ ] Are the PR labels correct?
  - [ ] Does the code do what the ticket and PR says?
    - [ ] Does it change concurrent code, unsafe code, or consensus rules?
  - [ ] How do you know it works? Does it have tests?

### CODE REVIEW

File: zebrad/tests/common/lightwalletd/wallet_grpc_test.rs [hunk 1]
```diff
@@ -339,6 +352,59 @@ pub async fn run() -> Result<()> {
...
+    if state_format_change.contains("launching upgrade task") {
+        let latest_version_for_adding_subtrees = latest_version_for_adding_subtrees();
+        tracing::info!(
+            ?test_type,
+            ?zebra_rpc_address,
+            %state_format_change,
+            %latest_version_for_adding_subtrees,
+            "waiting for zebrad subtree state upgrade..."
+        );
+        zebrad.expect_stdout_line_matches(&format!("marked database format as upgraded.*format_upgrade_version.*=.*{latest_version_for_adding_subtrees}"))?;
```
Comment (teor2345) [inline zebrad/tests/common/lightwalletd/wallet_grpc_test.rs]:
```suggestion
        //
        // TODO: this line will hang if the state upgrade finishes before the subtree tests start.
        // But that is unlikely with the 25.2 upgrade, because it takes 20+ minutes.
        // If it happens for a later upgrade, this code can be removed, as long as all the
        // lightwalletd cached states are version 25.2.2 or later.
        zebrad.expect_stdout_line_matches(&format!("marked database format as upgraded.*format_upgrade_version.*=.*{latest_version_for_adding_subtrees}"))?;
```

**Comment by teor2345** [comment]
> Error: Error: API rate limit exceeded for installation ID 1523599. If you reach out to GitHub Support for help, please include the request ID B04D:8776:1FF995:41593F:65040607.

https://github.com/ZcashFoundation/zebra/actions/runs/6195144535/job/16819307823?pr=7566#step:4:13

The tests should succeed if you re-run them in an hour or so.

File: zebra-chain/src/orchard/tree.rs [hunk 2]
```diff
@@ -394,6 +394,64 @@ impl NoteCommitmentTree {
...
+
+        Some(tree.position().into())
+    }
+
+    /// Returns true if this tree has at least one new subtree, when compared with `prev_tree`.
+    pub fn contains_new_subtree(&self, prev_tree: &Self) -> bool {
+        // A new subtree was completed by the last note commitment in this tree.
+        if self.is_complete_subtree() {
+            return true;
+        }
```
Comment (upbqdn) [inline zebra-chain/src/orchard/tree.rs]: This makes the function return `true` even when `self` equals `prev_tree` or the index of `self` is not greater than the index of `prev_tree`.

File: zebra-chain/src/orchard/tree.rs [hunk 3]
```diff
@@ -394,6 +394,64 @@ impl NoteCommitmentTree {
...
+
+        // Check for spurious index differences.
+        //
+        // There is one new subtree somewhere in the trees. It is either:
+        // - a new subtree at the end of the previous tree, or
+        // - a new subtree in this tree (but not at the end).
+        //
+        // This happens because the subtree index only increases when the first note is added to
```
Comment (upbqdn) [inline zebra-chain/src/orchard/tree.rs]: ###### Doc nit (optional)

It's not clear to me what "_This_" refers to. I assume it's the first item in the list above?

File: zebra-chain/src/sapling/tree.rs [hunk 4]
```diff
@@ -404,6 +462,48 @@ impl NoteCommitmentTree {
...
+            // If the subtree has no nodes, the remaining number of nodes is the number of nodes in
+            // a subtree.
+            None => {
+                // This position is guaranteed to be in the first subtree.
+                let first_position = 0.into();
+
+                let subtree_address = incrementalmerkletree::Address::above_position(
+                    TRACKED_SUBTREE_HEIGHT.into(),
+                    first_position,
+                );
```
Comment (upbqdn) [inline zebra-chain/src/sapling/tree.rs]: ###### Optional Simplifiaction

```suggestion
                let subtree_address = incrementalmerkletree::Address::above_position(
                    TRACKED_SUBTREE_HEIGHT.into(),
                    // This position is guaranteed to be in the first subtree.
                    0.into(),
                );
```

File: zebra-chain/src/orchard/tree.rs [hunk 5]
```diff
@@ -423,6 +481,48 @@ impl NoteCommitmentTree {
...
+            // If the subtree has no nodes, the remaining number of nodes is the number of nodes in
+            // a subtree.
+            None => {
+                // This position is guaranteed to be in the first subtree.
+                let first_position = 0.into();
+
+                let subtree_address = incrementalmerkletree::Address::above_position(
+                    TRACKED_SUBTREE_HEIGHT.into(),
+                    first_position,
+                );
```
Comment (upbqdn) [inline zebra-chain/src/orchard/tree.rs]: ###### Optional Simplifiaction

```suggestion
                let subtree_address = incrementalmerkletree::Address::above_position(
                    TRACKED_SUBTREE_HEIGHT.into(),
                    // This position is guaranteed to be in the first subtree.
                    0.into(),
                );
```

File: zebra-state/src/service/finalized_state/disk_format/upgrade/add_subtrees.rs [hunk 6]
```diff
@@ -14,161 +21,264 @@ use crate::service::finalized_state::{
 
 /// Runs disk format upgrade for adding Sapling and Orchard note commitment subtrees to database.
 ///
+/// Trees are added to the database in reverse height order, so that wallets can sync correctly
+/// while the upgrade is running.
+///
```
Comment (upbqdn) [inline zebra-state/src/service/finalized_state/disk_format/upgrade/add_subtrees.rs]: ###### Note (optional)

This doesn't hold for this PR, but I guess we can leave it here.

File: zebra-state/src/service/finalized_state/disk_format/upgrade/add_subtrees.rs [hunk 7]
```diff
@@ -387,46 +496,294 @@ fn check_orchard_subtrees(db: &ZebraDb) -> bool {
...
+#[must_use = "subtree should be written to the database after it is calculated"]
+#[instrument(skip(read_db, prev_tree, tree))]
+fn calculate_sapling_subtree(
+    read_db: &ZebraDb,
+    prev_end_height: Height,
+    prev_tree: Arc<sapling::tree::NoteCommitmentTree>,
+    end_height: Height,
+    tree: Arc<sapling::tree::NoteCommitmentTree>,
+) -> NoteCommitmentSubtree<sapling::tree::Node> {
+    // If a subtree is completed by a note commentment in the block at `end_height`,
```
Comment (upbqdn) [inline zebra-state/src/service/finalized_state/disk_format/upgrade/add_subtrees.rs]: ###### Optional Suggestion

```suggestion
    // If a subtree is completed by a note commitment in the block at `end_height`,
```

File: zebra-state/src/service/finalized_state/disk_format/upgrade/add_subtrees.rs [hunk 8]
```diff
@@ -387,46 +496,294 @@ fn check_orchard_subtrees(db: &ZebraDb) -> bool {
...
+#[must_use = "subtree should be written to the database after it is calculated"]
+#[instrument(skip(read_db, prev_tree, tree))]
+fn calculate_orchard_subtree(
+    read_db: &ZebraDb,
+    prev_end_height: Height,
+    prev_tree: Arc<orchard::tree::NoteCommitmentTree>,
+    end_height: Height,
+    tree: Arc<orchard::tree::NoteCommitmentTree>,
+) -> NoteCommitmentSubtree<orchard::tree::Node> {
+    // If a subtree is completed by a note commentment in the block at `end_height`,
```
Comment (upbqdn) [inline zebra-state/src/service/finalized_state/disk_format/upgrade/add_subtrees.rs]: ###### Optional Suggestion

```suggestion
    // If a subtree is completed by a note commitment in the block at `end_height`,
```

**Comment by teor2345** [comment]
## Questions for reviewers

Does this PR have any data bugs?
Are there any other blocking issues? (For example, security bugs.)

Since this PR is on the critical path, I'd like other suggestions to go in other PRs or tickets.

File: zebra-state/src/service/finalized_state/disk_format/upgrade/add_subtrees.rs [hunk 9]
```diff
@@ -180,76 +290,78 @@ pub fn run(
...
+                result = Err("completed subtree roots should match");
+                error!(?result);
             }
         }
         // Check that the final note has a greater subtree index if it didn't complete a subtree.
         else {
             let Some(prev_tree) = db.sapling_tree_by_height(&subtree.end.previous()) else {
-                error!(?subtree.end, "missing note commitment tree at subtree completion height");
-                is_valid = false;
+                result = Err("missing note commitment tree at subtree completion height");
```
Comment (upbqdn) [inline zebra-state/src/service/finalized_state/disk_format/upgrade/add_subtrees.rs]: ###### Optional Suggestion

```suggestion
                result = Err("missing note commitment tree below subtree completion height");
```

File: zebra-state/src/service/finalized_state/disk_format/upgrade/add_subtrees.rs [hunk 10]
```diff
@@ -272,99 +384,96 @@ fn check_sapling_subtrees(db: &ZebraDb) -> bool {
...
+                result = Err("completed subtree roots should match");
+                error!(?result);
             }
         }
         // Check that the final note has a greater subtree index if it didn't complete a subtree.
         else {
             let Some(prev_tree) = db.orchard_tree_by_height(&subtree.end.previous()) else {
-                error!(?subtree.end, "missing note commitment tree at subtree completion height");
-                is_valid = false;
+                result = Err("missing note commitment tree at subtree completion height");
```
Comment (upbqdn) [inline zebra-state/src/service/finalized_state/disk_format/upgrade/add_subtrees.rs]: ###### Optional Suggestion

```suggestion
                result = Err("missing note commitment tree below subtree completion height");
```

File: zebra-state/src/service/finalized_state/disk_format/upgrade/add_subtrees.rs [hunk 11]
```diff
@@ -374,7 +483,7 @@ fn check_orchard_subtrees(db: &ZebraDb) -> bool {
         .orchard_tree_by_height_range(..)
         // Exclude empty orchard tree and add subtree indexes
         .filter_map(|(height, tree)| Some((tree.subtree_index()?, height, tree)))
-        // Exclude heights that don't complete a subtree and count completed subtree
+        // Exclude heights that don't complete a subtree and count completed subtrees
         .filter_map(|(subtree_index, height, tree)| {
             if tree.is_complete_subtree() || subtree_index.0 > subtree_count {
```
Comment (upbqdn) [inline zebra-state/src/service/finalized_state/disk_format/upgrade/add_subtrees.rs:491]: ###### Optional

I just noticed this filter skips the tree with subtree index 0 if that tree is not a complete subtree. It might be worth mentioning that in a comment.

**Review by upbqdn — DISMISSED** [review]

**Comment by upbqdn** [comment]
I just reviewed this PR. Feel free to close all comments labeled as optional right away without addressing them.

File: zebra-chain/src/orchard/tree.rs (hunk 3 above)
Comment (teor2345) [reply zebra-chain/src/orchard/tree.rs]:
```suggestion
        // Spurious index differences happen because the subtree index only increases when the first note is added to
```

File: zebra-chain/src/orchard/tree.rs (hunk 2 above)
Comment (teor2345) [reply zebra-chain/src/orchard/tree.rs]: Ah, good catch! ~~I think a way to fix this bug is to make `self.is_complete_subtree()` the last line of this method.~~

This bug doesn't have any practical impact yet, but it's a trap for future uses of this method.

File: zebra-chain/src/sapling/tree.rs (hunk 4 above)
Comment (teor2345) [reply zebra-chain/src/sapling/tree.rs]: This will be fixed when I copy-paste-replace the orchard code:
https://github.com/ZcashFoundation/zebra/pull/7566/files/82bf50a37f5da716957e54fa85c205eee555869e#r1328982047

File: zebra-state/src/service/finalized_state/disk_format/upgrade/add_subtrees.rs (hunk 6 above)
Comment (teor2345) [reply zebra-state/src/service/finalized_state/disk_format/upgrade/add_subtrees.rs]: Oops, I thought I'd reverted all that code, but I must have missed this comment.. Happy to fix this since I have to edit the file anywa.

File: zebra-state/src/service/finalized_state/disk_format/upgrade/add_subtrees.rs (hunk 8 above)
Comment (teor2345) [reply zebra-state/src/service/finalized_state/disk_format/upgrade/add_subtrees.rs]: This will get fixed when I copy-paste-replace the sapling comments:
https://github.com/ZcashFoundation/zebra/pull/7566#discussion_r1329046372

File: zebra-state/src/service/finalized_state/disk_format/upgrade/add_subtrees.rs (hunk 11 above)
Comment (teor2345) [reply zebra-state/src/service/finalized_state/disk_format/upgrade/add_subtrees.rs:491]: I think I might leave this comment for @arya2 to clarify, because he wrote this code.

**Comment by teor2345** [comment]
My first fix in [5a1deb1](https://github.com/ZcashFoundation/zebra/pull/7566/commits/5a1deb1865071977df36dcb10e64c9e328f8c322) was wrong, but I think I fixed it in [41eef09](https://github.com/ZcashFoundation/zebra/pull/7566/commits/41eef096793dca9ec4d94318f117ec2cae675ad5).

There was also a bug in the quick check which skipped the same subtrees, which is why it didn't detect this issue on my local machine.

Edit: ok let's try again with [54f2bba](https://github.com/ZcashFoundation/zebra/pull/7566/commits/54f2bba601b55575b5748f2636ab5aafd54ca433). Good news is that the quick check detected that bug.

**Review by oxarbitrage — APPROVED** [review]
approving without reviewing so it can be merged fast, @upbqdn approved previously.

File: zebra-chain/src/orchard/tree.rs [hunk 12]
```diff
@@ -394,6 +394,72 @@ impl NoteCommitmentTree {
...
+        //
+        // Spurious index differences happen because the subtree index only increases when the
+        // first note is added to the new subtree. So we need to exclude subtrees completed by the
+        // last note commitment in the previous tree.
+        //
+        // We also need to exclude empty previous subtrees, because the index changes to zero when
+        // the first note is added, but a subtree wasn't completed.
+        if prev_tree.is_complete_subtree() || prev_index == -1 {
+            return false;
+        }
```
Comment (upbqdn) [inline zebra-chain/src/orchard/tree.rs:457]: I noticed two issues:

1. The method returns `false` here when `prev_tree` is empty, so `prev_index` is -1, but `self` is a complete subtree with index 0. I think the returned value should be `true` for this case. This case was covered correctly before the refactor.

2. The method returns `false` here when `index_difference` is 1, and both `prev_tree` and `self` are complete subtrees. This case was covered correctly before the refactor.

I think we need to refactor this method again.

File: zebra-chain/src/orchard/tree.rs [hunk 13]
```diff
@@ -394,6 +394,72 @@ impl NoteCommitmentTree {
...
+        // If the indexes are equal, there can only be a new subtree if `self` just completed it.
+        if index == prev_index {
+            return self.is_complete_subtree();
+        }
+
+        // If `self` is the next index, check for spurious index differences.
+        //
+        // There is one new subtree somewhere in the trees. It is either:
+        // - a new subtree at the end of the previous tree, or
+        // - a new subtree in this tree (but not at the end).
```
Comment (upbqdn) [inline zebra-chain/src/orchard/tree.rs:447]: We don't know here that the subtree is not at the end because we don't check the output of `self.is_complete_subtree()` after the refactor.

File: zebra-chain/src/orchard/tree.rs [hunk 14]
```diff
@@ -394,6 +394,72 @@ impl NoteCommitmentTree {
...
+        // There is at least one new subtree, even if there is a spurious index difference.
+        if index_difference > 1 {
+            return true;
+        }
+
+        // If the indexes are equal, there can only be a new subtree if `self` just completed it.
+        if index == prev_index {
+            return self.is_complete_subtree();
+        }
+
```
Comment (teor2345) [inline zebra-chain/src/orchard/tree.rs:442]: I think both issues can be resolved by adding this code here:

```rust
// If `self` has the next index, check if it completed a subtree.
if self.is_complete_subtree() {
    return true;
}
```

File: zebra-chain/src/orchard/tree.rs (hunk 13 above)
Comment (teor2345) [reply zebra-chain/src/orchard/tree.rs:447]: See my suggestion above.

File: zebra-chain/src/orchard/tree.rs (hunk 12 above)
Comment (teor2345) [reply zebra-chain/src/orchard/tree.rs:457]: See my suggestion above, which covers both cases.

File: zebra-chain/src/orchard/tree.rs (hunk 14 above)
Comment (teor2345) [reply zebra-chain/src/orchard/tree.rs:442]: I can do this change in another PR.

Comment (upbqdn) [reply zebra-chain/src/orchard/tree.rs:442]: Looks good. I also think the suggested solution will resolve both issues.
