### PR TITLE
fix(mempool): Avoid panicking when a transaction is unexpectedly missing in the mempool

### LINKED ISSUE #10038: panic: invalid transaction key
Sentry Issue: [ZEBRAD-15](https://zfnd.sentry.io/issues/6980655950/?referrer=github_integration)

```
panic: [31mThe application panicked (crashed).[0m
Message:  [36minvalid transaction key[0m
Location: [35mzebrad/src/components/mempool/storage/verified_set.rs[0m:[35m288[0m

Diagnostic metadata:
version: 3.0.0-rc.0
Zcash network: Mainnet
running state version: 27.0.0
initial disk state version: 27.0.0
features: default,default_release_binaries,howudoin,indicatif,metrics_exporter_prometheus,progress_bar,prometheus,release_max_level_info,sentry
branch: VERGEN_IDEMPOTENT_OUTPUT
git commit: eed8e07
commit timestamp: VERGEN_IDEMPOTENT_OUTPUT
target triple: x86_64-unknown-linux-gnu
rust compiler: 1.89.0
rust release date: 2025-08-04
optimization level: 3
debug checks: false

Backtrace omitted. Run with RUST_BACKTRACE=1 environment variable to display it.
Run with RUST_BACKTRACE=full to include source snippets.

Consider reporting this error using this URL: https://github.com/ZcashFoundation/zebra/issues/new?title=%3Cautogenerated-issue%3E&body=%23%23+Error%0A%60%60%60%0Ainvalid+transaction+key%0A%60%60%60%0A%0A%23%23+Metadata%0A%7Ckey%7Cvalue%7C%0A%7C--%7C--%7C%0A%7C**version**%7C3.0.0-rc.0%7C%0A%7C**Zcash+network**%7CMainnet%7C%0A%7C**running+state+version**%7C27.0.0%7C%0A%7C**initial+disk+state+version**%7C27.0.0%7C%0A%7C**features**%7Cdefault%2Cdefault_release_binaries%2Chowudoin%2Cindicatif%2Cmetrics_exporter_prometheus%2Cprogress_bar%2Cprometheus%2Crelease_max_level_info%2Csentry%7C%0A%7C**branch**%7CVERGEN_IDEMPOTENT_OUTPUT%7C%0A%7C**git+commit**%7Ceed8e07%7C%0A%7C**commit+timestamp**%7CVERGEN_IDEMPOTENT_OUTPUT%7C%0A%7C**target+triple**%7Cx86_64-unknown-linux-gnu%7C%0A%7C**rust+compiler**%7C1.89.0%7C%0A%7C**rust+release+date**%7C2025-08-04%7C%0A%7C**optimization+level**%7C3%7C%0A%7C**debug+checks**%7Cfalse%7C%0A%7C**location**%7Czebrad%2Fsrc%2Fcomponents%2Fmempool%2Fstorage%2Fverified_set.rs%3A288%3A22%7C%0A
```

### PR DESCRIPTION
**Pull request by arya2**
## Motivation

Closes #10038.

## Solution

- Logs a warning instead of panicking when a transaction that should be removed from the mempool is missing in the mempool's verified set, and
- Avoids calling `remove()` with tx ids that are not in the mempool.

Related:
- Fixes a bug where mined transactions were not being removed as dependencies of transactions in the mempool.

### PR Checklist

- [ ] The PR name is suitable for the release notes.
- [ ] The PR follows the [contribution guidelines](https://github.com/ZcashFoundation/zebra/blob/main/CONTRIBUTING.md).
- [ ] The library crate changelogs are up to date.
- [ ] The solution is tested.
- [ ] The documentation is up to date.

### CODE REVIEW

File: zebra-node-services/src/mempool/transaction_dependencies.rs [hunk 1]
```diff
@@ -73,7 +73,7 @@ impl TransactionDependencies {
                 };
 
                 // TODO: Move this struct to zebra-chain and log a warning here if the dependency was not found.
-                let _ = dependencies.remove(&dependent_id);
+                dependencies.remove(&mined_tx_id);
```
Comment (conradoplg) [inline zebra-node-services/src/mempool/transaction_dependencies.rs]: Good catch. I wonder if this is what was causing #9699

**Review by conradoplg — DISMISSED** [review]
Looks good. I think it just needs making clippy happy

**Comment by conradoplg** [comment]
@arya2 just a reminder about this PR that should merge before the release, the clippy fix is related to the PR itself

**Review by conradoplg — DISMISSED** [review]

**Review by conradoplg — APPROVED** [review]
