### PR TITLE
fix(panic): Stop panicking on async task cancellation on shutdown in network and state futures

### LINKED ISSUE #7170: Zebra sometimes panics in the state and network tasks on shutdown
### What happened?

I expected to see this happen:

A shutdown with no panics.

Instead, this happened:

> 2023-07-06T02:30:10.476975Z  INFO {net="Test"}: zebrad::components::tokio: waiting for async tokio tasks to shut down TOKIO_SHUTDOWN_TIMEOUT=20s
> The application panicked (crashed).
> Message:  panic in ReadRequest::Tip: JoinError::Cancelled(Id(23437))
> Location: zebra-state/src/service.rs:1208

https://github.com/ZcashFoundation/zebra/actions/runs/5470776835/jobs/9961459769#step:5:347

> 2023-07-10T04:02:08.269874Z  INFO {net="Test"}: zebrad::components::tokio: waiting for async tokio tasks to shut down TOKIO_SHUTDOWN_TIMEOUT=20s
> The application panicked (crashed).
> Message:  panic in next peer address book task: JoinError::Cancelled(Id(9554))
> Location: /opt/zebrad/zebra-network/src/peer_set/candidate_set.rs:407

https://github.com/ZcashFoundation/zebra/actions/runs/5503766375/jobs/10029501421#step:5:326

### What were you doing when the issue happened?

Running Zebra in CI and terminating the process.

### Zebra logs

You can see the full logs at:
https://github.com/ZcashFoundation/zebra/actions/runs/5470776835/jobs/9961459769#step:5:347
https://github.com/ZcashFoundation/zebra/actions/runs/5503766375/jobs/10029501421#step:5:326

### Zebra Version

1.0.1 with PR #7029
1.0.1 with PRs #7177 + #7183 in merge queue PR #7190

### Which operating systems does the issue happen on?

- [X] Linux
- [ ] macOS
- [ ] Windows
- [ ] Other OS

### OS details

Ubuntu 4   22.04.2 5   LTS GitHub Runner

### Additional information

This is a low priority because the cache is not corrupted, and the user was shutting down anyway. It also causes rare CI failures. (Any tokio update could make them more common.)

Every JoinError::Cancelled in every state and network request will need to be ignored, something like this:
https://github.com/ZcashFoundation/zebra/blob/1014e3c7855df1c53d0bf0ef571d2cecd9b795f8/zebra-network/src/peer_set/initialize.rs#L633-L640

It might be easier to do this using a `CheckForPanic::check_for_panic()` trait method, implemented on `JoinError` (async and thread).

State Metadata:
version: 1.0.1
Zcash network: Testnet
state version: 25
features: default,default_release_binaries,release_max_level_info,sentry
target triple: x86_64-unknown-linux-gnu
rust compiler: 1.70.0
rust release date: 2023-05-31
optimization level: 3
debug checks: false

Network Metadata:
version: 1.0.1
Zcash network: Testnet
state version: 25
features: default,default_release_binaries,release_max_level_info,sentry
target triple: x86_64-unknown-linux-gnu
rust compiler: 1.70.0
rust release date: 2023-05-31
optimization level: 3
debug checks: false

### PR DESCRIPTION
**Pull request by teor2345**
## Motivation

We want to stop Zebra panicking on shutdown.

Close #7170

### Specifications

Threads:
https://doc.rust-lang.org/std/thread/struct.JoinHandle.html#method.is_finished

Async tasks:
https://docs.rs/tokio/latest/tokio/task/struct.JoinHandle.html#impl-Future-for-JoinHandle%3CT%3E
https://docs.rs/tokio/latest/tokio/task/struct.JoinError.html#method.try_into_panic

### Complex Code or Requirements

This PR replaces a bunch of complex panic-handling code with consistent trait methods.

## Solution

- Create generic traits for checking and waiting for panics
- Implement those traits on OS threads and async tasks
- Use those trait impls to fix the panic and cancel bugs
- Replace existing manual implementations with the trait impls

### Testing

I've changed enough impls in this PR that any bugs should show up in the tests as they shut Zebra down.

## Review

This is a routine bug fix.

### Reviewer Checklist

  - [ ] Will the PR name make sense to users?
    - [ ] Does it need extra CHANGELOG info? (new features, breaking changes, large changes)
  - [ ] Are the PR labels correct?
  - [ ] Does the code do what the ticket and PR says?
    - [ ] Does it change concurrent code, unsafe code, or consensus rules?
  - [ ] How do you know it works? Does it have tests?

## Follow Up Work

We can use these methods on `JoinError` and `JoinHandle` throughout Zebra, or maybe create our own `JoinHandle` and `JoinError` types that automatically use these methods.

### CODE REVIEW

File: zebra-chain/src/diagnostic/task/thread.rs [hunk 1]
```diff
@@ -0,0 +1,111 @@
...
+    sync::Arc,
+    thread::{self, JoinHandle},
+};
+
+use super::{CheckForPanics, WaitForPanics};
+
+impl<T> CheckForPanics for thread::Result<T> {
+    type Output = T;
+
+    /// Waits for the thread to finish, then panics if the thread panicked.
```
Comment (arya2) [inline zebra-chain/src/diagnostic/task/thread.rs]:
```suggestion
    /// Panics if the thread panicked.
```

File: zebra-chain/src/diagnostic/task/thread.rs [hunk 2]
```diff
@@ -0,0 +1,111 @@
...
+    type Output = Option<T>;
+
+    /// If this is the final `Arc`, checks if the thread has finished, then panics if the thread
+    /// panicked. Otherwise, returns the thread's return value.
+    ///
+    /// If the thread has not finished, or this is not the final `Arc`, returns `None`.
+    fn check_for_panics(self) -> Self::Output {
+        let Some(handle) = self.take() else {
+            return None;
+        };
```
Comment (arya2) [inline zebra-chain/src/diagnostic/task/thread.rs]: Nitpick:
```suggestion
        let handle = self.take()?;
```

File: zebra-chain/src/diagnostic/task/thread.rs [hunk 3]
```diff
@@ -0,0 +1,111 @@
...
+    ///
+    /// If this is not the final `Arc`, drops the handle and returns `None`.
+    fn wait_for_panics(self) -> Self::Output {
+        let Some(handle) = self.take() else {
+            return None;
+        };
+
+        // This is more readable as an expanded statement.
+        #[allow(clippy::manual_map)]
+        if let Some(output) = handle.wait_for_panics() {
```
Comment (arya2) [inline zebra-chain/src/diagnostic/task/thread.rs]: Nitpick:
```suggestion
        // This is more readable as an expanded statement.
        #[allow(clippy::manual_map)]
        if let Some(output) = self.take()?.wait_for_panics() {
```

File: zebra-chain/src/diagnostic/task/thread.rs [hunk 4]
```diff
@@ -0,0 +1,111 @@
...
+}
+
+impl<T> CheckForPanics for &mut Option<Arc<JoinHandle<T>>> {
+    type Output = Option<T>;
+
+    /// If this is the final `Arc`, checks if the thread has finished, then panics if the thread
+    /// panicked. Otherwise, returns the thread's return value.
+    ///
+    /// If the thread has not finished, or this is not the final `Arc`, returns `None`.
+    fn check_for_panics(self) -> Self::Output {
```
Comment (arya2) [inline zebra-chain/src/diagnostic/task/thread.rs:74]: Does this need `#[track_caller]` as well?

File: zebra-chain/Cargo.toml [hunk 5]
```diff
@@ -24,6 +24,11 @@ json-conversion = [
     "serde_json",
 ]
 
+# Async error handling convenience traits
+async-error = [
```
Comment (arya2) [inline zebra-chain/Cargo.toml:28]: Why the new feature?

File: zebra-state/src/service.rs [hunk 6]
```diff
@@ -1255,10 +1253,7 @@ impl Service<ReadRequest> for ReadStateService {
                         Ok(ReadResponse::BestChainNextMedianTimePast(median_time_past?))
                     })
                 })
-                .map(|join_result| {
-                    join_result.expect("panic in ReadRequest::BestChainNextMedianTimePast")
-                })
-                .boxed()
+                .wait_for_panics()
```
Comment (arya2) [inline zebra-state/src/service.rs:1256]: Optional/Nitpick: It may be nice to pass in arguments for log or panic messages, but `#[track_caller]` should be enough.

**Review by arya2 — DISMISSED** [review]
This looks great, thank you for the simplification!

File: zebra-chain/Cargo.toml (hunk 5 above)
Comment (teor2345) [reply zebra-chain/Cargo.toml:28]: Because some developers might want to depend on a parsing crate that doesn't depend on tokio. (I think we've had this request or concern before.)

File: zebra-state/src/service.rs (hunk 6 above)
Comment (teor2345) [reply zebra-state/src/service.rs:1256]: Yep, that can be added in a later PR if it turns out it's needed.

File: zebra-chain/src/diagnostic/task/thread.rs (hunk 4 above)
Comment (teor2345) [reply zebra-chain/src/diagnostic/task/thread.rs:74]: They all do, thanks for catching that. Fixed in [b6a4f63](https://github.com/ZcashFoundation/zebra/pull/7219/commits/b6a4f631cd1daaf0fe8e2922a5753e36bbd60e81)

**Review by arya2 — APPROVED** [review]
