### PR TITLE
Fix a deadlock between the crawler and dialer, and other hangs

### LINKED ISSUE #1905: Zebra gradually loses peer connections, until it has none left
**Version**

`zebrad 1.0.0-alpha.3` commit 6473ed99

**Platform**

`Linux ... 5.4.96 #1-NixOS SMP Sun Feb 7 14:35:50 UTC 2021 x86_64 GNU/Linux`

**Description**

Sometimes, on testnet, Zebra gradually loses peers, until it has none left.

Sometimes the peers are lost after Zebra disconnects them due to block download or verify errors. Other times, the peers just seem to disconnect themselves.

Zebra should try to reconnect to these peers, but it doesn't seem to get any peers back.

Maybe Zebra isn't trying to connect. Or maybe the connections keep failing. Zebra might be triggering `zcashd`'s peer blocklist, due to bugs like #1848. Or there could be a peer address or connection state handling issue in Zebra's network stack.

This issue doesn't seem to happen that often (I've only seen it once in weeks of local testing). Our current reliability standard of 2 weeks continuous runtime: Zebra easily achieves that standard on mainnet, and mostly achieves that standard on testnet.

Therefore, this issue is a low priority, until it affects CI or other node deployments.

**Related Tickets**

Fixing #1904 will get Zebra better peers from the DNS seeders on testnet
Fixing #1848 and other network security issues will make Zebra's network stack more reliable

This ticket might block #1791, if it happens often enough in our CI

**Commands**

`zebrad start`, configured to use testnet with the DNS seeders and a few local peers.

**Logs**

The relevant logs are:
```
Mar 12 12:20:52.596  INFO {zebrad="6473ed99" net="Test"}:add_initial_peers: zebra_network::peer_set::initialize: connecting to initial peer set initial_peers={120.77.82.190:18233, 91.121.88.52:18233, 54.209.49.207:18233, 37.59.57.96:18233, 157.245.113.22:18233, 209.141.47.197:18233, 127.0.0.1:38233, 192.168.215.106:58233, 127.0.0.1:58233, 192.168.215.108:38233, 51.15.166.148:18233, 47.98.224.31:18233, 13.115.17.0:18233, 192.168.215.106:38233, 95.216.242.46:18233, 138.197.216.253:18233, 3.112.190.48:18233, 192.168.215.108:58233, 101.37.77.121:18233, 217.160.142.49:18233, 198.199.112.230:18233, 138.68.230.245:18233, 88.99.162.254:18233, 13.228.164.120:18233}
Mar 12 12:20:52.596  INFO {zebrad="6473ed99" net="Test"}:add_initial_peers: zebra_network::peer_set::initialize: an initial peer connection failed e=ConnectionClosed
Mar 12 12:20:52.957  INFO {zebrad="6473ed99" net="Test"}:add_initial_peers: zebra_network::peer_set::initialize: an initial peer connection failed e=Os { code: 111, kind: ConnectionRefused, message: "Connection refused" }
Mar 12 12:20:53.340  INFO {zebrad="6473ed99" net="Test"}:add_initial_peers: zebra_network::peer_set::initialize: an initial peer connection failed e=ObsoleteVersion(Version(170008))
Mar 12 12:20:53.612  INFO {zebrad="6473ed99" net="Test"}:add_initial_peers: zebra_network::peer_set::initialize: an initial peer connection failed e=ObsoleteVersion(Version(170007))
Mar 12 12:20:53.645  INFO {zebrad="6473ed99" net="Test"}:add_initial_peers: zebra_network::peer_set::initialize: an initial peer connection failed e=ObsoleteVersion(Version(170009))
Mar 12 12:20:55.568  INFO {zebrad="6473ed99" net="Test"}:add_initial_peers: zebra_network::peer_set::initialize: an initial peer connection failed e=Os { code: 113, kind: Other, message: "No route to host" }
Mar 12 12:20:56.597  INFO {zebrad="6473ed99" net="Test"}:add_initial_peers: zebra_network::peer_set::initialize: an initial peer connection failed e=Elapsed(())
...
Mar 12 12:21:53.815  INFO {zebrad="6473ed99" net="Test"}:sync:extend_tips: zebra_network::peer_set::set: network request with no ready peers: finding more peers, waiting for 4 peers to answer requests
Mar 12 12:22:53.815  INFO {zebrad="6473ed99" net="Test"}:sync:extend_tips: zebra_network::peer_set::set: network request with no ready peers: finding more peers, waiting for 3 peers to answer requests
Mar 12 12:29:38.849  INFO {zebrad="6473ed99" net="Test"}:sync:extend_tips: zebra_network::peer_set::set: network request with no ready peers: finding more peers, waiting for 2 peers to answer requests
Mar 12 12:39:48.600  WARN {zebrad="6473ed99" net="Test"}:sync: zebrad::components::sync: error downloading and verifying block e=Elapsed(())
Mar 12 12:40:49.606  INFO {zebrad="6473ed99" net="Test"}:sync:obtain_tips: zebra_network::peer_set::set: network request with no ready peers: finding more peers, waiting for 1 peers to answer requests
Mar 12 12:40:49.703  INFO {zebrad="6473ed99" net="Test"}:sync: zebrad::components::sync: extending tips tips.len=1 in_flight=372 lookahead_limit=2000
Mar 12 12:40:49.703  INFO {zebrad="6473ed99" net="Test"}:sync:extend_tips: zebrad::components::sync: trying to extend chain tips tips=1
Mar 12 12:40:49.791  INFO {zebrad="6473ed99" net="Test"}:sync: zebrad::components::sync: extending tips tips.len=1 in_flight=743 lookahead_limit=2000
...
Mar 12 12:40:49.962  INFO {zebrad="6473ed99" net="Test"}:sync:extend_tips: zebrad::components::sync: trying to extend chain tips tips=1
Mar 12 12:40:50.060  WARN {zebrad="6473ed99" net="Test"}:sync: zebrad::components::sync: error downloading and verifying block e=Block(Block { source: AlreadyInChain(block::Hash("00015eebadb01f74e09c0f7cbd03673c61fa5689d9b3fef3a98930c623a26ca0"), 308) })
Mar 12 12:40:50.060  INFO {zebrad="6473ed99" net="Test"}:sync: zebrad::components::sync: waiting to restart sync timeout=61s
Mar 12 12:41:25.515  INFO {zebrad="6473ed99" net="Test"}:peer{addr=127.0.0.1:38233}:msg_as_req{msg=getblocks}:state: zebra_state::service: responding to peer GetBlocks or GetHeaders final_height=Height(499) response_len=500 chain_tip_height=Height(282491) stop_height=None intersection_height=None
Mar 12 12:41:51.063  INFO {zebrad="6473ed99" net="Test"}:sync: zebrad::components::sync: starting sync, obtaining new tips
Mar 12 12:41:51.063  INFO {zebrad="6473ed99" net="Test"}:sync:obtain_tips:state: zebra_state::util: created block locator tip_height=Height(282491) min_locator_height=282392 locators=[Height(282491), Height(282490), Height(282489), Height(282487), Height(282483), Height(282475), Height(282459), Height(282427), Height(282392)]
Mar 12 12:41:51.063  INFO {zebrad="6473ed99" net="Test"}:sync:obtain_tips: zebrad::components::sync: trying to obtain new chain tips tip=block::Hash("0013da35d7196632f70cfa9fcc6e22906db20d21430ec08cfd2ba231bfd594b4")
Mar 12 12:41:51.063  INFO {zebrad="6473ed99" net="Test"}:sync:obtain_tips: zebra_network::peer_set::set: network request with no ready peers: finding more peers, waiting for 1 peers to answer requests
Mar 12 12:43:22.597  WARN {zebrad="6473ed99" net="Test"}:sync:obtain_tips: zebra_network::peer_set::set: network request with no peer connections. Hint: check your network connection
Mar 12 12:44:37.597  WARN {zebrad="6473ed99" net="Test"}:sync:obtain_tips: zebra_network::peer_set::set: network request with no peer connections. Hint: check your network connection
```

### LINKED ISSUE #1941: Zebra lags behind the best tip on testnet
**Version**

`zebrad` 1.0.0-alpha.5 with PR #1940

**Platform**

`Linux ... 5.4.96 #1-NixOS SMP Sun Feb 7 14:35:50 UTC 2021 x86_64 GNU/Linux`

**Description**

Testnet instances lag a few hundred blocks behind the tip synced by `zcashd`.

The `zcashd` tip is 1338659, and the Zebra tip is 1338519, a difference of 140 blocks.

We've had this bug before, it's possibly due to either network code hangs or peer issues (#1905), or the small number of peers on testnet (#704). I haven't seen it happen on mainnet since the late 2020 / early 2021 network fixes.

**Commands**

`zebrad start` with an epemeral testnet config with some local peers

**Logs**

```
Mar 25 17:17:05.551  INFO {zebrad="98726b0c" net="Test"}:peer{addr=127.0.0.1:38233}:msg_as_req{msg=getblocks}:state: zebra_state::service: responding to peer GetBlocks or GetHeaders final_height=Height(1338519) response_len=0 chain_tip_height=Height(1338519) stop_height=None intersection_height=Some(Height(1338519))
Mar 25 17:17:07.593  INFO {zebrad="98726b0c" net="Test"}:sync: zebrad::components::sync: exhausted prospective tip set
Mar 25 17:17:07.593  INFO {zebrad="98726b0c" net="Test"}:sync: zebrad::components::sync: waiting to restart sync timeout=61s
Mar 25 17:18:08.595  INFO {zebrad="98726b0c" net="Test"}:sync: zebrad::components::sync: starting sync, obtaining new tips
Mar 25 17:18:08.595  INFO {zebrad="98726b0c" net="Test"}:sync:obtain_tips:state: zebra_state::util: created block locator tip_height=Height(1338519) min_locator_height=1338420 locators=[Height(1338519), Height(1338518), Height(1338517), Height(1338515), Height(1338511), Height(1338503), Height(1338487), Height(1338455), Height(1338420)]
Mar 25 17:18:08.595  INFO {zebrad="98726b0c" net="Test"}:sync:obtain_tips: zebrad::components::sync: trying to obtain new chain tips tip=block::Hash("003e1b484c2c14ef29691c3640a7d5d66c4454029d7fb731a5b7c5111bad6fc4")
Mar 25 17:18:12.554  INFO {zebrad="98726b0c" net="Test"}:peer{addr=127.0.0.1:38233}:msg_as_req{msg=getblocks}:state: zebra_state::service: responding to peer GetBlocks or GetHeaders final_height=Height(1338519) response_len=0 chain_tip_height=Height(1338519) stop_height=None intersection_height=Some(Height(1338519))
Mar 25 17:18:14.597  INFO {zebrad="98726b0c" net="Test"}:sync: zebrad::components::sync: exhausted prospective tip set
Mar 25 17:18:14.597  INFO {zebrad="98726b0c" net="Test"}:sync: zebrad::components::sync: waiting to restart sync timeout=61s
```

### PR DESCRIPTION
**Pull request by teor2345**
## Motivation

In #1905, Zebra gradually loses peer connections, until there are none left. Then it stops making sync progress.

When this issue happens, a large number of peers are stuck in the `attempt_pending` state, despite the handshake timeout.

This issue also impacted the `peer::Connection` refactor in #1817, and a bunch of upcoming zebra-network security fixes.

## Solution

- Stop ignoring inbound message errors
- Add timeouts during handshake setup
- Add a timeout to the candidate set update
- Use the `select!` macro in the crawler to avoid starvation
- Spawn a separate task for each handshake
- Increase the crawl fanout to improve address diversity
- Avoid starvation when using the `select` function
- Fix priority of multiple ready futures in the `select` function
- Add correctness documentation

The code in this pull request has:
  - [x] Documentation Comments
  - [x] Existing Unit Tests and Integration Tests

## Review

@dconnolly or @oxarbitrage can review - whoever is available.

I'd like to get this merged in the next few days. It doesn't directly conflict with the other security fixes, but it will make them harder to test.

## Related Issues

Closes #1905 (based on 3 mainnet and 3 testnet nodes x 3 days of testing).
Closes #1941 (based on 3 testnet nodes x 3 days of testing).
Possibly closes some other related hang or reliability issues.

Deals with part of the #1892 and #1657 refactors.

### CODE REVIEW

**Comment by teor2345** [comment]
I'm going to put this PR in draft until I've tested a few full syncs over the weekend.

Feel free to review it or run it yourselves - I don't expect to be changing it much.

**Comment by teor2345** [comment]
Coverage is failing due to type errors in a dependency, maybe the most recent nightly has a bug?

I'll open a PR on Monday if no-one else gets to it first.

**Comment by teor2345** [comment]
I added a small change that avoids starvation when using the `future::select` function, and prioritises multiple ready futures correctly.

File: zebra-network/src/peer_set/initialize.rs [hunk 1]
```diff
@@ -315,74 +350,125 @@ where
...
-                            .map_err(move |e| {
-                                debug!(?candidate.addr, ?e, "failed to connect to candidate");
-                                candidate
-                            })
-                            .boxed(),
-                    );
+                    // Too many pending handshakes already
+                    DemandDrop
+                } else if let Some(candidate) = candidates.next().await {
+                    // candidates.next has a short delay, and briefly holds the address
```
Comment (teor2345) [inline zebra-network/src/peer_set/initialize.rs:363]:
```suggestion
                    // candidates.next has a short timeout, and briefly holds the address
```
```suggestion
                    // candidates.next has a short delay, and briefly holds the address
```

**Comment by teor2345** [comment]
@dconnolly or @oxarbitrage this fix is now ready for review.

Let me know if you want to do a walkthrough.

(I tried to split this PR, but unfortunately these changes all depend on each other and modify similar files.)

File: zebra-network/src/peer/connection.rs [hunk 2]
```diff
@@ -404,14 +420,25 @@ where
...
-                    match future::select(peer_rx.next(), cancel)
+                    // CORRECTNESS
+                    //
+                    // Currently, select prefers the first future if multiple
+                    // futures are ready.
+                    //
+                    // The peer can starve timeouts and cancellations, if it
+                    // sends an uninterrupted series of messages. But this is
+                    // unlikely in practice, due to network delays.
+                    //
```
Comment (teor2345) [inline zebra-network/src/peer/connection.rs]: This comment is now outdated
```suggestion
```

File: zebra-network/src/peer/handshake.rs [hunk 3]
```diff
@@ -376,22 +384,44 @@ where
...
-                                .await;
+                        match &msg {
+                            Ok(msg) => {
+                                metrics::counter!(
+                                    "zcash.net.in.messages",
+                                    1,
+                                    "command" => msg.to_string(),
+                                    "addr" => addr.to_string(),
+                                );
+                                use futures::sink::SinkExt;
```
Comment (oxarbitrage) [inline zebra-network/src/peer/handshake.rs]: It seems to me that none of the `SinkExt` imports (there are 3 of them in this file) are actually needed. Unsure why we have no warning about them (maybe because they are in `async` blocks?) but i tried removing them all and all the tests complete fine. I think it will be fine to remove them in this PR.

File: zebra-network/src/peer/handshake.rs [hunk 4]
```diff
@@ -510,17 +572,46 @@ where
                                 // Heartbeats are checked internally to the
                                 // connection logic, but we need to wait on the
                                 // response to avoid canceling the request.
-                                match rx.await {
-                                    Ok(_) => tracing::trace!("got heartbeat response"),
-                                    Err(_) => {
-                                        tracing::trace!(
+                                //
```
Comment (oxarbitrage) [inline zebra-network/src/peer/handshake.rs:576]:
```suggestion

```

File: zebra-network/src/peer_set/initialize.rs [hunk 5]
```diff
@@ -315,74 +350,125 @@ where
...
-            select(demand_rx.next(), crawl_timer.next()),
-            handshakes.next(),
-        )
-        .await
-        {
-            Left((Left((Some(_demand), _)), _)) => {
+
+        let crawler_action = tokio::select! {
+            a = handshakes.next() => a.expect("handshakes never terminates, because it contains a future that never resolves"),
+            a = crawl_timer.next() => a.expect("crawl_timer never terminates"),
```
Comment (oxarbitrage) [inline zebra-network/src/peer_set/initialize.rs]: For clarification maybe add `crawl_timer never terminates, because ...`

**Review by oxarbitrage — DISMISSED** [review]
I think it looks great, i made a few minor suggestions.

File: zebra-network/src/peer/handshake.rs (hunk 3 above)
Comment (teor2345) [reply zebra-network/src/peer/handshake.rs]: SinkExt is included in `futures::prelude::*`:
https://docs.rs/futures/0.3.13/futures/prelude/index.html

Comment (teor2345) [reply zebra-network/src/peer/handshake.rs]:
```suggestion
```

File: zebra-network/src/peer/handshake.rs [hunk 6]
```diff
@@ -376,22 +384,44 @@ where
...
+                                    .await;
+                            }
+                            Err(err) => {
+                                metrics::counter!(
+                                    "zebra.net.in.errors",
+                                    1,
+                                    "error" => err.to_string(),
+                                    "addr" => addr.to_string(),
+                                );
+                                use futures::sink::SinkExt;
```
Comment (teor2345) [inline zebra-network/src/peer/handshake.rs]:
```suggestion
```

File: zebra-network/src/peer/handshake.rs [hunk 7]
```diff
@@ -448,19 +478,42 @@ where
...
+            // The address book state can be updated via `ClientRequest.tx`, or the
+            // timestamp_collector.
+            //
+            // Returning from the spawned closure terminates the connection's heartbeat task.
             let heartbeat_span = tracing::debug_span!(parent: connection_span, "heartbeat");
             tokio::spawn(
                 async move {
                     use super::ClientRequest;
                     use futures::future::Either;
+                    use futures::sink::SinkExt;
```
Comment (teor2345) [inline zebra-network/src/peer/handshake.rs]:
```suggestion
```

File: zebra-network/src/peer/handshake.rs (hunk 4 above)
Comment (teor2345) [reply zebra-network/src/peer/handshake.rs:576]: I think the extra blank comment line improves readability - check the split diff view.

File: zebra-network/src/peer_set/initialize.rs (hunk 5 above)
Comment (teor2345) [reply zebra-network/src/peer_set/initialize.rs]:
```suggestion
            a = crawl_timer.next() => a.expect("timers never terminate"),
```

**Comment by teor2345** [comment]
The `pull-request (zealous-zebra)` failure is:
> failed to load source for dependency `redjubjub`

which should be fixed by a rebase/merge.

File: zebra-network/src/peer/handshake.rs (hunk 3 above)
Comment (oxarbitrage) [reply zebra-network/src/peer/handshake.rs]: Thanks for the clarification.

**Review by oxarbitrage — DISMISSED** [review]
Changes addressed.

**Comment by teor2345** [comment]
Squashed fixup commits to make the review easier.
Rebased to fix build errors.

**Review by oxarbitrage — APPROVED** [review]

File: zebra-network/src/peer/handshake.rs [hunk 8]
```diff
@@ -260,11 +270,10 @@ where
             };
 
             debug!(?version, "sending initial version message");
-            stream.send(version).await?;
+            timeout(constants::REQUEST_TIMEOUT, stream.send(version)).await??;
```
Comment (teor2345) [inline zebra-network/src/peer/handshake.rs:273]: Change all timeouts in handshake.rs to `HANDSHAKE_TIMEOUT`

File: zebra-network/src/peer/handshake.rs [hunk 9]
```diff
@@ -211,6 +217,10 @@ where
         let fut = async move {
             debug!("connecting to remote peer");
 
+            // CORRECTNESS
+            //
+            // As a defence-in-depth against hangs, every send or next on stream
+            // should be wrapped in a timeout.
             let mut stream = Framed::new(
```
Comment (teor2345) [inline zebra-network/src/peer/handshake.rs:224]: Open follow-up for wrapping a sink/stream in a timeout

File: zebra-network/src/peer/handshake.rs [hunk 10]
```diff
@@ -376,22 +384,44 @@ where
                 future::ready(Ok(msg))
```
Comment (teor2345) [inline zebra-network/src/peer/handshake.rs:384]: Open a follow-up for changing the codec without impacting any frames that are still being processed

File: zebra-network/src/peer/handshake.rs [hunk 11]
```diff
@@ -474,19 +522,28 @@ where
...
-                                            Ok(()) => {}
+                                        // TODO: also wait on the shutdown_rx here
+                                        match timeout(
+                                            constants::HEARTBEAT_INTERVAL,
+                                            server_tx.flush(),
+                                        )
+                                        .await
+                                        {
+                                            Ok(Ok(())) => {
+                                            }
```
Comment (teor2345) [inline zebra-network/src/peer/handshake.rs:535]: rustfmt should have fixed this

File: zebra-network/src/peer/handshake.rs [hunk 12]
```diff
@@ -474,19 +522,28 @@ where
                                     span: tracing::Span::current(),
                                 }) {
                                     Ok(()) => {
-                                        match server_tx.flush().await {
-                                            Ok(()) => {}
+                                        // TODO: also wait on the shutdown_rx here
+                                        match timeout(
```
Comment (teor2345) [inline zebra-network/src/peer/handshake.rs:528]: turn timeout match into a generic function that logs traces and returns a BoxErr result using Result::flatten?

File: zebra-network/src/peer/handshake.rs [hunk 13]
```diff
@@ -514,17 +571,46 @@ where
...
+                            // We can't get the client request for this failure,
+                            // so we can't send an error back on `tx`. So
+                            // we just update the address book with a failure.
+                            let _ = timestamp_collector
+                                .send(MetaAddr::new_errored(
+                                    &addr,
+                                    &remote_services,
+                                ))
+                                .await;
+                            return;
```
Comment (teor2345) [inline zebra-network/src/peer/handshake.rs:615]: turn into function which we call then return, so that we don't wait for a response to a failed request

File: zebra-network/src/constants.rs [hunk 14]
```diff
@@ -49,6 +49,14 @@ pub const LIVE_PEER_DURATION: Duration = Duration::from_secs(60 + 20 + 20 + 20);
 /// connected peer.
 pub const HEARTBEAT_INTERVAL: Duration = Duration::from_secs(60);
 
+/// The number of GetAddr requests sent when crawling for new peers.
+///
+/// ## SECURITY
+///
+/// The fanout should be greater than 1, to ensure that Zebra's address book is
+/// not dominated by a single peer.
+pub const GET_ADDR_FANOUT: usize = 2;
```
Comment (teor2345) [inline zebra-network/src/constants.rs:58]: Change to 3 so no peer has a majority

Comment (teor2345) [reply zebra-network/src/constants.rs:58]: Add a TODO note for the ticket that restricts the number of peers we take from each response.

File: zebra-network/src/peer_set/candidate_set.rs [hunk 15]
```diff
@@ -214,6 +242,16 @@ where
...
+        //
+        // In this critical section, we hold the address mutex.
+        //
+        // To avoid deadlocks, the critical section:
+        // - must not acquire any other locks
+        // - must not await any futures
+        //
+        // To avoid hangs, any computation in the critical section should
+        // be kept to a minimum.
         let reconnect = {
```
Comment (teor2345) [inline zebra-network/src/peer_set/candidate_set.rs:255]: Add to async RFC as an example of how rust stopped us holding the lock over the await

File: zebra-network/src/peer_set/initialize.rs [hunk 16]
```diff
@@ -315,74 +338,78 @@ where
...
+            a = demand_rx.next() => a.expect("demand_rx never fails, because we hold demand_tx"),
```
Comment (teor2345) [inline zebra-network/src/peer_set/initialize.rs]: Rename `a` to represent what is actually being returned

File: zebra-network/src/peer_set/initialize.rs [hunk 17]
```diff
@@ -315,74 +338,78 @@ where
...
-                                candidate
-                            })
-                            .boxed(),
-                    );
+                                HandshakeFailed {
+                                    failed_addr: candidate,
+                                }
+                            }
+                        },
+                    )));
```
Comment (teor2345) [inline zebra-network/src/peer_set/initialize.rs]: Turn this into a function.

Comment (teor2345) [reply zebra-network/src/peer_set/initialize.rs]: Do a `From` impl

File: zebra-network/src/peer_set/initialize.rs [hunk 18]
```diff
@@ -341,53 +345,65 @@ where
...
+                // the connector is always ready, so this can't hang
+                connector.ready_and().await?;
+                // the handshake has timeouts, so it shouldn't hang
+                handshakes.push(Box::pin(connector.call(candidate.addr).map(
+                    move |res| match res {
+                        Ok(peer_set_change) => HandshakeConnected { peer_set_change },
+                        Err(e) => {
+                            debug!(?candidate.addr, ?e, "failed to connect to candidate");
+                            HandshakeFailed {
+                                failed_addr: candidate,
```
Comment (teor2345) [inline zebra-network/src/peer_set/initialize.rs]: Make a From impl

File: zebra-network/src/peer_set/initialize.rs [hunk 19]
```diff
@@ -370,22 +378,40 @@ where
...
+                            Err(e) => {
+                                debug!(?candidate.addr, ?e, "failed to connect to candidate");
+                                HandshakeFailed {
+                                    failed_addr: candidate,
+                                }
                             }
+                        })
+                        .await
+                })
+                .map(move |res| match res {
```
Comment (teor2345) [inline zebra-network/src/peer_set/initialize.rs]: Make a From impl

File: zebra-network/src/peer_set/initialize.rs [hunk 20]
```diff
@@ -370,22 +378,40 @@ where
...
+                    debug!(?candidate.addr, "attempting outbound connection in response to demand");
+                    // the connector is always ready, so this can't hang
+                    let hs_connector = hs_connector
+                        .ready_and()
+                        .await
+                        .expect("connector never errors");
+                    // the handshake has timeouts, so it shouldn't hang
+                    hs_connector
+                        .call(candidate.addr)
+                        .map(move |res| match res {
```
Comment (teor2345) [inline zebra-network/src/peer_set/initialize.rs]: Make a From impl

File: zebra-network/src/peer_set/initialize.rs [hunk 21]
```diff
@@ -455,3 +431,44 @@ where
...
+    debug!(?candidate.addr, "attempting outbound connection in response to demand");
+
+    // the connector is always ready, so this can't hang
+    let connector = connector.ready_and().await.expect("connector never errors");
+
+    // the handshake has timeouts, so it shouldn't hang
+    connector
+        .call(candidate.addr)
+        .map(move |res| match res {
+            Ok(peer_set_change) => HandshakeConnected { peer_set_change },
```
Comment (teor2345) [inline zebra-network/src/peer_set/initialize.rs:465]: Make a From impl

File: zebra-network/src/peer/connection.rs [hunk 22]
```diff
@@ -372,6 +372,22 @@ where
...
+                    // uninterrupted series of messages. But this is unlikely in
+                    // practice, due to network delays.
+                    //
+                    // If both futures are ready, there's no particular reason
+                    // to prefer one over the other.
+                    //
+                    // TODO: use `futures::select!`, which chooses a ready future
+                    //       at random, avoiding starvation
+                    //       (To use `select!`, we'll need to map the different
+                    //       results to a new enum types.)
```
Comment (teor2345) [inline zebra-network/src/peer/connection.rs:390]: Open a follow-up ticket to use typed enums

File: zebra-network/src/peer/connection.rs [hunk 23]
```diff
@@ -404,14 +420,21 @@ where
...
-                    let cancel = future::select(timer_ref, tx.cancellation());
-                    match future::select(peer_rx.next(), cancel)
+                    // CORRECTNESS
+                    //
+                    // Currently, select prefers the first future if multiple
+                    // futures are ready.
+                    //
+                    // If multiple futures are ready, we want the cancellation
+                    // to take priority, then the timeout, then peer responses.
+                    let cancel = future::select(tx.cancellation(), timer_ref);
```
Comment (teor2345) [inline zebra-network/src/peer/connection.rs:430]: Open a follow-up task to use typed enums rather than Either

File: zebra-network/src/peer/handshake.rs [hunk 24]
```diff
@@ -504,12 +504,17 @@ where
...
-                            Either::Left(_) => {
+                        // CORRECTNESS
+                        //
+                        // Currently, select prefers the first future if multiple
+                        // futures are ready.
+                        //
+                        // Starvation is impossible here, because interval has a
+                        // slow rate, and shutdown is a oneshot. If both futures
+                        // are ready, we want the shutdown to take priority over
+                        // sending a useless heartbeat.
```
Comment (teor2345) [inline zebra-network/src/peer/handshake.rs:515]: Open a follow-up ticket for enums

File: zebra-network/src/peer/handshake.rs (hunk 10 above)
Comment (teor2345) [reply zebra-network/src/peer/handshake.rs:384]: #1993

File: zebra-network/src/peer/handshake.rs (hunk 9 above)
Comment (teor2345) [reply zebra-network/src/peer/handshake.rs:224]: #1994

File: zebra-network/src/peer_set/candidate_set.rs (hunk 15 above)
Comment (teor2345) [reply zebra-network/src/peer_set/candidate_set.rs:255]: Added TODO to RFC ticket

File: zebra-network/src/peer/connection.rs (hunk 22 above)
Comment (teor2345) [reply zebra-network/src/peer/connection.rs:390]: #1783

File: zebra-network/src/peer/connection.rs (hunk 23 above)
Comment (teor2345) [reply zebra-network/src/peer/connection.rs:430]: #1783

File: zebra-network/src/peer/handshake.rs (hunk 24 above)
Comment (teor2345) [reply zebra-network/src/peer/handshake.rs:515]: #1783

File: zebra-network/src/peer_set/initialize.rs (hunk 21 above)
Comment (teor2345) [reply zebra-network/src/peer_set/initialize.rs:465]: https://github.com/ZcashFoundation/zebra/pull/2003

File: zebra-network/src/constants.rs (hunk 14 above)
Comment (teor2345) [reply zebra-network/src/constants.rs:58]: #2004

File: zebra-network/src/peer/handshake.rs (hunk 8 above)
Comment (teor2345) [reply zebra-network/src/peer/handshake.rs:273]: #2008

File: zebra-network/src/peer/handshake.rs (hunk 12 above)
Comment (teor2345) [reply zebra-network/src/peer/handshake.rs:528]: Part of #2009

File: zebra-network/src/peer/handshake.rs (hunk 13 above)
Comment (teor2345) [reply zebra-network/src/peer/handshake.rs:615]: Part of #2009
