### PR TITLE
fix(rpc): Use a structure for parameters of getaddresstxids

### LINKED ISSUE #4216: getaddresstxids RPC should have a single struct argument, not multiple arguments
## Motivation

When I run this command against `zcashd` it works:
```sh
zcash-cli getaddresstxids '{"addresses": ["t3LmX1cxWPPPqL4TZHx42HU3U5ghbFjRiif"], "start": 1000, "end": 2000}'
```

But when I run it against Zebra, it fails:
```sh
zcash-cli -rpcport="$ZEBRAD_RPC_PORT" '{"addresses": ["t3LmX1cxWPPPqL4TZHx42HU3U5ghbFjRiif"], "start": 1000, "end": 2000}'
```

With this error:
```
error code: -32602
error message:
Invalid params: invalid length 1, expected a tuple of size 3.
```

This check needs the fix in PR #4215.

### Designs

It looks like Zebra should take a single struct argument with named fields, rather than multiple named arguments.

This appears to be the only `lightwalletd` request with multiple named fields:
https://github.com/zcash/lightwalletd/blob/bdaac63f3ee0dbef62bde04f6817a9f90d483b00/common/common.go#L97

### PR DESCRIPTION
**Pull request by oxarbitrage**
## Motivation

We need to fix the parameters of `getaddresstxids` or lightwalletd calls will fail. Fix https://github.com/ZcashFoundation/zebra/issues/4216

## Solution

Use a struct for parameters. Based on so we can also apply a test: https://github.com/ZcashFoundation/zebra/pull/4253

Also this PR simplifies the env variables checks needed to run `lightwalletd_wallet_grpc_tests`

## Review

Anyone can review but probably will be easier if it is done by the same person doing the review of https://github.com/ZcashFoundation/zebra/pull/4253

### Reviewer Checklist

  - [ ] Code implements Specs and Designs
  - [ ] Tests for Expected Behaviour
  - [ ] Tests for Errors

### CODE REVIEW

File: zebrad/tests/common/lightwalletd.rs [hunk 1]
```diff
@@ -306,7 +306,17 @@ impl LightwalletdTestType {
 
     /// Returns the lightwalletd state path for this test, if set.
     pub fn lightwalletd_state_path(&self) -> Option<PathBuf> {
-        env::var_os(LIGHTWALLETD_DATA_DIR_VAR).map(Into::into)
+        match env::var_os(LIGHTWALLETD_DATA_DIR_VAR) {
+            Some(path) => Some(path.into()),
+            None => {
+                tracing::info!(
+                    "skipped {self:?} lightwalletd test, \
```
Comment (teor2345) [inline zebrad/tests/common/lightwalletd.rs]: Blocker: These logs are really confusing, because they don't contain the test name.

Can we also pass a string containing the test name, and log it in the skip log message?

We also call this method from the 3 `lightwalletd_integration_test` tests, so we need to make some changes there as well.

**Review by teor2345 — COMMENTED** [review]
This is good, but I just want to fix up some logging.

Have you tested it with `zcash-rpc-diff`, or are you happy with the lightwalletd gRPC tests?

File: zebrad/tests/common/lightwalletd.rs (hunk 1 above)
Comment (oxarbitrage) [reply zebrad/tests/common/lightwalletd.rs]: You are right, i made some improvements in https://github.com/ZcashFoundation/zebra/pull/4264/commits/aaecc61709f720a3bb0f8c3f4460d97c72923590

File: zebrad/tests/common/lightwalletd.rs [hunk 2]
```diff
@@ -266,12 +266,12 @@ impl LightwalletdTestType {
...
 
     /// Returns the Zebra state path for this test, if set.
-    pub fn zebrad_state_path(&self) -> Option<PathBuf> {
+    pub fn zebrad_state_path(&self, test_name: String) -> Option<PathBuf> {
         match env::var_os(ZEBRA_CACHED_STATE_DIR_VAR) {
             Some(path) => Some(path.into()),
             None => {
                 tracing::info!(
-                    "skipped {self:?} lightwalletd test, \
+                    "skipped {test_name:?} lightwalletd test, \
```
Comment (teor2345) [inline zebrad/tests/common/lightwalletd.rs]: In the `lightwalletd_integration_test`, we run all 3 test types, so we need to log the type here too:

```suggestion
                    "skipped {test_name:?} {self:?} lightwalletd test, \
```

File: zebrad/tests/common/lightwalletd.rs [hunk 3]
```diff
@@ -305,8 +305,18 @@ impl LightwalletdTestType {
...
 
     /// Returns the lightwalletd state path for this test, if set.
-    pub fn lightwalletd_state_path(&self) -> Option<PathBuf> {
-        env::var_os(LIGHTWALLETD_DATA_DIR_VAR).map(Into::into)
+    pub fn lightwalletd_state_path(&self, test_name: String) -> Option<PathBuf> {
+        match env::var_os(LIGHTWALLETD_DATA_DIR_VAR) {
+            Some(path) => Some(path.into()),
+            None => {
+                tracing::info!(
+                    "skipped {test_name:?} lightwalletd test, \
```
Comment (teor2345) [inline zebrad/tests/common/lightwalletd.rs]: Same here:
```suggestion
                    "skipped {test_name:?} {self:?} lightwalletd test, \
```

**Review by teor2345 — COMMENTED** [review]
Looks good, just a minor logging tweak

**Review by teor2345 — APPROVED** [review]
Thanks!
