### PR TITLE
tests(scanner): Move zebra scanner tests to binary

### LINKED ISSUE #8585: Testing the new `zebra-scanner` binary
We have some good test coverage for our blockchain scanner and most of them will keep working after we introduce a new binary (https://github.com/ZcashFoundation/zebra/issues/8581) however tests that relies on the scanner being started by zebrad will fail. We need to replace these by specific tests in the new binary scope. We may also want to add more tests and add the build of this binary into the CI.

More details to be added.

Note: https://github.com/ZcashFoundation/zebra/pull/8631 should be reverted if/when the `scan-start-where-left-test` test is restored.

### LINKED ISSUE #8593: change(scan): Move integration tests for scanner out of `zebrad`
The `zebrad` crate contains a scanner integration test: https://github.com/zcashfoundation/zebra/blob/ce875f512b537d1404b64a8860815b146fe2096e/zebrad/tests/acceptance.rs#L3107.

### Suggested Solution

- Move the test to the new binary once we have it.

## Follow-ups

#8585

### PR DESCRIPTION
**Pull request by oxarbitrage**
## Motivation

We moved the scanner into a new binary in https://github.com/ZcashFoundation/zebra/pull/8608 . We also removed the scanner functionality from zebrad and commented out tests in https://github.com/ZcashFoundation/zebra/pull/8594

Now is time to get the tests we commented out back, in the context of the new binary.

Close https://github.com/ZcashFoundation/zebra/issues/8593

Part of https://github.com/ZcashFoundation/zebra/issues/8585

## Solution

Add tests to zebra scanner binary.

### Follow-up Work

- I think we can add a test close to the tip for `TrustedChainSync` functionality introduced in https://github.com/ZcashFoundation/zebra/pull/8596 to finish with the scanner tests coverage and complete #8585 

### PR Author's Checklist

- [ ] The PR name will make sense to users.
- [ ] The PR provides a CHANGELOG summary.
- [ ] The solution is tested.
- [ ] The documentation is up to date.
- [ ] The PR has a priority label.

### PR Reviewer's Checklist

- [ ] The PR Author's checklist is complete.
- [ ] The PR resolves the issue.

### CODE REVIEW

**Comment by mpguerra** [comment]
Does this PR also cover #8593 ?

**Comment by oxarbitrage** [comment]
> Does this PR also cover #8593 ?

Yes, this PR will close that issue. I added that to the description. I am rebasing now.

File: zebra-scan/tests/scanner.rs [hunk 1]
```diff
@@ -0,0 +1,257 @@
...
+///
+/// export ZEBRA_CACHED_STATE_DIR="/path/to/zebra/state"
+/// cargo test scan_start_where_left -- --ignored --nocapture
+///
+/// The test will run zebrad with a key to scan, scan the first few blocks after sapling and then stops.
+/// Then it will restart zebrad and check that it resumes scanning where it was left.
+#[ignore]
+#[tokio::test]
+#[cfg(not(target_os = "windows"))]
+async fn scan_start_where_left() -> Result<()> {
```
Comment (arya2) [inline zebra-scan/tests/scanner.rs:136]: We should uncomment the `scan-start-where-left-test` CI job too so this runs for every PR again.

File: zebra-scan/tests/scanner.rs [hunk 2]
```diff
@@ -0,0 +1,257 @@
...
+///
+/// To run it locally, one way is:
+/// ```
+/// export CARGO_BIN_EXE_zebrad="/path/to/zebrad_binary"
+/// cargo test scan_binary_starts -- --ignored --nocapture
+/// ```
+#[ignore]
+#[tokio::test]
+#[cfg(not(target_os = "windows"))]
+async fn scan_binary_starts() -> Result<()> {
```
Comment (arya2) [inline zebra-scan/tests/scanner.rs:45]: This wasn't ignored before, but now it needs the `CARGO_BIN_EXE_zebrad` env var to be defined outside the build process. If we want to avoid defining the env var to run this in CI as a unit test, we could move ~most of the code in the scanner binary to the `init` module, add a copy of the binary in the `zebrad` crate, and move these tests back to the zebrad acceptance tests.~ the scanner results reader from `zebra-utils` to `zebra-scan` and add a `zebrad` binary in `zebra-scan`.

Update: Fixed in https://github.com/ZcashFoundation/zebra/pull/8659/commits/f8bfd9dff1fd61e1d3c6d68769fa2ca3269660af.

File: zebra-scan/tests/scanner.rs [hunk 3]
```diff
@@ -0,0 +1,257 @@
...
+/// directory for `zebra-scanner`.
+pub trait ZebradTestDirExt
+where
+    Self: AsRef<Path> + Sized,
+{
+    // Zebra-scanner methods
+
+    /// Spawn `zebra-scanner` (`zebrad` flag = `false`) or `zebrad` (`zebrad` flag = `true`)
+    /// with `args` as a child process in this test directory.
+    fn spawn_child(self, args: Arguments, zebrad: bool) -> Result<TestChild<Self>>;
```
Comment (arya2) [inline zebra-scan/tests/scanner.rs]: Optional: Could we rename this trait and add `spawn_zebrad_child()`/`spawn_scanner_child()` methods?

```suggestion
pub trait ScannerTestDirExt
where
    Self: AsRef<Path> + Sized,
{
    // Zebra-scanner methods

    /// Spawn `zebra-scanner` with `args` as a child process in this test directory.
    fn spawn_scanner_child(self, args: Arguments) -> Result<TestChild<Self>>;
```

Update: Renamed in https://github.com/ZcashFoundation/zebra/pull/8659/commits/d70d6735d401229e75b24b9c06b971d668b7f5ba.

**Review by arya2 — COMMENTED** [review]
This looks good!

We should uncomment the `scan-start-where-left-test` CI job in this PR too (it was commented out [here](https://github.com/ZcashFoundation/zebra/pull/8594/files#diff-88f0a9cbc54ea70f51d3d7163ed664a292b5d5e5b3bbcf79d6bda582e46f9638R519))

I'm not sure how reliable it is to define a `CARGO_BIN_EXE_zebrad` env var outside the build process. If it's not very reliable, I'd suggest ~adding a `scanner` binary in `zebrad` as well and moving the tests here that rely on the `zebrad` binary back to the zebrad acceptance tests (it's nicer to have these tests here but it seems much more difficult to add a `zebrad` binary in `zebra-scan`)~.

Update: It seems very easy to add a `zebrad` binary to `zebra-scan`, I would suggest doing that instead if it's valuable to have the `CARGO_BIN_EXE_zebrad` environment variable .

File: zebra-scan/tests/scanner.rs (hunk 1 above)
Comment (arya2) [reply zebra-scan/tests/scanner.rs:136]: It wasn't running this test in the `Test All` job before because it doesn't include any optional features like `shielded-scan`, we could avoid running this there with an environment variable, a feature flag, or if there aren't any ignored tests that should be running in the `Test All` job, we could remove the `--include-ignored` flag in `entrypoint.sh` for `RUN_ALL_TESTS`.

Update: The CI job still needs to be restored but this comment's been addressed in https://github.com/ZcashFoundation/zebra/pull/8659/commits/314c4afedcab1df24dd4172668b827199f466fa3
Update: The CI job's been restored in https://github.com/ZcashFoundation/zebra/pull/8659/commits/25df03f9fd8f1f03243c72b07ba336d99cd84983.

**Review by arya2 — COMMENTED** [review]
@oxarbitrage The `shielded-scan` feature was partially removed from `zebrad`, but there are still some uses of it causing test failures.

**Comment by oxarbitrage** [comment]
> @oxarbitrage The `shielded-scan` feature was partially removed from `zebrad`, but there are still some uses of it causing test failures.

Ok, ill check that out. Thanks.

**Comment by oxarbitrage** [comment]
Update: Need more work related to moving this test https://github.com/ZcashFoundation/zebra/blob/main/zebrad/tests/common/shielded_scan/scan_task_commands.rs out of zebrad. I am still working on it, changing the PR to draft until that is sorted.

File: zebra-scan/tests/scan_task_commands.rs [hunk 4]
```diff
@@ -5,12 +5,14 @@
 //!
 //! export ZEBRA_CACHED_STATE_DIR="/path/to/zebra/state"
 //! cargo test scan_task_commands --features="shielded-scan" -- --ignored --nocapture
+#![allow(dead_code)]
```
Comment (arya2) [inline zebra-scan/tests/scan_task_commands.rs:8]: It's strange that this is necessary, since all of the code here is used, but it seems fine for now.

File: zebrad/tests/acceptance.rs [hunk 5]
```diff
@@ -120,14 +120,6 @@
...
 //! Please refer to the documentation of each test for more information.
 //!
-//! ## Shielded scanning tests
-//!
-//! Example of how to run the scan_task_commands test:
-//!
-//! ```console
-//! ZEBRA_CACHED_STATE_DIR=/path/to/zebra/state cargo test scan_task_commands --features shielded-scan --release -- --ignored --nocapture
-//! ```
-//!
```
Comment (arya2) [inline zebrad/tests/acceptance.rs:130]: Optional/Nitpick: Could we add this to the module docs for the `scanner` tests?

Update: On second though, it seems sufficient that's it's included in the docs for the particular test.

**Review by arya2 — APPROVED** [review]
This looks good!
