### PR TITLE
7. feat(state): add a read-only state service stub

### LINKED ISSUE #3745: Zebra takes too much time to respond to `getblock` RPC method.
## Description

During https://github.com/ZcashFoundation/zebra/pull/3707 manual testing it was found that the `get_block` method works when called just at when the port is open but it hangs for a while as zebra sync make progress.

### Steps to Reproduce

After https://github.com/ZcashFoundation/zebra/pull/3707 is merged into main or from the https://github.com/ZcashFoundation/zebra/pull/3707 branch:

- create a config to open rpc port.
- start zebra in 1 window.
- make calls from another window, after the port is open you will see:

```
$ curl -X POST -H "Content-Type: application/json" -d '{"jsonrpc": "2.0", "method": "getblock", "params": [4, 0], "id":123 }' 127.0.0.1:8232 | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3351  100  3282  100    69  1602k  34500 --:--:-- --:--:-- --:--:-- 1636k
{
  "jsonrpc": "2.0",
  "result": {
    "data": "040000007fc6ea65cae94cd84309ed9e0f35a67087cd4bfcf3c95ad6978ebbe5c4f606006e44e2f6865c547769a8ce02e148c83f3f15bfd8afd31e4c05318816b0b91b780000000000000000000000000000000000000000000000000000000000000000d07a1358ffff071f7534e5d60c000000000000000000000000000000000000000000000000000000fd4005008d16b18e21dff532f88087062f3919bee13ca6e204b89baa18973860fdaad24710b3ae6cd68297296c205f997e678d134bfebb3bfc4d61fdd746c45a8a3933f4ad6ca895f3e540b95978b3d1e4530b5059068706b476d21115a054da1ba3d6fa607f19caaaff109008d50ac5c145a9bcd71cb2999aca9144ae2d1d8a981f1f66ee54ef445dc25286eb40d7549a5261f808a133ae1e7dd86b7a21b57b64b0e8d7f38f265cfd881c0808c42029deaa632ef700ee483bdc4e7c95dac5a12235aa5902f470fdb0b5d640a259538b05af5aadaf1cedb48ed1691f3fbc51935728cb28566bb71eca9f1d650355c28ecfc97805820560771b34e6a0ec7c871641ebf574ef5207aaf008042ffa9eef45febf87bb447ee6fa64a726e965dea67491ee0a5a46a83ead4818282be5b72820738a5dd469cd38d8da252cb3ba621880653121062bb5cfbbd648ccd7b6bd9ca43e356006b64b7adf0833bc6c91228e95b0a68540517ccae80ed3eb9346474b8d1780017e85ab11a1f02dbfe8870ba7f9a0b80942a4d785b2661277f730bd2ff8ffb70c4dbdfb3c933b8d3fc0c20e634eae792f1d70c218095570f454c88b0aae3af5b5a1b1fcc9f18f1c29ef2379c560787545a5d404174582fd6d5a57e93964d409aa6bb60586e6a09cace3b2bc38c4e907bbd1da7a4a0445f9c9e0d80d57e4f5889749c89def7f98f6e30811587906d351a3835da235fd5ec8bd77d39c323710f96424954a2160ec2f82ba02620466a901d92b4732ace45ca3d9f86f742ff33ea31d5f4919b89a8504534d6b5199faa1a7ec2db8e61df3ee82dcf377e1ee099727c8654b9ce9c83e93f3b1de5eea0c6d111bc3350f7dfb989c20fbe578461d57d24a92254adbbc390e061fd028c82daf62cfe727bde25046704798bf3e2e87dd87c712185f805d09cf797060be7cb8f9ca6400b4bc5c8256c8ed5b0fd04139d9c5301ae7fd37ea062805bd7fe97b97589705dcec54e2a6c2d15a46e602492382f18afe2d63266229909593a6e9f5ba155f4b4693b563e85fd1abd0e6f81d3f5dc1c9a3fd9b44038d3669428a495ad8a60223876c6b51e6441ce4351a3e3a5657e53065e6c742e2715bb7eb81eabee52009d9f1aa5e5b1c8edf9233f87fe68081d5acbebf1759045cf0e5a95f0953077864dc57d656309574412a0209e097d2f1880fc1de0054c326a0b915a0141fbc03d0e2252cc3c1293cdd6639b86d33862290f8f31702d71c3a3bd61a56d108071c49ee1a5a627f167c4c2d2cfea51428b147e769a50a33adfb8eba3757f0e20646ff72b4115dc1b911a1c7b268f25cbd31a859dc0b51ac67c7f5cecbdb1e2220f7b06d852e2d956d3416067f34305d8c3f1c9f11c77163ec95f23b3f737232836272de1c6fedc76424a878f833e94c498eba5e0190d444b7c19fb4d466c0be3dc804108c4ef1f71910155504301eff1d9b4f5bf6b6e532ab41bdfa30250f05708718cf928681b631949f9fd5bba44cbf750812ab9aa409e19b6f62e911a506effbfd95cbb5699509a9ca7c6b457633d0f19205b5fe05e19f9cf8c71817ec98e4053a7833e3e604e97bea7b62bcdbfccac928d63c1944dd3f8f17d438f0f3d4dde6f5bf9e82d24cf3062c911702af8a8875260733bb369ef5f828370294a32f300d7ad8cf5f4467d9cdd83e48df7806ef1d1cf1a3f393c4f50257d2de8b9a117cec381db8f70519d6a52dd745d0bb4357b562e7339291263ae9d715e733187923689dcae662e96fc59142070336f4b61925f7b3bea72b23a534b458f1af6ad15bc87a5fbb2bcfa1dbef1d4831cfd3d526467fd92228ab16a5a927084c3754e907ab9d5e66d567cb8777bcd53f1b272c7deda98d27a1e16255174b69bcd14e017c38e8620101000000010000000000000000000000000000000000000000000000000000000000000000ffffffff025400ffffffff02400d0300000000002321027a46eb513588b01b37ea24303f4b628afd12cc20df789fede0921e43cad3e875ac50c300000000000017a9147d46a730d31f97b1930d3368a967c309bd4d136a8700000000"
  },
  "id": 123
}
$ 
```

Please note spent time above is 0.

A bit later the same call results in a hang of more than 1 minute to get a response:

```
$ curl -X POST -H "Content-Type: application/json" -d '{"jsonrpc": "2.0", "method": "getblock", "params": [4, 0], "id":123 }' 127.0.0.1:8232 | jq
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3351  100  3282    0    69     42      0  0:01:18  0:01:18 --:--:--   871
{
  "jsonrpc": "2.0",
  "result": {
    "data": "040000007fc6ea65cae94cd84309ed9e0f35a67087cd4bfcf3c95ad6978ebbe5c4f606006e44e2f6865c547769a8ce02e148c83f3f15bfd8afd31e4c05318816b0b91b780000000000000000000000000000000000000000000000000000000000000000d07a1358ffff071f7534e5d60c000000000000000000000000000000000000000000000000000000fd4005008d16b18e21dff532f88087062f3919bee13ca6e204b89baa18973860fdaad24710b3ae6cd68297296c205f997e678d134bfebb3bfc4d61fdd746c45a8a3933f4ad6ca895f3e540b95978b3d1e4530b5059068706b476d21115a054da1ba3d6fa607f19caaaff109008d50ac5c145a9bcd71cb2999aca9144ae2d1d8a981f1f66ee54ef445dc25286eb40d7549a5261f808a133ae1e7dd86b7a21b57b64b0e8d7f38f265cfd881c0808c42029deaa632ef700ee483bdc4e7c95dac5a12235aa5902f470fdb0b5d640a259538b05af5aadaf1cedb48ed1691f3fbc51935728cb28566bb71eca9f1d650355c28ecfc97805820560771b34e6a0ec7c871641ebf574ef5207aaf008042ffa9eef45febf87bb447ee6fa64a726e965dea67491ee0a5a46a83ead4818282be5b72820738a5dd469cd38d8da252cb3ba621880653121062bb5cfbbd648ccd7b6bd9ca43e356006b64b7adf0833bc6c91228e95b0a68540517ccae80ed3eb9346474b8d1780017e85ab11a1f02dbfe8870ba7f9a0b80942a4d785b2661277f730bd2ff8ffb70c4dbdfb3c933b8d3fc0c20e634eae792f1d70c218095570f454c88b0aae3af5b5a1b1fcc9f18f1c29ef2379c560787545a5d404174582fd6d5a57e93964d409aa6bb60586e6a09cace3b2bc38c4e907bbd1da7a4a0445f9c9e0d80d57e4f5889749c89def7f98f6e30811587906d351a3835da235fd5ec8bd77d39c323710f96424954a2160ec2f82ba02620466a901d92b4732ace45ca3d9f86f742ff33ea31d5f4919b89a8504534d6b5199faa1a7ec2db8e61df3ee82dcf377e1ee099727c8654b9ce9c83e93f3b1de5eea0c6d111bc3350f7dfb989c20fbe578461d57d24a92254adbbc390e061fd028c82daf62cfe727bde25046704798bf3e2e87dd87c712185f805d09cf797060be7cb8f9ca6400b4bc5c8256c8ed5b0fd04139d9c5301ae7fd37ea062805bd7fe97b97589705dcec54e2a6c2d15a46e602492382f18afe2d63266229909593a6e9f5ba155f4b4693b563e85fd1abd0e6f81d3f5dc1c9a3fd9b44038d3669428a495ad8a60223876c6b51e6441ce4351a3e3a5657e53065e6c742e2715bb7eb81eabee52009d9f1aa5e5b1c8edf9233f87fe68081d5acbebf1759045cf0e5a95f0953077864dc57d656309574412a0209e097d2f1880fc1de0054c326a0b915a0141fbc03d0e2252cc3c1293cdd6639b86d33862290f8f31702d71c3a3bd61a56d108071c49ee1a5a627f167c4c2d2cfea51428b147e769a50a33adfb8eba3757f0e20646ff72b4115dc1b911a1c7b268f25cbd31a859dc0b51ac67c7f5cecbdb1e2220f7b06d852e2d956d3416067f34305d8c3f1c9f11c77163ec95f23b3f737232836272de1c6fedc76424a878f833e94c498eba5e0190d444b7c19fb4d466c0be3dc804108c4ef1f71910155504301eff1d9b4f5bf6b6e532ab41bdfa30250f05708718cf928681b631949f9fd5bba44cbf750812ab9aa409e19b6f62e911a506effbfd95cbb5699509a9ca7c6b457633d0f19205b5fe05e19f9cf8c71817ec98e4053a7833e3e604e97bea7b62bcdbfccac928d63c1944dd3f8f17d438f0f3d4dde6f5bf9e82d24cf3062c911702af8a8875260733bb369ef5f828370294a32f300d7ad8cf5f4467d9cdd83e48df7806ef1d1cf1a3f393c4f50257d2de8b9a117cec381db8f70519d6a52dd745d0bb4357b562e7339291263ae9d715e733187923689dcae662e96fc59142070336f4b61925f7b3bea72b23a534b458f1af6ad15bc87a5fbb2bcfa1dbef1d4831cfd3d526467fd92228ab16a5a927084c3754e907ab9d5e66d567cb8777bcd53f1b272c7deda98d27a1e16255174b69bcd14e017c38e8620101000000010000000000000000000000000000000000000000000000000000000000000000ffffffff025400ffffffff02400d0300000000002321027a46eb513588b01b37ea24303f4b628afd12cc20df789fede0921e43cad3e875ac50c300000000000017a9147d46a730d31f97b1930d3368a967c309bd4d136a8700000000"
  },
  "id": 123
}
$ 
```

Other call can take 30 seconds, so it seems it depends on what zebra is doing but more than 1 minute seems to be normal.

### Expected Behaviour

Zebra should respond faster to `getblock` calls.

### Actual Behaviour

Takes to much time to get response.

### Operating System

Linux.

### PR DESCRIPTION
**Pull request by teor2345**
## Motivation

In #3745, we want to add a read-only, cloneable state service, with no buffer or queue.

### Designs

Share access to the best non-finalized chain and the finalized state.

## Solution

- Create a ReadStateService struct
    - Add a stub service implementation
    - Add support methods in the finalized and non-finalized state
- Make RPC accept a buffered state or a read-only state
- Doc comment updates

## Review

There is a lot of code changed in this PR series, it would be good to get it merged soon to avoid conflicts.

This doesn't do anything yet, the next few PRs will implement the read-only state requests, and add tests.

### Reviewer Checklist

  - [ ] Code implements Specs and Designs

## Follow Up Work

- implement block requests
- use in the RPC implementation
- test performance
- add tests

### CODE REVIEW

File: zebrad/src/commands/copy_state.rs [hunk 1]
```diff
@@ -123,8 +128,12 @@ impl CopyStateCmd {
         );
 
         let target_start_time = Instant::now();
-        let (mut target_state, _target_latest_chain_tip, _target_chain_tip_change) =
-            new_zs::init(target_config.clone(), network);
+        let (
```
Comment (teor2345) [inline zebrad/src/commands/copy_state.rs:134]:
```suggestion
        // TODO: call Options::PrepareForBulkLoad()
        // See "What's the fastest way to load data into RocksDB?" in
        // https://github.com/facebook/rocksdb/wiki/RocksDB-FAQ
        let (
```

**Review by oxarbitrage — APPROVED** [review]
Looks good, lets merge.
