### PR TITLE
Fix shutdown panics

### LINKED ISSUE #1574: Spurious MustUseOneshotSender panic on zebrad shutdown
**Version**

`zebrad 1.0.0-alpha.0`

Commit a4182846 "Create the global span immediately after activating tracing" from PR #1568

**Platform**

`Linux ... 5.4.83 #1-NixOS SMP Fri Dec 11 12:23:33 UTC 2020 x86_64 GNU/Linux`

**Description**

`zebrad` can panic with a spurious `MustUseOneshotSender` panic on shutdown.

I tried this:

Shutting down `zebrad` using Control-C (SIGINT)

I expected to see this happen:

`zebrad` exits without panicking

Instead, this happened:

`zebrad` panics with a spurious `MustUseOneshotSender` error, even though the sender invariant is irrelevant during shutdown.

**Possible Solutions**

Stop enforcing and relying on the sender invariant during shutdown:
* Set a flag during shutdown, and use it to ignore any `MustUseOneshotSender` errors
* As soon as the flag is set, `Client`s should stop polling the background `Receiver`s tied to their `Senders`

**Commands**

`zebrad start` from a debug build, using the default config

**Related Issues**

We should re-test the fix for this issue after #1351, because it will change the interrupt handler so it works even when `zebrad` is busy.

#1576 is a similar panic in the checkpointer during shutdown.

**Logs**

```                                                         
Jan 11 17:19:08.139  INFO {zebrad="827cb238" net=Mainnet}:peer{addr=161.53.201.181:8233}:msg_as_req{msg=getheaders}:inbound:state: zebra_state::service: responding to peer GetBlocks or GetHeaders final_height=Height(0) response_len=0 chain_tip_height=Height(0) stop_height=None intersection_height=Some(Height(0))
Jan 11 17:19:08.156  INFO {zebrad="827cb238" net=Mainnet}:peer{addr=93.51.53.177:8233}:msg_as_req{msg=getheaders}:inbound:state: zebra_state::service: responding to peer GetBlocks or GetHeaders final_height=Height(0) response_len=0 chain_tip_height=Height(0) stop_height=None intersection_height=Some(Height(0))
^CJan 11 17:19:08.177  INFO {zebrad="827cb238" net=Mainnet}:sig{kind=SignalKind(2) name="SIGINT"}: zebrad::signal: received SIGINT, starting shutdown
The application panicked (crashed).
Message:  unused oneshot sender: oneshot must be used or canceled: MustUseOneshotSender { tx: Some(Sender { inner: Inner { complete: false, data: Lock { locked: false, data: UnsafeCell }, rx_task: Lock { locked: false, data: UnsafeCell }, tx_task: Lock { locked: false, data: UnsafeCell } } }) }
Location: zebra-network/src/peer/client.rs:183

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ SPANTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━Jan 11 17:19:08.177  INFO {zebrad="827cb238" net=Mainnet}:peer{addr=185.86.76.62:8233}:msg_as_req{msg=getheaders}:inbound:state: zebra_state::service: responding to peer GetBlocks or GetHeaders final_height=Height(0) response_len=0 chain_tip_height=Height(0) stop_height=None intersection_height=Some(Height(0))
━━━━━━━━━
  
   0: zebra_network::peer::client::drop
      at zebra-network/src/peer/client.rs:180
```

### LINKED ISSUE #1576: Spurious checkpoint verifier JoinError panic on zebrad shutdown
**Version**

`zebrad 1.0.0-alpha.0`

Commit a4182846 "Create the global span immediately after activating tracing" from PR #1568

**Platform**

`Linux ... 5.4.83 #1-NixOS SMP Fri Dec 11 12:23:33 UTC 2020 x86_64 GNU/Linux`

**Description**

`zebrad` can panic with a spurious `commit_finalized_block should not panic: JoinError::Cancelled` error in the checkpointer on shutdown.

I tried this:

Shutting down `zebrad` using Control-C (SIGINT)

I expected to see this happen:

`zebrad` exits without panicking

Instead, this happened:

`zebrad` panics with a spurious `commit_finalized_block should not panic: JoinError::Cancelled` in the `CheckpointVerifier`.

This invariant is stronger than required, because the syncer is shutting down.

The `FinalizedState` already ensures the necessary invariants:
- commit continuous blocks to the finalized state
- commit complete block data for each block to the finalized state (using a RocksDB transaction)

**Solution**

- [ ] Ignore the checkpoint invariant during shutdown
- [ ] Add an acceptance test that makes sure we can restart in the middle of a checkpoint:
- [ ] Add an acceptance test that waits for 10 (?) seconds, kills `zebrad`, and then restarts it (rather than using `debug_stop_at_height`)

Restarting in the middle of a checkpoint:
1. Add a `height` parameter to the `restart_stop_at_height` test
2. Run the test for heights `0`, `zebra_consensus::MAX_CHECKPOINT_HEIGHT_GAP / 2`, and `zebra_consensus::MAX_CHECKPOINT_HEIGHT_GAP`

That way, we'll test that Zebra can restart:
* after genesis
* after an incomplete checkpoint
* after a full checkpoint
* after being killed (rather than exiting normally)

**Commands**

`zebrad start` from a debug build, using the default config

**Related Issues**

We should re-test the fix for this issue after #1351, because it will change the interrupt handler so it works even when `zebrad` is busy.

Spurious MustUseOneshotSender panic on zebrad shutdown #1574 is a similar issue in the network code

**Logs**

```                                                         
Jan 11 18:24:16.025  INFO {zebrad="a4182846" net=Mainnet}:sync:extend_tips:checkpoint: zebra_consensus::checkpoint: verified checkpoint range block_count=1600 current_range=(Excluded(Height(4800)), Included(Height(6400)))
Jan 11 18:24:18.863  INFO {zebrad="a4182846" net=Mainnet}:sync: zebrad::components::sync: waiting for pending blocks tips.len=1 in_flight=2372 lookahead_limit=2000
Jan 11 18:24:18.866  INFO {zebrad="a4182846" net=Mainnet}:sync: zebrad::components::sync: extending tips tips.len=1 in_flight=2000 lookahead_limit=2000
^CJan 11 18:24:21.751  INFO {zebrad="a4182846" net=Mainnet}:sig{kind=SignalKind(2) name="SIGINT"}: zebrad::signal: received SIGINT, starting shutdown
The application panicked (crashed).
Message:  commit_finalized_block should not panic: JoinError::Cancelled
Location: /home/dev/zebra/zebra-consensus/src/checkpoint.rs:902

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ SPANTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━
  
   0: zebrad::components::sync::extend_tips
      at zebrad/src/components/sync.rs:381
   1: zebrad::components::sync::sync
      at zebrad/src/components/sync.rs:150
   2: zebrad::application:: with zebrad="a4182846" net=Mainnet
      at zebrad/src/application.rs:240
```

### PR DESCRIPTION
**Pull request by oxarbitrage**
## Motivation

Attempt to fix panics on shutdown. If merged it will close https://github.com/ZcashFoundation/zebra/issues/1574 and close https://github.com/ZcashFoundation/zebra/issues/1576

## Solution

Added a shutdown flag so the check can be skipped when shutting down and the panics avoided.

## Tasks

- [x] Move all the new code into a `zebra_chain::shutdown` module
- [x] Document why we use the `SeqCst` memory ordering at the top of that module: https://github.com/ZcashFoundation/zebra/pull/1637/files#r565944454
- [x] Bug fix: set `IS_SHUTTING_DOWN` to true after shutdown has started, rather than at startup
- [x] Refactor: set `IS_SHUTTING_DOWN` to true in a new function, rather than copying and pasting the code in multiple places
- [x] Add fix for panic in #1576
- [x] Minor fixes for the checkpoint verifier panic
- [x] Change the description of `VerifyCheckpointError::Finished` to `checkpoint request after the final checkpoint has been verified`

### Optional Tasks

- add a small unit test that checks that IS_SHUTTING_DOWN is false: (#1666)
  - at the start of the test, and
  - after you've spawned a `shutdown()` task using `spawn_blocking` 

We don't need to check that `IS_SHUTTING_DOWN` becomes true - we'll notice the panics if that part of the code ever breaks.

## Follow Up

Restart tests #1666
Panic hook refactor #1677 
Graceful shutdown redesign #1678

### CODE REVIEW

File: zebra-network/src/peer/client.rs [hunk 1]
```diff
@@ -168,6 +168,14 @@ impl<T: std::fmt::Debug> MustUseOneshotSender<T> {
             .unwrap_or_else(
                 || panic!("called is_canceled() after using oneshot sender: oneshot must be used exactly once: {:?}", self))
     }
+
+    /// Returns true if the application is shutting down.
+    ///
+    /// Returns false otherwise.
+    pub fn is_shutdown(&self) -> bool {
+        use std::sync::atomic::Ordering;
+        crate::IS_SHUTDOWN.load(Ordering::Relaxed)
```
Comment (teor2345) [inline zebra-network/src/peer/client.rs]: Please add a comment explaining why this memory ordering is correct

File: zebra-network/src/peer/client.rs [hunk 2]
```diff
@@ -179,12 +187,15 @@ impl<T: std::fmt::Debug> From<oneshot::Sender<T>> for MustUseOneshotSender<T> {
 impl<T: std::fmt::Debug> Drop for MustUseOneshotSender<T> {
     #[instrument(skip(self))]
     fn drop(&mut self) {
-        // is_canceled() will not panic, because we check is_none() first
-        assert!(
-            self.tx.is_none() || self.is_canceled(),
-            "unused oneshot sender: oneshot must be used or canceled: {:?}",
-            self
-        );
+        // we don't evaluate if we are shutting down
```
Comment (teor2345) [inline zebra-network/src/peer/client.rs]: Let's make this comment clearer:
```suggestion
        // we don't panic if we are shutting down anyway
```

File: zebrad/src/components/tokio.rs [hunk 3]
```diff
@@ -34,6 +34,7 @@ impl TokioComponent {
 /// Zebrad's graceful shutdown function, blocks until one of the supported
 /// shutdown signals is received.
 async fn shutdown() {
+    zebra_network::IS_SHUTDOWN.store(true, Ordering::Relaxed);
```
Comment (teor2345) [inline zebrad/src/components/tokio.rs]: Please add a comment explaining why this memory ordering is correct

File: zebra-network/src/lib.rs [hunk 4]
```diff
@@ -88,3 +88,7 @@ pub use crate::{
 pub mod types {
     pub use crate::{meta_addr::MetaAddr, protocol::types::PeerServices};
 }
+
+use std::sync::atomic::AtomicBool;
+/// A flag to indicate if zebrad is shutting down.
+pub static IS_SHUTDOWN: AtomicBool = AtomicBool::new(false);
```
Comment (teor2345) [inline zebra-network/src/lib.rs]: Nitpick: Zebra is in the process of shutting down, so let's make the flag name clearer 
```suggestion
pub static IS_SHUTTING_DOWN: AtomicBool = AtomicBool::new(false);
```

File: zebra-network/src/peer/client.rs [hunk 5]
```diff
@@ -168,6 +168,14 @@ impl<T: std::fmt::Debug> MustUseOneshotSender<T> {
             .unwrap_or_else(
                 || panic!("called is_canceled() after using oneshot sender: oneshot must be used exactly once: {:?}", self))
     }
+
+    /// Returns true if the application is shutting down.
+    ///
+    /// Returns false otherwise.
+    pub fn is_shutdown(&self) -> bool {
```
Comment (teor2345) [inline zebra-network/src/peer/client.rs]:
```suggestion
    pub fn is_shutting_down(&self) -> bool {
```

**Review by teor2345 — CHANGES_REQUESTED** [review]
This change looks good, but can we make the shutdown flag or function a global that's shared across crates?

We also want to use the flag in the CheckpointVerifier: https://github.com/ZcashFoundation/zebra/issues/1576

I'd like to do both fixes in the same PR, to make sure we've got the shared references correct.

**Review by yaahc — DISMISSED** [review]
This PR looks good but I do think that is is indicative of a problem. I don't know if we can reasonably solve it but I do think we should consider evaluating what changes we would need to make to allow for a graceful shutdown that calls all destructors and exits main normally, rather than relying on `std::process::exit` / `panic` and adding special cases like this to prevent misleading diagnostics.

**Comment by teor2345** [comment]
> This PR looks good but I do think that is is indicative of a problem. I don't know if we can reasonably solve it but I do think we should consider evaluating what changes we would need to make to allow for a graceful shutdown that calls all destructors and exits main normally, rather than relying on `std::process::exit` / `panic` and adding special cases like this to prevent misleading diagnostics.

I think the alternative is checking `IS_SHUTTING_DOWN` in all our endless loop tasks, and in any futures that might block. And then making sure things shut down in the right order.

We could also pass a oneshot as a cancel handle to every endless loop, and close that oneshot when the next level up wants to finish. That seems like a better architecture than a shared global.

**Comment by yaahc** [comment]
> I think the alternative is checking `IS_SHUTTING_DOWN` in all our endless loop tasks, and in any futures that might block. And then making sure things shut down in the right order.
> 
> We could also pass a oneshot as a cancel handle to every endless loop, and close that oneshot when the next level up wants to finish. That seems like a better architecture than a shared global.

I think the shared global might be the best choice in this case, or at least something functionally equivalent. What we really want is a oneshot broadcast channel, but as far as I can tell that isn't a thing. The flag itself doesn't have to be exposed as a global, but I think just building a simple abstraction on top of a single static atomic boolean will be the simplest and most effective solution.

**Comment by teor2345** [comment]
> > I think the alternative is checking `IS_SHUTTING_DOWN` in all our endless loop tasks, and in any futures that might block. And then making sure things shut down in the right order.
> > We could also pass a oneshot as a cancel handle to every endless loop, and close that oneshot when the next level up wants to finish. That seems like a better architecture than a shared global.
> 
> I think the shared global might be the best choice in this case, or at least something functionally equivalent. What we really want is a oneshot broadcast channel, but as far as I can tell that isn't a thing. The flag itself doesn't have to be exposed as a global, but I think just building a simple abstraction on top of a single static atomic boolean will be the simplest and most effective solution.

If we're waiting on shutdown along with long-running futures in a `select!`, then it will need to be a broadcast channel.

We can make it a oneshot broadcast on the sender side, by dropping the sender once we've sent the shutdown message. (And giving it a queue length of 1.)

File: zebrad/src/components/tokio.rs [hunk 6]
```diff
@@ -34,6 +34,7 @@ impl TokioComponent {
 /// Zebrad's graceful shutdown function, blocks until one of the supported
 /// shutdown signals is received.
 async fn shutdown() {
+    zebra_network::IS_SHUTTING_DOWN.store(true, Ordering::Relaxed);
     imp::shutdown().await;
```
Comment (teor2345) [inline zebrad/src/components/tokio.rs]: This code sets `IS_SHUTTING_DOWN` to true, then waits for shutdown.

Instead, set `IS_SHUTTING_DOWN` to true after shutdown has started:
```rust
        signal(kind)
            .expect("Failed to register signal handler")
            .recv()
            .await;
        zebra_network::IS_SHUTTING_DOWN.store(true, Ordering::SeqCst);
```
and
```rust
        tokio::signal::ctrl_c()
            .await
            .expect("listening for ctrl-c signal should never fail");
        zebra_network::IS_SHUTTING_DOWN.store(true, Ordering::SeqCst);
```

You might also want to add a small unit test that checks that `IS_SHUTTING_DOWN` is false:
* at the start of the test, and
* after you've spawned a blocking `shutdown()` task

We don't need to check that it becomes true - we'll notice the panics if that part of the code ever breaks.

Let's also set `IS_SHUTTING_DOWN` in its own function, so we don't have to repeat the code.

File: zebra-network/src/peer/client.rs [hunk 7]
```diff
@@ -168,6 +168,14 @@ impl<T: std::fmt::Debug> MustUseOneshotSender<T> {
             .unwrap_or_else(
                 || panic!("called is_canceled() after using oneshot sender: oneshot must be used exactly once: {:?}", self))
     }
+
+    /// Returns true if the application is shutting down.
+    ///
+    /// Returns false otherwise.
+    pub fn is_shutting_down(&self) -> bool {
+        use std::sync::atomic::Ordering;
+        crate::IS_SHUTTING_DOWN.load(Ordering::Relaxed)
```
Comment (teor2345) [inline zebra-network/src/peer/client.rs]: We might need `SeqCst` ordering when we start sharing `IS_SHUTTING_DOWN` between crates using an `Arc`. `Arc`s also use atomics, and we need the write to happen within the `Arc` critical section.

```suggestion
        // ## Correctness:
        //
        // Since we're shutting down, and this is a one-time operation,
        // performance is not important. So we use the strongest memory
        // ordering.
        // https://doc.rust-lang.org/nomicon/atomics.html#sequentially-consistent
        crate::IS_SHUTTING_DOWN.load(Ordering::SeqCst)
```

**Review by teor2345 — CHANGES_REQUESTED** [review]
This code sets `IS_SHUTTING_DOWN = true` right after startup, but we need to set it just after shutdown begins.

I'm not sure about the memory ordering, and performance isn't important on shutdown, so let's just use the strongest memory ordering.

Please move all this new code into a new `shutdown` module in `zebra-chain`, so we can:
* use it from `zebra-network` and `zebra-consensus` (and any other crates that need it)
* keep the memory ordering docs and code in a single place, so they stay consistent

File: zebra-consensus/src/checkpoint.rs [hunk 8]
```diff
@@ -905,9 +905,12 @@ where
         });
 
         async move {
-            commit_finalized_block
-                .await
-                .expect("commit_finalized_block should not panic")
+            let fut = commit_finalized_block.await;
+            if zebra_chain::shutdown::is_shutting_down() {
+                Err(VerifyCheckpointError::Finished)
```
Comment (oxarbitrage) [inline zebra-consensus/src/checkpoint.rs]: I am unsure if this will be the best to return.

**Comment by oxarbitrage** [comment]
I made the refactor suggested and added a fix for https://github.com/ZcashFoundation/zebra/issues/1576

I tried this manually and i was not able to get any more panics on shutdown with ctrl-c in linux.
The `MustUseOneshotSender` panic was happening if ctrl-c was executed just a few seconds after the zebrad starts, before the `initializing syncer` msg. Checkpoint panic was happening with any ctrl-c signal after this.

File: zebra-chain/src/shutdown.rs [hunk 9]
```diff
@@ -0,0 +1,26 @@
+//! Shutdown related code.
+//!
+//! A global flag indicates when the application is shutting down so actions can be taken
+//! at different parts of the codebase.
+
+use std::sync::atomic::{AtomicBool, Ordering};
+
+/// A flag to indicate if zebrad is shutting down.
+pub static IS_SHUTTING_DOWN: AtomicBool = AtomicBool::new(false);
```
Comment (teor2345) [inline zebra-chain/src/shutdown.rs]: Two tweaks:
1. Let's just say `Zebra`, because we might also want to shut down `zebra-client`. And users of `zebra-network` might want to shut it down.
2. Let's be explicit about the initial value.

```suggestion
/// A flag to indicate if Zebra is shutting down.
///
/// Initialized to `false` at startup.
pub static IS_SHUTTING_DOWN: AtomicBool = AtomicBool::new(false);
```

File: zebra-chain/src/shutdown.rs [hunk 10]
```diff
@@ -0,0 +1,26 @@
...
+    // ## Correctness:
+    //
+    // Since we're shutting down, and this is a one-time operation,
+    // performance is not important. So we use the strongest memory
+    // ordering.
+    // https://doc.rust-lang.org/nomicon/atomics.html#sequentially-consistent
+    IS_SHUTTING_DOWN.load(Ordering::SeqCst)
+}
+
+pub fn set_shutting_down() {
```
Comment (teor2345) [inline zebra-chain/src/shutdown.rs:27]: We document every public function.

```suggestion
/// Sets the Zebra shutdown flag to `true`.
pub fn set_shutting_down() {
```

File: zebra-consensus/src/checkpoint.rs [hunk 11]
```diff
@@ -905,9 +905,12 @@ where
         });
 
         async move {
-            commit_finalized_block
-                .await
-                .expect("commit_finalized_block should not panic")
+            let fut = commit_finalized_block.await;
+            if zebra_chain::shutdown::is_shutting_down() {
```
Comment (teor2345) [inline zebra-consensus/src/checkpoint.rs:918]: I'm not sure if this shutdown check is in the right place.

`tokio::spawn` drives the task concurrently in another thread:
https://docs.rs/tokio/1.1.1/tokio/fn.spawn.html

So we can panic before the thread that runs this future gets to `commit_finalized_block.await`. I think the current code works because tokio sets `panic=unwind`. But I'm not sure if we want to rely on that.

Also, the verification in the `commit_finalized_block` future is usually much slower than this future, because it waits on other blocks. So this future usually gets to `commit_finalized_block.await` before the other future panics.

Maybe @yaahc can help?
Can we rely on tokio to always set `panic=unwind`?

File: zebra-consensus/src/checkpoint.rs [hunk 12]
```diff
@@ -905,9 +905,12 @@ where
         });
 
         async move {
-            commit_finalized_block
-                .await
-                .expect("commit_finalized_block should not panic")
+            let fut = commit_finalized_block.await;
```
Comment (teor2345) [inline zebra-consensus/src/checkpoint.rs]: Since you've awaited it, this isn't a future any more, it's just a result.
```suggestion
            let result = commit_finalized_block.await;
```

File: zebra-consensus/src/checkpoint.rs (hunk 8 above)
Comment (teor2345) [reply zebra-consensus/src/checkpoint.rs]: I don't think that `Finished` is the same error as `shutdown failure`, but they are easy to confuse.

Let's change the description of `Finished` to `checkpoint request after the final checkpoint has been verified`. That will help avoid confusion in future.

We also only need to return an error if the spawned task actually failed, so we should use `map_err`.

Finally, we might want to wrap the error with a note that Zebra is shutting down. I'm not sure if the code I've written will work, @yaahc might be able to give you a quick fix that does. But if it takes more than 5 minutes, let's just skip the `wrap_err`.

```suggestion
                result.map_err(wrap_err("Zebra is shutting down")).map_err(VerifyCheckpointError::CommitFinalized)
```

**Review by teor2345 — CHANGES_REQUESTED** [review]
Looks good, I just have a bunch of tweaks, and some error handling fixes and questions.

File: zebra-consensus/src/checkpoint.rs (hunk 8 above)
Comment (yaahc) [reply zebra-consensus/src/checkpoint.rs]: This wont be easy to do from within `zebra-consensus` because of the `tower::Buffer` which forces us to convert all these errors into a `Box<dyn Error + ...>`. If we were working directly with `eyre::Report`s here we could just shove a `.note` on the error to get a new section, but until I make the error handling refactors we should probably not bother worrying about notes or suggestions in errors coming from our library APIs

Comment (teor2345) [reply zebra-consensus/src/checkpoint.rs]: Ok, so we still have to fix up the `map_err` and the `Finished` description here.

Comment (oxarbitrage) [reply zebra-consensus/src/checkpoint.rs]: what about something as https://github.com/ZcashFoundation/zebra/pull/1637/commits/1326ceb4189b9d2475b399c53616f2ddadbc8c34 ?

File: zebra-consensus/src/checkpoint.rs (hunk 11 above)
Comment (yaahc) [reply zebra-consensus/src/checkpoint.rs:918]: > Can we rely on tokio to always set panic=unwind?

Not in in our library crates at the very least, any dependency of ours can just use unwinding panics instead and we have no control over that. That said, I'm not following the scenario as you're laying it out. Are you talking about the panic on line 912?

**Comment by teor2345** [comment]
The coverage failure is a known issue, but it doesn't have a ticket yet.

The macOS failure is a testnet large sync test failure, which is also a known issue.

File: zebra-consensus/src/checkpoint.rs (hunk 8 above)
Comment (teor2345) [reply zebra-consensus/src/checkpoint.rs]: Looks good

**Comment by yaahc** [comment]
> The coverage failure is a known issue, but it doesn't have a ticket yet.
> 
> The macOS failure is a testnet large sync test failure, which is also a known issue.

failing CI makes me a very sad rustacean

**Comment by teor2345** [comment]
> > The coverage failure is a known issue, but it doesn't have a ticket yet.
> > The macOS failure is a testnet large sync test failure, which is also a known issue.
> 
> failing CI makes me a very sad rustacean

We can fix the coverage now. The testnet failure is blocked by fixing the hangs, then we can deploy some more testnet nodes to fix it.

File: zebra-consensus/src/checkpoint.rs (hunk 11 above)
Comment (teor2345) [reply zebra-consensus/src/checkpoint.rs:918]: Yes, but the panic on line 912 happens because of a panic inside the spawned commit_finalized_block future, so the actual panic is probably on line 897. (Or it's an internal tokio task cancellation due to shutdown.)

Comment (teor2345) [reply zebra-consensus/src/checkpoint.rs:918]: At the moment, I think that there's a panic inside commit_finalized_block that gets turned into JoinError::Cancelled by tokio, but I'm not sure.

If there is a panic inside commit_finalized_block, and it could ever turn into an abort, we need to check the shutdown flag there.

Comment (yaahc) [reply zebra-consensus/src/checkpoint.rs:918]: I don't think there are any soundness issues here regarding the panic personality. With panic = abort we can see the spawned thread panic and immediately take down the entire application. With panic = unwind we will instead capture the panic, and re-panic in the else case on line 912. As far as the API of `zebra-consensus` is concerned this is fine. The main issue is that when you're capturing panics and re-throwing them it tends to be lossy and slow, so depending on how a consumer of `zebra-consensus` uses the `Service` they will need to handle the case where the service goes down, but that should be possible with our current API.

Comment (teor2345) [reply zebra-consensus/src/checkpoint.rs:918]: I'm not concerned about soundness or even state correctness issues here.
Edit: I'm also not concerned about performance - these panics only happen on shutdown.

I'm concerned about this fix being fragile and dependent on other libraries' panic personalities.

We check the shutdown flag here to avoid a panic on Ctrl-C. But this is the wrong place to check the shutdown flag if we're actually panicking somewhere else.

Specifically, we might need to check the flag elsewhere if:
1. we `panic=abort` on either `.expect("Verified checkpoints must be committed transactionally")`
2. whatever is causing the `JoinError::Cancelled` turns into a panic

I think this is a complex enough issue that it at least deserves a clarifying comment. I don't think we need to make any further code changes right now, because the code seems to work, and this is a low-priority fix.

Comment (teor2345) [reply zebra-consensus/src/checkpoint.rs:918]: Here's a draft comment.
```suggestion
            // Avoid a panic on shutdown
            //
            // When `zebrad` is terminated using Ctrl-C, the `commit_finalized_block` task
            // can return a `JoinError::Cancelled`. We expect task cancellation on shutdown,
            // so we don't need to panic here. The persistent state is correct even when the
            // task is cancelled, because block data is committed inside transactions, in
            // height order.
            if zebra_chain::shutdown::is_shutting_down() {
```

Comment (teor2345) [reply zebra-consensus/src/checkpoint.rs:918]: @yaahc #1576 is the bug we're trying to fix here

Comment (yaahc) [reply zebra-consensus/src/checkpoint.rs:918]: aah, that makes sense. We might need to put the check for `is_shutting_down` in the panic hook itself.

Comment (yaahc) [reply zebra-consensus/src/checkpoint.rs:918]: https://github.com/oxarbitrage/zebra/blob/issue1574/zebrad/src/application.rs#L222-L224

This would be the place, where we just skip reporting any panics if the shutdown flag is enabled.

Comment (teor2345) [reply zebra-consensus/src/checkpoint.rs:918]: Hmm yeah I hadn't thought of that. Good idea!

I don't think we want to skip all panics on shutdown, but it would definitely be easier to filter out certain kinds of panics (for example: `JoinError::Cancelled`) in the panic hook.

Can you open a ticket for that?

This PR fixes the known issues right now, and I don't think any further changes are urgent. We can move to the panic hook next time we find a shutdown panic.

Comment (teor2345) [reply zebra-consensus/src/checkpoint.rs:918]: For example, if a panic indicates a corrupted state, we don't want to skip it at shutdown.

Comment (teor2345) [reply zebra-consensus/src/checkpoint.rs:918]: (I've just committed the comment, because GitHub is hiding the middle of this conversation.)

**Review by teor2345 — APPROVED** [review]
This looks good now, but we still need to open a ticket to refactor some shutdown checks into the panic hook.

File: zebra-consensus/src/checkpoint.rs (hunk 11 above)
Comment (yaahc) [reply zebra-consensus/src/checkpoint.rs:918]: > I don't think we want to skip all panics on shutdown, but it would definitely be easier to filter out certain kinds of panics (for example: JoinError::Cancelled) in the panic hook.

The main issue is that panics completely erase the type of the payload, usually by stringifying it, so filtering is gonna be string matching :/. My feeling is that we're not planning on keeping this code long term anyways, and if there's corruption in the state I would expect the error to be triggered on the next start, not while shutting down. It doesn't seem like a huge risk to me, versus the benefit of pretty consistently suppressing superfluous errors until we've got graceful shutdown implemented.

Comment (teor2345) [reply zebra-consensus/src/checkpoint.rs:918]: I think this discussion belongs in a new ticket :-)

**Comment by teor2345** [comment]
> > > I think the alternative is checking `IS_SHUTTING_DOWN` in all our endless loop tasks, and in any futures that might block. And then making sure things shut down in the right order.
> > > We could also pass a oneshot as a cancel handle to every endless loop, and close that oneshot when the next level up wants to finish. That seems like a better architecture than a shared global.
> > 
> > 
> > I think the shared global might be the best choice in this case, or at least something functionally equivalent. What we really want is a oneshot broadcast channel, but as far as I can tell that isn't a thing. The flag itself doesn't have to be exposed as a global, but I think just building a simple abstraction on top of a single static atomic boolean will be the simplest and most effective solution.
> 
> If we're waiting on shutdown along with long-running futures in a `select!`, then it will need to be a broadcast channel.
> 
> We can make it a oneshot broadcast on the sender side, by dropping the sender once we've sent the shutdown message. (And giving it a queue length of 1.)

This redesign is now #1678

File: zebra-consensus/src/checkpoint.rs (hunk 11 above)
Comment (teor2345) [reply zebra-consensus/src/checkpoint.rs:918]: This refactor is now #1677
