### PR TITLE
fix(db): Fix a sprout/history tree read panic in Zebra 1.4.0, which only happens before the 25.3.0 state upgrade completes

### LINKED ISSUE #7961: bug: Crash: Sprout note commitment tree must exist if there is a finalized tip
### What happened?

 I expected to see this happen: zebra starts

Instead, this happened: Zebra is in restart crash loop (it is running under systemd). 

0|zebrad  | The application panicked (crashed).
0|zebrad  | Message:  Sprout note commitment tree must exist if there is a finalized tip
0|zebrad  | Location: zebra-state/src/service/finalized_state/zebra_db/shielded.rs:119
0|zebrad  | Metadata:
0|zebrad  | version: 1.4.0+14.gc3b11e3
0|zebrad  | Zcash network: Mainnet
0|zebrad  | running state version: 25.3.0
0|zebrad  | initial disk state version: 25.2.2
0|zebrad  | features: default,getblocktemplate_rpcs,howudoin,indicatif,progress_bar,release_max_level_info
0|zebrad  | branch: main
0|zebrad  | git commit: c3b11e3
0|zebrad  | commit timestamp: 2023-11-16T21:22:34.000000000Z
0|zebrad  | target triple: x86_64-unknown-linux-gnu
0|zebrad  | rust compiler: 1.72.0
0|zebrad  | rust release date: 2023-08-23
0|zebrad  | optimization level: 3
0|zebrad  | debug checks: false

### What were you doing when the issue happened?

_No response_

### Zebra logs

_No response_

### Zebra Version

_No response_

### Which operating systems does the issue happen on?

- [X] Linux
- [ ] macOS
- [ ] Windows
- [ ] Other OS

### OS details

_No response_

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by teor2345**
## Motivation

Zebra 1.4.0 only writes the sprout and history trees when they have changed, but it expects to find them at the empty key `()` or tip height. If there aren't any sprout transactions, or we're before heartwood, the trees can actually be below the tip height.

See this detailed explanation:
https://github.com/ZcashFoundation/zebra/issues/7961#issuecomment-1820451884

There is also a race condition that can happen when upgrading from 1.1.0 to 1.4.0, which we support on a best effort basis.

See this detailed explanation for this possible race condition:
https://github.com/ZcashFoundation/zebra/issues/7961#issuecomment-1820395206

Close #7961.

#### Check before marking the PR as ready for review:
  - [x] Will the PR name make sense to users?
  - [x] Does the PR have a priority label?
  - [x] Have you added or updated tests?
  - [x] Is the documentation up to date?

##### For significant changes:
  - [ ] Is there a summary in the CHANGELOG?
  - [ ] Can these changes be split into multiple PRs?

_If a checkbox isn't relevant to the PR, mark it as done._

We might want a changelog entry, I'm not sure.

### Complex Code or Requirements

This is concurrent code involving a data race.

## Solution

- Look for the sprout tree at the greatest available height before and during the 25.3.0 upgrade, rather than just checking the tip height
- Minimise the risk of a potential data race before and during the 25.3.0 state upgrade, by moving slow code to another database batch

### Testing

Marek and the ticket reporter have both manually tested this code and confirmed it is correct.

I don't think we can test for the race condition that's fixed in this PR.

## Review

This is a high priority fix.

### Reviewer Checklist

Check before approving the PR:
  - [x] Does the PR scope match the ticket?
  - [x] Are there enough tests to make sure it works? Do the tests cover the PR motivation?
  - [x] Are all the PR blockers dealt with?
        PR blockers can be dealt with in new tickets or PRs.

_And check the PR Author checklist is complete._

## Follow Up Work

Document how to avoid this happening again in the state upgrade docs.

In particular, don't concurrently read and write the same keys in the same column family:
- in an upgrade, and
- in the sync.

And make sure the read and write methods have compatible conditions.

### CODE REVIEW

File: zebra-state/src/service/finalized_state/zebra_db/chain.rs [hunk 1]
```diff
@@ -59,11 +59,10 @@ impl ZebraDb {
...
         if history_tree.is_none() {
-            let tip_height = self
-                .finalized_tip_height()
-                .expect("just checked for an empty database");
-
-            history_tree = self.db.zs_get(&history_tree_cf, &tip_height);
+            // In Zebra 1.4.0 and later, we only update the history tip tree when it has changed (for every block after heartwood).
+            // But we write with a `()` key, not a height key.
+            // So we need to look for the most recent update height if the `()` key has never been written.
+            history_tree = self.db.zs_last_key_value(&history_tree_cf);
```
Comment (teor2345) [inline zebra-state/src/service/finalized_state/zebra_db/chain.rs]:
```suggestion
            history_tree = self.db.zs_last_key_value(&history_tree_cf).map(|(_height_key, tree_value)| tree_value);
```

File: zebra-state/src/service/finalized_state/zebra_db/shielded.rs [hunk 2]
```diff
@@ -109,11 +109,10 @@ impl ZebraDb {
...
         if sprout_tree.is_none() {
-            let tip_height = self
-                .finalized_tip_height()
-                .expect("just checked for an empty database");
-
-            sprout_tree = self.db.zs_get(&sprout_tree_cf, &tip_height);
+            // In Zebra 1.4.0 and later, we don't update the sprout tip tree unless it is changed.
+            // And we write with a `()` key, not a height key.
+            // So we need to look for the most recent update height if the `()` key has never been written.
+            sprout_tree = self.db.zs_last_key_value(&sprout_tree_cf);
```
Comment (teor2345) [inline zebra-state/src/service/finalized_state/zebra_db/shielded.rs]:
```suggestion
            sprout_tree = self.db.zs_last_key_value(&sprout_tree_cf).map(|(_height_key, tree_value)| tree_value);;
```

File: zebra-state/src/service/finalized_state/zebra_db/shielded.rs [hunk 3]
```diff
@@ -109,11 +109,10 @@ impl ZebraDb {
...
         if sprout_tree.is_none() {
-            let tip_height = self
-                .finalized_tip_height()
-                .expect("just checked for an empty database");
-
-            sprout_tree = self.db.zs_get(&sprout_tree_cf, &tip_height);
+            // In Zebra 1.4.0 and later, we don't update the sprout tip tree unless it is changed.
+            // And we write with a `()` key, not a height key.
+            // So we need to look for the most recent update height if the `()` key has never been written.
+            sprout_tree = self.db.zs_last_key_value(&sprout_tree_cf).map(|(_height_key, tree_value)| tree_value);;
```
Comment (teor2345) [inline zebra-state/src/service/finalized_state/zebra_db/shielded.rs]:
```suggestion
            sprout_tree = self.db.zs_last_key_value(&sprout_tree_cf).map(|(_height_key, tree_value)| tree_value);
```

File: zebra-state/src/service/finalized_state/zebra_db/chain.rs [hunk 4]
```diff
@@ -59,11 +59,10 @@ impl ZebraDb {
...
         if history_tree.is_none() {
-            let tip_height = self
-                .finalized_tip_height()
-                .expect("just checked for an empty database");
-
-            history_tree = self.db.zs_get(&history_tree_cf, &tip_height);
+            // In Zebra 1.4.0 and later, we only update the history tip tree when it has changed (for every block after heartwood).
+            // But we write with a `()` key, not a height key.
+            // So we need to look for the most recent update height if the `()` key has never been written.
+            history_tree = self.db.zs_last_key_value(&history_tree_cf).map(|(_height_key, tree_value)| tree_value);
```
Comment (teor2345) [inline zebra-state/src/service/finalized_state/zebra_db/chain.rs]:
```suggestion
            history_tree = self
                .db
                .zs_last_key_value(&history_tree_cf)
                .map(|(_key: Height, tree_value)| tree_value);
```

File: zebra-state/src/service/finalized_state/zebra_db/shielded.rs [hunk 5]
```diff
@@ -109,11 +109,10 @@ impl ZebraDb {
...
         if sprout_tree.is_none() {
-            let tip_height = self
-                .finalized_tip_height()
-                .expect("just checked for an empty database");
-
-            sprout_tree = self.db.zs_get(&sprout_tree_cf, &tip_height);
+            // In Zebra 1.4.0 and later, we don't update the sprout tip tree unless it is changed.
+            // And we write with a `()` key, not a height key.
+            // So we need to look for the most recent update height if the `()` key has never been written.
+            sprout_tree = self.db.zs_last_key_value(&sprout_tree_cf).map(|(_height_key, tree_value)| tree_value);
```
Comment (teor2345) [inline zebra-state/src/service/finalized_state/zebra_db/shielded.rs]:
```suggestion
            sprout_tree = self
                .db
                .zs_last_key_value(&sprout_tree_cf)
                .map(|(_key: Height, tree_value)| tree_value);
```

File: zebra-state/src/service/finalized_state/disk_format/upgrade/fix_tree_key_type.rs [hunk 6]
```diff
@@ -46,6 +41,24 @@ pub fn run(
         .write_batch(batch)
         .expect("updating tree key formats should always succeed");
 
+    // These deletes can be slow due to tombstones for previously deleted keys,
```
Comment (upbqdn) [inline zebra-state/src/service/finalized_state/disk_format/upgrade/fix_tree_key_type.rs]: ###### Optional Suggestion

```suggestion
    // The deletes below can be slow due to tombstones for previously deleted keys,
```

**Review by upbqdn — DISMISSED** [review]

**Review by upbqdn — APPROVED** [review]
