### PR TITLE
network: correct data modeling for headers messages

### LINKED ISSUE #1398: Zebra hang - no sync progress
**Version**

`zebrad` main branch, 2020-11-26.

**Platform**

`Linux ... 5.4.75 #1-NixOS SMP Thu Nov 5 10:43:38 UTC 2020 x86_64 GNU/Linux`

**Possible Causes**

- [ ] #1406 - UTXO hang on first finalized block

**Description**

When I run Zebra on mainnet and testnet, it sometimes fails to make progress during its initial sync. This failure to make progress persists after a restart.

In some cases, the logs continually repeat tip exhaustion:
```
Nov 26 15:38:45.572  INFO sync: zebrad::components::sync: starting sync, obtaining new tips
Nov 26 15:38:45.572  INFO sync:obtain_tips:state: zebra_state::util: created block locator tip_height=Height(502800) min_locator_height=502701 locators=[Height(502800), Height(502799), Height(502798), Height(502796), Height(502792), Height(502784), Height(502768), Height(502736), Height(502701)]
Nov 26 15:39:00.571  INFO sync: zebrad::components::sync: exhausted prospective tip set
Nov 26 15:39:00.571  INFO sync: zebrad::components::sync: waiting to restart sync timeout=45s
Nov 26 15:39:45.572  INFO sync: zebrad::components::sync: starting sync, obtaining new tips
Nov 26 15:39:45.572  INFO sync:obtain_tips:state: zebra_state::util: created block locator tip_height=Height(502800) min_locator_height=502701 locators=[Height(502800), Height(502799), Height(502798), Height(502796), Height(502792), Height(502784), Height(502768), Height(502736), Height(502701)]
Nov 26 15:40:00.571  INFO sync: zebrad::components::sync: exhausted prospective tip set
Nov 26 15:40:00.571  INFO sync: zebrad::components::sync: waiting to restart sync timeout=45s
Nov 26 15:40:45.572  INFO sync: zebrad::components::sync: starting sync, obtaining new tips
Nov 26 15:40:45.572  INFO sync:obtain_tips:state: zebra_state::util: created block locator tip_height=Height(502800) min_locator_height=502701 locators=[Height(502800), Height(502799), Height(502798), Height(502796), Height(502792), Height(502784), Height(502768), Height(502736), Height(502701)]
Nov 26 15:41:00.571  INFO sync: zebrad::components::sync: exhausted prospective tip set
Nov 26 15:41:00.571  INFO sync: zebrad::components::sync: waiting to restart sync timeout=45s
Nov 26 15:41:45.572  INFO sync: zebrad::components::sync: starting sync, obtaining new tips
```

In other cases, the logs show exhausted tips once, then hang after getting a block locator:
```
Nov 26 16:47:57.272  INFO listen{addr=0.0.0.0:38233}: zebra_network::peer_set::initialize: Opened Zcash protocol endpoint at 0.0.0.0:38233
Nov 26 16:47:57.629  INFO peer{addr=198.199.112.230:18233}:handle_message_as_request{msg=GetHeaders { known_blocks: zebra_chain::block::hash::Hash, len=32, stop: None }}:inbound:state: zebra_state::service: responding to peer GetBlocks or GetHeaders final_height=Height(131554) response_len=160 chain_tip_height=Height(502800) stop_height=None intersection_height=Some(Height(131394))
Nov 26 16:47:57.659  INFO peer{addr=209.141.47.197:18233}:handle_message_as_request{msg=GetHeaders { known_blocks: zebra_chain::block::hash::Hash, len=32, stop: None }}:inbound:state: zebra_state::service: responding to peer GetBlocks or GetHeaders final_height=Height(131554) response_len=160 chain_tip_height=Height(502800) stop_height=None intersection_height=Some(Height(131394))
...
Nov 26 16:48:05.878  INFO zebrad::commands::start: initializing syncer
Nov 26 16:48:05.879  INFO sync: zebrad::components::sync: starting sync, obtaining new tips
Nov 26 16:48:05.879  INFO sync:obtain_tips:state: zebra_state::util: created block locator tip_height=Height(502800) min_locator_height=502701 locators=[Height(502800), Height(502799), Height(502798), Height(502796), Height(502792), Height(502784), Height(502768), Height(502736), Height(502701)]
Nov 26 16:48:07.277  INFO sync: zebrad::components::sync: exhausted prospective tip set
Nov 26 16:48:07.277  INFO sync: zebrad::components::sync: waiting to restart sync timeout=45s
Nov 26 16:48:52.278  INFO sync: zebrad::components::sync: starting sync, obtaining new tips
Nov 26 16:48:52.278  INFO sync:obtain_tips:state: zebra_state::util: created block locator tip_height=Height(502800) min_locator_height=502701 locators=[Height(502800), Height(502799), Height(502798), Height(502796), Height(502792), Height(502784), Height(502768), Height(502736), Height(502701)]
```

And on mainnet, with a synced tip, zebra gave no info-level log output for 4 hours:
```
Nov 26 17:41:30.373  INFO peer{addr=[2001:41d0:700:2233::]:8233}:handle_message_as_request{msg=GetHeaders { known_blocks: zebra_chain::block::hash::Hash, len=32, stop: None }}:inbound:state: 
zebra_state::service: responding to peer GetBlocks or GetHeaders final_height=Height(1055216) response_len=37 chain_tip_height=Height(1055216) stop_height=None intersection_height=Some(Height
(1055179))                                                                                                                                                                                     
...                                                                                                                                                           
Nov 26 17:41:30.398  INFO zebrad::commands::start: initializing syncer                                                                                                                         
Nov 26 17:41:30.398  INFO sync: zebrad::components::sync: starting sync, obtaining new tips                                                                                                    
Nov 26 17:41:30.398  INFO sync:obtain_tips:state: zebra_state::util: created block locator tip_height=Height(1055216) min_locator_height=1055117 locators=[Height(1055216), Height(1055215), He
ight(1055214), Height(1055212), Height(1055208), Height(1055200), Height(1055184), Height(1055152), Height(1055117)]                                                                           
Nov 26 17:41:30.557  INFO peer{addr=47.252.84.50:8233}:handle_message_as_request{msg=GetHeaders { known_blocks: zebra_chain::block::hash::Hash, len=32, stop: None }}:inbound:state: zebra_stat
e::service: responding to peer GetBlocks or GetHeaders final_height=Height(1055216) response_len=37 chain_tip_height=Height(1055216) stop_height=None intersection_height=Some(Height(1055179))
Nov 26 17:41:30.608  INFO peer{addr=47.107.242.15:8233}:handle_message_as_request{msg=GetHeaders { known_blocks: zebra_chain::block::hash::Hash, len=32, stop: None }}:inbound:state: zebra_sta
te::service: responding to peer GetBlocks or GetHeaders final_height=Height(1055216) response_len=37 chain_tip_height=Height(1055216) stop_height=None intersection_height=Some(Height(1055179)
)
...
Nov 26 17:41:31.920  INFO peer{addr=173.212.200.221:8233}:handle_message_as_request{msg=GetHeaders { known_blocks: zebra_chain::block::hash::Hash, len=32, stop: None }}:inbound:state: zebra_s
tate::service: responding to peer GetBlocks or GetHeaders final_height=Height(1055216) response_len=37 chain_tip_height=Height(1055216) stop_height=None intersection_height=Some(Height(105517
9))
Nov 26 17:41:34.357  INFO sync: zebrad::components::sync: exhausted prospective tip set
Nov 26 17:41:34.357  INFO sync: zebrad::components::sync: waiting to restart sync timeout=45s
Nov 26 17:42:19.358  INFO sync: zebrad::components::sync: starting sync, obtaining new tips
Nov 26 17:42:19.358  INFO sync:obtain_tips:state: zebra_state::util: created block locator tip_height=Height(1055216) min_locator_height=1055117 locators=[Height(1055216), Height(1055215), Height(1055214), Height(1055212), Height(1055208), Height(1055200), Height(1055184), Height(1055152), Height(1055117)]
```

I also saw a hang on testnet waiting for pending blocks. This hang seems to happen due to a missing UTXO:
```
Nov 30 13:32:21.870  INFO peer{addr=3.112.190.48:18233}:handle_message_as_request{msg=Inv([Block(block::Hash("0015efbe9e13f4af0f434ccb955137b2f439c3c0d20d87e718ec691ee76c9e83"))])}:inbound:download_and_verify{hash=0015efbe9e13f4af0f434ccb955137b2f439c3c0d20d87e718ec691ee76c9e83}: zebra_state::service: pruned utxo requests old_len=6 new_len=0 prune_count=6 tip=Some((Height(356413), block::Hash("0003a9de9e0828185648851cc2aab8124d8c312284a20330465c66f95a525536")))
Nov 30 13:32:30.290  INFO sync: zebrad::components::sync: starting sync, obtaining new tips
Nov 30 13:32:30.290  INFO sync:obtain_tips:state: zebra_state::util: created block locator tip_height=Height(356413) min_locator_height=356314 locators=[Height(356413), Height(356412), Height(356411), Height(356409), Height(356405), Height(356397), Height(356381), Height(356349), Height(356314)]
Nov 30 13:32:37.304  INFO sync: zebrad::components::sync: extending tips tips.len=1 in_flight=499 lookahead_limit=2000
Nov 30 13:32:49.859  INFO sync: zebrad::components::sync: extending tips tips.len=1 in_flight=993 lookahead_limit=2000
Nov 30 13:32:57.405  INFO sync: zebrad::components::sync: extending tips tips.len=1 in_flight=1491 lookahead_limit=2000
Nov 30 13:33:10.576  INFO sync: zebrad::components::sync: extending tips tips.len=1 in_flight=1989 lookahead_limit=2000
Nov 30 13:33:11.212  INFO sync: zebrad::components::sync: exhausted prospective tip set
Nov 30 13:33:11.212  INFO sync: zebrad::components::sync: waiting to restart sync timeout=45s
Nov 30 13:33:30.487  INFO peer{addr=159.69.217.179:18233}:handle_message_as_request{msg=Inv([Block(block::Hash("00139e448ad701a705b29c014d10182553c2748c25bd54124e4cf4c2444ae1e3"))])}:inbound:download_and_verify{hash=00139e448ad701a705b29c014d10182553c2748c25bd54124e4cf4c2444ae1e3}: zebra_state::service: pruned utxo requests old_len=14 new_len=0 prune_count=14 tip=Some((Height(356413), block::Hash("0003a9de9e0828185648851cc2aab8124d8c312284a20330465c66f95a525536")))
Nov 30 13:33:56.214  INFO sync: zebrad::components::sync: starting sync, obtaining new tips
Nov 30 13:33:56.214  INFO sync:obtain_tips:state: zebra_state::util: created block locator tip_height=Height(356413) min_locator_height=356314 locators=[Height(356413), Height(356412), Height(356411), Height(356409), Height(356405), Height(356397), Height(356381), Height(356349), Height(356314)]
Nov 30 13:34:09.390  INFO sync: zebrad::components::sync: extending tips tips.len=1 in_flight=499 lookahead_limit=2000
Nov 30 13:34:17.902  INFO sync: zebrad::components::sync: extending tips tips.len=1 in_flight=995 lookahead_limit=2000
Nov 30 13:34:25.823  INFO sync: zebrad::components::sync: extending tips tips.len=1 in_flight=1493 lookahead_limit=2000
Nov 30 13:34:33.369  INFO sync: zebrad::components::sync: extending tips tips.len=1 in_flight=1991 lookahead_limit=2000
Nov 30 13:34:40.901  INFO sync: zebrad::components::sync: waiting for pending blocks tips.len=1 in_flight=2489 lookahead_limit=2000
Nov 30 13:44:03.155  WARN sync: zebrad::components::sync: error downloading and verifying block e=Block(Transaction(InternalDowncastError("downcast to redjubjub::Error failed, original error: Elapsed(())")))
```

### LINKED ISSUE #1409: Mainnet zebrad ends up with a very small number of peers
**Version**

`zebrad` main branch, 2020-12-01.

**Platform**

`Linux ... 5.4.75 #1-NixOS SMP Thu Nov 5 10:43:38 UTC 2020 x86_64 GNU/Linux`

**Description**

After syncing overnight, `zebrad` trails the tip by at least 100,000 blocks, and has a very small number of peers (4) on Mainnet. 3 of these peers are local peers that specifically whitelist connections from the local network.

**Detailed Logs**

```
Dec 01 10:01:10.413  INFO sync:obtain_tips:state: zebra_state::util: created block locator tip_height=Height(914254) min_locator_height=914155 locators=[Height(914254), Height(914253), Height
(914252), Height(914250), Height(914246), Height(914238), Height(914222), Height(914190), Height(914155)]
Dec 01 10:01:16.414  INFO sync: zebrad::components::sync: exhausted prospective tip set
Dec 01 10:01:16.414  INFO sync: zebrad::components::sync: waiting to restart sync timeout=45s
Dec 01 10:02:01.415  INFO sync: zebrad::components::sync: starting sync, obtaining new tips
Dec 01 10:02:01.415  INFO sync:obtain_tips:state: zebra_state::util: created block locator tip_height=Height(914254) min_locator_height=914155 locators=[Height(914254), Height(914253), Height (914252), Height(914250), Height(914246), Height(914238), Height(914222), Height(914190), Height(914155)]
Dec 01 10:02:01.415  INFO sync:obtain_tips: zebra_network::peer_set::set: network request with no ready peers: finding more peers, waiting for 4 peers to answer requests. Hint: configure fast and reliable initial peers
Dec 01 10:02:07.416  INFO sync: zebrad::components::sync: exhausted prospective tip set
Dec 01 10:02:07.416  INFO sync: zebrad::components::sync: waiting to restart sync timeout=45s
Dec 01 10:02:52.417  INFO sync: zebrad::components::sync: starting sync, obtaining new tips
Dec 01 10:02:52.417  INFO sync:obtain_tips: zebra_state::service: pruned utxo requests old_len=12 new_len=10 prune_count=2 tip=Some((Height(914254), block::Hash("00000000010d5268529faa69c186d
433c486c7ef6726ee465fc0071207235e25")))
Dec 01 10:02:52.417  INFO sync:obtain_tips:state: zebra_state::util: created block locator tip_height=Height(914254) min_locator_height=914155 locators=[Height(914254), Height(914253), Height(914252), Height(914250), Height(914246), Height(914238), Height(914222), Height(914190), Height(914155)]
Dec 01 10:02:58.418  INFO sync: zebrad::components::sync: exhausted prospective tip set
Dec 01 10:02:58.418  INFO sync: zebrad::components::sync: waiting to restart sync timeout=45s
Dec 01 10:03:43.419  INFO sync: zebrad::components::sync: starting sync, obtaining new tips
Dec 01 10:03:43.419  INFO sync:obtain_tips:state: zebra_state::util: created block locator tip_height=Height(914254) min_locator_height=914155 locators=[Height(914254), Height(914253), Height(914252), Height(914250), Height(914246), Height(914238), Height(914222), Height(914190), Height(914155)]
Dec 01 10:03:49.420  INFO sync: zebrad::components::sync: exhausted prospective tip set
Dec 01 10:03:49.420  INFO sync: zebrad::components::sync: waiting to restart sync timeout=45s
Dec 01 10:04:34.421  INFO sync: zebrad::components::sync: starting sync, obtaining new tips
```

### LINKED ISSUE #1424: Headers messages are rejected
**Version**

Git post #1423 

**Description**

After fixing reject message parsing, we can see many messages of the form:
```
msg=Reject { message: "headers", ccode: Malformed, reason: "error parsing message", data: None }
```

### PR DESCRIPTION
**Pull request by hdevalence**
We modeled a Bitcoin `headers` message as being a list of block headers.
However, the actual data structure is slightly different: it's a list of (block
header, transaction count) pairs.  This caused zcashd to reject our headers
messages.

To fix this, introduce a new `CountedHeader` struct with a `block::Header` and
transaction count `usize`, then thread it through the inbound service and the
state.

I tested this locally by running Zebra with these changes and inspecting a
trace-level log of the span of a peer connection that requested a nontrivial
headers packet from us, and verified that it did not reject our message.

Closes #1424.
Closes #1409.
Closes #1398.

### CODE REVIEW

**Comment by hdevalence** [comment]
Fixes the problem revealed by #1423.

File: zebra-chain/src/block.rs [hunk 1]
```diff
@@ -18,7 +18,7 @@ use std::fmt;
 
 pub use hash::Hash;
 pub use header::BlockTimeError;
-pub use header::Header;
+pub use header::{Header, CountedHeader};
```
Comment (dconnolly) [inline zebra-chain/src/block.rs]: rustfmt

```suggestion
pub use header::{CountedHeader, Header};
```

File: docker/Dockerfile.build [hunk 2]
```diff
@@ -19,6 +19,7 @@ RUN cargo test --all --release; cargo build --release
 # Runner image
 FROM debian:buster-slim AS zebrad-release
 
+COPY --from=builder /zebra/otelcol-custom /
```
Comment (hdevalence) [inline docker/Dockerfile.build]: was this meant for this PR?

File: zebra-chain/src/block/header.rs [hunk 3]
```diff
@@ -109,3 +109,12 @@ impl Header {
...
 }
+
+/// A header with a count of the number of transactions in its block.
+///
+/// This structure is used in the Bitcoin network protocol.
+#[derive(Debug, Clone, PartialEq, Eq)]
+pub struct CountedHeader {
+    pub header: Header,
+    pub transaction_count: usize,
+}
```
Comment (teor2345) [inline zebra-chain/src/block/header.rs]: I'm surprised rustfmt doesn't add a line before EOF

**Review by teor2345 — DISMISSED** [review]
Also looks good, guess we should merge these all soon?

**Review by teor2345 — DISMISSED** [review]
Looks good, apart from a minor rustfmt tweak.

**Comment by hdevalence** [comment]
Rebased to pick up cargo fmt fixes in #1427

**Review by dconnolly — APPROVED** [review]
