### PR TITLE
Fix spurious WrongVersion errors, clean up checks, and tidy debug info

### LINKED ISSUE #1264: Wrong transaction version error in block verifier
**Version**

`zebrad` main branch, 2020-11-06.

**Platform**

`Linux ... 5.4.72 #1-NixOS SMP Sat Oct 17 08:11:24 UTC 2020 x86_64 GNU/Linux`

**Description**

When `zebrad` finishes the checkpoint sync on testnet, the block verifier keeps on returning a `Block(Transaction(WrongVersion))` error. The sync does not make any progress.

On testnet, the checkpoint verifier verifies the Sapling activation block `280000`. Blocks `280001` and later are verified by the block verifier.

`zebrad` on mainnet has the same issue.

**Details**

After I [added some debugging for WrongVersion](https://github.com/teor2345/zebra/commit/0a0d86f89f65787dee7fffb1d65c7233b02b05b0), I got the following error:

`Nov 20 12:45:04.319  WARN sync: zebrad::components::sync: error downloading and verifying block e=Block(Transaction(WrongVersion { version: 4, is_coinbase: true, hash: transaction::Hash("2fc0245a785668011e6a1a6830ffdc8195adeac75eb1b6bcc69c934d80f5bbf9") }))`

### PR DESCRIPTION
**Pull request by hdevalence**
## Motivation

Fixes the WrongVersion errors, cleans up checks, and tidies debug info.

## Solution

Described in commit messages

## Review

@dconnolly 

## Related Issues

Closes #1264 

## Follow Up Work

As a followup issue, we need to come up with a way to check whether a transaction spends outputs of a coinbase transaction.  This might require database format changes, so we should have a follow-up issue (#1342).

Testing the resulting code reveals that blocks aren't being committed for some reason, but this should be follow-on work, because I believe that it's a pre-existing problem revealed by removing the spurious errors.

### CODE REVIEW

File: zebra-consensus/src/transaction/check.rs [hunk 1]
```diff
@@ -21,50 +25,51 @@ pub fn validate_joinsplit_sig(
...
+            } else if tx_out_count + n_shielded_output + n_joinsplit == 0 {
+                Err(TransactionError::NoOutputs)
             } else {
-                Err(TransactionError::NoTransfer)
+                Ok(())
             }
         }
-        _ => Err(TransactionError::WrongVersion),
+        Transaction::V1 { .. } | Transaction::V2 { .. } | Transaction::V3 { .. } => {
+            unreachable!("tx version is checked first")
```
Comment (dconnolly) [inline zebra-consensus/src/transaction/check.rs:72]: 👍

File: zebra-consensus/src/transaction/check.rs [hunk 2]
```diff
@@ -86,22 +91,30 @@ pub fn shielded_balances_match(
...
+            // The ShieldedData contains both Spends and Outputs, and Outputs
+            // are allowed post-Heartwood, so we have to count Spends.
+            Transaction::V4 {
+                shielded_data: Some(shielded_data),
+                ..
+            } if shielded_data.spends().count() > 0 => Err(TransactionError::CoinbaseHasSpend),
+
+            Transaction::V4 { .. } => Ok(()),
+
+            Transaction::V1 { .. } | Transaction::V2 { .. } | Transaction::V3 { .. } => {
```
Comment (dconnolly) [inline zebra-consensus/src/transaction/check.rs:114]: 👍

**Review by dconnolly — APPROVED** [review]
