### PR TITLE
fix(rpc): Calculate getblocktemplate RPC testnet min and max times correctly

### LINKED ISSUE #5871: Fix getblocktemplate min and max times on testnet
## Motivation

On testnet only, there is a 1679 second difference between the `mintime` produced by Zebra and `zcashd` for the same height.

This amount doesn't seem to correspond to any particular consensus rule.

### Specifications

> Define the median-time-past of a block to be the median (as defined in § 7.7.3 ‘Difficulty adjustment’ on p. 131) of the nTime fields of the preceding PoWMedianBlockSpan blocks (or all preceding blocks if there are fewer than PoWMedianBlockSpan). The median-time-past of a genesis block is not defined.
> For each block other than the genesis block , nTime MUST be strictly greater than the median-time-past of that block.
> For each block at block height 2 or greater on Mainnet , or block height 653606 or greater on Testnet , nTime MUST be less than or equal to the median-time-past of that block plus 90 · 60 seconds.

https://zips.z.cash/protocol/protocol.pdf#blockheader

> This [difficulty] algorithm changed on Testnet, starting from block 299188, to allow "minimum-difficulty" blocks. If the block time of a block from this height onward is greater than 15 minutes after that of the preceding block, then the block is a minimum-difficulty block. In that case its nBits field MUST be set to ToCompact(PoWLimit)

https://zips.z.cash/zip-0205#change-to-difficulty-adjustment-on-testnet

### Complex Code or Requirements

Zebra adjusts the `mintime` or `maxtime` on testnet, so the block time range is either for a standard difficulty block, or a minimum difficulty block.

### Analysis

This is not a minimum difficulty block, so the `maxtime` should get adjusted to 15 minutes after the `mintime`. But instead it is 93.8 minutes later. But it should be 15m after the `mintime` for standard difficulty, or 75m (90m-15m) for minimum difficulty.

This seems like a bug in Zebra's testnet time adjustment. These comments are also wrong and don't match the spec:
https://github.com/ZcashFoundation/zebra/blob/80a6d3cdab2a9dc68e27ecfa729ba864394becb4/zebra-state/src/service/read/difficulty.rs#L263-L267

It is also possible that `zcashd` sets a higher minimum than the time permitted by the consensus rules.

## Related Work

This was discovered as part of:
- #5400 

## Logs

```sh
$ ZCASH_CLI="zcash-cli -testnet" zcash-rpc-diff 38232 getblocktemplate                                                                                               Checking first node release info...
Checking second node release info...
Connected to zebrad (port 38232) and zcashd (zcash-cli-testnet zcash.conf port).

Checking zebrad network and tip height...
Checking zcashd network and tip height...

Request:
getblocktemplate

Querying zebrad test chain at height >=2153481...

real    0m0.012s
user    0m0.006s
sys     0m0.005s

Querying zcashd test chain at height >=2153481...

real    0m0.018s
user    0m0.005s
sys     0m0.006s


Response diff between zebrad and zcashd:
--- /run/user/1000/tmp.2HCTThHXya.rpc-diff/zebrad-test-2153481-getblocktemplate.json    2022-12-16 13:44:35.074629890 +1000
+++ /run/user/1000/tmp.2HCTThHXya.rpc-diff/zcashd-test-2153481-getblocktemplate.json    2022-12-16 13:44:35.092629752 +1000
@@ -1,5 +1,6 @@
 {
   "capabilities": [
+    "proposal"
   ],
   "version": 4,
   "previousblockhash": "00357e387d134477dbcdaa721b51cbdcdfda2ddfd792d71d8d413a0868c1a5be",
@@ -24,9 +25,9 @@
     "sigops": 1,
     "required": true
   },
-  "longpollid": "000215348150723e951671167237000000000000000000",
+  "longpollid": "00357e387d134477dbcdaa721b51cbdcdfda2ddfd792d71d8d413a0868c1a5be287",
   "target": "005fd45000000000000000000000000000000000000000000000000000000000",
-  "mintime": 1671160202,
+  "mintime": 1671161838,
   "mutable": [
     "time",
     "transactions",
@@ -37,6 +38,5 @@
   "sizelimit": 2000000,
   "curtime": 1671162275,
   "bits": "1f5fd450",
-  "height": 2153482,
-  "maxtime": 1671167237
+  "height": 2153482
 }
```

### PR DESCRIPTION
**Pull request by teor2345**
## Motivation

The `min_time` field in the `getblocktemplate` RPC is not being calculated correctly on testnet.

Closes #5871

### Specifications

> On Testnet from block height 299188 onward, the difficulty adjustment algorithm [6](https://zips.z.cash/zip-0208#protocol-diffadjustment) allows minimum-difficulty blocks, as described in [10](https://zips.z.cash/zip-0208#zip-0205), when the block time is greater than a given threshold. This specification changes this threshold to be proportional to the block target spacing.
>
> That is, if the block time of a block at height height ≥ 299188 is greater than 6 · PoWTargetSpacing(height) seconds after that of the preceding block, then the block is a minimum-difficulty block. In that case its nBits field MUST be set to ToCompact(PoWLimit), where PoWLimit is the value defined for Testnet in section [5](https://zips.z.cash/zip-0208#protocol-constants).3 of the Zcash Protocol Specification 5, and ToCompact is as defined in section [7](https://zips.z.cash/zip-0208#protocol-nbits).7.4 of that specification 7.
>
> ...
>
> This change does not affect Mainnet.

https://zips.z.cash/zip-0208#minimum-difficulty-blocks-on-testnet

### Complex Code or Requirements

This is a consensus rule, and the calculations are a bit complex. But it only applies to testnet, so it's less risky.

## Solution

- Use the tip block for the `min_time` calculation (it's actually the first block in reverse order)
- Only adjust times within the min and max range specified by the other consensus rules
- Improve documentation

## Review

Anyone can review this PR.

### Reviewer Checklist

  - [x] Will the PR name make sense to users?
    - [ ] Does it need extra CHANGELOG info? (new features, breaking changes, large changes)
  - [x] Are the PR labels correct?
  - [x] Does the code do what the ticket and PR says?
    - [x] Does it change concurrent code, unsafe code, or consensus rules?
  - [x] How do you know it works? Does it have tests?

### CODE REVIEW

File: zebra-state/src/service/read/difficulty.rs [hunk 1]
```diff
@@ -275,7 +285,8 @@ fn adjust_difficulty_and_time_for_testnet(
     // There is still a small chance that miners will produce an invalid block, if they are
     // just below the max time, and don't check it.
 
-    let previous_block_time = relevant_data.last().expect("has at least one block").1;
+    // The tip is the first relevant data block, because they are in reverse order.
+    let previous_block_time = relevant_data.first().expect("has at least one block").1;
```
Comment (teor2345) [inline zebra-state/src/service/read/difficulty.rs:291]: This is the biggest fix, we need the tip time here.

File: zebra-state/src/service/read/difficulty.rs [hunk 2]
```diff
@@ -308,16 +319,28 @@ fn adjust_difficulty_and_time_for_testnet(
...
+        // Standard difficulty: the cur and max time need to exclude min difficulty blocks
+
+        // The maximum time can only be decreased, and only as far as min_time.
+        // The old minimum is still required by other consensus rules.
+        result.max_time = min(std_difficulty_max_time, result.max_time);
+        result.max_time = max(result.min_time, result.max_time);
+
+        // The current time only needs to be decreased if the max_time decreased past it.
+        // Decreasing the current time can't change the difficulty.
+        result.cur_time = result.cur_time.clamp(result.min_time, result.max_time);
```
Comment (teor2345) [inline zebra-state/src/service/read/difficulty.rs]: These fixes only matter if the last block's time is particularly large or small. (Which can happen, because the other consensus rules use the median time of recent blocks, not the tip block time.)

**Comment by teor2345** [comment]
This fix gives us an exact match with `zcashd`:

```
$ ZCASH_CLI="zcash-cli-testnet" zcash-rpc-diff 38232 getblocktemplate
Checking first node release info...
Checking second node release info...
Connected to zebrad (port 38232) and zcashd (zcash-cli-testnet zcash.conf port).

Checking zebrad network and tip height...
Checking zcashd network and tip height...

Request:
getblocktemplate

Querying zebrad test chain at height >=2180007...

real    0m0.011s
user    0m0.005s
sys     0m0.006s

Querying zcashd test chain at height >=2180007...

real    0m0.023s
user    0m0.007s
sys     0m0.004s


Response diff between zebrad and zcashd:
--- /run/user/1000/tmp.0PycfC3DMm.rpc-diff/zebrad-test-2180007-getblocktemplate.json    2023-01-06 17:50:22.818172323 +1000
+++ /run/user/1000/tmp.0PycfC3DMm.rpc-diff/zcashd-test-2180007-getblocktemplate.json    2023-01-06 17:50:22.841172082 +1000
@@ -1,5 +1,6 @@
 {
   "capabilities": [
+    "proposal"
   ],
   "version": 4,
   "previousblockhash": "002d967dc24ef2ef34eb977fbfd67ef679f4fadf4c8caf84c3ba7d1dc9bf53b2",
@@ -24,7 +25,7 @@
     "sigops": 1,
     "required": true
   },
-  "longpollid": "00021800077623f6ef1672991854000000000000000000",
+  "longpollid": "002d967dc24ef2ef34eb977fbfd67ef679f4fadf4c8caf84c3ba7d1dc9bf53b226534",
   "target": "012bae0000000000000000000000000000000000000000000000000000000000",
   "mintime": 1672991128,
   "mutable": [
@@ -37,6 +38,5 @@
   "sizelimit": 2000000,
   "curtime": 1672991422,
   "bits": "20012bae",
-  "height": 2180008,
-  "maxtime": 1672991854
+  "height": 2180008
 }
```

Proposal is in PR #5870, long polling is allowed to be different, and maxtime is not implemented by `zcashd`.

**Comment by teor2345** [comment]
Same network error as:
https://github.com/ZcashFoundation/zebra/pull/5938#issuecomment-1378201078

**Comment by teor2345** [comment]
@mergifyio update

**Comment by teor2345** [comment]
@arya2 would you mind giving this PR a review some time in the next few days?

File: zebra-state/src/service/read/difficulty.rs [hunk 3]
```diff
@@ -308,16 +319,28 @@ fn adjust_difficulty_and_time_for_testnet(
...
 
     if result.cur_time <= local_std_difficulty_limit {
-        // Standard difficulty: the max time needs to exclude min difficulty blocks
-        result.max_time = std_difficulty_max_time;
+        // Standard difficulty: the cur and max time need to exclude min difficulty blocks
+
+        // The maximum time can only be decreased, and only as far as min_time.
+        // The old minimum is still required by other consensus rules.
+        result.max_time = min(std_difficulty_max_time, result.max_time);
+        result.max_time = max(result.min_time, result.max_time);
```
Comment (arya2) [inline zebra-state/src/service/read/difficulty.rs]: Optional:
```suggestion
        result.max_time = std_difficulty_max_time.clamp(result.min_time, result.max_time);
```

File: zebra-state/src/service/read/difficulty.rs [hunk 4]
```diff
@@ -308,16 +319,28 @@ fn adjust_difficulty_and_time_for_testnet(
...
-        result.min_time = min_difficulty_min_time;
-        if result.cur_time < min_difficulty_min_time {
-            result.cur_time = min_difficulty_min_time;
-        }
+        // Minimum difficulty: the min and cur time need to exclude std difficulty blocks
+
+        // The minimum time can only be increased, and only as far as max_time.
+        // The old maximum is still required by other consensus rules.
+        result.min_time = max(min_difficulty_min_time, result.min_time);
+        result.min_time = min(result.max_time, result.min_time);
```
Comment (arya2) [inline zebra-state/src/service/read/difficulty.rs]: Optional:
```suggestion
        result.min_time = min_difficulty_min_time.clamp(result.min_time, result.max_time);
```

File: zebra-state/src/service/read/difficulty.rs [hunk 5]
```diff
@@ -308,16 +319,28 @@ fn adjust_difficulty_and_time_for_testnet(
         .expect("a valid block time minus a small constant is in-range");
 
     if result.cur_time <= local_std_difficulty_limit {
-        // Standard difficulty: the max time needs to exclude min difficulty blocks
```
Comment (arya2) [inline zebra-state/src/service/read/difficulty.rs:311]: We may want to update this comment a few lines above:
> - if cur_time gets clamped to max_time, this is already a minimum difficulty block.

for when `max_time` from `median_time_past` is behind the `std_difficulty_max_time` from the previous block time.

This wasn't changed in this PR but I thought the condition was `result.cur_time <=  min_difficulty_min_time`, why subtract `POST_BLOSSOM_POW_TARGET_SPACING * 2` from the `std_difficulty_max_time`?

File: zebra-state/src/service/read/difficulty.rs [hunk 6]
```diff
@@ -308,16 +319,28 @@ fn adjust_difficulty_and_time_for_testnet(
...
+        result.min_time = max(min_difficulty_min_time, result.min_time);
+        result.min_time = min(result.max_time, result.min_time);
+
+        // The current time only needs to be increased if the min_time increased past it.
+        result.cur_time = result.cur_time.clamp(result.min_time, result.max_time);
 
-        // And then the difficulty needs to be updated for cur_time
+        // And then the difficulty needs to be updated for cur_time.
         result.expected_difficulty = AdjustedDifficulty::new_from_header_time(
             result.cur_time.into(),
```
Comment (arya2) [inline zebra-state/src/service/read/difficulty.rs:347]: No change needed here but I wonder if we could set the `min_time` to `min_difficulty_min_time` as long as `max_time` is ahead of `std_difficulty_max_time` then use `min_difficulty_min_time` here instead of `cur_time`.

i.e. tell miners to use the minimum difficulty threshold then submit blocks with a timestamp ahead of their local clock.

https://github.com/ZcashFoundation/zebra/blob/691738226938a66c45527c5004b5710a294c6f0d/zebra-state/src/service/check.rs#L101-L106

**Review by arya2 — DISMISSED** [review]
Looks good!

File: zebra-state/src/service/read/difficulty.rs (hunk 3 above)
Comment (teor2345) [reply zebra-state/src/service/read/difficulty.rs]: I'm not sure if this is any easier to understand, maybe I'll need to fix the comments as well?

File: zebra-state/src/service/read/difficulty.rs (hunk 5 above)
Comment (teor2345) [reply zebra-state/src/service/read/difficulty.rs:311]: The miner is going to take approximately ~75 seconds to mine the next block from this template, so there's no point starting a difficult block if we're close to doing an easy one.

I'll make a constant for this.

File: zebra-state/src/service/read/difficulty.rs (hunk 3 above)
Comment (arya2) [reply zebra-state/src/service/read/difficulty.rs]: Maybe `result.max_time.clamp(result.min_time, std_difficulty_max_time);` would match the comment better than that suggestion, but I think the code and comments are clear in any case. `zcashd` uses min/max, either works, I just found it slightly verbose.

File: zebra-state/src/service/read/difficulty.rs (hunk 6 above)
Comment (teor2345) [reply zebra-state/src/service/read/difficulty.rs:347]: > I wonder if we could set the `min_time` to `min_difficulty_min_time` as long as `max_time` is ahead of `std_difficulty_max_time`

You might have already worked this out, but this is almost always true, at least for the first few blocks, or if a node is a minority miner. The `max_time` is 90 minutes ahead of the median, and the `std_difficulty_max_time` is 7.5 minutes ahead of the previous block.

So if we want to test in both modes, we need to support mining both standard and minimum difficulty blocks.

File: zebra-state/src/service/read/difficulty.rs (hunk 5 above)
Comment (teor2345) [reply zebra-state/src/service/read/difficulty.rs:311]: Fixed in 9842f52

**Review by arya2 — APPROVED** [review]

**Comment by teor2345** [comment]
Failed in the merge queue due to a macOS timeout after downloading the Zcash parameters. Maybe we could increase that timeout:
https://github.com/ZcashFoundation/zebra/actions/runs/3932482431/jobs/6725103522

**Comment by teor2345** [comment]
@mergifyio refresh

**Comment by teor2345** [comment]
Failed in the merge queue due to #5958:
https://github.com/ZcashFoundation/zebra/actions/runs/3935154986/jobs/6730584282#step:9:2109

**Comment by teor2345** [comment]
@mergifyio refresh
