### PR TITLE
change(state): Write finalized blocks to the state in a separate thread, to avoid network and RPC hangs

### LINKED ISSUE #5125: Avoid temporary failures verifying the first non-finalized block
## Motivation

Waiting for the last finalized block is currently handled by `can_fork_chain_at()`, which returns early if the tip hash doesn't match any blocks.

https://github.com/ZcashFoundation/zebra/blob/093d503d22894fee57249387f25eb86a5bc8b985/zebra-state/src/service.rs#L378-L381

But it has two bugs: 
- if the first non-finalized block arrives before the last finalized block, it will time out and fail verification, because the fork point is only checked once per block. But it will verify correctly when it gets retried.
- if the syncer reaches the lookahead limit before the last checkpoint verified block is committed, semantically verified blocks in the queue will time out, because it only checks if it's finished committing checkpoint verified blocks when semantically verified blocks are queued.

_Originally posted by @teor2345 in https://github.com/ZcashFoundation/zebra/issues/4937#issuecomment-1241352383_

### Status

We partially fixed this in PR #5257, and added a workaround for the remaining timeouts.

## Tasks

- when receiving a finalized block in the last checkpoint, check for pending non-finalized UTXO requests
- remove the special 5 minute timeout for initial fully verified blocks in `sync:: downloads`

### PR DESCRIPTION
**Pull request by teor2345**
## Motivation

This PR starts moving state block write requests into their own task.
When it is finished, it will make state block writes fully concurrent.

Part of #4937.
Closes #5125.

### Designs

See #4937 and https://docs.google.com/drawings/d/1FXpAUlenDAjl8nkftrypdAPsj0jr-Ut9gZlSP57nuyc/edit

## Solution

Add a block write task:
- Commit finalized blocks to the state in a separate task
- Add last_block_hash_sent to the state service, to avoid database accesses when draining the queue
- Add task handles to check for task exits and panics

Add block write channels:
- Finalized state
- Non-finalized state (not used in this PR)
- Close the finalized block channel when we're finished with it
- Remove a redundant `block_in_place()`

Deal with errors & shutdowns:
- Update last_block_hash_sent regardless of commit errors
- Check for panics in the block write task
- Close state channels and tasks on drop
- Drop channels and check for closed channels in the block commit task
- Work around a RocksDB shutdown bug in the tests, by removing previous code that cancelled RocksDB background work on shutdown
- Drop any leftover queued blocks when finished with the finalized state, and return an error on their channels
- Return an error on the channels of replaced duplicate blocks

Related fixes:
- Wait for the block commit task in tests, and check for errors
- Wait for chain tip updates in the RPC tests
- Improve RPC error logging
- When running a proptest that sleeps a lot, only run it once
- Explain finalized block duplicate handling and consensus rules

Related cleanups:
- Remove some duplicate fields across StateService and ReadStateService
- Rename a field to StateService.max_queued_finalized_height

## Testing

We should run a full sync on this before we merge, and make sure it is not significantly slower than the `main` branch.

## Review

This PR is part of regular scheduled work.

### Reviewer Checklist

  - [ ] Code implements Specs and Designs
  - [ ] Tests for Expected Behaviour
  - [ ] Tests for Errors

## Follow Up Work

Handle non-finalized blocks.
Handle task exits and panics correctly.
Testing.

### CODE REVIEW

**Comment by teor2345** [comment]
I'm running a full sync here:
https://github.com/ZcashFoundation/zebra/actions/runs/3050207033

If the mutex makes us loose too much performance, we might have to add the non-finalized channel to this PR before we merge it.

**Comment by teor2345** [comment]
There are some clippy warnings in some unchanged code:
> changes to closure capture in Rust 2021 will affect drop order

I think they might be solved by PR #5137, otherwise we might just disable them.
(Drop order doesn't matter here, and we are on Rust 2021 edition.)

**Comment by teor2345** [comment]
There are some errors in the tests, I think they might be fixed by moving the non-finalized state to the block commit task.
If not, I can add workarounds.

File: zebra-state/src/service/write.rs [hunk 1]
```diff
@@ -0,0 +1,105 @@
...
+pub fn write_blocks_from_channels(
+    mut finalized_block_write_receiver: tokio::sync::mpsc::UnboundedReceiver<QueuedFinalized>,
+    mut non_finalized_block_write_receiver: tokio::sync::mpsc::UnboundedReceiver<
+        QueuedNonFinalized,
+    >,
+    mut finalized_state: FinalizedState,
+    invalid_block_reset_sender: tokio::sync::mpsc::UnboundedSender<block::Hash>,
+    chain_tip_sender: Arc<Mutex<ChainTipSender>>,
+) {
+    while let Some(ordered_block) = finalized_block_write_receiver.blocking_recv() {
```
Comment (teor2345) [inline zebra-state/src/service/write.rs:34]: Close the other end of this channel when we're done: when we get a CommitBlock that is the child of the last sent hash

File: zebra-state/src/service/write.rs [hunk 2]
```diff
@@ -0,0 +1,105 @@
...
+                 and clearing child blocks in the channel",
+            );
+
+            let send_result =
+                invalid_block_reset_sender.send(finalized_state.db().finalized_tip_hash());
+
+            if send_result.is_err() {
+                info!("StateService closed the block reset channel. Is Zebra shutting down?");
+                return;
+            }
```
Comment (teor2345) [inline zebra-state/src/service/write.rs]: Don't send multiple times - if we do, then we reset even after the state has sent a valid block.

File: zebra-state/src/service/write.rs [hunk 3]
```diff
@@ -0,0 +1,105 @@
...
+                }
+            }
+        }
+    }
+
+    while let Some(_block) = non_finalized_block_write_receiver.blocking_recv() {
+        // TODO:
+        // - read from the channel
+        // - commit blocks to the non-finalized state
+        // - commit blocks to the finalized state
```
Comment (teor2345) [inline zebra-state/src/service/write.rs]:
```suggestion
        // - if there are any ready, commit blocks to the finalized state
```

File: zebra-state/src/service/write.rs [hunk 4]
```diff
@@ -0,0 +1,105 @@
...
+        // - handle errors
```
Comment (teor2345) [inline zebra-state/src/service/write.rs]:
```suggestion
        // - handle errors by sending a reset with all the block hashes in the non-finalized state, and the finalized tip
```

File: zebra-state/src/service/write.rs (hunk 1 above)
Comment (teor2345) [reply zebra-state/src/service/write.rs:34]: Fixed by cbc3d4173b

File: zebra-state/src/service/write.rs (hunk 2 above)
Comment (teor2345) [reply zebra-state/src/service/write.rs]: Fixed by commit 7f87c7a688

**Comment by teor2345** [comment]
Hey @arya2, I tried to change a few parts of the code to get shutdown working, I hope they don't cause too many rebase conflicts!

Edit: seems like shutdown isn't quite working yet

**Comment by teor2345** [comment]
I'm running a full sync here:
https://github.com/ZcashFoundation/zebra/actions/runs/3059036752

**Comment by teor2345** [comment]
I think I fixed the shutdown panics, the solution was "stop trying so hard":
https://github.com/ZcashFoundation/zebra/blob/cd9e2395623a8b5f2c55843f69c472c7558352a2/zebra-state/src/service/finalized_state/disk_db.rs#L714-L715

**Comment by teor2345** [comment]
It seems like there are also some timing issues where the tests don't wait for the block commit task to finish.

For example:
https://github.com/ZcashFoundation/zebra/actions/runs/3065213251/jobs/4949092612#step:14:5326

I'll fix these on Monday.
(They pass on my machine, which is why I think they are a timing issue.)

File: zebra-state/src/service.rs [hunk 5]
```diff
@@ -98,19 +100,67 @@ pub(crate) struct StateService {
...
     pub(crate) disk: FinalizedState,
 
-    /// The non-finalized chain state, including its in-memory chain forks.
-    mem: NonFinalizedState,
+    /// A channel to send blocks to the `block_write_task`,
+    /// so they can be written to the [`NonFinalizedState`].
+    //
+    // TODO: actually send blocks on this channel
+    non_finalized_block_write_sender:
+        Option<tokio::sync::mpsc::UnboundedSender<QueuedNonFinalized>>,
```
Comment (arya2) [inline zebra-state/src/service.rs:136]: I'm just curious, why the tokio channel rather than std?

File: zebra-state/src/service/write.rs [hunk 6]
```diff
@@ -0,0 +1,130 @@
...
+                if send_result.is_err() {
+                    info!("StateService closed the block reset channel. Is Zebra shutting down?");
+                    return;
+                }
+            }
+        }
+    }
+
+    // We're finished receiving finalized blocks from the state.
+    finalized_block_write_receiver.close();
```
Comment (arya2) [inline zebra-state/src/service/write.rs]:
```suggestion
    // We're finished receiving finalized blocks from the state.
```

we should get rid of this since it would only ever reach past the blocking_recv call once the channel is already closed and empty

**Comment by teor2345** [comment]
> I'm running a full sync here: https://github.com/ZcashFoundation/zebra/actions/runs/3059036752

It was about 23 minutes slower than commit 202dc43b11114761068655178d73de144d18d6e0:
https://github.com/ZcashFoundation/zebra/actions/runs/3070874944/jobs/4972408731#step:6:499

This is possibly the `Mutex`, but even if it's not, 20 minutes over 27 hours is within normal performance variations.

File: zebra-state/src/service/finalized_state/disk_db.rs [hunk 7]
```diff
@@ -715,16 +749,24 @@ impl DiskDb {
         let clone_prevention_guard = Arc::get_mut(&mut self.db);
 
         if clone_prevention_guard.is_none() && !force {
```
Comment (arya2) [inline zebra-state/src/service/finalized_state/disk_db.rs]: the `shutdown` method above returns before calling `delete_ephemeral` if `clone_prevention_guard.is_none()` and `force` is false, and that's the only place where `delete_ephemeral` is called.

File: zebra-state/src/service/finalized_state/disk_db.rs [hunk 8]
```diff
@@ -715,16 +749,24 @@ impl DiskDb {
...
-            debug!(
-                "dropping cloned DiskDb, \
-                 but keeping shared database files until the last reference is dropped",
-            );
-
-            return;
+            let path = self.path();
+            if force {
```
Comment (arya2) [inline zebra-state/src/service/finalized_state/disk_db.rs]: the if statement for this block requires `!force`

**Review by arya2 — COMMENTED** [review]
Great work with these changes

File: zebra-state/src/service.rs [hunk 9]
```diff
@@ -249,28 +399,106 @@ impl StateService {
...
+                "already finished committing finalized blocks: dropped duplicate block, \
+                 block is already committed to the state"
+                    .into(),
+            ));
+        }
+
+        if self.queued_finalized_blocks.is_empty() {
+            self.max_queued_finalized_height = f64::NAN;
+        } else if self.max_queued_finalized_height.is_nan()
+            || self.max_queued_finalized_height < queued_height.0 as f64
```
Comment (upbqdn) [inline zebra-state/src/service.rs:461]: I assume we have to do it this way because it wouldn't be easier to deal with NaNs in code that's closer to Grafana. Is that correct?

File: zebra-state/src/service.rs (hunk 5 above)
Comment (teor2345) [reply zebra-state/src/service.rs:136]: `UnboundedSender` and `UnboundedReceiver` have a simpler API that did exactly what I wanted:
https://docs.rs/tokio/latest/tokio/sync/mpsc/struct.UnboundedReceiver.html

I think we could switch if we needed to, let me know if you need a channel method that isn't in `tokio`.

File: zebra-state/src/service/write.rs (hunk 6 above)
Comment (teor2345) [reply zebra-state/src/service/write.rs]: Thanks, fixed in 870fa3fae4

File: zebra-state/src/service/finalized_state/disk_db.rs (hunk 7 above)
Comment (teor2345) [reply zebra-state/src/service/finalized_state/disk_db.rs]: Good catch!

The sole reference check was also more complicated than it needed to be, and it was documented incorrectly.

So I fixed that all up in commit 4e4c186f47

File: zebra-state/src/service/finalized_state/disk_db.rs (hunk 8 above)
Comment (teor2345) [reply zebra-state/src/service/finalized_state/disk_db.rs]: Oops, removed in 048038b3bb

File: zebra-state/src/service/write.rs [hunk 10]
```diff
@@ -0,0 +1,131 @@
...
+        match finalized_state.commit_finalized(ordered_block) {
+            Ok(finalized) => {
+                let tip_block = ChainTipBlock::from(finalized);
+
+                // TODO: update the chain tip sender with non-finalized blocks in this function,
+                //       and get rid of the mutex
+                chain_tip_sender
+                    .lock()
+                    .expect("unexpected panic in block commit task or state")
+                    .set_finalized_tip(tip_block);
```
Comment (teor2345) [inline zebra-state/src/service/write.rs:78]: I think this `Mutex` changes the timing of the tip update, which causes some RPC tests that depend on that exact timing to fail:
- `zebra_rpc::methods::tests::snapshot::test_rpc_response_data`
- `zebra_rpc::methods::tests::vectors::rpc_getaddresstxids_response`
- `zebra_rpc::methods::tests::vectors::rpc_getbestblockhash`

This seems to happen on some test runs on some machines, but not at all on my machine 😭 

Here are the CI failures:
https://github.com/ZcashFoundation/zebra/actions/runs/3065213251/jobs/4949092612#step:14:5326
https://github.com/ZcashFoundation/zebra/actions/runs/3065213251/jobs/4949092612#step:14:5746
https://github.com/ZcashFoundation/zebra/actions/runs/3065213251/jobs/4949092612#step:14:5877
https://github.com/ZcashFoundation/zebra/actions/runs/3065213265/jobs/4949322117#step:3:4483

The fix is to wait for the chain tip update _before_ sending the RPC requests: 55e03969ba0bbef4f3f2bb7fa3569ee2668e038f

File: zebra-state/src/service.rs [hunk 11]
```diff
@@ -271,75 +399,104 @@ impl StateService {
...
             "state.checkpoint.queued.block.count",
             self.queued_finalized_blocks.len() as f64,
         );
 
-        highest_queue_commit
+        rsp_rx
+    }
+
+    /// Finds queued finalized blocks to be committed to the state in order,
+    /// remove them from the queue, and sends them to the block commit task.
```
Comment (upbqdn) [inline zebra-state/src/service.rs]:
```suggestion
    /// removes them from the queue, and sends them to the block commit task.
```

File: zebra-state/src/service/write.rs [hunk 12]
```diff
@@ -0,0 +1,131 @@
...
+
+use zebra_chain::block::{self, Height};
+
+use crate::service::{
+    finalized_state::FinalizedState,
+    queued_blocks::{QueuedFinalized, QueuedNonFinalized},
+    ChainTipBlock, ChainTipSender,
+};
+
+/// Reads blocks from the channels, write them to the `finalized_state`,
```
Comment (upbqdn) [inline zebra-state/src/service/write.rs]:
```suggestion
/// Reads blocks from the channels, writes them to the `finalized_state`,
```

File: zebra-state/src/service/write.rs [hunk 13]
```diff
@@ -0,0 +1,131 @@
...
+/// and updates the
```
Comment (upbqdn) [inline zebra-state/src/service/write.rs]:
```suggestion
/// and updates the `chain_tip_sender`.
```

File: zebra-state/src/service/write.rs [hunk 14]
```diff
@@ -0,0 +1,131 @@
...
+    // until the state closes the finalized block channel's sender.
+    while let Some(ordered_block) = finalized_block_write_receiver.blocking_recv() {
+        // TODO: split these checks into separate functions
+
+        if invalid_block_reset_sender.is_closed() {
+            info!("StateService closed the block reset channel. Is Zebra shutting down?");
+            return;
+        }
+
+        // Discard any children of invalid blocks in the channel
```
Comment (upbqdn) [inline zebra-state/src/service/write.rs:42]: Are we actually discarding anything here?

File: zebra-state/src/service/tests.rs [hunk 15]
```diff
@@ -515,6 +468,80 @@ proptest! {
     }
 }
 
+// This test sleeps for every block, so we only ever want to run it once
```
Comment (upbqdn) [inline zebra-state/src/service/tests.rs:474]: How is it possible that the test would be run multiple times if we didn't wrap it into `proptest`?

File: zebra-state/src/service/write.rs (hunk 10 above)
Comment (teor2345) [reply zebra-state/src/service/write.rs:78]: This seems to be causing test hangs, I'll see what I can do.

Comment (teor2345) [reply zebra-state/src/service/write.rs:78]: I fixed this by adding a timeout in 770f73a76e

File: zebra-state/src/service.rs [hunk 16]
```diff
@@ -716,14 +924,13 @@ impl Service<Request> for StateService {
...
-                // and written to disk.
-                //
-                // See the note in `CommitBlock` for more details.
-                let span = Span::current();
-                let rsp_rx = tokio::task::block_in_place(move || {
-                    span.in_scope(|| self.queue_and_commit_finalized(finalized))
-                });
+                // This method doesn't block, access the database, or perform CPU-intensive tasks,
+                // so we can run it directly in the tokio executor's Future threads.
+                let rsp_rx = self.queue_and_commit_finalized(finalized);
```
Comment (teor2345) [inline zebra-state/src/service.rs:969]: I removed this redundant `block_in_place()` in 619caef95b.

File: zebra-state/src/service/arbitrary.rs [hunk 17]
```diff
@@ -209,7 +213,24 @@ pub async fn populated_state(
...
-        rsp.expect("blocks should commit just fine");
+        // Wait for the block result and the chain tip update,
+        // which both happen in a separate thread from this one.
+        rsp.expect("unexpected block commit failure");
+
+        // Allow the chain tip update
+        if let Err(timeout_error) = timeout(
+            CHAIN_TIP_UPDATE_WAIT_LIMIT,
+            chain_tip_change.wait_for_tip_change(),
+        )
```
Comment (teor2345) [inline zebra-state/src/service/arbitrary.rs:224]: I added this wait for tip change and timeout to fix test concurrency bugs in b890114eb4f8470a4c6b0d741d718167f894d531 and 770f73a76e28f826d7d8d34499e193cffb0eec9b.

File: zebra-state/src/service.rs (hunk 9 above)
Comment (teor2345) [reply zebra-state/src/service.rs:461]: `NaN`s show up as empty graphs, which is what we want when the code is empty.

File: zebra-state/src/service/write.rs [hunk 18]
```diff
@@ -0,0 +1,131 @@
...
+            debug!(
+                ?next_valid_height,
+                invalid_height = ?ordered_block.0.height,
+                invalid_hash = ?ordered_block.0.hash,
+                "got a block that was too high. \
+                 Assuming a parent block failed, and dropping this block",
+            );
+
+            // We don't want to send a reset here, because it could overwrite a valid sent hash
+        }
```
Comment (teor2345) [inline zebra-state/src/service/write.rs:66]: We need to drop the block here, and skip committing the block:
```suggestion
            std::mem::drop(ordered_block);
            continue;
        }
```

File: zebra-state/src/service/write.rs [hunk 19]
```diff
@@ -44,17 +44,11 @@ pub fn write_blocks_from_channels(
                 ?next_valid_height,
```
Comment (teor2345) [inline zebra-state/src/service/write.rs:56]: ^ Add a comment:
> `commit_finalized()` requires that we commit blocks in height order.
> If there has been a block commit error, we need to drop all the children of that block.

File: zebra-state/src/service/tests.rs (hunk 15 above)
Comment (teor2345) [reply zebra-state/src/service/tests.rs:474]: It was moved from one proptest block to another.

File: zebra-state/src/service/write.rs (hunk 14 above)
Comment (teor2345) [reply zebra-state/src/service/write.rs:42]: Oops!

File: zebra-state/src/service.rs [hunk 20]
```diff
@@ -191,6 +236,59 @@ pub struct ReadStateService {
...
+    /// Used to check for panics when writing blocks.
+    block_write_task: Option<Arc<std::thread::JoinHandle<()>>>,
+}
+
+impl Drop for StateService {
+    fn drop(&mut self) {
+        // The state service owns the state, tasks, and channels,
+        // so dropping it should shut down everything.
+
+        // Close the channels (non-blocking)
```
Comment (teor2345) [inline zebra-state/src/service.rs:252]:
```suggestion
        // Close the channels (non-blocking)
        // This makes the block write thread exit the next time it checks the channels.
        // We want to do this here so we get any errors or panics from the block write task before it shuts down.
```

File: zebra-state/src/service/write.rs (hunk 19 above)
Comment (teor2345) [reply zebra-state/src/service/write.rs:56]: Done in 72ddbe3d0

**Comment by teor2345** [comment]
Seems like we might have one final test timing issue on macOS 😭 

`mempool_cancel_downloads_after_network_upgrade` failed with:
> Message:  Test failed: assertion failed: `(left == right)`
>   left: `Some(Instant { t: 2398753679665 })`,
>  right: `None`: an already-evicted transaction should not be evicted again; minimal failing input: txid = Legacy(transaction::Hash("0000000000000000000000000000000000000000000000000000000000000000"))

https://github.com/ZcashFoundation/zebra/actions/runs/3094459231/jobs/5007860660#step:14:59341

I'll see if there is a quick fix tomorrow, otherwise I'll just disable this test on macOS.
(It's a second-tier support platform without guaranteed tests.)

**Comment by teor2345** [comment]
I made these changes:
- wait for chain tip updates in a failing macOS test
- drop duplicate and leftover blocks, and send errors for dropped blocks
- update CommitFinalizedBlock documentation

**Comment by teor2345** [comment]
Google Cloud ssh failure #5069:
> kex_exchange_identification: Connection closed by remote host

https://github.com/ZcashFoundation/zebra/actions/runs/3109728269/jobs/5041009873#step:6:105

**Comment by teor2345** [comment]
Failure in inbound_block_height_lookahead_limit, looks like another block out of sequence thing:

> Message:  assertion failed: `(left == right)`
>   left: `AdvertiseBlock(block::Hash("00040fe8ec8471911baa1db1266ea15dd06b4a8a5c453883c000b031973dce08"))`,
>  right: `AdvertiseBlock(block::Hash("0007bc227e1c57a4a70e237cad00e7b7ce565155ab49166bc57397a26d339283"))`: received an unexpected request
>  in zebra_test::mock_service::MockService<zebra_network::protocol::internal::request::Request, zebra_network::protocol::internal::response::Response, zebra_test::mock_service::PanicAssertion, alloc::boxed::Box<dyn std::error::Error+core::marker::Sync+core::marker::Send>>

https://github.com/ZcashFoundation/zebra/actions/runs/3109728269/jobs/5041101430#step:3:8517

**Comment by teor2345** [comment]
> Failure in inbound_block_height_lookahead_limit, looks like another block out of sequence thing:

I think I fixed it.

**Comment by arya2** [comment]
> Failure in inbound_block_height_lookahead_limit, looks like another block out of sequence thing:

The same failure happened in mempool_advertise_transaction_ids, which passed in the previous run

> Message:  assertion failed: `(left == right)`
>   left: `AdvertiseBlock(block::Hash("00040fe8ec8471911baa1db1266ea15dd06b4a8a5c453883c000b031973dce08"))`,
>  right: `AdvertiseBlock(block::Hash("0007bc227e1c57a4a70e237cad00e7b7ce565155ab49166bc57397a26d339283"))`: received an unexpected request
>  in zebra_test::mock_service::MockService<zebra_network::protocol::internal::request::Request, zebra_network::protocol::internal::response::Response, zebra_test::mock_service::PanicAssertion, alloc::boxed::Box<dyn std::error::Error+core::marker::Sync+core::marker::Send>>

https://github.com/ZcashFoundation/zebra/actions/runs/3110257397/jobs/5041556025#step:3:8863

**Comment by teor2345** [comment]
> > Failure in inbound_block_height_lookahead_limit, looks like another block out of sequence thing:
> 
> The same failure happened in mempool_advertise_transaction_ids, which passed in the previous run

Seems like the problem is in `setup()`, I tried to fix it in aef47858d4.

**Comment by teor2345** [comment]
Looks like this all works, apart from the Rust bug fixed by PR #5251

**Comment by upbqdn** [comment]
@mergifyio update

**Comment by teor2345** [comment]
I need to call `clear_finalized_block_queue()` in the `Drop` impl, and instead of `self.queued_finalized_blocks.clear()` when we finish committing finalized blocks.

**Comment by teor2345** [comment]
CI failed due to #5044

**Comment by teor2345** [comment]
I'd also like to remove `Clone` from `NonFinalizedState`, because it doesn't work the same way as `FinalizedState.clone()`.

**Comment by teor2345** [comment]
> I'd also like to remove `Clone` from `NonFinalizedState`, because it doesn't work the same way as `FinalizedState.clone()`.

That's not possible, so I just updated the docs.

File: zebrad/tests/common/lightwalletd/send_transaction_test.rs [hunk 21]
```diff
@@ -176,8 +176,13 @@ pub async fn run() -> Result<()> {
         assert_eq!(response, expected_response);
     }
 
-    tracing::info!("waiting for mempool to verify some transactions...");
-    zebrad.expect_stdout_line_matches("sending mempool transaction broadcast")?;
+    // The timing of verification logs are unrealiable, so we've disabled this check for now.
```
Comment (arya2) [inline zebrad/tests/common/lightwalletd/send_transaction_test.rs:179]: Not at all important.

```suggestion
    // The timing of verification logs are unreliable, so we've disabled this check for now.
```

**Review by arya2 — DISMISSED** [review]
Excellent.

File: zebrad/tests/common/lightwalletd/send_transaction_test.rs (hunk 21 above)
Comment (arya2) [inline zebrad/tests/common/lightwalletd/send_transaction_test.rs:179]: Not at all important so I'll update this in the following PR

```suggestion
    // The timing of verification logs are unreliable, so we've disabled this check for now.
```

File: zebra-state/src/service/finalized_state.rs [hunk 22]
```diff
@@ -171,21 +163,23 @@ impl FinalizedState {
...
         };
 
-        let _ = rsp_tx.send(result.map_err(Into::into));
+        // Some io errors can't be cloned, so we format them instead.
+        let owned_result = result
+            .as_ref()
+            .map(|_hash| finalized)
+            .map_err(|error| format!("{:?}", error).into());
+
+        let _ = rsp_tx.send(result);
```
Comment (upbqdn) [inline zebra-state/src/service/finalized_state.rs:180]: Could we swap these two statements, and return the adjusted result directly?

**Review by upbqdn — DISMISSED** [review]
Looks great. I left one minor q.

File: zebra-state/src/service/write.rs [hunk 23]
```diff
@@ -0,0 +1,138 @@
...
+        // So if there has been a block commit error,
+        // we need to drop all the descendants of that block,
+        // until we receive a block at the required next height.
+        let next_valid_height = finalized_state
+            .db
+            .finalized_tip_height()
+            .map(|height| (height + 1).expect("committed heights are valid"))
+            .unwrap_or(Height(0));
+
+        if ordered_block.0.height > next_valid_height {
```
Comment (upbqdn) [inline zebra-state/src/service/write.rs]: Could it happen that we attempt to commit a block with a height lower than `next_valid_height`? In that case, we would need
```suggestion
        if ordered_block.0.height != next_valid_height {
```

File: zebra-state/src/service/finalized_state.rs (hunk 22 above)
Comment (teor2345) [reply zebra-state/src/service/finalized_state.rs:180]: `send()` takes ownership of the Result, and the error isn't cloneable, so we have to format the error before we send it to two different places.

File: zebra-state/src/service/write.rs [hunk 24]
```diff
@@ -0,0 +1,138 @@
...
+            debug!(
+                ?next_valid_height,
+                invalid_height = ?ordered_block.0.height,
+                invalid_hash = ?ordered_block.0.hash,
+                "got a block that was too high. \
```
Comment (teor2345) [inline zebra-state/src/service/write.rs]:
```suggestion
                "got a block that was the wrong height. \
```

File: zebra-state/src/service/write.rs (hunk 23 above)
Comment (teor2345) [reply zebra-state/src/service/write.rs]: You're right, we should use the same check as `commit_finalized()` does.

**Comment by teor2345** [comment]
One last fix to the block height check in b150e3f, and I think we're done.

File: zebra-state/src/service/finalized_state.rs (hunk 22 above)
Comment (upbqdn) [reply zebra-state/src/service/finalized_state.rs:180]: This should have been obvious to me. Sorry.

**Review by upbqdn — APPROVED** [review]

File: zebra-state/src/service/finalized_state.rs (hunk 22 above)
Comment (teor2345) [reply zebra-state/src/service/finalized_state.rs:180]: > This should have been obvious to me. Sorry.

No worries, it's not obvious in the code, it trips me up all the time!
