### PR TITLE
network: fix invariant violation in peer set

### LINKED ISSUE #1183: Panic: preselected index must be valid in peer_set
**Version**

zebrad main branch, 19 October 2020.

**Platform**

`Linux ... 5.4.68 #1-NixOS SMP Sat Sep 26 16:03:16 UTC 2020 x86_64 GNU/Linux`

**Description**

While syncing testnet blocks, `zebrad` panicked with a "preselected index must be valid" error in `peer_set::set`, inside the span `zebrad::components::sync::obtain_tips`.

I tried this:

Syncing testnet from genesis.

I expected to see this happen:

A successful sync.

Instead, this happened:

A tip exhaustion cycle, followed by a `zebra-network` panic.

## Error
```
preselected index must be valid
```

## Metadata
|key|value|
|--|--|
|**version**|3.0.0-alpha.0|
|**location**|/home/dev/zebra-revhex/zebra-network/src/peer_set/set.rs:381:22|

## SpanTrace

<details>

```
SpanTrace:
   0: zebrad::components::sync::obtain_tips
             at zebrad/src/components/sync.rs:314
   1: zebrad::components::sync::sync
             at zebrad/src/components/sync.rs:169
```
</details>

### PR DESCRIPTION
**Pull request by hdevalence**
Closes #1183.

The peer set maintains a preselected ready service that it can use to
perform power-of-two-choices (p2c) routing of requests.  Ready services
are stored by key (socket address) in an `IndexMap`, and the preselected
service is represented by an `Option<usize>` indexing that map.  This
means that whenever the set of ready services changes (e.g., a service
is removed from the peer set, or a service is taken to be used to
process a request), the preselected index is invalidated.  The original
P2C-only implementation maintained this invariant but did not document
it.

The change to inventory-based routing introduced a bug by failing to
maintain this invariant and appropriately invalidate the preselected
index.  However, this was only noticeable approximately 1/N of the time
on the next request after an inventory-directed request, so the bug
occurred infrequently.  Luckily, the use of `.expect` caused the bug to
be an immediate panic, making it possible to identify by inspecting all
uses of the ready service map.

The second commit in the PR tidies the code as a cleanup, but is kept
separate to be able to pinpoint the bugfix.

### CODE REVIEW

File: zebra-network/src/peer_set/set.rs [hunk 1]
```diff
@@ -234,20 +183,82 @@ where
...
+            // No Heisenservices: they must be ready or unready.
+            assert!(!self.cancel_handles.contains_key(&key));
+            Some((key, svc))
+        } else {
+            None
+        }
+    }
+
+    fn remove(&mut self, key: &D::Key) {
+        if let Some(_) = self.take_ready_service(key) {
```
Comment (teor2345) [inline zebra-network/src/peer_set/set.rs]: Placate clippy
```suggestion
        if self.take_ready_service(key).is_some() {
```

**Review by teor2345 — APPROVED** [review]
Looks good to me, lets merge once CI passes.
