### PR TITLE
fix(rpc): Refactor the cookie-based RPC authentication

### LINKED ISSUE #8864: Protect the Zebra RPC endpoint
The Zebra RPC endpoint is currently unencrypted and accessible by anyone who knows the address and port. While the current recommendation is to restrict access to localhost or a trusted local network, there are cases where the endpoint needs to be open to the internet in production environments.

Implement one of the following authentication methods:

- Basic HTTP Authentication: This method would require users to provide a username and password when connecting to the RPC endpoint.
- Cookie-based Authentication: Similar to Zcashd, this method uses a randomly generated cookie stored on the file system to authenticate RPC connections.

We could implement just one of these methods or explore alternative solutions.  

Authentication should be enabled by default but turning it off should be an option for testing purposes and setups where the endpoint is restricted to localhost or a private network.

Encryption of RPC traffic (for example using TLS) is not part of this ticket but might be considered in the future.

### PR DESCRIPTION
**Pull request by upbqdn**
## Motivation

Resolve https://github.com/ZcashFoundation/zebra/pull/8900#discussion_r1801089575 and https://github.com/ZcashFoundation/zebra/pull/8900#discussion_r1801090790.

## Solution

- Don't read the cookie from the disk at all.
- Use a path to the cookie file when removing it.
- Rename `FixHttpRequestMiddleware` to `HttpRequestMiddleware` since it doesn't contain only fixes anymore but also serves as an authentication layer.

### Tests

No new tests.

### PR Author's Checklist

- [x] The PR name is suitable for the change log.
- [ ] The solution is tested.
- [x] The PR has a priority label.

### PR Reviewer's Checklist

- [ ] The PR resolves the issue.

### CODE REVIEW

File: zebra-rpc/src/server.rs [hunk 1]
```diff
@@ -280,32 +286,37 @@ impl RpcServer {
...
-    fn shutdown_blocking_inner(close_handle: CloseHandle) {
+    fn shutdown_blocking_inner(close_handle: CloseHandle, config: Config) {
         // The server is a blocking task, so it can't run inside a tokio thread.
         // See the note at wait_on_server.
         let span = Span::current();
         let wait_on_shutdown = move || {
             span.in_scope(|| {
+                if config.enable_cookie_auth {
+                    cookie::remove_from_disk(&config.cookie_dir)
+                        .expect("Zebra must be able to remove the auth cookie from the disk");
```
Comment (arya2) [inline zebra-rpc/src/server.rs]: It doesn't seem too important to remove the cookie file at shutdown, it should still work as expected when Zebra is restarted, so it seems better to try logging a warning here instead, at least for release builds.

We could also always skip removing the cookie and overwrite it at startup instead.

```suggestion
                    if let Err(err) = cookie::remove_from_disk(&config.cookie_dir) {
                        warn!(
                            ?err,
                            "unexpectedly could not remove the rpc auth cookie from the disk"
                        )
                    }
```

File: zebra-rpc/src/server/cookie.rs [hunk 2]
```diff
@@ -6,43 +6,47 @@ use rand::RngCore;
...
 }
 
-/// Get the encoded password from the auth cookie.
-pub fn get(cookie_dir: PathBuf) -> Result<String> {
-    let mut file = File::open(cookie_dir.join(COOKIEAUTH_FILE))?;
-    let mut contents = String::new();
-    file.read_to_string(&mut contents)?;
+/// Writes the given cookie to the given dir.
+pub fn write_to_disk(cookie: &Cookie, dir: &Path) -> Result<()> {
+    File::create(dir.join(FILE))?.write_all(format!("__cookie__:{}", cookie.0).as_bytes())?;
```
Comment (arya2) [inline zebra-rpc/src/server/cookie.rs:40]:
```suggestion
    // Create the directory if needed.
    std::fs::create_dir_all(&dir)?;
    File::create(dir.join(FILE))?.write_all(format!("__cookie__:{}", cookie.0).as_bytes())?;
```

File: zebra-rpc/src/server/http_request_compatibility.rs [hunk 3]
```diff
@@ -9,38 +9,58 @@ use jsonrpc_http_server::{
...
+#[derive(Clone, Debug, Default)]
+pub struct HttpRequestMiddleware {
+    cookie: Option<Cookie>,
+}
+
+/// A trait for updating an object, consuming it and returning the updated version.
+pub trait With<T> {
+    /// Updates `self` with an instance of type `T` and returns the updated version of `self`.
+    fn with(self, _: T) -> Self;
+}
```
Comment (arya2) [inline zebra-rpc/src/server/http_request_compatibility.rs:54]: This looks great, good idea! 

Optional: This could be useful elsewhere in Zebra as well, such as in the `testnet::ParametersBuilder`, so it might fit better in `zebra-chain`, but it could also be moved in whenever we try implementing it for other structs.

**Review by arya2 — COMMENTED** [review]
Thank you! This is an excellent refactor, it fixes the issues mentioned in the PR description, and the new `With` trait looks like it'll be very useful later/elsewhere in Zebra (I'm looking forward to using it in the `parameters::network::testnet` module).

File: zebra-rpc/src/server/http_request_compatibility.rs (hunk 3 above)
Comment (upbqdn) [reply zebra-rpc/src/server/http_request_compatibility.rs:54]: I'm glad you like it. :) It pretty much randomly occurred to me to do it this way. It seems to go well with something like `let foo = if cond1 {Foo::...with(...)} else if cond2 {Foo::...with(...)} else {Foo::...with(...)}`.

Yea, let's move it somewhere else if we're using it in other places.

**Review by oxarbitrage — APPROVED** [review]
Looks really good and it works. Thanks for the refactor!

File: zebra-rpc/src/server/http_request_compatibility.rs (hunk 3 above)
Comment (upbqdn) [reply zebra-rpc/src/server/http_request_compatibility.rs:54]: We could maybe add a macro which could take an arbitrary number of arguments: `...with!(a, b, c)`.
