### PR TITLE
fix tracing configuration issues

### LINKED ISSUE #98: Have the tracing component actually use the config settings.
Currently you can set a tracing filter in the config but this is never actually used by the tracing component, which always uses `RUST_LOG`.  We should probably use the config value instead of the environment variable.

### LINKED ISSUE #399: fix `zebrad config > zebrad.toml` when zebrad.toml doesn't already exist
`zebrad` is currently setup so that it can run without a config, but if the config is exists there are required fields. This causes issues when trying to create a config file. Running `cargo run -- config > zebrad.config` in `zebra/zebrad` causes the OS to immediately create an empty file to store the output of the command, but the output happens _after_ the application attempts to load the config file. This causes the application to immediately exit with an error because it is unable to parse the empty file as a config file.

To fix this we should make the behavior consistent whether or not you have a config file. An empty config file should result in the same behavior as an absent one, which means we want to make whatever fields it requires when a config exists optional.

### PR DESCRIPTION
**Pull request by yaahc**
Prior to this change the configuration options for tracing were controlled exclusively by the `tracing_config` function in `ZebraApp`. This resulted in it ignoring all configuration options other than `--verbose` and more recently `ZEBRAD_LOG`. Notably, this function is called before the `ZebraConfig` is ever loaded, so it is impossible to consider the config filter level when initializing the tracing component.

To fix this, we have the new `ZebraApp::level` fn take the `command` as input, so it can prioritize the settings correctly. Then we call this function in `tracing_config` when the Config is `None`, giving us an initial config, then we call it again in `after_config` when the Config has been loaded and use that to reload the filter. This change requires a breaking change in the `Abscissa` API to pass the `command` along with the `config` in `after_config` so they can both be referenced when setting the final level.

fixes https://github.com/ZcashFoundation/zebra/issues/98
fixes https://github.com/ZcashFoundation/zebra/issues/399

### CODE REVIEW

**Comment by yaahc** [comment]
Because this change requires a breaking change to the API of abscissa I'm going to take this opportunity to also fix the Tracing component in abscissa so that it takes a user provided subscriber instead of always setting up its own default subscriber, that way we can setup layers like `tracing-error` and `tracing-flame`.

**Comment by hdevalence** [comment]
@yaahc Just to confirm, the relevant changes to abscissa are here, correct:

https://github.com/iqlusioninc/abscissa/compare/develop...yaahc:develop

**Comment by yaahc** [comment]
> @yaahc Just to confirm, the relevant changes to abscissa are here, correct:
> 
> [iqlusioninc/abscissa@develop...yaahc:develop](https://github.com/iqlusioninc/abscissa/compare/develop...yaahc:develop)

Yup, the last line in that diff is some cruft that snuck in from earlier messing with error handling stuff but the rest of it is all the relevant stuff.

File: zebrad/src/config.rs [hunk 1]
```diff
@@ -15,11 +15,11 @@ use zebra_network::Config as NetworkSection;
...
 pub struct ZebradConfig {
     /// Tracing configuration
-    pub tracing: TracingSection,
+    pub tracing: Option<TracingSection>,
     /// Networking configuration
-    pub network: NetworkSection,
+    pub network: Option<NetworkSection>,
     /// Metrics configuration
-    pub metrics: MetricsSection,
+    pub metrics: Option<MetricsSection>,
```
Comment (hdevalence) [inline zebrad/src/config.rs]: Making these `Option`s is motivated by the empty-config problem, right? I don't think they should be optional.  What is someone supposed to do if the field is missing?

Comment (yaahc) [reply zebrad/src/config.rs]: Yea, that and the fact that if nothing is optional I cannot tell if the `config.tracing.filter` value was provided by an actual config file or just the default settings. I think the latter issue means these have to be optional, but I think theres still an issue where if you have the header for one of these sections present then all the values in that section become required again.

I don't think this is the right solution but I think this is strictly better than the current situation. What do you think about merging this and opening an issue to rework all the config stuff to support all partial configs.

Comment (hdevalence) [reply zebrad/src/config.rs]: Why do we need to check whether the `filter` value is a default setting? So that we know whether it should take priority over an environment variable?  Did we decide whether we wanted env variables to override it or vice versa?

If the config variable is supposed to override the env variables, then I think we should make `config.tracing.filter` optional, so that it has semantic meaning (`Some` is an explicit preference, `None` is use the env variable).  My preference would be to not merge this, since I think it will force a lot of code to have to deal with fallibilty that shouldn't have to.

Comment (yaahc) [reply zebrad/src/config.rs:22]: The env variable part is pretty easy to resolve but I figured we should also have the `--verbose` cli flag take priority over it and theres no way to reference that in the `Default` impl for TracingSection

File: Cargo.toml [hunk 2]
```diff
@@ -15,4 +15,7 @@ members = [
 panic = "abort"
 
 [profile.release]
-panic = "abort"
\ No newline at end of file
+panic = "abort"
+
+[patch.crates-io]
+abscissa_core = { git = "https://github.com/yaahc/abscissa.git", branch = "develop" }
```
Comment (dconnolly) [inline Cargo.toml:21]: If the upsteam is not expected to merge quickly, perhaps make an issue to track 'point to the inqlusion version when available'

**Review by dconnolly — APPROVED** [review]
🚚

File: Cargo.toml (hunk 2 above)
Comment (tony-iqlusion) [reply Cargo.toml:21]: FYI, we'd be happy to merge these changes upstream. Please open a PR.

Comment (yaahc) [reply Cargo.toml:21]: I plan to but I figured if we're gonna make a breaking change we should be sure that all the breaking changes are done at once, still thinking about changes to error handling.
