### PR TITLE
Make ZcashSerialize infallible mod its Writer.

### LINKED ISSUE #158: What should the error type for `ZcashSerialize` be?
The `ZcashDeserialize` trait has a single method:
```rust
fn zcash_deserialize<R: io::Read>(reader: R) -> Result<Self, SerializationError>;
```
This method must return a `Result`, because deserialization can fail, and this `Result` must have an error type that can include at least failures from the underlying `io::Read` as well as problems like parse errors.

The `ZcashSerialize` trait also has a single method:

```rust
fn zcash_serialize<W: io::Write>(&self, writer: W) -> Result<(), SerializationError>;
```

However, while this method must also return a `Result`, because the `io::Write` methods are fallible, it does not have the same constraint that the `Result`'s error type must (always) be able to represent other errors, and in fact there are places where we explicitly rely on serialization being infallible except for a failure of the underlying `writer`.

For instance, we implement object hashes like `TransactionHash` by serializing a `Transaction` into a `Sha256dWriter` to produce the hash, and then unwrapping the result, relying on the facts that:

1. the `ZcashSerialize` implementation for `Transaction` is infallible and can only produce an `io::Error` from the underlying writer;
2. the `Sha256dWriter` is infallible and never produces an `io::Error`.

Together (1) and (2) imply that computing a transaction hash is infallible, and similar logic is used for other hash types.  However, (2) is a much more reasonable property than (1) to maintain going forward, since it only involves a small amount of code in the writer, and it would be good to bring the type checker to bear on (1), rather than just trying to maintain that property ourselves.

There are two possible solutions I can think of:

1. Simply change `zcash_serialize` to return `Result<(), io::Error>`, declaring that *every* object which can be serialized in Zcash format *must* always be valid, so that serialization is always infallible (up to the underlying writer);

2. Change `ZcashSerialize` to have an associated `Error` type, which could be `io::Error` (meaning serialization is infallible) or something else (meaning it isn't). This allows the possibility of fallible serialization but means that the trait becomes more complicated, and it may require more complex `where` bounds downstream to make sure that the error types line up.

### PR DESCRIPTION
**Pull request by hdevalence**
Closes #158.

As discussed on the issue, this makes it possible to safely serialize
data into hashes, and encourages serializable data to make illegal
states unrepresentable.

### CODE REVIEW

**Comment by hdevalence** [comment]
This is another PR like the clippy one that makes minor changes but touches a wide part of the source tree; in particular it probably conflicts with work on #220 #219 #218 #195

File: zebra-chain/src/serialization.rs [hunk 1]
```diff
@@ -37,7 +37,12 @@ pub trait ZcashSerialize: Sized {
     /// This function has a `zcash_` prefix to alert the reader that the
     /// serialization in use is consensus-critical serialization, rather than
     /// some other kind of serialization.
-    fn zcash_serialize<W: io::Write>(&self, writer: W) -> Result<(), SerializationError>;
+    ///
+    /// Notice that the error type is [`std::io::Error`]; this indicates that
```
Comment (dconnolly) [inline zebra-chain/src/serialization.rs:41]: :+1:

**Review by dconnolly — APPROVED** [review]
:boat:
