### PR TITLE
fix(state): Restore initial sync performance by avoiding RocksDB merge operations when the on-disk database format is up-to-date

### LINKED ISSUE #9939: Performance regression in initial sync
PR #9539 seems to have introduced a performance regression in the initial sync. I ran fresh `zebrad` instances connected only to another, synced instance on localhost on Mainnet, and got these results:

```
first 10_000 blocks, commit: cfabd6bca606a330c2312f701ccc27680e5b0a40
________________________________________________________
Executed in   16.94 secs    fish           external
   usr time   15.84 secs    0.00 micros   15.84 secs
   sys time    1.07 secs  588.00 micros    1.07 secs
________________________________________________________
Executed in   22.35 secs    fish           external
   usr time   15.00 secs  549.00 micros   15.00 secs
   sys time    0.95 secs  247.00 micros    0.95 secs
________________________________________________________
Executed in   13.54 secs    fish           external
   usr time   15.90 secs  904.00 micros   15.90 secs
   sys time    1.01 secs    0.00 micros    1.01 secs

first 40_000 blocks, commit: cfabd6bca606a330c2312f701ccc27680e5b0a40
   ________________________________________________________
Executed in   80.11 secs    fish           external
   usr time  110.97 secs  581.00 micros  110.96 secs
   sys time    4.53 secs    0.00 micros    4.53 secs
________________________________________________________
Executed in   87.23 secs    fish           external
   usr time  111.25 secs  597.00 micros  111.25 secs
   sys time    4.48 secs  265.00 micros    4.48 secs
________________________________________________________
Executed in   86.10 secs    fish           external
   usr time  117.52 secs  609.00 micros  117.52 secs
   sys time    4.50 secs  273.00 micros    4.50 secs

=====================================================================

first 10_000 blocks, commit: 819aadb30cdf92b32470692af619dd0aff769107
________________________________________________________
Executed in   31.00 secs    fish           external
   usr time   33.67 secs   40.00 micros   33.67 secs
   sys time    1.09 secs  597.00 micros    1.09 secs
________________________________________________________
Executed in   34.01 secs    fish           external
   usr time   37.63 secs  223.00 micros   37.63 secs
   sys time    1.33 secs  653.00 micros    1.33 secs
________________________________________________________
Executed in   34.07 secs    fish           external
   usr time   34.58 secs  453.00 micros   34.58 secs
   sys time    1.09 secs  209.00 micros    1.09 secs

first 40_000 blocks, commit: 819aadb30cdf92b32470692af619dd0aff769107
________________________________________________________
Executed in  283.29 secs    fish           external
   usr time  320.30 secs  562.00 micros  320.30 secs
   sys time    4.93 secs  265.00 micros    4.93 secs
________________________________________________________
Executed in  283.67 secs    fish           external
   usr time  321.51 secs  482.00 micros  321.51 secs
   sys time    5.05 secs  225.00 micros    5.05 secs
________________________________________________________
Executed in  285.97 secs    fish           external
   usr time  324.43 secs  756.00 micros  324.43 secs
   sys time    5.43 secs  371.00 micros    5.42 secs
```

- Both commits are from #9539.
- Commit cfabd6bca606a330c2312f701ccc27680e5b0a40 is the last one that doesn't contain the regression.
- Commit 819aadb30cdf92b32470692af619dd0aff769107 contains the regression, but doesn't introduce it. I used it because it's the first one that contains the regression and compiles. The one that introduces the regression is 8f32bebc8cc0004f5d1dd7637b681e7c953f62a7, but doesn't compile.

### PR DESCRIPTION
**Pull request by arya2**
## Motivation

We want to fix a recently introduced regression in Zebra's initial sync performance.

Close https://github.com/ZcashFoundation/zebra/issues/9939.

## Solution

- Adds a `finished_format_upgrades` field on `DiskDb` to mark when there are no db format upgrades that are being applied or which need to be applied, and
- Updates `ZebraDb::write_block()` to insert updated address balances instead of merging address balance updates into database values

### Tests

These changes need manual testing to check that:
- [x] Zebra behaves as expected when syncing blocks during a db format upgrade, and
- [x] Zebra's initial sync performance has been restored to what it was before it started using merge operations

### Follow-up Work

We can further improve Zebra's initial sync performance by updating note commitment trees in parallel to writing blocks to the database, see https://github.com/ZcashFoundation/zebra/pull/9958 for more details.

We can also improve the `copy-state` command's performance by copying blocks in batches (or otherwise committing more blocks before verifying that their parents have been committed). See https://github.com/ZcashFoundation/zebra/pull/9958 for more details.

### PR Checklist

- [x] The PR name is suitable for the release notes.
- [x] The PR follows the [contribution guidelines](https://github.com/ZcashFoundation/zebra/blob/main/CONTRIBUTING.md).
- [x] The library crate changelogs are up to date.
- [x] The solution is tested.
- [x] The documentation is up to date.

### CODE REVIEW

**Comment by arya2** [comment]
Running [full sync test here](https://github.com/ZcashFoundation/zebra/actions/runs/18362392389) and locally.

**Comment by arya2** [comment]
Local full sync finished in 8 hours 29 minutes.

(using a lookahead limit of 1000, it may be relevant that it's a little more than the 400 needed to verify a checkpoint)

File: zebra-state/src/service/finalized_state/disk_format/transparent.rs [hunk 1]
```diff
@@ -212,6 +212,38 @@ impl<C: Constraint + Copy + std::fmt::Debug> AddressBalanceLocationInner<C> {
...
+        &mut self,
+        unspent_output: &transparent::Output,
+    ) -> Result<(), amount::Error> {
+        self.balance = (self
+            .balance
+            .zatoshis()
+            .checked_add(unspent_output.value().zatoshis()))
+        .expect("adding two Amounts is always within an i64")
+        .try_into()?;
+        self.received = self.received.saturating_add(unspent_output.value().into());
```
Comment (upbqdn) [inline zebra-state/src/service/finalized_state/disk_format/transparent.rs:228]: Let's go with `checked_add` here as well.

File: zebra-state/src/service/finalized_state/disk_format/transparent.rs [hunk 2]
```diff
@@ -212,6 +212,38 @@ impl<C: Constraint + Copy + std::fmt::Debug> AddressBalanceLocationInner<C> {
...
+    #[allow(clippy::unwrap_in_result)]
+    pub fn receive_output(
+        &mut self,
+        unspent_output: &transparent::Output,
+    ) -> Result<(), amount::Error> {
+        self.balance = (self
+            .balance
+            .zatoshis()
+            .checked_add(unspent_output.value().zatoshis()))
+        .expect("adding two Amounts is always within an i64")
```
Comment (upbqdn) [inline zebra-state/src/service/finalized_state/disk_format/transparent.rs]:
```suggestion
        .expect("ops handling taddr balances must not overflow")
```

File: zebra-state/src/service/finalized_state/disk_format/transparent.rs [hunk 3]
```diff
@@ -212,6 +212,38 @@ impl<C: Constraint + Copy + std::fmt::Debug> AddressBalanceLocationInner<C> {
...
+    #[allow(clippy::unwrap_in_result)]
+    pub fn spend_output(
+        &mut self,
+        spent_output: &transparent::Output,
+    ) -> Result<(), amount::Error> {
+        self.balance = (self
+            .balance
+            .zatoshis()
+            .checked_sub(spent_output.value().zatoshis()))
+        .expect("subtracting two Amounts is always within an i64")
```
Comment (upbqdn) [inline zebra-state/src/service/finalized_state/disk_format/transparent.rs]:
```suggestion
        .expect("ops handling taddr balances must not underflow")
```

File: zebra-state/src/service/finalized_state/disk_format/transparent.rs (hunk 1 above)
Comment (arya2) [reply zebra-state/src/service/finalized_state/disk_format/transparent.rs:228]: I think `saturating_add()` is better here, because we can't expect the received amount not to overflow. We could handle it differently, e.g. use floating point values or set it to `None` when it overflows to indicate that the value is not known.

File: zebra-state/src/service/finalized_state/zebra_db/block.rs [hunk 4]
```diff
@@ -517,18 +517,26 @@ impl ZebraDb {
...
+
+        let address_balances: AddressBalanceLocationUpdates = if self.finished_format_upgrades() {
+            AddressBalanceLocationUpdates::Insert(read_addr_locs(changed_addresses, |addr| {
+                self.address_balance_location(addr)
+            }))
+        } else {
+            AddressBalanceLocationUpdates::Merge(read_addr_locs(changed_addresses, |addr| {
+                Some(self.address_balance_location(addr)?.into_new_change())
+            }))
+        };
```
Comment (upbqdn) [inline zebra-state/src/service/finalized_state/zebra_db/block.rs:549]: Could you add docs describing why we use `Insert` when `finished_format_upgrades` returns `true` and `Merge` otherwise?

File: zebra-state/src/service/finalized_state/zebra_db/transparent.rs [hunk 5]
```diff
@@ -511,15 +512,45 @@ impl DiskWriteBatch {
                 // - create the balance for the address, if needed.
                 // - create or fetch the link from the address to the AddressLocation
                 //   (the first location of the address in the chain).
-                let address_balance_location = address_balances
-                    .entry(receiving_address)
-                    .or_insert_with(|| AddressBalanceLocationChange::new(*new_output_location));
-                let receiving_address_location = address_balance_location.address_location();
+
+                #[inline]
```
Comment (upbqdn) [inline zebra-state/src/service/finalized_state/zebra_db/transparent.rs]: This is a private and generic fn, so it'll most likely get inlined anyway: https://matklad.github.io/2021/07/09/inline-in-rust.html.

File: zebra-state/src/service/finalized_state/zebra_db/transparent.rs [hunk 6]
```diff
@@ -582,20 +613,41 @@ impl DiskWriteBatch {
...
             if let Some(sending_address) = sending_address {
-                let address_balance_location = address_balances
-                    .get_mut(&sending_address)
-                    .expect("spent outputs must already have an address balance");
-
-                // Update the address balance by subtracting this UTXO's value, in memory.
-                address_balance_location
-                    .spend_output(spent_output)
-                    .expect("balance underflow already checked");
+                #[inline]
```
Comment (upbqdn) [inline zebra-state/src/service/finalized_state/zebra_db/transparent.rs]: Same as above.

File: zebra-state/src/service/finalized_state/zebra_db/transparent.rs (hunk 5 above)
Comment (arya2) [reply zebra-state/src/service/finalized_state/zebra_db/transparent.rs]: > There’s [a joke](https://twitter.com/ManishEarth/status/936084757212946432) that LLVM’s heuristic for when the function should be inlined is “yes”.

Got it 🤣

File: zebra-state/src/service/finalized_state/zebra_db/block.rs [hunk 7]
```diff
@@ -517,18 +517,26 @@ impl ZebraDb {
...
-                    Some((address.clone(), addr_loc))
-                })
-                .collect();
+                .filter_map(|address| Some((address.clone(), f(&address)?)))
+                .collect()
+        }
+
+        let address_balances: AddressBalanceLocationUpdates = if self.finished_format_upgrades() {
+            AddressBalanceLocationUpdates::Insert(read_addr_locs(changed_addresses, |addr| {
+                self.address_balance_location(addr)
```
Comment (upbqdn) [inline zebra-state/src/service/finalized_state/zebra_db/block.rs:543]: This will iterate over `changed_addresses`, which may include addresses from `finalized`, which won't be seen by `self.address_balance_location`. I'm trying to figure out the consequences of that.

Comment (upbqdn) [reply zebra-state/src/service/finalized_state/zebra_db/block.rs:543]: I think it's a bug. I'm still trying to wrap my head around the whole stack that commits transparent data.

Comment (arya2) [reply zebra-state/src/service/finalized_state/zebra_db/block.rs:543]: If I understand correctly, there shouldn't be any problematic consequences, addresses which are in `finalized` but not in the database won't be added to the hashmap here, but will be initialized when receiving outputs in [`prepare_new_transparent_outputs_batch()` here](https://github.com/ZcashFoundation/zebra/blob/fix-perf-regression/zebra-state/src/service/finalized_state/zebra_db/transparent.rs#L527).

Comment (upbqdn) [reply zebra-state/src/service/finalized_state/zebra_db/block.rs:543]: Here? https://github.com/zcashfoundation/zebra/blob/188668168828648abb20d32f6c78c37ee4204d5a/zebra-state/src/service/finalized_state/zebra_db/transparent.rs#L528

Comment (upbqdn) [reply zebra-state/src/service/finalized_state/zebra_db/block.rs:543]: Oh, I forgot to click on the link. :D We posted the same one.

Comment (upbqdn) [reply zebra-state/src/service/finalized_state/zebra_db/block.rs:543]: The `changed_addresses` set is not used anywhere else, so including the addresses from `finalized` seems confusing and superfluous. I'll be happy to fix that in a subsequent PR.

**Review by upbqdn — APPROVED** [review]
All looks great!
