### PR TITLE
Fix sync algorithm.

### LINKED ISSUE #888: Configure resource limits on sled
Sled has a mode that selects whether to prioritize small space or high write throughput: https://docs.rs/sled/0.34.2/sled/enum.Mode.html and a setting for the maximum cache size: https://docs.rs/sled/0.34.2/sled/struct.Config.html#method.cache_capacity

We should 

- [ ] Hardcode a configuration asking sled to save space, since we write infrequently.
- [ ] Surface a configuration option that sets the cache capacity (since this makes sense for users to configure).

### PR DESCRIPTION
**Pull request by hdevalence**
Changes the sync algorithm in a few ways:

1.  We handle errors by discarding all of the prospective tips and restarting from the current verified state.  This discards the joinhandles for all of the spawned tasks, letting them run to completion and ignoring the results.

2.  This means that we have to handle cancelations in the checkpoint verifier, which we do by rejecting the *older* of duplicate verification results.  When a duplicate verification request arrives in the checkpoint verifier, we replace the old sender handle with the new one and send an error to the old handle.  If there are orphaned tasks waiting on verification, they'll error out and terminate when this happens.

3.  The sync algorithm now treats a tip as a *pair* of hashes rather than a single hash.  Rather than taking the last hash in the returned list as the new tip, we take the last two, treat the second-to-last as the new tip, and the last hash as an expected next hash. This lets us detect when a peer is extending our tip or when they're feeding us garbage.  (If they feed us *crafted* garbage, they can of course lead us in the wrong direction.  But because we don't rely on a single peer, we'll start working on both the bad and good tips, and hopefully get further along on the good tips before we restart on error).

Also closes #888 to add a memory limit to sled.

The sync algorithm is now different from the one described in the design document, so it should be updated, but I think that that could be a follow-on PR after this one is merged and we don't think we'll be making further changes to it.

With these changes I'm able to get Zebra to successfully checkpoint-sync up to at least 850,000 blocks in about an hour:
Screenshot from 2020-08-12 14-11-34

Looking at the metrics from the connection pool, it looks like for a lot of that period we're not fully saturating the connection pool, so we could potentially be going faster:
Screenshot from 2020-08-12 14-14-09

Zooming in on part of the sync metrics, we can see that there are some periods where no new blocks are being fed into the checkpointer and new blocks are not being downloaded.  I believe that this is caused by a situation where an early block failed to download, we're waiting for it to time out to retry, and we've hit the lookahead limit so we can't start fetching new blocks.  Increasing the lookahead limit might help improve speed here by letting the rest of the block downloads continue:
Screenshot from 2020-08-12 14-15-38

### CODE REVIEW

File: zebra-consensus/src/checkpoint.rs [hunk 1]
```diff
@@ -412,6 +412,18 @@ impl CheckpointVerifier {
             .entry(height)
             .or_insert_with(|| QueuedBlockList::with_capacity(1));
 
+        let hash = block.as_ref().into();
```
Comment (teor2345) [inline zebra-consensus/src/checkpoint.rs]: We have a convenience method now:
```suggestion
        let hash = block.hash();
```

File: zebra-consensus/src/checkpoint.rs [hunk 2]
```diff
@@ -412,6 +412,18 @@ impl CheckpointVerifier {
...
+
+        for qb in qblocks.iter_mut() {
+            if qb.hash == hash {
+                let old_tx = std::mem::replace(&mut qb.tx, tx);
+                let e = "rejected older of duplicate verification requests".into();
+                tracing::warn!(?e);
```
Comment (teor2345) [inline zebra-consensus/src/checkpoint.rs]: Question: Is a warn-level message appropriate here?

I don't think the syncer can guarantee that we won't have any duplicate blocks, because it might download duplicates after we restart and discard state. So let's info or debug instead.

**Review by teor2345 — COMMENTED** [review]
Looks good so far, thanks!

File: zebra-consensus/src/checkpoint.rs (hunk 2 above)
Comment (hdevalence) [reply zebra-consensus/src/checkpoint.rs]: Yes, debug would be better, I'll change this in a fixup commit.

File: zebra-consensus/src/checkpoint.rs (hunk 1 above)
Comment (hdevalence) [reply zebra-consensus/src/checkpoint.rs]: :+1:, will add a fixup.

**Comment by hdevalence** [comment]
This is still a WIP and it still breaks down but it works much better now, able to do sustained download and verification of about 300 blocks per second:
image

I suspect that the correct fix for the syncer confusion would be to define a tip as a pair of hashes, sending requests starting from the first item of the pair, and checking that the head of the response is the second item of the pair.

**Comment by teor2345** [comment]
> I suspect that the correct fix for the syncer confusion would be to define a tip as a pair of hashes, sending requests starting from the first item of the pair, and checking that the head of the response is the second item of the pair.

That sounds about right for the ExtendTips case. I had thought of something like pairs of hashes, but I hadn't worked out how to implement it in detail.

And ObtainTips can handle side-chains using the existing algorithm, which doesn't check the head of the response.

File: zebrad/src/commands/start/sync.rs [hunk 3]
```diff
@@ -219,27 +212,24 @@ where
...
-                    let unknown_hashes = &hashes[first_unknown..];
+                    let unknown_hashes = if let Some(index) = first_unknown {
+                        &hashes[index..]
+                    } else {
+                        continue;
+                    };
                     let new_tip = *unknown_hashes
                         .last()
-                        .expect("already checked that unknown hashes isn't empty");
+                        .expect("first unknown index < hashes.len() so slice is nonempty");
```
Comment (teor2345) [inline zebrad/src/commands/start/sync.rs]: Issue: enumerate can't return an index that is greater than the length of the iterator.

```suggestion
                        .expect("first unknown exists, so slice is nonempty");
```

File: zebrad/src/commands/start/sync.rs [hunk 4]
```diff
@@ -88,50 +89,60 @@ where
             self.pending_blocks = Box::pin(FuturesUnordered::new());
 
             tracing::info!("starting sync, obtaining new tips");
-            self.obtain_tips().await?;
+            if self.obtain_tips().await.is_err() {
+                tracing::warn!("failed to obtain tips, waiting to restart sync");
+                delay_for(Duration::from_secs(15)).await;
```
Comment (teor2345) [inline zebrad/src/commands/start/sync.rs]: We do this delay in two different places now, should we turn it into a constant?

**Review by teor2345 — DISMISSED** [review]
Looks good!

I really like how everything is more consistent now.

I wish there was a way to automatically keep ObtainTips and ExtendTips deduplication in sync, but I think that would make the code harder to understand. I guess that's a job for the transcript tests or for code reviews.

I had a few minor questions and suggestions, none of them should block.

File: zebrad/src/commands/start/sync.rs [hunk 5]
```diff
@@ -303,9 +303,18 @@ where
...
                             (_, 1) => {
+                                // zcashd might respond with a length-1 inv message if a broadcast of new inventory
+                                // is sent while we're sending our request.
                                 tracing::debug!("skipping length-1 response, in case it's an unsolicited inv message");
                                 continue;
                             }
+                            (_, 501) => {
+                                // zcashd has an ad-hoc buffering mechanism for inv items that can result in a broadcast
+                                // of new inventory getting mixed in to the *body* of a response to a getblocks message,
+                                // but only at the front or rear.
```
Comment (daira) [inline zebrad/src/commands/start/sync.rs]: Wait what? Please file a bug ticket.

File: zebrad/src/commands/start/sync.rs (hunk 3 above)
Comment (hdevalence) [reply zebrad/src/commands/start/sync.rs]: Right, but that invariant (`index < hashes.len()` is why the slice is nonempty, which is why it's in the `.expect` -- the index existing isn't enough, since it could be `Some(index)` with `index > len` and the slice would be empty.  (But this code is removed when changing to pairs of hashes anyways).

File: zebrad/src/commands/start/sync.rs (hunk 4 above)
Comment (hdevalence) [reply zebrad/src/commands/start/sync.rs]: Fixed in `67b415cb9bea207d418142f57fce21aa937b572d`.

**Review by yaahc — DISMISSED** [review]

**Review by yaahc — COMMENTED** [review]
wait, i didn't realize that the last file which contained all the important changes was hidden, still reviewing

File: zebrad/src/commands/start/sync.rs [hunk 6]
```diff
@@ -77,61 +92,75 @@ where
         // due to protocol limitations
         self.request_genesis().await?;
 
-        loop {
-            self.obtain_tips().await?;
+        'sync: loop {
```
Comment (yaahc) [inline zebrad/src/commands/start/sync.rs:95]: oh damn, we getting serious over here

File: zebrad/src/commands/start/sync.rs [hunk 7]
```diff
@@ -77,61 +92,75 @@ where
...
-            //
-            // If there are any prospective tips, call ExtendTips.
-            // Continue this step until there are no more prospective tips.
             while !self.prospective_tips.is_empty() {
-                tracing::debug!("extending prospective tips");
-
-                self.extend_tips().await?;
-                self.update_metrics();
+                // Check whether any block tasks are currently ready:
+                while let Some(Some(rsp)) = self.pending_blocks.next().now_or_never() {
```
Comment (yaahc) [inline zebrad/src/commands/start/sync.rs:110]: now_or_never??? what is this and where is it defined? (curiousity based question, not worried about it)

**Review by yaahc — APPROVED** [review]
looks good, for real this time

File: zebrad/src/commands/start/sync.rs (hunk 7 above)
Comment (hdevalence) [reply zebrad/src/commands/start/sync.rs:110]: it's in futures::future::FutureExt

Comment (yaahc) [reply zebrad/src/commands/start/sync.rs:110]: sick

File: zebrad/src/commands/start/sync.rs (hunk 6 above)
Comment (teor2345) [reply zebrad/src/commands/start/sync.rs:95]: When I saw this I thought "oh no, goto".

Comment (hdevalence) [reply zebrad/src/commands/start/sync.rs:95]: 😅

**Comment by teor2345** [comment]
I didn't get a chance to review these changes before they merged, so I added some potential issues to the sync tracking issue #884.
